### ISSUE TITLE
Search does not work when package name has special characters

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1015]
[Andre Robatino reported this issue](https://bugzilla.redhat.com/show_bug.cgi?id=1304119):

> Description of problem:
> If I do a search for "memtest86+" at https://bodhi.fedoraproject.org , no results are returned, even
> though memtest86+ is listed as one of the matching packages before entering. The search result
> should include https://bodhi.fedoraproject.org/updates/FEDORA-2016-1a840cc07e , for example.
> 
> How reproducible:
> always
> 
> Steps to Reproduce:
> 1. Search for "memtest86+".
> 
> Actual results:
> No results.
> 
> Expected results:
> At least one result.

**Comment by ryanlerch** [comment]
Unable to recreate this one, searching for "memtest86+" on the web UI on does return results as expected.

**Comment by robatino** [comment]
Still broken for me. Entering "memtest+" in the search box at https://bodhi.fedoraproject.org returns no results, the same result if I go directly to https://bodhi.fedoraproject.org/updates/?packages=memtest86+ . Immediately after typing "memtest86+", it DOES show a memtest86+ entry as a package, but even if you select that, it then gives no search results.

**Comment by robatino** [comment]
I just noticed that after typing "memtest86+", it not only shows "memtest86+" as a result, but also specific versions (but only after a long delay), and if you select one of those, THEN you get the page for that specific version. I didn't wait long enough to see them before. In any case, it's still broken in that you should be able to see all memtest86+ versions simultaneously by either clicking on "memtest86+" or going to https://bodhi.fedoraproject.org/updates/?packages=memtest86+ , and THAT link doesn't work.

**Comment by robatino** [comment]
It works for any package without special characters. For example, if you enter "kernel", you'll initially see three package names with "kernel" in them, including "kernel". If you wait around 30 seconds, you'll see specific kernel versions as well. If you don't wait, but immediately select "kernel" and hit enter, you see the bodhi page https://bodhi.fedoraproject.org/updates/?packages=kernel showing all kernel versions.

**Comment by ryanlerch** [comment]
Thanks for the Additional Information. 

The issue here is specifically with the query page, and the fact that the + is not escaped properly. The Search box itself is returning proper results. The following page is probably what we need to escape this to:

https://bodhi.fedoraproject.org/updates/?packages=memtest86%2B
