### ISSUE TITLE
Reminder email script adds comments that include the number of elapsed days

### ISSUE THREAD

**Issue by richardfearn** [fedora-infra/bodhi#1017]
When #1009 was fixed, I started getting Bodhi reminder emails for updates that passed the minimum number of days in testing some time ago.

Consider this update (chosen more or less at random):

https://bodhi.fedoraproject.org/updates/FEDORA-2016-c22fffe3da

It's an F24 update, so only needed to spend 7 days in testing. It entered testing on 2016-09-29, so the 7 days ended on 2016-10-06, and as of now (2016-10-08) it's been in testing for 9 days.

Due to #1009, the reminder comment was only added this morning (2016-10-08). Notice that it says "9 days", whereas "7 days" would have been more correct (that's the requirement for F24).

In case the script ever stops working again, and needs to 'catch up' with old updates, I think the code needs to change from:

```
text = config.get('testing_approval_msg') % update.days_in_testing
```

to:

```
text = config.get('testing_approval_msg') % update.release.mandatory_days_in_testing
```

so that the comment reflects the requirements for the Fedora release, rather than the time so far that the update has spent in testing.

**Comment by bowlofeggs** [comment]
Great suggestion, thanks for the report! Since you've basically written the code, care to send in a PR? I'm gonna mark this easy fix since the patch is pretty much here and I think it's the right change.

**Comment by richardfearn** [comment]
Sure - I'll do that later.
