### ISSUE TITLE
We need to de-duplicate the code that sets up database connections

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1028]
Code [like this](https://github.com/fedora-infra/bodhi/blob/2.2.4/bodhi/server/scripts/approve_testing.py#L46-L50) appears in various places in the code base, as well as in the tests:

```
    settings = get_appsettings(config_uri)
    engine = engine_from_config(settings, 'sqlalchemy.')
    Session = scoped_session(sessionmaker(extension=ZopeTransactionExtension()))
    Session.configure(bind=engine)
    db = Session()
```

We should have a utility function that creates database connections/sessions and return them. Then the various places in the code that need connections can get them from the new utility function, and the tests can mock the utility function to force the testing database to be used during testing.

[There is some code that's close to what we need](https://github.com/fedora-infra/bodhi/blob/2.2.4/bodhi/server/__init__.py#L45-L64), but it is currently request/response focused. We should pull the db building out into a more general utility function that everything else can use and have this existing function wrap it for requests.

This will simplify some code, deduplicate, and will improve our test framework.

**Comment by jeremycline** [comment]
I think this is no longer relevant since the database code was refactored
