### ISSUE TITLE
bodhi.server.models.models.Update.stable_karma should disallow NULL values

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1029]
Many of our columns have this problem, but the stable_karma in particular should disallow NULL values and require the column to always be explicitly True or False. Since it allows NULL, there are all kinds of checks in the code that look like `stable_karma not in (0, None)`. As it is, there is possibility of new code forgetting about the two possible "Falsy" values. It's better for the database to be opinionated.

Of course, we will also need to write a migration to set stable_karma to False where it is None and then convert the column to be non-nullable. Due to the migration, I am not marking this as an easy fix (even though it probably actually is).

**Comment by sebwoj** [comment]
Based on:
https://github.com/fedora-infra/bodhi/blob/a1a3cdd4089acd3e2477d5375f01e211585a5711/bodhi/server/schemas.py#L234
Can we drop False/True/None values and assume that db stable_karma value should be INT and not None?

**Comment by bowlofeggs** [comment]
@sebwoj yeah that's the proposal - we should enforce ```stable_karma``` being an ```int``` everywhere.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: https://github.com/fedora-infra/bodhi/pull/3221
