### ISSUE TITLE
inserts "--RAW HTML NOT ALLOWED--" instead of simply encoding with html entities

### ISSUE THREAD

**Issue by pliadanni** [fedora-infra/bodhi#1031]
bodhi doesn't allow e.g. `<i>some text</i>` or `<b>some text</b>` to be inserted into a comment _as plain text_.

see the following 2 comments:
[(link)](https://bodhi.fedoraproject.org/updates/atril-1.16.0-1.fc24%20caja-1.16.0-1.fc24%20caja-extensions-1.16.0-1.fc24%20engrampa-1.16.0-1.fc24%20eom-1.16.0-1.fc24%20libmatekbd-1.16.0-1.fc24%20libmatemixer-1.16.0-1.fc24%20libmateweather-1.16.0-1.fc24%20marco-1.16.0-1.fc24%20mate-applets-1.16.0-1.fc24%20mate-backgrounds-1.16.0-1.fc24%20mate-common-1.16.0-1.fc24%20mate-control-center-1.16.0-1.fc24%20mate-desktop-1.16.0-1.fc24%20mate-icon-theme-1.16.0-1.fc24%20mate-icon-theme-faenza-1.16.0-1.fc24%20mate-media-1.16.0-1.fc24%20mate-menus-1.16.0-1.fc24%20mate-notification-daemon-1.16.0-1.fc24%20mate-panel-1.16.0-1.fc24%20mate-polkit-1.16.0-1.fc24%20mate-power-manager-1.16.0-1.fc24%20mate-screensaver-1.16.0-1.fc24%20mate-sensors-applet-1.16.0-1.fc24%20mate-session-manager-1.16.0-1.fc24%20mate-settings-daemon-1.16.0-1.fc24%20mate-system-monitor-1.16.0-1.fc24%20mate-terminal-1.16.0-1.fc24%20mate-user-guide-1.16.0-1.fc24%20mate-utils-1.16.0-1.fc24%20mozo-1.16.0-1.fc24%20pluma-1.16.0-1.fc24%20python-caja-1.16.0-1.fc24#comment-507536)

In the first of these two comments, I noticed in the preview that it wasn't going to allow the tags (which I only intended to show as plain text), but I found that I could work around the issue by inserting zero-width spaces. However, the second of these comments shows the problem I'm describing, as I did not insert the zero-width spaces (so that I could confirm that the output would be affected in the same way as the preview showed, and indeed it was).

instead of stripping the tags (which can easily be overlooked, and which is a pain regardless), bodhi should html encode them so that they are displayed harmlessly as plain text.

**Comment by ryanlerch** [comment]
we now use python-bleach (PR #1560 ) to sanitize the comment markdown input. Bleach escapes the html entities, rather than inserting the Raw HTML not allowed message.
