### ISSUE TITLE
All my new updates are filed with autokarma enabled even though I unchecked the checkbox

### ISSUE THREAD

**Issue by kkofler** [fedora-infra/bodhi#1032]
Whenever I file a new update, even if I uncheck the autokarma checkbox, the update is filed with autokarma enabled. I have read issue #999, which claims that this is just a display thing:

> With the 2.2.0 release, all updates have karma thresholds displayed, whether or not autopush is enabled.

but I cannot confirm this: When I edit the update, the checkbox is on! If I then uncheck the checkbox and confirm the edit, the thresholds vanish, and any further edits will no longer show autokarma as enabled.

(Note that the thresholds vanishing when I edit updates to disable autokarma also means that the improvement from issue #772 (manual push to stable based on karma) does not work, so I am filing a new issue for that.)

**Comment by kkofler** [comment]
> If I then uncheck the checkbox and confirm the edit, the thresholds vanish, and any further edits will no longer show autokarma as enabled.
> 
> (Note that the thresholds vanishing when I edit updates to disable autokarma also means that the improvement from issue #772 (manual push to stable based on karma) does not work, so I am filing a new issue for that.)

This is now issue #1033.

**Comment by bowlofeggs** [comment]
This sounds like it is likely a UI issue, either in rendering or processing the form (or both). I know that updates have been successfully using non-autokarma updates with manual push thresholds based on karma. For example, this is how all recent kernel updates have been working. My guess is that they may be using the bodhi CLI to do this, so that might be a workaround for you.

**Comment by trishnaguha** [comment]
We have a PR #1027 which will display whether `Autopush` is enabled or disabled on the update page. This might be a solution for the confusion.

**Comment by kkofler** [comment]
Have you actually read the bug description? This is **not** a display issue, it is an issue in the form that files the update. Try editing the update and the autokarma flag is set! Only if you click Edit, uncheck the flag and save the changes, it unsets the flag (as shown if you click on Edit again).

**Comment by kkofler** [comment]
That pull request cannot possibly fix this bug.

I file an update with autokarma unchecked, I edit it, autokarma is checked. So either the filing form does not save the flag correctly or the editing form does not load it correctly. I think it is the former, because when I unset it in the editing form and OK that, the next editing form shows it unchecked.

How can your fix for the display field possibly fix this?

**Comment by bowlofeggs** [comment]
@kkofler I agree, I had failed to notice that the commit message claimed to close this bug. Apologies!

I do think the display field is a nice addition though, and makes it clearer what should be expected of updates since most users can't see if the autokarma is enabled or not.

**Comment by kkofler** [comment]
Why is this dangerous bug (which can lead to broken packages accidentally reaching the stable updates) still not fixed after 2 months?

**Comment by kkofler** [comment]
Actually, it turns out that this apparent bug was just an illusion. It is really the **combination** of bug #999 and bug #1308. Bug #999 alone would not have explained it, but bug #1308 in addition is what made it look as if the autokarma had never been correctly disabled. As long as I don't edit the update, the autopush stays disabled (as is now visible due to the fix to bug #999).
