### ISSUE TITLE
Bodhi should inform about freeze

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1038]
[Miro Hrončok reported this issue in Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1026321)

> Description of problem:
> When there is any freeze that prevents the update to be pushed in stable, bodhi should inform about > that.
> 
> Steps to Reproduce:
> 1. While there is a freeze, mark an update as stable
> 
> Actual results:
> Bodhi says:
> This update has been submitted for stable by $USERNAME. 
> 
> But the update is not pushed, because of the freeze. When the user doesn't know about the freeze,
> (s)he is confused.
> 
> Expected results:
> Bodhi says:
> This update has been submitted for stable by $USERNAME.
> There is an ongoing freeze, this will be pushed to stable after the freeze is over. $LINK_TO_WIKI

**Comment by ryanlerch** [comment]
Just a few questions on this one.

1. Does the push from testing to stable get done automatically? or is this something that is done only by a person using this procedure -- https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/bodhi.html#pushing-updates

2. Does bodhi have any knowledge of if a release is currently in a freeze? I couldn't find any references to this in the codebase. If bodhi doesn't have any knowledge, is there an external tool that can be queried to get this information, or will we need to add new fields and store this in Bodhi?

**Comment by ryanlerch** [comment]
It would also be nice to have some sort of notification or label or something on this page if a release is in Freeze too:

https://bodhi.fedoraproject.org/releases/F26

**Comment by bowlofeggs** [comment]
On Tue, 2017-06-06 at 22:55 -0700, Ryan Lerch wrote:
> Does the push from testing to stable get done automatically? or is
> this something that is done only by a person using this procedure --
> https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-
> guide/sops/bodhi.html#pushing-updates

I believe it is done by a person and not by Bodhi.

> Does bodhi have any knowledge of if a release is currently in a
> freeze? I couldn't find any references to this in the codebase. If
> bodhi doesn't have any knowledge, is there an external tool that can
> be queried to get this information, or will we need to add new fields
> and store this in Bodhi?

Bodhi doesn't currently have knowledge of the freeze, though there
would be obvious benefits to teaching it about them. I think Product
Definition Center might be able to help with this in the future? Not
sure.

**Comment by hroncok** [comment]
Any update here? People are confused.

```
(11:59:12) mrunge: mhroncok, hey, any idea what happened here? https://bodhi.fedoraproject.org/updates/FEDORA-2018-6f9dc1dd66
(11:59:27) mrunge: package submitted to stable and still on testing in bodhi?
(12:00:15) mrunge: ... like bodhi stopped working in the middle of the transaction
```

**Comment by hroncok** [comment]
People are still confused.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4ANRTWYWRXDGDTIZUXBKCTANML22AA4W/
