### ISSUE TITLE
EPEL 7 pushes?

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#1047]
Hi!

Is there something wrong with EPEL 7? There hasn't been a push to neither testing nor stable for a week now, not even failed attempts as far as I can see.

**Comment by bowlofeggs** [comment]
Hello @ellert! Thanks for the report. I believe that EPEL 7 hasn't had a push on purpose for a while while release engineering bootstraps aarch64 there. Apologies for the delay, but it's a purposeful "outage". You can read about it on this thread:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MCYKJB4YBHRFNWLVFQ3RKSHN6XX57YZQ/

Hope that helps!
