### ISSUE TITLE
[RFE] Expire overrides using CLI.

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#1049]
It seems it is not possible to expire override using CLI. The web UI seems to be the only option ATM. Please consider adding this feature.

```
$ rpm -q bodhi-client
bodhi-client-2.2.4-1.fc26.noarch
```

I noted this originally here:

https://bugzilla.redhat.com/show_bug.cgi?id=1366114#c6

**Comment by bowlofeggs** [comment]
I marked this high priority since it sounds like it is a feature regression since the 0.9 client.
