### ISSUE TITLE
Use faitout's correct URL in the unit tests

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1053]
@pypingou pointed out that we could use faitout by a domain name instead of address. We could change

```
FAITOUT = 'http://209.132.184.152/faitout/
```

to

```
http://faitout.fedorainfracloud.org/
```

In general, we do want the unit tests to work when run on an isolated network so that they will pass when run in the spec file on Koji. However if we can use an environment variable to detect that we are in Jenkins, I think it would be cool to use faitout.

**Comment by pypingou** [comment]
In pagure we use the environment variable `BUILD_ID` to detect if we're in jenkins or not: https://pagure.io/pagure/blob/master/f/tests/__init__.py#_49-61

In case of glitches, the code falls back to sqlite to keep things running :)

**Comment by bowlofeggs** [comment]
Bodhi's integration tests now launch their own instance of PostgreSQL, so we don't need to use faitout anymore.
