### ISSUE TITLE
Remove from models import * from bodhi.server.models.__init__

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1057]
We should stop the `from thing import *` pattern, and one particular place it's being used is in `bodhi.server.models.__init__`. To fix this issue, we should remove that line and choose between these two options:
1. Fix all the things that import from the `__init__.py`.
2. Rename models.py to `__init__.py`

I personally prefer the first option, but welcome discussion about the second.

**Comment by ankit01ojha** [comment]
Is second option will be correct?

**Comment by bowlofeggs** [comment]
Neither option is more correct than the other. It's a matter of preference. Some people dislike when Python package `__init__.py` files contain significant code. I personally feel that way, but I can't make any technical argument as to why. It just feels less clean to me. However, that's just a personal preference and I don't want to force my preferences onto others ☺ The second option is certainly easier ☺

**Comment by trishnaguha** [comment]
IMO **first** one would be better choice. It is good to have `DB model` inside `models.py` only :)

**Comment by bowlofeggs** [comment]
I think I agree with @trishnaguha. It is always a little surprising when projects put lots of code in `__init__.py` files.

There is a third option which might be nice: we could get rid of the `bodhi.server.models` package and replace it with a `bodhi.server.models` module. The only other thing in the models package is the `enum.py`. That could just become `bodhi.server.enum`, or it might make sense to just be in `bodhi.server.models`. Either way I think would be cleaner than `from bodhi.server.models import models` which is pretty strange if you ask me ☺

**Comment by trishnaguha** [comment]
+1 to replace `bodhi.server.models` package with `bodhi.server.models` module and `enum.py` with `bodhi.server.enum` . This sounds even better :-).
Any of the first or third sounds good to me :).

**Comment by bowlofeggs** [comment]
@trishnaguha Actually I had proposed just putting the enum stuff inside `bodhi.server.models`, but we could make enum its own thing too. Since it's part of bodhi.server.models now I figured it made sense to keep it there. It is used by the models extensively, so I think it makes sense to be part of them.

**Comment by trishnaguha** [comment]
Fair :)

**Comment by ankit01ojha** [comment]
Can you please tell me now  what basically I have to do with enum.py?

**Comment by ankit01ojha** [comment]
Can you please tell me now  what basically I have to do with enum.py?

**Comment by ankit01ojha** [comment]
Do I have to put this code from bodhi.server.models import models in place of from models import * .
