### ISSUE TITLE
Bodhi is using a transaction manager around fedmsg which may not be neccesary

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1078]
It may be possible to drop this code:

https://github.com/fedora-infra/bodhi/blob/2.3.1/bodhi/server/notifications.py#L82-L200

@puiterwijk suggested that this code is meant to work around fedmsg not handling threads well, but it is believed that fedmsg is well capable of working within threads. We should double check that, and if it is safe we should drop that code and fix whatever was using it to use fedmsg directly.

**Comment by jeremycline** [comment]
I don't think this is relevant anymore since we dropped transaction
