### ISSUE TITLE
Bodhi should release its lock on updates on mashing failures

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#1093]
When a push is started, the updates in the push are locked so they can not be modified while the push is in progress. When the push is completed, the updates in the push are released and changes can again be made. However, if the push fails the lock is not released and the updates remain locked until the next push is attempted, which often is a day or more later. This means that the updates are locked blocking changes to them for a long time for no reason (at least no apparent reason).

**Comment by ellert** [comment]
Still happening - still very disruptive.

**Comment by bowlofeggs** [comment]
The lock is used to determine which builds are part of a compose, so there is a reason for it.
