### ISSUE TITLE
bodhi resume push spews full updates details rather than just a list of NVRs

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#1113]
So when you use to resume a bodhi push it use to just provide a list of NVR updates just like when doing a new push. Now you get a list of the full output. Sample included below. It's too verbose and doesn't really provide useful output you can browse over to see if it looks sane.

<pre>
================================================================================
     cinnamon-translations-3.2.0-1.fc24 cinnamon-3.2.1-1.fc24 nemo-
     extensions-3.2.0-1.fc24 nemo-3.2.0-1.fc24 cinnamon-control-
     center-3.2.0-1.fc24 muffin-3.2.0-1.fc24 cinnamon-session-3.2.0-1.fc24
     cinnamon-settings-daemon-3.2.0-1.fc24 cinnamon-screensaver-3.2.0-2.fc24
     cinnamon-menus-3.2.0-1.fc24 cinnamon-desktop-3.2.0-3.fc24
     xapps-1.0.2-1.fc24 cjs-3.2.0-1.fc24
================================================================================
  Update ID: FEDORA-2016-a3e0d84cac
    Release: Fedora 24
     Status: pending
       Type: enhancement
      Karma: 0
    Request: testing
      Notes: Cinnamon-3.2.x update  - Input driver switched from synaptics to
           : libinput.
  Submitter: leigh123linux
  Submitted: 2016-11-15 15:39:45.321725
   Comments: bodhi - 2016-11-15 15:39:45.445701 (karma 0)
             This update has been submitted for testing by
             leigh123linux.

  https://bodhi.fedoraproject.org/updates/FEDORA-2016-a3e0d84cac

================================================================================
     openvas-scanner-5.0.7-1.fc24
================================================================================
  Update ID: FEDORA-2016-1212611d92
    Release: Fedora 24
     Status: pending
       Type: enhancement
      Karma: 0
    Request: testing
      Notes: Bugfix release 5.0.7
  Submitter: rebus
  Submitted: 2016-11-15 15:49:31.789280
   Comments: bodhi - 2016-11-15 15:49:31.821316 (karma 0)
             This update has been submitted for testing by rebus.

  https://bodhi.fedoraproject.org/updates/FEDORA-2016-1212611d92

================================================================================
     erlang-lager-3.2.4-1.fc24
================================================================================
  Update ID: FEDORA-2016-893e84257f
    Release: Fedora 24
     Status: pending
       Type: enhancement
      Karma: 0
    Request: testing
       Bugs: 1378633 - erlang-lager-3.2.4 is available
      Notes: * Ver. 3.2.4
  Submitter: peter
  Submitted: 2016-11-15 16:00:21.990581
   Comments: bodhi - 2016-11-15 16:00:22.005409 (karma 0)
             This update has been submitted for testing by peter.

  https://bodhi.fedoraproject.org/updates/FEDORA-2016-893e84257f

================================================================================
     perl-Crypt-IDEA-1.10-5.fc24
================================================================================
  Update ID: FEDORA-2016-e85db2ba89
    Release: Fedora 24
     Status: pending
       Type: newpackage
      Karma: 0
    Request: testing
       Bugs: 1395121 - Review Request: perl-Crypt-IDEA - Perl interface to IDEA
           : block cipher
      Notes: This is the first Fedora release of perl-Crypt-IDEA. The package is
           : moving from RPM Fusion to Fedora as the IDEA patent
           : expired a few years ago.
  Submitter: pghmcfc
  Submitted: 2016-11-15 16:31:10.134744
   Comments: bodhi - 2016-11-15 16:31:10.458556 (karma 0)
             This update has been submitted for testing by pghmcfc.

  https://bodhi.fedoraproject.org/updates/FEDORA-2016-e85db2ba89

</pre>

**Comment by nullr0ute** [comment]
Oh strangely it then seems to print the whole lot at the end. I had two to resume (24-u-t and 23):

<pre>
================================================================================
     pidgin-groupchat-typing-notifications-0-2.git33a75f9.fc23
================================================================================
  Update ID: FEDORA-2016-f0639c407b
    Release: Fedora 23
     Status: testing
       Type: newpackage
      Karma: 0
    Request: stable
       Bugs: 1392227 - Review Request: pidgin-groupchat-typing-notifications -
           : Adds typing notifications for group chats in Pidgin
      Notes: Small spec fixes.  ----  Initial upload.
  Submitter: xvitaly
  Submitted: 2016-11-07 17:02:19.374737
   Comments: bodhi - 2016-11-07 17:02:19.521718 (karma 0)
             This update has been submitted for testing by xvitaly.
             bodhi - 2016-11-07 17:02:36.204530 (karma 0)
             This update has obsoleted [pidgin-groupchat-typing-not
             ifications-0-1.git33a75f9.fc23](https://bodhi.fedorapr
             oject.org/updates/FEDORA-2016-49e258e3cc), and has
             inherited its bugs and notes.
             bodhi - 2016-11-08 01:30:39.879582 (karma 0)
             This update has been pushed to testing.
             bodhi - 2016-11-15 00:00:54.652583 (karma 0)
             This update has reached 7 days in testing and can be
             pushed to stable now if the maintainer wishes
             bodhi - 2016-11-15 00:05:15.071462 (karma 0)
             This update has been submitted for stable by xvitaly.
  https://bodhi.fedoraproject.org/updates/FEDORA-2016-f0639c407b
plee-the-bear-0.7.0-9.fc24
perl-Date-Extract-0.06-1.fc24
bluedevil-5.8.3-1.fc24 breeze-gtk-5.8.3-1.fc24 grub2-breeze-theme-5.8.3-1.fc24 kactivitymanagerd-5.8.3-1.fc24 kde-cli-tools-5.8.3-1.fc24 kde-gtk-config-5.8.3-1.fc24 kde-settings-24-8.fc24 kdecoration-5.8.3-1.fc24 kdeplasma-addons-5.8.3-1.fc24 kgamma-5.8.3-1.fc24 khotkeys-5.8.3-1.fc24 kinfocenter-5.8.3-1.fc24 kmenuedit-5.8.3-1.fc24 kscreen-5.8.3-1.fc24 kscreenlocker-5.8.3-1.fc24 ksshaskpass-5.8.3-1.fc24 ksysguard-5.8.3-1.fc24 kwayland-integration-5.8.3-1.fc24 kwin-5.8.3-1.fc24 kwrited-5.8.3-1.fc24 libkscreen-qt5-5.8.3-1.fc24 libksysguard-5.8.3-1.fc24 pam-kwallet-5.8.3-1.fc24 plasma-breeze-5.8.3-1.fc24 plasma-desktop-5.8.3-2.fc24 plasma-discover-5.8.3-1.fc24 plasma-integration-5.8.3-1.fc24 plasma-milou-5.8.3-1.fc24 plasma-nm-5.8.3-1.fc24 plasma-oxygen-5.8.3-1.fc24 plasma-pa-5.8.3-1.fc24 plasma-sdk-5.8.3-1.fc24 plasma-systemsettings-5.8.3-1.fc24 plasma-user-manager-5.8.3-1.fc24 plasma-workspace-5.8.3-1.fc24 plasma-workspace-wallpapers-5.8.3-1.fc24 plymouth-theme-breeze-5.8.3-1.fc24 polkit-kde-5.8.3-1.fc24 powerdevil-5.8.3-1.fc24 sddm-kcm-5.8.3-1.fc24
perl-Encode-IMAPUTF7-1.05-2.fc24 perl-Mail-IMAPTalk-4.04-1.fc24
moodle-3.1.3-1.fc24
znc-clientbuffer-0-0.1gitfe0f368.fc24
python-serpy-0.1.1-1.fc24
gimp-focusblur-plugin-3.2.6-1.fc24
php-simplesamlphp-saml2_1-1.10.2-1.fc24 php-simplesamlphp-saml2-2.3.2-1.fc24
kelbt-0.16-2.fc24
meson-0.36.0-1.fc24
sparse-0.5.0-8.fc24
lldb-3.8.0-3.fc24
mbuffer-20160613-1.fc24
moin-1.9.9-1.fc24
python-requestbuilder-0.6.0-1.fc24
ocaml-menhir-20161114-1.fc24
xorg-x11-server-1.18.4-5.fc24
flacon-2.1.0-1.fc24
php-phpunit-PHPUnit-5.6.3-1.fc24 php-sebastian-recursion-context-1.0.4-1.fc24
siege-4.0.2-2.fc24
libdrm-2.4.73-1.fc24
nfoview-1.21-1.fc24
perl-Data-ICal-TimeZone-1.23-1.fc24
ovirt-engine-sdk-python-3.6.9.1-1.fc24
firefox-50.0-1.fc24
sassc-3.3.6-1.fc24
ovirt-engine-cli-3.6.9.2-1.fc24
auter-0.8-1.fc24
ovirt-engine-sdk-java-3.6.10.0-1.fc24
lensfun-0.3.2-3.fc24
libindicator-12.10.1-8.fc24
msmtp-1.6.6-1.fc24
irclog2html-2.15.2-1.fc24
erlang-parse_trans-3.0.0-1.fc24
erlang-setup-1.8.0-1.fc24
ocserv-0.11.6-1.fc24
flmsg-4.0.0-1.fc24
perl-Convert-Base64-0.001-1.fc24
erlang-cuttlefish-2.0.10-1.fc24
cinnamon-translations-3.2.0-1.fc24 cinnamon-3.2.1-1.fc24 nemo-extensions-3.2.0-1.fc24 nemo-3.2.0-1.fc24 cinnamon-control-center-3.2.0-1.fc24 muffin-3.2.0-1.fc24 cinnamon-session-3.2.0-1.fc24 cinnamon-settings-daemon-3.2.0-1.fc24 cinnamon-screensaver-3.2.0-2.fc24 cinnamon-menus-3.2.0-1.fc24 cinnamon-desktop-3.2.0-3.fc24 xapps-1.0.2-1.fc24 cjs-3.2.0-1.fc24
openvas-scanner-5.0.7-1.fc24
erlang-lager-3.2.4-1.fc24
perl-Crypt-IDEA-1.10-5.fc24
nfoview-1.20-1.fc23
php-akamai-open-edgegrid-client-0.6.0-1.fc23
drupal7-i18n-1.14-1.fc23
drupal7-chosen-2.0-1.fc23
drupal7-field_permissions-1.0-1.fc23
php-sentry-0.22.0-1.fc23
prosody-0.9.11-1.fc23
pidgin-groupchat-typing-notifications-0-2.git33a75f9.fc23
Push these 52 updates? (y/n) 
</pre>

**Comment by bowlofeggs** [comment]
Without looking into what is causing this, I'm going to guess it's an easy fix. Possibly a stray print statement…

**Comment by puiterwijk** [comment]
Fix: #1123
