### ISSUE TITLE
rss-feeds should have more speaking titles

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/bodhi#1119]
eg.: https://bodhi.fedoraproject.org/rss/updates/?releases=F24
the feed is named "updates"
maybe it should be renamed to "Fedora XX Released Updates" where XX would be 24,...

**Comment by Peppa-Peddler** [comment]
I want to work on this issue! Can someone assist me?

**Comment by bowlofeggs** [comment]
I'm not very familiar with the code that does this, but the service that generates the update rss feed is here:

https://github.com/fedora-infra/bodhi/blob/2.3.2/bodhi/server/services/updates.py#L157-L316

And the rss renderer is here:

https://github.com/fedora-infra/bodhi/blob/2.3.2/bodhi/server/renderers.py#L8-L71

**Comment by TheIllusionistMirage** [comment]
@bowlofeggs I decided to work on this and follow the Bodhi docs and setup the required environment (using virtualenv). But while trying to run `python setup.py nosetests`, I'm getting an error that required pbr version is at least 1.11 while the actual latest version of pbr seems to be 1.10.x.

Any pointers about why I'm getting this?

**Comment by ghost** [comment]
@cverna there are various parameters on which rss feed for updates can be retrieved (release, severity, submitted_since ...). Can we formulate a standard template for the title for ```updates```, ```comments```, ```users``` and ```overrides```

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/renderers.py#L57-L64

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
