### ISSUE TITLE
Revoke stable request upon AutoQA failure if the stable karma has already been reached

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#116]
Example: https://admin.fedoraproject.org/updates/FEDORA-2014-17194/wget-1.16.1-2.fc20

Upon AutoQA/Taskotron failure, we should revoke the stable request if the stablekarma threshold has already been reached.

**Comment by ralphbean** [comment]
We could do this a couple ways:

- If taskotron published fedmsg messages, we could listen for those in the bodhi backend and make our update then.
- It doesn't publish those yet, so we have to do it somehow else for now, no?  Could we do it at push time?  I.e., jettison the update from the mash if it has taskotron failures?  (I think this is already done..)

**Comment by lmacken** [comment]
Yeah, I think this is all set for bodhi2, but I was thinking we could also solve it for bodhi1 as well.

**Comment by ralphbean** [comment]
We eject the update at push-time if there are any relevant taskotron failures.  Closing as fixed!

**Comment by kparal** [comment]
I hope maintainers can then override it and push it again, if our test turns out to be broken (unfortunately it does happen from time to time).
