### ISSUE TITLE
[web] cannot edit large bodhi update: should use hash alias

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#1161]
I can't edit [this large fedora update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-25cbafa070) in the Fedora Bodhi web interface...
when I try I get an error page saying the URL is invalid:

```
Not Found

The requested URL /updates/nvr1 nvr2 nvr3 .... nvr1XYZ/edit was not found on this server.
```

**Comment by bowlofeggs** [comment]
My guess is that the web form is using the long name for the update instead of using its alias. If so, it's probably an easy fix, but it's just a guess.

**Comment by juhp** [comment]
My guess is that the web form is using the long name for the update


Yes it is.

Maybe if I use the hash in the url, it will work??

**Comment by juhp** [comment]
Indeed edit seems to work fine with the hash alias.
So should be an EasyFix. :)

**Comment by bowlofeggs** [comment]
@juhp Awesome, thanks for investigating!
