### ISSUE TITLE
bodhi.server.util.flash_log does not flash

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1165]
The name and docblock of ```bodhi.server.util.flash_log``` says that it flashes and logs a message, but it only logs the message.

**Comment by ankit01ojha** [comment]
@bowlofeggs Is this issue still open?

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
