### ISSUE TITLE
Bodhi moved updates into the dist-6E-epel-testing tag before they were successfully pushed

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1173]
Today the EPEL 6 push moved several unsigned updates into the ```dist-6E-epel-testing``` tag, and then tried to push them. Since they were unsigned, the push failed but the updates remained in the ```dist-6E-epel-testing tag``` instead of the ```dist-6E-epel-testing-candidate``` tag.

This is essentially an order of operations problem. Bodhi should only move updates from the Candidate tag to the Testing tag once they are successfully pushed. This way, if there is an error during an update push, its tag will correctly reflect its state.

**Comment by ausil** [comment]
This is expected. when the push fails due to unsigned packages the correct action is to make sure they are signed and resume the push

**Comment by bowlofeggs** [comment]
Thanks @ausil!

I will close this issue since it is expected.
