### ISSUE TITLE
OSTree failures should not block RPM pushes from going out

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1174]
Currently, any failure in OSTree will block release engineering from pushing out RPMs. This could be bad if there were important security updates.

We need to refactor the masher such that:

* Failures in OSTree do not block RPM pushes from going to users (and vice-versa),
* Errors in OSTree and RPM mashing should be independently reported,
* The overall mash success should only be True if both succeeded.

**Comment by bowlofeggs** [comment]
It was suggested by @ausil in #1214 that the updates-testing pushes should be blocked by ostree failures but the updates pushes should not be blocked by them.

**Comment by ausil** [comment]
opposite way around, updates-testing should not be blocked on failures but updates should be

**Comment by bowlofeggs** [comment]
@ausil Thanks for the clarification, and that makes sense to me.

**Comment by bowlofeggs** [comment]
Now that we are using Pungi to do all the mashing, we are no longer in control of what is considered success or failure. I'm going to close this as a result.
