### ISSUE TITLE
Use kerberos tickets

### ISSUE THREAD

**Issue by Fale** [fedora-infra/bodhi#1179]
It would be nice if the CLI client for bodhi would use kerberos tickets instead of asking the password

**Comment by puiterwijk** [comment]
Sorry, :-1:.
We will be switching to OpenID Connect for API tokens in the near future, but we will not use Kerberos for CLI,

**Comment by Fale** [comment]
I see, it would make sense. Is there an indicative date for OpenID Connect introduction?

**Comment by puiterwijk** [comment]
Well, the server is live as of a bit ago, and the base client was implemented about two weeks ago.
I am hoping that client applications will start moving soon.

**Comment by Fale** [comment]
So it would be ready for bodhi to implement this feature? If yes, I think this ticket should be reopened, renamed etc

**Comment by puiterwijk** [comment]
Sure, although I would personally say that that's a new ticket, but if you want to reopen and rename this one, go ahead.
