### ISSUE TITLE
consider to implement bash completion for bodhi-client

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1188]
[Lukas Slebodnik originally filed this RFE in Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1408205):

> Description of problem:
> The bodhi client 2.0+ has two many nested subcomands. I do not use bodhi very often and therefore I do not remember the correct syntax. It is possible to type --help for each subcomand but it is slow. It is also possible to check syntax in manual page but then I need to copy&paste from man page to a command line. 
>
> Version-Release number of selected component (if applicable):
> sh$ rpm -q bodhi-client
> bodhi-client-2.3.3-1.fc26.noarch
>
> How reproducible:
> Deterministic
> 
> Steps to Reproduce:
> 1. //ensure that you are testing with bash and installed bash-completion
>    bash
> 2. // type bodhi<tab>
> 
> 
> Actual results:
> bash completion try to use local files as parameters which is not very usefull
> 
> Expected results:
> overrides updates
> 
> Additional info:
> $ bodhi updates<tab>
>  comment download new query request
> 
> //the similar output is printed with --help
> sh$ bodhi updates --help
> Usage: bodhi updates [OPTIONS] COMMAND [ARGS]...
>
> Options:
>   --help  Show this message and exit.
>
> Commands:
>   comment
>   download
>   new
>   query
>   request

**Comment by ryanlerch** [comment]
bodhi-client has built in support for bash-completion via click.

currently, if you enable it via this line in your bashrc:

```
eval "$(_BODHI_COMPLETE=source bodhi)"
```

it works. However, when testing on the vagrant install, every completion throws up a bunch of warnings:

```
overrides  updates
[vagrant@bodhi-dev bodhi]$ bodhi ov/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib64/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/paste': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/moksha': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/repoze': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/lib/python2.7/site-packages/fedora/client/bodhi.py:48: DeprecationWarning: fedora.client.bodhi has been deprecated. Please use bodhi.client.bindings instead.
  DeprecationWarning)
```

**Comment by bowlofeggs** [comment]
On Mon, 2017-06-19 at 06:21 -0700, Ryan Lerch wrote:
> bodhi-client has built in support for bash-completion via click.

I think this will get us part of the way there, but I think we can
probably do something fancy to add more. For example, you can do this
with click:

$ bodhi upda<TAB>

and get:

$ bodhi updates

However, I think it'd be super cool to do dynamic tab completion. For
example:

$ bodhi updates new bodhi-2.7.<TAB>

Where it queries Bodhi for possible versions (similar to how the web UI
does it). Unfortunately, I don't think click offers facilities to help
here yet, but we could try to add some kind of callback system to click
that allows us to supply possible completions. I think that'd be pretty
sweet.

Anyways, we really should distribute the existing tab completion
scriptlet thing to our users. Should be pretty easy, but is probably
something to be done more in the spec file than the upstream repo I
think (I could be wrong?).

> currently, if you enable it via this line in your bashrc:
> eval "$(_BODHI_COMPLETE=source bodhi)"
> it works. However, when testing on the vagrant install, every
> completion throws up a bunch of warnings…

These warnings are because I've set PYTHONWARNINGS away from the
default value in the Vagrant .bashrc file - I don't think users would
see them unless they also have a non-default value there. The warnings
are useful for us to see in development, so we are aware of deprecated
things, and other things we should be fixing.

Side note - I have no idea what these ImportWarnings are there for, or
if there's anything we can/should reasonably do about them…
