### ISSUE TITLE
Disable autokarma on *any* signed-in -1 karma

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/bodhi#1191]
Issue #879 disables autokarma if anyone gives a -1 to "basic system functionality". Let's extend that to all packages — if any logged-in user gives -1, disable automatic push. The maintainer will still be able to override and push manually, but will apply their judgement in this case, rather than letting the positive/negative sum decide.

**Comment by trishnaguha** [comment]
Okay this sounds like the same we have done for critical updates :-). I'm going to make a stab at it.

**Comment by kparal** [comment]
Thanks for implementing this! As a suggestion, you might add some message to clearly explain what just happened, e.g.:
> Negative karma received, disabling automatic push to stable. Please push manually if you decide the issue is not severe.
