### ISSUE TITLE
obsoleting single package from multiple packages update doesn't work

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#1192]
Update X: `foo-1.0, bar-1.0`
After some time you submit new update Y: `bar-2.0`

It doesn't remove `bar-1.0` from X and when you try pushing X to stable (Y already pushed) -- it fails.

**Comment by igor-raits** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2016-8b3063d71c
https://bodhi.fedoraproject.org/updates/FEDORA-2016-b9ecaa6f9f

So I had to manually remove one build from X.

**Comment by bowlofeggs** [comment]
I believe this might be duplicate with https://github.com/fedora-infra/bodhi/issues/512. Feel free to let me know if you think it's not!
