### ISSUE TITLE
removing pkg from multiple-pkg update should not reset days-to-stable counter

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#1193]
Update X: `foo-1.0, bar-1.0`

After YY days it's possible to push into stable, but once you remove one of packages you have to wait YY days again.

**Comment by bowlofeggs** [comment]
I'm not sure I agree on this one. Any testing that has been done on the package was presumably done on the set of packages (foo and bar in this case). If bar is removed, testers should reconsider whether foo is OK to go alone without bar. There are real world scenarios where this could fail, so resetting the karma does make sense in my opinion.
