### ISSUE TITLE
Mashing only commits after all mashes finish

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/bodhi#1208]
We should probably do a database commit after a mash finishes.
An example: if we push f25-updates and f24-updates, the f25-updates mash might have finished and synced out, and the bugzillas will be closed, but the bodhi page still displays the updates as "request: stable, status: testing", because the database commit that marks it as pushed hasn't been committed yet.

**Comment by bowlofeggs** [comment]
This was fixed when the Compose db model was introduced several months ago.
