### ISSUE TITLE
hold pushing package to repository until either all dependencies are in that repo or all dependencies will be added in same push

### ISSUE THREAD

**Issue by caeppeoppoo** [fedora-infra/bodhi#1212]
I don't think a package should be pushed to a repository if its dependencies aren't yet in that repository. the push of that package should wait until all dependencies are either already in the repo or will be added during the same push.

Here's an example where this is a problem for stable users:
https://bodhi.fedoraproject.org/updates/firewalld-0.4.4.2-2.fc24#comment-546028
https://bodhi.fedoraproject.org/updates/selinux-policy-3.13.1-191.23.fc24#comment-545938

The firewalld package got pushed even though it's dependency on a particular version of selinux-policy could not be resolved in stable. in yumex-dnf, this resulted in being prompted to remove selinux-policy and selinux-policy-targeted; with dnf --update, this resulted in "Skipping packages with broken dependencies"; it wasn't until I ran dnf --update --best that I could see what was going on.

At worst, this issue can result in errors such as important packages being removed by accident (I could have easily overlooked that yumex-dnf was going to remove the selinux-policy packages, especially if there happened to be more updates, which would have hidden this fact at the end of a long scrollable list of package changes). At best, this issue causes annoyance / headaches, such as the user's update application or script repeatedly informing them there's an update even though the update is impossible to install, and the user then having to try to figure out what's going on.

**Comment by bowlofeggs** [comment]
Thanks for the report!

Bodhi doesn't actually have the information on hand to make this determination. I wonder if we could collaborate with Taskotron to solve this issue, which I believe does have the needed information.

**Comment by kparal** [comment]
Yes, it's Taskotron's goal to automatically stop these issues from happening. In this case, you should have received a warning from depcheck saying the deps were not satisfied for pushing firewalld stable, and then Bodhi would have disabled karma autopush. But depchecks said everything was OK. There must be some problem in depcheck. I don't really want to dig deep into it, because we plan to replace our internal implementation of depcheck with rpmdeplint in the foreseeable future, so hopefully it starts to be more reliable.

**Comment by bowlofeggs** [comment]
Thanks for the information @kparal!

I'm going to close this bug report under the assumption that rpmdeplint will solve the problem for us.

**Comment by caeppeoppoo** [comment]
@kparal -- is there a place to follow the progress of the planned switch to rpmdeplint?

**Comment by kparal** [comment]
Hi, you can watch it here:
https://phab.qa.fedoraproject.org/T878

**Comment by dustymabe** [comment]
@caeppeoppoo - apparently we can follow along on this ticket: https://phab.qa.fedoraproject.org/T878

**Comment by dustymabe** [comment]
sigh.. browser hadn't been refreshed :(
