### ISSUE TITLE
[UI/UX] *Add Comment* button should be just below the Comment section of Updates

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/bodhi#1216]
The *Add Comment* looks odd down there. It should be just below the *Solution* field.
For instance: https://bodhi.fedoraproject.org/updates/FEDORA-2017-78a478cd32 

![screenshot from 2017-01-11 17-25-51](https://cloud.githubusercontent.com/assets/13337039/21847731/68a75016-d823-11e6-839d-3f4cc209ba81.jpg)

**Comment by ankit01ojha** [comment]
@trishnaguha I would like to work on this, could you please tell me how to start.

**Comment by trishnaguha** [comment]
You will need to look into https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/templates/update.html

**Comment by ankit01ojha** [comment]
@trishnaguha It would be nice if I just put the  Add comment on the right-side just below the solution field.

**Comment by ankit01ojha** [comment]
@trishnaguha can you assign me this issue.
