### ISSUE TITLE
Cannot create updates for packages comaintained by lxqt-sig group I'm a member of

### ISSUE THREAD

**Issue by lupinix** [fedora-infra/bodhi#1218]
Hi,

we created a fas and pkgdb group lxqt-sig some days ago and added the group as a comaintainer to LXQt-related packages. Now I could commit all my changes and could do all koji builds. But I cannot create updates in bodhi, I always get error messages like "Builds : lupinix does not have commit access to lximage-qt". Did I miss something?

Christian

**Comment by bowlofeggs** [comment]
This code sounds relevant: https://github.com/fedora-infra/bodhi/blob/2.3.3/bodhi/server/validators.py#L362-L369

**Comment by puiterwijk** [comment]
Please note that the groups list is only refreshed on login.
So please log out from bodhi and then relogin, and it should refresh your group list, which should fix your issue.

**Comment by lupinix** [comment]
Not solved :( I tried it several times within last days, using computer at work, notebook etc, so login should not be the issue

**Comment by puiterwijk** [comment]
Okay, so the problem is that nobody configured this group to be requested by Bodhi. This needs an SOP update on the infra side.

**Comment by lupinix** [comment]
Can you check astro-sig in this context too, another new fas/pkgdb group.

**Comment by lupinix** [comment]
Thank you for investigating :+1:

**Comment by puiterwijk** [comment]
http://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=bd3bade

**Comment by lupinix** [comment]
That worked, thank you very much!
