### ISSUE TITLE
Database Schema Image Missing in Developer documentation developer_docs.rst

### ISSUE THREAD

**Issue by lalitkr** [fedora-infra/bodhi#1237]
#1150 The database.png file is missing in the [developer documentation.](https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst)

**Comment by bowlofeggs** [comment]
@lalitkr The ```docs/Makefile``` automatically generates this file when you run ```make html```.

**Comment by lalitkr** [comment]
@bowlofeggs okay got it. Thank You
