### ISSUE TITLE
Human check to difficult

### ISSUE THREAD

**Issue by TerryBarnaby** [fedora-infra/bodhi#1241]
I tried to enter a comment on a new updated package that didn't work, but I could not as I could not work out the human check and there appeared to be no way to try a different one.
![bodhihumancheck](https://cloud.githubusercontent.com/assets/23216724/22236401/4ef43ad8-e1fd-11e6-8cda-35358c0048e7.png)

**Comment by trishnaguha** [comment]
There probably could be an option to try a different one?

**Comment by bowlofeggs** [comment]
I plan to drop anonymous comments in https://github.com/fedora-infra/bodhi/issues/2700.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by bowlofeggs** [comment]
Yeah, we will no longer have anonymous comments in Bodhi 4.
