### ISSUE TITLE
bodhi-push should sort the updates by release

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1245]
bodhi-push used to collate the list of packages it prints by release, and now it prints them in whatever order the database gives us. This makes it more difficult for the release engineer to review the list to approve or deny.

Instead, we could collate the printed list by release, and additionally it could be helpful to collate them by update (for updates with multiple packages).

**Comment by ankit01ojha** [comment]
I would like to work on this, can you tell me the file related to the issue.

**Comment by bowlofeggs** [comment]
If you look in the ```setup.py```, you can see that ```bodhi-push``` is automatically generated from the ```push()``` function in ```bodhi.server.push```:

https://github.com/fedora-infra/bodhi/blob/2.3.3/setup.py#L186

**Comment by bowlofeggs** [comment]
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092
