### ISSUE TITLE
link to build in koji should use https

### ISSUE THREAD

**Issue by obbuppu** [fedora-infra/bodhi#1246]
in each update, there's a link to the build in koji, for example, https://bodhi.fedoraproject.org/updates/FEDORA-2017-6d6e2bfd1a links to http://koji.fedoraproject.org/koji/search?terms=libXpm-3.5.12-1.fc24&type=build&match=glob (next to "Build") ... the link should use https so that the connection stays secure throughout. koji supports https and even redirects from http to https, so it would be better to change the link to point to https.

**Comment by ankit01ojha** [comment]
I would like to work on this, can you please tell me the files from where I can make these changes.

**Comment by obbuppu** [comment]
Here you go:
https://github.com/fedora-infra/bodhi/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fkoji.fedoraproject.org%2Fkoji%2Fsearch%3Fterms%3D%22

**Comment by ankit01ojha** [comment]
Is this fine or it needs more changes?
