### ISSUE TITLE
Position of the Add Comment button changes when the scren size is reduced.

### ISSUE THREAD

**Issue by ankit01ojha** [fedora-infra/bodhi#1247]
When the size of screen is reduced from the desktop size, Add Comment  button comes in centre after some time (size more a mobile phone screen) . Which needs to fixed at the right size like in https://bodhi.fedoraproject.org/updates/FEDORA-2017-6d6e2bfd1a .
![screenshot from 2017-01-25 21-29-04](https://cloud.githubusercontent.com/assets/21126132/22298257/de3d45c4-e345-11e6-8b3f-331274e27bc5.png)

**Comment by trishnaguha** [comment]
Would you probably like to make the changes in the PR https://github.com/fedora-infra/bodhi/pull/1227 ?
Since the PR is related to the `Comment` button as well. Just asking!

**Comment by ankit01ojha** [comment]
I think PR #1227 will solve this one too :) So, I don't think I will have to make any other changes in that.

**Comment by ryanlerch** [comment]
#1227 resolved this one, and fine-tuning of the placement of the button with the new theme was done in #1516
