### ISSUE TITLE
bodhi seems to have problems pushing packages to repositories

### ISSUE THREAD

**Issue by JayJayJazz** [fedora-infra/bodhi#1252]
Hi all,

if you check:
https://bodhi.fedoraproject.org/updates/?packages=firefox
then you see that packages for fc24 are already in in testing (firefox-51.0.1-1.fc24) or stable (firefox-51.0-3.fc24), but the ones for fc25 seem to be stuck in pending (firefox-51.0-3.fc25 and firefox-51.0.1-1.fc25). The packages for fc24 and fc25 were released at the same date/time. Can someone please check, because these firefox updates are security relevant.

Kind regards,
JayJayJazz

**Comment by bowlofeggs** [comment]
Hello @JayJayJazz and thanks for the report! The issue was with rpm-ostree, which Bodhi uses to compose OSTrees during mashing. You can read more about the problem here, but AFAIK it has been resolved now:

https://pagure.io/releng/issue/6602
