### ISSUE TITLE
Multi-branches update broken

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#1253]
Trying to submit a new update (security one for Wrodpress 4.7.2), add the build for each branch is unable to create the 5 updates (as in previous version) but only one.

Also see very strange output in (some updates list various time the same package)
https://bodhi.fedoraproject.org/updates/?packages=wordpress

**Comment by jeremycline** [comment]
I'm going to close this as a duplicate of #1251 - thanks for reporting it though!
