### ISSUE TITLE
[critical] Cannot add builds to existing update

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#1255]
Ex: https://bodhi.fedoraproject.org/updates/FEDORA-2017-c9970099a8

Trying to 
* remove  php-phpunit-PHPUnit-5.7.6-1.fc25
* add php-phpunit-PHPUnit-5.7.9-1.fc25
* add php-phpunit-comparator-1.2.4-1.fc25

Removal happens but nothing added

Seems critical^H important^H critical

**Comment by remicollet** [comment]
Cannot even create multi packages updates... :(

**Comment by jeremycline** [comment]
I hand-tested this and it looks like it's also fixed by #1232, which, when I look at the code, makes sense.

**Comment by kalev** [comment]
@nirik deployed a new bodhi build last night and I believe this should be working again.

**Comment by bowlofeggs** [comment]
I had also been experiencing this issue with my Bodhi Bodhi update (haha), and with @jeremycline's patch (now applied to production as @kalev said) I was able to edit it today:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-cd060eeb3c

I'll mark this as closed for now, but please let me know if you see it again and thanks for the report!
