### ISSUE TITLE
searching by Bodhi ID doesn't work in the web UI

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1258]
Example update:
https://bodhi.fedoraproject.org/updates/FEDORA-2017-1658dd0b1e

But if I search for `FEDORA-2017-1658dd0b1e` in the search box, it says `no matching updates`.

![snimek z 2017-02-01 09-17-47](https://cloud.githubusercontent.com/assets/755451/22499488/5fac57b2-e85f-11e6-981f-952a2ddb6b79.png)

If I don't know how to construct the URL, I'm not able to find that particular update in Bodhi.

**Comment by ankit01ojha** [comment]
its working for other updates-
![screenshot from 2017-02-02 14-51-53](https://cloud.githubusercontent.com/assets/21126132/22543709/c849791e-e957-11e6-9d18-e252f662875e.png)

**Comment by kparal** [comment]
@ankit01ojha You're not searching for Bodhi update ID, you're using package NVR.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
