### ISSUE TITLE
mention that karma is reset on update edit

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1276]
Some people are confused why karma is zero for certain updates, because they don't know that update edit resets karma. It might be a good idea to add a note when this happens, so that it's more obvious.

What about changing e.g. this:
```
jwrdegoede edited this update.

New build(s):
    mesa-13.0.4-1.fc25
    libglvnd-0.2.999-10.gitdc16f8c.fc25
Removed build(s):
    libglvnd-0.2.999-9.gitdc16f8c.fc25
    mesa-13.0.3-7.fc25
```

into this:
```
jwrdegoede edited this update.

New build(s):
    mesa-13.0.4-1.fc25
    libglvnd-0.2.999-10.gitdc16f8c.fc25
Removed build(s):
    libglvnd-0.2.999-9.gitdc16f8c.fc25
    mesa-13.0.3-7.fc25

All karma has been reset.
```
?

Of course don't add the note when just the update is edited, but builds are not changed (e.g. just the description is updated, or linked bug reports, etc) - that does not reset karma.

**Comment by trishnaguha** [comment]
I like the idea.
