### ISSUE TITLE
Change the mouse cursor when it hovers over  `Releases` to pointer.

### ISSUE THREAD

**Issue by ankit01ojha** [fedora-infra/bodhi#1296]
When we hover mouse cursor over the `Releases` button it changes to auto which seems odd as it should change to pointer just like as the `login` button.
https://bodhi.fedoraproject.org/

**Comment by ankit01ojha** [comment]
I know how to fix this but, I am not getting the file regarding this.

**Comment by bowlofeggs** [comment]
Looks like the Releases button is defined here:

https://github.com/fedora-infra/bodhi/blob/2.4.0/bodhi/server/templates/master.html#L97-L100
