### ISSUE TITLE
bodhi-client always enables autokarma

### ISSUE THREAD

**Issue by rdieter** [fedora-infra/bodhi#1298]
Submitted a bunch of stuff using 
bodhi-client-2.4.0-1.fc25.noarch
today, and seems my updates all had autokarma enabled, and I did not use --autokarma option (only --stable-karma and --unstable-karma)

**Comment by ryanlerch** [comment]
I believe this one has been fixed by:

https://github.com/fedora-infra/bodhi/commit/e51402ec5b158514315d615d86fef8bd936d5904
See Also the issue: #1378 

AFAICT, this commit makes it so when creating an update with the bodhi-client, autokarma is now disabled unless the --autokarma option is provided

**Comment by bowlofeggs** [comment]
Ah yes, I believe this was fixed by https://github.com/fedora-infra/bodhi/issues/1583. Thanks @ryanlerch!
