### ISSUE TITLE
The masher should clean up old mashes at the end of every run

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1304]
Bodhi 2.4.0 introduced a new CLI tool called ```bodhi-clean-old-mashes``` that deletes all but the 10 newest mashes. I had intended the script to be used in cron, but after talking with releng today about enabling it they suggested it would be nice if the masher called it automatically after each successful push to the mirrors. It's a good idea, so let's do it!

All we'll need to do is have the masher import and use the [```clean_up```](https://github.com/fedora-infra/bodhi/blob/2.4.0/bodhi/server/scripts/clean_old_mashes.py#L32) function when it completes a successful mash. I believe the print statements will be OK as they should just end up going to journald with the other log messages.

**Comment by ankit01ojha** [comment]
only thing needed is to import clean_up function and add its code??

**Comment by bowlofeggs** [comment]
On Fri, 2017-02-24 at 10:38 -0800, Ankit Raj Ojha wrote:
> only thing needed is to import clean_up function and add its code??

We will also need to test the change.

**Comment by bowlofeggs** [comment]
When we do this, let's add a new state to the ```ComposeState``` model for "Cleaning old composes" (please do use the word compose and not mash). This way the /composes/ UI, API, and CLI will be able to display this new state to the users. It'll be rad.

**Comment by bowlofeggs** [comment]
You will need to create a database migration. Here's another migration that extends an enum that you can use as an example:

bodhi/server/migrations/versions/22858ba91115_add_new_side_tag_update_states.py

**Comment by vismay-golwala** [comment]
Do we clean_up if a mash fails?

**Comment by bowlofeggs** [comment]
On 06/14/2018 10:05 AM, Vismay Golwala wrote:
> Do we clean_up if a mash fails?

No, we should only clean up when all the composes succeeded.

**Comment by bowlofeggs** [comment]
This feature is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by dustymabe** [comment]
do we know what the policy is for cleaning up old composes? i.e. is there some amount of time where they won't get cleaned up. Since we now produce atomic host artifacts in the bodhi runs we might need them to be around temporarily.

**Comment by bowlofeggs** [comment]
On 08/22/2018 09:40 PM, Dusty Mabe wrote:
> do we know what the policy is for cleaning up old composes?

I don't know of any policy around this, but Bodhi will keep 10 old
composes around when it does its clean up run.

**Comment by dustymabe** [comment]
> I don't know of any policy around this, but Bodhi will keep 10 old composes around when it does its clean up run.

I think that should work for us. If not it's pretty close and maybe I can ask to have it bumped up a few to like 12 or 14. Either way this should work for now.

**Comment by dustymabe** [comment]
thanks randy

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
