### ISSUE TITLE
push to stable threshold requires 3 karma and ignores fedora update policy

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1307]
Here are two updates I tried to push today:
https://bodhi.fedoraproject.org/updates/FEDORA-2017-c8269ca6da
https://bodhi.fedoraproject.org/updates/FEDORA-2017-42c556d203

The fc24 one had autopush disabled (the threshold levels were set to 3-3 by default, by I assumed that should not affect anything, since autopush is disabled), and I received one positive karma from mkrizek. But I couldn't push to stable, even though I thought I should be able to do so. Testcloud is not critpath nor security update, and https://fedoraproject.org/wiki/Updates_Policy#All_other_updates says:
>  reach the positive Bodhi karma threshold specified by the updates submitter

I had autopush disabled, so I assumed any threshold is ignored and I can submit any time. But ok, I decided to edit the update and lower the threshold to 1 (autopush still disabled). But that didn't help either. Then I tried enabling autopush (with threshold 1), no help. I tried few more configurations, nothing helped.

Receiving second karma from jsedlak didn't help either, even though https://fedoraproject.org/wiki/Updates_Policy#All_other_updates says:
>  reach the criteria laid out in the previous section

which refers to:

>  At the time of the request to stable, the update needs to have either a Bodhi karma sum of 2 

which was satisfied.

Only getting the third karma made the update to be pushed stable (autopush was enabled at that time). The same happened with the fc25 update, again I needed 3 karma (except that autopush was disabled for that one, and I pushed stable manually using a button).

Is https://fedoraproject.org/wiki/Updates_Policy outdated or Bodhi implementation wrong?

**Comment by bowlofeggs** [comment]
On Thu, 2017-02-23 at 00:54 -0800, Kamil Páral wrote:
> I had autopush disabled, so I assumed any threshold is ignored and I
> can submit any time.

I'm not 100% sure what happened in total with these updates, but I do
believe that a non-autokarma update still needs to hit the karma
thresholds before the push to stable button will appear.

>  But ok, I decided to edit the update and lower the threshold to 1
> (autopush still disabled). But that didn't help either.

I would also expect this to work, so it sounds like something's not
right.

>  Then I tried enabling autopush (with threshold 1), no help.

I think this would have worked, but only on the next +1 you got, or
possibly during the next mash (not sure on that one). The comment
processing code is what checks whether the threshold is met, at the
moment that karma is being added. The code that handles switching
autokarma on and off doesn't check this.

> Is https://fedoraproject.org/wiki/Updates_Policy outdated or Bodhi
> implementation wrong?

I don't know, but we should definitely review it and compare it with
Bodhi's behavior. I suspect there are discrepancies. If there are,
perhaps we should work with some governing body (FESCo?) to decide case
by case whether to update the document, or to correct Bodhi to comply.

Thanks for reporting this!

**Comment by kparal** [comment]
> I'm not 100% sure what happened in total with these updates, but I do believe that a non-autokarma update still needs to hit the karma thresholds before the push to stable button will appear.

OK, two questions :)
1. When I played with editing the autokarma checkbox, at one point the threshold levels disappeared (the edit fields were blank, `stable threshold: X unstable threshold: X` text was not displayed on the update page). What's the threshold in that case?
2. If I as a maintainer can set the threshold to 1 (for non-critpath non-security updates), what's the point of insisting that I have to hit that karma level before "push to stable" button appears? If you show it right away, it just saves me from editing the update and lowering the threshold. Or is it to prevent mistakes? The requirement in the document:
> reach the positive Bodhi karma threshold specified by the updates submitter

makes sense for autopushed updates, but I think for manual deliberate pushing, it doesn't mean much so we might not apply it in that case.



> I don't know, but we should definitely review it and compare it with Bodhi's behavior. I suspect there are discrepancies. If there are, perhaps we should work with some governing body (FESCo?) to decide case by case whether to update the document, or to correct Bodhi to comply.

Yes, FESCo is supposed to maintain that document. I don't necessarily agree with how the requirements are laid out, but we should at least make sure the document and the implementation is in sync :)

**Comment by bowlofeggs** [comment]
On Thu, 2017-02-23 at 06:55 -0800, Kamil Páral wrote:
> When I played with editing the autokarma checkbox, at one point the
> threshold levels disappeared (the edit fields were blank, stable
> threshold: X unstable threshold: X text was not displayed on the
> update page). What's the threshold in that case?

When the fields are set empty, I believe that *should* go into the
database as NULL values. I believe in this case there will be no
threshold at which the stable button will appear, and the update will
have to wait for the 7 days.

> If I as a maintainer can set the threshold to 1 (for non-critpath
> non-security updates), what's the point of insisting that I have to
> hit that karma level before "push to stable" button appears? If you
> show it right away, it just saves me from editing the update and
> lowering the threshold. Or is it to prevent mistakes?

You make a good point ☺ There doesn't seem to be much value in forcing
the maintainer to wait for a threshold they can change. I guess it
could prevent mistakes, but I think realistically a developer is
hopefully going to be pushing the stable button after reading the
comments.

> Yes, FESCo is supposed to maintain that document. I don't necessarily
> agree with how the requirements are laid out, but we should at least
> make sure the document and the implementation is in sync :)

Agreed!

**Comment by bowlofeggs** [comment]
This should get fixed when https://github.com/fedora-infra/bodhi/pull/3310 is merged.
