### ISSUE TITLE
autopush checkbox get enabled on update edit even though it was disabled before

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1308]
When I create a new update with autopush disabled (the checkbox unticked), and then I edit the update, the autopush checkbox gets re-ticked automatically. That's annoying, because for each update I edit, I need to untick the checkbox every time, so that autopush doesn't get enabled when I don't want it. That's quite error-prone.

This might only happen on first update edit, but not on subsequent ones, I'm not sure.

Please honor the existing update configuration (autopush enabled/disabled) and make the checkbox reflect the current state, when editing an update. Thanks.

**Comment by bowlofeggs** [comment]
This might be a duplicate of https://github.com/fedora-infra/bodhi/issues/1032 but they may be subtly different.

**Comment by kkofler** [comment]
Bug #1032 was an illusion caused by the combination of bug #999 and this bug. The (probably) correct analysis is the one above.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
