### ISSUE TITLE
Document the documentation

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1321]
We should put links to the documentation in the following places:

* The README
* The footer
* The man page

The docs will be hosted at https://bodhi.fedoraproject.org/docs soon, so we should use that URL.

**Comment by ankit01ojha** [comment]
@bowlofeggs Do you mean footer of bodhi.fedoraproject.org ? And link is to be added to all the files inside the man pages?

**Comment by bowlofeggs** [comment]
@ankit01ojha Yes, and yes. However, I recommend waiting until #1313 is merged because that pull request is reworking the HTML template.

**Comment by ankit01ojha** [comment]
@bowlofeggs I will send a PR regarding this issue ASAP. Sorry, for being late.

**Comment by ankit01ojha** [comment]
@bowlofeggs the link for docs https://bodhi.fedoraproject.org/docs is not working now?
When I clicked the link it showed `404 Not Found`.

**Comment by bowlofeggs** [comment]
On Tue, 2017-03-21 at 02:32 -0700, Ankit Raj Ojha wrote:
> @bowlofeggs the link for docs https://bodhi.fedoraproject.org/docs is
> not working now?
> When I clicked the link it showed 404 Not Found.

That's OK - it will work when Bodhi 2.5.0 is deployed to production, or
when I deploy a config change after the freeze. Bodhi 2.5.0 is
currently deployed to staging and it does work there:

https://bodhi.stg.fedoraproject.org/docs

We are currently in an infrastructure freeze so the docs change cannot
yet be deployed to production.

In either case, the link will work before or at the time any change to
develop gets deployed to production.
