### ISSUE TITLE
The main page of the documentation needs text describing what Bodhi is

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1322]
We need to add text to the ```docs/index.rst``` file describing what Bodhi is. It would also be helpful if it linked to some things:

* The PyPI page
* The Bodhi deployment (maybe even the staging deployment?)
* Where to report issues

**Comment by ankit01ojha** [comment]
@bowlofeggs Is the issue reporting link is https://github.com/projectatomic/rpm-ostree/issues ?
I am working on it, got confused on this one.

**Comment by ankit01ojha** [comment]
@bowlofeggs Can you tell me about the staging deployment links?

**Comment by bowlofeggs** [comment]
@ankit01ojha The staging deployment is at https://bodhi.stg.fedoraproject.org
