### ISSUE TITLE
Modify the REST API to handle multiple content types

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1325]
We need to modify the REST API so that it can handle multiple content types. It may be possible to do this in a backwards compatible way, but we can also name the next release Bodhi 3.0 if we need to make backwards-incompatible changes.

**Comment by ralphbean** [comment]
Based on the [meeting discussion](https://meetbot.fedoraproject.org/fedora-meeting-1/2017-05-23/bodhi_stakeholders.2017-05-23-15.00.html) this morning, this may be almost no work.  We need:

- To expand the GET apis to tell the user what “kind” of update it is.
- To add logic to the submit API to infer what kind of build/update it should be based on info gleaned from Koji.
- Add support to query by type (give me all updates of type “container”, etc..)
