### ISSUE TITLE
Modify the Web UI to handle multiple content types

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1329]
We will need to alter the web interface to handle multiple content types.

**Comment by bowlofeggs** [comment]
@ryanlerch @ralphbean I don't have many ideas for this, other than to slap some text in the right hand info box that says what kind of update it is. For a second I considered trying to come up with icons for each update type, but I can't imagine what an icon for an RPM or a module might look like.

Do either of you think more than just displaying text about the type is needed?

**Comment by ryanlerch** [comment]
Yeah, I think we are left to text here. The only thing we could use for RPM is the package icon, and we are already using it for New Package. and Module would be even more abstract Ithink...

**Comment by ralphbean** [comment]
Text works for me.  :)
