### ISSUE TITLE
Modify the masher to handle modules

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1330]
We will need to modify the masher to work with multiple content types, starting with modules.

**Comment by ralphbean** [comment]
Question, @bowlofeggs: the text of the ticket says "starting with containers".  Is that still the case?  Are containers first in line, or modules?

**Comment by bowlofeggs** [comment]
@ralphbean Modules are first. I had written this before I knew we were doing modules for Fedora 27. I'll fix it ☺

**Comment by bowlofeggs** [comment]
I believe @mcurlej is working on this.

**Comment by ralphbean** [comment]
He sure is!  :)

**Comment by ralphbean** [comment]
See #1697.
