### ISSUE TITLE
Don't reopen BZ review ticket if "Close bugs on stable" is disabled

### ISSUE THREAD

**Issue by morxa** [fedora-infra/bodhi#1349]
As the title says, I would expect bodhi to change the ticket status only if "Close on stable" is selected for the update.

Currently, bodhi always adds comments to the tickets and changes the status to ON_QA, even if "Close on stable" is disabled and the ticket is already closed.

As an example, I recently submitted python-pyswip. I closed the [BZ review request ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1413374) after building the package for rawhide. For the bodhi updates (e.g., [F24](https://bodhi.fedoraproject.org/updates/FEDORA-2017-cd4110b464)) I added the ticket number for completeness sake, but I disabled "Push on stable". After the package has been pushed to testing, the ticket was reopened and the status set to ON_QA.

**Comment by bowlofeggs** [comment]
I think the language "Close on stable" might only relate to changing the status to CLOSED, and doesn't imply that Bodhi wouldn't (or would) make other state changes on tickets. At least, that's how I've always interpreted it. In other words, the behavior you described is what I would expect that boolean to do based on the language it uses.

It sounds like you are asking for an RFE to have Bodhi make no state changes at all on bugs. If we were to do that I would probably want to adjust the boolean to say something else, like "modify bug states" or similar.

**Comment by morxa** [comment]
I agree that this is an RFE. Still, I think the current behavior is not consistent: In the example above, the bug was re-opened, but after submitting the package to stable, it is still ON_CA.

Maybe the issue is really that the current state is not checked (at least in this case), and the bug is set to ON_QA no matter what. I think the ticket shouldn't be re-opened even if "Close on stable" is enabled.

**Comment by bowlofeggs** [comment]
@morxa That's a bit similar to the request from @adamwill in #1091 - he similarly didn't want Bodhi to "downgrade" the state of a bug.

**Comment by AdamWill** [comment]
@bowlofeggs I'm pretty sure that in the past 'close on stable' has always meant 'don't make any status changes'. When it was unselected, Bodhi would add comments when the update was submitted and pushed, but that's *all* it would do. It would never make any state change. If it's been changed now and it makes state changes but just never makes a change to `CLOSED`, that's a significant behaviour change that people will *not* be expecting, and I'd suggest it should be reverted.

I agree the wording of the UI element is not the best, but I think people have got used to the behaviour it actually produces and expect it now. I certainly do. If I uncheck that box, I don't want Bodhi making any state changes on the bug.

**Comment by bowlofeggs** [comment]
Ah I didn't realize the behaviour had changed at some point. I'm certainly not opposed to changing it, though I can't make it a priority right now. Pull requests welcome ☺

I'm happy to consider it a bug since it sounds like it is a regression from prior behaviour. If someone does send a PR, please be sure to relabel the help text to clarify that it is about all state changes.

**Comment by AdamWill** [comment]
Well, I haven't verified the current behaviour independently, I'm just going off the description in this report.
