### ISSUE TITLE
Updates with lots of Packages look unweildy

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#1351]
The recent changes I made to bodhi on the updates page have not translated well for an update with a lot of builds attached to it. The title of the update includes all the packagenames of all the builds, resulting in:

![bodhi-large-update](https://cloud.githubusercontent.com/assets/592259/23982983/f211f908-0a5c-11e7-855c-2f0d7b840898.png)

**Comment by ryanlerch** [comment]
My proposal to fix this (and also #957) would be a two-pronged solution.

First, make the logic for this title a little saner. For an update with a single build, it behaves as normal:

    enhancement update for inkscape in Fedora 25

For an update with 2 builds:

    bugfix update for python-arrow & python-requests in Fedora 24

For an update with 3 or more builds:

    security update for firefox, epiphany & 23 more in Fedora 25

The second prong would be to provide a new field tied to an update allowing a package maintainer to add a short description to a multi-build update. With it falling back to the above logic if one is not given. In the example given in the inital report, the short description could simply be "GNOME", so the label would read:

    enhancement update for GNOME in Fedora 25

**Comment by bowlofeggs** [comment]
@ryanlerch I'm a +1 on your proposal. I suggest we do it in two separate issues/PRs since one is easier than the other.

**Comment by ryanlerch** [comment]
Okay!

I can do the first prong, but the second involves adding some database entries, so it's a little out of my skill range. Will get the PR done for the first one now.

**Comment by ryanlerch** [comment]
Filed #1369 for the request of the new short description field for an update

**Comment by bowlofeggs** [comment]
This was fixed by #1370.
