### ISSUE TITLE
search button is not working

### ISSUE THREAD

**Issue by ankit01ojha** [fedora-infra/bodhi#1352]
When clicked on the search button on the bodhi's new fronted , its not working.

**Comment by bowlofeggs** [comment]
@ankit01ojha what about it isn't working for you? It seems to work well when I try it.

**Comment by ankit01ojha** [comment]
@bowlofeggs when I tried this in my localhost the search button of the new frontend was not working.
If its working for you then its fine, I should close this one. It was not working for me when I created this issue. (I consulted on IRC about this).
