### ISSUE TITLE
Should say "This update has reached 14 days in testing" instead of 7

### ISSUE THREAD

**Issue by robatino** [fedora-infra/bodhi#1361]
See the critpath update https://bodhi.fedoraproject.org/updates/FEDORA-2017-803e6bacb4 for F25 which shows the message "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes" after spending 14 days in testing (which I believe is the correct amount of time for a critpath update?).

**Comment by robatino** [comment]
Also, most of bodhi's comments end with a period, the ones that say "This update has reached X days in testing" appear not to.

**Comment by bowlofeggs** [comment]
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
