### ISSUE TITLE
Add a short description field for an update

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#1369]
As discussed in #1351, in an effort to make the titles of updates more useful, it would be great provide a new field tied to an update allowing a package maintainer to add a short description to a multi-build update. With it falling back to the logic for truncating the list outlined in #1351, if a short description is not given. 

As an example the short description could simply be "GNOME", so the label would read:

    enhancement update in Fedora 25 for GNOME

instead of:

    enhancement update in Fedora 25 for nautilus, gnome-shell and 63 others

**Comment by sebwoj** [comment]
Now we have [display_name](https://github.com/fedora-infra/bodhi/blob/3dca0e367dcbee25c492424228b50c6ab857212d/bodhi/server/models.py#L1615) field, but user is unable to set it on update creation/edit.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close this?

**Comment by bowlofeggs** [comment]
Thanks @sebwoj!
