### ISSUE TITLE
Creating an update with --autokarma and without the --stable and --unstable-karma flags sets autokarma off

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1378]
Today I created an update with the CLI like this:

```
$ bodhi updates new --user bowlofeggs --type bugfix --notes "The bodhi-client package no longer depends on yum." --bugs 1135681 --close-bugs --autokarma bodhi-2.4.0-3.fc26
Password:
================================================================================
     bodhi-2.4.0-3.fc26
================================================================================
  Update ID: FEDORA-2017-e2e877073e
    Release: Fedora 26
     Status: pending
       Type: bugfix
      Karma: 0
  Autokarma: False  [-3, 3]
    Request: testing
       Bugs: 1135681 - None
      Notes: The bodhi-client package no longer depends on yum.
  Submitter: bowlofeggs
  Submitted: 2017-03-22 22:30:16
   Comments: bodhi - 2017-03-22 22:30:16 (karma 0)
             This update has been submitted for testing by
             bowlofeggs.

  https://bodhi.fedoraproject.org/updates/FEDORA-2017-e2e877073e
```

Note that the Autokarma is False in the resulting text, and if I go to that update Autokarma is displayed as being off there as well. I would expect that the ```--autokarma``` flag would set it to be on.

#1298 may be related to this (and may even be the same underlying problem) - it reports that setting ```--stable-karma``` without specifying ```--autokarma``` sets autokarma to be on. Given this, my guess is that something is using the karma thresholds to determine whether to enable autokarma instead of the ```--autokarma``` flag.

**Comment by trishnaguha** [comment]
@bowlofeggs `autokarma` by default is always enabled if we do not specify. There are similar testcases in [test_updates.py](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/services/test_updates.py) where we haven't set `autokarma = True`. 
Based on that #1298 should not be considered as a bug. 
But disabling autopush with flag `--autokarma` is worth investigating.

**Comment by cverna** [comment]
I had a quick look at this one, as @trishnaguha said by default the autokarma is enabled (True), when you use the --autokarma option it will set the autokarma to False 🐒 .

I think we can go in 2 direction either make autokarma Flase by default, then you would need to add --autokarma to enable it, or either change the name of autokarma to noautokarma or something like that.

I am more for the first option.

edit
-----
There could be a 3rd option and use click Boolean flags (http://click.pocoo.org/5/options/#boolean-flags) and have something like

@click.option('--autokarma/--no-autokarma', default=True)

This would default to True, and still be True when you use --autokarma.

It looks like a nice solution

**Comment by bowlofeggs** [comment]
On Fri, 2017-06-02 at 10:57 -0700, Clement Verna wrote:
> I think we can go in 2 direction either make autokarma Flase by
> default, then you would need to add --autokarma to enable it, or
> either change the name of autokarma to noautokarma or something like
> that.
> I am more for the first option.

I also am in favor of the first option. The CLI already documents that
behavior (even though it doesn't follow it) so it would be best if we
stick to it.

Hopefully we can fix this only in the bindings/CLI code without
disrupting the API.
