### ISSUE TITLE
Split the BuildrootOverride model into two, if needed

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1395]
We may need to split the BuiltrootOverride model into two models, a superclass (probably still called BuildrootOverride) and a new RPM-specific subclass, perhaps simply called RPMBuildrootOverride.

Whether we do this depends on whether modules need BuildrootOverrides, as I do not believe containers or flatpaks need them.

If we do need them, all of BuildrootOverride's relationships should be analyzed to determine which ones should be adjusted to reference RPM vs. continuing to reference BuildrootOverride. Also, a database migration will be needed so that Bodhi's existing data can be preserved in the new split BuildrootOverride design. All code will need to be altered to use the new RPM model rather than the BuildrootOverride model when the data involved is RPM-specific.

Once this is done, all of Bodhi's functionality should continue to work exactly as it does today.

**Comment by jeremycline** [comment]
### BuildrootOverride Fields

* Notes (a text field)
* Submission date
* Expiration date
* Expired date

None of these seem specific to RPM buildroot overrides

### BuildrootOverrides Relationships

* A build
* A submitter (user)

Using the build type, we can determine what type of override it is. There are two methods of interest on the model, ``enable`` and ``expire``. If we want to have custom implementations of these it _might_ make sense to make a superclass/subclass, but neither one looks complicated or RPM specific.

Based on this, my vote is to document this model and move on without changes.

**Comment by bowlofeggs** [comment]
@jeremycline I concur - let's document and move along like that scene where Obi Wan told the Storm Trooper that these aren't the BuildrootOverrides they are looking for.
