### ISSUE TITLE
Track automated test results from openQA as well as Taskotron

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#1399]
We've had openQA testing critpath updates in production for several weeks now:

https://openqa.fedoraproject.org/group_overview/2

It'd be great for Bodhi to track these, as well as the Taskotron results.

The openQA results are forwarded to ResultsDB, but they are stored by update ID, not by package NEVR, so both the places where Bodhi currently does test result querying would need to be changed. Sample result:

https://taskotron.fedoraproject.org/resultsdb/results/13114685

Note that openQA results should be de-duplicated using the 'scenario' concept we've recently imported to ResultsDB: for each update, Bodhi should show the latest result for each 'scenario'. The 'scenario' is the combination of properties that defines a single 'test'. This is basically the same thing we have with depcheck, where we don't just want to display "the latest depcheck result" for each update, but "the latest x86_64 depcheck result" and "the latest i386 depcheck result". The 'scenario' concept would handle this by making the 'scenario' be 'testname.arch', e.g. 'depcheck.x86_64'.

I've been meaning to send a patch for this for a while but haven't found the roundtuits; I figured we should have an issue to track it.

Right now, @bowlofeggs and I are both kinda wondering why the front end ResultsDB integration is done with client-side javascript; it seems like it'd be much more efficient to do it server-side, having the server listen for fedmsgs from ResultsDB when a new result appears and stashing relevant ones somehow. The front-end code would just have to display the relevant results for the particular update. I'm kinda curious to know if there's a reason not to change to that kind of system before diving into this.

**Comment by AdamWill** [comment]
As the 'why Javascript' thing is kinda its own issue, I filed it separately: https://github.com/fedora-infra/bodhi/issues/1401 . If we're going to change that design, we should probably work on the change before working on this (no need to write it as part of the Javascript code, then rewrite it when we throw away the Javascript code...)

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/bodhi/pull/1418 would do the web UI portion of this.

**Comment by bowlofeggs** [comment]
@AdamWill Does the current UI show the tests results that you expect?

**Comment by AdamWill** [comment]
Well we've had a few go-rounds on this, but right now, yes, it works.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by AdamWill** [comment]
I think so, this is working fine in current production.

**Comment by bowlofeggs** [comment]
Thanks!
