### ISSUE TITLE
Bugzilla links need a space before "rhbz" to be recognized

### ISSUE THREAD

**Issue by jsynacek** [fedora-infra/bodhi#1406]
When typing an update message, bugzilla links are not correctly recognized:

```(rhbz#12345)``` is **not** recognized as a link in the preview window.

```( rhbz#12345)``` **is** recognized as a link - notice the space between '(' and 'r'.

Expected result:
The link is recognized without the space between the markup string and a word separator.

**Comment by bowlofeggs** [comment]
[This regex](https://github.com/fedora-infra/bodhi/blob/2.5.0/bodhi/server/ffmarkdown.py#L85) is supposed to match bz links:

```
BUGZILLA_RE = r'([\S]+)(#[0-9]{5,})'
```

I don't see anything immediately wrong with it, but this area of the code is probably where the issue is.

**Comment by bowlofeggs** [comment]
The fix for this issue will appear in the upcoming 2.11.0 release:

https://github.com/fedora-infra/bodhi/pull/1790
