### ISSUE TITLE
The Hack font uses a license that isn't in Fedora's approved license list

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1431]
Bodhi currently [bundles the Hack font](https://github.com/fedora-infra/bodhi/tree/2.5.0/bodhi/server/static/fonts/hack). I started working on packaging this font for Fedora and discovered that it has a [custom license](https://github.com/chrissimpkins/Hack/blob/6c2fcce1ce52917acf6e12632d58b3d2558e8be3/LICENSE.md) which isn't on [Fedora's list of approved licenses](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Good_Licenses_4). I [started a discussion on Fedora's legal list](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/MJ4Q3D6JLDVX4OHSF3YXY76Z6BYSKKQR/) to ask if we can include Hack in Fedora but it sounds like it may take some time to get a decision.

Since Hack is not currently approved for distribution with Fedora we need to remove it from Bodhi for now.

@ryanlerch I can do the work of removing Hack, but I'm no good at picking a suitable replacement font. Feel free to send a PR with a font you prefer over whatever I go with, so long as that font is on the Fedora approved license list.

**Comment by ryanlerch** [comment]
Sigh -- didn't realise this when i suggested Hack. Sorry!

For a bit more info on why they are using a different licence, here is a thread over at the hack repo:
https://github.com/chrissimpkins/Hack/issues/209

I think we could just drop back to Liberation Mono. IIRC, its in the fedora repos, so we shouldnt have an issue with it.

cheers,
ryanlerch

**Comment by bowlofeggs** [comment]
@spotrh Has decided to allow Hack in Fedora, so we can close this issue. I'll work on packaging it soon.

https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/2YZLPJB7EMSF6PJBLAUNSWKKMNA3NCD2/
