### ISSUE TITLE
If the signed handler misses messages, Bodhi will not recover

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1433]
If the signed handler misses fedmsgs about builds that get signed, Bodhi will not recover and the update will remain unsigned forever.

We could instead have ```bodhi-push``` do a query to find updates that have a request but aren't signed, and then double check with koji to see if they are signed or not. If they are signed, it can update the database, and if they are not it can skip them as it does today.

**Comment by parasense** [comment]
We just hit this topic. Apparently there was a fedmsg hickup a while back and some builds were not pushing, even though they were signed.

**Comment by sebwoj** [comment]
> We could instead have bodhi-push do a query to find updates that have a request but aren't signed, and then double check with koji to see if they are signed or not. If they are signed, it can update the database, and if they are not it can skip them as it does today.

We have:
https://github.com/fedora-infra/bodhi/blob/cbb2bb99bf2f1d17b7183b1a1605f7ffc371d5fc/bodhi/server/push.py#L34

**Comment by bowlofeggs** [comment]
Yeah looks like this was fixed a while ago. Thanks @sebwoj!
