### ISSUE TITLE
OpenQA results will display invalid results for modified updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1435]
@kparal [reported](https://github.com/fedora-infra/bodhi/pull/1418#issuecomment-293253427) an issue with the patch from #1418:

> @AdamWill can you please add ```&since=<last modified timestamp of that update id>``` to the URL? As it is currently written, this will display invalid results for freshly modified updates.

**Comment by AdamWill** [comment]
Eh, sure. We can do that. Note it's not a huge deal, it only means that 'in the short time between the update being modified and the tests being re-run, Bodhi will show the results from the pre-modification tests instead of no results'.

**Comment by kparal** [comment]
> it's not a huge deal

I'm of the opposite opinion. You're assuming too many things: a) tests will be re-run b) in a short time c) people will not often act based on outdated results. With enough scale (and we do have enough scale in Fedora), this will be happening very often. Once an OpenQA re-run job crashes, you'll be displaying a wrong result for an update indefinitely. Put similar "good enough" assumptions to the accompanying systems throughout infra and things start to break down. We need to put extra effort to make sure processes are reliable, especially when it's very simple to do so.

And this should be trivial to do so. I just don't know from which variable I can retrieve the last modification timestamp. But if no one else looks at this, I will.

**Comment by AdamWill** [comment]
I'm not saying we shouldn't do it, just that the world isn't burning down (and it's not as serious an issue as the description kinda implies - it can be read as suggesting the tests *never* get re-run).

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/bodhi/pull/1439 should fix this.
