### ISSUE TITLE
Don't display unrelated javascript notifications

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1453]
If I have a Bodhi update page open, notifications frequently pop up in the right bottom corner. The notifications are completely unrelated to the page I'm currently seeing. It seems that anyone doing any action whatsoever causes a notification to pop up on every page. This has the following disadvantages:
a) It adds visual clutter to the page with no obvious benefit.
b) It consumes considerable amount of CPU and doesn't allow the CPU to idle. If I have several Bodhi pages opened in my browser, it creates a frequent and unnecessary CPU load on my computer.

Can you please change the notifications to pop up only when they are related to the very update they are displayed for? I.e. OK/Error messages, updated edited messages, karma added messages - for that particular update.

**Comment by bowlofeggs** [comment]
Hello @kparal!

There is a "disable popups" option if you click on your user in the upper right of the page - does that help? I'm not 100% sure if that persists or not, but if it doesn't we could try to make it persist. If it does persist, does that satisfy the issue for you?

**Comment by kparal** [comment]
Interesting, I didn't know that. But what happens if I should receive an error message e.g. when editing the update, or when adding a comment (with a token timed out)? Any error is currently displayed as a popup. What happens if I have popups disabled?

Of course this doesn't help if I'm not logged in (which I'm often not), or when I want to receive some popups (I think it's still helpful to see popups regarding the current update displayed).

I've heard similar opinions from my colleague, no one really understanding why every action happening in Bodhi is displayed to everyone (except for it being cool, fedmsg and stuff :) ). That's what actually convinced me to report this issue. Is there any rationale behind that? It seems to me it would still be easier to change the default rather than asking people to disable popups and potentially lose on some important ones.

**Comment by bowlofeggs** [comment]
On Thu, 2017-04-20 at 00:21 -0700, Kamil Páral wrote:
> Interesting, I didn't know that. But what happens if I should receive
> an error message e.g. when editing the update, or when adding a
> comment (with a token timed out)? Any error is currently displayed as
> a popup. What happens if I have popups disabled?

That's a good question - I don't know.

> Of course this doesn't help if I'm not logged in (which I'm often
> not), or when I want to receive some popups (I think it's still
> helpful to see popups regarding the current update displayed).

True.

> I've heard similar opinions from my colleague, no one really
> understanding why every action happening in Bodhi is displayed to
> everyone (except for it being cool, fedmsg and stuff :) ). Is there
> any rationale behind that? It seems to me it would still be easier to
> change the default rather than asking people to disable popups and
> potentially lose on some important ones.

I don't know why the popups were made to show all activity, but I'm not
opposed to changing that behavior.

**Comment by kparal** [comment]
> I don't know why the popups were made to show all activity, but I'm not opposed to changing that behavior.

@pypingou or @ralphbean (or @lmacken) could know the original decision

**Comment by pypingou** [comment]
@lmacken or @ralphbean may remember the exact reason, my guess is that it might just be listening to fedmsg and showing all bodhi activity, we would need to check the sources to be sure and see if it does any filtering (or not).

**Comment by ralphbean** [comment]
> except for it being cool

This was the reason.

**Comment by ryanlerch** [comment]
Yeah, not 100% sure of the utility of having the notifications constantly pop up for everything that changes in Bodhi.

@kparal as a user of Bodhi, is having the notifications -- even if they are for the current update being viewed -- even useful? 

One additional thing to note too is that we use these notifications also for reporting errors (like form validation) So it is a even more cluttered, and multi-use area.

**Comment by kparal** [comment]
> @kparal as a user of Bodhi, is having the notifications -- even if they are for the current update being viewed -- even useful?

Sure, as you say, for confirmation of actions and displaying errors. It's also useful to know that somebody else commented on the same update (or some other action was performed), because the page doesn't automatically update - this way you know you should refresh it. All of that can be solved without notifications. But I don't really mind it, I just suggest that we don't use them excessively for unrelated events.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by bowlofeggs** [comment]
Yeah this is dropped in the upcoming 4.0.0 release.
