### ISSUE TITLE
add tooltips for update icons

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1454]
There's a green lightning bolt next to the update title in this update https://bodhi.fedoraproject.org/updates/FEDORA-2017-da42cd69ce and I have no idea what it means. It's a really fast update? :)

![icon](https://cloud.githubusercontent.com/assets/755451/25178371/da5d77d8-2505-11e7-873e-aca8fe7b8b56.png)

Can we please add tooltips to these icons?

**Comment by bowlofeggs** [comment]
Hello @kparal!

This was actually fixed in Bodhi 2.6.0 (see #1362), which is currently in staging. Here's a "really fast update" (☺) in staging that shows the way it works now:

https://bodhi.stg.fedoraproject.org/updates/FEDORA-2017-19451b76d6

**Comment by kparal** [comment]
Great, thanks!
