### ISSUE TITLE
new theme requires locating tiny magnifying glass to show search box

### ISSUE THREAD

**Issue by ippienui** [fedora-infra/bodhi#1455]
the primary thing I do on bodhi is search for a package, but this is made considerably more clumsy since I have to locate and click a tiny magnifying glass in order to get to the search box. is search a secondary feature for your typical users?? can't it always be displayed? if not, could you provide a cookie to remember whether the user has opened the search box?

**Comment by bowlofeggs** [comment]
Yeah I think I agree - it would be better if the search box was persistent. I think I also dislike that it animates when clicked and slides the page down.

**Comment by ryanlerch** [comment]
Okies, can work on getting this back.

It is worth noting that it does take exactly the same number of clicks to get the search done as before. I guess folks are just more used to seeing a large text box rather than just the typical search icon.

**Comment by lersek** [comment]
Can this ticket get some attention please? Please see https://bugzilla.redhat.com/show_bug.cgi?id=1516599#c25 and later comments in that BZ. Thanks!
