### ISSUE TITLE
We need alt text for the update status icons

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/bodhi#1463]
The meaning of the update status icons at the right of the name for update type and whether the update is on critpath are not always obvious the first time you see them.
We should probably add alt text with "Critical path" and "Security update" or "Enhancement", and the likes.

**Comment by pypingou** [comment]
I believe this has been fixed in: https://github.com/fedora-infra/bodhi/pull/1410 and https://github.com/fedora-infra/bodhi/pull/1365

**Comment by puiterwijk** [comment]
#1356 fixed this indeed, thanks.
