### ISSUE TITLE
Icons to the right of the update name don't have tooltips

### ISSUE THREAD

**Issue by robatino** [fedora-infra/bodhi#1468]
The icons indicating "critical path", "security", "enhancement", etc. to the right of the update name don't have tooltips. This would really help since it's not obvious from looking at most of those icons what they mean.

**Comment by bowlofeggs** [comment]
This was fixed in https://github.com/fedora-infra/bodhi/issues/1362 which is included in [2.6.0](https://github.com/fedora-infra/bodhi/releases/tag/2.6.0).
