### ISSUE TITLE
Need to disambiguate openQA results by flavor

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#1471]
Now I look at the openQA results displayed in the webUI in production, there's a problem. We run some of the same tests starting from both the Server and Workstation base images: the four `base_` tests. As Bodhi currently only queries by test name, it doesn't show all these results, it will only show one instance of each of those four tests, whichever one completed last.

This is basically the 'scenario' problem, which I was hoping we could just not worry about for the present, but we'll probably have to :/ I'll try and see how hard it is to come up with a viable and sensible fix for this that works with the way the code is currently set up.

**Comment by kparal** [comment]
You can look at the results received from `/latest` and get the full history (limited to X pages/entries) for those that have `scenario` key set and non-empty. But that assumes `scenario` is only set for those results which really do have different scenarios, and not set for results which are not needed to be de-duplicated. But I feel that's a reasonable recommendation in general for all tests, so unless you want to do it otherwise, we need to find a way to make that happen in openqa.
CC @rajcze

**Comment by AdamWill** [comment]
I didn't really intend to do things that way, no. I dunno why you always want to make the scenario concept so *complicated*. It's not meant to be complicated. It's an identifier, that's all it is. Every test has one, I don't see why we need to try and figure out whether anyone will ever need to de-duplicate this particular result by scenario at the time we send the result to resultsdb. That's just silly.

For the record, my initial thought on this is that for now we can just adopt the silly hack that's used for depcheck - give bodhi the special knowledge that a particular set of tests exists twice and tell it to go look for the other one. It's probably not worth trying to redo the whole thing around the scenario key quite yet, though I'll probably get there in future.

**Comment by kparal** [comment]
> I didn't really intend to do things that way, no. I dunno why you always want to make the scenario concept so complicated. It's not meant to be complicated. It's an identifier, that's all it is. Every test has one, I don't see why we need to try and figure out whether anyone will ever need to de-duplicate this particular result by scenario at the time we send the result to resultsdb. That's just silly.

If all results have a `scenario`, even those which don't need it, you won't know for which testcases to pull historical results (possibly containing other scenarios). So you need to do it for all of them. If you pull all history for all testcases, the `/latest` endpoint is useless, and we're back to pulling everything, which proved to be very performance demanding and which we wanted to avoid. What am I missing?

> For the record, my initial thought on this is that for now we can just adopt the silly hack that's used for depcheck - give bodhi the special knowledge that a particular set of tests exists twice and tell it to go look for the other one. It's probably not worth trying to redo the whole thing around the scenario key quite yet, though I'll probably get there in future.

OK, works for the moment.

**Comment by AdamWill** [comment]
kparal: it's this idea of a result "needing" a scenario which I disagree with. It's just the wrong way to think about it. Technically, we can't absolutely know for sure at the time we file a result whether we'll ever file another result which would need to be disambiguated from it by scenario. We can make a reasonable guess based on the set of tests we know we're running *right now*, but what if we change the set of tests we run tomorrow and now that result *does* 'need' a scenario? (No, we can't assume we'll never re-run the tests on an item we've already tested; we already know we *do* do this).

BTW, I also think just going ahead and querying *all* the openQA results and then disambiguating by scenario on the client side would actually work OK at least for now, because we just don't run that many tests per update. We don't have the problem that occasionally there will be hundreds or thousands of results. The realistic maximum for an update is gonna be ~100 and that'd be very unusual. So we can either do that, or what I suggested above, I guess.

I still think there's stuff we could do resultsdb side to improve this kind of case, but we can talk about that elsewhere :)

**Comment by AdamWill** [comment]
So I have code that does this now, but there's still a problem; you just get two apparently-identical entries for the 'duplicate' tests in the web UI (`update.base_selinux`, for example). Because Bodhi doesn't know that it should display the result flavor to disambiguate the results.

This isn't disastrous, of course, it still basically works. But it's probably confusing, and not *obvious* what the right way to fix it is. This kinda points up why, I think, during the scenario discussion, one of @kparal 's suggestions (which I didn't give much consideration to at the time) was for results not just to include a `scenario` value intended solely for disambiguation use, but to include all the keys that form part of the 'scenario' in the extradata, and *indicate which keys these are*. I didn't realize it at the time, but that solves a problem for consumers like Bodhi: it gives them a cue as to what values it might need to show in a human-visible view to distinguish results from each other...

Of course we can do all kinds of dumb short term stuff here (just teach Bodhi about openQA's scenarios - just like, again, we've effectively "taught" it Taskotron's scenarios, by having it display the arch where available), stuff the currently-necessary bits of the scenario into the test case name when reporting from openQA to rdb, etc etc.) but they all seem kinda...bad. Time for more thinking, I guess. Sigh.
