### ISSUE TITLE
"Auto-request stable" cannot be disabled once enabled.

### ISSUE THREAD

**Issue by xsuchy** [fedora-infra/bodhi#1482]
Hi,
I created errata and checked "Auto-request stable", next day I changed my mind and wanted to disable this option. So I in WebUI clicked on Edit and unchecked "Auto-request stable" and hit "Save". However the "Auto-request stable" is still enabled.

The temporary workaround is to raise karma treshold to unsane high number so the treshold is never reached.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
