### ISSUE TITLE
The UI doesn't make it clear that locked updates can't be edited

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1492]
@ignatenkobrain and I had a chat in #fedora-devel today where we were confused by the UI's lack of edit buttons on locked updates. We didn't realize at the time that the updates were locked, and only noticed that the edit buttons were missing. It seemed that there were issues with permissions, when really it was just that the update was locked.

Perhaps we could make it more obvious that locked updates can't be edited, while still acknowledging that the user does have edit permissions. One idea would be to continue showing the edit button, but grey it out or show a lock icon over it with a tooltip that says "This update is currently locked and cannot be edited." or similar.

**Comment by ryanlerch** [comment]
yeah, i think the best way here is to just show the "edit" button, but grey it out with a tooltip. Might need some more information on why it is locked too.

/me spent a while in his test instance trying to figure out how to lock an update to test this, then realised they get locked while it is being pushed. Might be good to explain a bit more here too.

**Comment by bowlofeggs** [comment]
@ryanlerch 

Ah yeah, there's probably not a built-in way to make an update be locked but you can use the fancy new ```bshell``` alias I just made to get in there and force an update to be locked. Here's an example:

```
In [1]: b = m.Update.query.filter(m.Update.alias == u"FEDORA-EPEL-2017-650d7b9356").one()

In [2]: b.locked = True

In [3]: from datetime import datetime

In [4]: b.date_locked = datetime.now()

In [5]: s().add(b)

In [6]: s().commit()
```

Now when I browse to http://localhost:6543/updates/FEDORA-EPEL-2017-650d7b9356 I can see the lock icon on the update.

Note that I am using a modification to my ```development.ini``` file here, which I just filed a pull request for:

https://github.com/fedora-infra/bodhi/pull/1528

You can either apply that change to your local ```development.ini```, or you could achieve the same thing by doing this in the shell before the commands that use ```s```:

```
from bodhi.server import Session as s
```
