### ISSUE TITLE
Modify the updates fedmsg-client to check/set the CI status for new updates

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#1514]
We need a fedmsg-client listening to messages from bodhi about new updates and edits to updates and checks the CI status of the builds associated with this update and adjust the CI status accordingly

**Comment by bowlofeggs** [comment]
There is an existing "updates" consumer that listens for new updates to do background processing - I think it makes sense to tack this feature onto it:

https://github.com/fedora-infra/bodhi/blob/2.6.2/bodhi/server/consumers/updates.py

**Comment by bowlofeggs** [comment]
This is blocked on https://pagure.io/greenwave/issue/26.

**Comment by ralphbean** [comment]
Are you unblocked now with https://pagure.io/greenwave/pull-request/27 ?

**Comment by bowlofeggs** [comment]
@ralphbean Indeed!

**Comment by bowlofeggs** [comment]
@pypingou You had assigned this to yourself, but I can probably do it if you don't still intend to. What say you?

**Comment by pypingou** [comment]
@bowlofeggs go for it, thanks :)

**Comment by bowlofeggs** [comment]
The patch for this feature has been included in the [```3.3.0b0``` build](https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html), which is currently deployed to [staging](https://bodhi.stg.fedoraproject.org).
