### ISSUE TITLE
get_updates_from_builds returns extra 'tg_flash' key

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#152]
There's an extra `tg_flash=None` key returned from all `get_updates_from_builds` calls. Nothing serious, but it would be great if I didn't have to work around it :)

```
>>> from fedora.client import BodhiClient
>>> import bunch
>>> result = bodhi.send_request(method='get_updates_from_builds', req_params={'builds':'rpy-2.6.1-1.fc21'})
>>> print result.keys()
[u'tg_flash', u'rpy-2.6.1-1.fc21']
```

python-fedora-0.4.0-2.fc22.noarch

**Comment by lmacken** [comment]
yeah, that's a side-effect of TurboGears. This will be solved in bodhi2. Keeping this issue open to ensure that this API gets ported ;)

**Comment by lmacken** [comment]
Issue obsoleted by bodhi2
