### ISSUE TITLE
bodhi --autokarma does not enable autokarma

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#1559]
bodhi command line with --autokarma option like
```
$ bodhi updates new --user mtasaka --type bugfix --notes-file ./updates.txt --request testing --autokarma --stable-karma 2 --unstable-karma -30  gnome-commander-1.6.4-1.fc24
```
does not enable automarka like https://bodhi.fedoraproject.org/updates/FEDORA-2017-d98279c793 (if you go to this URL, you will see that Autopush is "disabled"), although ``$ bodhi updates new --help`` shows:
```
  --autokarma                     Enable karma automatism
```

Note:
```
$ which bodhi | xargs rpm -qf
bodhi-client-2.6.2-1.fc26.noarch
```

**Comment by bowlofeggs** [comment]
I think this is a duplicate with #1378. Feel free to let me know if you disagree!
