### ISSUE TITLE
Add knowledge of branch freezes to the Release model

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1563]
We should add the ability for Bodhi to know when a branched Release is frozen. During freeze periods, the masher should avoid mashing updates that are request stable, but it should allow exceptions by looking for blocker bugs. This way, releng doesn't have to run ```bodhi-push``` two times (once for the f<branched>-updates-testing, and again for all other stable releases).

**Comment by ryanlerch** [comment]
Related: #1038

**Comment by bowlofeggs** [comment]
UX-wise, we could give the CLI these commands to freeze and unfreeze F29 (for example):

```
$ bodhi releases freeze F29
$ bodhi releases unfreeze F29
```

Alternatively, we could just let the edit command flip a bool:

```
$ bodhi releases edit --name F29 --frozen true
$ bodhi releases edit --name F29 --frozen false
```

**Comment by bowlofeggs** [comment]
Since I wrote my comment suggesting a particular UX for this, Infrastructure has added some Ansible configs to track the status of releases. Thus, I think it would be most convenient for them if we did this in the configuration file for now, rather than via the CLI/API as I suggested above.

@mohanboddu @nirik, would you agree?

**Comment by mohanboddu** [comment]
@bowlofeggs I still think its nice if bodhi knows what are the updates (testing only for a particular release and testing+stable for all other releases or testing+stable for all releases) that it needs to push depending on a release frozen status. So, your suggestion still helps, since the ansible config does all or nothing. So, if I say a release is frozen, then when bodhi-push is run it should push stable and testing updates for all other releases and testing only updates for frozen release.

**Comment by sebwoj** [comment]
So the question is how Bodhi can fetch information about frozen release? Is there an api for that?

**Comment by bowlofeggs** [comment]
On Sun, 2019-04-07 at 12:13 -0700, Sebastian Wojciechowski wrote:
> So the question is how Bodhi can fetch information about frozen
> release? Is there an api for that?

We should probably discuss this on the infrastructure mailing list as
it would be good to get feedback from the admins about how they would
like to express this information to Bodhi.

**Comment by sebwoj** [comment]
Duplication #105

**Comment by sebwoj** [comment]
Is it related to #794?

**Comment by bowlofeggs** [comment]
@sebwoj I think it's sort of related. The other ticket is about making it so Bodhi knows about a release before it manages it at all. This happens usually for about two weeks after Fedora branches a release from Rawhide. This ticket is about Bodhi not pushing out stable updates while continuing to push out testing updates during releng freezes (i.e., during the time that Bodhi does manage the release).
