### ISSUE TITLE
Don't disable autopush when the update is already requested for stable

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1570]
@ignatenkobrain reported today that [an update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-92e5a01da8) didn't have the push to stable button, even though Bodhi had commented on the update to say "Bodhi is disabling automatic push to stable due to negative karma. The maintainer may push manually if they determine that the issue is not severe." It turned out that the update had already been submitted for stable by reaching the karma threshold earlier. The comment from Bodhi that autopush was being disabled was confusing and misleading. Bodhi should not disable autopush if the update is already requested for stable, or if the update is already stable.

**Comment by surya-prakash-susarla** [comment]
@bowlofeggs  I would like to solve this bug as I am beginner and you've tagged it as easyfix. Could you help me where to get started ?

**Comment by bowlofeggs** [comment]
The fix for this issue will appear in the upcoming 2.11.0 release:

https://github.com/fedora-infra/bodhi/pull/1790
