### ISSUE TITLE
bodhi.server.util.taskotron_results doesn't use a timeout on its call to requests.get()

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1597]
bodhi.server.util.taskotron_results should use a timeout on its call to requests.get() so that it won't hang indefinitely if there are issues communicating with resultsdb. 60 seconds is probably reasonable.

**Comment by rimshaakhan** [comment]
Hello @bowlofeggs !

I would like to work on this issue, can you please assign it to me. Thanks!

**Comment by bowlofeggs** [comment]
Hello @rimshaakhan,

I don't think GitHub allows assigning issues to users who are not in the fedora-infra group, but you are certainly welcome to work on this issue (you don't have to be officially assigned to an issue to work on it). Just make sure you end your commit message with a line that says "fixes #1597" when you send your pull request. Thanks!

**Comment by bowlofeggs** [comment]
The fix for this issue will appear in the upcoming 2.11.0 release:

https://github.com/fedora-infra/bodhi/pull/1790
