### ISSUE TITLE
Get mcurlej access to composer.stg.phx2.fp.o

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1599]

**Comment by ralphbean** [comment]
https://apps.fedoraproject.org/datagrepper/id?id=2017-589c7f96-db85-4f39-b86a-a7d9892a3ebc&is_raw=true&size=extra-large

**Comment by ralphbean** [comment]
Filed infra ticket to sync prod fas to stg:  https://pagure.io/fedora-infrastructure/issue/6106

**Comment by ralphbean** [comment]
He's in!

**Comment by mcurlej** [comment]
@ralphbean @bowlofeggs i have my account and i can connect via SSH to composer.stg.phx2.fedoraproject.org
