### ISSUE TITLE
Unable to add mixed-result comments

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#160]
I don't really know how the feedback system is supposed to work, but when I try to set "basic system functionality" to +1 and "general behavior" to -1 (which seems valid), I receive "unable to create comment" popup, with no further explanation. I have no idea what's wrong. If it's my fault, can Bodhi be more descriptive and explain what's wrong?

![bodhi](https://cloud.githubusercontent.com/assets/755451/9328199/e8579e30-45a6-11e5-9015-1534a26febda.png)

**Comment by ralphbean** [comment]
It looks like this was all related to CORS issues that cropped up recently.  It should be fixed by #166.
