### ISSUE TITLE
[nice-to-have] Create a Pungi Python API so Bodhi can drive Pungi via Pungi functions

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1600]
Bodhi currently can only use Pungi by writing config files and calling it via subprocess. It'd be nice if Bodhi could use Pungi via a native Python API.

**Comment by ktdreyer** [comment]
That is how I call Pungi (in Jenkins) as well, so I'm interested in this feature.

**Comment by ralphbean** [comment]
OK, with the latest work done by @bowlofeggs and @puiterwijk, this isn't necessary from the bodhi modular-mash point of view.

@ktdreyer, if this is still something you're interested in, it may be worth pursuing it with pungi upstream.

**Comment by ktdreyer** [comment]
What was the resolution with Bodhi to which you're referring?

**Comment by ktdreyer** [comment]
What I mean is: will Bodhi still execute Pungi?

**Comment by bowlofeggs** [comment]
Hello @ktdreyer,

Bodhi will still execute Pungi, but will do so by calling it via subprocess rather than importing it. See https://github.com/fedora-infra/bodhi/pull/1900.
