### ISSUE TITLE
Pungi needs to be able to accept full NSVs of modules in variants-modular.xml

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1602]
Pungi’s use of <modules> in [variants-modular.xml](https://pagure.io/pungi-fedora/blob/f26/f/variants-modular.xml) needs to be extended so that the user can optionally specify the full NSV of the module.  Currently, it only takes the name (N) and the stream (S) and it looks up the latest version (V) of that module-stream in PDC.  For Bodhi (and for other use cases; ask ralph) it would be nice to accept the full NSV so bodhi can compose the updates repo using exactly the content it wants, not just whatever’s latest in the build system.
Jkaluza wrote the first pass at this.  To adapt it, ask him where to go.

**Comment by mcurlej** [comment]
https://pagure.io/pungi/pull-request/652

**Comment by mcurlej** [comment]
@bowlofeggs The pull request in pagure was merged. I think this can be closed.

**Comment by bowlofeggs** [comment]
Thanks!
