### ISSUE TITLE
Ask releng what is special about an updates repo

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1603]
ask release engineering if there are any special properties that the updates repo needs to have that the compose repos don’t have.  We only know of updateinfo.xml and deltarpms.
Tell them we want to do f27 modular updates repos with no deltarpms.

**Comment by mcurlej** [comment]
@bowlofeggs @ralphbean  the only diff is the updateinfo.xml, everything else is the same as with just a "normal" created repo. Btw the mash is in general just a repo generated by mash + updateinfo added on top by bodhi.

**Comment by bowlofeggs** [comment]
On Thu, 2017-06-29 at 12:18 +0000, Martin Curlej wrote:
> @bowlofeggs the only diff is the updateinfo.xml, everything else is
> the same as with just a "normal" created repo. Btw the mash is in
> general just a repo generated by mash + updateinfo added on top by
> bodhi.

Cool, thanks for answering the question - I'd asked a few times in the
#fedora-releng channel but haven't gotten an answer. I'm gonna close
this issue.
