### ISSUE TITLE
The home page doesn't show stats for branched releases

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1619]
The home page doesn't show stats for branched releases, for example, Fedora 26 at the time of this writing.

**Comment by keszybz** [comment]
I think this *might* be on purpose: in the drop-down menu, F26 is separated at the bottom. Nevertheless, I think that's a bad choice, because most of the users of that page are Fedora packagers and testers, for whom branched is of primary interest.
