### ISSUE TITLE
improve docs for query(builds=)

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#162]
`get_updates_from_builds()` has been removed and `query(builds=)` was introduced instead. That's fine. But I'm quite unclear how it works in certain use cases and it would be great to have that clarified in the docstring.
- What happens if I specify multiple builds from the same update, will I receive the same update object once or several times? My experiments suggest I get it just once.
- What happens if the same build is part of several updates? Can that even happen? I assume an update can get e.g. obsoleted and then the same build can be reused. Does `query(builds=)` return just the latest one in that case, or all of them? If I query build by build sequentially, I can get just the latest one with `limit=1`. I assumed `get_updates_from_builds()` also worked like that. But I'm not sure how it works with `builds=`.
- The output is unsorted it seems. It makes processing a bit harder (when compared to `get_updates_from_builds()`), it could be worth mentioning in the docstring as well.

I'd love to know the answer to the second question before Bodhi 2.0 is pushed to production :) Thanks.

**Comment by ryanlerch** [comment]
@kparal not sure if this was added after your initial filing of this issue, but the docstring for bodhi.client.bindings.query(builds=) has a pretty substantial docstring now. 

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/bindings.py#L204

Does that docstring currently answer your questions, or do you think more detail in there is still required?

**Comment by kparal** [comment]
I think I don't need this anymore anyway. Thanks, though.
