### ISSUE TITLE
Mouseovers on home page could tell users what the update type counts mean

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1620]
langdon requested that we add mouseovers on the home page update-type counts to explain what they mean. We could write something like "There are 511 stable security updates in Fedora 25.", for example.

**Comment by langdon** [comment]
Specifically, to clarify what the icons mean on the breakdowns (which is on the interior pages)

**Comment by rimshaakhan** [comment]
Hey @bowlofeggs !  I would like to raise a PR .
Thanks!

**Comment by bowlofeggs** [comment]
I noticed today that the center column (about testing updates) on the updates do have mouseovers, but the pending and stable ones do not.

**Comment by bowlofeggs** [comment]
@rimshaakhan Go for it!

**Comment by ryanlerch** [comment]
Whoops! Sorry about that. For some reason, i didnt add titles to the icons for the Pending and stable ones.

adding a title, and activating the bootstrap tooltips is what needs to be added here, e.g: `title="New Package updates" data-toggle="tooltip"`

**Comment by ryanlerch** [comment]
@rimshaakhan are you still planning on working on this one?

**Comment by bowlofeggs** [comment]
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
