### ISSUE TITLE
bodhi config hasn't been updated in production

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#1663]
When looking into Fedora infra ansible, I still see this:

```
$ git grep depcheck
...
roles/bodhi2/base/templates/production.ini.j2:site_requirements = depcheck upgradepath
roles/bodhi2/base/templates/production.ini.j2:#site_requirements = depcheck upgradepath rpmgrill
roles/bodhi2/base/templates/staging.ini.j2:site_requirements = depcheck upgradepath
roles/bodhi2/base/templates/staging.ini.j2:#site_requirements = depcheck upgradepath rpmgrill
...
```
But it should be (per current `production.ini`):
```
# site_requirements = dist.rpmdeplint dist.upgradepath
```
As you can see, old values are still used. I believe the config needs to be updated in ansible and deployed so that the changes are applied to Bodhi servers.

**Comment by bowlofeggs** [comment]
Thanks for the report @kparal!

Since this is a deployment concern I've refiled this issue in the infra ticket system so we can track it there"

https://pagure.io/fedora-infrastructure/issue/6142

I asked a question for you there, if you have a moment to answer. Thanks again!
