### ISSUE TITLE
RFE: When logged in, show my pending updates on the front page

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/bodhi#1672]
I've always found it odd that I have to look at my profile to see the status of the updates I've submitted while the front page always shows generic information even when I'm logged in.  It it possible to have the front page show important information like that when I'm logged in, even if it's just a summary or a bootstrap notification at the top telling me that I have X updates that can be pushed to stable?

**Comment by bowlofeggs** [comment]
I like this idea, thanks!

**Comment by keszybz** [comment]
+1. It would be really great in the listing of updates to be able to see which are "actionable" updates, i.e. the ones which already passed the push criteria.

**Comment by ryanlerch** [comment]
#3500 implements a new front page, that shows your pending + testing updates when logged in now.

This is merged in develop.

cheers,
ryanlerch
