### ISSUE TITLE
Editing a bodhi update re-enables the auto-push checkbox

### ISSUE THREAD

**Issue by labbott** [fedora-infra/bodhi#1692]
If I've turned off auto-push on and update and go to edit it, I notice the auto-push checkbox is checked again. I need to explicitly uncheck it each time, otherwise the update will have auto-push enabled.

I expect the update to keep the auto-push off even with edit.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
