### ISSUE TITLE
Markdown linkified links without http:// produce relative href= attr

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#1721]
if you add a link to a markdown field (update description or a comment) without the http:// (or an email address), the custom fedora-markdown code linkifies this, but produces a relative link. For example, including the string `the fedora project website is getfedora.org` produces the following html markup:

```
the fedora project website is <a href="getfedora.org">getfedora.org</a>
```
which tries to link to `http://bodhi.fedoraproject.org/getfedora.org`

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
