### ISSUE TITLE
deploy a cronjob that periodically expires buildroot overrides

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#173]
In ``bodhi/scripts/`` there's a script for it.  We just have to deploy it as a cronjob.

**Comment by br0ziliy** [comment]
@ralphbean I suppose that should go somewhere in `roles/bodhi2/backend/tasks/main.yml` in Ansible, right?

**Comment by ralphbean** [comment]
Yes, exactly!

**Comment by lmacken** [comment]
This has been done (issue #616)
