### ISSUE TITLE
Unable to determine release from build

### ISSUE THREAD

**Issue by teigland** [fedora-infra/bodhi#1732]
Why is this happening?

$ fedpkg update
Creating a new update for  sanlock-3.5.0-1.fc26 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 93, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: Invalid tag: sanlock-3.5.0-1.fc26 not tagged with any of the following tags [u'f22-updates-candidate', u'dist-6E-epel-testing-candidate', u'f21-updates-candidate', u'f24-updates-candidate', u'epel7-testing-candidate', u'f25-updates-candidate', u'dist-5E-epel-testing-candidate', u'f23-updates-candidate', u'f26-updates-candidate']
Unable to determine release from build: sanlock-3.5.0-1.fc26
Could not execute update: Could not generate update request: Command 'bodhi --bodhi-url https://bodhi.fedoraproject.org/ --new --release f26 --file bodhi.template sanlock-3.5.0-1.fc26 --username teigland' returned non-zero exit status 1

Or on the web:

Builds : Unable to determine release from build: sanlock-3.5.0-1.fc26
￼×
Builds : Invalid tag: sanlock-3.5.0-1.fc26 not tagged with any of the following tags [u'f22-updates-candidate', u'dist-6E-epel-testing-candidate', u'f21-updates-candidate', u'f24-updates-candidate', u'epel7-testing-candidate', u'f25-updates-candidate', u'dist-5E-epel-testing-candidate', u'f23-updates-candidate', u'f26-updates-candidate']

**Comment by teigland** [comment]
So I tried to do a new build, and more errors

$ fedpkg build
Your git configuration does not use a namespace.
Consider updating your git configuration by running:
  git remote set-url origin ssh://teigland@pkgs.fedoraproject.org/rpms/sanlock
Kerberos authentication is used, but you do not have a valid credential.
Please use kinit to get credential with a principal that has realm FEDORAPROJECT.ORG
Could not execute build: Could not login to https://koji.fedoraproject.org/kojihub

**Comment by bowlofeggs** [comment]
It appears that ```sanlock-3.5.0-1.fc26``` is tagged as ```trashcan``` instead of with a tag that Bodhi can use. This is likely due to the build being fairly old:

https://koji.fedoraproject.org/koji/buildinfo?buildID=885191

I think Koji deletes builds if they sit around unused in a repo for a while. Thus, you will need to get a build that is tagged as ```f26-updates-candidate``` in Koji before Bodhi can use it.

The second comment you made is not related to Bodhi, but it seems that you just need to get kerberos credentials in order to authenticate to Koji. You can probably do this:

```
$ kinit teigland@FEDORAPROJECT.ORG
```
