### ISSUE TITLE
HTTP 400 instead of 403 when users don't have ACLs to edit a package

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1737]
I noticed today that I get an HTTP 400 when I try to visit https://bodhi.stg.fedoraproject.org/updates/FEDORA-2017-5ce9d89b82/edit when I am logged in to staging Bodhi, but I get a 403 when I visit it and am not logged in. The 400 should be a 403.

**Comment by amitsin6h** [comment]
let me take this as my first bug fix.

**Comment by bowlofeggs** [comment]
@amitsin6h Go 4 it!

**Comment by linux-modder** [comment]
@amitsin6h if you need any help I'm also willing to help you.

**Comment by egegunes** [comment]
After a quick look, it seems fixed? I visited https://bodhi.stg.fedoraproject.org/updates/FEDORA-2017-5ce9d89b82/edit when I'm logged in and not logged in and got 403 both times.

**Comment by bowlofeggs** [comment]
@egegunes hmm, I just tried again and I still get a 400 when I am logged in and visit that page.

**Comment by steaksauce-** [comment]
@bowlofeggs I get a 403 in both scenarios as well.

Might be a bit of a hassle, but what happens if you create a new account and reproduce the steps? Maybe it has something to do with something with your account.

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This fix is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by bowlofeggs** [comment]
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.
