### ISSUE TITLE
Bodhi comments that critical path updates have reached 7 days when they get to 14 days in testing

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1741]
Lukas Slebodnik [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1480070) that Bodhi put a comment "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes" when his update reached 14 days in testing.

I'm guessing this happened because the code that fills out that template doesn't consider whether the update is critical path or not. Critical path updates have different testing requirements than regular updates (in the case of Fedora, critical path updates should be in testing for 14 days instead of 7 when not meeting karma requirements.)

If my guess is correct, this should be an easy fix.

**Comment by RozzaysRed** [comment]
I wouldn't mind taking trying to take this one on.  I just joined so it may take me some time for me to get familiar with what is going on.

**Comment by bowlofeggs** [comment]
@ryanrowse Go for it!

**Comment by ghost** [comment]
@bowlofeggs I would like to know if this issue still persists.

I tried to reproduce this issue by calling the ```approve_testing``` method using ```development.ini``` settings on a critical path update, however obtained appropriate comment for the update (14 days).

This issue was last seen in November 2017 in [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-d9fb12e2aa). After this, I believe there is no critical path update with incorrect comment.

**Comment by steaksauce-** [comment]
Is there any update on this?

**Comment by bowlofeggs** [comment]
@steaksauce- have you experienced this issue?

**Comment by steaksauce-** [comment]
> @steaksauce- have you experienced this issue?

@bowlofeggs nope, just being pushy :p 

I saw @vismay-golwala 's response and thought maybe this is a non-issue anymore

**Comment by bowlofeggs** [comment]
On Mon, 2018-10-29 at 17:10 +0000, Ben wrote:
> @bowlofeggs nope, just being pushy :p
> I saw @vismay-golwala 's response and thought maybe this is a non-
> issue anymore

Ah - I haven't had time to verify it myself yet, though it would be
helpful to get another verification if you want to check it out!

**Comment by keszybz** [comment]
Bodhi now says "This update can be pushed to stable now if the maintainer wishes", without any reference to time, so this can be closed.
