### ISSUE TITLE
Bodhi will respect double newline characters in comment input but not single newlines

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1747]
@peullid reported this in a [comment](https://github.com/fedora-infra/bodhi/issues/748#issuecomment-320132922):

take the following input:
> line one
> line two
> 
> line three

bodhi changes the above to:
> `<p>line one line two</p>`
> `<p>line three</p>`

which renders roughly as:
> line one line two
> 
> line three

**Comment by ryanlerch** [comment]
This is expected behaviour for Markdown, it allows a user to input hard wrapped text. Here is the section from the original Markdown:

https://daringfireball.net/projects/markdown/syntax#p

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.
> 
> The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. 

IMHO, we should not change this behaviour, as it is a core feature of Markdown. Additionally, Changing this behaviour now would likely break the rendering of a multitude of comments and descriptions that are already stored in Bodhi.

**Comment by peullid** [comment]
@ryanlerch

I can't make sense of your comment, or of the relevant portion of the text you link to. It doesn't seem like we're even on the same page with the definition of hard wrapped text. How does taking away a user-inserted line break "allow a user to input hard wrapped text"? Can you define what hard wrapping means to you? Can you give an example of when a user would want a line break they manually inserted to be removed? do you really expect more comments would be broken by rendering user-inserted line breaks than are broken by the unexpected (by many(?) by most(?) by at least bowlofeggs and myself) removal of those line breaks? (and does it really matter that much if old comments and old update descriptions _might_ be affected? (and do the descriptions and the comments _have to_ be treated the same?)) do you expect that more people are familiar with the daring fireball markdown than the markdown used by e.g. github (which does not remove such line breaks)? is it really more useful and important for (usually simple) comments in an update system to adhere to strict and bizarre requirements suggested by daring fireball? how is it helpful for the text as rendered in the editor itself to be rendered in a syntactically different way on output? or, perhaps the most relevant question -- what do you think the user meant to do by inserting the line break if not to include that line break in the rendering of their text?

**Comment by ryanlerch** [comment]
The syntax definition on Daring Fireball is the original Markdown, and I included it to reference why the renderer is not respecting line breaks in this manner. The idea behind this is that if you include hard breaks within a single paragraph, (i.e. not a blank line in between), then the text is assumed to be in the same paragraph, so it renders it in the same &lt;p&gt; element.

Github flavoured Markdown (GFM) renders hard-wrapped text with the linebreaks in comments, but when rendering files like a README, it uses the Original Markdown behaviour that bodhi currently adheres too.

We could have two slightly different markdown syntaxes for update descriptions and comments, but not sure if we want to make such a spilt, as we will have two slightly different behaviors for Markdown input.   

the worry for me here is really breaking old comments & descriptions. If people have posted comments and descriptions using the current behaviour, they are not going to render the same. We also have the bodhi CLI where users are more likely to hard-wrap text in the same paragraph, and it is nicer to render this in HTML as a single paragraph not littered with &lt;br&gt;s

**Comment by peullid** [comment]
> the worry for me here is really breaking old comments & descriptions

this could be worked around by rendering the line breaks for comments which were made after the date on which the newer version of bodhi is installed, and not rendering for earlier comments.

> We also have the bodhi CLI where users are more likely to hard-wrap text in the same paragraph, and it is nicer to render this in HTML as a single paragraph not littered with `<br>`s

this use case could be accommodated by removing single line breaks for comments submitted via the command line client, and leaving them for comments submitted through the web interface. the removal could be done on either the client side (before transmission) or the server side (before storage).

**Comment by puiterwijk** [comment]
Given that the markdown documentation on the Create Update page says that we provide an extension of the Daring Fireball markdown, I think we should adhere to all the rules set out in that markdown definition.
As specified in the quote by Ryan, single linebreaks are supposed to be in the same paragraph, and if users want a hard line break they can press the return key twice.

In my opinion, the current implementation is correct.

**Comment by puiterwijk** [comment]
Also, using two different flavors of markdown within the same application is, in my opinion, crazy. Github might do this, but I don't think we should

**Comment by bowlofeggs** [comment]
I'm convinced that @ryanlerch and @puiterwijk's arguments are sound and that the current behavior is sane. Thanks for the comments!
