### ISSUE TITLE
Config has wrong url to comps repo

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#1761]
Currently the comps url is set to https://git.fedorahosted.org/comps.git

https://github.com/fedora-infra/bodhi/blob/a81b8f1c45ba564c0c367137109249089ba06e58/bodhi/server/config.py#L332-L333

It should be using https://pagure.io/fedora-comps.git

**Comment by bowlofeggs** [comment]
@mohanboddu That is just the default value for ```comps_url``` if it is not defined in ```production_url```. You can see that Fedora's instance is correctly defined when looking at the Ansible config:

https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/bodhi2/base/templates/production.ini.j2#n142
