### ISSUE TITLE
The client should not use USERNAME

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1789]
The CLI can use the ```USERNAME``` environment variable to identify a user's username. This name is problematic because GDM sets ```USERNAME```, and not everyone uses the same username on their desktop machine as they do for their FAS username.

We have a few options:

1. Don't use environment variables at all to identify usernames. This was used to work around the way that the bodhi 2 client used to do auth - it didn't have a good way before to know the username other than requiring users to type ```--username bowlofeggs``` on each command, which was a pain. Now it has the ability to use past successful authentications to determine the username, and can also prompt for the username if there isn't an existing cookie. Unfortunately, this would be a backwards-incompatible change.
2. Add a new ```BODHI_USER``` environment variable. The namespacing would make this unique enough not to conflict with other things. If this is present, it would supercede the ```USERNAME``` environment variable, and we could remove support for ```USERNAME``` in a future release of Bodhi.
3. Same as 2, but go ahead and also drop support for ```USERNAME```.

I suppose the main question in my mind is whether it is time to go ahead and release a Bodhi 3. I'm not afraid to rev the X bit, but I'd prefer not to do it too often. Perhaps 2a would be good to do for now?

**Comment by tyll** [comment]
fedora-cert reads the Fedora username nowadays from ```~/.fedora.upn``` therefore it could be used (again?). Then there is only one place to set the FAS name instead of multiple places.

**Comment by bowlofeggs** [comment]
We are about to release bodhi-3.0.0, because Bodhi is switching to Pungi instead of mash and that changes the repo layout (and is thus technically not backwards-compatible). As a result, I'm going to prioritize this. I'm going to take the easy route for now and just drop support for the USERNAME variable. We can add it back later in a Y release if we need it.
