### ISSUE TITLE
Package.fetch_test_cases() never removes tests

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1794]
It seems that QA tests that are removed from the Wiki do not get removed in Bodhi. I took a peek at the [code](https://github.com/fedora-infra/bodhi/blob/2.10.1/bodhi/server/models.py#L665-L707) that synchronizes Bodhi's Package test cases with the Wiki, and I observed that it adds new test cases it finds in the wiki to Packages, but it does not remove old ones:

```
        for test in set(list_categorymembers(wiki, cat_page)):
            case = db.query(TestCase).filter_by(name=test).first()
            if not case:
                case = TestCase(name=test, package=self)
                db.add(case)
                db.flush()
```

There should also be a mechanism in there to find tests that are associated with the Package that are no longer found by ```list_categorymembers()```. It would probably also be good to clean up orphaned tests when unlinking them from a Package leaves them linked to no other Packages (and they might have a 1-1 relationship anyway, not sure...)

Here's an example update that should not have https://fedoraproject.org/wiki/User:Pschindl/Draft/Testcase_Custom_partitioning?rd=User:Pschindl/Draft/Testcase_Anaconda_custom_partitioning associated with it anymore:

https://bodhi.fedoraproject.org/updates/FEDORA-2017-5361e86979

@AdamWill reported this problem via IRC today.

**Comment by AdamWill** [comment]
The relationship isn't necessarily 1:1, no. Wiki pages can be in as many categories as they like, so we *could* have a test case associated with more than one package, just by being in both categories. We may actually have some like that already, in fact.

**Comment by bowlofeggs** [comment]
The database model does have a foreign key to a package, though does not put a uniqueness constraint on the name. So the name isn't unique, but a model using that name can only reference one package.

**Comment by bowlofeggs** [comment]
Ugh, and the code is querying for existing test cases by *name*, even though that's not unique in the db or wiki. Fun!

**Comment by bowlofeggs** [comment]
This keeps getting more fun. The TestCase model is also associated with the *package*, not an update (i.e., kind of a set of package instances). This means that it would actually be wrong to remove a test case from a Package, because that would remove it from historic updates too.

It seems like it would be more logical to associate TestCases with Updates, or even Builds (a Build is essentially an instance of a Package), so we can capture the way they change over time.

This is turning out to be a very fun ticket indeed.

**Comment by AdamWill** [comment]
you're welcome ;)

**Comment by mattiaverga** [comment]
I'm working on move the association of TestCase model from Package to Update (or Build, I've not decided yet what's best).
That should cover other two related open bugs #824 and #2979
