### ISSUE TITLE
Web UI will not allow manual push of updates that meet the minimum karma threshold

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#1796]
Previously - I'm not sure *exactly* when this changed - the Bodhi web UI would let you manually submit updates for stable so long as they'd reached a certain set of karma requirements, *even if they had not met the autopush 'karma threshold' for the update*.

Now, however, it doesn't. If an update has +2 karma and no negative karma, but hasn't reached whatever karma threshold was set for auto-pushing the update, you can't push it stable manually either, through the web UI (it shows no "push to stable" button for the update). You *can*, however, push it stable via the CLI.

I believe this is because the template for the update page (`update.html`) just does this, to decide whether to show the button:

            % elif update.meets_testing_requirements and getattr(update.request, 'description', None) != 'stable':
              <a id='stable' class="btn btn-sm btn-success"><span class="fa fa-fw fa-arrow-circle-right"></span> Push to Stable</a>

However, the `meets_testing_requirements` method doesn't *really* cover all the possible ways in which an update can reach the requirements to be pushed stable. If you look at the code which the server uses to decide whether to accept a stable push request that was sent in some other way, this becomes clear:

        if action in (UpdateRequest.stable, UpdateRequest.batched) and not self.critpath:
            # Check if we've met the karma requirements
            if (self.stable_karma not in (None, 0) and self.karma >=
                    self.stable_karma) or self.critpath_approved:
                log.debug('%s meets stable karma requirements' % self.title)
            else:
                # If we haven't met the stable karma requirements, check if it
                # has met the mandatory time-in-testing requirements
                if self.mandatory_days_in_testing:
                    if not self.met_testing_requirements and \
                       not self.meets_testing_requirements:

(that's in `set_request`). Note that with this code, the request will *also* be accepted if `self.critpath_approved`, *even for a non-critpath update*. `critpath_approved` is a property which is basically true if the update has +2 total karma (or if some kinda admin approval override is in place).

So, when submitting a stable request via the CLI (or some other way besides the web UI), it will be accepted if the update has +2 karma, even if the update *hasn't* reached the 'Stable karma' specified in the update's properties and hasn't waited around for 7 or 14 days. But the web UI will not draw a 'push to stable' button in this case.

Here's what the updates policy has to say about all this, btw:

     Updates to 'critical path' packages

    Updates that constitute a part of the 'critical path' package set (defined below) including security updates MUST follow the rules as defined for critical path packages for pending releases, meaning:

        At the time of the request to stable, the update needs to have either a Bodhi karma sum of 2 OR
        It must spend at least 14 days in updates-testing AND have no negative Bodhi karma points.

     All other updates

    All other updates MUST either:

        reach the criteria laid out in the previous section OR
        reach the positive Bodhi karma threshold specified by the updates submitter OR
        spend some minimum amount of time in updates-testing, currently one week 

So the CLI behaviour *is* correct, according to the policy - the policy allows both critical path and non-critical-path updates to be pushed stable so long as they "have a Bodhi karma sum of 2", regardless of waiting time or 'stable karma' threshold set in the update itself.

Here's what I remember about all this from long ago: I *thought*, initially, we allowed manual push of any non-critpath update with +1 karma or critpath update with +2 karma regardless of other considerations. The per-update 'stable karma' setting in Bodhi was *only* supposed to be used for *automatic* push to stable, which was considered to be effectively a convenience feature, not a policy-based gating mechanism per se - the idea was that you could set a threshold at which the update would be *automatically* pushed stable, with the restriction of course that you couldn't set the threshold to be more liberal than the policy rules (so it shouldn't be possible to set an autopush threshold of 1 for a critpath update). I don't remember there being any intent that there be a per-update 'stable karma' threshold which applied to *manual* pushes, after all, that seems a bit weird - if the update submitter wants to only push an update stable manually when it hits +4, not +2, all they have to do is...do that. They don't really need some kinda mechanism to help them with it.

However, at some point, the updates policy got that odd language about "reach the positive Bodhi karma threshold specified by the updates submitter". I might talk to FESCo about whether that really makes any sense. It does have the *effect* of allowing non-critpath updates to go stable with just +1 karma (by letting the update submitter set the 'stable' threshold to 1), but it's an odd way of going about it.

Finally...the code around all this seems rather messy and awkward to me, it could stand some refactoring, I think...

**Comment by bowlofeggs** [comment]
This should get fixed when https://github.com/fedora-infra/bodhi/pull/3310 is merged.
