### ISSUE TITLE
Port the Masher

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#18]
- [x] Make it a stand-alone daemon instead of running it from apache
- [x] multithreading support
- [x] Make the mashing lock release-specific, so we can push multiple Fedora releases at the same time
- [x] Fix the queueing of pushes
- [x] Verify that the message was sent by someone in releng
- [x] Determine which updates to push
- [x] Lock updates
- [x] Lock repo, keep track of state (builds in the push, completed repos, etc)
- [x] Perform gating based on Taskotron depcheck results
- [x] Make sure things are safe to move? (ideally we should trust our own state)
- [x] Update security bug titles
- [x] Move build tags
- [x] Expire buildroot overrides
- [x] Remove pending tags
- [x] Update comps.xml
- [x] mash
- [x] request_complete
- [x] Add testing updates to updates-testing digest
- [x] Generate/update updateinfo.xml
- [x] Inject the updateinfo it into the repodata
- [x] Sanity check the repo
- [x] Flip the symlinks to the new repo
- [x] Cache the new repodata
- [x] Generate stable update notices
- [x] Wait for the repo to hit the master mirror
- [x] Send fedmsgs
- [x] Update bugzillas
- [x] Add comments to updates
- [x] Email stable update announcements
- [x] Email updates-testing digest
- [x] Unlock repo
- [x] Unlock updates
- [x] See if any updates now meet the stable criteria, and set the request

**Comment by lmacken** [comment]
Done! :tada:

**Comment by ralphbean** [comment]
:zap: :facepunch: :zap:
