### ISSUE TITLE
RFE: Add way to revoke update for archived release or cancel them automatically after some time

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#1802]
Hi,

when I use CLI interface to list my updates, which are in pending/testing phase, I got listed even updates, which are for archived release and I cannot revoke or cancel them. Would you mind adding any means to deal with them?

**Comment by bowlofeggs** [comment]
Hello, and thanks for reporting!

I believe this is a duplicate of https://github.com/fedora-infra/bodhi/issues/752, especially given my proposed fix.

**Comment by zdohnal** [comment]
Yes, you're right, that's totally what I would want. Sorry for duplicate, I missed that one.
