### ISSUE TITLE
document query(alias=) and query(updateid=)

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#181]
The new fields were added in #164, but they do not show up in the docstring.

python-fedora-0.5.4-1.fc22.noarch

**Comment by kparal** [comment]
Btw, it would be great to also clear the confusion between `alias` and `updateid`. Because the web UI now mentions `Update ID`, the API returns `update['alias']` and `update['old_updateid']`. If `query()` is going to take `alias=` and `updateid=`, it's going to be somewhat confusing. "Alias" would be used in 2 out of 3 places, and "update id" would be used in (different) 2 out of 3 places.

**Comment by rahulbajaj0509** [comment]
I would like to make the changes.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release

**Comment by bowlofeggs** [comment]
This feature is now deployed to Bodhi's production instance.
