### ISSUE TITLE
Pagure doesn't expand group membership for ACL purposes, and neither does Bodhi

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1810]
We [learned today](https://pagure.io/fedora-infrastructure/issue/6357) that Pagure no longer expands group members when asked for ACL info. Bodhi also doesn't know all the groups a user is part of, because it only  pays attention to special groups (like packager or releng). Since neither end is doing it, Bodhi is now unable to grant access to committers who have ACLs through group membership.

@puiterwijk has proposed adding a new query parameter to Pagure's API that would ask it to again expand group membership for us. If that feature is granted to Pagure then Bodhi could just have a small patch that adds that query parameter to the existing query and be back in business.

Alternatively, there is also a Pagure API that can be used to ask for group members. For [example](https://src.fedoraproject.org/api/0/group/rpm-software-management-sig):

```
{
  "creator": {
    "fullname": "Release Engineering",
    "name": "releng"
  },
  "date_created": "1501864801",
  "description": "Group rpm-software-management-sig",
  "display_name": "rpm-software-management-sig",
  "group_type": "user",
  "members": [
    "releng",
    "ignatenkobrain",
    "jsilhan",
    "mluscon",
    "jmracek",
    "mhatina"
  ],
  "name": "rpm-software-management-sig"
}
```

Bodhi could use this API to expand group membership as well, though this approach would not perform as well as having Pagure expand membership as proposed above.

**Comment by pypingou** [comment]
I was looking at bodhi's code to see which API endpoint it is calling to help fixing this. As far as I can see it's querying the api/0/ns/project endpoint and afair that endpoint did not change. So I'm not sure what went wrong :(
