### ISSUE TITLE
symlink check is not valid

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/bodhi#1819]
https://github.com/fedora-infra/bodhi/blob/33d1e733d88bc891e00bf9f0e09d471360253ab1/bodhi/server/consumers/masher.py#L723-L729

The code is checking `.rpm` files under `mash_path, arches[0]` but you can see from [this example](https://kojipkgs.fedoraproject.org/mash//updates/f26-updates-170804.1348/f26-updates/x86_64/) that no rpm files exist. They are just directories.

**Comment by bowlofeggs** [comment]
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
