### ISSUE TITLE
Bodhi2Client(staging=True) doesn't work

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#182]
Instead the production URL is used.
```
In [23]: bodhi = Bodhi2Client(staging=True)

In [24]: bodhi.base_url
Out[24]: 'https://admin.fedoraproject.org/updates/'
```

python-fedora-0.5.4-1.fc22.noarch

**Comment by laxathom** [comment]
The way it has been designed for now is to use ```BodhiClient()``` function which will return Bodhi2Client's object with the right data.
You should not instantiate it directly if you want to talk to bodhi2.

I will let @lmacken or @ralphbean explain why it has been designed this way.

**Comment by kparal** [comment]
I asked about that in #183. Currently in libtaskotron I've proposed a patch which uses Bodhi2Client explicitly [1], to avoid network connections during object initialization. What is wrong with using versioned client classes?

If they are not meant for public use, they should be marked private (starting with an underscore). And if `staging=` doesn't work, it shouldn't be there. I think :)

[1] https://phab.qadevel.cloud.fedoraproject.org/D514

**Comment by lmacken** [comment]
This should work now with the latest python-fedora code in git
