### ISSUE TITLE
Updates in "This update has been submitted for stable by adelton" for 12 days

### ISSUE THREAD

**Issue by adelton** [fedora-infra/bodhi#1827]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-4c4c6e3d72
* This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes
13 days ago
* This update has been submitted for stable by adelton.
12 days ago

https://bodhi.fedoraproject.org/updates/FEDORA-2017-c589dd16f3
* This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes
13 days ago
* This update has been submitted for stable by adelton.
12 days ago

They are both in the "Status: testing, Request: stable" state.

**Comment by bowlofeggs** [comment]
Hello @adelton,

These are both Fedora 27 updates. Fedora 27 is currently in a beta freeze, meaning that only freeze exception updates will get pushed to stable:

https://stg.fedoraproject.org/wiki/Updates_Policy#Milestone_freezes

Your updates will get pushed to stable when the freeze ends. Hope that helps!

**Comment by adelton** [comment]
Thanks @bowlofeggs. I wonder if the bodhi UI could get updated to say that so that people do no wonder why things don't happen as they might expect. Does it make to turn this / make new request for enhancement?

**Comment by bowlofeggs** [comment]
Hello again @adelton,

There are a couple open tickets that I think express that RFE, but feel free to file a new one if you don't think they cover it:

https://github.com/fedora-infra/bodhi/issues/1563
https://github.com/fedora-infra/bodhi/issues/1038
