### ISSUE TITLE
get rid of Bodhi1/Bodhi2 detection logic?

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#183]
I don't fully understand why the `BodhiClient` is just a wrapper that returns either `Bodhi1Client` or `Bodhi2Client` based on the server version. First, it causes issues (because connecting to network during object initialization is not really common, and less than ideal, I think):
https://phab.qadevel.cloud.fedoraproject.org/D510

Second, the API changed anyway (at least `query()` changed heavily, not sure about other parts), so what's the point? The client code won't be able to work with both Bodhi1 and Bodhi2 server interchangeably anyway. You will have to choose whether to support Bodhi1 or Bodhi2 in your code. Using the wrapper only adds uncertainty and possible breakage late during execution.

Wouldn't be better to simply rename `fedora.client.bodhi.BodhiClient` be an alias for `fedora.client.bodhi.Bodhi2Client`, and let people use `fedora.client.bodhi.Bodhi1Client` explicitly if they want it? This would also solve the problem with `fedora.client.BodhiClient` which most people use I guess - it would give you `Bodhi2Client` without any detection logic involving network connections or API changing randomly based on the server you talk to.

Thoughts?

python-fedora-0.5.4-1.fc22.noarch

**Comment by lmacken** [comment]
This change allows the bodhi1 cli tool to submit updates to bodhi2 via `fedpkg update`, which was the primary concern.

**Comment by lmacken** [comment]
I'm in favor of cleaning this up after the bodhi2-client tools are released and fedpkg is updated

**Comment by ralphbean** [comment]
This was probably one of the worst aspects of the migration/cutover.  I thought it was going to be pretty clever, but it completely stopped working when we took bodhi1 down.

:+1: to getting rid of it.

**Comment by bowlofeggs** [comment]
`fedpkg` is now able to detect whether `/usr/bin/bodhi` is Bodhi 1 or Bodhi 2 and will use each of them correctly. Additionally, `bodhi-2.2.4` is now released on EPEL 7 and Fedora Rawhide.

I'm not familiar with the detection code that is discussed here, but I assume it resides in the bodhi-0.9 client (which is still the stable client on Fedora 23, 24, and 25). The code both clients use seems to be here:

https://github.com/fedora-infra/python-fedora/blob/develop/fedora/client/bodhi.py

It sounds like we can consider this issue resolved with respect to upstream Bodhi, but it won't really be fully resolved until Fedora 25 (and thus the bodhi-0.9 client) goes EOL. Once that happens, we can drop the Bodhi1 code from fedora.client.

**Comment by kparal** [comment]
Honestly I'm not sure either, it's been a long time, and it's probably not worth the time to dig into this. Just remove Bodhi1 code when nothing/nobody needs it and it's resolved :) I have no objections to closing this issue right away.

**Comment by bowlofeggs** [comment]
I have solved this bug upstream! I made one commit to bring ```fedora.client.bodhi``` into a new ```bodhi.client.bindings``` module:

https://github.com/fedora-infra/bodhi/commit/7997494b8e610108ee5131a2a2263f1a53276b65

After that commit, I added a further commit that gets rid of the weird ```Bodhi1/2Clients``` and renames the ```Bodhi2Client``` to just ```BodhiClient```:

https://github.com/fedora-infra/bodhi/commit/f22351ab5f8b10e7ffebb7fd57f2790977841eed

These changes should be part of the 2.4.0 release, whenever that happens.
