### ISSUE TITLE
don't test auth during Bodhi2Client creation?

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#184]
This returns immediately:
```
bodhi = Bodhi2Client(base_url='https://bodhi.stg.fedoraproject.org/')
```
but this doesn't:
```
bodhi = Bodhi2Client(base_url='https://bodhi.stg.fedoraproject.org/', username='aaa', password='bbb')
```
It checks credentials during object initialization and throws an error if it's invalid. That can take several seconds.

This doesn't seem to me as a good design decision. It makes life for library users harder - they have to design their APIs to use singletons for bodhi clients, instead of creating the client when needed, because it wastes a few seconds every time this happens (even when the client is not used at all in the end). It can complicate unit testing (automatic network connections). It prevents object creation at one place, and then overriding some of the attributes later at a different place.

I've read the source code and it seems that every method that needs authentication makes sure we're logged in (by calling `self.csrf()`). That's a good approach, authentication on use. What is the reason to have authentication on creation as well?

I'd like to be able to create and initialize objects first, without them doing anything unnecessary. Once everything is created and set up and I decide to *use* it (by calling some methods), then I'd like to receive an auth error if there is one. It would be nice to have some separate method for checking auth correctness (`self.check_auth()` or `self.login()`), if I decide to check auth before calling any other method. But it would be nice to have separate from object creation.

Thoughts?

python-fedora-0.5.4-1.fc22.noarch

**Comment by kparal** [comment]
Just right now it took me 2 minutes to create `Bodhi2Client` instance. Probably some network issue. But it demonstrates the problem. Some of our classes create the bodhi client instance right away (in `__init__()`), because it used to be safe, and use it much later, if ever (taskotron configuration can disable bodhi reporting, it's even the default setting, and it that case the instance is not used at all). Of course we can work around that, but I wonder whether if it's not better solved in `BodhiClient` instead.

**Comment by lmacken** [comment]
Yeah, I think this should be fixed. The main reason was for compatiblity with the Bodhi1 client behavior, and to have things kind-of-work with the bodhi1 /usr/bin/bodhi.

**Comment by lmacken** [comment]
This has been fixed.
