### ISSUE TITLE
RFE: use update alias/updateid instead of update title in methods

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#186]
If it's not too late to change the API (haha, now or never!), I suggest `Bodhi2Client` methods should identify updates based on their alias/updateid instead of update title. This has the advantage of moving to an universal update identifier to be used everywhere, and having the identifier stable (update titles change in time).

So instead of something like this:

```
bodhi.request('foo-1.0.fc22,bar-1.0.fc22', 'stable')
```

it would be this:

```
bodhi.request('FEDORA-2015-123456', 'stable')
```

This involves the following methods (I hope I found them all):

```
save(edited=)
request(update=)
comment(update=)
```

I wouldn't worry about backwards compatibility, it would affect only `Bodhi2Client`, which is quite different API-wise already, so a further change doesn't really matter.

python-fedora-0.5.4-1.fc22.noarch

**Comment by kparal** [comment]
Another way (a compromise) would be to **add** `alias=` (or `updateid=`) and keep the existing `update=` and people could choose which selector they'll use. Not the prettiest API, but more backwards compatible.

**Comment by jwakely** [comment]
Using the stable updateid as the key is definitely better than using the concatenation of an arbitrary number of strings, as I discovered recently when the URLs got too long and I could no longer edit an update.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
