### ISSUE TITLE
New comment causes bodhi to resubmit for batched after submitting for stable

### ISSUE THREAD

**Issue by robatino** [fedora-infra/bodhi#1881]
See https://bodhi.fedoraproject.org/updates/FEDORA-2017-1db64016e9 . Bodhi submitted this for batched, then for stable when the necessary time was reached. A +1 comment after that caused Bodhi to immediately submit it for batched again.

**Comment by bowlofeggs** [comment]
Thanks for the report - I've found the problem. Fix incoming.

**Comment by bowlofeggs** [comment]
This is fixed in the 2.12.2 release.
