### ISSUE TITLE
The push to batched/stable button appears on unpushed or revoked Updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1887]
The push to batched/stable button appears on unpushed or revoked Updates. Clicking it sends the update back to testing (which is the correct behavior), but there is already a "Push to testing" button as well. We should not offer these buttons since the update needs to go back to testing when it is in this state.

**Comment by keszybz** [comment]
There is no batched any more, so maybe this can be closed?

**Comment by cverna** [comment]
Let's close
