### ISSUE TITLE
/updates 504 Gateway Timeouts

### ISSUE THREAD

**Issue by smackappletwo** [fedora-infra/bodhi#1899]
Queries for Fedora 24 through Fedora 26 security/stable package updates are hitting 504 a lot.

Example:
https://bodhi.fedoraproject.org/updates/?release=F26&status=stable&type=security&rows_per_page=1000&submitted_before=2017-10-14&submitted_since=2015-01-01

The above query works just fine if you reduce the rows_per_page to 200. But that's not reasonable.
https://bodhi.fedoraproject.org/updates/?release=F26&status=stable&type=security&rows_per_page=1000&submitted_before=2017-10-14&submitted_since=2015-01-01

Shouldn't there be a response even while it's trying to assemble results? Even 350 breaks it. If there's a better way to pull all (not some) of the updates, I'd love to hear it.

**Comment by bowlofeggs** [comment]
I've been looking into Bodhi's performance issues here and there with @tyll. I've not yet proved this theory, but my current idea is that Bodhi loads and serializes every related object when querying updates. It does all the serialization before sending results (which is hy you don't get a response while it's assembling). It's API does not have a way to request it not to pull in related objects, unfortunately.

This also affects fedora-easy-karma.

Unfortunately, I don't think there's a way to fetch all the results in one call at the moment.

**Comment by ryanlerch** [comment]
Possibly related to / or a duplicate of  #271

**Comment by mattiaverga** [comment]
I believe this can be closed now. During the past years there have been several tweaks on database side and json object serialization which fixed most (if not all) bottlenecks.
As usual, feel free to reopen or open a new bug if you sport something more.
