### ISSUE TITLE
The push to batched and unpush buttons are too close to the enhancement icon on mobile

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1902]
On the mobile view of an update, the "push to batched" and "unpush" buttons are too close to the enhancement icon:

![screenshot_20171016-032826](https://user-images.githubusercontent.com/354506/31625492-47b64d4a-b274-11e7-8106-4f61c62979c2.png)

**Comment by shitalmule04** [comment]
@bowlofeggs I would like to work on this issue. I am new so can you give reference for environment set-up.

**Comment by shitalmule04** [comment]
@bowlofeggs I think it requires to add **padding-left** and **padding-up** .

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
The fix for this issue has been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/
