### ISSUE TITLE
decide what to do with bodhi-backend02

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#192]
Unless it has a specific purpose, we should just kill it.

**Comment by ralphbean** [comment]
I'm pretty sure we're going to kill it.

**Comment by lmacken** [comment]
We're now using it to run our backend consumers that listen for when new updates are created/edited and perform various Bugzilla & Wiki tasks. We'll also throw some future cron jobs/fedmsg producers on there at some point.
