### ISSUE TITLE
Rename the prefer_ssl setting

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1921]
Bodhi has a ```prefer_ssl``` setting, which doesn't do what it sounds like it does at all because it's only used when ```libravatar_dns``` is ```True```, and is only used by ```libravatar``` and not generally all of Bodhi. We should rename it to something that makes that clearer, like ```libravatar_prefer_tls```.

This is a backwards incompatible change and should be done in an X release.

**Comment by puiterwijk** [comment]
Well, you could make a new setting and make it override the `prefer_ssl` setting if that's not set?

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
