### ISSUE TITLE
There are several validators for username that are essentially copied code

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1945]
There are several validators that make sure that various kwargs reference existing username. For example, check out [```validate_username()```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/validators.py#L619-L632), [```validate_update_owner()```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/validators.py#L648-L661), and [```validate_ignore_user()```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/validators.py#L664-L677). These validators are nearly identical to the point where it'd be easy to write a common method they all use, or a validator generator function.

There may be others, so check for that too.

**Comment by Yadnyawalkya** [comment]
hey @bowlofeggs, do you like to share your thoughts on this? https://github.com/fedora-infra/bodhi/pull/1982
