### ISSUE TITLE
Build is updated but title is not changed accordingly

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#1946]
I updated builds in update https://bodhi.fedoraproject.org/updates/FEDORA-2017-9cac2b8b4a. Its title is still the old one.

**Comment by umarbrowser** [comment]
hello there can i take it

**Comment by bowlofeggs** [comment]
@umarbrowser Go for it!

**Comment by umarbrowser** [comment]
thanks

**Comment by sfshameem5** [comment]
@umarbrowser Are you still on it ?

**Comment by sfshameem5** [comment]
What is the issue here ? Can someone point it out ?

**Comment by umarbrowser** [comment]
yes i am still on it but the problem is how to do it can you guide me

**Comment by sfshameem5** [comment]
I'm too stuck at the same problem. Now knowing where to start

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
