### ISSUE TITLE
Overrides are not working if update gets unpushed

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#1947]
1. create an override O with build B
 2. create an update U with build B
 3. update is pushed to testing
 4. unpush the update U
 5. try to build a package in koji that needs B in buildroot

Expected result:
O is still active and valid, B is in buildroot.

Actual result:
nothing provides B needed by ..., B is not in the buildroot

The override O still looks active. I had to expire it and activate it again to get it working.

**Comment by tkdchen** [comment]
+1. I encountered this today as well.

**Comment by bowlofeggs** [comment]
It's not immediately clear to me why this would happen and it's late on a Saturday night, but I wonder if Koji removes the BRO tag when the build's other tags are removed? [Here's some code](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L856-L879) that is used during unpushing:

```
    def unpush(self, koji):
        """
        Move this build back to the candidate tag and remove any pending tags.
        Args:
            koji (bodhi.server.buildsys.Buildsysem or koji.ClientSession): A koji client.
        """
        log.info('Unpushing %s' % self.nvr)
        release = self.update.release
        for tag in self.get_tags(koji):
            if tag == release.pending_signing_tag:
                log.info('Removing %s tag from %s' % (tag, self.nvr))
                koji.untagBuild(tag, self.nvr)
            if tag == release.pending_testing_tag:
                log.info('Removing %s tag from %s' % (tag, self.nvr))
                koji.untagBuild(tag, self.nvr)
            if tag == release.pending_stable_tag:
                log.info('Removing %s tag from %s' % (tag, self.nvr))
                koji.untagBuild(tag, self.nvr)
            elif tag == release.testing_tag:
                log.info(
                    'Moving %s from %s to %s' % (
                        self.nvr, tag, release.candidate_tag))
                koji.moveBuild(tag, release.candidate_tag, self.nvr)
```

**Comment by mohanboddu** [comment]
It happened again: https://pagure.io/releng/issue/8813 and seems like there is an issue with the display of the time of when actually the BRO got expired as well.
