### ISSUE TITLE
Updated new build is not pusted to updates-testing repo

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#1949]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-9cac2b8b4a

This update had ``-3`` previously and was moved to obsolete state. I made new build ``fedpkg-1.30-2``, replace fedpkg-1.30-1 with this new build, and push to testing again.

Problem is new build ``fedpkg-1.30-2`` does not appear in ``updates-testing``. Instead, old build is still there.

```
docker run --rm -i -t registry.fedoraproject.org/fedora:27 /bin/bash -c "dnf install -y fedpkg
rpm -q fedpkg
dnf info fedpkg
"
...
fedpkg-1.30-1.fc27.noarch
Last metadata expiration check: 0:02:42 ago on Sat Oct 28 03:55:46 2017.
Installed Packages
Name         : fedpkg
Version      : 1.30
Release      : 1.fc27
Arch         : noarch
Size         : 91 k
Source       : fedpkg-1.30-1.fc27.src.rpm
Repo         : @System
From repo    : updates-testing
Summary      : Fedora utility for working with dist-git
URL          : https://pagure.io/fedpkg
License      : GPLv2+
Description  : Provides the fedpkg command for working with dist-git
```

**Comment by tkdchen** [comment]
``fedpkg-1.30-2`` is available in ``updates-testing`` now. Why it is delayed to push new build?

**Comment by puiterwijk** [comment]
@tkdchen That's most likely because we only push updates out once a day, and looking at the timing of your edit the edit might have missed the previous push.
Also, even after we push the update out it takes a while to arrive at the mirrors.

**Comment by bowlofeggs** [comment]
I believe @puiterwijk has explained this well. I'm going to close the issue since Bodhi is working as expected here.

**Comment by tkdchen** [comment]
Thank you all.
