### ISSUE TITLE
make it easy to go from an update to a list of updates for a given package in that update

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#197]
We used to make the package names clickable in bodhi1 where people could easily see a list of updates for a specific package.

**Comment by ralphbean** [comment]
FWIW, we also want it to be easy to go from the same list of builds to the original koji build.

How about a list like this:

- python-fedora-0.5.5-1.fc23 (icon with a link to a list of other python-fedora updates) (icon with a link to koji for this build)
- bodhi-2.0.0-58.fc23 (icon with a link to a list of other bodhi updates) (icon with a link to koji for this build)
