### ISSUE TITLE
Drop support for pkgdb

### ISSUE THREAD

**Issue by frenzymadness** [fedora-infra/bodhi#1970]
Hello.

We had a short discussion with @bowlofeggs about packagedb-cli dependency and how to deal with it during making Bodhi Python 3 compatible.

The fact is that PackageDB is read-only from August and its CLI won't be ported to Python 3. Another fact is that there are still some installations of Bodhi using it and we should release all backward-incompatible changes in one release (if possible).

I think that I can postpone removal of PackageDB-cli from Bodhi until the Python 3 compatibility will be ready for merge. In the meantime, I'll use decorators/conditions to skip related code and tests. Then we can decide whether we want to remove PackageDB-cli from Bodhi or let it there until its EOL.

**Comment by pypingou** [comment]
>  its CLI won't be ported to Python 3

iirc the CLI is already py3 compatible

**Comment by pypingou** [comment]
In addition packagedb-cli isn't part of pkgdb2's sources so it would be pretty easy to fix bugs in it.

**Comment by frenzymadness** [comment]
Interesting. I see in the porting database [0[ that packagedb-cli has some unresolved dependencies, there isn't anything related to Python 3 in specfile [1], PyPI classifiers also contains only Python 2.7 and 2.6 [2] but source code looks compatible on first look. I'll try to install it and run tests with Python 3.

[0] http://fedora.portingdb.xyz/pkg/packagedb-cli/
[1] https://src.fedoraproject.org/rpms/packagedb-cli/blob/master/f/packagedb-cli.spec
[2] https://pypi.python.org/pypi/packagedb-cli/2.14.1

**Comment by pypingou** [comment]
Spec file and setup.py have never been adjusted indeed

**Comment by frenzymadness** [comment]
I tried to use packagedb-cli in the Python 3 environment and it failed because fedora-cert (subpackage of fedora-packager) is not available in Python 3. So, it seems that if we really want to keep packagedb-cli in Bodhi, we can, but it means to go through this steps:
1. Fix one small issue in fedora_cert
2. Update fedora_packager specfile to provide python2/python3 versions of fedora_cert
3. Test packagedb-cli in Python3-only environment to be sure that it is fully compatible
4. Update packagedb-cli specfile to provide python2/python3 subpackages
5. Make a new releases/updates etc.

The question here is if it makes sense because packagedb is closer and closer to its EOL.

What do you think about it?

**Comment by frenzymadness** [comment]
I decided to rename this issue to more general name and share dependencies solving progress with you here. The question in the previous comment should still be answered to know, what to do next.

Python 3 compatibility fix for fedora_packager: https://pagure.io/fedora-packager/pull-request/153
Python 3 compatibility fix for pyramid-fas-openid: https://github.com/fedora-infra/pyramid_fas_openid/pull/6

**Comment by bowlofeggs** [comment]
For pkgdb-cli, I'd probably vote for just killing Bodhi's integration with pkgdb rather than trying to get it working with Python 3. Because it is a backwards-incompatible change it would be good to save it as one of the last things we do so we can collate other backwards incompatible changes together into one x release.

That said, if you really want to port pkgdb-cli to keep it alive until it really does go EOL, that's fine with me too.

I've got a backwards-incompatible GitHub label, so I'll put that on this ticket.

**Comment by bowlofeggs** [comment]
It might actually be nice to keep this ticket focused on just the pkgdb change, since it is backwards incompatible and other changes might not be (i.e., it'll be clearer what the label applies to).

**Comment by bowlofeggs** [comment]
Since pkgdb is no longer maintained upstream, I think we should just say that Bodhi will drop pkgdb support with the next X release.

**Comment by frenzymadness** [comment]
I completely agree. How can I help?

**Comment by bowlofeggs** [comment]
@frenzymadness I'm not yet at the point where I'm ready to make Bodhi-4.0.0, so I'd say there's nothing to be done at this point. I have the backwards-incompatible label on this ticket to remind me to look at it when it is time for Bodhi-4, so I won't forget. Thanks for the offer!

**Comment by abitrolly** [comment]
I read through the ticket, but I don't get how `pkgdb` was used, why it is deprecated, what is the replacement and why people don't want to replace it?

**Comment by frenzymadness** [comment]
pkgdb was used to store info about packages, package maintainers and their rights (commit, admin, …). It was replaced by Pagure instance running on https://src.fedoraproject.org/ . PackageDB upstream github repository is read-only.

There is a page where you can find all info about old/new use cases and what and why happened: https://fedoraproject.org/wiki/Infrastructure/WhatHappenedToPkgdb

I cannot say if it can be safely removed from Bodhi.

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
