### ISSUE TITLE
bodhi.server.models.Update.num_admin_approvals includes invalid comments

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1996]
[```bodhi.server.models.Update.num_admin_approvals```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L2530-L2542) uses ```self.comments``` when it should use [```self.comments_since_karma_reset()```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L1210-L1230) instead.

This means that admin approvals are not cleared when developers change the Builds associated with an Update.

**Comment by bowlofeggs** [comment]
There are a couple other places in the codebase that use the wrong attribute as well, so we should clean those up as well.

**Comment by ghost** [comment]
Hey I am a second year Engineering student . I want to contribute in this Organization.Any help given from mentors will be very helpful to me on how to contribute. i am a novice at this.

**Comment by bowlofeggs** [comment]
@yashraj-Dhanuka To expand on the description, ```Update.comments``` is a sqlalchemy relationship field that returns all comments that are associated with a Bodhi ```Update```. Bodhi's ```Comment```s carry karma (an up vote or down vote on a proposed update), but developers can do things that should reset the karma on an Update (such as change the builds contained in the Update).

Since developers can do these things, we need to ensure that we don't count the comments in ```self.comments``` that happened before these karma reset events. In fact, we already have a Python property called ```Update.comments_since_karma_reset()``` that does this for us!

Thus, all we need to do here is find the places that use ```Updates.comments``` to get karma and change them to use the ```comments_since_karma_reset()``` instead, then write tests to ensure it works correctly.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
