### ISSUE TITLE
The CVE model seems to be unused

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1998]
While documenting ```models.py``` today, I noticed that the [```CVE``` model](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L2704-L2714) is unused:

```
>>> m.CVE.query.count()
0L
```

**Comment by ralphbean** [comment]
Heh, this was probably a case of "CVEs are important - they should probably have a db table."

**Comment by bowlofeggs** [comment]
Haha yeah, and I found out [why the CVEs don't get created](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L2025-L2042):

```
    def update_cves(self, cves, session):
        """
        Create any new CVES, and remove any missing ones.  Destroy removed CVES
        that are no longer referenced anymore.
        """
        for cve in self.cves:
            if cve.cve_id not in cves and len(cve.updates) == 0:
                log.debug("Destroying stray CVE #%s" % cve.cve_id)
                session.delete(cve)
        for cve_id in cves:
            cve = CVE.query.filter_by(cve_id=cve_id).one()
            if cve not in self.cves:
                self.cves.append(cve)
                log.debug("Creating new CVE: %s" % cve_id)
                cve = CVE(cve_id=cve_id)
                session.save(cve)
                self.cves.append(cve)
        session.flush()
```

It will never get to the line that tries to create the CVEs :)

**Comment by bowlofeggs** [comment]
The CVE model is removed in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
