### ISSUE TITLE
empty comment when accidentally hit "add comment & feedback" button

### ISSUE THREAD

**Issue by alick** [fedora-infra/bodhi#2009]
Hi,

The other day, I accidentally hit the "add comment & feedback" button, and it resulted in an empty comment with all karma 0s: https://bodhi.fedoraproject.org/updates/wget-1.19.2-1.fc25#comment-692806

I believe this should be disallowed since it just adds noise. Maybe check if the comments are empty and all karma are 0s, and show a popup dialog to notify when submitting?

**Comment by mrjilc** [comment]
I would like to work on this issue , any help given will be much appreciated

**Comment by bowlofeggs** [comment]
@mrjilc The comment handling code is [here](https://github.com/fedora-infra/bodhi/blob/3.2.0/bodhi/server/models.py#L2644-L2756).

**Comment by mattiaverga** [comment]
I think that requiring a comment to be set is not the best thing. A user should be able to post only karma with an empty comment, or a comment with empty karma.

In my opinion a better way to proceed would be to check if both the comment field AND karma are void then warn the user and do nothing.

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release

**Comment by bowlofeggs** [comment]
This fix is now deployed to Fedora's production instance.
