### ISSUE TITLE
Search is very confusing, not on header

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#201]
With 2.0 we seem to have lost the ability to search on every page.  I really miss that.

Also, when I type in a package name I get the confusing response:

Users
unable to find any users that match that query

leading me to wonder what is broken.  If I leave it long enough I get a list of matching packages.

**Comment by ralphbean** [comment]
Ack.  This is valid.  We should add a spinner at least!

**Comment by ralphbean** [comment]
I think this is in part a duplicate of #231.

**Comment by ralphbean** [comment]
As mentioned in #229, we could add ``spinner.gif`` in the results pane so people know to wait for results:  ![](https://bodhi.fedoraproject.org/static/img/spinner.gif)

**Comment by ralphbean** [comment]
OK, I'm going to close this as a duplicate of #229 so we only have one ticket open for search enhancement.  Thanks for reporting @opoplawski!
