### ISSUE TITLE
Add support for containers to the masher

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2028]
We need the masher to be able to promote containers into testing and stable. We will probably use skopeo for this.

Depends on #2027.

**Comment by TomasTomecek** [comment]
@runcom told me that @mtrmac is working on the support for manifest lists in skopeo (CC @owtaylor) #you-are-now-connected

**Comment by bowlofeggs** [comment]
On 01/29/2018 04:21 PM, Tomas Tomecek wrote:
> @runcom <https://github.com/runcom> told me that @mtrmac
> <https://github.com/mtrmac> is working on the support for manifest lists
> in skopeo (CC @owtaylor <https://github.com/owtaylor>)
> #you-are-now-connected

#so-connected

**Comment by mtrmac** [comment]
@nalind is actually working on that in containers/image (the library backing `skopeo`), in https://github.com/containers/image/pull/400 .
