### ISSUE TITLE
Please improve " Feedback received on updates " page

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#203]
This URL https://bodhi.fedoraproject.org/comments/?update_owner=pnemade looks confusing to me it should show also submitted update packages. By just looking at it, i can't conclude for which update the message "This update has been pushed to testing" is ?

**Comment by cicku** [comment]
+1 Confusing as well

**Comment by relrod** [comment]
(For whoever works on this issue), it also says "1 months ago" for comments that are one month old, which is grammatically incorrect.

**Comment by ralphbean** [comment]
I think this is identical to #215.

**Comment by pnemade** [comment]
I confirm reported problem is fixed now.
Thanks for quick fix. :smile:
