### ISSUE TITLE
multi branch update stay on same page

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#2034]
Previously, after a successful multi-branch update creation, after the "update split" message, we were redirected to the update list

Now, stay on the submit page (of course the submit button, if used, raise a message "an update already exists")

P.S. reproduced twice this morning for php-pecl-memcached and  php-zendframework-zend-serializer

**Comment by bowlofeggs** [comment]
Hi Remi!

I'm not sure I understand the issue. Was there a duplicate existing update that caused the multi-update form to fail? Or is multi-update creation always failing to show you the list of updates?

**Comment by remicollet** [comment]
Not, first time I use the button, there is no existing update, and creation is properly done, only without redirect.

If I use the button a second time, of course, it fails.

**Comment by remicollet** [comment]
Seems to work as expected again.
Perhaps some infra issue...
