### ISSUE TITLE
search box doesn't sanitize trailing spaces

### ISSUE THREAD

**Issue by sumantro93** [fedora-infra/bodhi#2046]
when one searches for a package and mistakenly hits an extra space after the package name, the search box doesn't sanitize. On the other hand, the URL if is passed with search=foo<some space> gets sanitized automatically.

**Comment by ghost** [comment]
I would like to work on this issue , any help given will be much appreciated

**Comment by bowlofeggs** [comment]
Hello @yashraj-Dhanuka,

The search box makes a few simultaneous API calls to search different objects (packages, users, buildroot overrides, and updates). The code that handles the update search is here, for example:

https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/services/updates.py#L263-L266

Notice that there are validators (search that code for "validators") that run before that handler gets called. The fix would be to validate the search parameter there and trim its whitespace. It should be possible to write one validator that is used for all the APIs that the search box uses.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
