### ISSUE TITLE
"Submitted for batched" notifications can now be triggered and recorded multiple times

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/bodhi#2048]
This is likely related somehow to #717 and #1403, as it involves both of these issues, but there is an additional problem. I tried to add karma to [https://bodhi.fedoraproject.org/updates/FEDORA-2017-92a0ae09aa](https://bodhi.fedoraproject.org/updates/FEDORA-2017-92a0ae09aa), and the first two tries seemed to fail entirely (#717 again). This was shortly before it was pushed to testing. Then after it made it to testing, I retried, and again the first try seemed to fail, so I submitted again perhaps a minute later. Ultimately, there were four "submitted for batched" emails sent (#1403 again, but doubled). The distinction in this new Bodhi release is that now the actual web content has recorded two "submitted for batched" entries as well, so something's off in that it lets the same status be reflected twice. (I'm not sure if this warrants its own bug, but it is new, and perhaps has different dependencies, so I'm reporting it as such.)

**Comment by bowlofeggs** [comment]
We are dropping the batching feature in #2977 so I will close this issue. Thanks for the report!
