### ISSUE TITLE
Taskotron output takes 2 lines

### ISSUE THREAD

**Issue by cicku** [fedora-infra/bodhi#205]
Hi,

Current result from taskotron is:

```
Taskotron: depcheck test PASSED on i386. Result log: https://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/116437/steps/runtask/logs/stdio (results are 
informative only)
```

I'm not sure the reason of using newline for `informative only`, is it a bug of `taskotron_results`?

Thanks.

> Resolution 1280*800(16*10), Chrome 44,  14.1" LCD

**Comment by ralphbean** [comment]
So, I think you're talking about the comments that taskotron leaves on updates, correct?

Is this just a CSS issue?  I noticed that sometimes on the user profile page that comments will stray off and flow outside of their box (which should be pretty easy to fix).

**Comment by cicku** [comment]
Yes, that comment left on updates.

It should be a CSS issue, because result comment shouldn't be in 2-line syntax.

**Comment by kparal** [comment]
Please include a link. It seems to be fine here:
https://bodhi.fedoraproject.org/updates/tint2-0.12.2-1.fc22

It's possible that it's a conversion problem. Taskotron hasn't posted any comments to Bodhi2 yet, so maybe the old comments when pulled in from Bodhi1 got reformatted improperly sometimes.

**Comment by cicku** [comment]
@kparal are you using console browser? :laughing:

It seems not fine here, it's still in 2 lines. I can confirm it's a bootstrap css issue, I'm inspecting the elements now.

Bootstrap CSS showed:

  .col-md-9 {
    width: 75;
  }

75% is too small, should be enlarged.

**Comment by kparal** [comment]
Firefox. I see it wrapped, but just because the link is too long. Notice that each of those two taskotron comments is wrapped differently:
![bodhi](https://cloud.githubusercontent.com/assets/755451/9405986/db56d22a-47fc-11e5-81ba-818f2027b1d8.png)
There's definitely not a forced newline before `informative only`.

**Comment by ralphbean** [comment]
Agreed with @kparal.  This is not a bug.
