### ISSUE TITLE
Mention submission to batched in Bugzilla

### ISSUE THREAD

**Issue by tyll** [fedora-infra/bodhi#2051]
I submitted https://bodhi.fedoraproject.org/updates/FEDORA-2017-7527834878 to batched 5 days ago but Bodhi did not mention this in the bug report https://bugzilla.redhat.com/show_bug.cgi?id=1508177 - therefore the reporter. Since submitting to batched means an extra delay, please consider adding a notification to Bugzilla ideally with the estimated date of the next batch push.

**Comment by bowlofeggs** [comment]
We are dropping the batching feature in https://github.com/fedora-infra/bodhi/issues/2977 so I will close this issue. Thanks for the suggestion!
