### ISSUE TITLE
Python 3 compatibility - final phase

### ISSUE THREAD

**Issue by frenzymadness** [fedora-infra/bodhi#2059]
Hello.

This issue is here for tracking work on the final phase of making Bodhi Python 3 compatible.

Currently, Bodhi is somehow Python 3 compatible (PR #2006) but we cannot be sure everything is okay and we don't break Python 3 compatibility in the future until we enable tests with Python 3.

Known stuff currently keeping us from enabling tests with Python 3:
* pyramid-fas-openid - https://github.com/fedora-infra/pyramid_fas_openid/pull/7 - We need to merge existing PR, prepare a new specfile with Python 3 subpackage and ship it to Fedoras. Then we can install both versions to VM and start testing with Python 3.
* packagedb-cli - https://github.com/fedora-infra/bodhi/issues/1970 - Backward incompatible change where we have to use some `if six.PY3` conditions to disable this backend and all related tests.

The last big task will be to solve all issues which will appear in tests with Python 3 and then include Python 3 tests to CI.

If I'll have enough time, I'll try to prepare PR with enabled Python 3 tests and all tests depending on blocking stuff mentioned above skipped until they will be fixed.

**Comment by frenzymadness** [comment]
There are last 20 tests skipped in Python 3 which need to be fixed.

**Comment by bowlofeggs** [comment]
bodhi-3.11.0b5 has been deployed to Bodhi's staging environment and uses Python 3 only:

https://bodhi.stg.fedoraproject.org

Please test and let us know if you find issues!

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
