### ISSUE TITLE
remove upgradepath from mandatory checks

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#2077]
Currently, `dist.upgradepath` is listed in `site_requirements` in Bodhi. FESCo asked us to drop upgradepath check, because it's no longer important, see https://pagure.io/taskotron/issue/244. Due to that, we stopped executing it. Please remove it from the list of mandatory/important checks, thanks.

Grepping the source code, I see it mentioned in `production.ini` and `bodhi/client/bindings.py`.

**Comment by sebwoj** [comment]
Actually `site_requirements` is unused config setting and should be removed in the next big release(5.0)
