### ISSUE TITLE
Buildroot override search/list

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#208]
In bodhi1, there was no way to search a package that is already added as buildroot override but I can browse through the list to check it.

Is there any plans for this in bodhi2? At least a way to find if someone has already added any version of a package in buildroot override?

**Comment by lmacken** [comment]
I think it'll be pretty easy to have the primary search box return overrides as well.

**Comment by opoplawski** [comment]
+1 for searching
