### ISSUE TITLE
bodhi-check-policies only operates on unpushed updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2085]
I noticed today when working on #1514 that the update query that ```bodhi-check-policies``` performs only selects [unpushed updates](https://github.com/fedora-infra/bodhi/blob/3.1.0/bodhi/server/scripts/check_policies.py#L40-L42):

```
updates = models.Update.query.filter(models.Update.pushed == false())\
        .filter(models.Update.status.in_(
                [models.UpdateStatus.pending, models.UpdateStatus.testing]))
```

I think this is probably not what we want, as [testing updates are marked pushed](https://github.com/fedora-infra/bodhi/blob/3b655f2/bodhi/server/consumers/masher.py#L845-L857). This means we will only consult Greenwave about pending updates.

**Comment by ralphbean** [comment]
Interesting!  Good catch.
