### ISSUE TITLE
Metrics enhancement to show also count/percentage

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#209]
On page https://bodhi.fedoraproject.org/metrics , is it possible to show total exact count/percentage for various colors by just taking mouse pointer on top of that colored section in the given graph?

thanks.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
