### ISSUE TITLE
The "Latest Critical Path Updates in Need of Testing" link isn't for critpath updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2094]
The home page has a link "Latest Critical Path Updates in Need of Testing", but if you click it it just takes you to all testing updates, not critical path updates.

This was reported by @AdamWill (thanks!)

**Comment by 0xsomesh** [comment]
UpdateType class in `server/models.py` has only four types mentioned i.e bugfix, security, newpackage and enhancement. There is no mention of 'critical path' updates. I think changing in the url in template won't work. Can you guide how to go about it?

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
