### ISSUE TITLE
Unable to determine release of build in trashcan

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#2103]
Somehow I managed to forget to make some updates for a couple builds, and just got an email about them being marked for deletion. So I re-tagged [`python-pep8-naming-0.4.1-4.fc26`](https://koji.fedoraproject.org/koji/buildinfo?buildID=991556) and [`python-pep8-naming-0.4.1-4.fc27`](https://koji.fedoraproject.org/koji/buildinfo?buildID=991557) into `f26-updates-candidate` and `f27-updates-candidate` respectively.

However, when I try to make an update out of either of these, I get `Unable to determine release from build: python-pep8-naming-0.4.1-4.fc27`. It does not matter if I use `fedpkg update` or the website.

**Comment by QuLogic** [comment]
Now that garbage collection has noticed they're tagged again, the packages are out of the trashcan and I can make an update out of them.

**Comment by ryanlerch** [comment]
this seems resolved. closing as not an issue.

feel free to reopen if needed
