### ISSUE TITLE
Bodhi is pushing EOLed Fedora updates to batched

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#2104]
I've just received an e-mail with: *This update has been submitted for batched by bodhi.* It's a Fedora 25 update and I don't think this should happen after EOL.

See https://bodhi.fedoraproject.org/updates/python3-3.5.4-3.fc25#comment-714357

Originally reported at infra: https://pagure.io/fedora-infrastructure/issue/6599 - was redirected to upstream.

**Comment by bowlofeggs** [comment]
I believe the proposed fix I wrote in https://github.com/fedora-infra/bodhi/issues/2104 will fix this too.

**Comment by keszybz** [comment]
There is no batched any more, so maybe this can be closed?

**Comment by cverna** [comment]
Let's close
