### ISSUE TITLE
The web UI does not display Update severity

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2108]
It would be nice if the web UI displayed the severity of each update.

**Comment by kurianbenoy** [comment]
Hi I was intrested in this issue. Can You shed some more on what I should do specifically

**Comment by bowlofeggs** [comment]
Hello @kurianbenoy,

Have a look at https://bodhi.fedoraproject.org/docs/developer/index.html to get started with Bodhi development. The UI template code in question lives here: https://github.com/fedora-infra/bodhi/blob/3.2.0/bodhi/server/templates/update.html#L753

Tests for that code are here: https://github.com/fedora-infra/bodhi/blob/3.2.0/bodhi/tests/server/services/test_updates.py

**Comment by bowlofeggs** [comment]
This feature is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
