### ISSUE TITLE
Disable the ability to give karma to your own updates?

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#211]
we did this in bodhi1

**Comment by nirik** [comment]
Yes, we should do the same in bodhi2. It's part of the updates policy.

**Comment by leigh123linux** [comment]
If you disable this how would you be able to push something after the seven day limit as there appears to be no push to stable button.

I had to leave positive karma to push to stable.
 
https://bodhi.fedoraproject.org/updates/tint2-0.12.2-1.fc21

**Comment by ralphbean** [comment]
Fixed by #247.
