### ISSUE TITLE
Invalid URL on Github Readme

### ISSUE THREAD

**Issue by palnabarun** [fedora-infra/bodhi#2116]
When I click on the `Developer Documentation` link shown [here](https://github.com/fedora-infra/bodhi), a 404 props up.

![image](https://user-images.githubusercontent.com/10010419/35046734-dcea9eec-fbbd-11e7-9c22-2428f3bb68f3.png)

This link should target [here](https://bodhi.fedoraproject.org/docs/developer_docs.html) I guess.

I would like to patch this up.

**Comment by puiterwijk** [comment]
This path has been changed in the new 3.2.0 version, which is planned for deployment into production soon.
That should make the url valid again.

**Comment by palnabarun** [comment]
Oh. Okay.

Where is the new 3.2.0 version located?
Are the bugs in Github Issues with respect to the new 3.2.0 version?

**Comment by bowlofeggs** [comment]
3.2.0 is currently deployed to Fedora's staging instance:

https://bodhi.stg.fedoraproject.org

You can access the 3.2.0 developer docs here:

https://bodhi.stg.fedoraproject.org/docs/developer/index.html

The open bugs in GitHub are mostly all still real issues, with some possibility of older ones being stale.
