### ISSUE TITLE
F21 metrics are wrong.

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#213]
There are 9560 total F21 updates, but the graph doesn't show that. https://bodhi.fedoraproject.org/metrics

**Comment by ryanlerch** [comment]
Just verified that the graph now seems to be working as expected.

The values shown in this graph seem to be the just updates in Stable, and the values seem accurate across all releases shown in Bodhi now.

**Comment by bowlofeggs** [comment]
Thanks @ryanlerch!
