### ISSUE TITLE
Bodhi has stopped registering feedback that references bug IDs the submitter has associated

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/bodhi#2130]
Until some time a couple of days ago, when I included feedback on a specific bug ID the submitter associated with a Bodhi update, it would register visibly in the content posted. Now it seems to have stopped doing this.

For example, I ticked off a bug in this submission a few days ago, and it's registered and visible as one would expect: [https://bodhi.fedoraproject.org/updates/FEDORA-2018-462f982e20](https://bodhi.fedoraproject.org/updates/FEDORA-2018-462f982e20)

However, I just did the same for another submission, and it didn't register. It doesn't show up in the content posted. Selecting the same bug in a second feedback submission just ends up with entirely empty content. (The same is true for the email generated.) This example is: [https://bodhi.fedoraproject.org/updates/FEDORA-2018-6f90feaeee](https://bodhi.fedoraproject.org/updates/FEDORA-2018-6f90feaeee)

**Comment by cverna** [comment]
Solved by #2461

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
