### ISSUE TITLE
Duplicate update notifications by bodhi on associated bugzilla

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#214]
e.g. check this bug comments https://bugzilla.redhat.com/show_bug.cgi?id=1252564#c11 and https://bugzilla.redhat.com/show_bug.cgi?id=1252564#c12

They are same and duplicate. Can this duplication be fixed in bodhi?

**Comment by ppisar** [comment]
The same with https://bugzilla.redhat.com/show_bug.cgi?id=1302288#c3 and following comments. They are quadruplicated there.

**Comment by bowlofeggs** [comment]
I haven't seen this happen before. Does it still happen? If not, can we close this bug?

**Comment by ppisar** [comment]
I also think it does not occur anymore.

**Comment by bowlofeggs** [comment]
Thanks @ppisar! I'll close for now, but please let me know if you see this again.
