### ISSUE TITLE
Link to new packages app instead of pkgdb

### ISSUE THREAD

**Issue by mjg** [fedora-infra/bodhi#2142]
The fedmenu which the bodhi site used still links to the old pkgdb.
Please adjust to the new hotness, since pkgdb is defunct since August 2017.

**Comment by bowlofeggs** [comment]
Hello @mjg!

I'm actually not very familiar with the fedmenu code, but it looks to me like it's just JavaScript that Bodhi loads from https://apps.fedoraproject.org/fedmenu/js/fedmenu.js. I think that means we need to fix it here:

https://github.com/fedora-infra/fedmenu/

I've filed https://github.com/fedora-infra/fedmenu/issues/22 for you. Thanks for the report!
