### ISSUE TITLE
Mention the package along with the 'comment'/'feedback'

### ISSUE THREAD

**Issue by tomspur** [fedora-infra/bodhi#215]
The list of feedback does not contain the information on which package the feedback was given to, see this picture:
![screenshot from 2015-08-20 08-57-23](https://cloud.githubusercontent.com/assets/303559/9377459/8720e6a2-4719-11e5-84e6-22f034cd7f35.png)

Instead this information is hidden in the link "23 days ago [...]".
Would it be possible to e.g. write the package name below the "23 days ago [...]"?

This would help a lot and one does not hove with the mouse to the link to see which package the feedback was given too.

**Comment by ralphbean** [comment]
Agreed!

**Comment by tomspur** [comment]
Thanks :+1:
