### ISSUE TITLE
What is "pending" status?

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/bodhi#2150]
Can Bodhi interface explain what is pending? What can I do with package in pending state? What states are available to find the state I need? Why the current state like this and what is it waiting?

![image](https://user-images.githubusercontent.com/8781107/36199620-1fdfbb96-118b-11e8-8dc9-e5c0e3c48b2e.png)

In particular, I am trying to know when I can test https://bodhi.fedoraproject.org/updates/FEDORA-2018-54c7a5b01b from `updates-testing` repository.

**Comment by bowlofeggs** [comment]
@abitrolly There is documentation on Bodhi's states that will be distributed with the upcoming 3.3.0 release. A beta for that version is deployed to staging, so you can see those docs there:

https://bodhi.stg.fedoraproject.org/docs/user/update_states.html

Updates are available in the ```updates-testing``` repository once they reach the ```testing``` state (not the ```testing``` request. It is possible to download the RPMs from Koji if you want to get them sooner. You can see links to the Koji builds on the builds tab in Bodhi.

All that said, perhaps we could add mouseovers to the status to make its meaning more discoverable.

**Comment by abitrolly** [comment]
Mouseovers would be great as well as more detailed Pending status. https://bodhi.stg.fedoraproject.org/docs/user/update_states.html#pending lists additional checks to be performed, and it would be nice to get them visualized or highlighted in description.

**Comment by gsauthof** [comment]
As a new bodhi user, I'm also wondering how long a new package update is supposed to stay in status 'pending' - the UI doesn't really make it obvious if some pending sub-task still needs to finish or if the process just hangs. For example, the update I'm looking at still is in status pending after 17 hours.

**Comment by abitrolly** [comment]
Ideally it should show positions in the pipeline and link to the queue.

                  (you are here)
    [pending](3) --> [testing] -->  [stable]

`(3)` is the queue size.

**Comment by bowlofeggs** [comment]
The difficulty is that there isn't any running task when an update is pending. The update will remain in pending until a human release engineer runs an update push. We cannot know when this will happen so cannot give useful estimations in the UI.

For Fedora, release engineers usually run one push a day, but not necessarily at a consistent time of day.
