### ISSUE TITLE
Rename "masher" to "composer"

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2151]
With the next major version of Bodhi, we should rename the "masher" to "composer" since mash is no longer used.

**Comment by sebwoj** [comment]
@bowlofeggs Since github has an issue closing "Bodhi issues", we should do it manualy ;/

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
