### ISSUE TITLE
Unable to open update alias URL

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#216]
I gave karma to update for liberation-fonts-1.07.4-6.fc23 package. That mean I got cc'ed to all further notification for that update. Now, after we moved to bodhi2, the next message I got on that update is showing "The following comment has been added to the liberation-fonts-1.07.4-6.fc23 update:" along with https://bodhi.fedoraproject.org/F23/FEDORA-2015-13268 URL.

This https://bodhi.fedoraproject.org/F23/FEDORA-2015-13268 is giving "404 Not Found"

**Comment by ralphbean** [comment]
* It should be https://bodhi.fedoraproject.org/updates/FEDORA-2015-13268
* I noticed that the bodhi client **also** prints out the incorrect URL after submitting a new update.
* Agreed -- this email-sending code should be changed.

**Comment by ralphbean** [comment]
I'm 90% sure this was fixed in 41336445938f91573271f1c44d95fcb1f40c1bb4 by removing the line:

```python
path.append(self.release.name)
```
