### ISSUE TITLE
Bodhi does not recognize/process karma on kernel regression test

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/bodhi#2189]
Leaving karma on kernel regression test cases is not shown on the corresponding site (example: https://bodhi.fedoraproject.org/updates/FEDORA-2018-817647a89b)

**Comment by dhgutteridge** [comment]
Presumably this is related to the regression I reported in #2130.

**Comment by bowlofeggs** [comment]
Might also be related to #2456.

**Comment by cverna** [comment]
Solved by #2461

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
