### ISSUE TITLE
Can't submit update to multiple distros at once

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#219]
I often build a new NEVR for multiple distros and then submit updates for all of them together. The old web interface happily accepted this: I could submit, say, 'fedfind-1.3-1.fc23' and 'fedfind-1.3-1.fc22' together and it'd create two updates, one for F22, one for F23. This saved me a lot of busywork.

The new web UI doesn't seem to allow this; it pops up a message for a few seconds saying 'multiple fedfind builds' or something like that. The failure cases in the new UI could stand to be more obvious.

**Comment by NiceandGently** [comment]
Happened to me with 2 packages.

**Comment by lmacken** [comment]
This is currently a known limitation of Bodhi2, and a high priority feature.

**Comment by kkofler** [comment]
IMHO, ideally, they should be treated as ONE update group and in particularly share the karma value (so that one needs only +1 or +2 for the identical update on all releases together rather than for every single release).

**Comment by AdamWill** [comment]
That's a significant policy change, not an engineering issue.

**Comment by ralphbean** [comment]
I never knew Bodhi1 could do this.  Sounds super useful.

**Comment by AdamWill** [comment]
:+1: @ralphbean is the best.
