### ISSUE TITLE
URLs should use update ID not title

### ISSUE THREAD

**Issue by jwakely** [fedora-infra/bodhi#221]
Related to #186, the URLs in the bodhi web UI should use the update ID not the title formed by joining all the builds.  Not only is the ID stable, but it doesn't get too long for the web server (or some part of the bodhi scripts running on the server) to handle, giving 404 errors when trying to edit a large update with very many builds.

i.e. instead of 

https://bodhi.fedoraproject.org/updates/curlpp-0.7.3-24.fc23%2Ccvc4-1.4-7.fc23%2Ccyphesis-0.6.2-8.fc23%2Cdans-gdal-scripts-0.23-10.fc23%2Cdavix-0.4.1-6.fc23%2Cdevice-mapper-persistent-data-0.5.3-3.fc23%2Cdiet-2.9-4.fc23%2Cdmlite-plugins-s3-0.5.1-9.fc23%2Cdolphin-connector-1.2-15.fc23%2Cdyninst-8.2.1-8.fc23%2Ceasystroke-0.6.0-12.fc23%2Cedb-0.9.18-16.fc23%2Cekiga-4.0.1-23.fc23%2Celektra-0.8.12-2.fc23%2Cember-0.7.2-10.fc23%2Cenblend-4.1.3-7.fc23%2Cexempi-2.2.1-12.fc23%2Cfawkes-0.5.0-25.fc23%2Cfgrun-3.4.0-5.fc23%2Cfife-0.3.3r3-16.fc23%2Cfityk-1.3.0-5.fc23.1%2Cflamerobin-0.9.3-12.20130401snap.fc23%2Cflowcanvas-0.7.1-21.fc23%2Cfreecad-0.15-8.fc23%2Cfritzing-0.9.0b-6.fc23%2Cfts-3.2.32-5.fc23%2Cfts-mysql-3.2.32-4.fc23%2Cfunguloids-1.06-15.fc23%2Cfuse-encfs-1.7.4-21.fc23%2Cgalera-25.3.10-4.fc23%2Cgappa-1.2.0-4.fc23%2Cgazebo-5.1.0-5.fc23%2Cgdal-2.0.0-2.fc23%2Cgearmand-1.1.12-14.fc23%2Cgecode-4.4.0-4.fc23%2Cgfal2-plugin-xrootd-0.4.0-4.fc23%2Cgfal2-python-1.8.3-3.fc23%2Cglob2-0.9.4.4-30.fc23%2Cglogg-1.0.2-7.fc23%2Cglom-1.28.4-5.fc23%2Cgnash-0.8.10-19.fc23%2Cgnote-3.17.0-3.fc23%2Cgnuradio-3.7.8-0.2.rc1.fc23%2Cgource-0.43-4.fc23%2Cgpick-0.2.5-12.fc23%2Cgpsdrive-2.11-31.fc23%2Cgqrx-2.3.2-11.fc23%2Cgr-air-modes-0-0.37.20140312gitcc0fa180.fc23%2Cgr-fcdproplus-0-0.14.20140920git1edbe523.fc23%2Cgrfcodec-6.0.5-4.fc23%2Cgr-iqbal-0.37.2-11.fc23%2Cgr-osmosdr-0.1.3-10.20141023git42c66fdd.fc23/edit

it should be

https://bodhi.fedoraproject.org/updates/FEDORA-2015-13449/edit

**Comment by ralphbean** [comment]
OK.  You can use either (as you know), this is just a question of tracking down all the instances of those title-based URLs.

**Comment by jwakely** [comment]
nice - thanks
