### ISSUE TITLE
Feedback form slightly confusing

### ISSUE THREAD

**Issue by jwakely** [fedora-infra/bodhi#222]
Using ticks and crosses in the Feedback section is a bit confusing when the questions are of the form "Does this update break the basic functioning of your system?" because a tick usually means "yes" but I don't want to say "yes, it breaks the basic functioning"

I realise the columns are labelled "FAIL" and "PASS" but that's only in popup text that isn't immediately visible.

How about:

"Is the basic functioning of the system still OK after this update?" so that you can give a positive answer

**Comment by ralphbean** [comment]
:+1: to the string change.
