### ISSUE TITLE
Update page should sort buglist by RHBZ# (on both Details and Bugs tab)

### ISSUE THREAD

**Issue by ferdnyc** [fedora-infra/bodhi#2222]
I saw some other sorting issues (fixed) here, but a couple of searches didn't turn up anything for this.

When an update has a _large_ number of associated bugs (esp. common with `selinux-policy` updates, like [this one](https://bodhi.fedoraproject.org/updates/FEDORA-2018-32ebae3424)), it can be almost impossible to find "your" bug in either the feedback form or on the Bugs tab, to submit/check its specific karma.

Sorting would help a lot. Bug# seems the only likely candidate for sort key, since (in these policy updates especially) the bug report titles are often so similar in both formatting and content.

**Comment by bowlofeggs** [comment]
This feature is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
