### ISSUE TITLE
notifications from all people are displayed

### ISSUE THREAD

**Issue by NiceandGently** [fedora-infra/bodhi#223]
When i'm logged in bodhi, i see  notifications from all other people when they do actions.

**Comment by ralphbean** [comment]
You even see it if you're logged out on bodhi.  This is the intended behavior.

**Comment by ralphbean** [comment]
(sorry if that was a short response.. I'm trying to triage all these tickets filed in the last few days.  Thanks for filing the report!!)

**Comment by leigh123linux** [comment]
@ralphbean 

Can you add an option to disable it please as I find it really annoying and a distraction.

**Comment by NiceandGently** [comment]
@ralphbean 
Hmm,
but for what reason should i see the activity of other people on other packages?
For me this is too much information on my screen
