### ISSUE TITLE
Bodhi 'forgets' previously added karma in EPEL matter

### ISSUE THREAD

**Issue by herrold** [fedora-infra/bodhi#2255]
see the archived email link at the bottom --- despite adding karma, the mailer thinks that none has been added

Date: Sat, 31 Mar 2018 20:00:27
From: updates@fedoraproject.org
To: herrold@owlriver.com
Subject: [Fedora Update] [comment] perl-Data-HexDump-0.02-28.el6

The following comment has been added to the perl-Data-HexDump-0.02-28.el6
update:

bodhi - 2018-04-01 00:00:26.759518 (karma: 0)
This update has reached 14 days in testing and can be pushed to stable now if
the maintainer wishes

To reply to this comment, please visit the URL at the bottom of this mail

=============================================================================
===
     perl-Data-HexDump-0.02-28.el6
=============================================================================
===
  Update ID: FEDORA-EPEL-2018-2f181ab039
    Release: Fedora EPEL 6
     Status: testing
       Type: newpackage
   Severity: low
      Karma: 1
       Bugs: 1557560 - Please add: perl-Data-HexDump to EPEL 6
      Notes: This is the first EPEL-6 build of perl-Data-HexDump.
  Submitter: pghmcfc
  Submitted: 2018-03-17 17:13:31.717690
   Comments: bodhi - 2018-03-17 17:13:31.731439 (karma 0)
             This update has been submitted for testing by pghmcfc.
             bodhi - 2018-03-17 17:13:53.818690 (karma 0)
             pghmcfc edited this update.
             bodhi - 2018-03-17 21:11:28.632420 (karma 0)
             This update has been pushed to testing.
             herrold - 2018-03-19 17:06:51.568413 (karma 1)
             uncontroversial -- +1
             bodhi - 2018-04-01 00:00:26.759518 (karma 0)

  https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-2f181ab039

**Comment by herrold** [comment]
it _may_ be that karma needs to be repeatedly re-awarded -- if this is so, it feels like it is a bug to require such

**Comment by puiterwijk** [comment]
The `karma` part in those lines is an indicator whether that particular comment gave karma:

````
herrold - 2018-03-19 17:06:51.568413 (karma 1)
uncontroversial -- +1
````

So this is as intended.

**Comment by puiterwijk** [comment]
Also note that in the summary part of the same email, it indicates that the karma point is still valid:

````
Update ID: FEDORA-EPEL-2018-2f181ab039
Release: Fedora EPEL 6
Status: testing
Type: newpackage
Severity: low
Karma: 1
Bugs: 1557560 - Please add: perl-Data-HexDump to EPEL 6
````
