### ISSUE TITLE
libravatar is shutting down

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2256]
Libravatar has [announced that they are shutting down](https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/). Bodhi uses this to give its users avatars. We should switch to something else, and should coordinate with the other Fedora apps.

**Comment by ryanlerch** [comment]
Libravatar was saved!

https://blog.libravatar.org/posts/Libravatar.org_is_not_going_away/
