### ISSUE TITLE
Insert Bodhi URL instead of BZ URL into BZ ticket.

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#226]
This is the [1] comment to my update submitted by Bodhi. It contains the link to the ticket itself. Previously, Bodhi used to submit Bodhi URL [2], which makes more sense

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1208316#c105
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1240983#c5

**Comment by ralphbean** [comment]
Ha!  I took me a long minute to stare at the two pages to figure out what the difference was.

Yes!  This should be fixed.  Thanks for the report!
