### ISSUE TITLE
Bodhi should display if an update has been wavied

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2266]
We should make the update page display a note if an update has been waived. It should display the user who added the waiver and their wavier message.

**Comment by sebwoj** [comment]
I found update with waived information("Automated test" tab):
https://bodhi.fedoraproject.org/updates/FEDORA-2018-03747e0c21

I assume that waived information should be visible on te first tab?

**Comment by bowlofeggs** [comment]
I am currently considering some alternative architectures for test gating and waiver registrations, so I recommend holding off on implementing this ticket or other tickets related to waiverdb or greenwave.

**Comment by AdamWill** [comment]
These days, the general information that some test results were waived is shown in the right-hand sidebar, and the Automated Tests tab shows a thumbs-up next to tests that were waived, which shows the person who waived it and the waiver messaged on hover.

I think that's sufficient to close this ticket?
