### ISSUE TITLE
Error running tests in Vagrant

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2268]
Launching 'btest' in Bodhi Vagrant test environment outputs: "-bash: flake8: command not found"

**Comment by bowlofeggs** [comment]
Yeah, unfortunately the ```flake8``` package is not done correctly in Fedora:

https://bugzilla.redhat.com/show_bug.cgi?id=1545382

It does look like there is a ```flake8-2```, which I suppose we could switch to.
