### ISSUE TITLE
No feedback when issues with update

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#227]
When creating an update that might be missing information or have some other problem there's a temporary "Unable to create update" error that isn't prominent or sticky. If someone looks away for a moment it's gone.

It would be useful if the error was more details, persistent on the page and possibly even highlighting the fields with issues some how to provide a visual clue as to where the update problem lies. 

Screen shot as an example

![bodhi-update](https://cloud.githubusercontent.com/assets/1917405/9381503/d552d14e-472f-11e5-874c-0e9f17acb806.png)

**Comment by ralphbean** [comment]
A number of different patches over the past few days have improved the feedback here!

(That "unable to create update" is returned for unhandled errors, and we're adding new handlers to them as we find them in the logs so that we can return more useful information to you).

Thanks for filing!
