### ISSUE TITLE
The waiverdb UI prompt doesn't explain what the text box is for

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2270]
If a developer clicks on the waive button on an update, there is a pop up that has a text box and a submit button. The UI does not explain the purpose of this text box and it should. The text box is supposed to be justification for waiving the test failure.

**Comment by son-vyas** [comment]
Is this issue open,@bowlofeggs?
 If it is open then I would like to give it a try.

**Comment by bowlofeggs** [comment]
I believe that @ralphbean is fixing this in #2394. Is that correct Ralph? If so, can you update the commit message over there to also specify that it fixes this issue? Thanks!

**Comment by ralphbean** [comment]
Done.

**Comment by bowlofeggs** [comment]
This feature is planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
The fix for this issue has been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/
