### ISSUE TITLE
bodhi-approve-updates does not publish fedmsg notifications

### ISSUE THREAD

**Issue by elyscape** [fedora-infra/bodhi#2281]
[The bodhi-approve-updates script][bodhi-approve-updates] runs periodically and comments on updates that have spent enough time in testing to be pushed to stable but have not received enough karma to be automatically pushed. However, since this comment is made as the bodhi user, [no fedmsg notification is sent][excluded]. It would be nice if either these comments were published to fedmsg anyway or the script published notifications to a new fedmsg topic.

[bodhi-approve-updates]: https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/scripts/approve_testing.py
[excluded]: https://github.com/fedora-infra/bodhi/blob/4253073628d7a17192f03c5d1bd95d6e69503431/bodhi/server/models.py#L3015-L3020

**Comment by elyscape** [comment]
Publishing the comment messages to fedmsg anyway would be easiest but I think that it would be better to create a new fedmsg topic. Is there a process for creating a new fedmsg topic?

**Comment by bowlofeggs** [comment]
There probably is a process, but I'm not sure if it's documented. I suggest asking in #fedora-apps on Freenode.
