### ISSUE TITLE
exclude releases from the last page results in a nonsensical page

### ISSUE THREAD

**Issue by jsoref** [fedora-infra/bodhi#2316]
1. load https://bodhi.fedoraproject.org/updates/?packages=clamav&page=6
2. click `Exclude old releases`

See:
```
Page 6 of 4 « 1 2 3 4 »
Page 6 of 4 « 1 2 3 4 »
```
Expected results:
```
Page 4 of 4 « 1 2 3 4 »
(results)
Page 4 of 4 « 1 2 3 4 »
```

**Comment by bowlofeggs** [comment]
The exclude old releases feature was dropped in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
