### ISSUE TITLE
Search box doesn't work after using browser back button

### ISSUE THREAD

**Issue by jwakely** [fedora-infra/bodhi#232]
The fancy Web 2.0 UI isn't stateful and searches don't work after using "Back".

Steps to reproduce:
1. Go to https://bodhi.fedoraproject.org/
2. Type the name of an update into the "Search Bodhi" form on the top right (maybe use a valid update from the "Latest Critical Path Updates in Need of Testing View all" list so you get results)
3. Click on the update shown in the search results
4. Click the browser's Back button
5. Try to see the search results again

Expected results:
Search results still visible. Or if not, hitting enter or adding a space in the search box should redisplay the results.

Actual results:
The update is still shown in the search box but no search results are shown. You have to re-enter the same name, or delete a character and re-type it, to get the results back.

Also, adding a space in the search box should not say "unable to find any search results that match the current query", maybe trim whitespace from the search box input, so it's more user friendly.

**Comment by jwakely** [comment]
In fact the search results are even lost just by switching focus to a different browser tab, not just after hitting "Back"

Enter a search term that has results, switch to a different browser tab, switch back ... you've lost your results and need to re-enter the query.

**Comment by ryanlerch** [comment]
In bodhi 5.0 we now have searching an filtering in the updates list page (rather than just in to quick global search thing), and this does stay when navigating backwards.

See the following PR for more details on this one:
https://github.com/fedora-infra/bodhi/pull/3511
