### ISSUE TITLE
Bodhi should expire side tag updates when their time is up

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2320]
We don't want side tags to stick around in Koji for very long because they are expensive. We need Bodhi to be able to expire side tags, deleting the tag in Koji and untagging any builds that are found in it for later garbage collection.

We may be able to reuse the existing buildroot override expiration CLI tool, or perhaps we can make a new tool for this.

**Comment by bowlofeggs** [comment]
Bodhi will not be responsible for ensuring that side tags don't stick around for too long with the current plan.

@pypingou agreed?

**Comment by pypingou** [comment]
@bowlofeggs agreed, I'll track this somewhere so we do not forget about it
