### ISSUE TITLE
[M] Document how packagers will use Bodhi to manage Rawhide, including side tags

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2322]
SSIA

**Comment by pypingou** [comment]
I think https://docs.fedoraproject.org/en-US/packaging-guidelines/ may be a good place for this

**Comment by pypingou** [comment]
or https://fedoraproject.org/wiki/Package_update_HOWTO ?

**Comment by pypingou** [comment]
Which relates to: https://fedoraproject.org/wiki/Package_maintenance_guide

**Comment by nphilipp** [comment]
The Package update HOWTO looks like a better place than the packaging guidelines which really don't concern themselves with package updates.

To scope this, I propose the following:

## Acceptance Criteria

This is considered done when the [Package update HOWTO](https://fedoraproject.org/wiki/Package_update_HOWTO) documents that/how:

(for single package builds)
- builds of packages without gating tests will land in Rawhide as they did before
- gating tests will be executed on builds for packages that have them
  - if successful, the builds will be in the next Rawhide compose and subsequent buildroots
  - if unsuccessful, the builds will be blocked and need to be waived or fixed

(for side tag builds)
- users can create side tags using fedpkg (`fedpkg request-side-tag ...`)
- users can create updates containing all builds in a side tag
  - using the CLI like this: ...
  - using the UI like this: ...
- gating tests will be executed on builds for packages that have them
  - if successful, the builds will be merged into the parent tag and available in the next Rawhide compose and subsequent buildroots
  - if unsuccessful, the update will be blocked from merging and the failing builds will have to be waived or fixed

**Comment by nphilipp** [comment]
I've made a (temporary) [copy](https://fedoraproject.org/w/index.php?title=User:Nphilipp/Package_update_HOWTO) of the original Wiki page for review purposes, and described single build package gating in there ([diff](https://fedoraproject.org/w/index.php?title=User:Nphilipp/Package_update_HOWTO&diff=555150&oldid=555147)).

**Comment by nphilipp** [comment]
I've finished describing the multi-build/side tag aspect of it, see the ["Rawhide and early Branched"](https://fedoraproject.org/w/index.php?title=User:Nphilipp/Package_update_HOWTO#Rawhide_and_early_Branched) section. Once this is reviewed, I'll copy it over to the main article.

**Comment by nphilipp** [comment]
Thanks @pypingou for the review. Holding off with copying this into the main article until we're past soft-launch.

**Comment by nphilipp** [comment]
Here's the diff, as of now: https://fedoraproject.org/w/index.php?title=User%3ANphilipp%2FPackage_update_HOWTO&type=revision&diff=558694&oldid=555147

**Comment by nphilipp** [comment]
Hmm, I've done this long ago. Closing.
