### ISSUE TITLE
[S] The UI needs a way for users to create side tag updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2324]
Once the [API can create side tags](https://github.com/fedora-infra/bodhi/issues/3009), we should rework the UI so that users can create side tag updates or create traditional updates. We might be able to just add a new entry to the "Create" menu in the top bar that creates a side tag update, while reusing some of the existing create update form, but presenting a few different choices. For example, a side tag update should prompt the user for a release and a display name, and should not prompt the user for builds.

**Comment by ryanlerch** [comment]
So looking into this, the current new update form (the current non-tag behaviour) is quite unweildy, and doenst lend itself to abstracting out the parts needed for both it and the new side-tag update form.

What would be the best way to attack this?

1. make an entirely new form for sidetag updates, that has the elements in it, but abstracted out so we can in the future update the original form to work better?

2. fix the original form, and then work on including the side tage funtionality into it?

cheers,
ryanlerch

**Comment by pypingou** [comment]
Which way sounds best for you?
