### ISSUE TITLE
Can't push updates to stable

### ISSUE THREAD

**Issue by swt2c** [fedora-infra/bodhi#233]
I have a couple of updates that have been in testing for 7+ days, for example: https://bodhi.fedoraproject.org/updates/python-pyqtgraph-0.9.10-4.fc22

However, there is no button for allowing me to push this update to stable.

**Comment by keszybz** [comment]
Also https://bodhi.fedoraproject.org/updates/execstack-0.5.0-8.fc23.

**Comment by lmacken** [comment]
This issue has been resolved. Thanks for the report!
