### ISSUE TITLE
Quote markdown does not work

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/bodhi#2333]
According to the Fedora-Flavored Markdown cheatsheet, using the ``>`` prefix should produce block quotes.

> Like this!

But it doesn't actually. https://bodhi.fedoraproject.org/updates/kernel-4.16.4-200.fc27#comment-774421 was supposed to read:

> Missing the patch for the KVM problem as discussed in: https://bodhi.fedoraproject.org/updates/FEDORA-2018-b6be90818d

Yes... etc.

This makes reading comments containing quotes confusing :(

**Comment by bowlofeggs** [comment]
Yeah that does seem to be broken and the cheat sheet def says it should work. Thanks for the report!

**Comment by mattiaverga** [comment]
It's a css style problem, not a code fault.
`fedora-bootstrap` css doesn't style block quotes, so solutions are: open a bug on fedora-bootstrap asking them to modify the defaults, or override the style ourselves in `static/css/site.css`:
```
.markdown blockquote {
    margin: 0 1rem;
    color: #6a737d;
    border-left: 0.25rem solid #dfe2e5;
}
```

By the way, Bodhi embeds fedora-bootstrap 1.0.1 which is old, upstream is now at 1.2.0 (but doesn't fix this issue either).

**Comment by bowlofeggs** [comment]
@mattiaverga Thanks so much for looking into this! I would be amenable to either solution, or we could even pursue both (add CSS to Bodhi temporarily, until it's fixed in fedora-bootstrap).
