### ISSUE TITLE
Newlines in the greenwave_summary_string break the JavaScript that renders test results

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2335]
While testing #2273 in staging today, I noticed that updates that having missing tests do not render anything in the test results tab. I was able to reproduce this locally and I found that the problem is that the newline gets included in the JavaScript in a way that makes the JS invalid (and the browser refuses to process the rest of the JS as a result). The issue is [here](https://github.com/fedora-infra/bodhi/blob/3.6.1/bodhi/server/templates/update.html#L86):

```
var summary = '${update.greenwave_summary_string}';
```

It may be best to either use a different string to split the missing tests from the summary (perhaps something more unique too, like :::), or to put it into a new field of its own (which might be cleaner but will require a database migration).

This is a 3.7.0 release blocker.

**Comment by puiterwijk** [comment]
Right, there's no way to put a newline in a javascript string, other than an explicit `\n` (i.e. escaped).

**Comment by bowlofeggs** [comment]
As stated in #2334 I think I am going to add a new field to store the list of missing tests in. This way we don't need a special separator character.

**Comment by bowlofeggs** [comment]
Disclaimer: I'm real bad at UX stuff.

I've been fiddling today with getting Bodhi to give more useful information to the user since I'm giving Bodhi a dedicated field to store Greenwave's unsatisfied requirements. Rather than just giving the user a list of test names that didn't run, I think we should just give them the full list of unsatisfied requirements. It's a little tricky to massage the data from Greenwave into a human comprehensible format, but here's a stab I've taken at it:

![screenshot from 2018-05-01 14-56-01](https://user-images.githubusercontent.com/354506/39488433-45972684-4d50-11e8-9908-0e872fa69506.png)
