### ISSUE TITLE
Waiving an update leaves its test_gating_status in a failed state

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2364]
If a user waives failing tests on an update using the waive button, the update stays in a failed state until the next time the cron job runs. It would be more sensible to put it back into the "waiting on test results" state.

**Comment by ralphbean** [comment]
If we do #2370, this one should get solved as a side-effect.

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release

**Comment by bowlofeggs** [comment]
This fix is now deployed to Fedora's production instance.
