### ISSUE TITLE
[S/M] The waiver hoverovers in the web UI do not say what the name of the waived test was

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2365]
If I hover over the cloud icons on an update that has waivers, it tells me the waiver number (not particularly useful) and the comment the person submitted with their waiver (useful). It does not tell me which test was waived and that would be useful to know.

![screenshot from 2018-05-08 15-43-07](https://user-images.githubusercontent.com/354506/39779265-a4e3003c-52d6-11e8-80c1-f07b01f1fb34.png)

**Comment by ralphbean** [comment]
Yes.  I *think* that this issue should be fixed if we move the waiver notifications all to the "test results" page where we can spell out exactly what was waived.

We could display "Tests Passed" but with an asterisk indicating that there is at least one waiver.  Clicking will take you to the test results page with all the gory details.

See also #2370.  It is a refactor task which will hopefully fix this.  Leave this open in case not.

**Comment by ralphbean** [comment]
This should be fixed in #2393.

**Comment by bowlofeggs** [comment]
The update doesn't show which tests were waived when the tests were missing:

![screenshot from 2018-07-31 14-44-41](https://user-images.githubusercontent.com/354506/43480110-45a82944-94d0-11e8-8260-2f97c9d4cbda.png)

**Comment by bowlofeggs** [comment]
Small/Medium

**Comment by sebwoj** [comment]
@bowlofeggs I'm not understand the isssue. We can check waived test cases in `Automated Tests` tab.

![waived tc](https://user-images.githubusercontent.com/42519683/54883468-3b4c5600-4e66-11e9-9b66-c7a2e7bc59b0.png)

And after #3089, we could check all informations,

BTW, I cant find update with build `python-rpdb-0.1.6-7.fc27`, also build `python-rpdb-0.1.6-7.fc27` itself is not exists.

**Comment by bowlofeggs** [comment]
Hello @sebwoj!

That shows that it was waived, but you can't find out what the waiver message was, which should tell you why it was waived. Clicking that thumbs up icon takes you to a forbidden URL.

**Comment by sebwoj** [comment]
`thumbs up icon` itself is not a link. Informations(waiverdb id and reason) are shown only in the "pop up" when user hover over this icon.
The reason why user is redirected to "forbidden" url is that all test cases are links.
So to summarize, what behavior do you expect?
Maybe we can use dead code from #3088

**Comment by bowlofeggs** [comment]
The behaviour I expect is for there to be some way for users to see what the waiver message was when tests were waived.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by bowlofeggs** [comment]
Sure, thanks!

**Comment by bowlofeggs** [comment]
The fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
