### ISSUE TITLE
It is not obvious what the cloud icons for waivers are for

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2369]
Bodhi's UI displays waivers as little clouds with up arrows in them in the "Test Gating Status" area:

![screenshot from 2018-05-08 15-43-07](https://user-images.githubusercontent.com/354506/39779265-a4e3003c-52d6-11e8-80c1-f07b01f1fb34.png)

It's not obvious that these serve a purpose, unless you hover over them. Two ideas to improve this:

1. Make a "Waivers" section and put them there.
2. Use some other icon. Or possibly, don't use an icon at all, but use the name of the nvr and test that was waived.

**Comment by bowlofeggs** [comment]
Here's an update with a waiver: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a13691074b

**Comment by ralphbean** [comment]
This should be fixed in #2393.
