### ISSUE TITLE
Bodhi should live query greenwave

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#2370]
Talking with @bowlofeggs today, we think that the database table cache, and the cronjob and the fedmsg updater are not worth it for the greenwave integration.

Instead, let's do a few things:

- [x] Replace the frontend display of resultsdb results and greenwave decision with a live ajax query to greenwave to get both the results and the decision.
- [ ] Replace the backend query of the cache at compose time with a live http query to greenwave to get the decision.
- [ ] The cornice service that accepts requests to push to stable or batched needs to also live query greenwave to know if the packager's request is allowed.
- [ ] Delete the cronjob.  Delete the database model and add a migration to drop that biz.

Tests, of course.

**Comment by bowlofeggs** [comment]
If we do this refactor as proposed, I believe #2364 should be automatically fixed.

**Comment by bowlofeggs** [comment]
Thanks to @puiterwijk for placing the thought of this design into my head ☺

**Comment by bowlofeggs** [comment]
Technically removing the test_gating_status from the DB will also remove it from the API, unless we make the API also live query Greenwave. I'm OK with removing it, but we should note that if we do that it will be a backwards incompatible change. I've been piling up quite a few of those for a while, so maybe it's just time to make Bodhi 4 now.

**Comment by ralphbean** [comment]
More like Bodhi 4000 :rocket:.

**Comment by bowlofeggs** [comment]
Question: would it be interesting to have the Bodhi backend live-query Greenwave instead of doing it in JS? Pros/cons:

Pro: We can share more code between the CLI and the web UI for test gating - 1 implementation instead of 2.
Pro: IMO, the mako templating language is nicer to work with than creating HTML with JS
Con: Bodhi's response will be slower than it is now.

@puiterwijk suggested a hybrid of giving Bodhi and endpoint that queries greenwave and returns. Similar pro/con as above. At first I thougth you would lose the second pro, but the JS could ask for HTML from the new endpoint so we could still have it render a template if we want.

**Comment by bowlofeggs** [comment]
No matter how we do this, we will need to make sure Bodhi does sane things when Greenwave doesn't give back a response in time, or when it gives back an error.

**Comment by bowlofeggs** [comment]
We had a big discussion about this in #fedora-apps today. I think we all seemed to come to the conclusion that neither of the three proposed methods is obviously superior to any of the others, so I think the pure JS proposal is fine as the de-facto proposal. Here's a slice of that discussion (there's more but we got into all kinds of other topics so I'm snipping it to just this bit):

```
<bowlofeggs> threebean, puiterwijk: before we go too far into implementing https://github.com/fedora-infra/bodhi/issues/2370 - would it be interesting to have the backend live query greenwave rather than having JS do it?
<bowlofeggs> there's +'s and -'s to it, as always
<bowlofeggs> +'s are that it will make it so the CLI can share code with the web UI
<bowlofeggs> -'s is that it'll make bodhi slower at serving the page
<puiterwijk> bowlofeggs: alternative
<puiterwijk> How about the javascript can query it, *but* it gets it from a Bodhi API call?
<bowlofeggs> another + is that the template language is nicer than JS for expressing how the page HTML is
<bowlofeggs> puiterwijk: not bad, though that loses the second + i just wrote
<puiterwijk> Agreed.
<bowlofeggs> to be clear, i'm not -1 to the current proposal of pure JS
<bowlofeggs> i just want us to consider all options :)
<bowlofeggs> maybe it's not bad to just have two implementation, one in JS and one in pythn
<bowlofeggs> you know, i'm gonna move this discussion into the ticket so we have history and what not
<bowlofeggs> puiterwijk: actually i think you don't lose the second pro with your suggestion, see [the ticket]
<puiterwijk> bowlofeggs: right
<puiterwijk> Now, just serving raw HTML is.... scary.
<puiterwijk> But we can see about implementation
<bowlofeggs> puiterwijk: well it'd work like any of the other cornice services - the request header just says whether it wants HTML back or JSON
<puiterwijk> bowlofeggs: sure. But what I mean is that any javascript that just inserts raw html it got from a remote service is scary.
<bowlofeggs> puiterwijk: well the HTML would be rendered by bodhi for bodhi's UI
<puiterwijk> Since what if that html contains <script src="https://evilsite.com/pwnmybox.js" />
<bowlofeggs> puiterwijk: if bodhi can inject that into this view, it could just inject it into any other view anyway
<puiterwijk> bowlofeggs: yes, as long as we make 100% sure that this call will only ever be called by the Bodhi code.
<threebean> :d
<threebean> i'd prefer if the bodhi server just returned json for the greenwave results.
<puiterwijk> i.e. my main "fear" is that someone figures out a way to make the browser call that "inject html at X" code with... a less benign url
<threebean> and let javascript prepare the layout.
<threebean> html fragments get all weird to debug later on.
<bowlofeggs> threebean:  to be clear, i'm not opposed to the de-facto proposal of just doing pure JS and not adding a new endpoint to bodhi
<threebean> but, I'm +0 to consolidating the greenwave query in one server-side cornice thingie.
<bowlofeggs> just want us to consider alternatives so we explored more ideas :)
<threebean> meaning, I am warmly ambivalent.  :p
<bowlofeggs> yeah i think i feel similarly
<puiterwijk> threebean: do you have a +0 and -0? :D
<bowlofeggs> it's not clearly better or worse to me
* puiterwijk looks at sign bits
<threebean> it is a 0 with nuance :p
<threebean> a 0 that's going places!
<bowlofeggs> the JS is nice because it makes bodhi feel faster
<bowlofeggs> because you can start rendering the page and then get more data later
<bowlofeggs> and bodhi isn't fast as is
```

**Comment by ralphbean** [comment]
Assigning to myself to do the javascript part.  Will try and remember to unassign when I'm done.

**Comment by bowlofeggs** [comment]
@ralphbean Bodhi 3.9.0 was deployed to production today, and it seems that Greenwave is not reporting any test results on the handful of updates that I spot checked:

https://bodhi.fedoraproject.org/updates/FEDORA-2018-01a9c96b51
https://bodhi.fedoraproject.org/updates/FEDORA-2018-23703f460d
https://bodhi.fedoraproject.org/updates/FEDORA-2018-60fdb8b0aa

This seemed to work before - any idea what's going wrong?

**Comment by bowlofeggs** [comment]
I've filed a new issue about the above: https://github.com/fedora-infra/bodhi/issues/2554

**Comment by bowlofeggs** [comment]
It seems that Greenwave is not giving us the data that Bodhi expects to receive:

```
curl 'https://greenwave-web-greenwave.app.os.fedoraproject.org/api/v1.0/decision' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/json' -H 'Origin: https://bodhi.fedoraproject.org' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --data '{"product_version":"fedora-28","decision_context":"bodhi_update_push_stable","subject":[{"item":"bodhi-3.9.0-1.fc28","type":"koji_build"},{"original_spec_nvr":"bodhi-3.9.0-1.fc28"},{"item":"FEDORA-2018-01a9c96b51","type":"bodhi_update"}],"verbose":true}'
{
  "applicable_policies": [
    "taskotron_release_critical_tasks_for_stable", 
    "atomic_ci_pipeline_results_stable"
  ], 
  "policies_satisfied": true, 
  "results": [], 
  "satisfied_requirements": [], 
  "summary": "no tests are required", 
  "unsatisfied_requirements": [], 
  "waivers": []
}
```

**Comment by AdamWill** [comment]
The 'no test results shown in Bodhi' bug(s) are fixed now, I think. A [NetworkManager update like this](https://bodhi.fedoraproject.org/updates/FEDORA-2018-03adc6f45c) is a good one to check as it'll be tested by The Pipeline *and* Taskotron *and* openQA, and indeed, you can see results from all three on its 'Automated Tests' tab. The only minor issue I see is that the pipeline tests are shown under a title 'undefined', when I'd expect them to be listed under the NVR - probably related to how pipeline results include the NVR not as the `item` but as `original_spec_nvr`.

**Comment by AdamWill** [comment]
I don't think there's anything left to do in this ticket (though it's cool to find the origin story of why we live query greenwave in the web UI frontend!) These days I believe things basically work the way this ticket intended them to. I think this could be closed.
