### ISSUE TITLE
[L/S, depending on Greenwave or not-Greenwave] Bodhi does not show which tests are missing

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2371]
There was a [recent patch](https://github.com/fedora-infra/bodhi/pull/2345) that was aimed at adding a list of unsatisfied test requirements to the top of the test results. Unfortunately, it was designed to use some data that [Greenwave no longer returns in production](https://pagure.io/greenwave/issue/169#comment-511247) which means the feature does not work.

We need to make it so Bodhi can show users which tests are missing or failed.

We need to do this for the CLI and the Web UI.

**Comment by bowlofeggs** [comment]
https://pagure.io/greenwave/pull-request/184 is likely relevant to pay attention to for this ticket, as the Greenwave v2 API may present this data in a different and more structured way than the current API.

**Comment by bowlofeggs** [comment]
I learned from @ralphbean that Greenwave may not have changed which things it returns, but that it might just not always return "koji_builds" when there are missing tests. Thus, perhaps it was a bad idea for me to have filtered for those in my patch. The goal there was to eliminate duplicates because there can be two elements in the greenwave response that are both the NVR and I only wanted to display one of them to the user.

We could either just stop trying to be helpful with deduplication and just show the user what we got from Greenwave (including duplicates), or we could try to make the deduplication a bit smarter than just filtering for "koji_builds".

**Comment by cverna** [comment]
So after a bit of wiggling in the html template I got to something that looks like that. We still get duplicated results but I think that comes from our request to greenwave. If we stop asking for the `original_spec_nvr` we don't have duplicated results

![image](https://user-images.githubusercontent.com/7237866/56960662-de714900-6b51-11e9-8afe-f77bf0561c68.png)

**Comment by sebwoj** [comment]
@cverna Take a look at #3089.

**Comment by cverna** [comment]
#3219 was merged and addresses this ticket
