### ISSUE TITLE
3.7.0(?) seems to fail to recognize updates-pending status

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#2372]
Today, I see lots of messages like this: https://bodhi.fedoraproject.org/updates/FEDORA-2018-d8511ad131
```
magic-8.2.60-1.fc27 ejected from the push because u"Cannot find relevant tag for magic-8.2.60-1.fc27. None of ['f27-updates', 'f27-updates-pending'] are in [u'f22-updates-testing', u'dist-6E-epel-testing', u'f21-updates-testing', u'f25-updates-testing', u'f24-updates-testing', u'epel7-testing', u'f27-modular-updates-testing', u'dist-5E-epel-testing', u'f23-updates-testing', u'f26-updates-testing', u'f28-updates-testing', u'f27-updates-testing', u'f28-modular-updates-testing']."
```
, although magic-8.2.60-1.fc27 seems to be already tagged as f27-updates. Another example is https://bodhi.fedoraproject.org/updates/FEDORA-2018-0efbc823e5 , and actually there are others.

So currently today's updates status  seems inconsistent. Would you investigate current status?

**Comment by bowlofeggs** [comment]
Hi @mtasaka!

This is due to #2368, so let's track the issue there. See also https://pagure.io/fedora-infrastructure/issue/6925 which is where I'm tracking fixing Fedora's deployment of Bodhi.
