### ISSUE TITLE
Clear completed repo from status when repo sanity checks fail

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#2374]
Sometimes we have hit a case where repo sanity checks fail. Usually a nfs problem or the like. 

The "fix" is to go into the db and tell it on the status of that compose that it doesn't already have a completed repo and resume it. It then recreates the repo/re-runs pungi and hopefully all is well. 

If it could just wipe that completed repo status anytime the repo sanity checks failed it would help us not have to go into the db and manually do that. Then we could just fix the cause (nfs, or whatever) and resume and it will redo the repo.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
