### ISSUE TITLE
Handle missing release when editing

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#238]
Production traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/services/updates.py", line 288, in new_update
    up = Update.edit(request, data)
  File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 772, in edit
    data['title'], data['release'].long_name, up.url))
KeyError: 'release'
```

**Comment by lmacken** [comment]
This could be related to issue #234

**Comment by ralphbean** [comment]
Agreed.  The validators should still catch the empty release before getting to the models.  Will work on it!

**Comment by ralphbean** [comment]
OK, the schema for saving/editing an update doesn't even have a field for passing the release explicitly.. it is derived from the builds afterwards.  So, this was (yes) a side-effect of #202 and can be closed.
