### ISSUE TITLE
Submitter filed issue, wrong person listed

### ISSUE THREAD

**Issue by agony** [fedora-infra/bodhi#241]
https://bodhi.fedoraproject.org/updates/gstreamer1-plugins-good-1.5.2-2.fc23
That package is listing me as the submitter, but all I did was giving karma days ago.

The comment section is correctly listing "wtaymans" as the one who submitted the Update.

**Comment by kkofler** [comment]
Same issue here: https://bodhi.fedoraproject.org/updates/calamares-1.1.2-1.fc22 – submitted by me, but lists dremor as the "submitter" when he only gave karma.

**Comment by error10** [comment]
Also affected https://bodhi.fedoraproject.org/updates/docker-compose-1.2.0-3.fc22

**Comment by ralphbean** [comment]
**Theory**:  this was a bug in the migration tool from bodhi1 to bodhi2 that mis-assigned submitters.

Can anyone confirm that this has happened to updates that were created/commented on **after** bodhi2 went live?

(If so, we still have the old bodhi1 DB, so we could write a patch-up tool that will fix the old submitter assignments...)

**Comment by kkofler** [comment]
For calamares-1.1.2-1.fc22, the comment was done on Bodhi 1, before Bodhi 2 went live.

**Comment by lmacken** [comment]
I can confirm that the data in the bodhi1 snapshot is correct, so this is an issue with the migration tool.

**Comment by lmacken** [comment]
Testing out a fix in staging. I think this is related to how we cached SQLAlchemy objects.

**Comment by lmacken** [comment]
Looks like < 1% of updates are affected by this. Will fix it in production shortly.

**Comment by lmacken** [comment]
Running this script in production.
https://gist.github.com/lmacken/4ea39791146a0e027408

**Comment by lmacken** [comment]
This issue has been resolved (about 2.5% of updates in production were affected. The <1% was in staging against the F20 EOL snapshot).

Please re-open this issue if you notice any more weirdness of this sort. Thanks!
