### ISSUE TITLE
Unable to add comment/karma

### ISSUE THREAD

**Issue by agony** [fedora-infra/bodhi#242]
bodhi is not letting me comment and give karma.

Tried other browsers and clean profiles, always the same issue.

 This is the only error message:
![error](https://cloud.githubusercontent.com/assets/14168/9384911/b3742ee6-4753-11e5-988f-f04d2233e6e6.png)

**Comment by ralphbean** [comment]
I think #243 should fix this.

**Comment by ralphbean** [comment]
OK, closing.  Please re-open if you hit it again (or file a new ticket if you see a new issue).
