### ISSUE TITLE
Remove bodhi-manage-releases

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2420]
This should not be done until there is a release with #2419. Once that exists, we should remove the old ```bodhi-manage-releases``` CLI.

**Comment by sebwoj** [comment]
@bowlofeggs Since #2419 is closed, can remove bodhi-manage-releases?

**Comment by bowlofeggs** [comment]
I'm not quite yet ready to make Bodhi 4.0.0, and so all issues marked backwards incompatible would not be good to merge just yet. I will probably make 4.0.0 this fall however. We can just keep this PR open until then.

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
