### ISSUE TITLE
Bodhi should know which packages are critical path without outside help

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2433]
PDC is going away, and Bodhi uses it to know which packages are critical path. It seems that Bodhi is the only application in Fedora Infrastructure that cares about whether a package is critical path, so it is sensible to move this information into Bodhi's database. This will reduce one of our external service dependencies, which should increase reliability.

Packages are critical path *per release*, which means that a package, for example, might be critical path in Fedora 27 but not Fedora 28, so we will need to be sure to model it in such a way that allows that information to be encoded.

Release engineering has a script they use to update PDC with information about which packages are critical path. We will need to work with them to ensure that their script is able to update Bodhi's critical path packages.

**Comment by cverna** [comment]
@vismay-golwala 
I think we should add to the `Release` db model a new attribute that will list the critical path packages for this update. To do that you should look at the [Many-to-Many](https://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#many-to-many) relationship in sqlalchemy. 
Since we want a relationship between `Release` and `Packages` and one `Release` can have many critpath `Packages` and one `Packages` can be critpath to many `Releases`

**Comment by ghost** [comment]
Should the critical path packages for a release be displayed in the server view (https://bodhi.fedoraproject.org/releases/F27)?

If yes, what details should be included for the package?

**Comment by ghost** [comment]
Also, is it a good idea to rename the ```--username``` option to ```--user``` for ```bodhi releases``` command? As all other commands (```bodhi updates```, ```bodhi overrides```) use ```--user```.

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/__init__.py#L112

**Comment by bowlofeggs** [comment]
On 07/18/2018 12:15 PM, Vismay Golwala wrote:
> Should the critical path packages for a release be displayed in the
> server view (https://bodhi.fedoraproject.org/releases/F27)?

For the purposes of this issue I don't think we need to make the web UI
show critical path packages. If someone really wants that they can add
it later in a separate patch, but I expect that nobody will want it.

**Comment by bowlofeggs** [comment]
On 07/18/2018 12:17 PM, Vismay Golwala wrote:
> Also, is it a good idea to rename the |--username| option to |--user|
> for |bodhi releases| command? As all other commands (|bodhi updates|,
> |bodhi overrides|) use |--user|.

That would be a good thing to do, but I have two thoughts:

0. If we want to do this, we must do it now before I release 3.9.0,
because once that is released we won't be able to change it anymore.

1. We need to make sure it stays --username for bodhi-manage-releases to
maintain backwards compatibility.

**Comment by keszybz** [comment]
See also https://pagure.io/releng/issue/8948 (request to update critpath list in pdc).

**Comment by mattiaverga** [comment]
Fixed in #5431
