### ISSUE TITLE
"Push to Stable" silently redirects me back to the homepage

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#244]
https://bodhi.fedoraproject.org/updates/python-shove-0.6.3-1.el6

This update has yet to meet the testing requirements. When I hit Push to Stable (the button is there because I'm in releng), it just redirects me back to the homepage without any information.

**Comment by thmo** [comment]
Same here, e.g. for
https://bodhi.fedoraproject.org/updates/python-regex-2015.07.19-1.el7

**Comment by opoplawski** [comment]
This is a real pain.
