### ISSUE TITLE
Links from grouped update messages on frontpage are broken

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#245]
The frontpage says: 
lmacken submitted 2 python-shove testing updates for EL-6
and links to:
https://admin.fedoraproject.org/updates/python-shove/

First off, I only submitted a single update, but revoked the and set the request over and over for testing.

Second, the link is broken. Removing the trailing slash fixes it.

**Comment by ralphbean** [comment]
Should be fixed by [this ansible commit](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=ab1674315205f349a2830c1118e99f55c4953d4d).
