### ISSUE TITLE
bugs can't be marked as fixed

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#2456]
In https://bodhi.fedoraproject.org/updates/FEDORA-2018-1a6e6196b9 I tried to mark #1580530 as fixed by giving it +1 feedback (directly for that bug). But only generic karma was shown in my [comment](https://bodhi.fedoraproject.org/updates/ansible-2.5.5-2.fc28#comment-800652), not the specific bug report karma. Also in Bugs tab the feedback was not shown. I tried again (this time without giving generic karma), and [again](https://bodhi.fedoraproject.org/updates/ansible-2.5.5-2.fc28#comment-800653) it was ignored.

It seems that giving karma for particular bugs is broken atm.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
