### ISSUE TITLE
Unable to manually add bugs to an update

### ISSUE THREAD

**Issue by snbueno** [fedora-infra/bodhi#246]
Numerous bugs were missed when bodhi automatically tried to create the list of related bugs for an update. If I try to edit the update and enter a bz# in the search/text field, bodhi does not seem to find it and present it as an option for me to select.

**Comment by ralphbean** [comment]
You're not the only one having this issue -- a lot of people are confused by it (which means we need to change it to make it more obvious!)

You have to type in the bz# and then **press enter**... and it will appear in the list below.  We're going to add some buttons to make this not-so-magical.

**Comment by snbueno** [comment]
Aha, that definitely works; thanks a lot!

Heh, one thing though, adding a whole line of comma-separated or space-separated bugs adds them as if they're all one bz query: https://sbueno.fedorapeople.org/adding-bugs.png
It might be nice to have that functionality like in the old bodhi back at some point if that's not too painful to implement.

**Comment by ralphbean** [comment]
> It might be nice to have that functionality like in the old bodhi back at some point if that's not too painful to implement.

This is done now.

Buttons coming soon!
