### ISSUE TITLE
karma voting section for anonymous users should indicate their karma will be ignored

### ISSUE THREAD

**Issue by jsoref** [fedora-infra/bodhi#2474]
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-88c0c447a4
has what appears to be three karma: 👍items.
But, afaict, the third, from anonymous is ignored by the calculator.
We believe that's to protect against bots. That's fine, but I'm fairly confident a human wrote that message.

It would be nice if the interface told the human that they should use an account if they want their vote to be tallied.

**Comment by mattiaverga** [comment]
Shall I work on this?
I think to disable karma radio buttons and to display a warning if the user is not logged in, like this mockup:
![screenshot_20180720_173515](https://user-images.githubusercontent.com/17218209/43011467-d5a49658-8c43-11e8-8c0b-05b3423822d8.png)
I think it could be useful to keep the possibility for anonymous users to vote on bugs and testcases, so I would not disable the other radio buttons. What's your opinion?

**Comment by jsoref** [comment]
So... That might be the right overall approach.

Minor UX problem: there's nothing obvious in that last item indicating that it *is* / *represents* karma. Or put another way, how are the other +1 / -1's not karma?

I think that changing:
"Is the update generally functional?"

to:
"Is the update generally functional? (karma)"
would address that.
