### ISSUE TITLE
Add support to the cli to edit the release email template name

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#2475]
The name of the email template used for each release was added to the database in #2469. It should be possible to edit this field from the cli using the `bodhi release` command

**Comment by bowlofeggs** [comment]
This feature is planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
This feature is available in Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/
