### ISSUE TITLE
Single-package updates that obsolete multi-package updates leave old update in testing

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/bodhi#2479]
Suppose you have an update that contains two packages, A-1.0 and B-1.0. You then create a new update for just A-2.0. My expectation is that this would obsolete the (A-1.0, B-1.0) update. However, this does not happen: the [kernel-4.17.4, kernel-tools-4.17.4](https://bodhi.fedoraproject.org/updates/FEDORA-2018-0f7448b3ab) update is still marked as in testing, but [kernel-4.17.5](https://bodhi.fedoraproject.org/updates/FEDORA-2018-8484550fff) is in stable.

This is something of an edge case. I guess what I'd expect to happen is that the bugs would be merged for the two updates, and the newer A build would replace the old A build, while the B build remained in the update. However, it seems like leaving the update in testing when a newer package is in stable is weird.

**Comment by mattiaverga** [comment]
Same as #1087

**Comment by jeremycline** [comment]
Ah, thanks. I should have hunted for dupes first :)
