### ISSUE TITLE
Problem with EPEL updateinfo data

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/bodhi#2487]
On a test centos7 VM with both epel and epel-testing enabled, `yum updateinfo` has many complaints about the metadata (which means that yum-cron spams me with those complaints on a regular basis).  The complaints take this form:
```
Update notice FEDORA-EPEL-2018-ccbfac33e4 (from epel-testing) is broken, or a bad duplicate, skipping.
```
Full output from `yum -v updateinfo` is below.  The issue seems to be threefold:
* The update metadata are not removed from updates-testing when the updates are pushed to stable.
* The metadata are altered when the updates are pushed to stable.
* yum is annoyingly strict in the metadata that it accepts. It could just take the most recent metadata for each update, since it's complaining about timestamps.

The issue persists for quite some time, so it's not just an unfortunate check in between epel and epel-testing pushes.  And it happens on multiple mirrors, so it's not just a problem with my local pubmirror*.math.uh.edu machines.  yum will completely refuse to give any information about one of these updates (besides the complaints) so this could have the result that some process ignores these updates.  That could be pretty bad depending on what uses them.  (yum-cron has the ability to install only security updates and I think it uses this information to determine those, which could potentially be a serious issue.)

```
[root@test-el7 ~]# yum -v updateinfo
Loading "changelog" plugin
Loading "fastestmirror" plugin
Config time: 0.017
Yum version: 3.4.3
rpmdb time: 0.000
Duplicate of FEDORA-EPEL-2018-be727516a8 differs in some fields:
<<<<<<< epel-testing:issued
'2018-07-16 18:07:55'
=======
'2018-07-17 13:27:35'
>>>>>>> epel:issued
Update notice FEDORA-EPEL-2018-be727516a8 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
Duplicate of FEDORA-EPEL-2018-ccbfac33e4 differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:05'
=======
'2018-07-18 16:19:59'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-ccbfac33e4 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-8aacc66280 differs in some fields:
<<<<<<< epel-testing:issued
'2018-07-01 03:05:29'
=======
'2018-07-17 13:27:35'
>>>>>>> epel:issued
Update notice FEDORA-EPEL-2018-8aacc66280 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-b6c144fd80 differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:17'
=======
'2018-07-18 16:12:42'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-b6c144fd80 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-95e735b8cf differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:29'
=======
'2018-07-18 16:14:45'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-95e735b8cf (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-00485dde65 differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:34'
=======
'2018-07-18 16:22:32'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-00485dde65 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-600818773b differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:41'
=======
'2018-07-18 16:21:08'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-600818773b (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-714d1f5d7c differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:46'
=======
'2018-07-18 16:18:06'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-714d1f5d7c (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-a2b0c16057 differs in some fields:
<<<<<<< epel-testing:issued
'2018-07-01 22:57:49'
=======
'2018-07-17 13:27:35'
>>>>>>> epel:issued
Update notice FEDORA-EPEL-2018-a2b0c16057 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2018-83ea866ee5 differs in some fields:
<<<<<<< epel-testing:updated
'2018-07-16 18:08:49'
=======
'2018-07-18 16:21:10'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2018-83ea866ee5 (from epel-testing) is broken, or a bad duplicate, skipping.
updateinfo time: 1.694
Building updates object
Setting up Package Sacks
Loading mirror speeds from cached hostfile
 * base: reflector.westga.edu
 * epel: pubmirror1.math.uh.edu
 * epel-testing: pubmirror1.math.uh.edu
 * extras: repos-tx.psychz.net
 * updates: mirrordenver.fdcservers.net
pkgsack time: 0.195
up:Obs Init time: 0.264
up:simple updates time: 0.011
up:obs time: 0.005
up:condense time: 0.000
updates time: 0.929
updateinfo summary done
```

**Comment by bowlofeggs** [comment]
Hello @jasontibbitts!

That does not sound good. Did this recently start happening? There hasn't been a Bodhi deployment in a while (perhaps 6-8 weeks iirc) so I'm a bit surprised if it just started.

In any case, we should fix this. Thanks for the report.

**Comment by jasontibbitts** [comment]
I only started seeing it relatively recently myself; within the past month, but to be honest I may not have had updates-testing enabled on this VM before that.  I did a search and found a report of something similar over two years ago: https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/message/SRELH2OH2KXJUINHT6QKGKW2OUABF75S/
But I can't say if the underlying cause is the same.  The more recent report is https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/message/EN4NLN5JQ6RTW4NC23SM44Y7XW3GXFFM/ from just over a month ago.

What the first message tells me is that yum in RHEL7 has done similar checks for quite some time, so this doesn't appear to be a case of yum being updated to complain about a case where before it was silent.

**Comment by jasontibbitts** [comment]
I also note that old updates do seem to get pruned at some point and sometimes things are OK.  For example for the past couple of days, up to and including Sun, 22 Jul 2018 00:01:08 -0500, I got this once per hour:
```
Update notice FEDORA-EPEL-2018-488c9cde12 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
Update notice FEDORA-EPEL-2018-2a87964159 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-a4e2fee578 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-1b2a2c2565 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-bcd34dc8d0 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-d9b2811b79 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-8d000d1dc6 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-2c0fe021fc (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-29e2ddd9d4 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2018-cf616220e5 (from epel-testing) is broken, or a bad duplicate, skipping.
```
Then it was quiet for a bit over a day.  And then this started showing up hourly beginning at Mon, 23 Jul 2018 01:01:18 -0500 and continues as I type this:
```
Update notice FEDORA-EPEL-2018-49c7c88f85 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
Update notice FEDORA-EPEL-2018-7853163ec6 (from epel-testing) is broken, or a bad duplicate, skipping.
```
I suspect it would be interesting to compare these times with the past few epel7/epel7-testing composes but I don't know how to get them.

**Comment by jasontibbitts** [comment]
There was a mention on IRC today of something which might be related.  It seems that the metadata for updates is continuously updated, so that even old updates appear to be new:
```
[08:14] <khanyooh> with a recent fun I've had with satellite6 content view filters, I've spotted something that is very confusing and would like to ask whether it's actually intended or not
[08:17] <khanyooh> Essentially, nearly all the EPEL7 errata updates' "updated date" is set to <the last evening>
[08:18] <khanyooh> out of 4299 packages I can see now are synced, 3961 packages seem to have been updated yesterday
[08:20] <khanyooh> this applies to all the update types: bugfix, enhancement, security and newpackage (the last one cannot be filtered by type on Sat6 though)
[08:22] <khanyooh> looking at the file from the random mirror: http://mirror.inode.at/epel/7/x86_64/repodata/20d98a8faff6a29ffa59ac0e88813f73022b917aadfc3c001da78d76d7904103-updateinfo.xml.bz2
[08:22] <khanyooh> $ bzgrep -A6 "update.*type=" 20d98a8faff6a29ffa59ac0e88813f73022b917aadfc3c001da78d76d7904103-updateinfo.xml.bz2 | less
[08:24] <khanyooh> It's absolutely fine until one wants to use <Erratum by Date (and Type)> filters
[08:25] <khanyooh> is that intended for any reason?
[08:35] <khanyooh> note: I figured that when I wanted to filter by the past date, let's say May 14th 2018, it gives me approx 3617 packages ~ 187 errata then
```

**Comment by avantsysadm** [comment]
Hi @bowlofeggs,

The Red Hat Bugzilla folks pointed me in this direction. I see this issue is still open and we're having a similar problem. Let me know if it should be attached in its own issue.

Our error output from `yum check-update`

> Update notice FEDORA-EPEL-2019-b1b73eda91 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
Update notice FEDORA-EPEL-2019-c44b218d4a (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d6bedfa33e (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-6c9bd69e8c (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-17d2b3507b (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d08cc0cf56 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-63395bd546 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-b3b252ad49 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-936f369393 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-77e03a194b (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-caf5e780e6 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-a6e87b96c1 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-0ad24584d8 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-f457d4367d (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-f84c232513 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-8cbc520a97 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d50307dc61 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-10c651b6cf (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d49efff651 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-1e0469226c (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-906483cc2f (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-3221ff1dea (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-8618614749 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-7d7926ef71 (from epel-testing) is broken, or a bad duplicate, skipping.

EDIT: Thanks @bowlofeggs , I've opened a separate issue for this ([here](https://github.com/fedora-infra/bodhi/issues/3937)), and will follow up on the Freenode channel.

**Comment by bowlofeggs** [comment]
Hi @avantsysadm! I no longer work at Red Hat, or on Bodhi, but perhaps you can ping the #fedora-apps channel on Freenode.

**Comment by mattiaverga** [comment]
At first I had thought it may be related to https://github.com/fedora-infra/bodhi/issues/3944#issuecomment-596189098 but then I saw other examples that are unrelated to that.
For example:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7610
https://koji.fedoraproject.org/koji/buildinfo?buildID=676882
```
  <update from="updates@fedoraproject.org" status="stable" type="newpackage" version="2.0">
    <id>FEDORA-EPEL-2015-7610</id>
    <title>rubygem-shellany-0.0.1-1.el7</title>
    <issued date="2015-11-10 15:17:03"/>
    <updated date="2020-03-06 22:02:38"/>
    <rights>Copyright (C) 2020 Red Hat, Inc. and others.</rights>
    <release>Fedora EPEL 7</release>
    <severity>None</severity>
    <summary>rubygem-shellany-0.0.1-1.el7 newpackage update</summary>
    <description>MRI+JRuby compatible command output capturing.</description>
    <references>
      <reference href="https://bugzilla.redhat.com/show_bug.cgi?id=1249791" id="1249791" type="bugzilla" title="Review Request: rubygem-shellany - Simple, somewhat portable command capturing"/>
    </references>
    <pkglist>
      <collection short="EPEL-7">
        <name>Fedora EPEL 7</name>
        <package name="rubygem-shellany" version="0.0.1" release="1.el7" epoch="0" arch="src" src="https://download.fedoraproject.org/pub/fedora/linux/updates/7/SRPMS/r/rubygem-shellany-0.0.1-1.el7.src.rpm">
          <filename>rubygem-shellany-0.0.1-1.el7.src.rpm</filename>
        </package>
        <package name="rubygem-shellany-doc" version="0.0.1" release="1.el7" epoch="0" arch="noarch" src="https://download.fedoraproject.org/pub/fedora/linux/updates/7/i386/r/rubygem-shellany-doc-0.0.1-1.el7.noarch.rpm">
          <filename>rubygem-shellany-doc-0.0.1-1.el7.noarch.rpm</filename>
        </package>
        <package name="rubygem-shellany" version="0.0.1" release="1.el7" epoch="0" arch="noarch" src="https://download.fedoraproject.org/pub/fedora/linux/updates/7/i386/r/rubygem-shellany-0.0.1-1.el7.noarch.rpm">
          <filename>rubygem-shellany-0.0.1-1.el7.noarch.rpm</filename>
        </package>
      </collection>
    </pkglist>
  </update>
```
It may be useful to see the logs to get an idea of what has been changed on `updated date="2020-03-06 22:02:38"` for an update which has been pushed to stable 4 years ago...

**Comment by bakkc** [comment]
Here, same kind of messages:
Update notice FEDORA-EPEL-2019-936f369393 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
Update notice FEDORA-EPEL-2019-17d2b3507b (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2020-cd54f8f3d2 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-1e0469226c (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-f457d4367d (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2020-4b3752c0f5 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2020-ff1f3baa59 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-77e03a194b (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d6bedfa33e (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-8cbc520a97 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-10c651b6cf (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-0ad24584d8 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-3221ff1dea (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d49efff651 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-f84c232513 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-d50307dc61 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-b1b73eda91 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-906483cc2f (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-a6e87b96c1 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-b3b252ad49 (from epel-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-EPEL-2019-6c9bd69e8c (from epel-testing) is broken, or a bad duplicate, skipping.

**Comment by asangal** [comment]
On Stackoverflow https://stackoverflow.com/questions/62053813/yum-check-update-failed-for-ex-elasticsearch-update-notice-fedora-epel-from

**Comment by shawnz** [comment]
To be clear, would disabling epel-testing (but keeping epel) work around this issue?

This issue is actually causing our organization's automatic update script to fail completely (despite no updates for any epel packages).

**Comment by opoplawski** [comment]
It is a conflict between the epel and epel-testing repos.  But it doesn't cause us any problems updating systems - just outputting annoying messages.
```
# yum updateinfo --verbose
Loading "auto-update-debuginfo" plugin
Loading "versionlock" plugin
Config time: 0.022
Yum version: 3.4.3
rpmdb time: 0.000
Setting up Package Sacks
Found 18 installed debuginfo package(s)
Enabling epel-debuginfo: Extra Packages for Enterprise Linux 7 - x86_64 - Debug
Enabling epel-testing-debuginfo: Extra Packages for Enterprise Linux 7 - Testing - x86_64 - Debug
Enabling rpmfusion-free-updates-debuginfo: RPM Fusion for EL 7 - Free - Updates Debug
Enabling rpmfusion-free-updates-testing-debuginfo: RPM Fusion for EL 7 - Free - Test Updates Debug
Enabling ius-debuginfo: IUS for Enterprise Linux 7 - x86_64 - Debug
Enabling sl-extras-debuginfo: Scientific Linux Extras - debuginfo
Enabling sl-debuginfo: Scientific Linux Debuginfo
slack                                                                       | 1.0 kB  00:00:00     
teams                                                                       | 3.0 kB  00:00:00     
Reading version lock configuration
Excluding 1 update due to versionlock (use "yum versionlock status" to show it)
pkgsack time: 1.629
Duplicate of FEDORA-EPEL-2019-d50307dc61 differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:05'
=======
'2020-10-20 19:03:18'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-d50307dc61 (from epel-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the epel-testing repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
Duplicate of FEDORA-EPEL-2019-b3b252ad49 differs in some fields:
<<<<<<< epel-testing:updated                                                                       
'2020-10-21 15:40:07'                                                                              
=======                                                                                            
'2020-10-20 19:02:36'                                                                              
>>>>>>> epel:updated                                                                               
Update notice FEDORA-EPEL-2019-b3b252ad49 (from epel-testing) is broken, or a bad duplicate, skipping.                                                                                                
Duplicate of FEDORA-EPEL-2019-1e0469226c differs in some fields:                                   
<<<<<<< epel-testing:updated                                                                       
'2020-10-21 15:40:09'                                                                              
=======                                                                                            
'2020-10-20 19:03:08'                                                                              
>>>>>>> epel:updated                                                                               
Update notice FEDORA-EPEL-2019-1e0469226c (from epel-testing) is broken, or a bad duplicate, skipping.                                                                                                
Duplicate of FEDORA-EPEL-2019-0ad24584d8 differs in some fields:                                   
<<<<<<< epel-testing:updated                                                                       
'2020-10-21 15:40:10'                                                                              
=======                                                                                            
'2020-10-20 19:07:37'                                                                              
>>>>>>> epel:updated                                                                               
Update notice FEDORA-EPEL-2019-0ad24584d8 (from epel-testing) is broken, or a bad duplicate, skipping.                                                                                                
Duplicate of FEDORA-EPEL-2019-d49efff651 differs in some fields:                                   
<<<<<<< epel-testing:updated                                                                       
'2020-10-21 15:40:11'                                                                              
=======                                                                                            
'2020-10-20 18:57:46'                                                                              
>>>>>>> epel:updated                                                                               
Update notice FEDORA-EPEL-2019-d49efff651 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-f84c232513 differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:20'
=======
'2020-10-20 19:07:40'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-f84c232513 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-906483cc2f differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:27'
=======
'2020-10-20 19:04:49'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-906483cc2f (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-10c651b6cf differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:28'
=======
'2020-10-20 19:14:29'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-10c651b6cf (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-6c9bd69e8c differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:36'
=======
'2020-10-20 19:08:02'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-6c9bd69e8c (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-f457d4367d differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:41'
=======
'2020-10-20 19:04:39'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-f457d4367d (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-8cbc520a97 differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:42'
=======
'2020-10-20 18:57:51'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-8cbc520a97 (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-77e03a194b differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:47'
=======
'2020-10-20 19:02:44'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-77e03a194b (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-17d2b3507b differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:49'
=======
'2020-10-20 19:08:18'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-17d2b3507b (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-3221ff1dea differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:40:50'
=======
'2020-10-20 19:03:00'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-3221ff1dea (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-d6bedfa33e differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:41:06'
=======
'2020-10-20 19:08:13'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-d6bedfa33e (from epel-testing) is broken, or a bad duplicate, skipping.
Duplicate of FEDORA-EPEL-2019-a6e87b96c1 differs in some fields:
<<<<<<< epel-testing:updated
'2020-10-21 15:41:08'
=======
'2020-10-20 19:02:40'
>>>>>>> epel:updated
Update notice FEDORA-EPEL-2019-a6e87b96c1 (from epel-testing) is broken, or a bad duplicate, skipping.
updateinfo time: 7.383
Building updates object
up:Obs Init time: 0.859
up:simple updates time: 0.054
up:obs time: 0.008
up:condense time: 0.000
updates time: 4.675
updateinfo summary done
```

**Comment by shawnz** [comment]
You are right -- false alarm about the update script failing. There was actually another unrelated issue going on at the same time.

**Comment by dralley** [comment]
@jasontibbitts 

>There was a mention on IRC today of something which might be related. It seems that the metadata for updates is continuously updated, so that even old updates appear to be new:

For future reference I resolved that particular issue last year (ironically because of the same reason) https://github.com/fedora-infra/bodhi/issues/4189

I'm not sure if there's an issue in this thread not captured by the one above, but this *might* be resolved now.

**Comment by mattiaverga** [comment]
I think the culprit of this are the lines:
https://github.com/fedora-infra/bodhi/blob/85e6c48786276135a54ca12146629398c8b08f05/bodhi-server/bodhi/server/metadata.py#L215-L241

Whenever the updated_date, issued_date or any other update property is updated yum complaints about `broken or bad duplicate`. I've never seen reports coming for releases other than EPEL7, which is the only one using yum.

However, I'm not really expert on this topic and I don't know what's the best way to handle this.

**Comment by mattiaverga** [comment]
#4521 may be related, but that is EPEL8

**Comment by dralley** [comment]
I'm dealing with a very similar issue here, RHEL 7 (but it's going through Red Hat Satellite first): https://bugzilla.redhat.com/show_bug.cgi?id=2070692
