### ISSUE TITLE
The API endpoints should be able to take multiple values.

### ISSUE THREAD

**Issue by Sodalite** [fedora-infra/bodhi#2489]
It seems that the API endpoints do not accept multiple values. Thus, the API does not allow for refinement of searches.

For example : 
I would like to receive all comments, but I would like not to receive comment from the user *bodhi*. I can use `https://bodhi.fedoraproject.org/comments/?ignore_user=bodhi` and it works as expected. However, should I require all comments, but skip user *bodhi* and *fedpeg*, I cannot use this query `https://bodhi.fedoraproject.org/comments/?ignore_user=bodhi&ignore_user=fedpeg` nor this one `https://bodhi.fedoraproject.org/comments/?ignore_user=bodhi,fedpeg`.

There should be a way to do it.

**Comment by lruzicka** [comment]
It seems I was logged into my private profile, but I wanted to file the issue under this account. Thanks.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
This patch has been deployed to Bodhi's staging environment:

https://bodhi.stg.fedoraproject.org

Please test and let us know if you find issues!

**Comment by bowlofeggs** [comment]
This feature is now deployed to Bodhi's production instance.
