### ISSUE TITLE
Add buttons to text input fields that require enter

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#249]
Right now Bodhi 2 requires pressing enter in several text input fields before it accepts the input. Examples would be the "Candidate Builds" and "Related Bugs" fields in the new update submission form.

This is confusing because web forms usually don't need enter pressed in individual fields. An improvement would be to add a button, such as "Add" next to each text input field to make it visually obvious that one has to press enter / hit the button after typing in the text.

**Comment by ralphbean** [comment]
Yes!  This is a good proposal.
