### ISSUE TITLE
Feedback for bugs is not properly recorded

### ISSUE THREAD

**Issue by tyll** [fedora-infra/bodhi#2508]
I selected that the bug mentioned in https://bodhi.fedoraproject.org/updates/FEDORA-2018-1a22e606a6 was properly fixed but this is not shown in the comments or in he bug overview.

**Comment by ghost** [comment]
Same as #2456 . Fix will most probably be visible with the next release of Bodhi.

**Comment by bowlofeggs** [comment]
Yeah this should have been fixed in #2456, and that patch is currently deployed at https://bodhi.stg.fedoraproject.org if you want to try it out.
