### ISSUE TITLE
Submit comment/feedback button disappears when browser window is too small

### ISSUE THREAD

**Issue by tyll** [fedora-infra/bodhi#2509]
When the browser window is too small, the button to submit a comment disappears. Probably at about 640 pixel.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
The fix for this issue has been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/
