### ISSUE TITLE
add option to query according to update title

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#251]
If I know the update title, there seems to be no way to retrieve the corresponding update object. There is no `query(title=)` or similar. Can you please implement this?

From IRC:

```
<threebean> kparal: can you file an RFE to add a 'title' to the ListUpdatesSchema ?
```

And a follow-up:

```
<lmacken> kparal: like=title should work?
<lmacken> but we should have a proper title field
<kparal> lmacken: that works!
```

python-fedora 0.5.5

**Comment by kparal** [comment]
Adding it not just to update schema but also to the docstring would be appreciated ;-)

**Comment by ralphbean** [comment]
Yes, thanks!

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
Bodhi 3.11.0b5 has been deployed to staging:

https://bodhi.stg.fedoraproject.org

It is also available via Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release

**Comment by bowlofeggs** [comment]
This feature is now deployed to Bodhi's production instance.
