### ISSUE TITLE
The search bar does not work in staging

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2523]
I have so far been unable to reproduce the problem in the development environment, but I am unable to get the search bar to work in staging. It seems that the code in ```bodhi/server/static/js/search.js``` does not get executed on page load, but I do not know why yet.

**Comment by vismay-golwala** [comment]
@bowlofeggs : are you referring to the search bar [here](https://bodhi.stg.fedoraproject.org/)? That one's working for me.

**Comment by bowlofeggs** [comment]
@puiterwijk and I looked at this today while clipping along at 200 km/h. It seems that Bodhi has hardcoded the hostname ```hub.fedoraproject.org``` in its [live.js](https://github.com/fedora-infra/bodhi/blob/3.8.1/bodhi/server/static/js/live.js). The content security policy does not allow staging Bodhi to access production hub.fedoraproject.org. This happens during ```document.ready()```, which is also responsible for setting up the search bar.

To fix this, we believe that we should be able to make this a setting in Bodhi's configuration, and configure staging to use ```hub.stg.fedoraproject.org```.

**Comment by bowlofeggs** [comment]
I believe this issue has existed for a while and is not a regression in 3.9.0. Thus, I am downgrading it to high priority and will not consider it to be a release blocker.

**Comment by bowlofeggs** [comment]
The fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
