### ISSUE TITLE
Editing an update using CLI sets type to 'bugfix' if not provided

### ISSUE THREAD

**Issue by ghost** [fedora-infra/bodhi#2528]
While editing an update using CLI, if we don't provide the update type, it will modify it to ```bugfix```

So if we edit a ```security``` update, 

```bodhi updates edit --severity low moin-1.9.9-1.el6```

update's type will be changed to ```bugfix```. I think [this](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/__init__.py#L96) might be the reason, as the default is shared between create and edit update.

**Comment by bowlofeggs** [comment]
Was this not fixed by https://github.com/fedora-infra/bodhi/pull/2464 ? If not, was it caused by it? Is this a regression in 3.9, or was it present before?

**Comment by ghost** [comment]
@bowlofeggs: Neither. This bug is logically different from #2464. It was present before as there is a common default option in CLI for creating/editing update. I think a simple fix will be moving ```--type``` out of the common options [here](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/__init__.py#L96). But it will move it to either top or bottom in the ```--help``` section.

**Comment by bowlofeggs** [comment]
I have confirmed that this issue is present in Bodhi 3.8, so I will degrade its priority to high and will not consider it a 3.9 release blocker.

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This fix is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by bowlofeggs** [comment]
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.
