### ISSUE TITLE
No feedback in web ui after a new update submission fails

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#253]
I tried to submit a 83 package update in the web ui. It took a while to process it after clicking "Submit". I got bored after staring at the screen after a few minutes and looked elsewhere. Meanwhile, it apparently returned (the spinning image had stopped and "Submit" button was active again), but there was no indication what had happened.

It may have displayed an error message while I was looking away, but it had disappeared when I looked back. Error messages shouldn't automatically disappear without the user dismissing them.

**Comment by ralphbean** [comment]
Acknowledged!
