### ISSUE TITLE
BuildrootOverrides should not be allowed if the test gating status is failed

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2537]
We should add a check that disallows creating BROs if the test gating status is failed.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This feature is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by bowlofeggs** [comment]
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.

**Comment by AdamWill** [comment]
So, um, if we [need a buildroot override to fix the failing tests](https://bodhi.fedoraproject.org/updates/FEDORA-2022-092636385d), where do we buy a chicken and an egg?
