### ISSUE TITLE
Each failed update submission is shown as "null" in the web UI

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#254]
See the screenshot where it shows "null" 21 minutes ago.

![bodhi-null](https://cloud.githubusercontent.com/assets/498858/9391380/b957d394-4776-11e5-85fb-9c8a20025540.png)

**Comment by ralphbean** [comment]
So, that is **actually** a message that represents @nirik requesting that the backend masher start the mash process and the code to fix that UI bit for it was written in fedora-infra/fedmsg_meta_fedora_infrastructure#308, it just hasn't been deployed yet.  Soon!  Closing as "done in dev, will be live soon."
