### ISSUE TITLE
Add rube tests for bodhi2

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#255]
https://github.com/fedora-infra/rube/blob/develop/rube.fedora/rube/fedora/test_bodhi2.py

**Comment by ralphbean** [comment]
Ha!  Yes!

**Comment by ryanlerch** [comment]
Is this something that we should still look into? Is rube something that is still in use?

**Comment by ralphbean** [comment]
I don't think anyone is using it currently.

The automated job (that no one is checking) runs here:  https://jenkins.fedorainfracloud.org/job/fedora-rube/
