### ISSUE TITLE
Bodhi no longer displays test results in production

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2554]
#2393 is now deployed to production. I've spot checked a few updates and they do not seem to display test results anymore:

https://bodhi.fedoraproject.org/updates/FEDORA-2018-01a9c96b51
https://bodhi.fedoraproject.org/updates/FEDORA-2018-23703f460d
https://bodhi.fedoraproject.org/updates/FEDORA-2018-60fdb8b0aa

**Comment by bowlofeggs** [comment]
CC @ralphbean

**Comment by bowlofeggs** [comment]
I have filed https://pagure.io/greenwave/issue/287 to track this problem, which appears to be Greenwave not handing test results back to Bodhi:

```
$ curl 'https://greenwave-web-greenwave.app.os.fedoraproject.org/api/v1.0/decision' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/json' -H 'Origin: https://bodhi.fedoraproject.org' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --data '{"product_version":"fedora-28","decision_context":"bodhi_update_push_stable","subject":[{"item":"bodhi-3.9.0-1.fc28","type":"koji_build"},{"original_spec_nvr":"bodhi-3.9.0-1.fc28"},{"item":"FEDORA-2018-01a9c96b51","type":"bodhi_update"}],"verbose":true}'
{
  "applicable_policies": [
    "taskotron_release_critical_tasks_for_stable", 
    "atomic_ci_pipeline_results_stable"
  ], 
  "policies_satisfied": true, 
  "results": [], 
  "satisfied_requirements": [], 
  "summary": "no tests are required", 
  "unsatisfied_requirements": [], 
  "waivers": []
}
```

**Comment by bowlofeggs** [comment]
Here is a screenshot of the issue:

![screenshot from 2018-08-27 16-22-41](https://user-images.githubusercontent.com/354506/44683861-7512c680-aa15-11e8-930d-10bbf106f105.png)

**Comment by ralphbean** [comment]
See updates and conversation in [the greenwave issue](https://pagure.io/greenwave/issue/287).

**Comment by ralphbean** [comment]
Can this be closed @bowlofeggs?

**Comment by bowlofeggs** [comment]
Yes, this seems to be resolved in production now. Thanks!
