### ISSUE TITLE
Bodhi should not allow retired releases to be composed

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2555]
Today composes for F26 (currently EOL) were accidentally run, which failed and required manual clean up. Bodhi should not allow composing retired releases.

**Comment by sebwoj** [comment]
@bowlofeggs Since github has an issue closing "Bodhi issues", we should do it manualy ;/

**Comment by bowlofeggs** [comment]
@sebwoj, yeah, I'm not sure what is going on with that. Must be a bug, because it's documented here: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
