### ISSUE TITLE
Errors in testing in Vagrant environment

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2568]
Running `btest` on devel branch in a Vagrant environment fails while building docs (also `bdocs` fails):

    /home/vagrant/bodhi/docs/developer/docblocks/bodhi.server.models.rst:10:failed to import get_nvr

It seems that after recent changes the `bodhi.server.models.rst` file was not updated. I think there are some functions that need to be wiped out: get_nvr, greenwave_api_post, packagename_from_nvr, waiverdb_api_post

**Comment by bowlofeggs** [comment]
Hi @mattiaverga!

I am unable to reproduce this issue. Does it still happen for you?

**Comment by mattiaverga** [comment]
@bowlofeggs I had some old files still present locally, a cleaning with `git clean -xd` solved the problem. Sorry for the noise.
