### ISSUE TITLE
Document & link to the RSS/JSON/HTML features of each service

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#259]
We have a super powerful architecture now that allows for RSS/Atom, JSON, and HTML views of updates, releases, users, etc. We need to document this and we should link to it somewhere.

**Comment by lmacken** [comment]
Bodhi1 also linked to a bunch of documentation, like the Updates Policy. We might want to setup a separate menu item for docs?

**Comment by ryanlerch** [comment]
WE now have API docs, and the Docs are linked to in the footer on Bodhi.
