### ISSUE TITLE
allow querying for buildroot overrides by package

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#261]
It would be cool if this worked:  https://bodhi.fedoraproject.org/overrides/?package=fedmsg

**Comment by pnemade** [comment]
hmm I am not sure why above link is also showing compat-guile and fedora-python packages. 
I have reported similar issue #208 to show list/search buildroot overrides.
Another thing in above URL, its not showing till how long package is going to be in buildroot override. I need to click on specific package to know its expiration date.

**Comment by ralphbean** [comment]
> I am not sure why above link is also showing compat-guile and fedora-python packages.

Oh, that's because the feature hasn't been implemented yet.

**Comment by ralphbean** [comment]
Oh, wait.  You can already do this with the following URL:  https://bodhi.fedoraproject.org/overrides/?packages=fedmsg  *note the 's' on the end of packages*

**Comment by ralphbean** [comment]
.. and it seems you always could, since 00056fbd.
