### ISSUE TITLE
Bugs list in 'new update' page

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2622]
The 'Related Bugs' list in the 'New Update' page doesn't work correctly, in my opinion.
For example, if you enter 'bodhi' in Packages, the bug list will show bodhi bugs; then if you change Packages to something else, the bug list will show bugs for the new package + bugs for the bodhi package; moreover, if you re-enter bodhi in Packages, the bug list now shows bodhi bugs twice.

I think the 'New Update' page could work better by changing how 'Packages' field works. Now it lets you enter only one package at a time, but there are many cases where you want to deploy multiple packages in the same update. So it should be changed to accept multiple packages, for example using a script like this:
http://sliptree.github.io/bootstrap-tokenfield/

![mockup](https://user-images.githubusercontent.com/17218209/46133825-b8916800-c241-11e8-8f5d-70e1ec325c07.png)

This way the 'Candidate Builds' and 'Related Bugs' lists can be populated in a more consistent way: instead of append bugs to the end of the list, the list can completely be rebuilt when the package list is changed.
Sadly, I have poor experience in javascript and I am unable to write a pull request to modify the current behavior...

**Comment by mattiaverga** [comment]
I made a few progress in https://github.com/mattiaverga/bodhi/tree/new_update if someone wants to take a look at it.
There are some aesthetic glitches and I need to make it remember flagged elements when the lists are rebuilt, but it seems to work for the most part. If I ever manage to reach the point of making a pull request, it will need a full review from an experienced javascript programmer.

**Comment by ryanlerch** [comment]
#3453 overhauled the new update form, to make adding bugs a lot more intuitive. Feel free to re-open this one if you don't agree.
