### ISSUE TITLE
Bodhi metrics for EPEL are missing

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#263]
https://bodhi.fedoraproject.org/metrics only displays the Bodhi metrics for Fedora releases, not for EPEL. Can we have them back? Additionally, the "old" metrics were more verbose (package most often being updated, packager with the most updates, etc.).

**Comment by ralphbean** [comment]
Ah, check out this page for more info:  https://bodhi.fedoraproject.org/releases/

We haven't yet figured out how/where to promote that stuff in the UI yet.

**Comment by robert-scheck** [comment]
I am sorry, I can't see how the URL would provide the same metrics (also with a timeframe) and some numbers, packages and packagers. https://bodhi.fedoraproject.org/releases/EL-5 doesn't really look usable regarding the diagram here (Firefox 38 ESR).
