### ISSUE TITLE
Drop support for Fedora Tagger

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2657]
Bodhi has some support to integrate data from Fedora Tagger into its generated repositories. Fedora Tagger has been retired, so we can drop support in the next major Bodhi release.

**Comment by puiterwijk** [comment]
I believe that all the Tagger code was already removed as part of 33d1e733d88bc891e00bf9f0e09d471360253ab1 ?

**Comment by bowlofeggs** [comment]
Ha I'd forgotten about that. Thanks for remembering!
