### ISSUE TITLE
bodhi does not show a bug to close

### ISSUE THREAD

**Issue by NiceandGently** [fedora-infra/bodhi#266]
Bodhi does not show a bug to close!
Please add a button to add bugs manualy ;)
update:
https://bodhi.fedoraproject.org/updates/marco-1.10.2-1.fc23
https://bodhi.fedoraproject.org/updates/marco-1.10.2-1.fc22
bug which isn't selectable:
https://bugzilla.redhat.com/show_bug.cgi?id=1226530

**Comment by ralphbean** [comment]
It's not obvious, but you can type in the bugzilla number when submitting a form and press **enter** and it will be added to the selectable list.  Can you confirm?

I'll be tracking the progress of making those text boxes more obvious in #249.

**Comment by NiceandGently** [comment]
Sorry, my old 4 eyes, i didn't saw that.
But adding rhbz1226530 to https://bodhi.fedoraproject.org/updates/marco-1.10.2-1.fc22 does not have any effect in resulting bodhi page and bugzilla report :-/

**Comment by NiceandGently** [comment]
sigh,
trying again and now it works...but this isn't vwery maintainer friendly.
Up to you to close this report or not ;)

**Comment by ralphbean** [comment]
@NiceandGently, thanks much for reporting this.  A commit earlier this evening ( c774e747 ) went out that will add a button to those input fields which should hopefully help make it more obvious what maintainers need to do.  We're working as hard as we can to deal with all the feedback we're getting.  Thanks for being patient!

**Comment by NiceandGently** [comment]
Thank you for your work in the last days!
