### ISSUE TITLE
fedora-easy-karma fails with limit error

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#267]
With python-fedora-0.5.5-1.fc22.noarch installed, running fedora-easy-karma gives: 

$ fedora-easy-karma 
Getting list of installed packages...
Waiting for Bodhi for a list of packages in updates-testing (F22)...
Cannot query Bodhi: 1000 is greater than maximum value 100

perhaps allow queries of 1000 or we could ask fedora-easy-karma to adjust to 100 I guess.

**Comment by nirik** [comment]
If I manually edit fedora-easy-karma and set it to 100, it gets past that to a new error: 

Waiting for Bodhi for a list of packages in updates-testing (F22)...
Traceback (most recent call last):
  File "/usr/bin/fedora-easy-karma", line 651, in <module>
    FedoraEasyKarma()
  File "/usr/bin/fedora-easy-karma", line 466, in __init__
    self.already_commented(update, self.options.fas_username):
  File "/usr/bin/fedora-easy-karma", line 576, in already_commented
    comment["author"].split(" ")[0] == user:
KeyError: 'author'

**Comment by JamesWrigley** [comment]
This also happens for me with fedora-easy-karma-0-0.24.20150508gitc8e437c0.fc22.noarch and python-fedora-0.5.5-1.fc22.noarch.

**Comment by tyll** [comment]
IMHO the 100 updates limit is too low, at least for f-e-k, this means that 6 slow request are required to get a list of all testing updates which took 4 minutes when I tested this. Since the f-e-k queries are very common, can Bodhi maybe cache them and for example just provide it at a static location to make this faster?

**Comment by lmacken** [comment]
It looks like this issue has been fixed.
