### ISSUE TITLE
Search URLs are missing since Bodhi 2

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#269]
I am missing search URLs such as e.g. https://admin.fedoraproject.org/updates/search/phpMyAdmin-4.4.13.1 - which simply listed all matching packages (independent of the Fedora/EPEL branch). Using such old URLs leads also to 404 not found. Could they get re-added, please?

**Comment by ralphbean** [comment]
Try this:  https://bodhi.fedoraproject.org/updates/?like=phpMyAdmin-4.4.13.1

We can add a redirect at the proxy level for the old url (MAYBE).

**Comment by robert-scheck** [comment]
Ah, that URL works (a rewrite to keep the old URLs intact would be very nice and helpful through).

**Comment by ralphbean** [comment]
Fixed in [this ansible commit](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=270aad97c46eaee7fad1508b03fd7735370f0ecc) which is being [rolled out via the proxies.yml playbook](https://apps.fedoraproject.org/datagrepper/raw?category=ansible).
