### ISSUE TITLE
Return the test cases in the update json

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#270]
The test cases are associated with each package, so we should iterate over each package for each build and throw the test cases into the json results as well.

This was originally filed accidentally in the wrong place as fedora-infra/fedmsg_meta_fedora_infrastructure#313.

**Comment by tflink** [comment]
Just to make sure I'm understanding properly - is this supposed to list the test cases (and the URLs to those test cases) which bodhi knows about for a given update?

**Comment by tflink** [comment]
The data I'm seeing is: testcase name (no url), comments which gave feedback using the testcase in question and what appears to be the packages known by bodhi to be associated with this testcase.

Won't this data become huge with time?

**Comment by ralphbean** [comment]
Yeah, the comments will grow over time.  Filing a separate issue for it.
