### ISSUE TITLE
We should drop anonymous comments

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2700]
SSIA

**Comment by ryanlerch** [comment]
Anon comments are the only thing that uses the CAPTCHA stuff too, right? so that can all be dropped as well.

**Comment by bowlofeggs** [comment]
On Sun, 2018-11-04 at 20:58 -0800, Ryan Lerch wrote:
> Anon comments are the only thing that uses the CAPTCHA stuff too,
> right? so that can all be dropped as well.

Indeed!

**Comment by morxa** [comment]
The captcha is not working anyway:
```
Captcha : No captcha session cipher match (replay).
```

![screenshot from 2018-11-23 13-44-15](https://user-images.githubusercontent.com/4573064/48946644-49c14a00-ef26-11e8-9644-130ccf3267e9.png)

I was just going to report this, but I guess I can save the effort?

**Comment by bowlofeggs** [comment]
@morxa I think that is related to Bodhi switching to Python 3 and have filed https://github.com/fedora-infra/bodhi/issues/2786 about it. Thanks for letting me know!

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
