### ISSUE TITLE
Comments list not refreshed after posting feedback

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2706]
Sometimes the comment list on the update page doesn't get refreshed and the form doesn't get polished after posting comment/feedback, making user post his comment twice.

I saw this behavior twice, the first time on production and I've reproduced once on stage. I think another user had this issue, because in [this](https://bodhi.fedoraproject.org/updates/FEDORA-2018-506e97bb9b) update he posted feedback twice (and that's the same update where I first seen the issue).

On staging I could see the problem on my first try (https://bodhi.stg.fedoraproject.org/updates/FEDORA-2018-a2754759c6); here the comment was posted, but I had to manually refresh the page before seeing it.
However I couldn't reproduce this behavior on successive tries, also on different updates.

**Comment by rathann** [comment]
This is happening all the time for me now (bodhi-4.0.2 on bodhi-web-77-vpspf), which often leads me to add duplicate comments, for example:  https://bodhi.fedoraproject.org/updates/FEDORA-2019-8d98e2633a .

**Comment by mattiaverga** [comment]
This should be fixed with #3539
