### ISSUE TITLE
Submitting large updates takes too long

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#272]
I worked on submitting a 83 package GNOME update today and Bodhi took a long long time to process it. threebean asked me to file it to see if it's possible to optimize it.

The experience for me was like this:

1) Submitted the update. 15 minutes later the web UI (or a proxy server?) timed out and returned without any errors.

2) I tried to click Submit again twice after the time out. It timed out similarly each time, after 15 or so minutes.

3) ~1.5 hours after first clicking Submit, it finally posted bugzilla comments and tagged the packages.

**Comment by cicku** [comment]
TBH, I doubt that the model originated from Bodhi1 has flaw.

Bodhi2 doesn't enhance that, but even worser. In fact, Bodhi should immediately receive new update requests and submit them to cache-like queue(with return like `pending` in Bodhi1 but not the same meaning. It means updates received, and they are being handled), and notifies users when updates are submitted exactly to testing channel.

**Comment by lmacken** [comment]
I have a feeling a lot of this time is spent querying the wiki for test cases. More profiling is needed, but we do plan on offloading a lot of the slow external API calls to the wiki, bugzilla, etc to a fedmsg consumer on the backend. See #314 for more info.

**Comment by lmacken** [comment]
Yep, as I suspected, the wiki is slow.

[Thu Aug 27 19:03:29.658288 2015] [:error] [pid 11744] 2015-08-27 19:03:29,658 INFO  [bodhi][Dummy-3] Querying the wiki for test cases
[Thu Aug 27 19:05:37.587026 2015] [:error] [pid 11744] 2015-08-27 19:05:37,586 INFO  [bodhi][Dummy-3] Done querying for test cases


We plan on moving this code to a backend process to speed this up (issue
#314)

**Comment by cicku** [comment]
OK. 

So I think maybe it's time to use separate instance to hold test cases. Traversing the wiki consumes too much time as we can see. I don't see reason test cases should be put on wiki because in many years lots of users just treat Fedora wiki as a place for testing instead of diffusing knowledge.

**Comment by lmacken** [comment]
Wiki querying has been moved to a seperate fedmsg consumer, which will drastically speed things up.

**Comment by lmacken** [comment]
I believe @kalev said he has had pretty good experiences with large updates recently.
