### ISSUE TITLE
Bad update info today August 20-2015

### ISSUE THREAD

**Issue by frankzen** [fedora-infra/bodhi#275]
Update notice FEDORA-2015-13197 (from updates-testing) is broken, or
a bad duplicate, skipping.
You should report this problem to the owner of the updates-testing 
repository.
Update notice FEDORA-2015-12912 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-12821 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-12934 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-11572 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-12955 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-13252 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-13254 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-13257 (from updates-testing) is broken, or
a bad duplicate, skipping.
Update notice FEDORA-2015-13229 (from updates-testing) is broken, or
a bad duplicate, skipping.

**Comment by lmacken** [comment]
It doesn't look like these are duplicate entries... but this is the first time we are using createrepo_c to generate the updateinfo xml, so I'm wondering if yum can't handle the new fields.

Here is the difference between the bodhi1 xml and bodhi2s for the first update:

```diff
--- good.xml    2015-08-20 21:43:45.684177825 +0000
+++ bad.xml     2015-08-20 21:45:56.794119930 +0000
@@ -1,25 +1,26 @@
 <?xml version="1.0"?>
-<update from="updates@fedoraproject.org" status="testing" type="enhancement" version="1.4">
+<update from="updates@fedoraproject.org" status="stable" type="enhancement" version="2.0">
   <id>FEDORA-2015-13197</id>
   <title>python-copr-1.58-1.fc21</title>
+  <issued date="2015-08-20 15:34:03"/>
+  <rights>Copyright (C) 2015 Red Hat, Inc. and others.</rights>
   <release>Fedora 21</release>
-  <issued date="2015-08-12 04:43:09"/>
-  <reboot_suggested/>
-  <references/>
+  <summary>python-copr-1.58-1.fc21 enhancement update</summary>
   <description>allow submitting SRPM directly from your workstation</description>
+  <references/>
   <pkglist>
     <collection short="F21">
       <name>Fedora 21</name>
-      <package arch="noarch" epoch="0" name="python-copr" release="1.fc21" src="http://download.fedoraproject.org/pub/fedora/linux/updates/testing/21/i386/python-copr-1.58-1.fc21.noarch.rpm" version="1.58">
+      <package name="python-copr" version="1.58" relase="1.fc21" epoch="0" arch="noarch" src="http://download.fedoraproject.org/pub/fedora/linux/updates/21/i386/python-copr-1.58-1.fc21.noarch.rpm">
         <filename>python-copr-1.58-1.fc21.noarch.rpm</filename>
       </package>
-      <package arch="noarch" epoch="0" name="python3-copr" release="1.fc21" src="http://download.fedoraproject.org/pub/fedora/linux/updates/testing/21/i386/python3-copr-1.58-1.fc21.noarch.rpm" version="1.58">
+      <package name="python3-copr" version="1.58" relase="1.fc21" epoch="0" arch="noarch" src="http://download.fedoraproject.org/pub/fedora/linux/updates/21/i386/python3-copr-1.58-1.fc21.noarch.rpm">
         <filename>python3-copr-1.58-1.fc21.noarch.rpm</filename>
       </package>
-      <package arch="noarch" epoch="0" name="python-copr-doc" release="1.fc21" src="http://download.fedoraproject.org/pub/fedora/linux/updates/testing/21/i386/python-copr-doc-1.58-1.fc21.noarch.rpm" version="1.58">
+      <package name="python-copr-doc" version="1.58" relase="1.fc21" epoch="0" arch="noarch" src="http://download.fedoraproject.org/pub/fedora/linux/updates/21/i386/python-copr-doc-1.58-1.fc21.noarch.rpm">
         <filename>python-copr-doc-1.58-1.fc21.noarch.rpm</filename>
       </package>
-      <package arch="src" epoch="0" name="python-copr" release="1.fc21" src="http://download.fedoraproject.org/pub/fedora/linux/updates/testing/21/SRPMS/python-copr-1.58-1.fc21.src.rpm" version="1.58">
+      <package name="python-copr" version="1.58" relase="1.fc21" epoch="0" arch="src" src="http://download.fedoraproject.org/pub/fedora/linux/updates/21/SRPMS/python-copr-1.58-1.fc21.src.rpm">
         <filename>python-copr-1.58-1.fc21.src.rpm</filename>
       </package>
     </collection>
```

**Comment by lmacken** [comment]
`relase`... typo...

**Comment by lmacken** [comment]
PR sent up to createrepo_c https://github.com/Tojaj/createrepo_c/pull/34

**Comment by lmacken** [comment]
I deployed a patched createrepo_c to production last night, so hopefully the f22-updates push that went out does not have this issue.

**Comment by lmacken** [comment]
This issue should hopefully be resolved. Please re-open this ticket if you notice these warnings again. Thanks!

**Comment by mccfrank** [comment]
They are back. August 26-2015 
This is Fedora 21



Update notice FEDORA-2015-12705 (from updates-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the updates-testing repository.
Update notice FEDORA-2015-10652 (from updates-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-2015-13518 (from updates-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-2015-13424 (from updates-testing) is broken, or a bad duplicate, skipping.
Update notice FEDORA-2015-12717 (from updates-testing) is broken, or a bad duplicate, skipping.
[root@localhost frankzen] #

**Comment by lmacken** [comment]
So the first one `FEDORA-2015-12705` is as follows:
```xml
  <update from="updates@fedoraproject.org" status="stable" type="enhancement" version="2.0">
    <id>FEDORA-2015-12705</id>
    <title>perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21</title>
    <issued date="2015-08-24 22:25:54"/>
    <rights>Copyright (C) 2015 Red Hat, Inc. and others.</rights>
    <release>Fedora 21</release>
    <summary>perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21 enhancement update</summary>
    <description>This release improves documentation.</description>
    <references>
      <reference href="https://bugzilla.redhat.com/show_bug.cgi?id=1249360" id="1249360" type="bugzilla" title="perl-Syntax-Highlight-Engine-Kate-0.10 is available"/>
    </references>
    <pkglist>
      <collection short="F21">
        <name>Fedora 21</name>
        <package name="perl-Syntax-Highlight-Engine-Kate" version="0.10" release="1.fc21" epoch="0" arch="noarch" src="https://download.fedoraproject.org/pub/fedora/linux/updates/21/i386/p/perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21.noarch.rpm">
          <filename>perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21.noarch.rpm</filename>
        </package>
        <package name="perl-Syntax-Highlight-Engine-Kate" version="0.10" release="1.fc21" epoch="0" arch="src" src="https://download.fedoraproject.org/pub/fedora/linux/updates/21/SRPMS/p/perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21.src.rpm">
          <filename>perl-Syntax-Highlight-Engine-Kate-0.10-1.fc21.src.rpm</filename>
        </package>
      </collection>
    </pkglist>
  </update>

```

**Comment by lmacken** [comment]
@mccfrank What command are you running to generate those warnings? Can you try `yum clean all` and see if that resolves it?

**Comment by lmacken** [comment]
I'm unable to reproduce this on F21 with `yum --enablerepo=updates-testing --security update`

**Comment by mccfrank** [comment]
On 27/08/15 02:22 PM, Luke Macken wrote:
>
> @mccfrank <https://github.com/mccfrank> What command are you running 
> to generate those warnings? Can you try |yum clean all| and see if 
> that resolves it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fedora-infra/bodhi/issues/275#issuecomment-135513511>.
>


    Yum clean all followed by yum check-update followed by yum update.

**Comment by mccfrank** [comment]
On 27/08/15 02:29 PM, Luke Macken wrote:
>
> I'm unable to reproduce this on F21 with |yum 
> --enablerepo=updates-testing --security update|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fedora-infra/bodhi/issues/275#issuecomment-135515063>.
>


    Interesting...but I never ran that command.
I always do  yum clean all---yum check-update...yum update

Until this last " incident" never had a problem.

**Comment by lmacken** [comment]
I changed all of the mirrorlists in /etc/yum.repos.d/* to baseurl=https://dl.fedoraproject.org/.. and I'm unable to reproduce this issue.

**Comment by mccfrank** [comment]
On 27/08/15 02:50 PM, Luke Macken wrote:
>
> I changed all of the mirrorlists in /etc/yum.repos.d/* to 
> baseurl=https://dl.fedoraproject.org/.. and I'm unable to reproduce 
> this issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fedora-infra/bodhi/issues/275#issuecomment-135520678>.
>


    We'll I don't know what to say at this point. I guess you can close 
the ticket
again. We'll see what happens.

**Comment by lmacken** [comment]
I think this issue has been resolved. If you still encounter any yum update notice warnings, please re-open this ticket.

**Comment by opoplawski** [comment]
I'm seeing these again:
~~~~~
Update notice FEDORA-2015-15862 (from updates-testing) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the updates-testing repository.
Update notice FEDORA-2015-16403 (from updates-testing) is broken, or a bad duplicate, skipping.
~~~~~

and lots more.

**Comment by toracat** [comment]
Perhaps related to the bug reported against RHEL:

https://bugzilla.redhat.com/show_bug.cgi?id=1194915
