### ISSUE TITLE
New bodhi updates are "Logout required" by default

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#2778]
Go to https://bodhi.fedoraproject.org/updates/new

The *Suggestion* now defaults to *logout*.

Is this new policy or a mistake? I see some logout updates in bodhi where it is most likely not needed.

I've filled this as [an infra issue](https://pagure.io/fedora-infrastructure/issue/7396), got redirected here.

**Comment by hroncok** [comment]
https://github.com/fedora-infra/bodhi/pull/2777

**Comment by bowlofeggs** [comment]
It turns out that Python 3 sorts these entries differently than Python 2 does. Running Bodhi with ```pserve-2``` does not show this issue, but running it with ```pserve-3``` does.

**Comment by hroncok** [comment]
Don't know what entries are there, but if it has something to do with dict, Python 3.6+ maintains insertion order (as language standard in 3.7+).

**Comment by bowlofeggs** [comment]
@hroncok Oh that's an interesting possibility. I'll look into that. It turns out that #2777 did not fix this issue, so I'm going to see if I can figure it out now.

**Comment by bowlofeggs** [comment]
The fix for this issue is now released with Bodhi 3.11.1 and deployed to Fedora's production instance.
