### ISSUE TITLE
Build.ci_url seems to be unused

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2782]
Build.ci_url seems to be unused.

**Comment by bowlofeggs** [comment]
This attribute is removed in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
