### ISSUE TITLE
/updates/? returns too much data

### ISSUE THREAD

**Issue by zulu7** [fedora-infra/bodhi#279]
I want to continuously consume information about the latest stable updates for all Fedora releases in an automated way.

It's my impression that some updates have status "testing", potentially for a long time, before they transition to status "stable".

When I
```
GET https://bodhi.fedoraproject.org/updates/?release=f21
Accept: application/json
```
the result is one page of information about updates. When I max out the page size (rows_per_page=100), the result is 96 pages of updates. Since these are sorted by date_submitted (not updated when an update moves from "testing" to "stable"), as I continuously check for new updates, I would need to check every single page to see if any update has changed state.

If I instead consume 
```
https://bodhi.fedoraproject.org/updates/?release=f21&status=stable
```
since items are sorted by date_submitted, I would again have to check every page to see if new updates are available and which ones they are (now only 84 pages).

Other users might want to do something similar, filtering on different attributes.

Since I want to consume this information continuously (say check for new updates every couple hours) and not put undue load on your web servers / databases, I would like to make the following request:

I suggest creating a new route /updates/ids that lists only the updateid of updates matching request conditions. For this endpoint, the rows_per_page could safely be much greater, say 1000 or 10000.

```
https://bodhi.fedoraproject.org/updates/ids?release=f21&status=stable
```
This would return something like:
```javascript
{
    "rows_per_page": 1000,
    "total": 9568,
    "pages": 10,
    "updates": [
        "FEDORA-2015-13080",
        "FEDORA-2015-13129",
        ...
    ]
}
```

This is a fairly simple addition, and would make it much easier for users to consume information about updates on an ongoing basis.

Let me know if you think this is a good idea. I'm happy to submit a pull request.

**Comment by ralphbean** [comment]
This is not a bad idea, but have you considered using [fedmsg](http://fedmsg.com) to receive events about updates being pushed to stable?

It even has its own history of events where you could see just [the events where updates are pushed to stable](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.complete.stable).
