### ISSUE TITLE
Bug status not updated

### ISSUE THREAD

**Issue by psss** [fedora-infra/bodhi#2790]
There are three bugs attached to the following update:

* https://bodhi.fedoraproject.org/updates/FEDORA-2018-a028b681ac

Two of them have been successfully updated and their status modified, the third one has not received any update and in the list of bugs just shows running circles...

**Comment by mattiaverga** [comment]
Bug #1635156 is a private bug. That means that Bodhi cannot post any comment neither change its status.

There's already a PR #2714 that will prevent private bugs to be added to an update, but it will (probably) come into a future version. I'm also working on a PR that will warn a user when they add a prvate bug in web UI, but I'm blocked by a problem with bugzilla data retrieval https://bugzilla.redhat.com/show_bug.cgi?id=1641232

**Comment by bowlofeggs** [comment]
Yeah it's that Bodhi doesn't handle private BZs gracefully. That is tracked in https://github.com/fedora-infra/bodhi/issues/344, so let's close this one.

**Comment by psss** [comment]
Ah, I see. Thanks for clarification. Warning about private bugs would be useful.
