### ISSUE TITLE
Selecting multiple packages in new update changes builds to numbers, or not numbers

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/bodhi#2791]
With bodhi 3.11.0, if you make an update composed of builds from several packages *and* you use the "packages" field to search for candidate builds, the candidate build you select is replaced with a number (the build's database primary key?) when you change the packages field to find the next candidate build.

To reproduce:

1. Enter "kernel" into the "Packages" field.
2. Select a candidate build, such at "kernel-4.19.5-300.fc29"
3. Enter "kernel-headers" into the "Packages" field.
4. Candidate Builds should now be populated with kernel-headers builds, but the "kernel-4.19.5-300.fc29" candidate build is now "1167347"
5. Select a kernel-headers build.
6. Search for "kernel-tools" in the "Packages" field.
7. Now kernel-4.19.5-300.fc29 (which became  "1167347") shows up in the list as "NaN"

**Comment by mattiaverga** [comment]
Yeah, I think I've messed up NVRs and build-ids in the javascript code when building the list of existing checked builds... I'm currently travelling and trying to debug by smartphone is not the best, I can take a look into this in the next weekend. (If someone else doesn't precede me)

**Comment by bowlofeggs** [comment]
The fix for this has been deployed to Fedora's production instance.
