### ISSUE TITLE
The integration tests should cover all supported releases

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2824]
We should expand the coverage on the integration tests so they cover all supported releases (Fedora 28, Rawhide, and pip installed dependencies).

**Comment by abompard** [comment]
Fixed by PR #2837 .

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
