### ISSUE TITLE
No candidates available in devel environment

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#2828]
When running a devel environment in Vagrant, no candidate builds are available for creating an upgrade and no candidates are showed in `/latest_candidates` page.

If I'm correct, the data which should provide those candidates is in `bodhi/server/buildsys.py`. 
https://github.com/fedora-infra/bodhi/blob/ccec39aa26465581a955a3de4c14190455fa2dbd/bodhi/server/buildsys.py#L429-L446
I think the problem is that `DevBuildsys.__tagged__` is empty, so no build is returned.

**Comment by bowlofeggs** [comment]
Yeah that would be a nice thing to add. FYI, I think you can just type in some build NVRs into the candidate builds box as a workaround.
