### ISSUE TITLE
Can't push updates to stable

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/bodhi#283]
I have been notified that three updates are able to be pushed to stable:

https://bodhi.fedoraproject.org/updates/osmpbf-1.3.3-7.20150712git17fd0cc.fc23
https://bodhi.fedoraproject.org/updates/nodejs-mapnik-reference-8.2.0-1.fc23
https://bodhi.fedoraproject.org/updates/libgxps-0.2.3.1-1.fc23

None of those updates is showing any button to push to stable however, and the command line client fails with a 404 when I try:

```
bericote [~] % bodhi -R stable osmpbf-1.3.3-7.20150712git17fd0cc.fc23
Password for tomh: 
ServerError(https://admin.fedoraproject.org/updates/request, 404, Not Found)
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 268, in main
    data = bodhi.request(update=args[0], request=opts.request)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 159, in request
    'action': request,
  File "/usr/lib/python2.7/site-packages/fedora/client/baseclient.py", line 379, in send_request
    auth_params=auth_params, retries=retries, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/fedora/client/proxyclient.py", line 505, in send_request
    raise ServerError(url, http_status, msg)
ServerError: ServerError(https://admin.fedoraproject.org/updates/request, 404, Not Found)
```

**Comment by tomhughes** [comment]
So I have now updated to the new python-fedora from testing and I no longer got a 404 from the command line, but instead I get:

```
bericote [~] % bodhi -R stable osmpbf-1.3.3-7.20150712git17fd0cc.fc23
Password for tomh: 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 532, in <module>
    main()
  File "/usr/bin/bodhi", line 268, in main
    data = bodhi.request(update=args[0], request=opts.request)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 107, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: This update has not yet met the minimum testing requirements defined in the <a href="https://fedoraproject.org/wiki/Package_update_acceptance_criteria">Package Update Acceptance Criteria</a>
```

Which probably also explains why there is no button, but doesn't explain why I got an email saying I could now push it.

In any case it's wrong, as the push time for testing was about 3 days and 7 hours ago so the 4 days for F23 has expired.

**Comment by cicku** [comment]
They mishandle the import date and update date, so you might wait until it's in new bodhi for 3 days or whatever

**Comment by lmacken** [comment]
This issue has been resolved. Please re-open if you still experience this problem.
