### ISSUE TITLE
Updates for rawhide containers

### ISSUE THREAD

**Issue by omron93** [fedora-infra/bodhi#2830]
Hi,
could it be possible to enable update for rawhide containers? Or for Fedora release N+1, currently F30...

Currently there is no way for developers how to release them. Result images are pushed into `candidate-registry.fedoraproject.org` by koji.

Different possible solution would be to push images directly into `registry.fedoraproject.org` by koji for rawhide.

Many thanks,
Marek

**Comment by omron93** [comment]
@cverna ?

**Comment by bowlofeggs** [comment]
There is not a technical reason that Bodhi could not be used for this today. However, since this is a policy/configuration issue, I think Release Engineering is probably the right place to ask this question, so I've refiled it for you there:

https://pagure.io/releng/issue/7979
