### ISSUE TITLE
[M] Drop support for fedmsg

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2838]
Now that Bodhi supports fedora-messaging, we should drop support for fedmsg.

CC @jeremycline @abompard

**Comment by AdamWill** [comment]
openQA relies on the Bodhi fedmsgs to trigger update tests. I'm happy to migrate to fedora-messaging, but I was sort of waiting for some sort of signal or flag day that we were going to start migrating *everything* in infra - for instance, I can't migrate the *compose* test trigger unless Pungi has also started emitting fedora-messaging messages (I don't know if it has), and so on...

**Comment by bowlofeggs** [comment]
@jeremycline can correct me if I am wrong, but as I understand it, there is a bridge that will translate fedora-messaging messages to fedmsg and vice-versa. If I am correct about that, you should still receive fedmsgs, even if Bodhi isn't sending them.

**Comment by jeremycline** [comment]
Indeed, there is a bridge from AMQP to fedmsg and fedmsg to AMQP (and they're currently running in production) so there will be no flag day. You can migrate at your leisure.

**Comment by bowlofeggs** [comment]
Fantastic.

On Wed, 2018-12-12 at 13:36 -0800, Jeremy Cline wrote:
> You can migrate at your leisure.

Did you pronounce that in your head like "leezure" or "lehzure"?

**Comment by bowlofeggs** [comment]
@abompard @jeremycline is there anything like fedmsg-hub for fedora messaging? I've got a few message consumers in Bodhi. Most of them would actually be better to replace with Celery, but there is one listener that looks for messages from robosignatory so Bodhi knows when builds are signed.

If there isn't a fedmsg-hub equivalent, I guess I could just make my own process that listens on the robosignatory topic.

**Comment by abompard** [comment]
@bowlofeggs You can either write a small script to call the listening API, or use the `fedora-messaging` command line and point it at a python callback. Docs and examples are here: https://fedora-messaging.readthedocs.io/en/stable/tutorial/usage.html#listening

**Comment by jeremycline** [comment]
Yes, the command is ``fedora-messaging consume`` (https://fedora-messaging.readthedocs.io/en/stable/fedora-messaging.html), although it looks like https://fedora-messaging.readthedocs.io/en/stable/consuming.html isn't linked to it which it probably should

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
