### ISSUE TITLE
my testing update has been waiting for 7 days but wont allow me to push to batched/stable ?

### ISSUE THREAD

**Issue by letoams** [fedora-infra/bodhi#2849]
This is currently affecting https://bodhi.fedoraproject.org/updates/FEDORA-2018-7a2cd05640

This update has been submitted for testing by pwouters. 8 days ago

This update has been pushed to testing. 7 days ago

submitted | 8 days ago
-- | --
in testing | 7 days ago
days to stable | 7

**Comment by bowlofeggs** [comment]
Critical path updates require 14 days in testing instead of 7 in Fedora:

https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/#updates-to-critical-path-packages

**Comment by letoams** [comment]
maybe the webgui could mention this?

**Comment by bowlofeggs** [comment]
@letoams it does say that the update has 7 days to stable in the screenshot you posted.
