### ISSUE TITLE
submitting one package for two different releases

### ISSUE THREAD

**Issue by mrunge** [fedora-infra/bodhi#285]
I made an update of python-django, UI offered me to add f22 and f23 version; submit seemed to fail and gave me a warning in the UI. Apparently it was submitted.

Unfortunately, linked bzs were only updated for f23 version, not for f22.

https://bodhi.fedoraproject.org/updates/python-django-1.8.4-1.fc23
https://bodhi.fedoraproject.org/updates/python-django-1.8.4-1.fc22

**Comment by ralphbean** [comment]
As per #219, the multi-release update submission is currently broken/undefined behavior in bodhi2.  We aim to get it back in place as soon as we can.
