### ISSUE TITLE
Intermittent test failure in one of Bodhi's fedora-messaging tests

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2858]
There's a [test assertion](https://github.com/fedora-infra/bodhi/blob/e30c5f2/bodhi/tests/server/test_notifications.py#L141) in Bodhi that occasionally fails like this:

```
bodhi/tests/server/test_notifications.py .......F

=================================== FAILURES ===================================
_____________________ TestPublish.test_fedmsg_publish_off ______________________

self = <bodhi.tests.server.test_notifications.TestPublish testMethod=test_fedmsg_publish_off>
mock_init = <MagicMock name='init' id='140416901561296'>

    @mock.patch.dict('bodhi.server.config.config', {'fedmsg_enabled': False})
    def test_fedmsg_publish_off(self, mock_init):
        """Assert when fedmsg publish is off, fedora-messaging messages are queued."""
        expected_msgs = [api.Message(topic='org.fedoraproject.dev.bodhi.demo.topic',
                                     body={u'such': 'important'})]
        session = Session()
    
        notifications.publish('demo.topic', {'such': 'important'})
    
        self.assertIn('messages', session.info)
        for expected, actual in zip(expected_msgs, session.info['messages']):
>           self.assertEqual(expected, actual)
E           AssertionError: Message(id='7e76630d-3e13-4478-9e82-f4f4a5975c0e', topic='org.fedoraproject.dev.bodhi.demo.topic', body={u'such': 'important'}) != Message(id='74855ca5-6638-472b-9018-6e5bde011267', topic='org.fedoraproject.dev.bodhi.demo.topic', body={u'such': u'important'})

bodhi/tests/server/test_notifications.py:141: AssertionError
```

The problem seems to be that the ```Message.id``` attribute is not the same between the two messages. We could fix it by either stopping to compare the ```id```, or maybe by contributing an assertion method to ```fedora-messaging``` that allows users to compare messages without having to compare the ```id```s.

@jeremycline what would you recommend here?

**Comment by jeremycline** [comment]
I think the problem is that the automatically-set ``sent-at`` header is included in the equality check which would explain the intermittent failure. The id shouldn't be included in the equality check and is just a uuid4 so it's quite likely it's never equal.

I can make a PR to delete the header for that bodhi test so you're unblocked and also fix the equality check in fedora-messaging.
