### ISSUE TITLE
[M] - Give Bodhi a task scheduling system

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2867]
Once we've done https://github.com/fedora-infra/bodhi/issues/2851, we should be able to give Bodhi a task scheduling system. This should allow us to get rid of several of the server CLIs, since they exist to be used in cron. Instead of having cron jobs, we can just farm the work out to task workers.

**Comment by sebwoj** [comment]
How about http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html?

**Comment by bowlofeggs** [comment]
On Sun, 2018-12-23 at 10:08 -0800, Sebastian Wojciechowski wrote:
> How about 
> http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html
> ?

Yeah if we go with Celery, we can use celerybeat. I've used celery for
many years, so it's likely we'll use that, but I think it could be good
to do a quick analysis of other options just to see what else is out
there.

**Comment by cverna** [comment]
Depends on #2851

Scope
---------
Convert the current cronjob (~ 4 jobs) to use celerybeat instead.
