### ISSUE TITLE
New package update failure (How long do you sync pkgdb with bodhi?)

### ISSUE THREAD

**Issue by cicku** [fedora-infra/bodhi#287]
I'm submitting new package update but it can't be found so I can't submit it.

How long should I wait? (I shouldn't wait for this)

**Comment by ralphbean** [comment]
Not sure -- but you can just type in the build NVR directly instead of waiting for the suggested list.

**Comment by cicku** [comment]
Last time I tried but failed with "you may not specify an empty list of builds"

**Comment by ralphbean** [comment]
AH! yes, so.. that's an issue a lot of people are hitting.

The old answer is:  "you have to press **enter** to add the build to the list"

In a commit just pushed in the last few hours, it will add a *button* next to that input field that will hopefully make it obvious that *just* typing it in isn't enough, you have to add it to the list by hitting enter or hitting that button.

**Comment by cicku** [comment]
Okkkk... :laughing:
