### ISSUE TITLE
Doubled HTTP requests (redirects) for queries

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#288]
I have noticed that every `Bodhi2Client.query()` that I send makes two HTTP requests. The first one goes to `/updates?something`, returns HTTP 302, and goes to `/updates/?something`. That can be easily tested, open:
https://bodhi.fedoraproject.org/updates?updateid=FEDORA-2015-13694
and you'll end up at:
https://bodhi.fedoraproject.org/updates/?updateid=FEDORA-2015-13694

The same is probably true for `Bodhi2Client.get_releases()`, which goes to `/releases` gets redirected to `/releases/`.

It might affect other requests as well, I haven't tested. I think these two (read-only, to retrieve data) are the most common ones which makes the most sense to optimize. You can cut the number of HTTP requests in half.

I tried to naively edit `Bodhi2Client.query()` and change
```
return self.send_request('updates', verb='GET', params=kwargs)
```
to
```
return self.send_request('updates/', verb='GET', params=kwargs)
```
but that didn't seem to get the job done. Either I did something wrong, or there is some url munging behind the scenes which needs to be adjusted as well.

python-fedora 0.5.5

**Comment by kparal** [comment]
> I tried to naively edit Bodhi2Client.query() and change

So, it seems I've been editing a wrong file (outside of virtualenv) and the change I mentioned should fix it for `query()`.

**Comment by ralphbean** [comment]
Thanks @kparal!

**Comment by ralphbean** [comment]
This will be a super simple patch to [python-fedora](https://github.com/fedora-infra/python-fedora) if anyone wants to take it on.

**Comment by ralphbean** [comment]
Will be fixed with the next python-fedora release.
