### ISSUE TITLE
Sign packages before a push

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/bodhi#29]
At the moment, signing packages and pushing updates are two, completely disjoint processes.

As a result, it is quite common to have a push failing because of unsigned packages, so you go and sign them, but then when you try to push there are new updates you need to sign, etc...

Bodhi could make signing a part of its push process, to avoid these problems.

However, signing requires user input (the passphrase to unlock the signing key), so that makes it a bit trickier.

**Comment by bowlofeggs** [comment]
I believe this concern is addressed by @puiterwijk's recent work that makes Bodhi Updates gate on whether the packages are signed or not. Now only signed builds will get mashed! This should be released with bodhi-2.3.0, which is currently scheduled to be released on Thursday this week.

https://github.com/fedora-infra/bodhi/pull/1011
