### ISSUE TITLE
Inexisting update state(Revoked) in docs

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2902]
https://bodhi.fedoraproject.org/docs/user/update_states.html#revoked

As far as I know "revoke" is only action.
So, can we remove it from docs, or the following line:
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L2587
should be changed?

**Comment by bowlofeggs** [comment]
We should correct the docs to reference the state that happens when an update is revoked.
