### ISSUE TITLE
Remove deprecated Update.old_updateid

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2903]
SSIA

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
