### ISSUE TITLE
Refactor integration tests to create their own data

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2934]
Right now the integration tests load database data from production and then perform some tests on the server using that data. This is problematic because the production data changes every day, which leads to test inconsistencies.

It would be better if we instead loaded predictable data into the integration test database (similar to what we do in the unit tests. Then we can be sure of our preconditions for all of our tests.

**Comment by abompard** [comment]
For now I disagree with that. Production data is indeed non-predictable, but that's the data that the next version of Bodhi is going to be running with. If there is an unexpected situation in the production data that causes a crash in Bodhi, I'd be happy to see the integration tests fail. And we can't anticipate those situations by feeding the tests controlled data (by definition).
I think that controlled data is fine for unit tests, but it's better to run integration tests on production data. For a little while we'll be fixing the tests to handle all the cases that happen in production, but one day it may very well detect a bug in the code, and not in the tests.
What do you think?

**Comment by abompard** [comment]
After discussing this with Randy, he seems to agree that prod data is better suited for integration tests. Can we close this issue?

**Comment by bowlofeggs** [comment]
Yep, thanks @abompard!
