### ISSUE TITLE
strange "in 4 hours" text next to rpmlint output

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/bodhi#294]
https://bodhi.fedoraproject.org/updates/execstack-0.5.0-9.fc23 says "rpmlint	execstack-0.5.0-9.fc23	in 4 hours" in the "Automated Test Results". The results are already there, so I don't know what this is supposed to mean.

**Comment by keszybz** [comment]
A related note: I find the cross-in-circle mark quite confusing. It looks like a button to close or get rid of the red box. But in fact it is a link to the results.

**Comment by robert-scheck** [comment]
I think my #297 might be a duplicate of this. If I am right, this is an issue between server and local time and thus the time zone difference.

**Comment by keszybz** [comment]
Yeah, that seems likely. It now says:
```
rpmlint	execstack-0.5.0-9.fc23	in 3 hours
depcheck	execstack-0.5.0-9.fc23(x86_64)	in 4 hours
depcheck	execstack-0.5.0-9.fc23(i386)	in 4 hours
```

**Comment by ralphbean** [comment]
This is also a duplicate of #217.

**Comment by keszybz** [comment]
Closing in favour of  #217.
