### ISSUE TITLE
Update.display_name seems to be unused

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2955]
I'm not able to check all DB updates(DB query takes too much memory), but each update in
state: pending, testing, obsolete, unpushed, has empty display_name.

**Comment by sebwoj** [comment]
Now I see that this field is a part of 24953bd2f (side tags).

**Comment by bowlofeggs** [comment]
Yeah this was added at the request of @ryanlerch - he wanted users to be able to set a display name for updates. I think the idea was that Bodhi would default to using the NVRs as it does today, but that users could optionally override it to say something more meaningful if they wanted.

The side tag plans evolved quite a bit recently and I'm not sure the display name is needed as part of that effort anymore with the new plans. It seems like Bodhi will not be responsible for creating side tags if the new plan sticks. The current idea is to make a koji plugin that creates and manages the side tags, and then we'd have bodhi create an update based on a side tag.

All that to say that I think the display name still has a place in Bodhi but the motivation to use it for side tags may not be there anymore.
