### ISSUE TITLE
Update.greenwave_unsatisfied_requirements seems to be unused

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2958]
Since talking to GW is handled by js, and Bodhi is working only based on GW decision, Update.greenwave_unsatisfied_requirements  seems to be unused.

**Comment by bowlofeggs** [comment]
Thanks @sebwoj!

**Comment by bowlofeggs** [comment]
This field is removed in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
