### ISSUE TITLE
Bodhi webinterface disagrees with nagmail about stable push

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#296]
```
Date: Fri, 21 Aug 2015 06:59:07 +0000
From: updates@fedoraproject.org
To: …
Subject: [Fedora Update] [comment] imaptest-20150812-1.fc23
Message-Id: <20150821065909.584A26076F7B@bastion01.phx2.fedoraproject.org>
X-Mailer: TurboMail 3.0
From updates@fedoraproject.org  Fri Aug 21 08:59:14 2015

The following comment has been added to the imaptest-20150812-1.fc23 update:

bodhi - 2015-08-21 06:59:06 (karma: 0)
This update has reached 3 days in testing and can be pushed to stable now if the maintainer wishes

To reply to this comment, please visit the URL at the bottom of this mail
```

But when trying to push the package to stable via https://bodhi.fedoraproject.org/updates/imaptest-20150812-1.fc23 I receive "This update has not yet met the minimum testing requirements defined in the Package Update Acceptance Criteria" instead. Why? Feels like a bug somewhere...

**Comment by lmacken** [comment]
This nagmail is from Bodhi1, which I just disabled in production.

**Comment by robert-scheck** [comment]
But you noticed that the nagmail was sent after bodhi2 was live?

Additionally, why can't I push the update to stable? It has been served for three days in testing, but bodhi2 is disagreeing about a stable push...

**Comment by lmacken** [comment]
Yeah, I forgot to disable the bodhi1 jobrunner, which I just did.

I'm looking into the other underlying issue now.

**Comment by lmacken** [comment]
Can you please try again?  The f23 pre_beta policy config didn't get ported over properly.

**Comment by robert-scheck** [comment]
No, does still not work. No more error message, but the Bodhi logo in the background wheels once and that's it.

**Comment by lmacken** [comment]
Oops, there were stray quotes in the config...How about now?

**Comment by robert-scheck** [comment]
Yes, works now. Thank you very much!

Btw, pushing to stable takes ~ 30 seconds (quite slow).

**Comment by lmacken** [comment]
Cool, thanks for testing. I opened #301 to investigate these performance issues.
