### ISSUE TITLE
Bodhi webfrontend seems to mixup server times and browser (local) time

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#297]
![fedora-time-mismatch](https://cloud.githubusercontent.com/assets/10982488/9415477/fe07aedc-483f-11e5-94ce-21162b53916a.png)
How is it possible that an automated test result is older than the update itself? From my point of view, this is an issue or a mixup between the server times (likely UTC) and the browser (local) time, which is CEST (UTC+02:00) in my case.

**Comment by ralphbean** [comment]
Yup, just like in #217, this is due to us getting UTC timestamps from the taskotron API *on the client* and passing those to `moment.js` without specifying a timezone.  Should be an easy javascript fix for someone.
