### ISSUE TITLE
Drop the batching feature

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2977]
Unfortunately, the batching feature was pretty controversial among the Fedora community and we were unable to garner enough support to keep it. FESCo has [voted](https://pagure.io/fesco/issue/1820) to remove it.

I would personally like to keep the feature, but I would also prefer not to have to maintain it if Fedora is not going to use it.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by bowlofeggs** [comment]
@sebwoj yeah. Strange, I wonder why GitHub didn't close this automatically? The related pull request had what looks to me like the correct "fixes #2977" in it…

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
