### ISSUE TITLE
Remove python-fedora-api-test.py

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#2980]
Since integration tests are finished, can we remove it from tools?

**Comment by bowlofeggs** [comment]
Yeah. Frankly I don't use anything in the ```tools/``` folder and it seems likely that many of them are broken by changes in Bodhi over the years.

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
