### ISSUE TITLE
multiple bug numbers rejected as "not a number"

### ISSUE THREAD

**Issue by letoams** [fedora-infra/bodhi#299]
Creating a new update for  conntrack-tools-1.4.2-8.el7 
Traceback (most recent call last):
  File "/bin/bodhi", line 532, in <module>
    main()
  File "/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 107, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: "1253755 1253757 1255578" is not a number
Could not generate update request: Command 'bodhi --new --release epel7 --file bodhi.template conntrack-tools-1.4.2-8.el7 --username pwouters' returned non-zero exit status 1

I tried using comma's and spaces. This is using fedpkg-.5.5 and bodhi-client-0.9.12.2-1

**Comment by lmacken** [comment]
Can you please provide the contents of the `bodhi.template` file?

**Comment by lmacken** [comment]
Nevermind, I'm able to reproduce this issue in staging. It only happens with multiple bug numbers.
