### ISSUE TITLE
[L] Bodhi should be able to automatically create updates when builds are tagged into Koji tags

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3007]
When Bodhi sees Koji builds getting tagged for a Release, it should automatically create updates for those builds.

In order to achieve this, we will need the following:

* A fedora-messaging listener that looks for builds getting tagged into particular tags, creating updates for those tags automatically.
* The update creator should be set to whichever FAS user created the build.
* Looks at the changelog to see if there are referenced RHBZ #'s that should be associated with the update.
* Uses the changelog entries to fill out the update description.

Note: This ticket will need some clearer requirements defined. For example, should the ```Release``` model have a boolean attribute that indicates whether or not automatic updates should be created for that release, or should Bodhi just create updates for any builds it sees into the specified Koji tags? i.e., would we want Bodhi to automatically create updates for stable Fedora releases too, and not just Rawhide?

**Comment by cverna** [comment]
I feel that this ticket needs to be split, for example do you think that the RHBZ part is mandatory for an MVP ? or should we consider it as nice to have ?

**Comment by bowlofeggs** [comment]
Note: it is possible that a FAS ID that makes a Rawhide build has never logged into Bodhi, so we need to handle that case when creating an update associated with those. When this happens, we just need to create the User account. Not sure what we would set the e-mail address to though…

**Comment by bowlofeggs** [comment]
On Fri, 2019-03-01 at 02:20 -0800, Clement Verna wrote:
> I feel that this ticket needs to be split, for example do you think
> that the RHBZ part is mandatory for an MVP ? or should we consider it
> as nice to have ?

The updateinfo.xml file includes this data. Technically we don't
produce an updateinfo.xml file for Rawhide today and so maybe it's OK
to consider that data a nice to have.

**Comment by nphilipp** [comment]
While going at it, there are some questions I had which we probably want to answer to do things right:

- What type of update should be created? A user submitting an update knows if it fixes bugs or is about enhancements, we don't. Should this get a new update type even?
- Gating aside, updates normally need either enough karma, or enough time plus submitter action to be moved to stable, both of which require manual intervention either on the side of testers or the submitter. Do we want to automatically push these updates to stable once gating has succeeded?

These may be answered elsewhere in the conversations about Rawhide Gating but I haven't come across them, nor would I know where to look for them.

**Comment by nphilipp** [comment]
Also, the updates would need to have an associated release:

- Should we have one "Rawhide" release that these updates are associated with, or should we just create the "real" releases early?
- Is the release supposed to be manually created or should we do that on the fly (with which information)?

**Comment by cverna** [comment]
> While going at it, there are some questions I had which we probably want to answer to do things right:
> 
>     * What type of update should be created? A user submitting an update knows if it fixes bugs or is about enhancements, we don't. Should this get a new update type even?

Good question I am not sure there a good way to guess the type of an update based on the data in koji. Maybe @bowlofeggs already thought about that.

> 
>     * Gating aside, updates normally need either enough karma, or enough time plus submitter action to be moved to stable, both of which require manual intervention either on the side of testers or the submitter. Do we want to automatically push these updates to stable once gating has succeeded?

This is what https://github.com/fedora-infra/bodhi/pull/3090 does. Autopush based on the time spent in testing. This time will be set to 0 for rawhide.
> 
> 
> These may be answered elsewhere in the conversations about Rawhide Gating but I haven't come across them, nor would I know where to look for them.

**Comment by cverna** [comment]
> Also, the updates would need to have an associated release:
> 
>     * Should we have one "Rawhide" release that these updates are associated with, or should we just create the "real" releases early?

I would think that having a "rawhide" release would make things easier, but there might some reason not to do that.

> 
>     * Is the release supposed to be manually created or should we do that on the fly (with which information)?

The releases are manually created by Release Engineering, so we don't have to create them.

**Comment by bowlofeggs** [comment]
We had a meeting about these questions today, so I'll record our
conclusions:

On Thu, 2019-04-04 at 10:57 +0000, Nils Philippsen wrote:
> What type of update should be created? A user submitting an update
> knows if it fixes bugs or is about enhancements, we don't. Should
> this get a new update type even?

Let's add a new "unspecified" enum variant for automatically created
updates for now. We should not allow UI, CLI, or API users to set the
enum to this new value. In the future, we could consider providing a
way for packagers to specify this in the RPM changelog, or perhaps via
the commit message.

> Gating aside, updates normally need either enough karma, or enough
> time plus submitter action to be moved to stable, both of which
> require manual intervention either on the side of testers or the
> submitter. Do we want to automatically push these updates to stable
> once gating has succeeded?

See https://github.com/fedora-infra/bodhi/issues/2978 - that will give
us the ability to automatically push updates based on time in testing.
The plan for Rawhide is to set the time in testing to 0 days, so they
should get pushed as soon as their tests pass.

**Comment by bowlofeggs** [comment]
On Thu, 2019-04-04 at 04:25 -0700, Nils Philippsen wrote:
> Should we have one "Rawhide" release that these updates are
> associated with, or should we just create the "real" releases early?

> Is the release supposed to be manually created or should we do that
> on the fly (with which information)?

When we start using Bodhi to manage Rawhide, Release Engineering will
create a Rawhide release in Bodhi.

For development purposes, you have a couple options. You could use
```bodhi releases create``` to create a Rawhide release in your
development environment. You will need to configure it to have 0 days
of testing in your development.ini file (see comments in production.ini
for how to do this.) To be allowed to make a release, you will need to
configure your development.ini to consider one of the FAS groups you
are part of to be Bodhi admins (see comments in production.ini for this
as well.) Another option is to just configure an existing release to
have 0 days in testing in your development.ini.

**Comment by nphilipp** [comment]
For the remainder of items not implemented with PR #3168, I've created a new issue: #3192
