### ISSUE TITLE
[M] Bodhi should respond synchronously to Greenwave decisions

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3008]
Bodhi currently polls Greenwave to find out its gating decisions, using ```bodhi/server/scripts/check_policies.py```. This isn't great, because the web interface polls Greenwave on every load, which means that there can be a lag between Bodhi's front end and back end on the decision.

We should add a fedora-messaging consumer that processes decisions from Greenwave. It should update the same information that ```check_policies.py``` does.

The lack of this feature causes confusion among packagers, as they see that their update passed checks in the Bodhi UI and so ask infrastructure members why their update hasn't moved to stable yet.

Since Greenwave is still using fedmsg, which is not reliable, we should not remove Bodhi's polling as part of this work. This way our polling can be used to ensure we have eventual consistency when we miss messages.

**Comment by cverna** [comment]
@bowlofeggs  I going to take this one over, this that works for you

**Comment by bowlofeggs** [comment]
@cverna sure, thanks!

**Comment by tdawson** [comment]
I have the basic code ready.  I'm currently working my way through the greenwave messages to find what I need to grab the correct update.  After that, figuring out how to do testing of this.

**Comment by sebwoj** [comment]
Duplication #1513

**Comment by tdawson** [comment]
Greenwave currently isn't sending any messages on either fedmsg or fedora-messaging.  That's making this a bit hard to work on.  From the example fedmsg that is supposed to be sent by greenwave, there isn't enough information to determine the bodhi update that is being referenced.  I'm hoping that is just a bad example that I'm looking at.
I have opened an issue to get greenwave sending messages again.
https://pagure.io/fedora-infrastructure/issue/7735

**Comment by cverna** [comment]
> Greenwave currently isn't sending any messages on either fedmsg or fedora-messaging. That's making this a bit hard to work on. From the example fedmsg that is supposed to be sent by greenwave, there isn't enough information to determine the bodhi update that is being referenced. I'm hoping that is just a bad example that I'm looking at.

I don't think that the greenwave fedmsg format or content changed. I expect the following to be true https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#greenwave. 
I think we want to use the koji builds nvr from the message to lookup for the corresponding update.

Here is an example of a greenwave message for the `bodhi` package --> https://apps.fedoraproject.org/datagrepper/id?id=2019-09aceb45-3360-4f83-9975-32ae6439c41c&is_raw=true&size=extra-large

It looks like the `msg["subject_identifier"]` provides the nvr.


> I have opened an issue to get greenwave sending messages again.
> https://pagure.io/fedora-infrastructure/issue/7735

**Comment by tdawson** [comment]
Thank you for that link to the full greenwave message in datagrepper.  I'm still fairly new to the fedmsg datagrepper and didn't know you could get the full message from it.
I also see that the reason I couldn't get a full NVR from the example, is that the example is an image compose, not an rpm build.  So there was no NVR to get from the example.

Greenwave still needs to get fixed so that it sends messages again, but I believe I'm unblocked now.

**Comment by tdawson** [comment]
I believe I have the code ready in this pull request.
https://github.com/fedora-infra/bodhi/pull/3200

**Comment by sebwoj** [comment]
Yes, I think that we can close this.

**Comment by pypingou** [comment]
Let's do it :)
