### ISSUE TITLE
[S] - API users should be able to create updates based on Koji side tags

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3009]
Bodhi currently allows users to create updates by specifying a list of builds via the API. In order to support Rawhide gating without addition additional steps to packagers for Rawhide packaging*, we will need to provide a way for packagers to create multi-build updates. In #3007 we are planning to automatically create updates when we see builds tagged into particular Koji tags. That will work for single build updates, but packagers often need to update multiple packages atomically due to build dependencies.

The plan here is to allow packagers to work in Koji side tags to do their builds. When they are ready to publish their work, they will ask Bodhi to create an update based on that side tag. Bodhi will then query Koji to get the needed information and create an update with the builds found there.

The API needs to allow packagers to create updates based on NVRs, as they do today, or based on koji side tag names. When packagers use a side tag, Koji should be queried to find the list of NVRs, and then Bodhi can proceed as it would have before.

* Packagers are not used to dealing with Bodhi for Rawhide. We could just start using Bodhi for Rawhide today, but many packagers would be confused and some may dislike the extra step. This plan is about trying to minimize any extra burden placed on packagers as we add gating to Rawhide.

**Comment by cverna** [comment]
Scope
--------

Idea is to reuse the current Update creation form and add a toggle to either provide a list of build or a side tag. Based on the input the API will be able to either process the list of build or get the list of build from the side tag before processing it.

Notes: We might want to store the side tag provided, to allow packager to edit the update and not have to provide the side tag again.

**Comment by nphilipp** [comment]
I'll pick this up, but so far can't make it official because I don't have the necessary permissions, see https://pagure.io/fedora-infrastructure/issue/7747

**Comment by nphilipp** [comment]
The PR for this is #3228, which I missed linking here for a while.
