### ISSUE TITLE
[L] We need a functioning Greenwave and WaiverDB in the development environment

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3011]
It is currently very difficult to develop against Greenwave and WaiverDB. There isn't test data in staging, and so we can't test them there, and we obviously don't want to write waivers to the production WaiverDB  during development. We need to have the Vagrant environment provision both of these, and provide an easy way for Bodhi developers to simulate failing tests and set policies.

**Comment by cverna** [comment]
Could we mock these systems in the development environment ? I am thinking of simple python scripts that would send the expected requests to bodhi ? 

Or maybe this is a silly idea :smile:

**Comment by bowlofeggs** [comment]
This is Large.

**Comment by bowlofeggs** [comment]
On Fri, 2019-03-01 at 02:24 -0800, Clement Verna wrote:
> Could we mock these systems in the development environment ? I am
> thinking of simple python scripts that would send the expected
> requests to bodhi ?

We do mock them for unit tests, but I estimate that it might actually
be more work to write and maintain a mock than it would be to have
running services.

**Comment by sebwoj** [comment]
Should we provide GW and WDB as a docker service(like in integration tests)?
