### ISSUE TITLE
Can not add bugzilla reference

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#3023]
I tried to add a reference to https://bugzilla.redhat.com/show_bug.cgi?id=1678129 in the bodhi update https://bodhi.fedoraproject.org/updates/FEDORA-2019-23ed568d47 but was not successful.
I pressed Edit, entered the RHBZ number and pressed + and the bug number appeared in the list with the checkbox ticked. Then I pressed Save and the spinning wheel appeared as if the request was being processed. After a while the spinning wheel disappeared as if the processing was done, but there was neither a Success message nor an Error message displayed. If I reload the update page there is no indication of the bug I added, and neither are there any comments added to the bugzilla ticket. I do get an e-mail about that I edited the ticket, but there are no changes mentioned in this e-mail.

**Comment by bowlofeggs** [comment]
Hi @ellert,

This was fixed by https://github.com/fedora-infra/bodhi/pull/3028, which I expect to release and deploy later today. Thanks for the report!
