### ISSUE TITLE
When the CLI hits a server error, it prints out a lot of HTML

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3036]
The Bodhi CLI prints out a lot of HTML when it hits server errors, such as what happened in #3024. The server should not return HTML upon requests from the CLI, but instead should return a standardized error struct (which needs to be defined as part of solving this issue). Then the CLI should look for this error struct and format the error in a human readable fashion.

**Comment by sebwoj** [comment]
@bowlofeggs Since we have #3042, can we close it?

**Comment by bowlofeggs** [comment]
Yep, thanks!
