### ISSUE TITLE
As a CLI user, I can edit the list of builds in an update

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3037]
I just noticed that ```bodhi updates edit``` does not let you add or remove builds from an update. We should give it the ability to alter the set of builds on an update.

**Comment by tdawson** [comment]
Pull request for this option
https://github.com/fedora-infra/bodhi/pull/3125

**Comment by tdawson** [comment]
Pull request has been merged.
This should be available in the next release.
