### ISSUE TITLE
The search box results for packages links to users

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3040]
If you click the search box in the upper right hand corner and type "ejabberd", you will get some matches on packages and updates. If you click on the ejabberd package result, it will take you to ```/users/ejabberd```, when it should take you to a view that shows you updates that pertain to that package.

I believe it is due to this code:

https://github.com/fedora-infra/bodhi/blob/09dc4c3808f28eb76f0e3cea02567842f7e47624/bodhi/server/static/js/search.js#L51-L67

Note the ```hasOwnProperty('stack')``` in there. Stacks were removed in #2241, and I must have missed this when I made that change.

To fix it, we'll need the if statement to correctly identify packages so that the packages link is used instead of the user link later in the ```if/else``` block.

**Comment by ryanlerch** [comment]
@bowlofeggs are you able to reproduce this on bodhi.fp.o? i can reproduce on my vagrant setup, but not on live.

**Comment by sebwoj** [comment]
@ryanlerch 
The problem is that in prod/stg `package.stack` exists, but in Vagrant Bodhi env not.
And as Package and User both have `name`, in Vagrant we get `/user` instead od `/package`

**Comment by bowlofeggs** [comment]
@ryanlerch yeah it's only reproducible in dev - it's a regression from when I removed the stacks feature in #2241 - I must have missed this JS (my mistake).
