### ISSUE TITLE
Bodhi should only block updates when Greenwave returns a NOGO response

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3044]
Currently Bodhi will only allow updates to proceed to repositories if Greenwave gives back a GO response. This means that updates will be blocked from proceeding if Greenwave raises an Exception, which has been [happening often recently](https://pagure.io/greenwave/issue/388). Due to the frequent nature of these errors, it is most sensible to adjust Bodhi such that it will only block an update if Greenwave gives back a positive NOGO answer, and that any other answer (GO, error, etc.) means that the update can proceed.

**Comment by pypingou** [comment]
FTR, this does mean if the cron job runs while the service is being restarted, upgraded or during a reboot or openshift or anything like this, all updates will go through.

**Comment by bowlofeggs** [comment]
Of course. We can't tell the difference between those scenarios and it failing for other reasons, but we are going to be correct in almost all cases that it is a failure in Greenwave and not infrastructure. With this patch, at least we can gate some of the time correctly.

We cannot pass the pain of an architectural choice on to our volunteer packagers. When forced to choose between easing the work of our volunteer contributors in Fedora who are choosing to spend their free time to help us make a product, and a small fraction of packagers that use test gating, I side with protecting the volunteer's time. It's not fair to make them pay the price of the architectural choice that led to these problems.

Test gating is still an experimental feature and is clearly not production ready as evidenced by this and the long list of bugs related to it. Shipping updates is Bodhi's most core function. We can't hold up Bodhi's core function for an experimental feature.

If we move the test gating logic into Bodhi, we won't have either problem.

**Comment by bowlofeggs** [comment]
Fixed in #3045
