### ISSUE TITLE
"<user> submitted <no.> <package> testing updates for <branches>" leads to 404

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#305]
Link "https://admin.fedoraproject.org/updates/gofed/" for "jchaloup submitted 3 gofed testing updates for F21, F22, and F23" at https://bodhi.fedoraproject.org/ leads to "404 Not Found\nThe resource could not be found."

**Comment by ralphbean** [comment]
Yup.  It's the trailing slash.

Partly discussed in #230.

Could be fixed in bodhi with a change to the cornice services **or** maybe more easily fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure
