### ISSUE TITLE
Add logs at every place that expires buildroot overrides

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3060]
Some users have been having trouble with buildroot overrides getting unexpectedly untagged in Koji, and according to Koji the Bodhi user is the one untagging it. Unfortunately, Bodhi does not currently emit log messages when ```BuildrootOverride.expire()``` is called, so it is not easy to tell which code path is responsible for this.

We should find all the calls to ```BuildrootOverride.expire()``` and add log messages to explain *why* it is being called, for each one. This way we will have more useful debugging information in the future.

**Comment by nphilipp** [comment]
I'll take a shot at this before my PTO next week.

**Comment by nphilipp** [comment]
Looks like I need to be added to the org or project before I can assign this to myself.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
