### ISSUE TITLE
CI is a bit flaky

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3074]
Our CI runner is a bit flaky. It seems that it occasionally fails while waiting for the PostgreSQL container to start up. I recently tried raising the amount of time it waits from 30 seconds to 64 seconds. This likely helped a bit, but I just saw another failure:

https://ci.centos.org/job/bodhi-pipeline/job/PR-2842/73/execution/node/459/log/?consoleFull

I have a few ideas to consider:

0. We could try raising the timeout even more. This is the easiest but also dirtiest solution. The real problem is likely that we are running too many things at once on the CI system and its load is high.
1. We could configure the [groovyscript](https://github.com/fedora-infra/bodhi/blob/81bb242/devel/ci/cico.pipeline) to limit how many concurrent jobs are run. This would be a more elegant solution, but would also duplicate some features with bodhi-ci.
2. We could give bodhi-ci a new flag to have it output machine-readable data and have the groovyscript use that flag. Then we could refactor the groovyscript to read this machine-readable output in order to set the GitHub flags at the end of the job. The pros of this approach are that we could use a more similar call to bodhi-ci in CI as we use locally when developing (right now the groovyscript starts several bodhi-ci's in parallel, rather than letting it manage the jobs as it does locally). The cons are that it is the most work of the three ideas I've written here, and also that it won't report anything to GitHub until the entire job is done (well it may be possible to have it report as it goes, but that may be tricky to do, especially since I don't really know Groovy.)

**Comment by bowlofeggs** [comment]
I just had another idea for a solution here we could consider: we could get more than one Duffy node and run half the releases' tests on one, and the other half on the other. That would cut the load down a lot by spreading the load over more than one machine.

**Comment by abompard** [comment]
Brian says "certainly, you can have request up to 6 in a 5 minute time period". I'll try to implement that without repeating myself too much.

**Comment by bowlofeggs** [comment]
I know there's an open pull request for this, but wanted to write down one more easy solution I thought of. The goal of reporting all the test results is to allow us to mark some of them as required for merging vs. ones that aren't required (like Rawhide).

We could solve this problem by running bodhi-ci exactly twice - one run would be for the required releases, and the other run would be for Rawhide. Then we would just report two results to GitHub, required tests and non-required tests. This would allow us to let bodhi-ci handle the concurrency mostly, without needing it to do all the machine readable stuff.

The downside would be that all the test output would be in two jobs instead of in 40 like it is today, but I think that's a fair trade to get reliability for now.

What do you think?

**Comment by sebwoj** [comment]
@bowlofeggs What do you think about running test sequential, instead of parallel:
https://github.com/fedora-infra/bodhi/blob/04a331013f7b7a39ba15d0190a7b29e4d1f7d46c/devel/ci/cico.pipeline#L158

**Comment by bowlofeggs** [comment]
@sebwoj thanks for the suggestion! I put that into action this week and it does seem to be more reliable, but we still need some improvements.

**Comment by bowlofeggs** [comment]
I'm going to open a PR to try out my idea of reporting optional and required tests separately.

**Comment by bowlofeggs** [comment]
Here's a PR where I am trying out my idea of having bodhi-ci just manage the concurrency:

https://github.com/fedora-infra/bodhi/pull/3150

**Comment by sebwoj** [comment]
@bowlofeggs CI test are fine now. What do you thing about closing this?
