### ISSUE TITLE
error code 500 - traceback might be useful

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/bodhi#3078]
I was at the https://bodhi.fedoraproject.org/composes/ url just now and I refreshed and I get an error with a traceback. it might be useful to tracking down a bug: 

![Untitled](https://user-images.githubusercontent.com/4530030/54721929-b72e6180-4b39-11e9-9094-1019d812ded0.png)

**Comment by bowlofeggs** [comment]
Yeah this is actually fixed in our develop branch and will get included in at least 4.0.0 (or possibly a 3.something release, if we make another one): https://github.com/fedora-infra/bodhi/issues/2826
