### ISSUE TITLE
Release Bodhi 3.14.0

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3084]
We should make a 3.14.0 release, with @owtaylor's flatpak namespace patches, and perhaps a few other fixes. Here are the two must-have pull requests to get into 3.14.0:

- [ ] https://github.com/fedora-infra/bodhi/pull/2924
- [ ] https://github.com/fedora-infra/bodhi/pull/3052

And here's one that isn't quite a must-have, but I think would be wise to include since it fixes a crash:

- [ ] https://github.com/fedora-infra/bodhi/issues/2826

**Comment by bowlofeggs** [comment]
Here are a list of what I would call "nice to have"s - they are completely at the option of whoever does the release. Some of them may be tricky to backport, so don't go through heroic efforts if they are, and feel free to ignore them even if you just don't want to do it:

- [ ] https://github.com/fedora-infra/bodhi/issues/3060
- [ ] https://github.com/fedora-infra/bodhi/issues/3035
- [ ] https://github.com/fedora-infra/bodhi/issues/3021

Feel free to backport any others you like too, as long as they are not backwards incompatible.

**Comment by bowlofeggs** [comment]
@abompard, would you like to work on this to try out the release process with a pretty small release?

**Comment by abompard** [comment]
Yes please :-)

**Comment by bowlofeggs** [comment]
3.14 is released and deployed to production.
