### ISSUE TITLE
Misleading information about waivers in /updates/{alias}

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#3089]
Example:
[Example update: FEDORA-2018-bd73ec6f3a](https://bodhi.fedoraproject.org/updates/FEDORA-2018-bd73ec6f3a)

Waiver information in `Automated Tests` tab:
`Waived 2 different times`

Actual waivers (only one):
[quassel-0.12.5-1.fc27 waivers from waiverdb](https://waiverdb-web-waiverdb.app.os.fedoraproject.org/api/v1.0/waivers/?subject_identifier=quassel-0.12.5-1.fc27)

Reason:
In `update.greenwave_subject` return data, build nvr is provided twice in subject:
`{'product_version': 'fedora-27', 'decision_context': 'bodhi_update_push_stable', 'subject': [{'item': 'quassel-0.12.5-1.fc27', 'type': 'koji_build'}, {'original_spec_nvr': 'quassel-0.12.5-1.fc27'}, {'item': 'FEDORA-2018-bd73ec6f3a', 'type': 'bodhi_update'}], 'verbose': True}`

In response on the request above, GW is providing data with the following waiver entry(duplicated waiver entry):
`[{'comment': 'This is fine.', 'id': 131, 'product_version': 'fedora-27', 'proxied_by': None, 'subject': {'item': 'quassel-0.12.5-1.fc27', 'type': 'koji_build'}, 'subject_identifier': 'quassel-0.12.5-1.fc27', 'subject_type': 'koji_build', 'testcase': 'dist.rpmdeplint', 'timestamp': '2018-05-08T21:12:19.869536', 'username': 'tc01', 'waived': True}, {'comment': 'This is fine.', 'id': 131, 'product_version': 'fedora-27', 'proxied_by': None, 'subject': {'item': 'quassel-0.12.5-1.fc27', 'type': 'koji_build'}, 'subject_identifier': 'quassel-0.12.5-1.fc27', 'subject_type': 'koji_build', 'testcase': 'dist.rpmdeplint', 'timestamp': '2018-05-08T21:12:19.869536', 'username': 'tc01', 'waived': True}]`

Side effect:
Instead of detailed waiver information(detailed information is presented only when there are only one waiver [here](https://github.com/fedora-infra/bodhi/blob/a5a39c42a27b054e58003ec6b8d54a92a5fa90a8/bodhi/server/templates/update.html#L151)) website with update `FEDORA-2018-bd73ec6f3a` is informing user about 2 waivers, without providing details.

Fix(and here is the question):
Which field from `update.greenwave_subject` shoud be removed: `{'item': 'quassel-0.12.5-1.fc27', 'type': 'koji_build'}` or `{'original_spec_nvr': 'quassel-0.12.5-1.fc27'}`? Both works as expected, tested locally.

**Comment by bowlofeggs** [comment]
On Sun, 2019-03-24 at 10:19 -0700, Sebastian Wojciechowski wrote:
> Which field from update.greenwave_subject shoud be removed: {'item':
> 'quassel-0.12.5-1.fc27', 'type': 'koji_build'} or
> {'original_spec_nvr': 'quassel-0.12.5-1.fc27'}? Both works as
> expected, tested locally.

I'm not sure, it is probably best to ask the Greenwave project:

https://pagure.io/greenwave

**Comment by gnaponie** [comment]
Hello,
sorry for the late reply. I saw this issue only now.
@sebwoj I'm Greenwave's main developer. I'm actually not sure which one you should use. Maybe @ralphbean can help me on that.

I've filed this PR to quickly address the issue: https://pagure.io/greenwave/pull-request/405
I can let you know once this gets released.

I hope this helps!

**Comment by sebwoj** [comment]
Hi @gnaponie 
Funny, I just writing new issue on the GW repo in pagure, but noticed you comment here :)

Thanks for your help!

**Comment by sebwoj** [comment]
New GW released.
