### ISSUE TITLE
Overall Metrics Request Produces: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by caronc** [fedora-infra/bodhi#3095]
Using an authenticated account, I get a 500 server error if i choose **Overall Metrics** from the _Stats_ dropdown that reads:
`'NoneType' object has no attribute 'groups'`

![Screenshot from 2019-03-25 20-22-49](https://user-images.githubusercontent.com/850374/54962655-04e10a80-4f3c-11e9-8aa0-eb5e18e3c27e.png)

I've only been just recently sponsored for a package maintainer role, so i'm not sure if that's related or not (but worth sharing) :slightly_smiling_face:

**Comment by cverna** [comment]
Hi @caronc thanks for reporting this. We have already a ticket for that #2966 which is already fixed in the main branch but not yet deployed in production.

So I am going to close this ticket.
