### ISSUE TITLE
Reconcile Update.{get_title,beautify_title}()

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3114]
The ```Update``` model has two methods that both generate a title:

https://github.com/fedora-infra/bodhi/blob/a5a39c42a27b054e58003ec6b8d54a92a5fa90a8/bodhi/server/models.py#L2280-L2296

and

https://github.com/fedora-infra/bodhi/blob/a5a39c42a27b054e58003ec6b8d54a92a5fa90a8/bodhi/server/models.py#L2369-L2402

Of course, these two functions don't do the same exact thing, but it doesn't make a lot of sense to have them both.

Let's do an analysis of how these are each used, and then simplify by making a single function that can be used to generate a title for updates.

**Comment by sebwoj** [comment]
@ryanlerch Can we close this?

**Comment by StephenCoady** [comment]
Completed in attached PR.
