### ISSUE TITLE
Support Sourceware bugs in Fedora enhanced markdown

### ISSUE THREAD

**Issue by codonell** [fedora-infra/bodhi#3129]
Many key projects reside on sourceware.org including glibc, gdb, binutils, elfutils, libabigail, systemtap etc.

Could you please add markdown support for sourceware.org bugzilla (https://sourceware.org/bugzilla/)?

I suggest a unified markup of SWBZ#XXXX or SW#XXXX for all projects on the main sourceware bugzilla instance.

Likewise gcc compiler bugs are also on sourceware but use a distinct instance (https://gcc.gnu.org/bugzilla/)

I suggest a markup of GCC#XXXX for gcc bugs.

Thank you!

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
