### ISSUE TITLE
Move bug commenting into async process

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#314]
This should help a lot with performance, but let's leverage fedmsg and move bug commenting (the initial bug comment) out of ``Update.new(..)`` and into a new fedmsg consumer that gets run on bodhi-backend01.  It can listen for when new updates are created by the frontend and then do some of the more expensive tasks (like commenting on bugs..).

**Comment by lmacken** [comment]
Great idea!

**Comment by lmacken** [comment]
I think a ton of the slowness is coming from querying the wiki in `Package.fetch_test_cases`, so we should do that in this consumer as well.

**Comment by cicku** [comment]
And I think it's really helpful to reduce the time consumption of waiting.
