### ISSUE TITLE
Push to stable request not updated after update has been pushed to stable

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3154]
This is strange, I've pushed to stable an update and now I can see Bodhi claims to be in stable, but still shows "Request: stable":
https://bodhi.fedoraproject.org/updates/FEDORA-2019-284e0d2daf

**Comment by sebwoj** [comment]
Update is locked(in the top left corner):
![Screenshot from 2019-04-13 10-17-41](https://user-images.githubusercontent.com/42519683/56076837-a8a03680-5dd5-11e9-82fd-78d2106a9d87.png)

Request value will be removed after unlocking:
https://github.com/fedora-infra/bodhi/blob/7e780c7743b208c893ab9b68a352ef23a501dfe7/bodhi/server/consumers/masher.py#L681

**Comment by bowlofeggs** [comment]
Yeah this is just a consequence of how Bodhi keep track of which updates are part of a compose. Thanks for letting us know though!
