### ISSUE TITLE
Hidden push buttons

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#318]
The top banner is very tall and hides part of the page. In the screen shot attached the page is scrolled as far upwards as is possible, but part of the page - including the push buttons - are hidden behind the banner.

![bodhi-banner](https://cloud.githubusercontent.com/assets/1931206/9422813/c9c43418-48a5-11e5-9edc-fbdfc9d53e60.png)

If the page is resized the different elements on the page jump around, and in some configurations the push buttons comes out of hiding. But the push buttons should be visible regardless of the width of browser window.

**Comment by ralphbean** [comment]
Oh, give the page a hard reload.  You have the css assets from an old release cached in your browser (we're cutting releases quite frequently).
