### ISSUE TITLE
misleading notification for automatic karma pushes

### ISSUE THREAD

**Issue by morxa** [fedora-infra/bodhi#320]
If the karma threshold is reached and the update is automatically pushed, the notification says that the last person giving karma submitted the update for stable. See for example [this i3 update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-13445), which says:
> This update has been submitted for stable by thofmann. 

I only added karma, I did not submit anything.

#### How to reproduce
1. Find an update in testing which needs +1 karma to reach the threshold, and with automatic pushing enabled
2. add +1 karma

**Comment by ralphbean** [comment]
This should be a simple string change.  Thanks for reporting!
