### ISSUE TITLE
Document the full set of bug trackers that can be referenced in Bodhi's markdown

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3209]
While reviewing #3173 today, I realized that we don't document the full list of bug trackers that Bodhi supports in its markdown:

https://github.com/fedora-infra/bodhi/blob/3ea106ae8a074f26fb6982c133ac85299704782c/bodhi/server/ffmarkdown.py#L65-L74

We do have a link under the update comment box that pops up a modal that mentions a few of these:

![Screenshot from 2019-05-02 12-30-30](https://user-images.githubusercontent.com/354506/57091075-5f594d80-6cd6-11e9-847a-16a1993cb81f.png)

That model is here:

https://github.com/fedora-infra/bodhi/blob/3ea106ae8a074f26fb6982c133ac85299704782c/bodhi/server/templates/fragments.html#L218-L243

We should also document this in our Sphinx project.

So to solve this ticket, two things should be done:

- [ ] Document the trackers in the modal.
- [ ] Add a section to our Sphinx docs about Bodhi markdown, and list these there as well.

**Comment by bowlofeggs** [comment]
P.S. We can have the modal just link to the Sphinx docs - that might be better so we only have one place we need to maintain the list.

**Comment by bowlofeggs** [comment]
Perhaps an even better option is to have the list automatically generated from the code.

**Comment by binayakbehera999** [comment]
I would like to work on this @bowlofeggs . I am new to open source, could you guide how to start with this issue?

**Comment by richardgreg** [comment]
@cverna pls assign me to this. Thanks.

**Comment by richardgreg** [comment]
>We do have a link under the update comment box that pops up a modal that mentions a few of these:

@bowlofeggs There is a help icon in the update's comment box that alludes to Fedora-Flavored Markdown and that's it. No link to `/fragments.html`
