### ISSUE TITLE
"Stuck" updates with "Bodhi is unable to request this update for stabilization: This update has not yet met the minimum testing requirements"

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/bodhi#3218]
I have a bunch of updates for which I clicked on the "push to batched" button, but I keep getting "Bodhi is unable to request this update for stabilization: This update has not yet met the minimum testing requirements defined in the Package Update Acceptance Criteria" one every 24h.

  https://bodhi.fedoraproject.org/updates/FEDORA-2019-6c4e5fc271                                                              
  https://bodhi.fedoraproject.org/updates/FEDORA-2019-0b2adfac87                                                              
  https://bodhi.fedoraproject.org/updates/FEDORA-2019-8e3b4690c6                                                              
  https://bodhi.fedoraproject.org/updates/FEDORA-2019-b789f85211                                                              

There's also #2133, but it seems different.

**Comment by bowlofeggs** [comment]
Hey @keszybz!

Each of these hasn't been in testing for 7 days yet, so that's why that message is happening. 

The push to stable/batched button should not be appearing, but that is reported here: https://github.com/fedora-infra/bodhi/issues/1508
