### ISSUE TITLE
bodhi update shows wrong submitter (on old update(s)?)

### ISSUE THREAD

**Issue by bitlord** [fedora-infra/bodhi#322]
I first time tried bodhi2 and when I explored different options ..., I saw that it says I submitted one update, which is impossible, I never did it, I'm not a packager ..., not sure if something went wrong with data conversion ..., but specific update is https://bodhi.fedoraproject.org/updates/PackageKit-Qt-0.9.2-6.fc21

**Comment by ralphbean** [comment]
Hi!  I think this is a duplicate of #241.  Once we have some time, we'll likely be able to pull the old correct data out of the old db snapshot and fix the current data.

**Comment by lmacken** [comment]
Yep, duplicate of #241. I have a fix that I'm testing in staging now.
