### ISSUE TITLE
We should not use blockingCallFromThread in the composer

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3236]
I spoke with @jeremycline today and he informed me that we should not be using ```twisted.internet.threads.blockingCallFromThread``` to wrap Bodhi's calls to ```publish()```. The reason is that though we are running in a thread, we are not a thread that is running the event loop and thus we should not be using any twisted code. We can treat all our code as if it were synchronous here.

Thus, I think we want to revert https://github.com/fedora-infra/bodhi/pull/3145

This seems to be related to the crash we saw in https://github.com/fedora-infra/fedora-messaging/issues/175

**Comment by jeremycline** [comment]
To expand on this a little bit:

fedora_messaging.api.publish uses the Pika blocking connection, not a connection managed by Twisted. Thus, it doesn't need to run inside the reactor thread and it, in fact, blocks the reactor loop so things like heartbeating can't occur. If you were calling the Twisted version of publish, you _would_ need to use blockingCallFromThread.
