### ISSUE TITLE
Bodhi's rate limiting doesn't work when the message consumers crash

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3238]
Bodhi's logging rate limiter stores its state in memory. This means that if the message consumer crashes while handling a message, an e-mail will get sent and then the process will exit, losing that state. That message then does not get acked and so when the process starts up again the same message is picked up and crashes the process again, sending another email. And so forth.

We should have a big 'ol try/except on our message consumer to catch any exceptions (preventing the process from crashing), log them, and then raise a Nack so the message is put back on the queue. This way we still get notified, the message is not lost, but we also don't get notified too many times.

**Comment by aidarbek** [comment]
I am a new to the project, but could you clarify few things if I understood this issue correctly?
Does it mean that simply the content of this function should be wrapped by try/except?
https://github.com/fedora-infra/bodhi/blob/cbb2bb99bf2f1d17b7183b1a1605f7ffc371d5fc/bodhi/server/consumers/__init__.py#L36
And once exception is raised, it's message should be sent passed `log.error()` and a new `fedora_messaging.exceptions.Nack` exception should be raised?

**Comment by bowlofeggs** [comment]
@aidarbek yeah that's exactly what it needs - though I'm actually going to take care of this now because I need it today to get a new beta built. However, there are a few more good starter issues here if you are interested in getting involved in Bodhi development:

https://github.com/fedora-infra/bodhi/issues?q=is%3Aopen+is%3Aissue+label%3AEasyFix
