### ISSUE TITLE
Bodhi redirects web UI users to a non-existant URL after creating updates

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3248]
Bodhi is redirecting users to ```/updates/{title}``` instead of ```/updates/{alias}``` when they create updates. The title is no longer a valid way to access updates, so this leads the user to a 404. We should instead redirect them to the alias URL.

**Comment by mattiaverga** [comment]
This is strange, the javascript that manages the update form is correctly set to redirect to `/updates/{alias}`:
https://github.com/fedora-infra/bodhi/blob/e42d7653a556a3e11ae0b961b6acc8772994037e/bodhi/server/static/js/update_form.js#L18
Indeed, the redirect works well in my local Vagrant VM.

**Comment by bowlofeggs** [comment]
I wonder if the user that reported it had stale cached JS in their browser?

**Comment by bowlofeggs** [comment]
I'm going to close this, as I haven't heard anything further about it. I think we can assume it was cached JS.
