### ISSUE TITLE
fedpkg update 'fails' to submit update

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#3255]
Submitting an update with `fedpkg` on the new bodhi outputs the following:
```
$ fedpkg update 
Could not execute update: Could not generate update request: 'anonymous'
A copy of the filled in template is saved as bodhi.template.last
```
though checking on web the update seems to have worked.

**Comment by bowlofeggs** [comment]
This is due to the Bodhi 3 client not being compatible with the Bodhi 4 server, which is what Fedora Infrastructure is currently hosting.

You can follow [this FESCo ticket](https://pagure.io/fesco/issue/2137) to see what Fedora will do about it (we haven't decided on a plan yet).

**Comment by bowlofeggs** [comment]
#3257 has a traceback with more info, so let's track this issue over there.

**Comment by QuLogic** [comment]
So I guess we can close this now that Bodhi 4 is in stable Fedora.
