### ISSUE TITLE
bodhi updates request fails from NVR

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#3258]
```
[mtasaka@localhost ~]$ bodhi updates query --mine --status testing | grep magic
 magic-8.2.113-1.fc29                     rpm        testing   2019-05-17 (12)
 magic-8.2.113-1.fc30                     rpm        testing   2019-05-17 (11)
[mtasaka@localhost ~]$ bodhi updates request magic-8.2.113-1.fc30 stable
Invalid update id
ACL validation mechanism was unable to determine ACLs.
```

This operation was accepted before. Note that querying ID of the update fails as written on https://github.com/fedora-infra/bodhi/issues/3257

**Comment by bowlofeggs** [comment]
Hi @mtaska!

The [Bodhi 4 server](https://bodhi.fedoraproject.org/docs/user/release_notes.html) does not accept NVRs as update IDs anymore: https://github.com/fedora-infra/bodhi/pull/3038

You should be able to set the request using the update ID (the ID is the string that looks like FEDORA-2019-xxxx).
