### ISSUE TITLE
Documentation "framework"?

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#326]
So, we need docs for lots of things.  Lots of people have questions about the things we've been talking about in `#fedora-apps` for years now -- stuff we've started to take for granted.  We should write it down.

I really like how FMN has [this page](https://apps.fedoraproject.org/notifications) which gets generated from [this file](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/notifs/frontend/files/fedora-sitedocs/about.rst).  We have a plaintext thing we can easily edit on the fly and it gets rendered nicely by the app.  The webapp does this with [this stretch of code](https://github.com/fedora-infra/fmn.web/blob/develop/fmn/web/app.py#L1059-L1122).

I'd like to do something very similar for Bodhi2 where we can document what you use bodhi for, all the things it can do, a FAQ for quirks, etc..  We could start just by copying the existing code from FMN, but I'd like to take it a step further.

Boostrap has this nice layout/navigation thing for docs called [affix](http://getbootstrap.com/javascript/#affix) that we could use to make it all look pretty, with a table-of-contents.  In order to do it though, we'll need to modify the HTML output we get so we'll either need to hack docutils to generate the more complicated version of what we want, or we'll need to use some other tool (like pandoc?)

Furthermore, it seems reasonable to me that we could auto-generate nice API docs from our cornice services and their colander schemas and validators (as long as we gave those all some nice docstrings).  It would be the coolest if we had a dropdown item in the top navigation bar titled "Docs" that had multiple items under it for FAQ, API, and "Contact us" (which could just take people here to file a github/pagure issue).

**Comment by bowlofeggs** [comment]
We do have documentation now with Sphinx. We even have the REST API autodoc'd as of last week! The docs will be hosted at https://bodhi.fedoraproject.org/docs after the infra freeze, but they are currently available at https://bodhi.stg.fedoraproject.org/docs.

I think we can close this issue.
