### ISSUE TITLE
Indicate that comments can be added after logging in

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#3260]
Now that bodhi doesn't support anonymous comment, the page looks quite blank when unauthenticated and nothing tells users that they can submit feedback after they log in.

![bodhi](https://user-images.githubusercontent.com/755451/58541493-e9c09e80-81fb-11e9-881b-b6cc4e2a934c.png)

Please add some visible hint that you can add feedback/karma/comment after logging in.

**Comment by bowlofeggs** [comment]
Fixed in #3273.
