### ISSUE TITLE
add build completion to buildroot override add

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#327]
From: https://fedorahosted.org/bodhi/ticket/788

"Small regression in Bodhi 2.0: builds completion fails to work in the override page.

I tried to submit an override for qpid-cpp-0.32-8.fc23 (due to boost rebuild induced ABI break), and it failed in both discovering the name of the source package and the nvr."

**Comment by ralphbean** [comment]
I guess I'm not sure if this is a client side (javascript) issue, where the build field should autocomplete with suggestions as you type stuff in.. or if it's a server-side (python) issue, where you could submit a portion of an nvr and the server would just figure out the right thing to do.  Can someone familiar with it fill me in more precisely on what bodhi1 did?

**Comment by hguemar** [comment]
Since it's a part of Bodhi, I wasn't using that often, my memory could trick me. But if I remember well, it was supposed to provide suggestions as you type stuff in so it should be a javascript issue.

**Comment by ralphbean** [comment]
Thanks for the clarification.  This can probably be done without too much work.
