### ISSUE TITLE
RSS feed gives no information about packages build

### ISSUE THREAD

**Issue by pmca31** [fedora-infra/bodhi#3272]
Since commit 60dc56c that RSS feed doesn't give information about the packages affected in a build.
Example from [Fedora30 Stable - RSS](https://bodhi.fedoraproject.org/rss/updates/?releases=F30&status=stable) :
```xml
<item>
  <title>FEDORA-2019-59d394e0fd</title>
  <link>https://bodhi.fedoraproject.org/updates/createrepo_c-0.14.1-1.fc30</link>
  <description>- Update to 0.14.1
- Add --pkgorigins mode for Koji
- Correct pkg count in headers if there were invalid pkgs (RhBug:1596211)
- Prevent exiting with 0 if errors occur while finalizing repodata.
  </description>
  <pubDate>Fri, 24 May 2019 12:20:49 +0000</pubDate>
</item>
```

Also the link is invalid as in #3248

Looking to the [Fedora30 Stable - Web UI](https://bodhi.fedoraproject.org/updates/?releases=F30&status=stable) it seems that it should be:
```
  <title>createrepo_c-0.14.1-1.fc30</title>
  <link>https://bodhi.fedoraproject.org/updates/FEDORA-2019-59d394e0fd</link>
```

**Comment by didierm** [comment]
No offense intended, but : how [High Priority] or [EasyFix] is this issue ?
RSS feeds have been unreadable for the past few months : 

 ![image](https://user-images.githubusercontent.com/989004/63118970-53e91400-bf9f-11e9-8b2b-c218d5de7c56.png)

**Comment by szpak** [comment]
I've run into the same issue:
https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/XHRKAAUKBFFU5LXAJ54VI7AG633SGDMV/

Very often It's really hard to determine without clicking a link which package it is all about.

**Comment by didierm** [comment]
Feed : https://bodhi.fedoraproject.org/rss/updates/?release=F30&type=newpackage
![image](https://user-images.githubusercontent.com/989004/63879660-72ea9b80-c9cc-11e9-93d7-795675fb84d6.png)

What kind of information is supposed to be provided here ?
The non-descriptive titles (_"FEDORA-2019-e4e24c3776"_), together with the generic descriptions (_"Initial package"_) have been rendering the feeds next to useless ...
