### ISSUE TITLE
Bug in caching repodata for EL5 & EL6

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#328]
We're hitting this traceback in production when trying to cache the repodata of EL6 & EL5 (not EL7 or Fedora). The contents of that directory are `/mnt/koji/mash/updates/dist-6E-epel-150822.1734/../dist-6E-epel.repocache/repodata/.nfs0000000007d203a900000196`. We think it might be related to the fact that we're still using bzip2 compression for that repodata. Could be a bug in createrepo_c or bzip2? 

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 252, in run
self.work()
File "/usr/lib/python2.7/site-packages/bodhi/masher.py", line 327, in work
uinfo.cache_repodata()
File "/usr/lib/python2.7/site-packages/bodhi/metadata.py", line 323, in cache_repodata
shutil.rmtree(cache)
File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/mnt/koji/mash/updates/dist-6E-epel-testing-150822.1930/../dist-6E-epel-testing.repocache/repodata/'
```

**Comment by lmacken** [comment]
We hit this with EL7 tonight as well, so I don't think it's related to Bzip2...

**Comment by nirik** [comment]
The file seems to be the updateinfo.xml.bz2 fiile. It's being held open by the fedmsg-hub process. (so, restarting fedmsg-hub makes the file go away). 

Looking at the fedmsg-hub process: 

# ls -la /proc/29522/fd | grep epel7
l-wx------. 1 masher masher 64 Sep 14 18:57 437 -> /mnt/fedora_koji/koji/mash/updates/epel7-150914.1814/epel7/x86_64/repodata/6822870af83ae6bcdbfeded540fb33c3c5f8a5dcd3c16d283f3d7dc4ad351b32-updateinfo.xml.bz2
lr-x------. 1 masher masher 64 Sep 14 18:57 67 -> /mnt/fedora_koji/koji/mash/updates/epel7.repocache/repodata/.nfs00000000057b4bfe00000406
l-wx------. 1 masher masher 64 Sep 14 18:57 93 -> /mnt/fedora_koji/koji/mash/updates/epel7-150914.1814/epel7/SRPMS/repodata/6822870af83ae6bcdbfeded540fb33c3c5f8a5dcd3c16d283f3d7dc4ad351b32-updateinfo.xml.bz2
l-wx------. 1 masher masher 64 Sep 14 18:57 97 -> /mnt/fedora_koji/koji/mash/updates/epel7-150914.1814/epel7/ppc64/repodata/6822870af83ae6bcdbfeded540fb33c3c5f8a5dcd3c16d283f3d7dc4ad351b32-updateinfo.xml.bz2

It seems like a race condition where it sometimes tries to remove the file before it's done writing it?

**Comment by bowlofeggs** [comment]
This ended up being a bug in createrepo_c that @puiterwijk fixed upstream.

https://github.com/rpm-software-management/createrepo_c/pull/66
