### ISSUE TITLE
Add ability to re-run OpenQA tests on an Update

### ISSUE THREAD

**Issue by tdawson** [fedora-infra/bodhi#3284]
A user may want to re-run the Bodhi Update tests.  OpenQA is one of the places that the tests are run.  There is currently nothing in bodhi that allows OpenQA tests to be re-run.  Implement an API to allow an update's OpenQA tests to be re-run.
Minimum - re-run all the tests.
Ideal - Have an option to re-run all tests, or just specific tests.

**Comment by tdawson** [comment]
A preliminary investigation has already been done concerning this.  For more details on who to contact, and possible ways to implement this, please see issue #2323

**Comment by Zlopez** [comment]
This is a part of https://github.com/fedora-infra/bodhi/issues/3288 and https://github.com/fedora-infra/bodhi/issues/3287 now. So I'm closing this.
