### ISSUE TITLE
Add ability to re-run Taskotron tests on an Update

### ISSUE THREAD

**Issue by tdawson** [fedora-infra/bodhi#3286]
A user may want to re-run the Bodhi Update tests. Taskotron is one of the places that the tests are run. There is currently nothing in bodhi that allows Taskotron tests to be re-run. Implement an API to allow an update's Taskotron tests to be re-run.
Minimum - re-run all the tests.
Ideal - Have an option to re-run all tests, or just specific tests.

**Comment by tdawson** [comment]
A preliminary investigation has already been done concerning this.  For more details on who to contact, and possible ways to implement this, please see issue #2323

**Comment by pypingou** [comment]
Considering that taskotron is going away, I am not sure we should invest much time in this

**Comment by Zlopez** [comment]
This is a part of https://github.com/fedora-infra/bodhi/issues/3288 and https://github.com/fedora-infra/bodhi/issues/3287 now. So I'm closing this.
