### ISSUE TITLE
Users should be able to re-run update tests with the Web UI

### ISSUE THREAD

**Issue by tdawson** [fedora-infra/bodhi#3287]
User should be able to re-run update tests in the web interface.
Very Minimal - All tests are re-run
Minimal - A user can choose to re-run all OpenQA, or Fedora-CI, or Taskatron tasks.
Ideal - A user can choose to either run all tests, or choose which individual tests to run.

**Comment by tdawson** [comment]
A preliminary investigation has already been done concerning this. For more details on who to contact, and possible ways to implement this, please see issue #2323

The proper API's need to be in place before we can implement this.  The cannot be implemented until the OpenQA (#3284 ) Fedora-CI (#3285 ) and/or Taskotron (#3286 ) API's are implemented.    It is probably possible to implement this after just one of these API's is implemented, but not before.

**Comment by mattiaverga** [comment]
This should now be possible with Bodhi 5.7.1
