### ISSUE TITLE
Bodhi's docs don't build with Sphinx 2.1.0

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3300]
Due to https://github.com/Cornices/cornice.ext.sphinx/issues/22 our autogenerated REST API docs won't build with Sphinx 2.1.0. I plan to pin us to Sphinx < 2.1 temporarily so that our pip CI tests will unblock our PRs, but we are going to have to solve this problem because eventually Rawhide is going to get that version of Sphinx and then we'll be in trouble.

Here are a few options we could consider:

0. Fix ```cornice_sphinx```. I have contributed a few patches before. I'm not sure how involved this fix will be.
1. Switch to Django - there are a lot of benefits to doing this, but it is also a lot of work and we don't likely have the time to do it before Rawhide gets the new Sphinx (or before F31 is branched).
2. Hand write our docs instead. We could use https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/ to assist in formatting, and we could also put the docs in-line in the Python service files. This would be a lot of work up front, and would also require us to maintain them as we change the API (which is why keeping them in-line in the Python code would be wise - that way we are more likely to remember to adjust them.)

Other ideas welcome.

**Comment by mattiaverga** [comment]
This has been fixed, I forgot to close
