### ISSUE TITLE
The automatic update handler will cause Nackloops

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3306]
Similar to https://github.com/fedora-infra/bodhi/issues/3302, the automatic update handler will lead to Nackloops if it receives misformatted messages, or messages referencing data it does not know about. It raises Exceptions in a number of cases, which will cause the message to be placed back on the queue.

Exceptions should only be raised on temporary failures (think things like network problems connecting to Koji) and not permanent failures (think things like not being able to find a build in Koji or Bodhi's DB).

This is critical because it can cause Bodhi's queue to become full of messages with permanent errors, which will stop it from being able to process messages.

**Comment by cverna** [comment]
@nphilipp can you take a look at this issue :smiley:

**Comment by nphilipp** [comment]
Proposed fix in PR #3319.
