### ISSUE TITLE
search header section is bigger in size and overlapps top information of update

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#334]
![bodhi2-header-section](https://cloud.githubusercontent.com/assets/671366/9435411/2d14682e-4a65-11e5-9601-3bcd48c2222b.png)

Here I see search header took more space and hide the initial top information of an update.

**Comment by ralphbean** [comment]
As in #333, your browser just has the old CSS assets cached.  Give the page a hard reload and it should work.

**Comment by pnemade** [comment]
Thanks that worked.
