### ISSUE TITLE
Convert the testcases to PyTest

### ISSUE THREAD

**Issue by abompard** [fedora-infra/bodhi#3357]
Some testcase classes, for example in `bodhi/tests/server/test_util.py`, derive from `unittest.TestCase`. We use pytest, so they could be migrated to derive from `bodhi.tests.server.base.BaseTestCase`. That would allow us to use the simpler `assert` constructs instead of the `self.assert*()` methods.

**Comment by mm-git01** [comment]
Has this been resolved ? can i take this ?

**Comment by pypingou** [comment]
It has not and it is not a small task so feel free to one file at a time and submit PR as you go :)

**Comment by mm-git01** [comment]
> It has not and it is not a small task so feel free to one file at a time and submit PR as you go :)

cool,will do it. Btw i was pointed to bodhi by vipul-siddhart. I have been a fedora contributor for almost a year+ now and was a google summer of code intern this year with fedora. Want to do more infra work moving forward.

**Comment by mm-git01** [comment]
i took a look at the code today,this is definitely gonna take some time.I'll push thing one by one as they are done.

**Comment by Navneet78** [comment]
Hello I am new here. It would be my first PR can I do this?

**Comment by mm-git01** [comment]
> Hello I am new here. It would be my first PR can I do this?

hey,i am kinda working on this rn. Since this is your first PR and pretty easy,you can take this :smile: 

@pypingou can you please point me to some other issue that i can look into that needs to be fixed.

**Comment by Navneet78** [comment]
Thank you @Pac23

**Comment by ryanlerch** [comment]
@Pac23 @Navneet78 I have started creating a little project for this issue, breaking down each file that needs to be changed into it's own issue.

Feel free to check out the project here, and grab one of these if you are still interested:

https://github.com/fedora-infra/bodhi/projects/7

**Comment by nphilipp** [comment]
@abompard @ryanlerch 

BTW, `bodhi.tests.server.base.BaseTestCase` is the legacy class derived from `unittest.TestCase`, we want stuff to be converted over to `BasePyTestCase` instead—both these classes incorporate `BaseTestCaseMixin` which contains the meat, i.e. the database session with test data in it, and the WSGI TestApp where we can test exposed web API. At some point, when everything has been migrated away from `unittest.TestCase`, we can get rid of `BaseTestCase` and migrate the mixin into `BasePyTestCase`.

**Comment by nphilipp** [comment]
@abompard @ryanlerch 

And BTW², only test classes previously derived from `BaseTestCase`, i.e. which need the infrastructure (populated DB, test WSGI app), should be migrated over to `BasePyTestCase`. Test classes which are directly derived from `unittest.TestCase` should simply not derive from that and be ported over to the PyTest class API (e.g. `setup_method()` rather than `setUp()` and so forth).

**Comment by nphilipp** [comment]
@abompard @ryanlerch, I've noticed that we didn't capture all instances of tests using `unittest.TestCase`, probably because the affected classes are derived from `BaseTestCase` and thus didn't show up when grepping for it. I'll file additional issues soon.
