### ISSUE TITLE
Unpushing updates should need confirmation.

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/bodhi#3358]
I just inadvertently [unpushed an update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-6817686c4d#comment-966018) because I missed the border of a window I wanted to resize by a few pixels. It wasn't even my update but I just happen to be a provenpackager and what's worse, it was requested for stable before and wouldn't let me request that again (not sure if this is an issue, probably rather something with how the permissions for provenpackagers are set up in the Bodhi prod instance). Because unpushing is a relatively uncommon operation, the web UI should probably ask the user for confirmation to avoid snags like this.

**Comment by mattiaverga** [comment]
A really simple javascript should be enough.
I'll do it in no time.
