### ISSUE TITLE
Do not send multiple notifications due to BZ ticket updates

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#336]
When my update was pushed into stable, I received two notifications from BZ [1], one with comment and second with remaining flags modified. Is there chance to do this in one action, preventing BZ to send multiple emails?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1253872

**Comment by voxik** [comment]
Just FYI, it used to be done in one step:

https://bugzilla.redhat.com/show_bug.cgi?id=1227779#c16

**Comment by ralphbean** [comment]
:+1: probably possible.  Will just need to change the ``bodhi.bugtracker`` object's behavior.  Sorry for the noise!

**Comment by bowlofeggs** [comment]
A fix for this issue is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
The patch for this issue was deployed to Fedora's production Bodhi instance yesterday.
