### ISSUE TITLE
Update pending is not visible on main page

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/bodhi#3366]
Currently in staging there is one update for rawhide that is now pending  (see https://bodhi.stg.fedoraproject.org/updates/?releases=f31&status=pending), but on the main page the total number is 0 (https://bodhi.stg.fedoraproject.org/).

**Comment by Zlopez** [comment]
I tried to play a little more with this issue and it's strange, when I'm refreshing the page I'm getting different results. 

One time is showing correct number, than I do a refresh and it's showing 0.

I also noticed, that this update is not shown in any category bellow the total number.

Here is the id of the update: https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-f7a7a6c4ac

**Comment by sebwoj** [comment]
Now, I see opposite situation.
[Bodhi](https://bodhi.fedoraproject.org/) on the main page shows 1 update in "Fedora 31 prerelease", but page [https://bodhi.fedoraproject.org/updates/?releases=F31&status=pending](https://bodhi.fedoraproject.org/updates/?releases=F31&status=pending) is showing 0 updates.

**Comment by sebwoj** [comment]
I found the reason.
Method responsible for generating home page stats is cached:
https://github.com/fedora-infra/bodhi/blob/3985832112ae06bc75e16d8b851d5b455aebac8a/bodhi/server/__init__.py#L321

In case of vagrant dev environment, cache timeout is set to 1H:
https://github.com/fedora-infra/bodhi/blob/3985832112ae06bc75e16d8b851d5b455aebac8a/devel/development.ini.example#L11

@Zlopez Do you think that we should decrease this value in production/staging?

**Comment by Zlopez** [comment]
I'm not sure if this should be cached at all.

**Comment by bowlofeggs** [comment]
It's cached because it takes a long time to generate the data, and the data does not need to be current. I think we should close this issue.
