### ISSUE TITLE
Bodhi should push automatically created updates to -pending on successful Greenwave gating

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/bodhi#3367]
Currently, automatically created updates for Rawhide get created with a pending request for testing. The builds are stuck in the candidate tag of the release.

We want Bodhi to move them forward to ~~testing~~ stable (`*-updates-candidate` → `*-pending` tags in Rawhide) when Greenwave tests pass. For this, the Greenwave consumer should set the update status to ~~`testing`~~ `stable`, unset its request and tag the builds accordingly with the ~~testing~~ stable tag of the release (which should be set to e.g. `f31-pending` for Rawhide).

We want this if the following is true:

* The release is a pre-release.
* The update's minimum time spent in testing is zero (`Update.stable`).

**Comment by nphilipp** [comment]
@pypingou @abompard I've updated the description to reflect that we want to go to stable directly. Please give it a lookover if I got it right :wink:.

**Comment by pypingou** [comment]
I think we still want to the move from ``*-updates-candidate`` → ``*-pending`` but according to @cverna using the code in that cron job (``approve_testing``) will give it to us for free :)

**Comment by pypingou** [comment]
This is now working as desired in staging.

It's even directly pushing the update to the stable_tag :)
