### ISSUE TITLE
Updating an issue to add more BZ #'s fails

### ISSUE THREAD

**Issue by sgallagher** [fedora-infra/bodhi#337]
I attempted to edit FEDORA-2015-13283 to add BZ #1239090. The new BZ was not added, but Bodhi 2 reported that my user had resubmitted the update for testing (which it shouldn't do on just a BZ addition anyway)

**Comment by siwinski** [comment]
I had this same issue.  I updated a few updates with new BZ #'s and my updates were resubmitted for testing so the "time in testing" got reset on my security release updates :(  The new BZ # was added to my updates though.

**Comment by lmacken** [comment]
Hmm, I can't reproduce this issue in the test suite. Are you folks still hitting this with the latest version in production?

**Comment by sgallagher** [comment]
In my case, I did not create the original update. That likely played a part. I was updating someone else's errata using my provenpackager privileges.

**Comment by siwinski** [comment]
I just re-tested and this does not appear to be an issue for me anymore.

**Comment by lmacken** [comment]
I believe this issue has been resolved. Please re-open this issue if you still experience this behavior.
