### ISSUE TITLE
Cannot search packages

### ISSUE THREAD

**Issue by Germano0** [fedora-infra/bodhi#338]
In new https://bodhi.fedoraproject.org/updates/ is no longer possible to search packages in search field

**Comment by ralphbean** [comment]
We can probably add this to the JS search box.

In the meantime, you can use a URL like this to get at the information you need:

https://bodhi.fedoraproject.org/updates/?packages=imapsync

* note, that's a package name in the URL.

**Comment by lmacken** [comment]
https://bodhi.fedoraproject.org/updates/imapsync works as well

**Comment by ralphbean** [comment]
Nice, yeah!

To implement this in the JS searchbox in the header, we'll need to add a new cornice service which can search for package names.. it doesn't need an HTML UI, but we can use the data in the search box to then redirect user to the URLs mentioned aboved.

**Comment by bowlofeggs** [comment]
We do seem to have the JS searchbox that I think @ralphbean was talking about implemented now - if you type bodhi but don't hit enter, you will see both bodhi updates but also a bodhi package appear in the search box dropdown. You can also search for users like this.

**Comment by ralphbean** [comment]
\ó/
