### ISSUE TITLE
Search doesn't work in WebKit browsers

### ISSUE THREAD

**Issue by contyk** [fedora-infra/bodhi#340]
The dropdown thingy with results never appears in WebKit-based browsers and pressing Enter just refreshes the notifications feed. The search feature is simply unavailable.

Neither webkitgtk (tested with midori and jumanji) nor webkitgtk3 (epiphany/web, the default Fedora desktop browser) work.

**Comment by ralphbean** [comment]
Thanks for reporting!  We'll look into it.

**Comment by mcatanzaro** [comment]
This is definitely fixed now, not sure if by a change in bodhi or a change in WebKit. Yay!

**Comment by ralphbean** [comment]
Cool!  We didn't change anything here, so it must've been something shifting in WebKit.  Glad to hear it!

**Comment by mcatanzaro** [comment]
Broken again in WebKit trunk:

![screenshot from 2016-01-30 20-12-11](https://cloud.githubusercontent.com/assets/1424966/12699791/5027079e-c78e-11e5-9cf1-1f7f472515e4.png)

It's working in WebKitGTK+ 2.10.4, but I don't know why.

**Comment by mcatanzaro** [comment]
Finally fixed: https://bugs.webkit.org/show_bug.cgi?id=165804
