### ISSUE TITLE
[s] Fix comment order: https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-a0e3451113

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3401]
The comment that the update was created automatically appears after the comments generated by checking greenwave.

**Comment by nphilipp** [comment]
See https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-a0e3451113:
![Screenshot from 2019-07-18 10-27-04](https://user-images.githubusercontent.com/820624/61441865-c5a15400-a946-11e9-9095-639caba1df3c.png)
