### ISSUE TITLE
Automatic rawhide updates should not list karma limits

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3424]
I think that the highlighted part of an update overview page should not be visible in an automated rawhide update:

![_](https://user-images.githubusercontent.com/2401856/61891933-0b43bb00-af0b-11e9-945a-6dd758c61d58.png)

**Comment by cverna** [comment]
@hroncok karma is actually valid on updates created by rawhide. So if an update gets a -1 karma it would block the update from being pushed to stable.

Apart from being automatically created the updates in rawhide are exactly the same as the one in a stable release.

**Comment by hroncok** [comment]
So before the tests finish, users have a chance to quickly do -3 karma? Is that really possible?

**Comment by hroncok** [comment]
Oh, sorry, they can do a quick -1 to block it and than extra -2 unpushes it?

**Comment by hroncok** [comment]
Does +3 override the test failure?

**Comment by cverna** [comment]
> Does +3 override the test failure?

If gating is enabled on the release then no, the update would still be blocked by the failing tests.

**Comment by hroncok** [comment]
It just feels that the autokarma thing is not relevant then. What am I missing?

**Comment by cverna** [comment]
> It just feels that the autokarma thing is not relevant then. What am I missing?

Yes I don't think anyone will use karma on any rawhide update. What could be easily done is to disable autokarma on the rawhide update but you would still see the karma bits in the update view. Just the `Autopush (karma)` bit would be showing `disabled` instead of `enabled.
