### ISSUE TITLE
Greenwave consumer should not process the compose results

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3425]
Currently the greenwave consumer consumes all the messages from `topic=org.fedoraproject.prod.greenwave.decision.update` but some messages on this topic are related to compose results and not koji build.

The consumer should filter the messages based on the `subject_type`, and only process `koji_build` type.

See a koji_build example https://apps.fedoraproject.org/datagrepper/id?id=2019-efb310ed-6acf-4742-809f-90a40c2a5855&is_raw=true&size=extra-large

And a compose example https://apps.fedoraproject.org/datagrepper/id?id=2019-33002e05-241c-4180-8953-5a29cea4443d&is_raw=true&size=extra-large

This is currently raising the following exception in production : 
``` 2019-07-26 15:16:55,501 ERROR [bodhi.server][PoolThread-twisted.internet.reactor-0] Bodhi failed to send POST request to Greenwave at the following URL "https://greenwave-web-greenwave.app.os.fedoraproject.org/api/v1.0/decision". The status code was "502". The error was "{'message': 'Failed to retrieve SCM URL from Koji build "Fedora-Workstation-Rawhide-20190726.n.0" at "https://koji.fedoraproject.org/kojihub" (expected SCM URL in "source" attribute)'}". ```

**Comment by pypingou** [comment]
Definitely :+1:  on the idea
We may need to be careful (ie: double-check) on the impact this may have. It seems it is still not 100% clear if some fields are required or not, cf:
- https://src.fedoraproject.org/rpms/python-virtualenv/pull-request/10
- https://pagure.io/fedora-ci/docs/issue/30
