### ISSUE TITLE
Rawhide updates ruining the bodhi.fedoraproject.org/users/<me> experience

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3429]
I was using https://bodhi.fedoraproject.org/users/churchyard to see my recent updates and check whether they are still in testing.

Since I don't usually have more than 10 updates in testing at the same time, the page was perfect.

However I do dozens (hundreds?) rawhide builds a week and now rawhide updates are swamping the page, making it essentially useless for me.

I'd appreciate, if I could hide the rawhide updates (maybe via an URL argument, such as `?release=!F31`). Thanks.

**Comment by cverna** [comment]
Does https://bodhi.fedoraproject.org/updates/?user=churchyard&status=testing works for you ? Rawhide update will not stay long in testing unless the tests are failing.

**Comment by hroncok** [comment]
Can I see testing + pending?

**Comment by hroncok** [comment]
Also, this doesn't list the buildroot overrides at all, so from one simple dashboard page, I would need to use more.

**Comment by cverna** [comment]
Ok then I guess we need some way to filter the updates per releases. Currently you can do something like that https://bodhi.fedoraproject.org/updates/?user=churchyard&release=F30 but it seems limited to one release.

**Comment by ryanlerch** [comment]
> Can I see testing + pending?

Just opened up #3463  that lets you specify multiple status params in the updates query, so it will let you do testing + pending.

The same code that renders the /updates/ page is used to render the update list on the user profile page, so what i am thinking here is to add a new box at the top that shows just the pending and testing updates. (perhaps only showing this box if the user page is your page too maybe)

Filtering by if it is an auto update or not could be problematic if one of your auto updates doo get stuck in pending or testing, you probably still want to know about that.

**Comment by hroncok** [comment]
> Filtering by if it is an auto update or not could be problematic if one of your auto updates doo get stuck in pending or testing, you probably still want to know about that.

I think you are right here. Thanks!

**Comment by ryanlerch** [comment]
The new dashboard view now shows your pending and testing updates on the index (when logged in)

![screencapture-0-0-0-0-6543-2019-09-12-15_58_29](https://user-images.githubusercontent.com/592259/64757812-79554780-d576-11e9-90cf-98c36881c2a9.png)

#3500 is in develop branch now.

going to close this one, feel free to re-open if this doesnt meet your expectaions, @hroncok

**Comment by hroncok** [comment]
Looks awesome!
