### ISSUE TITLE
Create a new Update status : Stable not tested

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3442]
This is a proposal to create a new Update status "Stable not tested" (or something better ) to help identify which update were pushed to stable without having any tests run against.

**Comment by pypingou** [comment]
I do wonder if we don't already have this via the ci_status "ignored".

**Comment by cverna** [comment]
Yes we do, but the status that is displayed on the UI is the Update Status (Pending, Testing, Stable, Obsolete, ...). I was thinking that adding an extra status would make it easier to display that on the UI, ie we just add a new color for the Stable not tested status.

Happy to have other suggestions :-)

**Comment by pypingou** [comment]
Is this information really useful for the users. If it's only a question of knowing how much gating is used and its effect, we could gather this info outside of bodhi itself no?

**Comment by cverna** [comment]
> Is this information really useful for the users. If it's only a question of knowing how much gating is used and its effect, we could gather this info outside of bodhi itself no?

I would say that this is more a nice to have thing for the users rather than must have, but I can see value in quickly knowing which update were not tested by CI in the release view for example (https://bodhi.fedoraproject.org/releases/F31).
Also this might bring an extra motivation for maintainers to adopt tests, since there update status will be different than ohters.

Thinking about it how would the ci_status "ignored" work for multi build updates ?

**Comment by pypingou** [comment]
> Thinking about it how would the ci_status "ignored" work for multi build updates ?

Good question, we really have still a lot to figure out for mult-builds :(

**Comment by nphilipp** [comment]
To me it looks like this doesn't need a new update status if we know the information from ci_status already. Wouldn't it be enough if we displayed this information in the CLI/UI?

**Comment by cverna** [comment]
> To me it looks like this doesn't need a new update status if we know the information from ci_status already. Wouldn't it be enough if we displayed this information in the CLI/UI?

It would be a solution but involves a lot more UI work (creating a new column to display that info). While I believe that just adding a new status makes the change simpler. (https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/util.py#L572)

**Comment by pypingou** [comment]
A new column? I'm not quite following you there.

If we count the number of update by CI status, it's just a few more rows on the left side of the release overview page: https://bodhi.fedoraproject.org/releases/F31 .
In the update view that information is already there: https://bodhi.fedoraproject.org/updates/FEDORA-2019-dadb07e23b .

**Comment by cverna** [comment]
> A new column? I'm not quite following you there.

I was looking at these views
https://bodhi.fedoraproject.org/updates/?releases=F31
https://bodhi.fedoraproject.org/users/cverna

The quick to have this is to create the new status and have a different color on the UI for that status. So Green means stable with test and for example Purple means stable without tests.

> 
> If we count the number of update by CI status, it's just a few more rows on the left side of the release overview page: https://bodhi.fedoraproject.org/releases/F31 .
> In the update view that information is already there: https://bodhi.fedoraproject.org/updates/FEDORA-2019-dadb07e23b .

Are you referring to the Gating status part ? if yes I think this is currently just displaying the summary of the greenwave decision. So we don't know if this is green because all tests passed or because there was no tests.

**Comment by cverna** [comment]
I have opened https://github.com/fedora-infra/bodhi/pull/3458 that will give us the ci status `passed` and `ignored` on the release overview.

It is also adding the possibility to filter updates by ci status.

**Comment by cverna** [comment]
https://github.com/fedora-infra/bodhi/pull/3458 merged
