### ISSUE TITLE
Builds coming from the releng user should not create updates in rawhide.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3445]
The releng user is used to create composes in koji. The koji builds are tagged with the f31-updates-candidate tag which makes bodhi create updates for it.

The automatic update consumer needs to check if the build comes from the `releng` user and ignore it.

@mohanboddu and @nirik also think that the build should be tagged directly to f31.

**Comment by nphilipp** [comment]
This should be easy enough to do. Do we usually hardcode stuff like this, or do we add a configuration option?

**Comment by cverna** [comment]
The problem I see is tagging the build with f31. As far as I know Bodhi currently only have the code to tag builds that are within an update which would not be the case here.

**Comment by pypingou** [comment]
I'm a bit curious why we want to do this in F31 while we did not in F30

@mohanboddu @nirik any thoughts?

**Comment by cverna** [comment]
For the koji garbage collection, I think @mohanboddu and @nirik were looking at why F30 builds are not tagged in F30.

**Comment by nirik** [comment]
It might be we can just leave them where they land, but we need to make sure koji-gc does the right thing with them. ie, we want to keep ones that are used in places we distribute (releases, etc). 

Note that ignoring releng builds would fix also the issue of bodhi in rawhide trying to file updates for image builds (which fails in a traceback currently).

**Comment by ryanlerch** [comment]
is the releng user also used for mass rebuilds? 

or are these usally done in side-tags, so wont be an automated update?

**Comment by cverna** [comment]
> is the releng user also used for mass rebuilds?

Correct

> 
> or are these usally done in side-tags, so wont be an automated update?

Yes the builds are done in a side tag, I think the current plan is to keep mass rebuild out of bodhi scope.
