### ISSUE TITLE
Do not allow buildroot override in rawhide

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3447]
If the user creates a buildroot override in rawhide it ends up messing with our entire workflow. The builds are no longer in their appropriate tags, they appear in bodhi's database but aren't linked to any update (cf PR: #3446) that leads to basically builds being stuck.

Preventing buildroot override creation in rawhide should just solve that :)

**Comment by cverna** [comment]
One possible easy way to do this is to not configure the override tag for the rawhide release.

**Comment by pypingou** [comment]
Wfm, we just need to document this enough to make sure we don't miss it at branching
