### ISSUE TITLE
Please do not call rawhide “stable”

### ISSUE THREAD

**Issue by fweimer** [fedora-infra/bodhi#3452]
For me, this is very confusing because of my Debian background. The Debian releases are called “stable”. I expect I'm not alone in this.

**Comment by cverna** [comment]
For Bodhi, rawhide is not really different from any other release ( ie using the pending, testing and stable state for an update). Changing this behavior in my opinion will require quite some work, and I am not sure that this is worth the effort.

Is that something you can leave with ? Also the goal of having rawhide in Bodhi is to make rawhide more and more stable :smile:

**Comment by fweimer** [comment]
Fair enough. In the end, it would probably help more to have some indication where the update will show up (which tags, buildroots and composes) and how far things has progressed getting there.
