### ISSUE TITLE
The F29 update was moved to stable without explicit request

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/bodhi#3454]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-f9dd0d1bbd

**Comment by cverna** [comment]
@praiskup yes this is the new default see the first item of the Features in the release notes (https://github.com/fedora-infra/bodhi/releases/tag/4.1.0).

**Comment by praiskup** [comment]
Ah, interesting, but I had to submit manually this one: https://bodhi.fedoraproject.org/updates/FEDORA-2019-c5df969648 (it really was weird that F29 got pushed before F30).  Nevermind, thanks.

**Comment by cverna** [comment]
It all depends when the update was created, if it was before bodhi 4.1 was deployed then you still need to push manually.
