### ISSUE TITLE
Disallow empty checkboxes in the new update form

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#347]
![screenshot from 2015-08-24 17-45-07](https://cloud.githubusercontent.com/assets/9980/9455383/02fa07c4-4a88-11e5-910d-34b75b75ee14.png)

**Comment by jwboyer** [comment]
I saw this quite a bit yesterday while I was trying to add bugs to an update edit.  Doing a shift-reload cleared whatever weird state Chrome had cached, but it was frustrating at the time.

**Comment by farhaanbukhsh** [comment]
I am new to Fedora community would like to take this bug and start contributing can you please me and guide me with this bug.

**Comment by ralphbean** [comment]
Hey @farhaanbukhsh, stop by ``#fedora-apps`` on freenode and ask for some direction.  First, you'll need to get the app up and running as in the README.  After you have it running, the change will need to be made in ``bodhi/static/js/update_form.js`` to ignore empty values like this.
