### ISSUE TITLE
Update without build can be created

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3471]
It appears that an update without build can be created (https://bodhi.fedoraproject.org/updates/FEDORA-2019-e4e61bb84b). 
We need to make sure that the validators are not letting an update without a build being created.

In that case the update made the compose failed.

**Comment by cverna** [comment]
This seems to happen if you create an update with build A, then create the another update with the same build.

**Comment by ryanlerch** [comment]
Related: #3495

**Comment by cverna** [comment]
This happened again today, some more info from the IRC log
```
15:37 <RemiFedora> cverna, bodhi hangs during the "submit" (btw, it have properly obsolete an old update)
15:37 <RemiFedora> so I press "submit" another time, and get the proper update, with the build (but without the changelog from the obsoleted one...)
```
It seems to happen when bodhi hangs, I guess that we could check if an update has a build before commiting to the db.

**Comment by mohanboddu** [comment]
I was supposed to comment here, but couldn't find the ticket:

https://github.com/fedora-infra/bodhi/issues/3495#issuecomment-543210296
