### ISSUE TITLE
Search button does nothing

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#3472]
Clicking the search icon does nothing; no bar is shown and there's no other way to search.

Using Firefox 66.0.5 on Fedora 30.

**Comment by QuLogic** [comment]
This seems to only be a problem when viewing an update. If on the homepage, then the button works.

But to be honest, why bother with the hidden search entry? It's bad UX to have hiding widgets like that, and it's not like there's no room on the header.

**Comment by ryanlerch** [comment]
> Clicking the search icon does nothing; no bar is shown and there's no other way to search.
> 
> Using Firefox 66.0.5 on Fedora 30.

This appears to be resolved in the develop branch, i think with the update to the newer bootstrap.
