### ISSUE TITLE
Bugs assigned to non-updated packages are closed

### ISSUE THREAD

**Issue by dwmw2** [fedora-infra/bodhi#3479]
I've just had to manually reopen https://bugzilla.redhat.com/show_bug.cgi?id=1701157 twice.
I pushed an update to NetworkManager-openconnect, but I also reassigned that bug to NetworkManager itself, because there is a bug there too that needs to be fixed before everything works.

Each time the NetworkManager-openconnect update got pushed to stable (for f29 and f30), the bug got closed despite not actually being assigned to the NetworkManager-openconnect package at the time.

Shouldn't the bug only get closed if it's actually assigned to the same package that's being updated?

**Comment by pypingou** [comment]
bodhi closes the bugs that it is instructed to close. Looking at: https://bodhi.fedoraproject.org/updates/FEDORA-2019-84bfd3d917 bug 1701157 is listed associated to this update. So when the update reaches stable bodhi closes the bug.

**Comment by dwmw2** [comment]
That makes some sense, I suppose. But I'd really like to be able to list bug 1701157 in the update without autoclosing it, since this update is a necessary *part* of the fix for that bug.

I suppose I could have refrained from enabling the autoclose feature, and manually closed the other bug on this occasion.

But *"don't close bugs assigned to a package other than the one being updated"* does seem like a sensible enough rule that would have avoided me having to do that, surely?

**Comment by pypingou** [comment]
> But "don't close bugs assigned to a package other than the one being updated" does seem like a sensible enough rule that would have avoided me having to do that, surely?

I can bet you $10 that if we do this, we'll have people opening tickets asking why we're not closing tickets that they listed as "to-be-closed" :)

Just take the example of updating the rpm: python3-foo while the component in bugzilla is named python-foo :)

**Comment by dwmw2** [comment]
Hah, fair enough. Although, that's insane.

Thanks.

**Comment by pypingou** [comment]
Note that I'm just one voice, more people may disagree w/ me and I'm not saying we couldn't change this behavior. I'm just feeling that if we do change it, there will be people complaining about it. 

If we believe that the gain is considered greater than the pain of dealing with these people, then we should do it :)
