### ISSUE TITLE
Unable to create a sidetag update: no release associated with build

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#3480]
When trying to create a new update based on a sidetag, it fails, with Bodhi unable to associate a release to the sidetag.

Specifically, the error is:

    Cannot find release associated with build: adwaita-blue-gtk-theme-3.22.21.0-10.fc30, tags: ['f30-build-side-7749']

This is being generated by https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/validators.py#L158

Also, note that the tests for using the `from_tag` field in  server/services/update.py 's new_update do work, but only because it is testing using a valid candidate tag which bodhi can determine a release for.

 Possibly related to: #3473

**Comment by nphilipp** [comment]
The Bodhi service (backend) could determine the release from a side tag like this:

If we can't figure out the release from the tag itself, ...

* check that the `from_tag` is a side tag (see the `extra` sub dict):

```
In [1]: import koji; koji_hub = 'https://koji.stg.fedoraproject.org/kojihub'; koji_client = koji.ClientSession(koji_hub, {})                                                                        

In [2]: koji_client.getTag('f31-build-side-7715')                                                                      
Out[2]: 
{'maven_support': False,
 'locked': False,
 'name': 'f31-build-side-7715',
 'extra': {'sidetag_user': 'nphilipp', 'sidetag': True, 'sidetag_user_id': 11},
 'perm': None,
 'perm_id': None,
 'arches': None,
 'maven_include_all': False,
 'id': 7715}
```

* get its ancestry

```
In [13]: koji_client.getFullInheritance('f31-build-side-7715')                                        
Out[13]: 
[{'intransitive': False,
  'name': 'f31-build',
  'pkg_filter': '',
  'priority': 0,
  'parent_id': 6448,
  'maxdepth': None,
  'noconfig': False,
  'child_id': 7715,
  'nextdepth': None,
  'filter': [],
  'currdepth': 1},
 {'intransitive': False,
  'name': 'f31-override',
  'pkg_filter': '',
  'priority': 0,
  'parent_id': 6447,
  'maxdepth': None,
  'noconfig': False,
  'child_id': 6448,
  'nextdepth': None,
  'filter': [],
  'currdepth': 2},
 {'intransitive': False,
  'name': 'f31-updates',
  'pkg_filter': '',
  'priority': 0,
  'parent_id': 6441,
  'maxdepth': None,
  'noconfig': False,
  'child_id': 6447,
  'nextdepth': None,
  'filter': [],
  'currdepth': 3},
 {'intransitive': False,
  'name': 'f31',
  'pkg_filter': '',
  'priority': 0,
  'parent_id': 6438,
  'maxdepth': None,
  'noconfig': False,
  'child_id': 6441,
  'nextdepth': None,
  'filter': [],
  'currdepth': 4}]
```

* try to match up the resulting parent tags with a release (that we store the different "roles" of tags in separate fields doesn't help here, but hey :wink:)

As I mentioned, in theory the tags of one release could have tags of an older release in their ancestry but we don't seem to be doing this (anymore? ISTR seeing tag ancestries spanning releases). To be safe we could limit ourselves to dig only so deep, i.e. 3 or 4 levels which would yield the `stable_tag` (`f31-updates`) or `dist_tag` (`f31`) of the `Release`, respectively.
