### ISSUE TITLE
Should we stop a user from creating two sidetag updates with the same sidetag

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#3484]
Currently, it is possible for a user to create two different updates from the same sidetag. This may be an edge-case, as if the builds are the same when creating the update, bodhi will not allow the update to be created, as the builds validator detects an update already has those builds.

However, it is possible if a user pushes new builds to a sidetag, to create a new update from the same sidetag.

The discussion here is should we update the validators to determine if any existing update has the same from_tag value, and block the update from being created?

**Comment by cverna** [comment]
I would say that if an update was already created with a side tag and a packager wants to change it then it should edit the existing update. So I think that not allowing creating multiple update from the same side tag seems to be a good idea.

tagging @hroncok to see his opinion.

**Comment by hroncok** [comment]
This is more an user story question. What is the idea behind side tag updates? Will pushing to stable close the side tag, etc.? Do we have a step by step user perspective of this?

**Comment by cverna** [comment]
@hroncok oh sorry for the lack of context. A side tag update is how we will do multi build updates in rawhide. The simplified workflow is here (https://pingou.fedorapeople.org/Simplified_multi_builds_update.jpg).

**Comment by hroncok** [comment]
That picture doesn't really give that much context :D 

This is what I usually do in side tag:

 1. request it
 1. build, build, build, build
 1. request it to be merged
 1. it is merged, nobody can build in it

In the bodhi world, I expect the following:

 1. request it
 1. build, build, build, build
 1. create a bodhi update with the entire side tag content
 1. update pushed, nobody can build in the side tag

If this is the expected usecase, the answer to "Should we stop a user from creating two sidetag updates with the same sidetag " is yes.

The better question IMHO is: "Should we allow an user from creating two (or more) updates from a sidetag without having all of the (most recent) builds from the side tag in that update" and a followup: "If a sidetag update exists and a new build happens in that side tag, should it be automatically added?" and if not: "Should side tag builds be allowed with pending updates, without explicit unpush of that update?"

**Comment by cverna** [comment]
> That picture doesn't really give that much context :D
> 
> This is what I usually do in side tag:
> 
>     1. request it
> 
>     2. build, build, build, build
> 
>     3. request it to be merged
> 
>     4. it is merged, nobody can build in it
> 
> 
> In the bodhi world, I expect the following:
> 
>     1. request it
> 
>     2. build, build, build, build
> 
>     3. create a bodhi update with the entire side tag content
> 
>     4. update pushed, nobody can build in the side tag
> 
> 
> If this is the expected usecase, the answer to "Should we stop a user from creating two sidetag updates with the same sidetag " is yes.

Yes that is the expected workflow.

> 
> The better question IMHO is: "Should we allow an user from creating two (or more) updates from a sidetag without having all of the (most recent) builds from the side tag in that update"

Hum yes that's a good point.

 and a followup: "If a sidetag update exists and a new build happens in that side tag, should it be automatically added?" and if not: "Should side tag builds be allowed with pending updates, without explicit unpush of that update?"

Yes also good questions, in the discussion we had we expect the packager to edit the update in the case where it is needed to add a new build to an already existing update.

tagging @pypingou so he is aware of the questions you have raised.

**Comment by hroncok** [comment]
I guess it is OK to require the packager to edit the update in order to add new builds. In that case please make it easy to add all new builds. My last side tag has something between 2000 and 3000 packages.

I think having a strict 1:1 relationship between a side tag an and update is the only reasonable way. Aka we don't want multiple updates from within one side tags and we don't want one update to contain builds from multiple side tags (that might work, but is very fragile IMHO).

**Comment by pypingou** [comment]
> I think having a strict 1:1 relationship between a side tag an and update is the only reasonable way. Aka we don't want multiple updates from within one side tags and we don't want one update to contain builds from multiple side tags (that might work, but is very fragile IMHO).

:+1:

**Comment by pypingou** [comment]
> If a sidetag update exists and a new build happens in that side tag, should it be automatically added?

So far we were thinking: "No but it would prevent the side-tag from being merged (since not all builds are in the update and thus not all builds have been tested"

> Should side tag builds be allowed with pending updates, without explicit unpush of that update?

If we make sure to prevent merging side-tags where not all builds are included in the update, I think we don't need this extra step.
