### ISSUE TITLE
On update edit the "type" is lost

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#349]
When "edit" a submitted update, the Type is lost, need to be check again.

Notice: the error message is not really clear: "required"

**Comment by ralphbean** [comment]
I'm unable to duplicate this error.  @remicollet can you still get it to happen?

**Comment by lmacken** [comment]
Which update were you dealing with when you hit this issue?

**Comment by remicollet** [comment]
Yes, I can reproduce, but I think it only occurs with "new package", I cannot reproduce with standard update (bugfix or enhancement)

**Comment by lmacken** [comment]
Oh, I think we've discovered an inconsistency with 'new package' vs. 'newpackage' in various parts of the code. Working on a potential fix :)

**Comment by lmacken** [comment]
Will close this once the fix is in production.

**Comment by lmacken** [comment]
Okay, this issue should hopefully be resolved.
