### ISSUE TITLE
Prevent user to create an update from a tag that is not a side tag.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3492]
Currently when we validate the tag given to the --from-tag flag we do not check if this tag is a side tag or not. Which means that in theory we could create an update with all the build in the f30 or f31 tag. 

We need to make sure that the tag given in the --from-tag is a side tag before processing the request.

**Comment by ryanlerch** [comment]
Just a heads up to anyone implementing this, there is already a function at https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/views/generic.py#L156 that gets sidetag info for the webUI if you want to have a look how that is done there.

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/bodhi/pull/3536
