### ISSUE TITLE
Karma limits reached too early after being reset

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#3493]
In [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-729bba50f9), karma was added as follows:
* -1
* "This update has been pushed to testing."
* "Bodhi is disabling automatic push to stable due to negative karma. The maintainer may push manually if they determine that the issue is not severe."
* +1
* New builds added; "Karma has been reset."
* "This update has been pushed to testing."
* +1 (repeat of the first +1)
* +1 (reverting the original -1)
* "This update can be pushed to stable now if the maintainer wishes"

The stable limits are 3, and there _are_ 3 +1's, but the first one was before the reset, so there should only be +2 karma. It also shows only +2 karma, and it's only been in testing 2 days, so that last comment should not have been made.

**Comment by karmadolkar** [comment]
It shows +3 karmas now, I think someone gave it a +1 karma after this issue came up. I guess it's already stable now (by the +3 karma criteria)? Is it a common problem in other "resetted" karma updates as well?

**Comment by cverna** [comment]
> It shows +3 karmas now, I think someone gave it a +1 karma after this issue came up. I guess it's already stable now (by the +3 karma criteria)? Is it a common problem in other "resetted" karma updates as well?

Yes I think there is a bug in the logic on how the karma is calculated for all Updates. I would start to look how at this method (https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L1980) and try to reproduce the issue either using a test or using the development environment.

**Comment by karmadolkar** [comment]
@cverna Could you please explain to me how I can reproduce the issue using a test or the development environment?

**Comment by cverna** [comment]
> @cverna Could you please explain to me how I can reproduce the issue using a test or the development environment?

Using the tests, I would look at making a new tests based on [this](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/test_models.py#L3063) and try to reproduce the comments from the update linked in the ticket.

You can run individual tests in the vagrant box using pytest, for example

```
pytest-3 bodhi/tests/server/test_models.py::TestUpdate::test__composite_karma_ignores_comments_before_new_build
```

That should allow you to iterate quickly

**Comment by mattiaverga** [comment]
@karmadolkar just a small hint: this issue has nothing to do with update's karma. The comment `This update can be pushed to stable now if the maintainer wishes` is made by Bodhi when the update reaches the minimum number of days in testing... so it seems that when an update is edited, Bodhi doesn't take that into account while calculating how many days the update has been in testing.
You should look in `update.edit()` method.

**Comment by karmadolkar** [comment]
Okay, so we want to set the value of number of days in testing to zero every time the update is edited? If so,

`up.date_modified = datetime.utcnow()`

should be the up.date_testing. 

Then we should call the https://github.com/fedora-infra/bodhi/blob/894b795bee6f9f79fd61596db9a9586750afeb8e/bodhi/server/models.py#L3737 function to store the days_in_testing value somewhere. Is there a class attribute for this?

**Comment by mattiaverga** [comment]
Do not confuse a function decorated with `@property` with the actual property stored in database.
`days_in_testing()` is only used to calculate and get the number of days passed since the update was pushed to testing.
The real attribute stored in database is
https://github.com/fedora-infra/bodhi/blob/894b795bee6f9f79fd61596db9a9586750afeb8e/bodhi/server/models.py#L1762-L1763
which is initially set to None when the update is created and then is populated with a SqlAlchemy DateTime object when the update is pushed to Testing.

So here we only need to clean the `date_testing` attribute when appropriate. You could do that when the karma is resetted (we don't want to reset the `date_testing` at every edit, for example when a user does a simple change to update notes).

**Comment by karmadolkar** [comment]
https://github.com/fedora-infra/bodhi/blob/894b795bee6f9f79fd61596db9a9586750afeb8e/bodhi/server/models.py#L2431-L2434 

then do `up.date_testing=datetime.utcnow()` inside the same loop?

**Comment by mattiaverga** [comment]
No, I think we should set it to None, then `date_testing` will be set when the update is pushed again in testing.
You can do it inside the first if statement after `data['request'] = UpdateRequest.testing`:
https://github.com/fedora-infra/bodhi/blob/894b795bee6f9f79fd61596db9a9586750afeb8e/bodhi/server/models.py#L2415-L2434

BTW we can also move `data['karma_critpath'] = 0` there and save an if statement.

**Comment by karmadolkar** [comment]
```
 # Updates with new or removed builds always go back to testing 
 if new_builds or removed_builds: 
     data['request'] = UpdateRequest.testing 
     data['karma_critipath'] = 0
     up.date_testing = None
  
     # Remove all koji tags and change the status back to pending 
     if up.status is not UpdateStatus.pending: 
         up.unpush(db) 
         caveats.append({ 
             'name': 'status', 
             'description': 'Builds changed.  Your update is being ' 
             'sent back to testing.', 
         }) 
```
set to None and saved the if statement.

**Comment by mattiaverga** [comment]
Would you mind making a PR and add/edit tests accordingly to make sure everything run as expected?
