### ISSUE TITLE
Add versioning for updates

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3497]
Basically we need  a way to uniquely identify an update as a specific list of builds (1 or more).
If the update is edited (builds added/removed), that list of builds change and thus the version should be different.

In the world of CI, we want to test the updates (uniquely identified by their alias/updateid), but since the builds in the update may change, we currently cannot distinguish test results from an update containing the build A-1 and B-1 from the same update edited to contain the builds A-1 and B-2.

Adding a `version` field to the update should allow for this distinction.

Note: that field should appear on the message sent to the bus.

**Comment by mattiaverga** [comment]
What about to store an hash based on update alias + builds names instead of manually created version field? I think it would be more error proof.
Maybe there's no need to store the hash in the database, it could be calculated on the fly.

**Comment by pypingou** [comment]
I see pros and cons to this:
Pros:
- Nothing to store in the DB
- Edited an update without changing the builds associated with it won't increment the version (Note: this could also be circumvent with the integer-based version by being careful on when we increment it)

Cons:
- It'll be harder to figure out the order of the versions: is dflkjhsaf before or after sdlifkhaskhf2?

In the context of using this for CI I suspect that the order of the version may be something interesting.

What do you think?

**Comment by mattiaverga** [comment]
I don't think any reason to know the order of the update versions, isn't the order of test result enough?

But yes, if that is important, a integer based approach is the most straightforward. I thought it was only a matter of uniquely bind a test result to a specific update "version".

**Comment by pypingou** [comment]
> I don't think any reason to know the order of the update versions, isn't the order of test result enough?

That would be correct, my only issue is if we ever face the situation where a test about an update v2 finishes before a test about the v1.
This may be a theoretical issue and maybe it does not happens often enough to worry about it, in which case your solution is more elegant :)

I'll leave the decision to the person implementing the feature :)
