### ISSUE TITLE
No browsing of updates based on releases

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#350]
Please add one more tab on right upper top "Releases" that will allow to browse updated submitted for that particular release. 
e.g. Like in old interface, In new interface when clicked on "Releases" tab, it should show all active releases like for "Fedora 23" should show https://bodhi.fedoraproject.org/updates/?releases=F23

**Comment by ralphbean** [comment]
Let's have it link to https://bodhi.fedoraproject.org/releases/F23

From there you can click the ``View all`` link and get to the list of all updates for that release.
