### ISSUE TITLE
Add a banner during Freezes

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#3505]
Just before every release, I see people wondering why their packages are not pushed to stable. If Bodhi showed a message _somewhere_, this would probably be less common.

**Comment by mm-git01** [comment]
I am taking this.

**Comment by ryanlerch** [comment]
Been thinking about this one, and i think there are two options here:

1. put an alert at the top of the new user dashboard page (i.e. the homepage for logged in users) listing the fact there are release(s) in the frozen state, and nothing will be pushed to stable until it is unfrozen.

and/or

2. add an alert somewhere on the update page for updates to the frozen release, saying the same thing. for this one, we probably only want to show it for updates in pending or testing.

**Comment by sebwoj** [comment]
#3170

**Comment by QuLogic** [comment]
I don't think 1 is sufficient on its own, because people can click on links in update emails and go directly to an update, never seeing their user page.

**Comment by mm-git01** [comment]
> I don't think 1 is sufficient on its own, because people can click on links in update emails and go directly to an update, never seeing their user page.

agree with this,imo both 1 and 2 of what @ryanlerch said should be implemented.

**Comment by ryanlerch** [comment]
@Pac23 are you still working on this one?

**Comment by sebwoj** [comment]
Now, when the release is in frozen state in bodhi, the following alert is printed on the top of release page :
`Release is frozen`

Also bodhi puts comment `There is an ongoing freeze; this will be pushed to stable after the freeze is over.` on the update page when:
- release state is `frozen` and user set request to `stable
- release state is set to `frozen` form other state.

Do we need additional `Release is frozen` alert on the top of the update page.
Maybe we should add some docs with info that now bodhi has `frozen` release state?

**Comment by mm-git01** [comment]
@ryanlerch still interested, haven't got around to this due to my schedule if this is super critical please assign to someone else.

**Comment by gsteja025** [comment]
can i take this
