### ISSUE TITLE
Update stable days default should be set by the release mandatory days in testing value

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3506]
Currently an update stable days default value is 7 days. This is not optimal when a release is in pre-beta since the policy requires an update to spend 3 days in testing.

To avoid that when creating an update the default value of stable days should be taken from the release mandatory days in testing value.

**Comment by Zlopez** [comment]
I tested this today and the stable days value is already set to mandatory days in testing, so I'm closing this one.
