### ISSUE TITLE
Can't remove bugs from an update

### ISSUE THREAD

**Issue by M4rtinK** [fedora-infra/bodhi#3508]
I've tried to remove a bug from the bug listing on a Bodhi update, but that does not seem to work & I'm getting the following error after unchecking the bug I want to remove & clicking on the save button:

`Builds : Unable to create update. DELETE statement on table 'update_bug_table' expected to delete 1 row(s); Only 3 were matched.`

The update in question:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-2cabc3f936

**Comment by ryanlerch** [comment]
@M4rtinK do you have any more information on which bug you were trying to remove here?

I just tried with the new new update form on bodhi.stg.fedoraproject.,org, and removing bugs seems to work there. 

Have you encountered this issue in the past? or was this just a one-off?

**Comment by cverna** [comment]
This is seems to work fine. Please feel free to reopen if you experience this again
