### ISSUE TITLE
submit update FEDORA-2015-13697 to stable

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#351]
Hi,
  Generally we get message that submitted update is in testing for 3 days and if maintainer want, can be moved to stable. I see this update https://bodhi.fedoraproject.org/updates/FEDORA-2015-13697 has already completed 3 days and I want to submit it to stable. I can't find how can I do it.

Please submit it to stable.

**Comment by ralphbean** [comment]
Is there no "Push to stable" button on the update page for you?  (At the top right?)

**Comment by pnemade** [comment]
ah! it is there. Sorry for the noise but there is too much information now on any update page, might be my eyes missed it to find. Need to get used to with this UI.

Thanks. Closing this issue.
