### ISSUE TITLE
Create single build updates in pending status for rawhide

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3513]
Now that we have the automation in place to automatically move an update from pending to testing we should use that for single build updates too.

For that we need to change the automatic_update consumer (https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/consumers/automatic_updates.py) to create the update in the pending status. 

And make sure that the signed consumer will move the updates from pending to testing when the build is signed.

**Comment by pypingou** [comment]
When we move this to production, we'll have to be careful to adjust robotsignatory's config and to double check that we do not leave any builds in a middle-state where they no longer move forward.
We'll need adjust our docs as well (I can pick this up though)
