### ISSUE TITLE
Update text in bugs is out of date and strangely formatted

### ISSUE THREAD

**Issue by jwboyer** [fedora-infra/bodhi#357]
The instructions bodhi puts in each bug for testing an update is strangely formatted and out of date.  Example text:

"kernel-4.2.0-0.rc8.git0.1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with \n su -c 'yum --enablerepo=updates-testing update kernel'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-14151"

The \n characters look strange there.  Further, yum is no longer used as the package manager in Fedora 22 and newer.  It will still work for now, but it is likely better to change the text to reference dnf.

**Comment by ralphbean** [comment]
Thanks for reporting!  Noting here that this is similar to #335.
