### ISSUE TITLE
Migrate Package Update HOWTO from Fedora Wiki to Fedora Docs

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/bodhi#3573]
As a contributor to Bodhi documentation,

I'd like the documentation describing the [Bodhi update process](https://fedoraproject.org/wiki/Package_update_HOWTO) to be migrated to the [Fedora Documentation site](https://pagure.io/fedora-docs/),

so that proposed changes can be reviewed before being published.

## Background

Currently, this documentation is in the wiki which makes reviewing changes awkward because by the time people can review them, they're already live, or you have to do a complicated "copy the page, do your changes in the copy, have them reviewed, and reintegrate them into the original page" dance.

Also, it lets us break it up into easier consumable chunks in the future, which also makes reviewing and integrating/merging after review easier.

## Acceptance Criteria

- A suitable Fedora Docs space is selected, e.g. the [Quick Docs](https://pagure.io/fedora-docs/quick-docs).
- The current content is
  - converted to ASCIIDoc
  - submitted as a PR to the selected docs repo
  - which is reviewed, merged and published.
- The old Wiki page directs users to the new place (use the `fedoradocs` custom directive which we have in our MediaWiki instance).

**Comment by anshikavashistha** [comment]
@nphilipp May I work on this issue?
Please this assign this issue to me.

**Comment by nphilipp** [comment]
Are you with Outreachy? I have no idea if this is still current, but any assistance here is gladly accepted!

**Comment by nphilipp** [comment]
I just looked into it, the content has been converted and moved to https://docs.fedoraproject.org/en-US/package-maintainers/Package_Update_Guide/ already. I’ll close this issue, thanks again!

Would like to work on something else? It’s late here, but I and others who work on Bodhi currently (or have in the past) are in the [Fedora Infrastructure Team](https://matrix.to/#/#admin:fedoraproject.org) or [Fedora Apps](https://matrix.to/#/#apps:fedoraproject.org) Matrix rooms, so we could chat about this there tomorrow or another day.
