### ISSUE TITLE
https://bodhi.fedoraproject.org/updates/list no longer accept POST arguments

### ISSUE THREAD

**Issue by mhabrnal** [fedora-infra/bodhi#358]
We use the /updates/list method to find a new updates of packages [1], but this doesn't work in the new version of bodhi.

It returns:
405 Method Not Allowed
The method POST is not allowed for this resource.

[1] https://github.com/abrt/abrt/blob/master/src/plugins/bodhi.c#L32

**Comment by jfilak** [comment]
This issue prevents ABRT client from reporting crashes to Red Hat Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1256493

**Comment by ralphbean** [comment]
The URL changed to https://bodhi.fedoraproject.org/updates which I think you'll need to hit with GET instead of POST.  Were you passing arguments to it to list updates only for certain packages or some other limiting factor?

**Comment by kparal** [comment]
You can see the new API here:
https://github.com/fedora-infra/python-fedora/blob/develop/fedora/client/bodhi.py#L196

**Comment by jfilak** [comment]
ABRT client needs to filter updates by Bugzilla Bug IDs, release versions and package names and all of these criteria are supported.

**Comment by jfilak** [comment]
Would it be possible to add Package name to ``updates:builds`` in the search response? The field has the member ``nvr`` but ABRT client needs a package name to be able to run ``rpm -q`` and splitting ``nvr`` is not reliable.

**Comment by kparal** [comment]
You can use `hawkey` to split NVR reliably (we use that in Taskotron). But it's true that we would also appreciate if package name was available in the build info (it used to be there in Bodhi1 response).

@jfilak: You can use `rpm -q NVR` just fine.

**Comment by jfilak** [comment]
@kparal ``rpm -q NVR`` works only if you have installed ``NVR`` but in our case we want to get the installed version of ``n`` and compare it with the ``vr``.

**Comment by bowlofeggs** [comment]
Is this still an issue?
