### ISSUE TITLE
bodhi --release filtering issues

### ISSUE THREAD

**Issue by sorki** [fedora-infra/bodhi#360]
Wrong release results in

`$ bodhi --release=fc23 abrt`

```
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 486, in main
    print_query(data)
  File "/usr/bin/bodhi", line 478, in print_query
    for update in data['updates']:
KeyError: 'updates'
```

Specifying correct release doesn't yield expected result either:

`$ bodhi --release=f22 abrt`

```
================================================================================
     clearlooks-phenix-6.0.3-3.fc22
================================================================================
  Update ID: FEDORA-2015-14198
    Release: Fedora 22
     Status: pending
...
```

**Comment by ryanlerch** [comment]
This issue is filed against the old, deprecated version of Bodhi CLI. Are you still encountering this issue with the new bodhi2 CLI -- i.e. the command is now `bodhi updates query --releases=f23 --packages=abrt`.

**Comment by bowlofeggs** [comment]
I'm going to close this. If you can reproduce with bodhi-2.8.1 or newer, please feel free to reopen!
