### ISSUE TITLE
ResultsDB Querying - switch from update.title to build names

### ISSUE THREAD

**Issue by rajcze** [fedora-infra/bodhi#361]
At the moment, Bodhi queries ResultsDB on per-update.title basis. That effects multi-build updates in a way, which causes no results to be found (https://bodhi.fedoraproject.org/updates/control-center-3.16.3-1.fc22%20gnome-settings-daemon-3.16.3-1.fc22 for example).

This works with single-build results, as the koji-build-name is usually the same as bodhi-update-title.
The multi-build-update result querying did work to some extent in the past, as depcheck stored per-update(-title) results, as well as per-koji-build-name results, but then no rpmlint (for example) results were shown, although the builds contained in the update were tested.

I suggest querying ResultsDB on build-name(s) basis (all our current check store per-build results), which will give you all the results for all the builds in the update.

It might happen, that some multi-build updates will have quite a lot of automated results (gnome mega updates come to mind), but that can be sorted out by (e.g.) showing an overall result (computed from the singular per-build results, e.g. "if at least one build FAILed, overall result is FAIL" etc.), and implementing a drop-down to show the separate per-build results.

**Comment by ralphbean** [comment]
Adjusting the queries will not be difficult, but designing/implementing the drop-down will be a pain.  Can do, though!

**Comment by ralphbean** [comment]
A reminder to whoever implements this: taskotron results are used in three places:

* In javascript in the web client to show results in a table on the update page.
* In python on the server when someone requests an update go to stable.. we check to make sure they pass all *required* taskotron checks at that point.
* In python again, but this time in the masher at the beginning of the push.   We eject any updates from the push which fail any *required* taskotron checks.

In practice, this only needs to be implemented in two places since the python code is shared in ``bodhi/models/models.py`` .. specifically in the ``check_requirements(self, ...)`` method.

**Comment by ralphbean** [comment]
Note that #890 fixed the UI portion of this only.  The server-side mash-time checks still need to be adjusted.

(In retrospect, that's a little dangerous because people might see the UI and think all checks are being consulted, when in reality it's still just the per-update checks).

**Comment by kparal** [comment]
Do I understand correctly that some parts of Bodhi still send `type=bodhi_update` requests and we should continue producing these results until that is resolved?

**Comment by AdamWill** [comment]
Note there's now an additional wrinkle to this: we're now testing updates with openQA, and the openQA results are reported by update ID, not by NVR (i.e. the 'old' way so far as Taskotron is concerned). For openQA this isn't an 'old' or 'wrong' way, it's the right way - openQA really does test at the level of the update - so we're not likely to change it to report results by NVR. So, Bodhi is gonna have to be able to query both ways.

I'm planning to send a PR for the web UI code, I'll have to look into how the backend code works and what to do with it...

**Comment by bowlofeggs** [comment]
Is this issue resolved now by the refactoring of the JavaScipt over the past few months, combined with how we now query Greenwave for gating information?

**Comment by kparal** [comment]
Yes, this issue should be resolved now with the patches I provided some months back.

**Comment by bowlofeggs** [comment]
Thanks!
