### ISSUE TITLE
Update.pushed needs to be set to True in the signed consumer when an update is moved to testing.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3625]
A rawhide update is moved from pending to testing in the signed consumer, when moving the update the update.pushed is not set which then makes it impossible to unpush an update from the UI.

**Comment by StephenCoady** [comment]
@cverna @pypingou I think I have added the change necessary locally. Could one of you guys give me permission to assign tickets, please? Pushing branch now and will create a PR shortly.
