### ISSUE TITLE
Install LGTM app to the bodhi repo to reports on PR

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3636]
LGTM provides a report on code quality see https://lgtm.com/projects/g/fedora-infra/bodhi

We could add the LGTM application to the project settings so that we get a report for each PR.

**Comment by abompard** [comment]
Indeed, LGTM is currently pointing out real errors, that's interesting.

**Comment by abompard** [comment]
I think we need someone with admin permissions on the fedora-infra Github organization to add the LGTM app before we can add it to this repo.
