### ISSUE TITLE
Link for multiple updates to same package doesn't work

### ISSUE THREAD

**Issue by richardfearn** [fedora-infra/bodhi#364]
e.g. I just submitted a `findbugs-contrib` update for F22/F23; the text shown is 

> richardfearn submitted 2 findbugs-contrib testing updates for F22 and F23

and the URL is https://bodhi.fedoraproject.org/updates/findbugs-contrib/ which gives me a 404.

**Comment by richardfearn** [comment]
I've now submitted more updates for different packages and Bodhi says:

> richardfearn submitted findbugs, findbugs-contrib, and jcip-annotations updates for F23

In this case the URL is https://admin.fedoraproject.org/updates/user/richardfearn/ - that's also a 404 because of the trailing slash. https://bodhi.fedoraproject.org/users/richardfearn (which is the URL for the "Profile" link) works.

**Comment by richardfearn** [comment]
> the URL is https://bodhi.fedoraproject.org/updates/findbugs-contrib/ which gives me a 404.

That's also due to the trailing slash - https://bodhi.fedoraproject.org/updates/findbugs-contrib works.

**Comment by ralphbean** [comment]
Thanks!  This should be fixed in fedora-infra/fedmsg_meta_fedora_infrastructure#315, which has been merged, but not yet deployed.

**Comment by ralphbean** [comment]
*Finally* got around to deployed that fedmsg.meta fix to the datagrepper server today.  This should be finally fixed in production now.

**Comment by richardfearn** [comment]
Thanks a lot!
