### ISSUE TITLE
New update should not offer builds that already have their updates

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3649]
When I enter new update via https://bodhi.stg.fedoraproject.org/updates/new it offers me a list of builds to pick from. It includes builds that already have their updates. Only to error upon submitting.

**Comment by ryanlerch** [comment]
The builds list could definitely do with a little more pre-validation here too. In addition to builds that already have updates, checking acls so we only list candidate builds that you can submit updates for would also be good.

Tagged this as RFE, as this is not a regression (in the old form, all the checking was done after submitting the form as well.)

**Comment by hroncok** [comment]
It lists a lot of epel 6 updates. Does it at least filter by candidate tags, as before? It's hard to tell on staging.

Also,previously, this was 2 phases: pkgname, build. It reduced the amount a lot.

**Comment by ryanlerch** [comment]
the control itself shows all the candtidate builds from all releases that are open. the search is actually filters on a few fields, so you cound type in "churchy python- fc30" to filter down. 

But generally, we should remove some more of the options that will always come back from the server as failures :)
