### ISSUE TITLE
obsoleting updates not working right

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#365]
I had: 

https://bodhi.fedoraproject.org/updates/calibre-2.35.0-1.fc23
https://bodhi.fedoraproject.org/updates/calibre-2.35.0-1.fc22

But rex was building a new qt5, so he rebuilt calibre against that and submitted: 

https://bodhi.fedoraproject.org/updates/calibre-2.35.0-1.fc22.1%20python-qt5-5.5-1.fc22%20PyQt4-4.11.4-1.fc22%20sip-4.16.9-1.fc22

but it didn't obsolete my ilder ones.

**Comment by kalev** [comment]
Likewise, https://bodhi.fedoraproject.org/updates/FEDORA-2015-13858 should have obsoleted https://bodhi.fedoraproject.org/updates/FEDORA-2015-13284 but didn't.
