### ISSUE TITLE
Cannot remove builds in the new UI from

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3651]
When creating a new update and selecting the side tag option to populate the build list, the UI does not let me remove builds or change my choice to use a side tag.

I think the user should be able to clear the list of builds in order to restart from scratch.

**Comment by ryanlerch** [comment]
#3620 covers the not being able to go back to normal builds mode, but not sure how common this will be in actual use to be honest.

WRT removing / editing builds of a side tag, this is not possible really. there is the option to load new builds from a sidetag, but manual editing is not really a thing with sidetags, right? you just get the builds in the tag. on koji.

**Comment by ryanlerch** [comment]
marking this as a dupe of #3620
