### ISSUE TITLE
Updates in stable are still pushable back to testing

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3653]
Related to #3451 
In bodhi.stg updates in F31 stable are still pushable back to testing:
![immagine](https://user-images.githubusercontent.com/17218209/67557042-91db8480-f714-11e9-97e7-528183ef453e.png)

**Comment by ryanlerch** [comment]
this is showing because this update is not marked as "pushed". This is fixed so all automatic updates going forward will be marked as pushed. Yeah, not sure how to fix the old ones in the database (or if we want to bother too)

I noted this in #3462 the PR that resolves #3451

**Comment by mattiaverga** [comment]
I think that when the `pushed` property was introduced in the Update model, we should had run a database change like:
`if update.request is None and not update.pushed`
then
`update.pushed = True`.
If we don't do that, every user could push back stable updates to testing. Is there a backend check in Bodhi that prevents the downgrade? What happens in this case?

**Comment by cverna** [comment]
I have updated staging with the following snippet run from the bodhi-shell

```
>>> s = m.Session
>>> updates = s.query(m.Update).filter(m.Update.status == m.UpdateStatus.stable, m.Update.pushed == False)
>>> updates.count()
4345
>>> for u in updates:
...     u.pushed = True
... 
>>> s.commit()
```

Once we are not in freeze and Fedora 31 is release we can do the same thing in production

**Comment by ryanlerch** [comment]
> I think that when the `pushed` property was introduced in the Update model, we should had run a database change like:
> `if update.request is None and not update.pushed`
> then
> `update.pushed = True`.
> If we don't do that, every user could push back stable updates to testing. Is there a backend check in Bodhi that prevents the downgrade? What happens in this case?

the pushed property on updates has been there for well over 6 years: https://github.com/fedora-infra/bodhi/blame/52266ead23eba389d860735da3a6eb59c7188cf9/bodhi/server/models.py#L1787

The issue here was that when an automated update was "pushed", which happens in a different manner to a normal update, the pushed property was not set. #3462 fixes that issue.
