### ISSUE TITLE
After bodhi update last week, I'm missing a URL that I like to use

### ISSUE THREAD

**Issue by w6jve** [fedora-infra/bodhi#367]
I have been using the URL  
http://admin.fedoraproject.org/updates/F22/  to learn about released updates
It doesn't work anymore.  I'd like to get it back, or a suitable replacement.

I'm just an ordinary user who updates systems in the ordinary way from the updates
repository.  Sometimes I like to look at the writeup for a recent update to see what it
does.

I was given a pointer to https://bodhi.fedoraproject.org/releases/F22 but that doesn't
show what I want to see - unless there is a filter I don't see that lets me look at only
the updates that have been released.

**Comment by ralphbean** [comment]
Hm.  If you want to see the list of released updates for a release, have you tried clicking on the ``View all`` link on that  https://bodhi.fedoraproject.org/releases/F22 page?  Does that show what you want?

And, if it doesn't, can you tell me more about what it's missing that you need?  I'm definitely open to adding.

**Comment by w6jve** [comment]
When I go to that web site  https://bodhi.fedoraproject.org/releases/F22
it shows to begin with those that are Request testing and Status pending.
If I click View All the view changes but it still shows those that are
testing and pending.  I want to see only those that have been released
to the updates repository, those that are going to be applied to my
machines.  That's what the former web page that I referred to showed.

Thanks.

**Comment by ralphbean** [comment]
Sure thing, I think you want this URL:  https://bodhi.fedoraproject.org/updates/?releases=F22&status=stable with the ``status=stable`` argument.  Does that suffice?

**Comment by w6jve** [comment]
Yes, thanks, that will do nicely.

**Comment by ralphbean** [comment]
Great.  :)
