### ISSUE TITLE
Update name truncated upon edit

### ISSUE THREAD

**Issue by psss** [fedora-infra/bodhi#3675]
Steps to reproduce:

* https://bodhi.fedoraproject.org/updates/FEDORA-2019-0c2e93b669
* title says `Python 3 and custom plugins`
* click the `Edit` button
* update name is `Python`
* should be `Python 3 and custom plugins`

**Comment by AdamSaleh** [comment]
There are "" missing on https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/templates/new_update.html#L53 meaning 

`value=${update.display_name | h}`

should have been

`value="${update.display_name | h}"`

Will submit a PR :D

**Comment by hroncok** [comment]
Went here to report that. Found this as a duplicite.
