### ISSUE TITLE
Small UI glitch

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3676]
There seems to be a small UI glitch on the update page: https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-865f2c37b3

Here is a screenshot:
![Screenshot from 2019-10-30 10-24-10](https://user-images.githubusercontent.com/1240038/67845309-9088ce00-faff-11e9-95bf-61deaee1a329.png)

**Comment by ryanlerch** [comment]
Looks like there is invalid HTML (an additional button closing tag, and a missing div closing tag) in the greenwave modal. As this is not shown on all pages, it only shows if this modal is on the page.

This is what is causing that extra white bar at the bottom of the page.
