### ISSUE TITLE
Bodhi2 no longer restricts changes to Security Response bugs (Regression)

### ISSUE THREAD

**Issue by thoger** [fedora-infra/bodhi#368]
Bodhi2 lost all special handling of security bugs ("Security Response" BZ product, "vulnerability" component) that was implemented in Bodhi1.  These are differences from the standard handling I can remember, hopefully not missing anything important.  Bodhi1 code should serve as authoritative reference.

* Bodhi should only add comments to Security Response bugs when update is pushed to stable.  No comments are expected to be added when updates are submitted or pushed to testing.
* Bodhi should never change Security Response bugs status - no change to ON_QA, no close on push to stable.
* Bodhi should never change content of the Fixed In Version field.

Basically, Bodhi is only expected to add comment when update is pushed to stable and do no other changes to the bugs.

Please handle this as regression that should be corrected ASAP.

Example of bug changes Bodhi should not be doing:
https://bugzilla.redhat.com/show_bug.cgi?id=1254547#c5

**Comment by vdanen** [comment]
Just adding that this is really important to Product Security and is a severe regression for us.

**Comment by lmacken** [comment]
Working on a fix for this now.

From what I can tell from the bodhi1 code, it will actually close the Security Response parent bugs if all of the bugs it `dependson` are closed and the bug is not `NEW`. Do you still want this behavior?

**Comment by lmacken** [comment]
So with the above patch, I think bodhi2 should have the same behavior as bodhi1.

Here is the logic around closing security bugs, which is the same from bodhi1. https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L1115-L1146

**Comment by thoger** [comment]
> From what I can tell from the bodhi1 code (and bodhi2), it will actually close the Security Response parent bugs if all of the bugs it dependson are closed and the bug is not NEW. Do you still want this behavior?

Those bugs are not really expected to be in any other state than NEW.  Hence the code was rarely used and I'd say to not add it to Bodhi2.

**Comment by lmacken** [comment]
Okay, cool. I'll remove it.

**Comment by lmacken** [comment]
Okay, this fix has been deployed to production. Hopefully it should only comment on Security Response when updates hit stable. Please re-open if this is not the case. Thanks!

**Comment by thoger** [comment]
Previous comment suggests the fix is in production, however I just noticed the following change done when package was pushed to stable:

https://bugzilla.redhat.com/show_bug.cgi?id=1256746#c3

Fixed In Version field was updated and bug CLOSED:NEXTRELEASE.
