### ISSUE TITLE
CI failings, probably celery worker isn't started

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3698]
I did some investigation on the CI failings, it seems that Celery worker isn't started. I think that `/etc/bodhi/start.sh` is not executed when docker image changes from `f31-integration-build-bodhi` to `f31-integration`
https://github.com/fedora-infra/bodhi/blob/6794e5b9b5b2ecca77e43e7df596e8b569b84448/devel/ci/integration/bodhi/Dockerfile-f31#L65
I tried to change that from CMD to ENTRYPOINT, but it never executes - I cannot even see a simple echo command.

That leads the 
https://github.com/fedora-infra/bodhi/blob/6794e5b9b5b2ecca77e43e7df596e8b569b84448/devel/ci/integration/tests/test_bodhi_tasks.py#L48
line fail for timeout.
Note that the other tasks that rely on celery `.delay()` are not tested for a successful completion so the other tests don't fail...

**Comment by mattiaverga** [comment]
Well, after having spent the last couple of days hunting down the problem, I now see that CI tests are working again... so it couldn't be what I have been focused early in this report, even if I can't see the `start.sh` been executed in the logs.

Another possibility of those random fails could be what I noticed in another bug report: our dummy buildystem used in dev goes crazy with builds which don't follow classic nvr. With a build named like `fedora-release-32-0.1` the `koji.getBuild()` method raises a ValueError.
When the CI tests were failing, I saw this error by setting `task_always_eager = True` into Celery options, but I didn't pay much attention.

Since we use real data in CI tests, it may be possible that when that data contain such builds the compose test fails.

**Comment by AdamSaleh** [comment]
I have been investigating, and might have found another reason.

When we run the integration test, it checks there are pending composes. But it looks like if there are only container-based composes, the pungi wouldn't be run at all. I think we could improve the tests reliability by checking there are at least some rpm/module-type composes, where pungi would be run and pungi.log created :) Will try to submit a PR.
