### ISSUE TITLE
Broken /rss/updates/ page in bodhi 5.0

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#3703]
Bodhi 5.0 rss page for updates is broken.
Bodhi 5.0 stg: https://bodhi.stg.fedoraproject.org/rss/updates/
Bodhi 4.1.1: https://bodhi.fedoraproject.org/rss/updates/

**Comment by ryanlerch** [comment]
Can you provide a little more information on how this is broken for you?

It seems to parse for me in a feed reader.

**Comment by sebwoj** [comment]
An oversight on my part.
Closing.
