### ISSUE TITLE
Incorrect karma values for bash-4.3.42-1.fc22

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#371]
In https://bodhi.fedoraproject.org/updates/bash-4.3.42-1.fc22 I count four +1 votes, but Bodhi shows this update as having +8 karma.

Is it perhaps something gone wrong with database migration from Bodhi 1 to Bodhi 2?

**Comment by ralphbean** [comment]
Yeah, something must've gone wrong in the migration.

**Comment by bowlofeggs** [comment]
Karma was reworked with Bodhi 2.4.0 and is now dynamically calculated to solve issues like this. Though I found a [bug](https://github.com/fedora-infra/bodhi/issues/829#issuecomment-282330985) in the new calculation just today, the updated cited in this bug report now shows the correct value of +5 so I will close this issue. Thanks for reporting it!
