### ISSUE TITLE
Did database migration lose autokarma values?

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#372]
I've noticed that a lot of older updates that were migrated from Bodhi 1 database to Bodhi 2 now have their autokarma disabled.

As an example,
https://bodhi.fedoraproject.org/updates/gnupg2-2.1.7-1.fc22 (reached autokarma with bodhi 1 and is in stable now)
https://bodhi.fedoraproject.org/updates/gnupg2-2.1.7-1.fc23 (still in updates-testing, bodhi 2 shows autokarma as disabled)

... and many more similar cases.

Now, I don't have any hard facts to say for sure whether the gnupg2 update really had autokarma set originally in Bodhi 1 or not, but it might be good to have a look at the Bodhi 1 database and maybe retroactively fix up the database migration if this really got migrated wrongly.

**Comment by ralphbean** [comment]
Yes, this appears to be an issue with the migration.  Thanks for reporting!

**Comment by ryanlerch** [comment]
Is this one still an issue that should be addressed? Or can it be closed now?
