### ISSUE TITLE
Expired overrides cannot be made active

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/bodhi#3721]
I go to [this override](https://bodhi.fedoraproject.org/overrides/R-bit64-0.9.7-6.fc30), which expired 20 hours ago (i.e., today), change the date to two days from now, and hit Submit.

Instead of extending the override, it fails with a "Nvr : Required" popup.

**Comment by QuLogic** [comment]
This might be the same as #3710.

**Comment by ryanlerch** [comment]
@QuLogic pretty sure it is the same issue here.

Just tested it out locally with the patch in #3719 which seems to fix this issue too.
