### ISSUE TITLE
feature request: status of karma should shown in overview page of updates

### ISSUE THREAD

**Issue by NiceandGently** [fedora-infra/bodhi#373]
At overview site of my updates the status of karma of an update isn't show anymore.
This was possible with bodhi-1.
Now i've to select an update to see the karma status.
It would be very nice to add this feature back.

Thank you

**Comment by ralphbean** [comment]
This should be possible, yes.

**Comment by NiceandGently** [comment]
Whow, that was fast :)
thanks again
