### ISSUE TITLE
No feedback when trying to add karma without entering a comment.

### ISSUE THREAD

**Issue by jwakely** [fedora-infra/bodhi#375]
If I click the radio button to say the update is generally functional and click the "Add comment" button nothing happens.

It seems to refuse to submit unless I type something in the comment textbox, but there is no error or feedback telling me that.

**Comment by ralphbean** [comment]
OH!  I see.  What browser are you using?

We use the ``<textarea required="true"/>`` HTML5 attribute which should prompt your browser to say "you have to fill this in".

**Comment by jwakely** [comment]
This was with Firefox 40.0 from Fedora 22.

**Comment by jwakely** [comment]
Hmm, now I see a (fairly subtle) "please fill in this field" alert ... I wonder if that was there before and I missed it.  I've just been playing with it, and don't see how I would have missed it (it appears pretty close to where I must have been looking in order to click on the button) but I have no other explanation other than PEBKAC.

**Comment by ralphbean** [comment]
Thanks @jwakely!
