### ISSUE TITLE
sent emails not encoded correctly

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#377]
From: https://fedorahosted.org/bodhi/ticket/789

one example is: 

https://bodhi.fedoraproject.org/updates/FEDORA-2015-13400

the notes seems to use "smart quotes" which aren't encoded right... ie: 
“Select commit”
not
"Select commit"

**Comment by pypingou** [comment]
I wonder if the way to fix it is not to use:
https://github.com/pypingou/pagure/blob/master/pagure/lib/notify.py#L200

This allows to declare the encoding of the email sent.
