### ISSUE TITLE
Obsoleted update links broken in Bodhi 5.0

### ISSUE THREAD

**Issue by tim77** [fedora-infra/bodhi#3773]
They are not clickable anymore. For example:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-bfd89bbb49

![DeepinScreenshot_select-area_20191117192806](https://user-images.githubusercontent.com/5614476/69011177-76a91100-0970-11ea-8e81-cdcde0a5f232.png)

**Comment by sebwoj** [comment]
Duplication of #3723

**Comment by tim77** [comment]
Oh, yep. TY. Closing.
