### ISSUE TITLE
Bodhi complains that it doesn't handle certain types of bugs (regression)

### ISSUE THREAD

**Issue by jmflinuxtx** [fedora-infra/bodhi#3789]
When filing security updates for Fedora, there are 2 bugs which must be included. The Fedora tracker for that security issue, and the security team tracker. With the bodhi update, it complains that it doesn't handle that type of bug for the security team tracker. Examples:

Fedora bug that bodhi handles:
https://bugzilla.redhat.com/show_bug.cgi?id=1775116

Tracker that it does not (and should):
https://bugzilla.redhat.com/show_bug.cgi?id=1775074

**Comment by mattiaverga** [comment]
Bodhi has never handled bugs for the "Security Response" product, but the old update form didn't show any warning about that:
https://bugzilla.redhat.com/show_bug.cgi?id=1767726
https://bugzilla.redhat.com/show_bug.cgi?id=1765043

That said, it should just be a matter of adding that product into Bodhi configuration:
https://github.com/fedora-infra/bodhi/blob/3383ca09fa066c84f37a366701e31205474d2fdd/bodhi/server/config.py#L278-L279

**Comment by jmflinuxtx** [comment]
The previous version did not warn, and did add comments to those issues.  It can't close them either way because they tend to have blockers on all vulnerable products.
https://bugzilla.redhat.com/show_bug.cgi?id=1758239

**Comment by mattiaverga** [comment]
> The previous version did not warn, and did add comments to those issues. It can't close them either way because they tend to have blockers on all vulnerable products.
> https://bugzilla.redhat.com/show_bug.cgi?id=1758239

Yes, adding comments to those bugs is the only operation that Bodhi is allowed to, but it (actually) can't set it to "modify" or "on_qa" statuses, nor it can close the bug, because these operations are checked against the `bz_products` list. And that's exactly what the new warning is saying to the user.

If we want Bodhi to be able to modify the bug status or close it, the PR I've just posted will do that. If we don't want Bodhi to do that and continue working as it always did, then the warning is right because it reminds the user that they will have to handle that bug manually. (and just trash my PR)

**Comment by jmflinuxtx** [comment]
I think the previous behavior was correct in this case. Those bugs need the comment, status changes and closing are not really necessary, but considering the instructions in the Fedora security tracker bug template includes adding those bugs to bodhi, I would definitely consider the new warning a UI problem. When following the instructions of the security tracker, bodhi now essentially tells you that you are doing something wrong.  Of course this is made much worse when filing an update with 20 CVEs fixed, as you get this warning 20 times.

**Comment by mattiaverga** [comment]
The behavior changed in #2336 in consequences of a need to not alter bugs statuses if they were `Security Response`... so discard my PR, we should not re-enable that.

**Comment by jmflinuxtx** [comment]
Yes, I think the correct behavior here is not to allow altering bug statuses on those products, but to get rid of the warning that was recently added.
