### ISSUE TITLE
No feedback for successful update creation

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#379]
After clicking Submit on the new update page, I get no feedback for successful update creation.

**Comment by ralphbean** [comment]
Does it not redirect you to view the new update?

**Comment by ralphbean** [comment]
@opoplawski you may need to hard-reload the page to get the latest JS assets from the server (your browser may have the old ones cached).

**Comment by ralphbean** [comment]
Oh!  We just found the bug for this one.  Should be fixed in 2494b25.

**Comment by lmacken** [comment]
Yep, this fix is live. Please re-open if you still experience this issue.
