### ISSUE TITLE
Bring back space delimited bug number entry.

### ISSUE THREAD

**Issue by jmflinuxtx** [fedora-infra/bodhi#3790]
With the latest Bodhi upate, I can no longer drop in a list of space delimited bug numbers, they must be entered one at a time and select the found results.  This is a huge annoyance when dealing with updates that fix a large number of bugs (today's kernel updates address 40 different security bugs).  Please bring back the ability to drop a list of bug numbers in the bugs field.

**Comment by pypingou** [comment]
@ryanlerch what do you think of this one?

**Comment by mattiaverga** [comment]
Just as a note, adding a comma separated list of bugs seems to work.

**Comment by jmflinuxtx** [comment]
1774933,1774934,1774937,1774939,1774946,1774947,1774949,1774950,1774957,1774958,1774963,1774965,1774972,1774973,1774976,1774978,1774988,1774989,1774998,1775002,1775021,1775023,1775010,1775011,1775015,1775016,1775042,1775043,1775047,1775048,1775050,1775051,1775956,1775110,1775097,1775115,1775074,1775116,1775063,1775117
Seems to just hang there forever. (Yes, this is a real bug list on a current update)

**Comment by ryanlerch** [comment]
yeah, let's pull the code that pulls down the bug titles for now, it seems to make this hang

**Comment by ryanlerch** [comment]
not sure what is causing the hang here... other than the annoying messages that should soon be resolved by #3794 pasting the comma separated list seems to work for me.

I am adding it to a new update, @jmflinuxtx are you editing an exisitng update or adding to a new update?
