### ISSUE TITLE
Cannot expire build override

### ISSUE THREAD

**Issue by pemensik** [fedora-infra/bodhi#3802]
Created two overrides [f30](https://bodhi.fedoraproject.org/overrides/bind-9.11.13-2.fc30) [f31](https://bodhi.fedoraproject.org/overrides/bind-9.11.13-2.fc31) and wanted to expire them. However, error popup was raised: Nvr: Required.

Where am I supposed to provide NVR? It is already there in Candidate Build. Am I missing something?

**Comment by ryanlerch** [comment]
Thanks for filing this issue. However, this is an issue that has already been reported at #3710 and consequently already fixed with the pull request #3719 . 

Note however, that this fix is not already in production, so the issue may still be encountered on  bodhi.fp.o
