### ISSUE TITLE
Cannot de-select the "auto-request stable" options or change thresholds.

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#3814]
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-dac149ad76/edit
I want to de-select the auto-request stable options, but the save button is not responsive.  Nor can I change the karma threshold or number of days.

**Comment by mattiaverga** [comment]
I think that's because the javascript form crashes due to the presence of `"` in some bug titles. After the provided patch is applied it should work as expected.
Same problem as in #3714
