### ISSUE TITLE
Comment submission is slow on updates with many builds, in extreme cases request times out and user experience is confusing (spinner stops spinning, no page refresh, no error shown, comment not yet visible on manual refresh)

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#3837]
Lately when I add a comment to an update, it often doesn't appear. I press the "Add Comment & Feedback" button, it shows a spinner for a while, then it goes back to 'ready to press' state - but the rest of the page is not refreshed, I do not see my comment or karma appear. Sometimes if I do a hard refresh (shift-ctrl-r) at this point the changes will appear, but sometimes even this doesn't make them show up. So I submit the comment again (and the same thing happens)...then I hard refresh again a few seconds or minutes later, and I see both comments.

I've seen quite a few duplicated comments on updates from other people, too, from which I infer that I'm not the only one getting bitten by this.

**Comment by ryanlerch** [comment]
When this does happen next time, are you able to check the browser's error log and web console to see if anything is returned there? Might help reporducing this one

**Comment by mattiaverga** [comment]
I suspect this is only due to the slowness of the server in high traffic moments.
Actually when posting a comment the flow is: 
1) push the 'add comment' button
2) the button is deactivated and the request is posted by JS
3) when the JS finishes with success a successful message is showed and the button is reactivated
4) finally, the html page is refreshed and the new comment is visible

If 3 happens, the only way to not have the comments showed is that the page isn't refreshed.
To avoid the double post we could let the button deactivated instead of reset it in 3, so that the spinner in the button signals to the user that something is still happening behind the scenes. In the worst case, an impatient user will refresh the page themselves without double posting.

**Comment by AdamWill** [comment]
does 3 have a timeout? because I don't recall seeing a 'success message' when this has happened to me, the spinner disappeared and the button went back to active state, but I don't think I saw any message...

**Comment by AdamWill** [comment]
so yeah, I'm about 90% sure that's what is happening here. I tried using staging to confirm for sure but I can't because adding comments on updates in staging seems to work really fast (even on an update with a lot of other comments it works within a few seconds). But I'm fairly sure when I've seen this on prod, I was staring at the spinner for like 30 seconds, and I did not see the little black 'success' toaster in the bottom right when it stopped spinning.

So my guess as to what's happening is that I hit the 'Add Comment & Feedback' button and two things happen: `forms.js` `submit()` calls `self.start()`, which toggles all spinners (so the spinner starts spinning), and then sends a POST request.

After a while the POST request times out - I'm guessing 30 seconds, per https://stackoverflow.com/questions/28475753/override-request-timeout-in-pyramid-gunicorn and https://stackoverflow.com/questions/53744751/python-pyramid-increase-request-timeout this isn't controlled by Pyramid or Bodhi exactly but by the web server - and this will trigger the `error()` function. That calls `self.finish()`, which toggles all spinners again, so the spinner stops spinning. It also tries to pop up a toast for each error in the response - but since we hit a generic server timeout, I'm guessing the response doesn't contain anything this function actually recognizes as an error, so it just doesn't pop up anything.

As I said I'm not in a position to confirm this for sure right now (I'll have to redeploy my development server and play around with it a bit, sigh) but it seems plausible and would result in exactly the observed behaviour: spinner starts, runs for a while, then stops, with nothing else visibly happening; comment has not actually been added yet (so doesn't show up when I force a page refresh) because Bodhi is still 'thinking about it' but the request has timed out; eventually Bodhi does manage to finish handling the comment submission so on a later refresh of the page it *does* show up.

**Comment by AdamWill** [comment]
BTW, if I'm right, the second answer to https://stackoverflow.com/questions/53744751/python-pyramid-increase-request-timeout seems relevant to how this ought to be fixed:

"The correct approach is not to execute long running tasks in the requests. What you can do is:

* Make an initial request to kick off the task, returns immediately. This request writes the task to a database.
* Have a background worker process (e.g. Celery) to process tasks
* Have a front end polling / JavaScript / redirect loop to check if the background process has completed the task"

So either that, or just figure out why submitting a comment is taking so damn long in prod, and fix that...

Also as a more generic mitigation here, the `error` function could be enhanced to show some sort of generic "Oh dear, something went wrong, but we don't know what!" message if it doesn't find any specific errors in the response.

**Comment by AdamWill** [comment]
Aha, OK, so now I'm 99% sure that's what's going on. I found a [staging update where I can reproduce this](https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-8b21f399ee): it seems you need, not an update with lots of comments, but an update with lots of *builds*. I checked the current time, hit the submit button, then carefully watched what happened. It's exactly as I described: the spinner starts, runs for a while, and stops, no toasts appear at all. As soon as that happened I checked the time again, and it was exactly 30 seconds since I hit the button. I then did it again and watched the browser console; it shows an error "TypeError: data.responseJSON is undefined" for `forms.js` line 74, which is very strong proof I'm right, because that's exactly where the `error` function tries to parse individual errors out of the response.

**Comment by AdamWill** [comment]
Here's the exact response as logged by Firefox. It's a 504 "Gateway Timeout".

    {
      "log": {
        "version": "1.2",
        "creator": {
          "name": "Firefox",
          "version": "71.0"
        },
        "browser": {
          "name": "Firefox",
          "version": "71.0"
        },
        "pages": [
          {
            "startedDateTime": "2019-12-10T09:00:51.432-08:00",
            "id": "page_1",
            "pageTimings": {
              "onContentLoad": -488018,
              "onLoad": -487628
            }
          }
        ],
        "entries": [
          {
            "pageref": "page_1",
            "startedDateTime": "2019-12-10T09:00:51.432-08:00",
            "request": {
              "bodySize": 0,
              "method": "GET",
              "url": "https://bodhi.stg.fedoraproject.org/markdown?text=test+comment+%233",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "Host",
                  "value": "bodhi.stg.fedoraproject.org"
                },
                {
                  "name": "User-Agent",
                  "value": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
                },
                {
                  "name": "Accept",
                  "value": "application/json, text/javascript, */*; q=0.01"
                },
                {
                  "name": "Accept-Language",
                  "value": "en-US,en;q=0.5"
                },
                {
                  "name": "Accept-Encoding",
                  "value": "gzip, deflate, br"
                },
                {
                  "name": "Referer",
                  "value": "https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-8b21f399ee"
                },
                {
                  "name": "X-Requested-With",
                  "value": "XMLHttpRequest"
                },
                {
                  "name": "DNT",
                  "value": "1"
                },
                {
                  "name": "Connection",
                  "value": "keep-alive"
                },
                {
                  "name": "Cookie",
                  "value": "1caa5c4232b1a1f24f8c4f6e0f496284=584847486e407abc7406f93ce15a0d6a; session=fPnHK7xHb5v7-jgwnLIJSFiiMLjl_rkZWqdcu_U1ucT3PaUSFH_Xi_HJ_6c51MEqGB_oMHDZV9kjMd31iYvpHoAElUkAAAAAAAAASlrN711HQdd78ibSUUZ9lIwHX2NzcmZ0X5SMKDM3NTNjNzViODg1MWI0ODdhYzQ4NzdhNGI3MmQ2MjkzODQwNWQ3NmWUc4eULg; auth_tkt=e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw%3D!userid_type:b64unicode; auth_tkt=e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw%3D!userid_type:b64unicode"
                },
                {
                  "name": "TE",
                  "value": "Trailers"
                }
              ],
              "cookies": [
                {
                  "name": "1caa5c4232b1a1f24f8c4f6e0f496284",
                  "value": "584847486e407abc7406f93ce15a0d6a"
                },
                {
                  "name": "session",
                  "value": "fPnHK7xHb5v7-jgwnLIJSFiiMLjl_rkZWqdcu_U1ucT3PaUSFH_Xi_HJ_6c51MEqGB_oMHDZV9kjMd31iYvpHoAElUkAAAAAAAAASlrN711HQdd78ibSUUZ9lIwHX2NzcmZ0X5SMKDM3NTNjNzViODg1MWI0ODdhYzQ4NzdhNGI3MmQ2MjkzODQwNWQ3NmWUc4eULg"
                },
                {
                  "name": "auth_tkt",
                  "value": "e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw=!userid_type:b64unicode"
                },
                {
                  "name": "auth_tkt",
                  "value": "e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw=!userid_type:b64unicode"
                }
              ],
              "queryString": [
                {
                  "name": "text",
                  "value": "test comment #3"
                }
              ],
              "headersSize": 1093
            },
            "response": {
              "status": 200,
              "statusText": "OK",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "date",
                  "value": "Tue, 10 Dec 2019 17:00:51 GMT"
                },
                {
                  "name": "server",
                  "value": "Apache/2.4.41 (Fedora) mod_wsgi/4.6.4 Python/3.7"
                },
                {
                  "name": "strict-transport-security",
                  "value": "max-age=31536000; includeSubDomains; preload"
                },
                {
                  "name": "x-frame-options",
                  "value": "SAMEORIGIN"
                },
                {
                  "name": "x-xss-protection",
                  "value": "1; mode=block"
                },
                {
                  "name": "x-content-type-options",
                  "value": "nosniff"
                },
                {
                  "name": "referrer-policy",
                  "value": "same-origin"
                },
                {
                  "name": "content-length",
                  "value": "64"
                },
                {
                  "name": "x-content-type-options",
                  "value": "nosniff"
                },
                {
                  "name": "content-type",
                  "value": "application/json"
                },
                {
                  "name": "apptime",
                  "value": "D=11760"
                },
                {
                  "name": "x-fedora-proxyserver",
                  "value": "proxy01.stg.phx2.fedoraproject.org"
                },
                {
                  "name": "x-fedora-requestid",
                  "value": "Xe-PQ@qeX9AFmqYiLHMJJAAAABE"
                },
                {
                  "name": "X-Firefox-Spdy",
                  "value": "h2"
                }
              ],
              "cookies": [],
              "content": {
                "mimeType": "application/json",
                "size": 64,
                "text": "{\"html\": \"<div class=\\\"markdown\\\"><p>test comment #3</p></div>\"}"
              },
              "redirectURL": "",
              "headersSize": 518,
              "bodySize": 582
            },
            "cache": {},
            "timings": {
              "blocked": 0,
              "dns": 0,
              "connect": 0,
              "ssl": 0,
              "send": 0,
              "wait": 74,
              "receive": 0
            },
            "time": 74,
            "_securityState": "secure",
            "serverIPAddress": "209.132.181.5",
            "connection": "443"
          },
          {
            "pageref": "page_1",
            "startedDateTime": "2019-12-10T09:00:56.228-08:00",
            "request": {
              "bodySize": 1248,
              "method": "POST",
              "url": "https://bodhi.stg.fedoraproject.org/comments/",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "Host",
                  "value": "bodhi.stg.fedoraproject.org"
                },
                {
                  "name": "User-Agent",
                  "value": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
                },
                {
                  "name": "Accept",
                  "value": "application/json, text/javascript, */*; q=0.01"
                },
                {
                  "name": "Accept-Language",
                  "value": "en-US,en;q=0.5"
                },
                {
                  "name": "Accept-Encoding",
                  "value": "gzip, deflate, br"
                },
                {
                  "name": "Referer",
                  "value": "https://bodhi.stg.fedoraproject.org/updates/FEDORA-2019-8b21f399ee"
                },
                {
                  "name": "Content-Type",
                  "value": "application/json"
                },
                {
                  "name": "X-Requested-With",
                  "value": "XMLHttpRequest"
                },
                {
                  "name": "Content-Length",
                  "value": "1248"
                },
                {
                  "name": "Origin",
                  "value": "https://bodhi.stg.fedoraproject.org"
                },
                {
                  "name": "DNT",
                  "value": "1"
                },
                {
                  "name": "Connection",
                  "value": "keep-alive"
                },
                {
                  "name": "Cookie",
                  "value": "1caa5c4232b1a1f24f8c4f6e0f496284=584847486e407abc7406f93ce15a0d6a; session=fPnHK7xHb5v7-jgwnLIJSFiiMLjl_rkZWqdcu_U1ucT3PaUSFH_Xi_HJ_6c51MEqGB_oMHDZV9kjMd31iYvpHoAElUkAAAAAAAAASlrN711HQdd78ibSUUZ9lIwHX2NzcmZ0X5SMKDM3NTNjNzViODg1MWI0ODdhYzQ4NzdhNGI3MmQ2MjkzODQwNWQ3NmWUc4eULg; auth_tkt=e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw%3D!userid_type:b64unicode; auth_tkt=e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw%3D!userid_type:b64unicode"
                },
                {
                  "name": "TE",
                  "value": "Trailers"
                }
              ],
              "cookies": [
                {
                  "name": "1caa5c4232b1a1f24f8c4f6e0f496284",
                  "value": "584847486e407abc7406f93ce15a0d6a"
                },
                {
                  "name": "session",
                  "value": "fPnHK7xHb5v7-jgwnLIJSFiiMLjl_rkZWqdcu_U1ucT3PaUSFH_Xi_HJ_6c51MEqGB_oMHDZV9kjMd31iYvpHoAElUkAAAAAAAAASlrN711HQdd78ibSUUZ9lIwHX2NzcmZ0X5SMKDM3NTNjNzViODg1MWI0ODdhYzQ4NzdhNGI3MmQ2MjkzODQwNWQ3NmWUc4eULg"
                },
                {
                  "name": "auth_tkt",
                  "value": "e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw=!userid_type:b64unicode"
                },
                {
                  "name": "auth_tkt",
                  "value": "e8a20617056cdc5265f79ec434e1768b04d47ee878e4dcfa887817902a9fd674637e598475f855db57788f88a553125c6c39cd43c783312356ca7333998ffaa75defc8a3YWRhbXdpbGw=!userid_type:b64unicode"
                }
              ],
              "queryString": [],
              "headersSize": 1171,
              "postData": {
                "mimeType": "application/json",
                "params": [],
                "text": "{\"csrf_token\":\"3753c75b8851b487ac4877a4b72d62938405d76e\",\"update\":\"FEDORA-2019-8b21f399ee\",\"text\":\"test comment #3\",\"karma\":\"0\",\"bug_feedback.0.bug_id\":\"1414865\",\"bug_feedback.0.karma\":\"0\",\"bug_feedback.1.bug_id\":\"1669057\",\"bug_feedback.1.karma\":\"0\",\"bug_feedback.2.bug_id\":\"1677889\",\"bug_feedback.2.karma\":\"0\",\"bug_feedback.3.bug_id\":\"1705734\",\"bug_feedback.3.karma\":\"0\",\"bug_feedback.4.bug_id\":\"1712973\",\"bug_feedback.4.karma\":\"0\",\"bug_feedback.5.bug_id\":\"1721707\",\"bug_feedback.5.karma\":\"0\",\"bug_feedback.6.bug_id\":\"1721710\",\"bug_feedback.6.karma\":\"0\",\"bug_feedback.7.bug_id\":\"1722588\",\"bug_feedback.7.karma\":\"0\",\"bug_feedback.8.bug_id\":\"1722862\",\"bug_feedback.8.karma\":\"0\",\"bug_feedback.9.bug_id\":\"1723050\",\"bug_feedback.9.karma\":\"0\",\"bug_feedback.10.bug_id\":\"1723146\",\"bug_feedback.10.karma\":\"0\",\"bug_feedback.11.bug_id\":\"1724231\",\"bug_feedback.11.karma\":\"0\",\"bug_feedback.12.bug_id\":\"1728096\",\"bug_feedback.12.karma\":\"0\",\"bug_feedback.13.bug_id\":\"1729969\",\"bug_feedback.13.karma\":\"0\",\"bug_feedback.14.bug_id\":\"1733753\",\"bug_feedback.14.karma\":\"0\",\"bug_feedback.15.bug_id\":\"1739537\",\"bug_feedback.15.karma\":\"0\",\"bug_feedback.16.bug_id\":\"1740403\",\"bug_feedback.16.karma\":\"0\",\"bug_feedback.17.bug_id\":\"1741371\",\"bug_feedback.17.karma\":\"0\",\"\":[]}"
              }
            },
            "response": {
              "status": 504,
              "statusText": "Gateway Timeout",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "date",
                  "value": "Tue, 10 Dec 2019 17:00:56 GMT"
                },
                {
                  "name": "server",
                  "value": "Apache"
                },
                {
                  "name": "strict-transport-security",
                  "value": "max-age=31536000; includeSubDomains; preload"
                },
                {
                  "name": "x-frame-options",
                  "value": "SAMEORIGIN"
                },
                {
                  "name": "x-xss-protection",
                  "value": "1; mode=block"
                },
                {
                  "name": "x-content-type-options",
                  "value": "nosniff"
                },
                {
                  "name": "referrer-policy",
                  "value": "same-origin"
                },
                {
                  "name": "cache-control",
                  "value": "no-cache"
                },
                {
                  "name": "content-type",
                  "value": "text/html"
                },
                {
                  "name": "apptime",
                  "value": "D=30005795"
                },
                {
                  "name": "x-fedora-proxyserver",
                  "value": "proxy01.stg.phx2.fedoraproject.org"
                },
                {
                  "name": "x-fedora-requestid",
                  "value": "Xe-PSOqeX9AFmqYiLHMKgwAAABM"
                },
                {
                  "name": "X-Firefox-Spdy",
                  "value": "h2"
                }
              ],
              "cookies": [],
              "content": {
                "mimeType": "text/html",
                "size": 92,
                "text": "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"
              },
              "redirectURL": "",
              "headersSize": 481,
              "bodySize": 573
            },
            "cache": {},
            "timings": {
              "blocked": 0,
              "dns": 0,
              "connect": 0,
              "ssl": 0,
              "send": 0,
              "wait": 30066,
              "receive": 0
            },
            "time": 30066,
            "_securityState": "secure",
            "serverIPAddress": "209.132.181.5",
            "connection": "443"
          }
        ]
      }
    }

**Comment by AdamWill** [comment]
FWIW, I poked about in the code a bit trying to figure out *why* saving a comment to an update with a lot of builds takes a long time, but it's not particularly obvious so I'd need to set up a development environment again and profile it. I couldn't justify the time that would take me today over work I'm actually specifically supposed to be doing, so I didn't do it. I may do it at a later date.
