### ISSUE TITLE
Error encountered getting candidate builds from koji

### ISSUE THREAD

**Issue by adelton** [fedora-infra/bodhi#3843]
When creating new update at https://bodhi.fedoraproject.org/updates/new or editting existing one for example at https://bodhi.fedoraproject.org/updates/FEDORA-2019-b921e33fb0/edit, Build lookup fails with error notification "Error encountered getting candidate builds from koji".

**Comment by stransky** [comment]
I have the same problem,  I can't get Firefox builds (https://koji.fedoraproject.org/koji/buildinfo?buildID=1420744)

**Comment by mattiaverga** [comment]
duplicate of #3841

**Comment by adelton** [comment]
Closing as dupe of https://github.com/fedora-infra/bodhi/issues/3841.
