### ISSUE TITLE
When update is autopushed, don't send both 'update can now be pushed' and 'update has been pushed' notifications

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#3846]
When an update has autopush-for-time enabled, at the point the time threshold for pushing is reached, Bodhi adds *two* comments and sends *two* emails basically simultaneously: the first to say the update can now be pushed to stable, and the second to say it has been pushed stable.

This is entirely unnecessary. If autopush by time is disabled it makes sense to add a comment/send a mail saying the update "can now be pushed stable", but it makes no sense to send two mails if autopush is enabled. I don't really care in detail how it's implemented, but in this situation, Bodhi should add *one* comment and send *one* email to describe the situation (the update reached its autopush threshold and was pushed automatically).

**Comment by richardgreg** [comment]
@AdamWill @cverna I want to investigate this. Where should I start looking?

**Comment by cverna** [comment]
@richardgreg I would start looking here --> https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/tasks/approve_testing.py

This is the tasks that will check if an update can be pushed to stable or not.

**Comment by ryanlerch** [comment]
This PR / Issue was included in the 5.7.0 release of Bodhi, and is now deployed in Fedora Staging. Please verify and test that this works as expected.

https://bodhi.stg.fedoraproject.org/
