### ISSUE TITLE
Updates from rawhide do not close bugs properly

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#3851]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-770c3761ba

This set bug status to MODIFIED, but it did not close it when update went stable.

**Comment by cverna** [comment]
is this still happening ? if not I think we can close this ticket

**Comment by mattiaverga** [comment]
I think this was fixed long ago (at least, it seems to work now), so I'm going to close the ticket. Feel free to reopen if needed.
