### ISSUE TITLE
UpdateReadyForTestingV1 needs to be sent only for rpm build updates

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3855]
For other content (modules, flatpaks, containers) a new message will be needed.

We should check the `update.content_type` in `_ready_for_testing` method and only send the message if the contentType is rpm.

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L3900

**Comment by sebwoj** [comment]
> For other content (modules, flatpaks, containers) a new message will be needed.

Any requirements?

**Comment by AdamWill** [comment]
"For other content (modules, flatpaks, containers) a new message will be needed."

Why?

This is the only message that is *only* sent for RPM-based updates. AFAICT, there's no particular reason why that should be the case.

No "new message" ever appears to have been created for modules, flatpaks or containers.
