### ISSUE TITLE
bodhi push/compose failures

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#3856]
Lately we are hitting lot of compose failures with the following error:

```
This session is in 'committed' state; no further SQL can be emitted within this transaction.
```

Although, a resume of the pushes is fixing them, but it would be better to fix this.

This is not high priority as such, but a fix is appreciated.

**Comment by cverna** [comment]
Fixed by https://github.com/fedora-infra/bodhi/pull/3853 :). We will try to deploy that soon
