### ISSUE TITLE
Updates stuck in pending

### ISSUE THREAD

**Issue by michaelkuhn** [fedora-infra/bodhi#3862]
I created three updates yesterday. While one went through without a problem, two showed a `504 Gateway Time-out` error and are since stuck in pending:
1. https://bodhi.fedoraproject.org/updates/FEDORA-2019-4e9131663f
2. https://bodhi.fedoraproject.org/updates/FEDORA-2019-6aeb5f8619

Trying to change them in the web interface just does nothing and a `bodhi updates edit` also times out with the same error message:
```
fedora.client.ServerError: ServerError(https://bodhi.fedoraproject.org/updates/, 504, Error returned from json module while processing b'https://bodhi.fedoraproject.org/updates/': b'Expecting value: line 1 column 1 (char 0)'
b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n")
```

**Comment by cverna** [comment]
We have been experiencing some problems with bodhi in production. I see that your updates are now in testing so going to clone this.

Thanks for the report
