### ISSUE TITLE
empty update title makes it un-clickable in list views due to empty <a> element

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#3877]
I just noticed that if somebody sets the update title to an empty string (or it accidentally gets assigned an empty string), the created update is not clickable in list views since the generated `<a href=URL></a>` element is empty.

For example: https://bodhi.fedoraproject.org/updates/FEDORA-2019-110533d946

Not sure if this link is going to be valid for long:
https://bodhi.fedoraproject.org/updates/?status=pending&releases=F31&page=6

But there are multiple updates that are affected by this. Maybe a buggy version of the bodhi web interface inserted empty strings instead of leaving that argument as `None`.

![Screenshot from 2019-12-29 01-05-27](https://user-images.githubusercontent.com/12836693/71550735-6d7f7b00-29d7-11ea-88a2-03b081fd2f44.png)

**Comment by decathorpe** [comment]
@mattiaverga The linked PR is good, but it does not fix the issue I reported, and does not go far enough.

Stripping an empty string is still an empty string, and not `None`. The update I linked above already has an empty string set as the update's `display_name`, not some whitespace characters.

Empty strings should be prevented same as whitespace, and replaced by `None`.

---

EDIT: I see now that the `display_name` column is not nullable. But then I'm wondering why these updates look so broken in the bodhi web interface - is that a frontend issue then?

**Comment by mattiaverga** [comment]
@decathorpe I have tested locally that an empty string is managed just like None.
Actually, if you have the `display_name` property set to all whitespaces, these whitespaces are only stripped in the template, but not in backend, thus is not threated as None by the template.... yes, it's weird!
If you can edit those updates you could manually clean the `name` field (you must see the placeholder text, if not it means there are whitespaces in it)

@abompard we probably need to sanitize the database with a TRIM() on values of that column

**Comment by decathorpe** [comment]
@mattiaverga there's something weird going on.

I've checked every existing update up until Dec 31, and **NOT ONE** update has only whitespace (`str.isspace()`) set as their `display_name`, but a lot of them have the empty string.

You can verify it for the borked update https://bodhi.fedoraproject.org/updates/FEDORA-2019-110533d946:

```python3
ret = requests.get("https://bodhi.fedoraproject.org/updates/FEDORA-2019-110533d946").json()
s = ret["update"]["display_name"]  # ""
len(s) == 0  # true
```

So this is not an issue with whitespace, except if bodhi does some sanitation of values before generating JSON responses ...

**Comment by mattiaverga** [comment]
@decathorpe ah, that's a totally different problem: see #3471 
Some times ago, a bunch of void updates (without any build) have been created end it seems they're now stuck in Bodhi database. There are currently 16 void updates stuck: https://bodhi.fedoraproject.org/updates/?search=&status=pending&page=19
These updates shows an empty <a> element because they don't have any build to make their title showing up...

@abompard @cverna it seems these updates need to be manually cleaned out. There are also some strange updates in pending state since more than 3 years ago :-/

**Comment by mattiaverga** [comment]
Running a quick check on a local Vagrant environment with an updated database give:
```
>>> updates = m.Update.query.filter(m.Update.builds==None).all()
>>> len(updates)
36
>>> for update in updates:
...     print(update.alias)
... 
FEDORA-2015-13799
FEDORA-2015-f7d2f6b77c
FEDORA-2015-fde9b8aa65
FEDORA-2015-084442a526
FEDORA-2015-3933d6e71b
FEDORA-EPEL-2015-56f1789544
FEDORA-2015-8312a1422c
FEDORA-EPEL-2015-2d0e7de56f
FEDORA-2016-52e09c8358
FEDORA-EPEL-2016-0bc504f81d
FEDORA-2016-3745a3404a
FEDORA-2016-9683e48c38
FEDORA-2016-19d7f3d798
FEDORA-2016-2f3052d543
FEDORA-2016-796de36de3
FEDORA-2016-3122ec6414
FEDORA-2017-37b618a185
FEDORA-2019-48c30c6663
FEDORA-2019-1cfe355806
FEDORA-2019-2268266d31
FEDORA-EPEL-2019-d119182890
FEDORA-2019-bef5c0c3c8
FEDORA-EPEL-2019-0a394e5d23
FEDORA-EPEL-2019-e6890f4861
FEDORA-2019-1a9f460ddf
FEDORA-2019-0afb6633c8
FEDORA-2019-39027b3336
FEDORA-2019-240ae9127c
FEDORA-2019-521db81bfa
FEDORA-2019-3b596e447b
FEDORA-2019-e89227ba40
FEDORA-2019-12ed3b8473
FEDORA-2019-98ef2a04fc
FEDORA-2019-f57b34f7a0
FEDORA-2019-110533d946
FEDORA-2019-3875c36a14
```
