### ISSUE TITLE
Something broken with the push of gnupg2-2.2.18-2.fc30 update to stable

### ISSUE THREAD

**Issue by t8m** [fedora-infra/bodhi#3881]
The https://bodhi.fedoraproject.org/updates/FEDORA-2019-b436a3156c update has been automatically submitted for stable by bodhi however probably due to some misconfiguration or bug somewhere it got ejected from the update push. The build has the right tag f30-updates in koji however it is not present in the F30 updates repository.

**Comment by cverna** [comment]
this now fixed
