### ISSUE TITLE
not possible to create bug or testcase feedback via REST api

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#3888]
If I'm reading this correctly, the `/comments/` POST endpoint in the REST API (which calls the `Update.comment` method) expects lists of BugKarma and TestCaseKarma dictionaries when creating a new comment.

POST endpoint: https://github.com/fedora-infra/bodhi/blob/7265d5e267be9b46642d8679bada7608f743d5ed/bodhi/server/services/comments.py#L190-L200

Update.comment method: https://github.com/fedora-infra/bodhi/blob/7265d5e267be9b46642d8679bada7608f743d5ed/bodhi/server/models.py#L3193-L3195

Here, dictionaries are converted into `BugKarma` and `TestCaseKarma` instances by stuffing the dict items into the initializers as kwargs:
https://github.com/fedora-infra/bodhi/blob/7265d5e267be9b46642d8679bada7608f743d5ed/bodhi/server/models.py#L3276-L3284

This should work fine for bug feedback, since the numerical bug IDs are exposed in the `Bug` class, but for `TestCase`, the ID is not exposed (only the name) - but for creating new `TestCaseFeedback` instances, the `testcase_id` seems to be a required keyword argument.

It's not completely clear to me, since the logic is hidden behind kwargs and the initialization of the rather opaque `Base` class.

If the `testcase_id` really is required for creating new `TestCaseKarma` instances via the REST api, can the numerical ID please be included in JSON responses of `TestCase`?

**Comment by decathorpe** [comment]
Oof. So, I started digging through the code for the bodhi web interface, and found this:

https://github.com/fedora-infra/bodhi/blob/eaad747cba66fd98166a089c79175bd2f45945ac/bodhi/server/templates/update.html#L297-L303

Which looks like `testcase_name` is actually an accepted initializer for `TestcaseKarma` after all. I'll test that, and if it works, I'll close this bug since it's actually not a bug :sweat_smile:

**Comment by decathorpe** [comment]
Alright, I tried submitting test case feedback with `testcase_name` and `karma` values, but apparently that's not working, since it's not showing up in the web interface.

This is what the JSON body of the comment I'm sending looks like:

```json
{
    "update": "FEDORA-2020-194da76ba0",
    "text": "$VALUABLE_FEEDBACK",
    "karma": 1,
    "karma_critpath": null,
    "bug_feedback": null,
    "testcase_feedback": [
        {
            "karma": 1,
            "testcase_name": "QA:Testcase calc"
        }
    ],
    "csrf_token": "REDACTED"
}
```

**Comment by decathorpe** [comment]
Upon further investigation, submitting bug feedback is also impossible via the REST API.

**Comment by AdamWill** [comment]
Did you try catching a webUI submission 'in flight' to see the format it uses?

**Comment by decathorpe** [comment]
@AdamWill Well, I looked at the HTML form for the web UI, and it uses

- array of `{"bug_id": BUG_ID, "karma": KARMA}` for `bug_feedback`, and
- array of `{"testcase_name": TESTCASE_NAME, "karma": KARMA}` for `testcase_feedback`.

I've tried doing the same thing (numerical bug ID, testcase name as string, karma as signed integer) - the comment and karma submitted with the same request gets submitted, parsed, and displayed correctly, but the bug and testcase feedback is just **"lost"** somehow (so I'm not sure what the server does - I don't think it would just silently continue when encountering an exception?).

I've looked at the server code (the relevant lines are https://github.com/fedora-infra/bodhi/blob/7265d5e267be9b46642d8679bada7608f743d5ed/bodhi/server/models.py#L3276-L3284 ), and I don't see why it works via the web UI and not via the REST API.

What makes it worse, I don't know how the initializer for `Base` subclasses works, since that's internal to the DB stuff (I think?), so I can't even tell which attributes it expects to be present in the `__init__` constructor. Is it the testcase ID? the testcase name? which data types? The code doesn't specify, and the API documentation is "lacking" in this regard (it just lists `Sequence` data type for both bug and testcase feedback. Well, sequence of what? It's pretty much useless, so I tried to figure out the expected format by reading the server code, which didn't work (hence this bug report)

**Comment by mattiaverga** [comment]
I don't think comments can be posted through API calls: firstly, the POST request requires a CSRF token and secondly the comment submission service is protected by `cors_origins_rw` rules, which only allow the Bodhi server as source.
```
$ curl -H "Content-Type: application/json" -X POST -d '{"update": "FEDORA-2020-194da76ba0","text": "sick","karma": 1,"karma_critpath": null,"bug_feedback": null,"testcase_feedback": [{"karma": 1,"testcase_name": "QA:Testcase calc"}],"csrf_token": "REDACTED"}' https://bodhi.stg.fedoraproject.org/comments/
{"status": "error", "errors": [{"location": "body", "name": "csrf_token", "description": "CSRF tokens do not match.  This happens if you have the page open for a long time. Please reload the page and try to submit your data again. Make sure to save your input somewhere before reloading. "}]}
```

**Comment by decathorpe** [comment]
@mattiaverga of course comments can be posted through the API:

https://bodhi.fedoraproject.org/docs/server_api/rest/comments.html#service-1-POST

After all, posting comments via both the bodhi client (which uses the official bodhi python bindings) and via my rust bindings (and hence, both bodhi-cli and fedora-update-feedback) works just fine. You just have to supply a valid CSRF token with the request.

It's just that the `bug_feedback` and `testcase_feedback` parameters of the JSON request body are either discarded or ignored, and the API documentation doesn't specify the schema of accepted values.

**Comment by mattiaverga** [comment]
The webpage form actually sends JSON data in the following form:
```
{
    "csrf_token":"TOKEN",
    "update":"FEDORA-2020-194da76ba0",
    "text":"COMMENT",
    "karma":"1",
    "testcase_feedback.0.testcase_name":"QA:Testcase Gnome Accessibility",
    "testcase_feedback.0.karma":"1",
    "testcase_feedback.1.testcase_name":"QA:Testcase Gnome Classic mode",
    "testcase_feedback.1.karma":"0",
    "bug_feedback.0.bug_id":"1775633",
    "bug_feedback.0.karma":"1",
    "bug_feedback.1.bug_id":"1777690",
    "bug_feedback.1.karma":"0",
    "":[]
}
```
(the last line with the empty list is injected by the javascript which packs the data before sending, but I think that it's not required)

**Comment by decathorpe** [comment]
@mattiaverga wow, that's some ugly JSON :)

Thanks for looking into this, I'll try to adapt my code to use this schema.

**Comment by decathorpe** [comment]
It works! :tada:

Thank you for your help!

Maybe we can get the documentation for the API endpoint updated? It's far from obvious that bug and test case feedback needs to be formatted this weirdly :)
