### ISSUE TITLE
can't seem to add F31M bug to F31M update

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#3893]
I was trying to add a bug to https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2019-1a8b176b64 but Bodhi complains it doesn't manage the product of the bug.
Is this a known problem?

`Save` seems to just spin on endlessly - maybe it times out later...

**Comment by juhp** [comment]
Okay the timeout seems unrelated indeed but when the bug is added in the UI it complains with a warning:

```
Bug #1764604 doesn't seem to refer to a product that Bodhi manages updates for. Are you sure you want to reference it in this update? Bodhi will not be able to operate on this bug!
```

**Comment by mattiaverga** [comment]
It seems Bodhi's `production.ini` is misconfigured in ansible and overwrites Bodhi's default.
`bz_products = Fedora,Fedora EPEL` should be `bz_products = Fedora,Fedora EPEL,Fedora Modules`

@abompard @cverna can you have a look?

**Comment by cverna** [comment]
Yes https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/bodhi2/base/templates/production.ini.j2#n527

I can fix that.

**Comment by cverna** [comment]
https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=d802e4d4875c210deee178acd8638f296fd7a11b
