### ISSUE TITLE
Strange errors trying to remove a build from an update

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#390]
I tried to remove kf5-baloo from https://bodhi.fedoraproject.org/updates/FEDORA-2015-14270 by unchecking the box next to it.  When I clicked submit I got the following alerts:

ACL validation mechanism was unable to determine ACLs.

You may not specify an empty list of builds.

Required

Now, I may not have permission to edit this update, but none of these messages indicate that.

**Comment by mbooth101** [comment]
I see this too, after checking and then unchecking a build, then clicking submit.

**Comment by nirik** [comment]
Several folks on the devel list are also seeing this:

https://lists.fedoraproject.org/pipermail/devel/2015-August/213850.html

It seems to be tied to specific updates rather than specific users.

**Comment by ralphbean** [comment]
I'm 95% sure this is fixed now after the ``data-singleton`` patches in #400 and #446.

Please do re-open if you encounter it again.

Thanks for filing!
