### ISSUE TITLE
bodhi occasionally fails to publish to fedora-messaging when it ought to (`update.request.testing`, `update.edit` at least)

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#3904]
I noticed that openQA tested a 389-ds-base update for Fedora 31, but not an update for the same package for Fedora 30 that was submitted a few minutes later. Looking into it, it seems we got a [bodhi.update.request.testing message for the F31 update](https://apps.fedoraproject.org/datagrepper/id?id=2020-87b4ee60-1e32-4b6b-ac6f-02f043aa9c8a&is_raw=true&size=extra-large), but none was published for [the F30 update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-fb48098a19). I can't see any reason why a message should not have been published, so I'm filing this bug.

openQA won't test updates unless it sees a message for them, so this is restricting test coverage.

**Comment by AdamWill** [comment]
This wasn't a one-off. [Here's another case](https://bodhi.fedoraproject.org/updates/FEDORA-2020-4f5299af86). That update was submitted to testing on 2020-02-10 at 07:23:38 according to the web UI, but there is no `bodhi.update.request.testing` message logged in datagrepper, and openQA did not test it.

This is a serious problem, please take a look at it.

**Comment by abbra** [comment]
One more problem: https://bodhi.fedoraproject.org/updates/FEDORA-2020-62c54952b9 wasn't getting any OpenQA tests due to this bug.

**Comment by AdamWill** [comment]
[Here's another case](https://bodhi.fedoraproject.org/updates/FEDORA-2020-62c54952b9#comment-1263796). No `bodhi.update.edit` message is [logged in datagrepper](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.edit) for the edit @abbra made recently.

**Comment by AdamWill** [comment]
For the record, [this anaconda update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-52be94871e) looks like another case. I can't find any [update.request.testing message](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.request.testing&delta=172800) for it.

**Comment by AdamWill** [comment]
Saw another case today.

**Comment by mattiaverga** [comment]
This won't be fixed until Bodhi 5.2 is released. Unless we decide to hotfix production, since it breaks so many things... @cverna what do you think?
