### ISSUE TITLE
Autocomplete click versus tab key

### ISSUE THREAD

**Issue by jamesjer** [fedora-infra/bodhi#391]
I built new versions of gap-pkg-fga for F22+ tonight.  I went to bodhi to create F22 and F23 updates.  I typed in the name "gap-pkg-fga", saw that the autocomplete box just below matched and hit tab to go to the versions box.  Apparently, what I was supposed to do was click on the text in the autocomplete box.  In any case, I typed in the package versions for the update, added some update text, and pushed the Submit button, which then grayed out.  There was no error message, but several minutes later, there was no notification of success either.  I checked my update list.  Not there.  Figuring something had gone wrong, I went back and tried again, this time figuring out that I need to click on the autocomplete text, which then populated the version box for me.  Nice!  Except when I clicked the Submit button, I got this:

"Unable to create update. (IntegrityError) duplicate key value violates unique constraint "builds_nvr_key" DETAIL: Key (nvr)=(gap-pkg-fga-1.3.0-1.fc22) already exists. 'INSERT INTO builds (nvr, inherited, package_id, release_id, update_id) VALUES (%(nvr)s, %(inherited)s, %(package_id)s, %(release_id)s, %(update_id)s) RETURNING builds.id' {'package_id': 10296, 'release_id': None, 'update_id': None, 'nvr': u'gap-pkg-fga-1.3.0-1.fc22', 'inherited': False}

That error message is clearly intended for bodhi developers, not bodhi users.  How about logging messages like that somewhere where the bodhi developers can find them, and showing the users something more comprehensible, like "Hey, dummy, you already created an update with this package!"

Anyway, the updates finally showed up on my update list, so they were created successfully, but I thought I'd better file this anyway so that I can vote for (1) make tab out of the package name box == click on an exact match on the autocomplete list, and (2) change the duplicate update message to something comprehensible to mere mortals.  Thanks!  I like the looks of bodhi 2.

**Comment by ralphbean** [comment]
Good idea!  I'm going to split it into two issues to make it more manageable for bodhi devs.  We'll say **this** ticket is about the tab/click autocomplete issue.
