### ISSUE TITLE
Can't push Rawhide update manually

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#3912]
When I tried pushing update with merged side tag, it took some while, where I did not know what is going on. During that time, because I was impatient, I have disabled "Auto-request stable based on karma?", "Auto-request stable based on time?" and "Require testcases". Then it eventually got into testing, but there was no option to push it into stable.

I was told by @cverna, that I should re-enable "Auto-request stable based on time?", which seems to enable the auto push, but this is not obvious. It should either not be possible to disable everything or there should be option to push this manually.

[1]: https://bodhi.fedoraproject.org/updates/FEDORA-2020-223644200d

**Comment by cverna** [comment]
Yes I think we need to make it impossible to disable that setting for rawhide updates.
