### ISSUE TITLE
Update's test gating status has been changed to 'failed' but bodhi reports "1 of 1 required test results missing"

### ISSUE THREAD

**Issue by bachradsusi** [fedora-infra/bodhi#3913]
https://bodhi.fedoraproject.org/updates/FEDORA-2020-3f14ef5a84
I believe the test failed more than 10 hours ago, but according to bodhi test results missing. Also in "Automated Test Results" you can see:

    fedora-ci.koji-build.tier0.functional    -----   a few seconds ago

This value hasn't changed since yesterday

**Comment by AdamWill** [comment]
I think this got fixed? The update status did change to 'passed' at some point, anyway. Are you still seeing issues here?

**Comment by bachradsusi** [comment]
No, thanks, closing.
