### ISSUE TITLE
Auto obsoletion not working in rawhide

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3916]
Looking at the list of updates in Testing state for Rawhide, it seems there are some packages which are not obsoleted automatically. All those packages were failing gating tests and never reached the Stable state.
https://bodhi.fedoraproject.org/updates/?search=&status=testing&releases=F32

**Comment by mattiaverga** [comment]
What to do with updates which fail CI? Should they be unpushed instantly at failure, since they cannot reach stable?

**Comment by cverna** [comment]
I think we indented it that way when implementing the change (ie not have the update set to obsolete) but I am not sure why anymore :stuck_out_tongue: 

@pypingou do you remember ?

**Comment by pypingou** [comment]
If we obsolete a build -1 for -2 and -2 gets gated while -1 passed its tests, nothing would go out, in the current mode at least -1 goes out.

If -1 fails gating and -2 pass, then -1 will stay in limbo and -2 will go to stable.

However, I agree that we need a mechanism to allow withdrawing updates that failed gating.

**Comment by mattiaverga** [comment]
Unless I'm mistaken, the current workflow when adding a new update is:

1. Create package in db
2. Add builds
3. Create update with Update.new()
   1. Add update in db
   2. Set update.request to Testing if the update is not from sidetag (I don't understand where updates from sidetags are pushed to testing)
   3. Set test_gating_status to waiting
4. Set Koji tags
5. Obsolete older builds

So it seems to me that updates are pushed to Testing before CI gating.
https://github.com/fedora-infra/bodhi/blob/1be3f91c9da1b7ba1f7556999091511a674ad317/bodhi/server/models.py#L2279-L2286
In my opinion, the Update should stay in Pending and we must not set koji tags and obsolete builds  until we receive CI results, then we decide if it can be pushed to Testing and obsolete older builds or it should be unpushed instantly.
Instead I can't find anything in the code that gates the update based on its test_gating_status. Only the push to Stable is gated.

**Comment by pypingou** [comment]
On Sat, Feb 08, 2020 at 12:05:33AM -0800, Mattia Verga wrote:
>    Unless I'm mistaken, the current workflow when adding a new update is:
> 
>     1. Create package in db
>     2. Add builds
>     3. Create update with Update.new()
>          1. Add update in db
>          2. Set update.request to Testing if the update is not from sidetag
>             (I don't understand where updates from sidetags are pushed to
>             testing)
>          3. Set test_gating_status to waiting
>     4. Set Koji tags
>     5. Obsolete older builds
> 
>    So it seems to me that updates are pushed to Testing before CI gating.
>    https://github.com/fedora-infra/bodhi/blob/1be3f91c9da1b7ba1f7556999091511a674ad317/bodhi/server/models.py#L2279-L2286
>    In my opinion, the Update should stay in Pending until we receive CI
>    results, then we decide if it can be pushed to Testing and obsolete older
>    builds or it should be unpushed instantly.
>    Instead I can't find anything in the code that gates the update based on
>    its test_gating_status.

Couple of items missing from the description here:

a) we only automatically create updates for (single) build in rawhide, 
b) there is no testing repositoring in rawhide

So: pending == build is waiting to be signed
testing == CI is running
stable == available in the buildroot (not necessarily in the mirrors)

The code that moves updates based on its gating status is a celery bead which
replaces a cron job.

For stable releases, we announce (or should announce) that the update is ready
for testing when it's submitted to testing and again when it's submitted to
stable.
There the code that will leverage the gating status should part of the compose
(iirc :s)
