### ISSUE TITLE
bodhi has precognition powers

### ISSUE THREAD

**Issue by zdzichu** [fedora-infra/bodhi#392]
It seems bodhi2 will send update to stable *before* the update reaches required karma. It happens if karma will be added in near future.

Examples:
maradns-2.0.12-1.fc21 - https://bodhi.fedoraproject.org/updates/FEDORA-2015-14033
Push to stable: 38 minutes ago, 2015-08-27 05:56:03.214537
Karma reached: 37 minutes ago, 2015-08-27 05:56:25.204575

maradns-2.0.12-1.fc22 - https://bodhi.fedoraproject.org/updates/FEDORA-2015-14032
Push: 38 minutes ago, 2015-08-27 05:55:17.784630
Karma: 38 minutes ago, 2015-08-27 05:55:34.486011

maradns-2.0.12-1.fc23 - https://bodhi.fedoraproject.org/updates/FEDORA-2015-14034
Push: 39 minutes ago, 2015-08-27 05:54:39.445624
Karma: 39 minutes ago, 2015-08-27 05:54:53.652995

Bodhi pushes the package 15-20 before stable karma threshold is reached.

Also, on the main screen (link doesn't work) there's information about bodhi submitting 3-pack of updates before one of them reach karma threshold. 

![2015-08 bodhi too fast](https://cloud.githubusercontent.com/assets/496236/9514128/9db508c0-4c97-11e5-83b8-7a3ad47e1d0f.png)

**Comment by ralphbean** [comment]
Pretty crazy, huh?  :)

Take a look at the [history of the message bus](https://apps.fedoraproject.org/datagrepper/raw?package=maradns&category=bodhi&start=1440654179&end=1440671381) for maradns during that time period, you can see the same events you're reporting here.  If you drill down into the details, you can see that [the original comment](https://apps.fedoraproject.org/datagrepper/id?id=2015-64b2d00e-c2c4-42b2-9a4b-1d5f28dbf39e&is_raw=true&size=extra-large), [the "stable threshold reached" event](https://apps.fedoraproject.org/datagrepper/id?id=2015-294e9b58-58ec-4f6d-b02a-db42010ee3ea&is_raw=true&size=extra-large), and [the request for stable](https://apps.fedoraproject.org/datagrepper/id?id=2015-8ca51317-0057-4211-8520-2bccd6c2d4e5&is_raw=true&size=extra-large) all have exactly the same timestamp (there ought to be a millisecond different between them, but we don't have millisecond level accuracy in the fedmsg history.. it's a long story involving x509 and tiny differences in the ``json`` module between python2.6 and python2.7).  So, with the same timestamp, it's kind of up to chance as to how any particular view/presentation will sort the events.

You see how the "requests for stable" all get lumped into one event in the bodhi screenshot there?  We still need to do that for the "stable karma threshold" events.. and with many other events on the timeline.. but that's another issue.

That aside, is there anything for us to actually fix here?  Bodhi2 is not actually doing future magic, fedmsg just doesn't have a whole lot of timestamp precision.

**Comment by zdzichu** [comment]
If those events have the same timestamp (with tenth of second precision, it seems), then the times displayed by bodhi shouldn't be dispersed by couple of seconds. Especially that bodhi presents them with 10^-6 of second precision (how, original information did not have that order of precision).

**Comment by ralphbean** [comment]
Fixed by #471 which ensures that the messages only get produced *after* the database transaction has completed.
