### ISSUE TITLE
Get familiar with bodhi-shell

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3923]
# Summary
* Learn how to use bodhi-shell in the development environment to query and change the database.

## Background
A production database dump is used to populate the development environment database. It means that when running Bodhi from the development environment you have access to production like data. This is very useful in order to better understand how things work, or for example to investigate a bug.

The `bodhi-shell` application provides a Python shell which gives you access to the bodhi's database.   

There is a main task for this ticket:

## Learn how to query and change the database using bodhi-shell.

Run through the existing [documentation](https://bodhi.fedoraproject.org/docs/developer/vagrant.html) and execute the bodhi-shell example. Learn more about [SQLAlchemy](https://www.sqlalchemy.org/) and try to do some of the following tasks : 

* Get all the Updates in the "pending" state.
* Get all the Updates in the "pending" state for the Fedora 32 release .
* Get the package id of the build "firefox-72.0.2-3.fc30".
* Get all the builds for the "firefox" package using the package id from the previous step. 
* Query one update in the "pending" state and change its state to "stable".

When you complete this, post a comment of your code sample :+1:

**Comment by karmadolkar** [comment]
Hello @cverna! Could you please explain this task? What is the table or data we're accessing?

**Comment by karmadolkar** [comment]
I tried doing something like this to know the tables that exist in the production database https://stackoverflow.com/questions/21310549/list-database-tables-with-sqlalchemy/21346185
However, it's throwing an OperationalError. Could you please help? I'm having trouble understanding how to create an engine.

**Comment by cverna** [comment]
@karmadolkar so the goal of the task is to get familiar with Bodhi's  [models.py](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py) file.
This is where all the tables are declared using SQLAlchemy, for example the [Release class](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L755) will match the `releases` table in the postgresql database.

In the shell you can get for example all the Updates as follow:
```
>>> releases = s.query(m.Release).all()
```
or 
```
>>> releases = m.Release.query.all()
```

Hope that helps

**Comment by richardgreg** [comment]
@cverna 
#### Get all the Updates in the "pending" state.
`m.Release.query.filter_by(state=m.UpdateStatus.pending).all()`

#### Get all the Updates in the "pending" state for the Fedora 32 release.
`m.Release.query.filter_by(long_name = 'Fedora 32', state=m.UpdateStatus.pending).all()`

#### Get the package id of the build "firefox-72.0.2-3.fc30".
`m.Build.query.filter_by(nvr='firefox-72.0.2-3.fc30').all()`
From the result there is only a `release_id`. That is what I used for the next query.

#### Get all the builds for the "firefox" package using the package id from the previous step.
`m.Release.query.filter_by(id=28).one() || m.Release.query.get(28)`

#### Query one update in the "pending" state and change its state to "stable"
```
q = m.Release.query.filter_by(state=m.UpdateStatus.pending).first()
q.state = m.UpdateStatus.stable
s().commit()
```

**Comment by AnchalJain** [comment]
@cverna 

Get all the Updates in the "pending" state.
```
s.query(m.Release).filter_by(state=m.UpdateStatus.pending).all()
```
Get all the Updates in the "pending" state for the Fedora 32 release.
```
aliased=s().query(m.Release).filter_by(long_name="Fedora 32").first()
s().query(m.Update).filter_by(status=m.UpdateStatus.pending, release=aliased).all()
```
Get the package id of the build "firefox-72.0.2-3.fc30".
```
package_id=s().query(m.Build).filter_by(nvr="firefox-72.0.2-3.fc30").first().package_id
```
Get all the builds for the "firefox" package using the package id from the previous step.
```
s().query(m.Package).filter_by(name="firefox", id=package_id).first().builds
```
Query one update in the "pending" state and change its state to "stable"
```
u= s.query(m.Update).filter_by(status=m.UpdateStatus.pending).first()
u.status = m.UpdateStatus.stable
s().commit()
```

**Comment by karmadolkar** [comment]
@cverna 

1.) `m.Update.query.filter_by(status=m.UpdateStatus.pending).all()`

2.) `m.Release.query.filter_by(long_name = 'Fedora 32', state=m.UpdateStatus.pending).all()`

3.) `m.Build.query.filter_by(nvr='firefox-72.0.2-3.fc30').all()`

4.)`m.Build.query.filter_by(id=28).all()`

5.)
 ```
x=m.Update.query.filter_by(status=m.UpdateStatus.pending).one()
x.status = m.UpdateStatus.stable
s().commit()
```

**Comment by cverna** [comment]
> #### Get all the Updates in the "pending" state for the Fedora 32 release.
> 
> `m.Release.query.filter_by(long_name = 'Fedora 32', state=m.UpdateStatus.pending).all()`

This does not work, if you check the results of that query you get a list of Release object instead of Updates :-)

> #### Get all the builds for the "firefox" package using the package id from the previous step.
> 
> `m.Release.query.filter_by(id=28).one() || m.Release.query.get(28)`

This does not return a Release object no a list of builds. I suggest looking at the Package class in order to get a Package ID and see how to use that to query a list of Builds.

> #### Query one update in the "pending" state and change its state to "stable"
> 
> ```
> q = m.Release.query.filter_by(state=m.UpdateStatus.pending).first()
> q.state = m.UpdateStatus.stable
> s().commit()
> ```

Here too you are changing a Release object instead of an Update :-).

To all: 

I suggest to really spend a lot of time on this task, so that you gain a good understanding of the [models.py](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py) file and how to different classes works together. A lot of the project later will involve having to look at the relationship between these classes and understand how the current database works so don't be afraid to invest as much time as you need in this task to be comfortable working with [models.py](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py).

**Comment by sukkubm** [comment]
@cverna 

1. Get all the Updates in the "pending" state.
```PYTHON
m.Update.query.filter_by(status=m.UpdateStatus.pending).all()
```
2. Get all the Updates in the "pending" state for the Fedora 32 release .
```PYTHON
release = m.Release.query.filter_by(long_name="Fedora 32").first()
m.Update.query.filter_by(status=m.UpdateStatus.pending, release=release).all()
```
3. Get the package id of the build "firefox-72.0.2-3.fc30".
```PYTHON
package_id = m.Build.query.filter_by(nvr="firefox-72.0.2-3.fc30").first().package_id
```
4. Get all the builds for the "firefox" package using the package id from the previous step.
```PYTHON
m.Package.query.filter_by(name="firefox", id=package_id).first().builds
```
5. Query one update in the "pending" state and change its state to "stable".
```PYTHON
update = m.Update.query.filter_by(status=m.UpdateStatus.pending).first()
update.status = m.UpdateStatus.stable
s().commit()
```

**Comment by karmadolkar** [comment]
**1.) Get all the Updates in the "pending" state.**
`s.query(m.Update).filter(m.Update.status==m.UpdateStatus.pending).all()`

**2.) Get all the Updates in the "pending" state for the Fedora 32 release .**
```
x=m.Release.query.filter(m.Release.long_name=="Fedora 32").first()
for update in s.query(m.Update).filter(m.Update.status==m.UpdateStatus.pending, m.Update.release==x).all():
    print(update)
```
**3.) Get the package id of the build "firefox-72.0.2-3.fc30".**
`p_id=m.Build.query.filter(m.Build.nvr=='firefox-72.0.2-3.fc30').first().package_id`

**4.) Get all the builds for the "firefox" package using the package id from the previous step.**
```
for builds in s.query(m.Package).filter(m.Package.name=="firefox", m.Package.id==p_id).first().builds:
    print(builds)
```

**5.) Query one update in the "pending" state and change its state to "stable".**
```
update = s.query(m.Update).filter(m.Update.status==m.UpdateStatus.pending).first()
update.status = m.UpdateStatus.stable
s().commit()
```

@cverna

**Comment by richardgreg** [comment]
@cverna right. I hadn't taken a look at the models.py file and I was working with the schema from the development setup page. I have revised my queries accordingly.

#### Get all the Updates in the "pending" state.
```python
m.Update.query.filter_by(status=m.UpdateStatus.pending).all()
```

#### Get all the Updates in the "pending" state for the Fedora 32 release.
```python
fedora_32 = m.Release.query.filter_by(long_name='Fedora 32').one()
m.Update.query.filter_by(release=fedora_32, status=m.UpdateStatus.pending).all()
```

#### Get the package id of the build "firefox-72.0.2-3.fc30".
```python
firefox_build = m.Build.query.filter_by(nvr='firefox-72.0.2-3.fc30').one()
print(firefox_build.package_id)
```

#### Get all the builds for the "firefox" package using the package id from the previous step.
```python
firefox_package = m.Package.query.get(firefox_build.package_id)
print(firefox_package.builds)
```

Query one update in the "pending" state and change its state to "stable".
```python
one =  m.Update.query.filter_by(status=m.UpdateStatus.pending).first()
one.status = m.UpdateStatus.stable
s().commit()
```

**Comment by jennizalwango** [comment]
@cverna 

1. **Get all the Updates in the "pending" state.**
 >>> m.Update.query.filter_by(status=m.UpdateStatus.pending).first()

2.  **Get all the Updates in the "pending" state for the Fedora 32 release .**

>>> all_updates=m.Release.query.filter_by(long_name="Fedora 32").first()
>>> print(all_updates)
>>> m.Update.query.filter_by(release=all_updates, status=m.UpdateStatus.pending).all()

 3. **Get the package id of the build "firefox-72.0.2-3.fc30".**

>>> Pkge_id=m.Build.query.filter_by(nvr="firefox-72.0.2-3.fc30").first()
>>> Pkge_id.package_id

 4. **Get all the builds for the "firefox" package using the package id from the previous step.**

 >>> m.Package.query.filter_by(name="firefox", id=Pkge_id.package_id).first().builds


5. **Query one update in the "pending" state and change its state to "stable".**

>>> query_update=m.Update.query.filter_by(status=m.UpdateStatus.pending).first()
>>> query_update.status=m.UpdateStatus.stable
>>> s().commit()
>>> print(query_update)
