### ISSUE TITLE
Release notes not updated

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3928]
Bodhi release notes i production are not updated to 5.1.1, they're still show only till 5.1.0.

Also, the `news` directory on `develop` branch is not clean: it still contains news fragments already present in 5.1.0.

**Comment by richardgreg** [comment]
@mattiaverga I see what you mean in https://bodhi.fedoraproject.org/docs/user/release_notes.html. 

How does one go about rendering the latest contents `release_notes`?

**Comment by cverna** [comment]
I have prepared version 5.2 last week and that will fix this issue once it is deployed. See https://github.com/fedora-infra/bodhi/blob/develop/docs/user/release_notes.rst#v511
