### ISSUE TITLE
Drop/re-purpose the required taskotron checks

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3938]
Currently bodhi offers the possibility to gate an update based on user-specified taskotron checks. This appears in the UI under the field ``Required Taskotron checks``.

With taskotron going away, we should be able to drop this field/feature.

Note that we may be able to leverage some of the information/logic of this feature to gate updates for some (non-taskotron) tests.

**Comment by AdamWill** [comment]
So, this is all called "taskotron" but it's really "resultsdb". All it uses is resultsdb, which still exists.

*However*, it is essentially completely reinventing the entire mechanism we have with greenwave - including having a rather large chunk of code to query build timestamps from Koji(!) and then get results from resultsdb - but with fewer capabilities; notably it doesn't handle scenarios, so blocking on openqa tests is kinda broken (you can't really block on the KDE base_selinux test and the GNOME base_selinux test separately; all you can say is 'block on the base_selinux test' and it'll consider the result from whichever of the two tests finished most recently).

OTOH, it does provide a capability the Greenwave Industrial Complex doesn't give us: custom gating requirements *per update*. You can't really do that with Greenwave.

At the very least, we should drop the ability for requirements to be associated with packages (which causes all updates for those packages to inherit those requirements). That's just duplicating what the "`gating.yaml` in package repository" does (but without scenario support). And change every reference to 'taskotron' to say 'resultsdb' instead.

I'm not sure it's worth the large amount of code duplication to have the 'per update gating' functionality, and the fact that we have two mostly-redundant mechanisms here is pretty awkward architecturally. I'd personally be in favor of just dropping this capability. Can we check in the production DB if anyone is actually *using* it? i.e. if anyone has actually set any `requirements` for any updates in the last few years?

**Comment by AdamWill** [comment]
@hluk did you know Bodhi essentially has its own mini-greenwave inside it? If you didn't, you do now. :D See [here](https://github.com/fedora-infra/bodhi/blob/5791170483071446d32fd34fc564e47edff251f4/bodhi-server/bodhi/server/models.py#L3802) and [here](https://github.com/fedora-infra/bodhi/blob/5791170483071446d32fd34fc564e47edff251f4/bodhi-server/bodhi/server/util.py#L854)...

oh, and the other major limitation I can see in this mechanism is, it doesn't consider waivers.

There's some kinda...conceptual confusion around whether these requirements matter in different bits of Bodhi, as well. The `Update` model contains *two* methods for deciding if an update 'passes requirements': `Update.meets_testing_requirements()` (which does not consider this built-in taskotron/resultsdb requirements stuff, only Greenwave gating status), and `Update.check_requirements()` (which *does* consider this stuff, *as well as* Greenwave gating status).

Two things actually call `check_requirements`, AFAICT, and thus actually 'enforce' these internal "taskotron" requirements: the `set_request` function in `bodhi/server/services/updates.py`, which seems to back the `update_request` API endpoint, and `ComposerThread.perform_gating()` in `bodhi/server/tasks/composer.py`, which I think is a kinda final check when we're actually running an "update push" for a stable compose.

Other things use `meets_testing_requirements`, and so *ignore* the internal 'taskotron' requirements. Notably, for instance, `update.html` shows the option to push to stable so long as `meets_testing_requirements` is `True` - so if an update meets all the Greenwave gating requirements, but doesn't meet any requirements that were specified directly in Bodhi, I'm pretty sure we show the "Push to stable" button but it won't actually *work* (the push will be rejected).

Also notably, I think the "Rawhide autopush" mechanism ignores the internal 'taskotron' requirements. `bodhi/server/tasks/approve_testing.py` has an `approve_update` function, which is documented as only adding a comment on updates that can be pushed stable, but *actually* also goes ahead and submits them for stable for updates where `update.release.composed_by_bodhi` is `False` (which basically means Rawhide, and I think possibly ELN). It does this only if `update.meets_testing_requirements`, but it does *not* call `update.check_requirements`. So I *think*, if you try to set a Bodhi-level 'taskotron' requirement for a Rawhide update, it will not actually be taken into account unless you somehow have the update set such that it has to be *manually* pushed stable (not go through the automatic push).

There are a couple of other paths that use `meets_testing_requirements`, both inside the update model itself, but they don't seem as important (one affects whether a 'flash' is added to the update, the other is the "how long before this update can go stable" calculcation for update.html).

Another inconsistency I'm noticing while going through this stuff: `meets_testing_requirements` implements the 'minimum karma and days in testing' checks. `check_requirements` does *not*. So things which go through `meets_testing_requirements` check Greenwave gating and time/karma, but do *not* check Bodhi 'taskotron' requirements; things which go through `check_requirements` check Greenwave gating and Bodhi 'taskotron' requirements, but do *not* check time/karma. It seems likely that this could lead to odd inconsistencies.

Here's a handy ASCII table guide:

    METHOD                      CHECKS GREENWAVE    CHECKS "TASKOTRON" REQS     CHECKS TIME/CRITPATH    PATHS USING THE METHOD
    meets_testing_requirements  YES                 NO                          YES                     update.html "push to stable" button, approve_update() (Rawhide "autopush")
    check_requirements          YES                 YES                         NO                      set_request() (API update_request endpoint), ComposerThread.perform_gating()

**Comment by mattiaverga** [comment]
> Can we check in the production DB if anyone is actually _using_ it? i.e. if anyone has actually set any `requirements` for any updates in the last few years?

The database query shows that there are 88 updates with non-empty `requirements` property, nearly all of those are from 2019 (and a couple from 2015). I can provide the list, if you want to check them.

As updates requirements are also inherited from Package model, I've checked there also, but there is no package with `requirements` set (from a quick look, I didn't see how that property could be possibly set).

I'd be in favor of dropping the 'taskotron' stuff to simplify the code. Then we could try merging `meets_testing_requirements` and `check_requirements` so that only one exists to avoid confusion.

**Comment by AdamWill** [comment]
Thanks! Yeah, seeing the list might be useful, we might be able to tell if they were 'organic' uses or if someone was testing or something. I agree that dropping the stuff seems the most sensible option, I don't think the weight of all that code is worth it just to add one capability that apparently nobody has used in at least three years.

**Comment by mattiaverga** [comment]
```
FEDORA-2015-14170       rpmlint
FEDORA-2015-b06d4d9081  upgradepath
FEDORA-2017-828ccca3cf  dist.depcheck
FEDORA-2019-86217cbcd3  dist.rpmlint
FEDORA-2019-2e584862fd  dist.rpmlint
FEDORA-2019-819cea0584  dist.rpmlint
FEDORA-2019-617a616cb4  dist.rpmlint
FEDORA-2019-7ec39686a8  dist.rpmlint
FEDORA-2019-358d7dc330  dist.rpmlint
FEDORA-2019-b117aa881b  dist.rpmlint
FEDORA-2019-2a57b9b96b  dist.rpmlint
FEDORA-2019-08338407e7  dist.rpmlint
FEDORA-2019-14f919d9ee  dist.rpmlint
FEDORA-2019-6175efe854  dist.rpmlint
FEDORA-2019-35642e12e8  dist.rpmlint
FEDORA-2019-5d7567504e  dist.rpmlint
FEDORA-2019-da8f989bf2  dist.rpmlint
FEDORA-2019-bbcc4ceb0c  dist.rpmlint
FEDORA-2019-bd8570b5f8  dist.rpmlint
FEDORA-2019-b66b09e599  dist.rpmlint
FEDORA-2019-98192a3b90  dist.rpmlint
FEDORA-2019-81112593f3  dist.rpmlint
FEDORA-2019-48aa349cec  dist.rpmlint
FEDORA-2019-9a9a374c57  dist.rpmlint
FEDORA-2019-5ca1cf2874  dist.rpmlint
FEDORA-2019-8c1b78e3f3  dist.rpmlint
FEDORA-2019-8c026ae268  dist.rpmlint
FEDORA-2019-37b6e49d9b  dist.rpmlint
FEDORA-2019-781d86d783  dist.rpmlint
FEDORA-2019-c6ab079d28  dist.rpmlint
FEDORA-2019-a525430c85  dist.rpmlint
FEDORA-2019-a06434794f  dist.rpmlint
FEDORA-2019-5977d3e6a8  dist.rpmlint
FEDORA-2019-9ed3b11a07  dist.rpmlint
FEDORA-2019-b94471dc6e  dist.rpmlint
FEDORA-2019-227e897037  dist.rpmlint
FEDORA-2019-3306c0febe  dist.rpmlint
FEDORA-2019-5371cdad71  dist.rpmlint
FEDORA-2019-cc43591d84  dist.rpmlint
FEDORA-2019-ed848e6e8d  dist.rpmlint
FEDORA-2019-416c94e6a8  dist.rpmlint
FEDORA-2019-5ee4a58238  dist.rpmlint
FEDORA-2019-2ec5d11092  dist.rpmlint
FEDORA-2019-61c564a233  dist.rpmlint
FEDORA-2019-4465b03d20  dist.rpmlint
FEDORA-2019-e1b2872da7  dist.rpmlint
FEDORA-2019-0d0957b29e  dist.rpmlint
FEDORA-2019-65f9e8a62b  dist.rpmlint
FEDORA-2019-db766f9a01  dist.rpmlint
FEDORA-2019-bd99e73326  dist.rpmlint
FEDORA-2019-346f946181  dist.rpmlint
FEDORA-2019-865395fad4  dist.rpmlint
FEDORA-2019-ef234b929f  dist.rpmlint
FEDORA-2019-db62d8d105  dist.rpmlint
FEDORA-2019-7db739d56a  dist.rpmlint
FEDORA-2019-974a8effb3  dist.rpmlint
FEDORA-2019-aed1b709b7  dist.rpmlint
FEDORA-2019-655facb8bd  dist.rpmlint
FEDORA-2019-c6fe6a4db4  dist.rpmlint
FEDORA-2019-616cfc4472  dist.rpmlint
FEDORA-2019-03d35f08bf  dist.rpmlint
FEDORA-2019-66c66b1a10  dist.rpmlint
FEDORA-2019-730dfdf007  dist.rpmlint
FEDORA-2019-09b8e08fde  dist.rpmlint
FEDORA-2019-78d99e8a7d  dist.rpmlint
FEDORA-2019-1f200d036f  dist.rpmlint
FEDORA-2019-ad27bb6f70  dist.rpmlint
FEDORA-2019-e2d778cd88  dist.rpmlint
FEDORA-2019-63fb5bbf1a  dist.rpmlint
FEDORA-2019-4273e83775  dist.rpmlint
FEDORA-2019-30be86ee78  dist.rpmlint
FEDORA-2019-58f41f29b1  dist.rpmlint
FEDORA-2019-91fd4785ae  dist.rpmlint
FEDORA-2019-d3efc6b12f  dist.rpmlint
FEDORA-2019-2dfcf3de87  dist.rpmlint
FEDORA-2019-5de2d59483  dist.rpmlint
FEDORA-2019-5fed938cdf  dist.rpmlint
FEDORA-2019-66bf28cade  dist.rpmlint
FEDORA-2019-bc5be4a1dd  dist.rpmlint
FEDORA-2019-83bef31529  dist.rpmlint
FEDORA-2019-cd899ae9e6  dist.rpmlint
FEDORA-2019-d84013767b  dist.rpmlint
FEDORA-2019-7e861a4825  dist.rpmlint
FEDORA-2019-dfd62c0a82  dist.rpmlint
FEDORA-2019-6005ba4047  dist.rpmlint
FEDORA-2019-21e6a58a36  dist.rpmlint
FEDORA-2019-a3979d3ca3  dist.rpmlint
FEDORA-2019-017ff0998f  dist.rpmlint
```

**Comment by AdamWill** [comment]
@cottsay ahoy! Hope you don't mind the ping. Executive summary: we're considering yanking the "gate this specific update on some specific test" feature from Bodhi because it's a rather hoary codepath that causes a lot of complication and duplication (with the greenwave/gating.yaml option). As part of this we pulled a list of all the times anyone had ever actually used the feature - see above - and it looks like almost all of them were you, in 2019. So, we're interested in your take on this. Did you find it useful? Why did you stop using it? Do you see any problems with just removing it and telling people to use the gating.yaml path instead?

Thanks a lot!

**Comment by cottsay** [comment]
Greetings!

> Did you find it useful? Why did you stop using it? Do you see any problems with just removing it and telling people to use the gating.yaml path instead?

My main goal in enabling the gating was to prevent myself making stupid mistakes. It was a "low-cost" mechanism to enable, since I'd already curated `.rpmlintrc` files for my packages to get "clean" results from them.

I stopped using the gating only because I was fighting with changes to rpmlint and packaging standards and it made it harder to keep the packages "clean". If consistent results from rpmlint are now more reliable, I would certainly consider using `gating.yaml` instead.

Thanks for asking!

**Comment by AdamWill** [comment]
Thanks a lot for the reply, it's super helpful! I don't honestly know if much has changed with rpmlint, sorry. We were mainly concerned with the mechanisms at this point. It sounds like you really wanted to have the gating enabled for *all* updates for each package, ideally, right? So the greenwave/gating.yaml mechanism would indeed be sufficient for your needs so far as the gating mechanism goes, if I'm understanding correctly. Thanks a lot, that should give us more confidence in the current plan.

**Comment by cottsay** [comment]
> So the greenwave/gating.yaml mechanism would indeed be sufficient for your needs so far as the gating mechanism goes, if I'm understanding correctly.

I think it meets my needs even more than manually specifying the gates each time :)

**Comment by hluk** [comment]
> @hluk did you know Bodhi essentially has its own mini-greenwave inside it? If you didn't, you do now. :D See [here](https://github.com/fedora-infra/bodhi/blob/5791170483071446d32fd34fc564e47edff251f4/bodhi-server/bodhi/server/models.py#L3802) and [here](https://github.com/fedora-infra/bodhi/blob/5791170483071446d32fd34fc564e47edff251f4/bodhi-server/bodhi/server/util.py#L854)...

Very interesting. Is there any feature missing in Greenwave that would help with dropping the custom code in Bodhi?

BTW, it is possible to ask Greenwave for specific required test cases instead of using a fixed policy defined in Greenwave configuration (using `rules` instead of `decision_context` in the API query):

```
http https://greenwave.fedoraproject.org/api/v1.0/decision <<EOD
{
  "product_version": "f38",
  "subject_identifier": "selinux-policy-38.20-1.fc38",
  "subject_type": "koji_build",
  "verbose": true,
  "rules": [
    {
        "type": "PassingTestCaseRule",
        "test_case_name": "fedora-ci.koji-build.tier0.functional"
    },
    {
        "type": "PassingTestCaseRule",
        "test_case_name": "fedora-ci.koji-build.rpminspect.static-analysis"
    }
  ]
}
EOD

```

**Comment by AdamWill** [comment]
I'm working on this now. I have a commit that passes tests, I just need to look up how to add the db migration, and consider whether to include a follow-up commit that merges `meets_testing_requirements` and `check_requirements` (my initial commit just reduces `check_requirements` to a little stub that only checks gating status).

**Comment by AdamWill** [comment]
I'm working on the `meets_testing_requirements` vs. `check_requirements` thing now. It has, uh, kinda metastasized...

**Comment by mattiaverga** [comment]
> I'm working on the `meets_testing_requirements` vs. `check_requirements` thing now. It has, uh, kinda metastasized...

Do you want to have that change in 8.0 too?
I'd like to publish 8.0 release as soon as I get time, since staging is going smooth (for what we can test there...), so that we can close https://pagure.io/fedora-infrastructure/issue/11447 and a few other things. 
But let me know if there are other things you want to land before release.

**Comment by AdamWill** [comment]
No, it's probably best for it to come after. It's going to be a big change with some (intentional) differences in behaviour and it'll definitely want a careful review and some heads-up to packagers about the changes.

**Comment by AdamWill** [comment]
Finally submitted giganto-PR https://github.com/fedora-infra/bodhi/pull/5630 , which addresses the `meets_testing_requirements` vs. `check_requirements` thing. And, uh, lots of other stuff.
