### ISSUE TITLE
Stable push offered on edited update

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/bodhi#394]
Update https://bodhi.fedoraproject.org/updates/FEDORA-2015-14038 is showing me a "push to stable" button and claiming that the update was submitted over three days ago.

That's sort of correct, but also sort of incorrect. It was submitted some time ago, and was pushed to testing. It has since been edited however which should cause it to be withdrawn and repushed to testing with the clock starting over.

**Comment by tomhughes** [comment]
Any thoughts on this? I've changed it several more times but it never seems to get repushed to testing and is still offering push-to-stable but I'm reluctant to use that in case it doesn't work and because it may make it harder for you to debug this...

**Comment by ralphbean** [comment]
Go ahead and push it @tomhughes, I have a handle on what needs to be done for this.  Thanks!

**Comment by ralphbean** [comment]
Editing the update and changing the builds should now correctly reset the karma sum and resend the update to testing.  See #456 and #525.
