### ISSUE TITLE
Unable to create update. IntegrityError.. duplicate key value

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#395]
See #391 for a full description, but we need to catch Integrity errors from sqlalchemy in the new update service and transform them into something more user friendly before returning them via the caveats/errors API (it's not clear which error reporting route was used in #391..)

**Comment by ralphbean** [comment]
It would be nice to have the full traceback to work on this.

**Comment by bowlofeggs** [comment]
I have not observed this problem during my tenure on Bodhi, so I will close this. Feel free to reopen if you believe it is still an issue.
