### ISSUE TITLE
"fedpkg update" does not move bugs from "NEW"

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/bodhi#3954]
I submitted an update with `fedpkg update`:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-1ccdc325aa

There is a linked bug there, 1812692. It does not have the `initial_bug_msg` comment in the bug, and the bug is still in NEW instead of MODIFIED.

**Comment by mattiaverga** [comment]
Caused by #3904
