### ISSUE TITLE
UI shows an endless spinner for bugs

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/bodhi#3955]
I filed a new update at https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-1ccdc325aa 

The "BZ#1812692" entry on the main page (and on the "Bugs" tab) just shows a spinner endlessly spinning, and there is no other information for the bug in the Bodhi UI.

I loaded the page through Chrome Developer Tools, but I cannot see any xhr request that went out for this bug's data.

**Comment by ktdreyer** [comment]
![Screenshot_2020-03-11_16-53-25](https://user-images.githubusercontent.com/620295/76471796-48d15780-63b9-11ea-9854-94220e385d42.png)

**Comment by mattiaverga** [comment]
Caused by #3904
