### ISSUE TITLE
Stable by karma limit not displayed in update

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#3957]
![_](https://user-images.githubusercontent.com/2401856/76637525-2f601500-654b-11ea-986c-d292adf2db40.png)

https://bodhi.fedoraproject.org/updates/FEDORA-2020-f905273b27

There is **Unstable by Karma**, but no **Stable by Karma**

**Comment by mattiaverga** [comment]
This is the intended behavior: disabling the autokarma push will prevent the update to be automatically pushed to stable when `stable_karma threshold` is reached, but it will not prevent the update to be obsoleted if `unstable_karma` threshold is reached.

**Comment by hroncok** [comment]
I have not noticed the autopush is disabled. Maybe it should say so instead of the limit?

**Comment by mattiaverga** [comment]
Yes, we could show a `stable by karma: disabled` in the UI and also add a `stable by time: disabled` when appropriate.
We should also add a `Autotime: False` to the CLI output.

**Comment by richardgreg** [comment]
@mattiaverga pls assign me to this issue? Also, any hints about approaching the problem would be appreciated.

**Comment by mattiaverga** [comment]
@richardgreg for the UI part you will need to look in the update page template:
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/templates/update.html

For the CLI part you'll need to look in the `bindings.py` file the function responsible for printing the update details and add the missing part. And modify the tests accordingly.
