### ISSUE TITLE
Fix the pushed flag for old migrated updates

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#396]
I can see "Edit" and "Push to Testing" buttons on updates that are already in stable. Bodhi should disallow editing and hide the buttons for stable updates.

![push-to-stable](https://cloud.githubusercontent.com/assets/498858/9520108/856d1262-4cc4-11e5-82c0-51ccc10c5520.png)

**Comment by ralphbean** [comment]
This is actually a migration issue.  :(  The ``pushed`` boolean flag didn't get copied over from the old bodhi1 db.

**Comment by kalev** [comment]
I am not sure it's only about migration; https://bodhi.fedoraproject.org/updates/FEDORA-2015-13858 is an update that was submitted in the new Bodhi and it also has "Edit" and "Push to Testing" buttons.

**Comment by ryanlerch** [comment]
@kalev is this one still an issue? Just checked a couple of updates of mine that are in Stable, and the edit and push buttons are not displayed anymore.

**Comment by kalev** [comment]
Seems to be working right here too. Thanks.
