### ISSUE TITLE
Search bar on landing page apparently does nothing

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/bodhi#3962]
Using either Firefox or Epiphany, the search bar on [bodhi's homepage](https://bodhi.fedoraproject.org/?term=foo) seems to do nothing. It just reloads the current page and does not perform any search. In contrast, the search bar on [the updates page](https://bodhi.fedoraproject.org/updates/?search=foo) works perfectly fine. It would be nice if the search bar on the homepage would search for updates like the search bar on the updates pages does. Otherwise, it should be removed.

**Comment by mattiaverga** [comment]
The searchbar is not meant to be used by entering text and pressing enter. You must select one of the results that are showed in the list:
![immagine](https://user-images.githubusercontent.com/17218209/77092614-3e8f0900-6a0a-11ea-94a2-49a57a07ad1e.png)

The submit event should be disabled at all.
However, I'm working on completely replace the component behind this, so I'll let this open to remember me of taking care of this also in the new UI.

**Comment by mcatanzaro** [comment]
Ahh... I see... I can confirm it does work properly as long as I don't press Enter!
