### ISSUE TITLE
unable to use bodhi web ui, get 3 errors: ACL validation mechanism wsa unable to determin ACLs...

### ISSUE THREAD

**Issue by rdieter** [fedora-infra/bodhi#397]
Per summary, I've been unable to use bodhi web ui at all since yesterday... Tried several browsers (chrome, firefox mostly), (force) reloads, nothing seems to help,

Whenever I try to submit a new update or edit and existing one, it fails with 3 popup errors:
* ACL validation mechanism was unable to determine ACLs
* You may not specify an empty list of builds (I assure you the checked list is non-empty)
* Required (yep, that's it, just one word)

**Comment by rdieter** [comment]
Fwiw, I was able to use 'fedpkg update' to submit a new one today at least.

**Comment by ralphbean** [comment]
@rdieter can you link me to an example of an update you were trying to edit that caught this?

And, if you have a moment to sink on this.. can you post a screenshot of a form you were trying to submit before you got the error (you'd have to go back and re-create it, which would be a pain...)

**Comment by rdieter** [comment]
OK, snapshots before
https://rdieter.fedorapeople.org/bodhi3.png
and after hitting Edit
https://rdieter.fedorapeople.org/bodhi4.png

**Comment by rdieter** [comment]
The update in question is/was:
admin.fedoraproject.org/updates/FEDORA-2015-14270
