### ISSUE TITLE
broken comments help (missing markdown link, broken privacy link)

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#3971]
This is how the comments help looks now:
![bodhi](https://user-images.githubusercontent.com/755451/77542973-48e85180-6ea7-11ea-9178-d46847436a4b.png)

"Fedora-flavored Markdown" is no longer a link - it used to be a link, even though I don't know where exactly it pointed. Now, nobody can figure out what the Fedora enhancements are.

Privacy policy link is broken, you can see its actual value in the bottom left corner.

 bodhi-5.2.2

**Comment by kparal** [comment]
@richardgreg @mattiaverga Should I open a separate issue for the missing markdown link? Or will you reopen this ticket? Because the privacy policy link was just one of two issues mentioned here. Thanks.

**Comment by cverna** [comment]
@kparal the markdown link will be address in this PR https://github.com/fedora-infra/bodhi/pull/3985. So I don't think we need a second issue for it :smile:

**Comment by kparal** [comment]
Great, thanks
