### ISSUE TITLE
Can't add bugs to errata

### ISSUE THREAD

**Issue by adelton** [fedora-infra/bodhi#3982]
When Fedora rawhide build is finished in koji, errata is automatically created in bodhi, for example https://bodhi.fedoraproject.org/updates/FEDORA-2020-b1136cde72. I'd like the related bugzilla to be autoclosed when the errata gets pushed, so I rush to the errata to edit it, to add bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1814917, before that errata switches to stable (?) and cannot be edited anymore.
However, for the past week or so, looking up bugs in the errata Edit form via the "search and add bugs" does not work -- the spinner on the right keeps spinning and even if I put in the full bugzilla number and click on the pulldown "Add 1814917 ...", it never finishes, and when I click elsewhere in the form, the bugzilla number disappears and cannot be Saved.

**Comment by mattiaverga** [comment]
Adding bugs automatically to rawhide updates is something planned in #3956 

About the update form, it's strange: I don't have any problem adding bugs even by filling the bug number directly. Do you have any script blocker activated in your browser?

**Comment by adelton** [comment]
I have some cookie and ad blockers. Let me try to disable them the next time I do a Fedora package update.

**Comment by adelton** [comment]
I've verified that it's Privacy Badger addon which causes the bug lookup to fail/never finish.

**Comment by mattiaverga** [comment]
Thanks for the info.
There's nothing we can do to prevent Privacy Badger to block requests to Bugzilla. You should set up Privacy Badger to allow that.

For the notes, I've just tried to install Privacy Badger and with a fresh installation it doesn't block Bodhi's javascript by default.
