### ISSUE TITLE
Bad characters in username

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#3993]
There's a bot with a bad username of `packagerbot/os-master01.phx2.fedoraproject.org` that makes CI tests failing.
https://bodhi.fedoraproject.org/users/packagerbot/os-master01.phx2.fedoraproject.org

I'm pushing a PR to safe check CI tests, but do we want to make Bodhi safe to bad usernames like this? Since usernames are from outside world, should we modify them in a safe way before storing in the database?

**Comment by cverna** [comment]
> There's a bot with a bad username of `packagerbot/os-master01.phx2.fedoraproject.org` that makes CI tests failing.
> https://bodhi.fedoraproject.org/users/packagerbot/os-master01.phx2.fedoraproject.org
> 
> I'm pushing a PR to safe check CI tests, but do we want to make Bodhi safe to bad usernames like this? Since usernames are from outside world, should we modify them in a safe way before storing in the database?

Yeah I think we could transform the '/' by '_' for example before creating the user in the database.

**Comment by AdamSaleh** [comment]
I for one think it is a very good bot username, because it reflects its kerberos principal :-)

**Comment by AdamSaleh** [comment]
(I do understand why it can be a problem)

**Comment by mattiaverga** [comment]
After some thought, modifying the username in our db with arbitrary rules can be dangerous and can produce unexpected behavior.
For example, replacing all non alfanumeric characters with `_` we may end to identifying two different users with the same internal username.

Since we don't have any issue having those bad usernames in database, I'd let them unchanged. We only have to address how to produce safe URLs for those usernames.
By replacing characters on the fly, we get back to the former problem. So, two possible solutions are to replace username in URLs with user id or to add a new unique field to the User model like "url_id" and use that.
I would go for the second one, since it would not change current URLs for real users and also it would be user friendlier.

What do you think?

**Comment by mattiaverga** [comment]
So, as discussed in my retired PR, we have to decide how should we manage situations like this:

- store a URL friendly username along with the real username, like in my PR.
- prevent bad usernames to be used with Bodhi

Overall, I would prefer n.2: I have retired my PR because, even if it worked and is backwards compatible with the current situation, it seems awful to me to have a real username and a URL friendly username in database. And it brings confusion. But that's the only solution I could think to prevent two similar bad usernames to have the same URL if they're translated on the fly.

The second solution will imply to prevent bad usernames to operate in Bodhi. As far as I know, since the username is supposed to be compatible with OpenID, it should never break URLs, even with Bodhi instances other than Fedora's. Currently the only problematic username in Bodhi is that `packagerbot/os-master01.phx2.fedoraproject.org` that is not even coming from FAS.
