### ISSUE TITLE
Provide and use a YAML schema to validate gating test description

### ISSUE THREAD

**Issue by serge-sans-paille** [fedora-infra/bodhi#4000]
It would be nice to have an explicit YAML schema for tests lying in the tests/ directory of rpms. That way the gating infrastructure could provide more explicit errors in case of, say, mis-indentation of the test description. Maybe `fedpkg lint` could also perform some linting/ checks in the same spirit.

Note: I'm not 100% sure bodhi is the right place to report that, feel free to state it if that's not the case!

**Comment by cverna** [comment]
@serge-sans-paille Hi thanks for the report, indeed there is not much Bodhi can do to improve that situation. I believe that it would be better to file an issue [here](https://pagure.io/fedora-ci/general/issues) to start the discussion with the wider Fedora CI group.

**Comment by serge-sans-paille** [comment]
Thanks! Opened at https://pagure.io/fedora-ci/general/issue/105
