### ISSUE TITLE
Docs build failures with Sphinx 3

### ISSUE THREAD

**Issue by stratakis** [fedora-infra/bodhi#4008]
bodhi fails to build from source on Fedora with Sphinx 3 series.

Downstream bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1823739

Error:
Warning, treated as error:
/builddir/build/BUILD/bodhi-5.1.1/bodhi/server/models.py:docstring of bodhi.server.models.Bug.url:1:duplicate object description of bodhi.server.models.Bug.url, other instance in developer/docblocks/bodhi.server.models, use :noindex: for one of them
make: *** [Makefile:51: html] Error 2
make: Leaving directory '/builddir/build/BUILD/bodhi-5.1.1/docs'
error: Bad exit status from /var/tmp/rpm-tmp.A6849v (%build)

Sphinx 3 changelog: https://www.sphinx-doc.org/en/master/changes.html#release-3-0-0-released-apr-06-2020

**Comment by mattiaverga** [comment]
Possibly related to #1995

I think we can just drop the `url` column, since `Bug.url` is provided via the url property. I don't see anything in the code that stores the url in db.

**Comment by stratakis** [comment]
Trying a new build with either the patch applied or with version 5.3.0 I now get:

/builddir/build/BUILD/bodhi-5.3.0/bodhi/messages/schemas/base.py:docstring of bodhi.messages.schemas.base.BuildV1.nvr:1:duplicate object description of bodhi.messages.schemas.base.BuildV1.nvr, other instance in server_api/messages/base, use :noindex: for one of them
