### ISSUE TITLE
Cannot select package for the new update

### ISSUE THREAD

**Issue by perexg** [fedora-infra/bodhi#4015]
I cannot select https://koji.fedoraproject.org/koji/buildinfo?buildID=1473971 for unknown reason. Could you check, please?

**Comment by keszybz** [comment]
It has `tags: trashcan`. I would suggest just building it again, and submitting an update.

**Comment by perexg** [comment]
It's not possible. The build system complains that this version is already built.

**Comment by keszybz** [comment]
Yes. A version bump is necessary.

**Comment by mattiaverga** [comment]
Not a Bodhi fault, closing
