### ISSUE TITLE
No custom headers on Bodhi emails

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#402]
Emails from Bodhi 1.0 had several custom headers. It may have varied with different types of email, but one I just pulled out of my old Bodhi folder has these:

X-bodhi-update-builds: firewalld-0.3.13-7.fc22
X-bodhi-update-type: bugfix
X-bodhi-update-release: F22
X-bodhi-update-pushed: True
X-bodhi-update-title: firewalld-0.3.13-7.fc22
X-bodhi-update-status: stable
X-bodhi-update-submitter: sgallagh

Bodhi 2 emails don't seem to have any of those. This isn't critical stuff or anything, I was only using them for identifying Bodhi emails for filtering, and there's any number of other ways I could do that. But someone else may have been doing something smarter with them.

**Comment by kparal** [comment]
Just two days ago, the headers were present:
```
From: dvratil@fedoraproject.org
To: kparal@fedoraproject.org
X-Bodhi-Update-Builds: python-fedora-0.5.5-1.fc22
In-Reply-To: <bodhi-update-37080-ralph-F22@admin.fedoraproject.org>
X-Bodhi-Update-Pushed: False
X-Bodhi-Update-Type: bugfix
X-Bodhi-Update-Release: F22
References: <bodhi-update-37080-ralph-F22@admin.fedoraproject.org>
X-Bodhi-Update-Status: testing
X-Bodhi-Update-Request: stable
X-Bodhi-Update-Submitter: ralph
X-Bodhi-Update-Title: python-fedora-0.5.5-1.fc22
Subject: [Fedora Update] [comment] python-fedora-0.5.5-1.fc22
```

But today, the headers are gone:
```
From: ralph@fedoraproject.org
To: kparal@fedoraproject.org
Subject: [Fedora Update] [CRITPATH] [comment] btrfs-progs-4.1-1.fc20
```

This makes the update emails hard to filter (I'll need to rely on subject matching).

Also, is there a reason for setting the `From` header to the commenter's email? I'd rather see something like `From: noreply@bodhi.fedoraproject.org`. It would make filtering much easier (especially for those unfortunate people using Gmail, which can't filter according to any custom email headers).

**Comment by tyll** [comment]
the code seems to be there, maybe it is not used:
https://github.com/fedora-infra/bodhi/blob/dc525d9f7d4b3d13db8ae45fa839e2b2f704a998/bodhi/mail.py#L450
