### ISSUE TITLE
allow editing "from_tag" updates for stable releases

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4028]
According to @pypingou builds for updates created from side tags are just moved into the corresponding updates-testing tags, for stable releases, and the side tag is then deleted afterwards. The resulting update should be a "regular stable release update".

However, since the `from_tag` attribute stays set (to a then non-existent side tag) the update cannot be edited, since bodhi can't find the side tag any longer.

Can the `from_tag` attribute on updates be unset / set to `None` after all builds that are contained in the update have been tagged correctly and the side tag has been removed?

EDIT: I am aware that when adding new builds, users will then have to fall back to using buildroot overrides (since the side tag is gone at that point), but this would still be better in the case when I just want to edit some update metadata.

**Comment by mattiaverga** [comment]
Same as #4002
