### ISSUE TITLE
Side tag updates are not automatically pushed to testing 

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#4032]
When I create a side tag update for a stable Fedora, it sits in pending until I manually click "push to testing". This is inconsistent with regular updates and a tad confusing.

See also https://pagure.io/fedora-infrastructure/issue/8930

**Comment by cverna** [comment]
This issue is related to the builds of the update not being marked as signed by Bodhi. I think there is an issue with the Signed consumer and side tag updates that are coming from no rawhide release.
