### ISSUE TITLE
 500 Internal Server Error  No such user: 'XXXXX'

### ISSUE THREAD

**Issue by tuxedotje** [fedora-infra/bodhi#4038]
when looking for updates in https://bodhi.fedoraproject.org/ after login. 
text: "You have no updates in pending or testing, view all your updates"
Now click on  "view all your updates"
new screen "0 updates"  click on "+ new update"
"500 Internal Server Error No such user: 'XXXXX'  "

**Comment by mattiaverga** [comment]
Do you still experience this problem? I cannot reproduce it in any way...

**Comment by tuxedotje** [comment]
It has been a one time issue, not seen after may 26. I will close the issue. Thanks for looking.
