### ISSUE TITLE
Request not cleared on updates when release goes EOL

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4039]
When a release is archived, its updates statuses are set to "Obsolete", but we should also clear the Update request:
https://bodhi.fedoraproject.org/updates/FEDORA-2020-2855a8a590

**Comment by Siddharth1010** [comment]
Hi @mattiaverga :)
Could you please let me know where this issue lies?

**Comment by mattiaverga** [comment]
Look into https://github.com/fedora-infra/bodhi/blob/1c1a6ba3f95a40ab60c6b27141b0148982a5e70c/bodhi/server/services/releases.py#L348
