### ISSUE TITLE
Comment and close bugs in same operation

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#404]
It looks like Bodhi 2.0 is performing two separate Bugzilla transactions when closing bugs: first it writes the "has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report." message, then it sends another request to close the bug. This results in two Bugzilla mails to everyone subscribed to the bug. It'd be better if it used one transaction both to post the comment and close the bug (only in the case where 'close bugs when update pushed stable' is set, of course).

**Comment by bowlofeggs** [comment]
I'm going to work on this one as my first "real" Bodhi commit, because it sounds doable and it annoys me too ☺
