### ISSUE TITLE
link in body to koji is slow or does not work

### ISSUE THREAD

**Issue by tuxedotje** [fedora-infra/bodhi#4045]
In bodhi ; Updates View;  Right collumn; under Builds; is a link, that link does not work very well.

**Comment by tuxedotje** [comment]
Links like these 
https://koji.fedoraproject.org/koji/search?terms=stlink-1.6.1-1.fc32&type=build&match=glob

**Comment by tuxedotje** [comment]
in https://koji.fedoraproject.org/koji/    search window does not find stlink-1.6.1-1.fc32  
when search on stlink it finds results.

**Comment by cverna** [comment]
This is an infrastructure issue and it was reported here --> https://pagure.io/fedora-infrastructure/issue/8970

Thanks for the report
