### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by bhepple** [fedora-infra/bodhi#4049]
Every time:

500 Internal Server Error

Could not convert return value of the view callable function pyramid_fas_openid.view.verify_openid into a response object. The value returned was None. You may have forgotten to return a value from the view callable.

**Comment by mattiaverga** [comment]
The datacenter is being moved
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/WYMAEIYUQSX6NMZ4LHJBBZBGJZCCEUWF/

Bodhi could experience some hiccups this week.

**Comment by cverna** [comment]
This is now fixed and login is working again

**Comment by bhepple** [comment]
Yep - working again. Thanks.
