### ISSUE TITLE
Web layout for comments on updates with lots of 'karma items' is messy

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#405]
![Screenshot of messy update](https://www.happyassassin.net/temp/bodhi2messy.png)

See how the longer karma item names flow off the edge of the screen and there's a lot of wasted space.

Perhaps it would look better if they were shown in sort of horizontal tile form under the comment?

**Comment by ralphbean** [comment]
Jeebus that's ugly.

**Comment by ralphbean** [comment]
Here's a link to the update:  https://bodhi.fedoraproject.org/updates/FEDORA-2015-13831
