### ISSUE TITLE
Update times out

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#4051]
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-d7c1181e05
→
504 Gateway Time-out
The server didn't respond in time. 

For me this happens for this particular update every time I have tried.
Doesn't happen for other updates.

This update seems to be stuck, the command line client show messages about the update being ejected due to som builds in it not having the right tags.

bodhi updates query --updateid FEDORA-EPEL-2020-d7c1181e05

**Comment by ellert** [comment]
Of the 274 builds in this update 271 are currently tagged "epel8-testing".

One (accounts-qml-module-0.7-1.el8) is tagged "epel8-testing" and "epel8-testing-candidate"

Two (kde-dev-scripts-19.12.2-1.el8 and qt5-qtnetworkauth-5.12.8-1.el8) are tagged "epel8-testing-candidate"

There are no comments to the update about builds having been added or removed, so all builds should have the same tags.

**Comment by ellert** [comment]
The inconsistent state of the update also filed as a rel-eng ticket:
https://pagure.io/releng/issue/9520

That the web interface times out is a bodhi problem though.

**Comment by mattiaverga** [comment]
I suspect this has the same root cause of #4044

**Comment by mattiaverga** [comment]
Displaying updates with a lot of builds is now much more faster with Bodhi 5.4.
I think this ticket can be closed.
