### ISSUE TITLE
Bodhi docs are not reachable

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4066]
Bodhi documentation is not reachable (404 Error) since the datacenter move to iad2:
https://bodhi.fedoraproject.org/docs

This hasn't changed after today update.

**Comment by cverna** [comment]
Ah this is something I have broken by switching to gunicorn instead of httpd in production. httpd used to serve the docs and gunicorn cannot do that (serve static content). 

We had problems with httpd (growing memory and getting OOM killed) in openshift just before the move so the quick solution was to try to move to gunicorn instead. I guess we have 2 choice here either we create a new pod with httpd that serves only the docs or we host the docs somewhere else like readthedocs or similar.

**Comment by mattiaverga** [comment]
Running a pod to serve docs seems a waste of resources to me... +1 for readthedocs.
Or better, would be possible to sync the docs we produce to something like docs.fedoraproject.org/bodhi ?

**Comment by mattiaverga** [comment]
> Ah this is something I have broken by switching to gunicorn instead of httpd in production. httpd used to serve the docs and gunicorn cannot do that (serve static content).
> 
I'm not familiar with gunicorn, but I assume it sits behind some HTTP proxy (nginx?) https://gunicorn.org/index.html#deployment
Can't we serve static files from nginx?

**Comment by cverna** [comment]
> > Ah this is something I have broken by switching to gunicorn instead of httpd in production. httpd used to serve the docs and gunicorn cannot do that (serve static content).
> 
> I'm not familiar with gunicorn, but I assume it sits behind some HTTP proxy (nginx?) https://gunicorn.org/index.html#deployment
> Can't we serve static files from nginx?

In our case it is a bit complex :P we have the OpenShift haproxy instance that routes the traffic to the correct pod. I am not sure if we could use that to serve static content.
Before that we have the fedora infrastructure proxies that routes bodhi.fp.o to openshift. So I think it does something like browser --> httpd (fedora proxies) --> haproxy (fedora proxies) --> haproxy(openshift) --> gunicorn.

We could probably serve the docs directly from the fedora proxies

**Comment by ghost** [comment]
> browser --> httpd (fedora proxies) --> haproxy (fedora proxies) --> haproxy(openshift) --> gunicorn.

Wow lol. That's crazy. You probably have a 3rd choice to re-create the docs dynamically however long that takes :-)P

**Comment by pypingou** [comment]
Pagure recently gained support to serve static file via whitenoise http://whitenoise.evans.io/en/stable/ which should make it more openshift-friendly.

This is also a library that noggin uses. Perhaps worth looking at for bodhi as well?

**Comment by juhp** [comment]
Yes it would be nice to have the API docs available somewhere again.
