### ISSUE TITLE
Can't create an update for epel8 module

### ISSUE THREAD

**Issue by vashirov** [fedora-infra/bodhi#4069]
I'm trying to create an update for 2 streams of 389-directory-server module. For [389-directory-server-stable-820200622113135.9edba152](https://koji.fedoraproject.org/koji/buildinfo?buildID=1526287) it got successfully created: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-MODULAR-2020-877362f78d
For [389-directory-server-testing-820200604203729.9edba152](https://koji.fedoraproject.org/koji/buildinfo?buildID=1520959) I get: 
```
bodhi updates new --type bugfix 389-directory-server-testing-820200604203729.9edba152  --notes "Update 389-ds-base to 1.4.3.10" --autotime --autokarma 
Update for 389-directory-server-testing-820200604203729.9edba152 already exists
Invalid tag: 389-directory-server-testing-820200604203729.9edba152 not tagged with any of the following tags ['f32-container-updates-candidate', 'f33-updates-candidate', 'f32-modular-updates-candidate', 'f32-flatpak-updates-candidate', 'dist-6E-epel-testing-candidate', 'epel7-testing-candidate', 'dist-5E-epel-testing-candidate', 'f27-modular-updates-candidate', 'f33-container-updates-candidate', 'eln-updates-candidate', 'f30-modular-updates-candidate', 'f28-modular-updates-candidate', 'f28-container-updates-candidate', 'f30-container-updates-candidate', 'epel8-testing-candidate', 'f30-flatpak-updates-candidate', 'f31-modular-updates-candidate', 'f31-container-updates-candidate', 'f31-flatpak-updates-candidate', 'f29-modular-updates-candidate', 'f29-container-updates-candidate', 'f29-flatpak-updates-candidate', 'f22-updates-candidate', 'f21-updates-candidate', 'f25-updates-candidate', 'f24-updates-candidate', 'f23-updates-candidate', 'f26-updates-candidate', 'f27-updates-candidate', 'f28-updates-candidate', 'f32-updates-candidate', 'f30-updates-candidate', 'f31-updates-candidate', 'f29-updates-candidate', 'el8-modular-updates-candidate', 'f33-build-side-24753']
```

It says that "Update for 389-directory-server-testing-820200604203729.9edba152 already exists", but there is no update for *testing*, only for *stable* stream.

This worked fine in the past: https://bodhi.fedoraproject.org/updates/?search=389-directory-server

**Comment by mattiaverga** [comment]
That's just because the update for 389-directory-server-testing-820200604203729.9edba152 really already exists:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-MODULAR-2020-48244a5f2c

You're trying to push to testing the update of 2020-06-04 instead of 2020-06-22 (which build exists only in stable: https://koji.fedoraproject.org/koji/packageinfo?packageID=30656 )

**Comment by vashirov** [comment]
You're absolutely right! I was confused by the fact that all packages were built in the module, but the module itself was not: https://mbs.fedoraproject.org/module-build-service/2/module-builds/9118
Anyways, thank you for your help!
