### ISSUE TITLE
Can't give karma to Bodhi update

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#4088]
When trying to give karma to a bodhi update its throwing me the following error on the browser:

```
Testcase_feedback : Invalid testcase names specified: QA:Testcase Dleyna Renderer Push From Gnome Photos to Rygel, QA:Testcase Gnome Online Accounts Add Facebook, QA:Testcase Gnome Online Accounts Add Google, QA:Testcase Gnome Online Accounts Add IMAP and SMTP, QA:Testcase Gnome Online Accounts Add Kerberos, QA:Testcase Gnome Online Accounts Add MS Exchange, QA:Testcase Gnome Online Accounts Add Windows Live, QA:Testcase Gnome Online Accounts Add ownCloud
```

The update is https://bodhi.fedoraproject.org/updates/FEDORA-2020-cbdab3e9d0

I was able to give the karma with bodhi cli

RelEng ticket: https://pagure.io/releng/issue/9614

**Comment by hroncok** [comment]
I was able to give the karma with bodhi cli as well. Thanks for the hint.
