### ISSUE TITLE
Do not let update through when bodhi fails to talk to greenwave

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#4089]
Now that bodhi and greenwave have been together for a while and that we can see that appart from the unplanned outage, they are performing well. I believe it is time to stop letting bodhi push update through when it fails to talk to greenwave.

The current flow is as follow:
- bodhi queries greenwave
- if greenwave returns an error code or times-out
- bodhi sets the gating status to "failed"
- if there is a push, bodhi will take update that are in gating status "passed" and "failed", therefore letting through updates that should potentially be gated, but we do not know for sure because for some reason we failed to get a clear answer from greenwave.

There are two ways we can address this:
- Stop setting the gating status to "failed" when we fail to talk to greenwave (pros: less noise on the update, less notifications, less confusions to the users, cons: we don't know why the gating status has not been updated)
- Stop including updates with gating status "failed" in the push (pros/cons: the opposite as above)

**Comment by mattiaverga** [comment]
In my opinion, if Bodhi fails to talk to Greenwave, the status should remain "waiting".

Also note that for updates in current Releases the status is set to "ignored" upon submission, then changes to "waiting" and then again to "ignored/passed/failed"... this needs to be fixed.
