### ISSUE TITLE
ELN bodhi updates closing Fedora rawhide bugzillas

### ISSUE THREAD

**Issue by smooge** [fedora-infra/bodhi#4094]
== From https://pagure.io/fedora-infrastructure/issue/9191

I've just seen an ELN update close my rawhide Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1856103

While this bugzilla is now technically rightfully closed because of the mass rebuild, I find it confusing that the ELN update closes a Fedora rawhide bugzilla.

Is this integration enabled for ELN updates intentionally?

====￼ 

pingou commented 4 hours ago
￼
￼
￼
The corresponding bodhi updates points to that bugzilla ticket: https://bodhi.fedoraproject.org/updates/FEDORA-2020-3ff70cd141

I don't think that bodhi does any logic as to whether it should close a rawhide bugzilla ticket for a F32/31/33 update. I suspect it leaves that problem to humans and just close the tickets it is instructed to close.

￼ pingou commented 4 hours ago
￼
￼
￼
And the mass-rebuild by-passing bodhi, it would not have been able to close that ticket.

The base of what happened is documented at https://github.com/fedora-infra/bodhi/blob/develop/docs/user/automatic_updates.rst#associate-bugs-to-automatic-updates

**Comment by pypingou** [comment]
I honestly don't think there is anything to do here.

**Comment by mattiaverga** [comment]
What happened here is that the mass rebuild did actually by-pass Bodhi: python-argcomplete-1.12.0-2.fc33 was built by mass rebuild and did not pass though Bodhi workflow, so the bugzilla ticket wasn't closed inside a F33 update.

After that, an automated task from jenkins fired a build for ELN, the automatic update got created inside Bodhi, which in turn attached the bugzilla ticket that was still open...

This is a really unusual case, I thought in the past about doing a check between the Bodhi release and the bugzilla ticket release, but that would be a lot of work and I think many users would then complain about bugs not being attached/closed...

**Comment by cverna** [comment]
Based on @mattiaverga explanation I would be +1 to close

**Comment by hroncok** [comment]
In this specific case only the ELN update closed the bugzilla because it happened during the mass rebuild.

However, Id' like to opt out form the ELN updates commenting in my packages. Is that possible?

If I choose to use the "Fixes: rhbz#xxx" changelog entries, the ELN builds will spam my rawhide bugzillas.
The only way to not make that happen is to not use such comments in changelogs and close my bugzillas manually?

**Comment by pypingou** [comment]
> The only way to not make that happen is to not use such comments in changelogs and close my bugzillas manually?

Or manually link the update to the bugzilla tickets (and then bodhi will close the ticket as it does normally).

**Comment by hroncok** [comment]
When things work, the update is pushed to stable before I can edit it to add the bugzilla link.

**Comment by decathorpe** [comment]
I'd like to +1 this, please don't close bugs when ELN builds get pushed. There's no way to prevent this from a packager perspective and all it does is create bugzilla spam for every rawhide update.

**Comment by ryanlerch** [comment]
This PR / Issue was included in the 5.7.0 release of Bodhi, and is now deployed in Fedora Staging. Please verify and test that this works as expected.

https://bodhi.stg.fedoraproject.org/

**Comment by decathorpe** [comment]
> Please verify and test that this works as expected.

Well, but, how? Even if I submitted a rawhide build to staging koji, that staging bodhi would pick up, automatic ELN builds are not done in staging, so no bodhi updates that could exhibit this issue can be created.
