### ISSUE TITLE
Top 5 "Active Packagers" should not include Jenkins / bot accounts

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4096]
For the past few days, the top 5 "Active packagers" on the bodhi home page (<https://bodhi.fedoraproject.org/>) are topped by a Jenkins bot account (`bpeck/jenkins-continuous-infra.apps.ci.centos.org`) that's responsible for ELN build submissions. It probably doesn't make much sense to include it there.

Not sure how to deal with this, but maybe accounts with a `/` in their name can be filtered out? That should cover most "bot" accounts in koji, I think?

**Comment by mattiaverga** [comment]
An account with a `/` in its name is certainly a bot, since regular users are bound to FAS rules which don't allow such character. But it may happen a bot doesn't have a `/` in its name.
If we could found a way to identify bots upon login, we may want to add a flag to Bodhi's users table to mark them.

**Comment by decathorpe** [comment]
I don't think FAS provides this information, and I have not looked at noggin yet, but that may be a nice RFE :)

As a start, a simple `is_bot(username)` function in bodhi could just be

```python3
def user_is_bot(username: str) -> bool:
    return "/" in username
```

and that simple heuristic could be replaced with a more sophisticated check if / when that data becomes available.

**Comment by mattiaverga** [comment]
This can actually be solved by adding "offending" bots to a blacklist in the config file.
I've opened https://pagure.io/fedora-infra/ansible/pull-request/248

**Comment by decathorpe** [comment]
Nice! :+1: Thanks for looking into this.

**Comment by decathorpe** [comment]
This issue is back since today's bodhi deployment:

![Screenshot from 2022-01-26 12-43-06](https://user-images.githubusercontent.com/12836693/151157408-976f1adb-e2b7-4a2c-8fb3-cb52cc681864.png)

**Comment by AdamSaleh** [comment]
Ok, will doublecheck.

**Comment by mattiaverga** [comment]
The problem is that new bot name should be blacklisted in Bodhi's config file, I'll open a PR on ansible side
