### ISSUE TITLE
ServerError: ServerError(https://admin.fedoraproject.org/updates/save, 404, Not Found)

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/bodhi#410]
fedpkg switch-branch f23; fedpkg update

after insert bug type and bugs to close ,  bodhi-client gives me this error: 

    /usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
      hash = self.cmd._hash_file('bodhi.template', 'sha1')
    Creating a new update for  pngquant-2.5.1-1.fc23 
    ServerError(https://admin.fedoraproject.org/updates/save, 404, Not Found)
    Traceback (most recent call last):
      File "/usr/bin/bodhi", line 225, in main
        data = bodhi.save(**update_args)
     File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 111, in save
    'bugs': bugs,
     File "/usr/lib/python2.7/site-packages/fedora/client/baseclient.py", line 369, in send_request
       auth_params=auth_params, retries=retries, timeout=timeout)
     File "/usr/lib/python2.7/site-packages/fedora/client/proxyclient.py", line 488, in send_request
       raise ServerError(url, http_status, msg) 
     ServerError: ServerError(https://admin.fedoraproject.org/updates/save, 404, Not Found)
     Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template pngquant-2.5.1-1.fc23 --username sergiomb' returned non-zero exit status 255

**Comment by ralphbean** [comment]
What version of python-fedora do you have installed?  You need python-fedora-0.5.5 or greater.

**Comment by sergiomb2** [comment]
Yep , I just found the solution in http://comments.gmane.org/gmane.linux.redhat.fedora.devel/210780
https://lists.fedoraproject.org/pipermail/devel/2015-August/213557.html

     dnf  --enablerepo=updates-testing update bodhi-client python-fedora 

Fixed the issue 
Thanks
