### ISSUE TITLE
Bodhi 2 error messages cannot be copy/pasted

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#412]
The errors Bodhi 2 uses - which pop up in boxes in the bottom-right hand corner - cannot be copy/pasted. Which is annoying if you're trying to report a bug and include the error message it produces.

**Comment by ralphbean** [comment]
To try fixing this, first we should check if there's a new version of messenger.js out and see if it takes care of it.  Otherwise, we'll either need to hack it or report the issue upstream.

**Comment by remicollet** [comment]
Definitively a big issue.

It also seems popup disapears after some timeout. Which is terribly bad.
* push
* wait... so go for a beer
* no information why the push have failed.

**Comment by ralphbean** [comment]
Filed a request upstream:  https://github.com/HubSpot/messenger/issues/95

**Comment by ralphbean** [comment]
Heads up, someone upstream suggested that this is just a css setting which we can override with:

```css
ul.messenger-theme-your-theme {
  user-select: text;
}
```
