### ISSUE TITLE
Prevent ELN updates with gating from getting stuck

### ISSUE THREAD

**Issue by mmathesius** [fedora-infra/bodhi#4128]
ELN builds for packages that have a `gating.yaml` end up getting stuck in Bodhi with missing "fedora-ci.koji-build.tier0.functional" test results--and require manual waiving by someone with the appropriate rights. (For example, https://bodhi.fedoraproject.org/updates/FEDORA-2020-af92c6b93a) Please correct this.

**Comment by pypingou** [comment]
I don't think there is anything to do for bodhi here. Bodhi does what it is told.
I guess someone needs to instruct greenwave to distinguish regular builds from eln builds and let through the eln updates.

**Comment by pypingou** [comment]
Either that or the CI folks should run tests on the eln builds/updates which would also solve the question of missing test results.

**Comment by mmathesius** [comment]
Reopened this as a greenwave issue: https://pagure.io/greenwave/issue/597
