### ISSUE TITLE
Stable push not possible even karma stable threshold is reached

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#413]
At https://bodhi.fedoraproject.org/updates/prosody-0.9.8-5.fc23, I am not able to push the package to stable (only the buttons "Edit" and "Revoke" are available). As of writing, the package is pending for testing, but due to the reached karma stable threshold this package should go into stable rather into testing.

**Comment by lmacken** [comment]
I fixed the underlying bug, but still need to fix these updates in the database.
