### ISSUE TITLE
Cannot push to stable: https://bodhi.fedoraproject.org/updates/eclipse-pydev-4.1.0-3.fc22

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#414]
This update cannot be pushed to stable. Conversation from IRC:

> mbooth> threebean: I see the button, but I get "This update has not yet met..."

> mbooth> even though it has been in testing for 7 days?

> mbooth> Or has it? I see no "this update was pushed to testing" comment, even though the status says "testing"

> threebean> ah, I bet this is an issue with the bodhi1->bodhi2 migration

> threebean> see the table on the top left?  the last row says "Submitted...."

> threebean> there *should* be a row that says "Pushed...." also that tells the date when it was actually pushed to testing.

> threebean> and.. that may have gotten dropped in the migration.

> mbooth> threebean: Aha

> threebean> shoot.. it also doesn't have an assigned alias which makes it more complicated.  I gotta leave this one to lmacken I think..

Link to broken update: https://bodhi.fedoraproject.org/updates/eclipse-pydev-4.1.0-3.fc22

**Comment by mtasaka** [comment]
And my update request is also broken
https://bodhi.fedoraproject.org/updates/rubygem-zoom-0.5.0-1.fc22

Belows are not reached for 7 days testing period, however perhaps broken similarly
https://bodhi.fedoraproject.org/updates/rubygem-pdfkit-0.8.1-1.fc22

**Comment by lmacken** [comment]
I fixed the underlying bug, but still need to fix these updates in the database.

**Comment by mooninite** [comment]
When will the database be fixed? I am unable to push the mediawiki updates, too.

**Comment by mbooth101** [comment]
@ralphbean Any news here? When do you plan to address this? Would it be quicker for me to revoke the update and create a new one?

**Comment by lmacken** [comment]
This issue has been resolved in production. Please re-open this ticket if you still experience this problem. Thanks!
