### ISSUE TITLE
WebUI-way of initiating bodhi updates trigger-tests would be nice

### ISSUE THREAD

**Issue by adelton** [fedora-infra/bodhi#4144]
When tests haven't been run for a while, it is possible to retrigger the test run with
```
bodhi updates trigger-tests <update id>
```
as suggested by Bruno in https://lists.fedoraproject.org/archives/list/ci@lists.fedoraproject.org/message/VWDLUTXRFUZL6BV5IKMXUQKVH255KZ5A/ -- thank you.

Since that is not something the people likely do regularly to remember the possibility and syntax, and some might not even have the `bodhi` CLI, it would be useful to have this action available in the Bodhi WebUI, for example for updates where test results are missing for a long time (hours).

**Comment by mattiaverga** [comment]
Actually, this is already implemented in Bodhi webUI, but it seems that there's a bug which prevents the button from showing. It also needs to be polished a bit.
I'll look into it.
