### ISSUE TITLE
Can not create multiple buildroot overrides

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#415]
In bodhi 2 the "Candidate build" field in the form for creating buildroot overrides only accepts one value. In bodhi 1 this could be a long list of builds. It is not uncommon that you need the same buildroot override in all releases (except rawhide). This mean that I now have to fill the bodhi 2 form 6 times for F23, F22, F21, EPEL7, EPEL6 and EPEL5, instead of just once in bodhi 1. If I need overrides for two packagas I need to fill the form 12 times instead of once. This takes a lot of time that could be used for more interesting things.

Also, if you list more than one build in the "Candidate build" field and press submit, the submission just silently fails without giving any feedback. There is no information given telling the sumitter why nothing happens.

**Comment by ralphbean** [comment]
Agreed.  Good point.

**Comment by opoplawski** [comment]
I just ran into this as well.
