### ISSUE TITLE
List of overrides does not contain overrides creaded with bodhi 1

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#416]
When looking at the list of overrides created by me, only overrides created using bodhi 2 are liated.

Overrides created with bodhi 1 are missing, so I can not expire old overrides no longer needed.

**Comment by mbooth101** [comment]
I suffered from this too -- as a workaround you can do, e.g.:

    koji untag-build f22-override <pkg>

**Comment by ellert** [comment]
Well, that doesn't work either - https://fedorahosted.org/rel-eng/ticket/6245

**Comment by ryanlerch** [comment]
Going to close this one. Any issues with the migration of overrides from bodhi1 are likely not an issue anymore due to age.
