### ISSUE TITLE
Update.date_approved is always NULL (at least in JSON responses)

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4171]
Either I am doing something very weird, or the content of the Update.date_approved column is always None / NULL in JSON responses. I did some queries of the bodhi production instance, and I found zero updates where this value was not `null`.

Did those values get lost during a migration, or was that column always NULL? Or are the values not NULL internally and they're only mangled to NULL by JSON serialization? I see some code that uses this value, so I suspect the latter to be the case ...

https://github.com/fedora-infra/bodhi/search?q=date_approved

**Comment by mattiaverga** [comment]
Indeed, `date_approved` isn't set nowhere.
We record a lot of dates for every update, I'm not sure what date_approved was intended for:
```
        date_submitted (DateTime): The date that the update was created.
        date_modified (DateTime): The date the update was last modified or ``None``.
        date_approved (DateTime): The date the update was approved or ``None``.
        date_pushed (DateTime): The date the update was pushed or ``None``.
        date_testing (DateTime): The date the update was placed into the testing repository
            or ``None``.
        date_stable (DateTime): The date the update was placed into the stable repository or
            ``None``.
```

**Comment by decathorpe** [comment]
Okay, so those values really are unused ... thanks for confirming my sanity!

Looks like they're at least checked against though:
https://github.com/fedora-infra/bodhi/blob/57135db/bodhi/server/services/updates.py#L284

So querying something with `approved_before` or `approved_since` actually never actually yields any results (because no updates have any values for `date_approved`) :laughing:

But thanks for confirming, I will ignore that column now. :+1:
