### ISSUE TITLE
consider running a readonly Koji REST API

### ISSUE THREAD

**Issue by cgwalters** [fedora-infra/bodhi#4175]
See https://github.com/coreos/rpm-ostree/pull/2420
as well as some of the stuff that lives in the `bodhi updates download` client side source which calls out to the `koji` CLI.

Since bodhi already speaks to Koji and it's written in Python, WDYT about [this idea](https://github.com/coreos/rpm-ostree/pull/2420#issuecomment-754204084):

> Though it would probably be relatively straightforward to write (and hopefully deploy) a proxy service that queries Koji via XML-RPC and returns JSON that we could parse instead.

If Bodhi added this on the server side, then the client could use it instead of calling out to `koji` as a subprocess, and rpm-ostree could use it and avoid scraping HTML or depending on XML-RPC or the `koji` binary plus its huge pile of dependencies.

**Comment by cgwalters** [comment]
I decided not to block on this, see https://github.com/coreos/rpm-ostree/pull/2420#issuecomment-756187588

But that service is obviously still an ideally temporary hack, so am still interested in your thoughts on whether this should live in Bodhi or not.  Thanks!

**Comment by cgwalters** [comment]
Another alternative is we could just run https://github.com/cgwalters/koji-sane-json-api in the Fedora Infrastructure OpenShift?

Or, obviously I could actually add this to Koji directly but I'm not sure I want to context switch into that...
EDIT: opened an issue here https://pagure.io/koji/issue/2659

**Comment by cverna** [comment]
I think we could add a few data we get from koji to the current bodhi api, but I am not sure about creating new endpoints. I agree that it would be much better for koji to have a native json api.

You can also use xml-rpc in rust :P --> https://github.com/fedora-cloud/fedora-container-release/blob/master/src/prerelease/koji.rs

**Comment by cgwalters** [comment]
Closing since https://github.com/coreos/rpm-ostree/pull/2888
