### ISSUE TITLE
Bodhi doesn't correctly mark updates as critpath updates for Rawhide

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4177]
Rawhide updates are never identified as critpath updates:
https://bodhi.fedoraproject.org/updates/FEDORA-2021-c8f0463820
https://bodhi.fedoraproject.org/updates/FEDORA-2021-d8b1203333

The problem is in the interface with PDC:
https://github.com/fedora-infra/bodhi/blob/d275cc2bb9e513dc10e2009262adc989e199dadf/bodhi/server/models.py#L2103
and
https://github.com/fedora-infra/bodhi/blob/d275cc2bb9e513dc10e2009262adc989e199dadf/bodhi/server/util.py#L959

We query PDC for "name=f34", but rawhide in PDC is always "name=master"...

**Comment by ryanlerch** [comment]
This PR / Issue was included in the 5.7.0 release of Bodhi, and is now deployed in Fedora Staging. Please verify and test that this works as expected.

https://bodhi.stg.fedoraproject.org/

**Comment by mattiaverga** [comment]
This is not fixed.
The `Update.contains_critpath_component()` class method now works as expected, but I've just realized that the automatic_updates consumer doesn't check if the new update should be marked as critpath anywhere.

We'll need to add the appropriate flag into the update data.
