### ISSUE TITLE
Satisfied required tests are not marked as such

### ISSUE THREAD

**Issue by msrb** [fedora-infra/bodhi#4184]
Hello,

There is this update: https://bodhi.fedoraproject.org/updates/FEDORA-2021-ace6e91761

The package has this gating.yaml: https://src.fedoraproject.org/rpms/binutils/blob/rawhide/f/gating.yaml

Bodhi correctly states that "All required tests passed", which is correct.

However, when I click on the "Automated Tests" tab, no tests are marked (with "*") as required.

This used to work 4 days ago: https://bodhi.fedoraproject.org/updates/FEDORA-2021-2d7967c391 (gating.yaml has changed since then)

Any idea what is going on there?

Thanks! :wink:

**Comment by psss** [comment]
Hi, just ran into this today with the following update:

 * https://bodhi.fedoraproject.org/updates/FEDORA-2021-be96b935c4

The tests tab says `All required tests passed` which seems to be a clickable link but nothing happens when used. And I see no mark which would indicate which tests are actually required.

**Comment by psss** [comment]
@AdamSaleh, could you please have a look?

**Comment by AdamSaleh** [comment]
This might have been something that is fixed in new release currently in staging. I.e. I can see https://bodhi.stg.fedoraproject.org/updates/FEDORA-2021-ace6e91761 does have the star as expected.

**Comment by psss** [comment]
Nice, thanks for the update! Looking forward to the new release :)

**Comment by AdamSaleh** [comment]
Ok, I have doublechecked the code, and would advise you to temper the excitement for new release.

Way we have written the code, the star/asterix marking required tests is applied only on unsatisfied requirements. We get both list of satisfied and unsatisfied requirements from greenwave, but only take process the unsatisfied. I will find somebody that would be able to make this ui improvement, but it won't make the release we are testing in staging.

**Comment by psss** [comment]
Understood, thanks much for moving this forward!

**Comment by AdamWill** [comment]
I fixed this in 36cc800257005041362be3a8e9cf431993a3084c . I believe the ticket can be closed.
