### ISSUE TITLE
updated_date on updateinfo is changed constantly, without any changes to the errata

### ISSUE THREAD

**Issue by dralley** [fedora-infra/bodhi#4189]
Referred here by: https://pagure.io/releng/issue/10051#comment-719399

It appears that the "updated_date" fields on errata / advisories / updateinfo is updated daily, even without any changes to the actual metadata or package lists. This causes problems for repository management tools such as Pulp, which sees that the "updated_date" has changed, and that therefore the repository has changed, and that therefore the repository metadata needs to be regenerated each time (unnecessarily).

"updated_date" should preferably only be changed when the advisory itself has been updated. Changing it daily without changing the advisory, devalues its usefulness as a component of the metadata.

It would be very difficult to simply ignore "updated_date" because we semi-frequently encounter errata that were updated without changing the "version" metadata appropriately - and it becomes deeply problematic to work with updateinfo / errata / advisories if neither of these fields can be relied upon.

This seems to be true of both EPEL and Fedora.  This issue was reported to us by a user and filed in our issue here: https://pulp.plan.io/issues/8229

EPEL is more of a concern to us simply due to the number of Pulp / Katello / Satellite users who want to manage EPEL content.

**Comment by dralley** [comment]
@mattiaverga I see that a new release was pushed, please let me know when it's live in production so that we can verify the fix.

**Comment by ryanlerch** [comment]
This PR / Issue was included in the 5.7.0 release of Bodhi, and is now deployed in Fedora Staging. Please verify and test that this works as expected.

https://bodhi.stg.fedoraproject.org/

**Comment by dralley** [comment]
Verified, it works as expected.
