### ISSUE TITLE
Missing automatic update for micropipenv (rawhide)

### ISSUE THREAD

**Issue by frenzymadness** [fedora-infra/bodhi#4193]
A few hours ago, I've successfully built micropipenv for rawhide: https://koji.fedoraproject.org/koji/buildinfo?buildID=1722639
but there is still no automatic Bodhi update for that build: https://bodhi.fedoraproject.org/updates/?packages=micropipenv

By the way, I've tried to filter all updates for Fedora 35 and Bodhi gives me `400 Bad Request - Invalid releases specified: F35`.

**Comment by ellert** [comment]
I have the same issue for this build: https://koji.fedoraproject.org/koji/buildinfo?buildID=1722608

**Comment by frenzymadness** [comment]
It seems that somebody fixed it and there are tons of new updates now. Thanks!
