### ISSUE TITLE
Produce a 5.7 release of Bodhi

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#4201]
The time has come for a new release of Bodhi -- 5.7 i presume.

Just created this ticket to track the release, and see if anyone has anything that needs to be added / merged before the release.

* @mattiaverga mentioned #4200 as something we should merge before release

**Comment by mattiaverga** [comment]
:+1: 
#4200 is already approved, but the the failure in pip-docs prevented it from being merged automatically. The failure is unrelated to the changes I made, I have to figure out what is causing it (maybe some buggy module was updated in pip) or it can be manually merge by someone who has powers.

**Comment by ryanlerch** [comment]
@mattiaverga #4200 is now merged. I re-opened your PR for a new release (but marked it as draft so mergify wont do anything with it) -- feel free to close again if i overstepped here.

Was there anything else that you usually do to cut a release?

**Comment by mattiaverga** [comment]
@ryanlerch this is the first time I prepare a PR for cutting a release... I've followed https://bodhi.fedoraproject.org/docs/developer/releases.html#preparation but it's not entirely correct in some steps.

Anyway, I've updated the release notes with the notes from the recently added PR. I think that the next steps are to merge the PR and then tag / branch 5.7.
I don't know anything about deploying it in Openshift, but from a quick read of Bodhi SOP it seems that's outdated too (if I read corectly, it says Bodhi is deployed from Koji builds, but in Ansible it seems it's deployed from git branch).

**Comment by ryanlerch** [comment]
@mattiaverga yeah, i think that is our next steps -- it doesnt seem there are any backwards-incompatable commits on develop since 5.6.1, so i'm pretty sure we are safe to branch 5.7 directly off develop. 

https://github.com/fedora-infra/bodhi/compare/5.6.1...develop

I'll invedtigate the current freeze status, and see if we are able to deploy bodhi to fedora staging to see if everything works.

**Comment by ryanlerch** [comment]
okay, branched and tagged

https://github.com/fedora-infra/bodhi/releases/tag/5.7
https://github.com/fedora-infra/bodhi/tree/5.7

now need to deploy to staging for testing it out.

**Comment by AdamWill** [comment]
I think you can close this now :D
