### ISSUE TITLE
Can't see a way to waive a rawhide CI test run via bodhi web ui.

### ISSUE THREAD

**Issue by rh-mcermak** [fedora-infra/bodhi#4208]
Hi folks, I fail to see a way to waive the following annobin update CI gating:

https://bodhi.fedoraproject.org/updates/FEDORA-2021-0a76ee686a

Please, excuse me if I'm missing something, or overlooked something.

**Comment by rh-mcermak** [comment]
Note that I can't waive it [via CLI](https://docs.fedoraproject.org/en-US/ci/gating/#_waive) either.

**Comment by rh-mcermak** [comment]
Note that I was able to waive the annobin gating failures in the past via the CLI interface, so this looks like a regression in my view.

**Comment by msrb** [comment]
I was able to waive via CLI, but I don't see the waive button in Bodhi (I am proven packager, but not the committer).

**Comment by mattiaverga** [comment]
The waive button in webUI wasn't never really added, it seems it's only partially implemented.
