### ISSUE TITLE
Unable to edit update from side-tag: no commit access to one of the builds.

### ISSUE THREAD

**Issue by alebastr** [fedora-infra/bodhi#4209]
I added a build that I don't have commit access to into [FEDORA-2021-0cad58d4f4](https://bodhi.fedoraproject.org/updates/FEDORA-2021-0cad58d4f4) (f34) and after that I lost permissions to edit the update. I'm the owner of both the side-tag and the bodhi update.

The error message is
```
403 Forbidden
alebastr does not have commit access to cage
alebastr does not have commit access to labwc
```

My guess is that #4133 did not cover permission check for modifying existing update.

**Comment by mattiaverga** [comment]
The validator is used to check submitted data in backend and to allow a user to display the edit page in frontend. I did not take into account the frontend case, so the edit is currently possible only by directly submitting edits from CLI.
I'll work to fix this ASAP.

**Comment by alebastr** [comment]
Thanks for explanation and a quick fix!

> so the edit is currently possible only by directly submitting edits from CLI.

Hm...
```
% bodhi updates request --debug FEDORA-2021-0cad58d4f4 stable
Password:
: Check your FAS username & password
```
Seems like another 403.
Was that another permission issue or a valid rejection? I had enough karma to push the update to stable.
