### ISSUE TITLE
Is it possible to revoke release from stable repository?

### ISSUE THREAD

**Issue by ma3yta** [fedora-infra/bodhi#4215]
looks like by mistake buggy and unstable release candidate of podman was published to stable repository.
https://bodhi.fedoraproject.org/updates/FEDORA-2021-fc15685f73 (4 days in stable repo)

they tried to override it with a new Epoch
https://bodhi.fedoraproject.org/updates/FEDORA-2021-51708c90bc

Do you have a way to revoke a release from the stable repository?

**Comment by lsm5** [comment]
@Ma3yTa https://bodhi.fedoraproject.org/updates/FEDORA-2021-51708c90bc was set to land in stable but you -1'd it :D . Can you revert that please?

**Comment by lsm5** [comment]
ugh .. revoking from stable could be painful IIUC, but infra people would know better. Why shouldn't we bump epoch and revert here? We're quite a few days away from a stable 3.2.0 release.
