### ISSUE TITLE
koji-build-group.build.complete messages don't indicate when they are a re-trigger request (but seem like they want to)

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4217]
Currently, `koji-build-group.build.complete` messages published by Bodhi have a `re-trigger` key whose value is hardcoded to `False`, and an `agent` key whose value is hardcoded to `'bodhi'`. This seems odd. Why have a `re-trigger` key which is never anything but `False`? The name clearly implies it is intended to convey whether the message was produced by a packager requesting a test re-run for an update, but it does not.

The message schema in `messages/schemas/update.py` class `UpdateReadyForTestingV1` also claims:

            'agent': {
                'description': 'Name of the person asking to re-trigger the tests.',
                'type': 'string',

but again, this seems to be a lie, as the value seems to be always hardcoded to 'bodhi' regardless of whether the message is a re-trigger request or not.

**Comment by AdamWill** [comment]
It looks like 1ca2dfec84af7f878bce930211965ff1caecbb08 changed things so `re-trigger` is always `False` - before that it was, correctly, `True` for re-trigger requests but `False` for other cases - but did not do anything to change what the `agent` value would be AFAICS. @pypingou

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/bodhi/pull/4218 ought to fix this (untested).

**Comment by pypingou** [comment]
On Fri, May 14, 2021 at 09:45:17AM -0700, Adam Williamson wrote:
>    It looks like [1]1ca2dfe changed things so re-trigger is always False -
>    before that it was, correctly, True for re-trigger requests but False for
>    other cases 

Looking at the diff, I don't think the re-trigger field was set at all before.

**Comment by AdamWill** [comment]
> On Fri, May 14, 2021 at 09:45:17AM -0700, Adam Williamson wrote: It looks like [1]1ca2dfe changed things so re-trigger is always False - before that it was, correctly, True for re-trigger requests but False for other cases
> Looking at the diff, I don't think the re-trigger field was set at all before.

Sure it was. See line 3889 in the 'after' diff of 1ca2dfe, where it's hard coded to `False`.

**Comment by pypingou** [comment]
It was also before, see https://github.com/fedora-infra/bodhi/commit/1ca2dfec84af7f878bce930211965ff1caecbb08#diff-f66f5d7c307b4514376207c7ddadc17c94a57ba64396ecb8e83a2df4443e6fbcL3869 (ie: line 3869 of the bodhi/server/model in the diff)

**Comment by AdamWill** [comment]
In the before diff there are two codepaths that publish `UpdateReadyForTestingV1` messages. That one is in `_ready_for_testing` and sets `re-trigger` as `False`. Look down a few lines and you see the other: https://github.com/fedora-infra/bodhi/commit/1ca2dfec84af7f878bce930211965ff1caecbb08#diff-aca8cee6439cf81b9f583ebc1a79480858a05fcbb9d25498e929ff162ff9e1f4L715 (line 715). That one is in `trigger_tests` (i.e. the function called when someone requests a re-trigger) and sets it `True`.

In the after diff, both paths just call the update's `_build_group_test_message()` method, and that always sets it `False`.

**Comment by pypingou** [comment]
ah, thanks! I had indeed missed it (and was missing it again until now :))

**Comment by Andrei-Stepanov** [comment]
Hi, we still face this issue.
https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.bodhi.update.status.testing.koji-build-group.build.complete&delta=180000&contains=perl-Future-AsyncAwait-0.51-4.fc35

https://apps.fedoraproject.org/datagrepper/id?id=2021-bfb1a60e-825e-428d-b6a1-d9da19215ba5&is_raw=true&size=extra-large
https://apps.fedoraproject.org/datagrepper/id?id=2021-34353abb-9d19-4eb7-8739-300c773d2b05&is_raw=true&size=extra-large
https://apps.fedoraproject.org/datagrepper/id?id=2021-4e788775-b24b-4143-9c16-45c495ee90eb&is_raw=true&size=extra-large

**Comment by AdamWill** [comment]
yes, the fix is hung up in review: https://github.com/fedora-infra/bodhi/pull/4218
