### ISSUE TITLE
Fedora Update Notification contains unexpanded macros

### ISSUE THREAD

**Issue by ppisar** [fedora-infra/bodhi#4249]
A user reported <https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HCJA63UQ4GS7SFX22W2YR7OKRK5WNJYU/> that Fedora Update Notification for ansible-pcp-2.0.3-1.fc33 <https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WXTHUIAFXNBD37OWHLL5XA24GZZBLLMA/> contains an unexpanded RPM macro in URL value:

~~~~
--------------------------------------------------------------------------------
Fedora Update Notification
FEDORA-2020-fa6dea3553
2020-11-27 01:20:50.552660
--------------------------------------------------------------------------------

Name        : ansible-pcp
Product     : Fedora 33
Version     : 2.0.3
Release     : 1.fc33
URL         : %{ansible_collection_url}
Summary     : Ansible Metric collection for Performance Co-Pilot
~~~~

The value is properly expanded in the SRPM in Koji <https://koji.fedoraproject.org/koji/buildinfo?buildID=1823929>.

Bodhi should retrieve the data from the built package instread of reparsing/rebuilding it from a spec file.

**Comment by humaton** [comment]
Hi, bodhi uses koji_client function getRPMHeaders. When checked the macro is unexpanded in src.rpm.
```
rpm -qi ./ansible-pcp-2.2.1-1.fc33.src.rpm
Name        : ansible-pcp
Version     : 2.2.1
Release     : 1.fc33
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 96076
License     : MIT
Signature   : (none)
Source RPM  : (none)
Build Date  : Čt 26. srpna 2021, 13:49:08
Build Host  : buildvm-a32-09.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : %{ansible_collection_url}
```

**Comment by ppisar** [comment]
Your are right. I would bet I downloaded the source packages from Koji it is was expanded there. But now when I recheck it, it's not expanded.

And that makes sense. Sources packages are built in a SRPM build root where no "ansible" package which defines the macro is installed. It's a packager's bug.

**Comment by ppisar** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2001902.
