### ISSUE TITLE
Can provenpackager push to stable any update?

### ISSUE THREAD

**Issue by hguemar** [fedora-infra/bodhi#425]
I noticed that I can push to stable updates made by other packagers.
https://bodhi.fedoraproject.org/updates/FEDORA-2015-13432

Previously, provenpackagers couldn't edit updates made by other packagers, so looks like an improvement to me.
But I'm only guessing that so could you confirm that not everyone could push to stable updates?

PS: I'm currently upgrading python-cryptography, packagers were notified ahead.

**Comment by ralphbean** [comment]
Yes.  [Here](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/validators.py#L83-L90) and [here](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/validators.py#L311-L317).

Thanks!
