### ISSUE TITLE
Better error messages when creating new release

### ISSUE THREAD

**Issue by LenkaSeg** [fedora-infra/bodhi#4257]
# Observed
When creating new release with required fields missing:
`bodhi releases create --name P33 --long-name "FFedora 33"`
The error message shows this:
`ERROR: Required
ERROR: Required
ERROR: Required
ERROR: Required
ERROR: Required
ERROR: Required
`
I suppose it's complaining about missing required fields, but does not show which.

# Expected
It would be nice to have the required items shown in the error message, even better with some example.

# Proposed solution
Add more specific error message or show help.

**Comment by mattiaverga** [comment]
It's in the backlog: #3096

**Comment by LenkaSeg** [comment]
Ah, thanks!
