### ISSUE TITLE
Package-specific gating policies may not work correctly with critpath packages

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4259]
In https://pagure.io/fedora-ci/docs/pull-request/71#comment-157488 , @psss pointed out a problem with the approach [I came up with](https://github.com/fedora-infra/bodhi/pull/4180) to query different Greenwave "decision contexts" for critpath and non-critpath updates; it may cause problems with package-specific gating policies.

Based on how things previously worked, it's reasonable for a package-specific gating policy to specify the decision context "bodhi_update_push_testing" and expect the policy to always apply when an update containing the package is gated for testing (ditto for stable). But with my change, this is no longer true. If the update contains a critpath package, the package-specific gating policy will not be applied.

I checked Greenwave's API, and it does not allow for querying on multiple "decision contexts" in a single request. It also does not seem to allow for policies to 'include' other policies, which would be helpful here (I may submit this as a suggestion to Greenwave). So with current Greenwave behaviour, I can think of two fixes off the top of my head:

1. Have Bodhi query Greenwave for *both* relevant contexts on critpath updates, and combine the results
2. Require package-specific gating policies to specify both decision contexts

The first has the benefit of not requiring any changes or 'special knowledge' for package-specific gating policies. However, it would mean Bodhi would run more Greenwave queries for critpath updates, generating more load on Greenwave and possibly slowing down Bodhi performance. It also turns out to be a bit tricky to implement: specifically, it would require some re-engineering of how `Update.get_test_gating_info()` and the things that use it work (although, in fact, that method is already not really 'safe' for updates containing more subjects than the Greenwave limit).

The second means we don't actually have to change Bodhi's behaviour any further, but would require us to go through all existing package gating policies and adjust them for this, and update documentation to try and make sure future package-specific policies specify both contexts. It could be a bit more convenient if Greenwave supported wildcards for decision contexts as it does for product versions, but it currently does not.

I'm filing the issue as I'm not sure which approach will be best here overall. I don't want to put the work into 1) if we decide 2) would be the best bet. Or if someone can come up with a third approach I haven't thought of yet. So, what do people think? Thanks!

**Comment by AdamWill** [comment]
@hluk for thoughts from a Greenwave perspective.

**Comment by psss** [comment]
From my point of view, the option 2 is not a good approach as it means that many (tens or even hundreds) package configurations would need to be updated now and also upon introducing any similar decision context change in the future. The gating configuration is already now quite user unfriendly, I'd say, so I would discourage to make the things even worse.

The essential point of the gating config for a component should be IMO specifying which test/plan (resultsdb-testcase) should be used for which gate (decision context). That's it. Anything else sounds to me as a duplication of information which should be stored somewhere else (e.g. whether or not the component is on the critical path).

In the bright future we imagine with @mvadkert and friends, enabling of the gating could be as simple as specifying the [gate](https://tmt.readthedocs.io/en/latest/spec/plans.html#gate) name in the `tmt` plan. This is how a simple plan could look like:

```yaml
execute:
    script: ./run-the-test.sh
gate:
  - add-build-to-update
```

But these dreams will need some more time to implement. @mvadkert, I guess you might also want to share your thoughts here.

**Comment by thrix** [comment]
from my POW the solution 1. is a more clear one to the user, so I agree we should aim for that if possible. Moreover, the current behaviour was introduced quite silently and it was not at all clear the gating will break for users after this change.

**Comment by AdamWill** [comment]
@thrix well, I did detail this approach in a [devel@ thread which was quite widely read/discussed](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/QFYS4OCIAYLOBS3PX4MZNIDMEUVQUO3Q/). Indeed I hadn't thought of this consequence of the approach, though, so it was not explicitly listed.

**Comment by AdamWill** [comment]
@psss for the record:

> The essential point of the gating config for a component should be IMO specifying which test/plan (resultsdb-testcase) should be used for which gate (decision context). That's it. Anything else sounds to me as a duplication of information which should be stored somewhere else (e.g. whether or not the component is on the critical path).

This wouldn't really be "storing information" about that in the per-package gating config, it would just be acknowledging the *possibility* that an update including the package could be on the critical path. It's actually impossible to 'know' this at that level, because critpath status is "infectious" - an entire update is or is not critpath. If package foo is not in the critpath, an update containing only foo is not critical path, but if a build of foo happened to be in an update that also contained, say, kernel, that update would be critpath, and Bodhi would query on the critpath decision context...


Anyway, I got a bit more time to think about this today, and unfortunately my "include" idea wouldn't really work, because it's not a *policy* that would need to include another *policy*, it's a *decision context* that would need to include a *decision context*, and that just wouldn't make a lot of sense in the overall design here. The decision contexts aren't defined 'independently' anywhere you could store that kind of information, they are just strings in the policies, I just can't envisage a way to stuff this concept into the approach that would make sense.

I'll try and find a few hours to work on the 'have Bodhi query on both contexts' approach if I can.

**Comment by AdamWill** [comment]
since several people have actually [been bitten by this problem](https://pagure.io/fedora-ci/general/issue/263) (and because I'm getting nowhere fast trying to fix bugs in KDE's package manager...) I'm kicking this one up the priority list today. I think I can do something that'll be OK for the 'query both contexts' approach in Bodhi, it'll need a single I think little-used API endpoint's return value to change. Just got to adjust all the tests, now.
