### ISSUE TITLE
Editing a side tag update doesn't follow the tagging structure

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#4269]
When ever an update that is created from the side tag is edited with a newer build, then the newer build doesn't get tagged properly and wont get signed, which will fail the bodhi composes as pungi checks for signed builds. This has become an annoyance as bodhi pushes are automated and lately the failures are only due to this one particular issue.

**Comment by mattiaverga** [comment]
Should be fixed by #4261 not yet released into prod

@AdamSaleh can you push the latest changes from devel into 5.7? It would be nice to have all of them in the next Bodhi release.

**Comment by AdamSaleh** [comment]
Yes, that is the plan :)
