### ISSUE TITLE
Wrong resolution for BZ tickets

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#427]
It used to be "CLOSED ERRATA" [1], not it says "CLOSED NEXTRELEASE" [2]. Or am I mistaken and the resolution for upcoming release is different from stable releases?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1233336#c5
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1205294#c6

**Comment by voxik** [comment]
Ah, I am not mistaken: https://bugzilla.redhat.com/show_bug.cgi?id=1248923

**Comment by ralphbean** [comment]
For reference:  https://fedoraproject.org/wiki/BugZappers/BugStatusWorkFlow
