### ISSUE TITLE
Bodhi does not include scenario in generated waivers

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4270]
When someone waives results on an update via Bodhi, it seems the scenario field of the generated waiver is always `null`, even when the result definitely has a scenario. e.g. check this waiver: https://waiverdb-web-waiverdb.app.os.fedoraproject.org/api/v1.0/waivers/9181

The scenario is `null`, but there would never be a `update.install_default_update_live` test run with no scenario. For any critpath update there will be *four* runs of that test with four different scenarios. I'm not sure offhand if Bodhi is generating just one waiver with a null scenario or four waivers with null scenarios in this case, but neither is really correct.

**Comment by mattiaverga** [comment]
Just one waiver with null scenario:
https://github.com/fedora-infra/bodhi/blob/891564724f08124c3272e2f16717b41fd9a56e78/bodhi/server/models.py#L3102-L3117

**Comment by AdamWill** [comment]
OK. So I think the result of that is that Greenwave considers *all* tests matching the testcase and item to be waived. So it's not the worst outcome for what Bodhi is trying to do, but it is technically incorrect.
