### ISSUE TITLE
Bodhi waives all test results, even ones that passed

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4271]
It seems that when someone waives tests via Bodhi, it waives every single test run on the update, even ones that passed. This seems kinda unnecessary and inelegant (and generates a lot of messaging traffic). It would seem more logical to only waive tests that have failed, at least by default.

**Comment by mattiaverga** [comment]
No, Bodhi only waives failed tests. See the first line:
https://github.com/fedora-infra/bodhi/blob/891564724f08124c3272e2f16717b41fd9a56e78/bodhi/server/models.py#L3102-L3117

If you're referring to [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2021-1d24845e93), it had 49 tests failed thus 49 tests were waived. You can check what tests were actually waived in the "automated tests" by the "thumbs up" icon.

**Comment by AdamWill** [comment]
ahhh, OK. Right, sorry. Probably at least one time when he ran the waivers, the 'current' state for that calculation still had a lot of failures from the 'depending on non-stable openssl' problem, yeah. My bad.
