### ISSUE TITLE
Store data about the current rawhide release in bodhi

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/bodhi#4277]
On https://bodhi.fedoraproject.org/releases/ page it is not explicitly stated which of the releases is current *rawhide*. We should make this explicit. This will allow us to use the endpoint in our scripts instead of relying on pdc.

**Comment by mattiaverga** [comment]
I think we already have this: the release which have `branch=rawhide` is Rawhide.

**Comment by mattiaverga** [comment]
Closing per the above comment
