### ISSUE TITLE
bodhi 5.7.1 sometimes only commenting on, but not actually closing linked bugs

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4279]
At least in some cases, bodhi seems to only leave a comment on linked bugs when an update goes stable, but does not actually update the bug status to "CLOSED ERRATA" as it should.

For example, here's a comment without the corresponding expected status change:
https://bugzilla.redhat.com/show_bug.cgi?id=2022244#c1

In contrast, an update I pushed a few hours earlier got processed as expected:
https://bugzilla.redhat.com/show_bug.cgi?id=1982310#c1

**Comment by mattiaverga** [comment]
The first one you linked is about an update being pushed to testing, not to stable... only when it's pushed to stable the bug is closed.

Anyway, there have been a lot of 500 Errors after the update to 5.7.1, it's possible this is breaking the bug handling workflow, let's wait until things get better.

**Comment by decathorpe** [comment]
No, Comment No. 1 from the first linked Bug is "pushed to Fedora 36 stable" as well.

**Comment by mattiaverga** [comment]
mmm the update for F36 has `close_bugs` set to False:
```
>>> up = m.Update.get('FEDORA-2021-088b52bff4')
>>> up.close_bugs
False
```
that's why the bugs were not closed. If you're sure to have created the side-tag update with `close_bugs` enabled, I'll try to check why it was created otherwise.

**Comment by decathorpe** [comment]
Hm, that is a question that only dcavalca (not sure if he's on GitHub or what's his username here) can answer. But he was surprised that the bugs did not get closed, so I assume he did not un-check that checkbox.

**Comment by mattiaverga** [comment]
it should be @davide125

**Comment by davide125** [comment]
I normally use `bodhi updates new` to create updates for side tags, I don't remember if I passed `--close-bugs` when I made that one but probably not, as I kinda thought it would be the default. I'll make sure to pay attention to this the next time.

**Comment by decathorpe** [comment]
That's possible. According to the `bodhi` CLI tool code, `--close-bugs` is not true by default when using the CLI, whereas it's on by default when using the web GUI (which is a bit confusing).

So it appears this was no bug at all, but just confusion. Sorry for the noise.
