### ISSUE TITLE
Bodhi should be split into multiple packages

### ISSUE THREAD

**Issue by markobrien1** [fedora-infra/bodhi#4301]
Currently Bodhi is a number of packages combined. It may be beneficial to split into its separate parts. These could be kept in a single repo for now to avoid changing how rpms are done

Currently setup.py is used in an unsupported way to manage several python packages from a single file. We need to split the file, while maintaining the internal hierarchy of the packages.

These docs show how this can be done: https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by mattiaverga** [comment]
Yeah, the current solution comes from a workaround I found to fix a situation where Bodhi was no more installable with pip (or it was setuptools?...)

Anyway, there's some work in progress, see #4166 and #4298 . The former mine PR doesn't probably respect any of the schemes listed by PyPA.... but that document is not entirely clear to me, as in the first chapter gives an example where there are different setup.py files for each subpackage, while in the other chapter gives only a master setup.py.

I think we need to find a way where we can have some common setup for all the subpackages (version is one which should be surely common) and probably split into bodhi (common things like docs and variables currently in the main __init__.py), bodhi-server, bodhi-client and bodhi-messages.

**Comment by ryanlerch** [comment]
Could moving to poetry be an option here? Not sure if it helps, but datanommer is set up to produce 3 seperate packages from the one repo:

https://github.com/fedora-infra/datanommer
