### ISSUE TITLE
epel5 needs sha1 checksum in repomd.xml for updateinfo.xml

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#431]
Right now the repomd.xml for epel5 has a sha256sum for updateinfo.xml in repomd.xml. 

When someone uses the security yum plugin and doesn't have python-hashlib installed, yum can't deal with the sha256sum and keeps retrying and retrying leading to lots of load on mirrors and an error for the user. 

We need this to be 'sha' like all the other stuff in repomd.xml for epel5 (only).

**Comment by lmacken** [comment]
This fix has been deployed to production and should propagate after the next EL5 push.
