### ISSUE TITLE
Invalid update id

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#432]
Click on "Updates status" for rubygem-compass-core [1] points to [2] which "fails" with some json:

~~~
{"status": "error", "errors": [{"location": "url", "name": "id", "description": "Invalid update id"}]}
~~~

This is not user friendly.

[1] https://admin.fedoraproject.org/pkgdb/package/rubygem-compass-core/
[2] https://bodhi.fedoraproject.org/updates/rubygem-compass-core

**Comment by ralphbean** [comment]
Weird.  Bodhi2 doesn't know about any updates or builds for that package.. so that's why this is happening.

https://bodhi.fedoraproject.org/updates/?packages=rubygem-compass-core

Has it not had a new update in some time?  Or.. ?

**Comment by voxik** [comment]
No, there were no updates yet, just the initial build

**Comment by ralphbean** [comment]
Yeah, we need some kind of generic HTML renderer for non-200 status codes across all our API endpoints to make this nicer.  Hide the JSON.
