### ISSUE TITLE
My update got assigned to someone else during migration

### ISSUE THREAD

**Issue by lkundrak** [fedora-infra/bodhi#433]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-10143

I filed this; I no longer own it.

**Comment by ralphbean** [comment]
We had a bug in the migration script that caused some updates owner to be changed to one of the comment authors.  It should be easy to go back and fix, we just haven't [had time yet](https://github.com/fedora-infra/bodhi/pulse/monthly).

**Comment by lmacken** [comment]
It says that you submitted the update... what do you mean you no longer own it?

**Comment by lmacken** [comment]
It looks like after you edited the update it should have been unpushed & resubmitted back to testing. I queued it up for pushing manually in the mean time.

**Comment by lmacken** [comment]
I'm pretty sure the mis-assigned update bug has been fixed for a while. Please re-open this issue if you still experience this problem.
