### ISSUE TITLE
bodhi randomly throws "NoSuchColumnError user.id" server errors for various queries

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4344]
I am not sure what changed, but since a short time ago (only a few hours), another incarnation of this error has readed its head, see

- "NoSuchColumnError bugs.id": https://github.com/fedora-infra/bodhi/issues/4287
- "NoSuchColumnError testcases.id": https://github.com/fedora-infra/bodhi/issues/4302

Now it is another different one:

```
{
  errors: [
    {
      "location": "body",
      "description": "Could not locate column in row for column 'users.id'",
      "name": "NoSuchColumnError"}
    ],
  status: "error"
}
```

**Comment by mattiaverga** [comment]
@AdamSaleh @abompard @ryanlerch my best attempts were the fix to the serialization problem and the change of the join you can see in the linked bugs. I don't know where to look more than that.

I've just triggered an image build in OS and got the bodhi-web pod restarted (not sure if there's a way to only restart the pod, didn't find anything in openshift manual). At the moment there are no more 500 errors.

I've noticed a couple of things after the bodhi-web pod has restarted:
- the memory consumption has been lowered from 1.5GB to 0.67GB
```
$ oc adm top pods
NAME                          CPU(cores)   MEMORY(bytes)   
bodhi-celery-155-k7rf6        0m           627Mi           
bodhi-celery-beat-108-7r5zz   0m           60Mi            
bodhi-consumer-154-tk2xp      2m           79Mi            
bodhi-web-165-zk52v           46m          672Mi
```
- just after the restart a lot of errors are logged about "lost synchronization with db". Maybe we need to make sure that the old pod instance shuts down cleanly before killing and moving to the new one?

I wonder if sometimes some zombie process is eating resources and make Bodhi start throwing 500 Errors? Is there a topping to the RAM usage? Before restarting the pod I would have wanted to see the list of processes running on the pod, but `top` was not available... is there any other method?

**Comment by decathorpe** [comment]
Huh. You might be onto something, because I can't reproduce this issue today.

**Comment by mattiaverga** [comment]
I now think that these random errors started to show up when Bodhi was moved to use gunicorn:
https://pagure.io/fedora-infra/ansible/c/9fafa15626dfe0bfc3672d4f32a3a6e79029b6f4?branch=main

From [gunicorn faqs](https://docs.gunicorn.org/en/stable/design.html#choosing-a-worker-type):

> The default synchronous workers assume that your application is resource-bound in terms of CPU and network bandwidth. Generally this means that your application shouldn’t do anything that takes an undefined amount of time. An example of something that takes an undefined amount of time is a request to the internet. At some point the external network will fail in such a way that clients will pile up on your servers.

If I'm correct, we're using the default synchronous workers, but there are many places where Bodhi calls external services directly (Koji, Bugzilla, Fedora wiki). Maybe we should switch to an asynchronous type of workers?
See https://pagure.io/fork/mattia/fedora-infra/ansible/c/2a918955d91d982b466ae9c153668c52d43c98c1?branch=bodhi_workers

**Comment by AdamSaleh** [comment]
We plan to make a smaller bodhi release this week, I will try to incorporate the changes you suggest in the ansible-repo, and we will see ... if it doesn't improve the situation, we can reverse the changes.

**Comment by AdamSaleh** [comment]
And damn it, I was really hoping it was just about changing the join configuration to be eager!

**Comment by nirik** [comment]
FYI, the only thing that changed was that we re-deployed the existing setup 2 times... once to enable DEBUG logging and next to disable it. Thats all we changed. ;( Could it be some kind of race condition on deploy where old pods aren't fully down before new ones start or something?

**Comment by AdamSaleh** [comment]
Yeah, I just checked that we have recreate configuration setting in ansible that should take care of that, but for some reason in openshift there still is rolling deployment.

**Comment by mattiaverga** [comment]
We've applied the fixes to object serialization and switched to asynch workers in prod... I hope to not see this error anymore!

**Comment by decathorpe** [comment]
Yeah, I haven't seen this issue in a while. Thanks again!
