### ISSUE TITLE
Search box should display a placeholder while the package search is running

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#436]
The Bodhi 2.0 web UI search box searches 'as you type', but the package search takes rather a long time and there's no indication at all that it's happening. It should probably have a 'searching for updates...' placeholder or something to make it clear that if you wait, results will show up.

**Comment by ralphbean** [comment]
Agreed.  We need to upgrade to the latest release of typeahead.js to do this as mentioned in #229.
