### ISSUE TITLE
Unit tests will never fail in CI due to problem with `test_command` in `UnitJob`

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4382]
Here's the test command from `UnitJob` currently:

        test_command = (
            # Run setup.py develop in all 3 modules
            f'for submodule in {" ".join(MODULES)}; do '
            'cd $submodule; /usr/bin/python3 setup.py develop; cd ..; done; '
            # Run the tests in each submodule
            f'for submodule in {modules}; do '
            '  mkdir -p /results/$submodule; '
            '  cd $submodule; '
            f' /usr/bin/python3 -m pytest {pytest_flags} && '
            '    cp *.xml /results/$submodule/ || '
            '    (cp *.xml /results/$submodule/ && exit 1); '
            '  cd ..; '
            'done'
        )

This will never exit 1, and so CI never sees the unit tests as failed even when they *do* fail. Simplified example of why:

    #!/bin/sh
    for i in 1 2; do /bin/false && echo "did a thing" || (echo "did a bad thing" && exit 1); cd .; done

that prints "did a bad thing" twice and hits the `exit 1` both times, but it exits 0. Why? Because `cd .` succeeds. If you drop the `cd .` from the end, it exits 1.

Fixing this isn't at all trivial, because also consider this example:

    #!/bin/sh
    for i in "false" "true"; do /bin/$i && echo "did a thing" || (echo "did a bad thing" && exit 1); done

We dropped the `cd .`, but this still exits 0, even though the first loop "fails" (it hits "did a bad thing"). The command exits with the exit code of the *last* thing it did, and the last thing it did was the *second* loop, which "passed".

I could probably work out a good way to fix this in an hour or two but it's 6pm on a Friday, so I'm just going to file the issue and go drink instead. :D If nobody else wants to fix it I'll try and do it on Monday.

**Comment by AdamWill** [comment]
oh, wait, it's actually slightly different than I thought. It's the `(cp *.xml /results/$submodule/ && exit 1)` that's the problem - the attempt to do two things within the `||` block, wrapped in a single parenthesis. That just does not do what it wants to do. I'm not sure *exactly* how bash interprets it, but the effect seems to be that the first thing in the brackets happens but the second thing doesn't. So, this actually 'works':

    #!/bin/sh
    for i in "false" "true"; do /bin/$i && echo "did a thing" || exit 1; cd .; done;

it exits 1 on the first run through the loop, never hitting the second run.

**Comment by AdamWill** [comment]
Oh, OK. I think I understand it all now. The parentheses create a subshell - it's like doing `$(foo)` except you're not assigning the output to anything. So when we do `(cp *.xml /results/$submodule/ && exit 1)` we exit *the subshell* with exit code 1. That's why if we make that the *last* thing the loop does, and have the loop fail on the last iteration, the overall exit code is 1 - we're exiting with the exit code from the subshell.

Anyway, I'm sending a PR to fix this, I hope.

**Comment by abompard** [comment]
Fixed by #4383
