### ISSUE TITLE
Broken Requires in spec file

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4407]
This:
https://github.com/fedora-infra/bodhi/blob/6ad5becb1daf8527f71428b1e8f183c241ecb29b/bodhi-server/bodhi-server.spec#L51-L52
will not work, because the version tag is populated with the time when the code checkout is made.

For example, I just tried to rebuild staging image and got:
```
Problem: cannot install the best candidate for the job
 - nothing provides bodhi-client = 5.7.5^202203020212gitf8c4b68-1.fc34 needed by bodhi-server-5.7.5^202203020212gitf8c4b68-1.fc34.noarch
 - nothing provides python3-bodhi-messages = 5.7.5^202203020212gitf8c4b68-1.fc34 needed by bodhi-server-5.7.5^202203020212gitf8c4b68-1.fc34.noarch
```

but the available packages are:
```
bodhi-client-5.7.5^202203020213gitf8c4b68-1.fc34
python-bodhi-messages-5.7.5^202203020213gitf8c4b68-1.fc34
```

**Comment by mattiaverga** [comment]
Looking at this a bit more, the problem is that we're running the Build RPMs job in a matrix of 'release' | 'modules'.
That means there are separate jobs for 'bodhi-server', 'bodhi-client' and bodhi-messages', but to have consistent version tags for each we should run a single job for each Fedora release:
`devel/ci/bodhi-ci rpm -r f34`
(since it defaults to build all modules)

This should be changed in the staging workflow, at least. I don't know about the tests workflow, do we need to have consistent versions there as well, or do we prefer to have better hints about what can be wrong building modules? @ryanlerch

**Comment by mattiaverga** [comment]
A small side note: the spec file of bodhi-messages should be named `python-bodhi-messages.spec` to be 100% conform to Fedora Packaging Guidelines.

**Comment by ryanlerch** [comment]
Yeah, i threw the time in there on the odd case that we might want to push multiple versions to staging in the same day.

I'll note too that was my addition, the Fedora guidelines don't recommend a time in there.

Let's remove the time for now

**Comment by ryanlerch** [comment]
looked into it a bit more, and its easier i think to just build the three modules rpms in the same run in the CI. have pushed those changes now, and it will ensure that the times are not different with the same builds.
