### ISSUE TITLE
Bodhi Docs

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#4415]
Previously, when bodhi was a single package, we built the docs and shipped them as bodhi-docs (and also displayed them in at bodhi.fedoraproject.org/docs)

Note too that the docs contain server docs, client docs, server API docs, client API docs, developers guide, sysadmins guide, and the man pages

Now that the packages are spilt, the man pages have been moved into the -client and -server modules, but the rest of the docs are in /docs in the root.

Just wondering if anyone has any ideas on how to do the docs. 

IMHO, the developer docs arent really useful to be shipped in the bodhi deployment. 

Would it be worth investigating moving the docs to github pages? or some other solution?>

**Comment by mattiaverga** [comment]
In the past there was some attempt to build the docs in ReadTheDocs.org, but it wasn't possible because of dependencies... now that we have separate packages, maybe we can re-try.

Serving the docs in RTD can also save us from pulling in whitenoise dependency for serving static pages (if I remember well, it was added as dependency only for that quite recently).

**Comment by ryanlerch** [comment]
so was the idea here to move all the docs to RTD? -- and not have them on bodhi.fp.o (or have the package)?

**Comment by ronitblenz** [comment]
Should I work on the documentation? If so you can assign me

**Comment by juhp** [comment]
I would really like to have the REST API docs back again.
They used to be at https://bodhi.fedoraproject.org/docs/server_api/rest/

**Comment by mattiaverga** [comment]
> I would really like to have the REST API docs back again. They used to be at https://bodhi.fedoraproject.org/docs/server_api/rest/

The problem is that those pages were autogenerated by cornice-sphinx which is unmaintained upstream and doesn't work with Sphinx 4.
