### ISSUE TITLE
Bring versatility to packages search engine

### ISSUE THREAD

**Issue by Ricky-Tigg** [fedora-infra/bodhi#4438]
[reference](https://bodhi.fedoraproject.org/)

 -  "Copyright © 2007-2019 (...)" is expected be "Copyright © 2007–2022 (...)"; _note_:  "–", not "-".
- **bodhi v.:** 5.7.4 

Hello. Currently search engine lacks versatility. An example if needed;  pattern is searched anywhere in title or linked page.

Suggestions aiming at bringing basic versatility At least allowing filtering of strings 
- **beginning by** pattern
- having the **exact pattern** only
- with pattern **being in package headers** only, not in linked pages.

Illustration (partial output) | while operating a [search](https://bodhi.fedoraproject.org/updates/?search=dnf-&releases=F36) against release 36 of Fedora and pattern _dnf_.

![bodhi fedoraproject org_bodhi_v :5 7 4_search_engine_matches](https://user-images.githubusercontent.com/26058215/159501482-d61959c2-3471-43a8-85e8-2df374ced69b.png)

**Comment by ryanlerch** [comment]
> [reference](https://bodhi.fedoraproject.org/)
> 
> * "Copyright © 2007-2019 (...)" is expected be "Copyright © 2007–2022 (...)"; _note_:  "–", not "-".
> * **bodhi v.:** 5.7.4
> 

The Copyright date issue in the footer is now resolved in the develop branch (was fixed a few weeks ago in #4403). As for changing the hyphen to an en dash, sure it is technically correct that a endash is the correct punctuation here, but its also not going to cause any confusion. Fixing that seems like a great first contribution to the Bodhi project if you are keen.

**Comment by Ricky-Tigg** [comment]
Keen  i am. I ignore though the protocol in this regard. Otherwise it would be done yet today if only i knew. The UI is worth a translation. Keen  i am. in this regard too.
