### ISSUE TITLE
integration tests failing due to security update not having a severity

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#4440]
The integration tests are currently failing, because the the `test_update_edit` test is finding this security update:

https://bodhi.fedoraproject.org/updates/FEDORA-2022-cf87a9b146

which for some reason doesnt have a severity defined. So when the update edit tries to edit it it fails.

so we need to find out how this security update got created without a severity.

and figure out how to fix the integartion tests to not fail on this issue

**Comment by abompard** [comment]
Fixed with 7e0d238, I just excluded security updates when running this test because that's not what we want to test there anyway.
