### ISSUE TITLE
Missing add bodhi user and bodhi group commands in bodhi-server .SPEC file

### ISSUE THREAD

**Issue by edwardlewis35** [fedora-infra/bodhi#4457]
## part of bodhi-server.spec file
install apache/bodhi.wsgi %{buildroot}%{_datadir}/bodhi/bodhi.wsgi
install -d %{buildroot}%{_mandir}/man1
install -pm0644 docs/_build/*.1 %{buildroot}%{_mandir}/man1/

> missing contents
> Below is how I fix this error temporarily
> In my opinion, bodhi should be changed to bodhi-sever to adapt to the new bodhi-server module
> And change apache/bodhi.conf 's user name and group to bodhi-server

############################################
%pre
%{_sbindir}/groupadd -r bodhi &>/dev/null || :
%{_sbindir}/useradd  -r -s /sbin/nologin -d %{_datadir}/bodhi -M \
                     -c 'Bodhi Server' -g bodhi bodhi &>/dev/null || :
############################################

%files -n %{pypi_name}
%doc README.rst bodhi/server/migrations/README.rst bodhi/server/static/vendor/fedora-bootstrap/README.rst
%{_bindir}/bodhi-approve-testing
%{_bindir}/bodhi-check-policies

**Comment by mattiaverga** [comment]
This was has been fixed:
https://github.com/fedora-infra/bodhi/blob/d28243d0488a761ced184c050f8bc2bd55899ee9/bodhi-server/bodhi-server.spec#L122-L124
