### ISSUE TITLE
Automate bodhi pushes in releng freezes

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#4478]
Currently, we have a small script that runs from cron that calls: 

bodhi-push --username releng

This defaults to: 

  --releases TEXT  Push updates for a comma-separated list of releases
                   (default: current and pending releases)

  --request TEXT   Push updates with a specific request (default:
                   testing,stable)

So, most of the time it's perfect. Basically all pending updates are pushed. 

However, in beta and final freezes, we do not want to push any stable updates for the pending releases, but we do want to push the rest. Currently, we disable the cron job and some releng person has to once a day push just everything else in two batches (everything but the pending release, then the updates-testing for the pending release). NOTE: we still need to be able to use --builds to push specific builds stable in the pending release as QA requests them to fix blockers or FE's. 

One possible option would be to find a way to 'mark' pending releases frozen or non frozen. Then, have the default for bodhi-push to honor that and not push stable updates for frozen pending releases. That would require releng to mark/unmark it, but only twice per milestone.

**Comment by mattiaverga** [comment]
Releases can already be marked `frozen` status, I don't recall it was ever used and I'm not sure what side effects can have (apart from excluding the release from being composed).

**Comment by nirik** [comment]
From a quick glance it looks like it just adds a additional message to updates that have a stable pending request saying that the release is in freeze and the update will go stable after the freeze is over. :( 
Ideally it would explain how to propose the update as a FE/Blocker fix, but thats a nitpick. It doesn't seem like it is connected to bodhi push at all currently.

**Comment by mattiaverga** [comment]
Well, since both the composer and the bodhi push default to filter only releases in `pending` or `current` statuses, setting a release as `frozen` should automatically exclude it from being processed.
