### ISSUE TITLE
Bodhi never identifies Rawhide updates as critical path, because it queries PDC wrong

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#4480]
I'm experimenting with Rawhide update testing in openQA. This made me notice that Bodhi never marks Rawhide updates as critical path (which is an issue, as openQA usually only schedules tests on critical path updates). I looked into why, and I think it's because Bodhi queries PDC wrong in this case.

I believe Bodhi will send `update.release.branch` (where `update` is the update in question) as the `name` component in the query to https://pdc.fedoraproject.org/rest_api/v1/component-branches/ when it tries to decide if an update is critpath (from the `Update` model in `bodhi/server/models.py`, which runs `get_critpath_components()` from `bodhi/server/util.py`, which calls `get_critpath_components_from_pdc()` using a `branch` arg that was passed all the way through and is used as the `name` query parameter). For Rawhide, I believe that is `fXX`, where `XX` is the release number currently associated with Rawhide - so right now, it uses `f37`. However, if you query PDC in this way, you get no results:

https://pdc.fedoraproject.org/rest_api/v1/component-branches/?active=true&critical_path=true&name=f37

To get the data from PDC, you have to set the name as 'rawhide':

https://pdc.fedoraproject.org/rest_api/v1/component-branches/?active=true&critical_path=true&name=rawhide

I guess we need to somehow be aware in this case that we're querying the release number that's currently associated with Rawhide and change the query, not sure off the top of my head what the best way to do that is. I'll see if I can figure it out and send a PR.

**Comment by mattiaverga** [comment]
Yeah, that's because the "Rawhide" release should have set `rawhide` as the `branch` value, but for F37 this is currently wrongly set to `f37`.
The SOP is correct: https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/bodhi/#_adding_a_new_pending_release

Releng should fix that.

**Comment by AdamWill** [comment]
Oh, so the 'branch' value is manually set when the release is created in Bodhi? Hmm. Can we fix it for F37/current Rawhide, then?

**Comment by AdamWill** [comment]
Also, the SOP would I guess need to also cover changing the branch name to 'fXX' when it was branched, too. So at branch point, releng should create a new release in Bodhi with the branch name set to 'rawhide', and change the branch name of the release that is now being branched off to 'fXX'...

**Comment by AdamWill** [comment]
Filed https://pagure.io/releng/issue/10761 for releng.

**Comment by mattiaverga** [comment]
Yep, someone from Releng can simply edit the F37 release and set it to `rawhide`.
The SOP covers the switch to branched too: https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/bodhi/#_pre_beta_bodhi_config
