### ISSUE TITLE
fedpkg update not worked correctly

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#449]
I pushed f23 update using "fedpkg update" command. Here is what I got in reply

```
Creating a new update for  iso-codes-3.61-1.fc23 
==============================================================================
     iso-codes-3.61-1.fc23
==============================================================================
  Update ID: FEDORA-2015-14815
    Release: Fedora 23
     Status: pending
       Type: bugfix
      Karma: 0
    Request: testing
       Bugs: 1259094 - None
      Notes: Update to 3.61
  Submitter: pnemade
  Submitted: 2015-09-02 04:38:39
   Comments: bodhi - 2015-09-02 04:38:46 (karma 0)
             This update has been submitted for testing by pnemade.

  https://bodhi.fedoraproject.org/F23/FEDORA-2015-14815
```

You can observe bugzilla summary has come as "None" then the update id URL   https://bodhi.fedoraproject.org/F23/FEDORA-2015-14815 not working as of now (404 error)

Also from IRC, come to know from lmacken that he updated bodhi. Not sure if I hit the window of bodhi2 deployment where at same time my update gets submitted. just my thoughts.

**Comment by lmacken** [comment]
So the bugzilla handling code has recently moved to a backend fedmsg-consumer in order to speed up the time it takes to submit updates (PR #419). This means that bug titles will be None immediately after submission.

The 404 error needs to be fixed in python-fedora.

**Comment by ryanlerch** [comment]
Is this still an issue with the latest version of the Bodhi client?

**Comment by bowlofeggs** [comment]
I believe this is fixed now. Feel free to reopen if you can reproduce with the Bodhi 2 client!
