### ISSUE TITLE
bodhi-client on pypy wasn't updated for some time

### ISSUE THREAD

**Issue by frantisekz** [fedora-infra/bodhi#4508]
It seems the bodhi-client package on pypy ( https://pypi.org/project/bodhi-client/ ) wasn't updated for some time. This is an issue. because of announced bodhi 6.0 server side compat break ( https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/thread/AT2H4MRGIEC7N6VMUEZRXN7BAA7SGSSR/ ).

Could be bodhi-client 5.7.5 and 6.x uploaded to pypy?

**Comment by frantisekz** [comment]
@abompard this is significant problem for Blockerbugs instance ( https://pagure.io/fedora-qa/blockerbugs/issue/246 ) which consumes packages for deployment from pypy.

**Comment by mattiaverga** [comment]
I've uploaded 5.7.5 to Pypi.

I'll let this ticket open as a reminder to add a new github action to automatically upload a new release to pypi.

**Comment by mattiaverga** [comment]
BTW I've also pushed 6.0.0 (the current `develop` branch) to pypi test instance, but note that the `bodhi` package doesn't exists anymore with v6.

**Comment by kparal** [comment]
> but note that the `bodhi` package doesn't exists anymore with v6.

We don't need the full `bodhi` package, just `bodhi-client`. When 6.0 is officially out, you intend to push `bodhi-client` 6.0 to the main PyPI server, right?

**Comment by abompard** [comment]
It's on PyPI now :-)
