### ISSUE TITLE
Bodhi client crashes when expecting a comment of 10 chars without a useful message

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#451]
Often when the fix is "fix FTBFS" or "Rebuild" due to the failure a message of 10 chars it should at least report why it's crashing. 

$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  nmap-6.47-5.fc23 
Password for pbrobinson: 
Creating a new update for  nmap-6.47-5.fc23 
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 225, in main
    data = bodhi.save(**update_args)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 107, in wrapper
    raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: Shorter than minimum length 10
Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template nmap-6.47-5.fc23 --username pbrobinson' returned non-zero exit status 1

**Comment by ralphbean** [comment]
Seems like there's two separate issues going on here:

- The server could be updated to have a shorter minimum character requirement.  '2' seems okay so people can just say '+1' or ':)'.
- The client could catch those ``BodhiException``s and print them out more nicely.
