### ISSUE TITLE
New package update broken push

### ISSUE THREAD

**Issue by cicku** [fedora-infra/bodhi#453]
https://bodhi.fedoraproject.org/updates/libebur128-1.0.2-1.fc22

Only 1 comment from bodhi, no testing pushed notification even!

**Comment by lmacken** [comment]
I fixed this issue in https://github.com/fedora-infra/bodhi/commit/399f3afc24df7c8907cb3400a7c6769998a9aaba and wrote a script today to fix the updates in the production db https://github.com/fedora-infra/bodhi/commit/6a602c65d33157ac0974b4411ce70762976842c0
