### ISSUE TITLE
Do not allow users to set stable request on side-tag rawhide updates

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4566]
Example: https://pagure.io/releng/issue/10832

Usually, side-tag rawhide updates are pushed to stable instantly after creation, but the above example pointed out a special case.

1. as critpath update, it wasn't pushed to stable due to failing gating tests
2. a negative comment disabled autopush
3. the update was edited so gating tests were passing, but still it wasn't pushed to stable because of 2. At this state, it should have been edited to re-enable autopush and wait for the approve_testing task, but no one did.
4. a user manually set request to push it to stable (I assume by CLI, as webUI shouldn't show the option - @AdamWill do you remember how you set the request? it was by CLI or webUI?)
5. the update was edited so that autopush was re-enabled. But the approve_testing task doesn't process updates with pending requests. And as rawhide update, the existing request wasn't process by composer neither. So the update was stuck.

**Comment by AdamWill** [comment]
I used the CLI, yeah. There are a few cases where you can do things with the CLI that you can't do with the web UI.
