### ISSUE TITLE
Auth token only lasts an hour

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#4581]
I acquired a fresh token on Jun 17th 07:34. Watch the expire date:
```
$ cat ~/.config/bodhi/client.json
{"tokens": {"https://id.fedoraproject.org/openidc": {"access_token": "XXX", "refresh_token": "XXX", "expires_in": 3600, "id_token": "XXX", "token_type": "Bearer", "expires_at": 1655447653}}}

$ date -d '@1655447653'
Fri Jun 17 08:34:13 AM CEST 2022
```

Also `"expires_in": 3600` confirms this is just an hour. I don't believe this is intended. A token that only lasts an hour is... not very useful :-/

`bodhi-client-6.0.0-2.fc36.noarch`

**Comment by abompard** [comment]
What actually matters is the expiration of the refresh token. The access token is expected to be short-lived, and when it expires the library will automatically request another access token using the refresh token, which should have a much longer lifespan. I'll check what the lifespan of the refresh token is.

**Comment by kparal** [comment]
I haven't used the bodhi-client library since 07:34 as reported. The contents of the json file was still the same. Yet, when I tried to authenticate again now at 14:42, I received a new request for opening the browser. So it seems that token refreshing is not working as expected.

**Comment by abompard** [comment]
This was actually an Ipsilon issue: https://pagure.io/ipsilon/issue/372
