### ISSUE TITLE
The karma feedback icons are not aligned

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#4587]
This is what I see on Bodhi updates in Firefox 101. See how the karma icons are not aligned with the radio buttons.

![Screenshot from 2022-06-21 10-45-52](https://user-images.githubusercontent.com/755451/174757721-ef3fff43-c36d-4e75-b020-1e3b101f81b7.png)

**Comment by mattiaverga** [comment]
Fixed in next bugfix release see #4562
