### ISSUE TITLE
FC35: Can not update package python3-reportlab-3.6.1-1.fc35.x86_64

### ISSUE THREAD

**Issue by abysso2** [fedora-infra/bodhi#4589]
Hi,
i can not update  package python3-reportlab-3.6.10-1.fc35.x86_64 due to 

"nothing provides python3.10dist(pillow) >= 9 needed by python3-reportlab-3.6.10-1.fc35.x86_64"

dnf search python3-pillow
Letzte Prüfung auf abgelaufene Metadaten: vor 0:12:50 am Di 21 Jun 2022 19:15:50 CEST.
=================================================================================================== Name exakte Treffer: python3-pillow ====================================================================================================
python3-pillow.x86_64 : Python 3 image processing library
python3-pillow.i686 : Python 3 image processing library
======================================================================================================= Name Treffer: python3-pillow =======================================================================================================
mingw32-python3-pillow.noarch : MinGW Windows Python2 pillow library
mingw64-python3-pillow.noarch : MinGW Windows Python2 pillow library
python3-pillow-devel.i686 : Development files for pillow
python3-pillow-devel.x86_64 : Development files for pillow
python3-pillow-doc.noarch : Documentation for pillow
python3-pillow-qt.x86_64 : Qt pillow image wrapper
python3-pillow-tk.x86_64 : Tk interface for pillow

yum download python3-pillow.x86_64
Letzte Prüfung auf abgelaufene Metadaten: vor 0:13:31 am Di 21 Jun 2022 19:15:50 CEST.
python3-pillow-8.3.2-3.fc35.x86_64.rpm

**So version >= 9 is missing for fc35 …**

**Comment by mattiaverga** [comment]
See https://bodhi.fedoraproject.org/updates/FEDORA-2022-9d594bad46

However, this is not the right place for this kind of bugs, in future report to RedHat bugzilla against the affected package.
