### ISSUE TITLE
Cannot middle-click search result links

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#461]
When you run a search in the Bodhi 2 web UI, you can't middle-click a result to open it in a new tab (at least, not in Firefox you can't). This is annoying, because sometimes I want to open a search result without navigating away from the Bodhi page I have open in the current tab (e.g.: while editing the description for one update, I want to open another update for reference).

**Comment by ralphbean** [comment]
> you can't middle-click a result to open it in a new tab (at least, not in Firefox you can't).

I had no idea you could do this anywhere.  I always control-click to do that.  Good to know!

We can figure something out for this...

**Comment by ralphbean** [comment]
As mentioned near the bottom of #229, we're kind of stuck waiting for the next stable release of typeahead.js.

That said, an *easy* short-term fix would be to *always* open results in a new tab.  I'll put that in a PR so we can discuss it.

**Comment by ralphbean** [comment]
> an easy short-term fix would be to always open results in a new tab. I'll put that in a PR so we can discuss it.

**Nevermind**.  It turns out this is actually *hard* since browsers will try and block the pop-up.
