### ISSUE TITLE
" has been requested to testing "?

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/bodhi#4702]
I've been notified that a new build is available https://bodhi.fedoraproject.org/updates/FEDORA-2022-8cf9d64c36
I remember I've seen some instructions how to test Bodhi builds, but I don't see them.

Maybe because build are not really available. Hovering over the last part of the label hints that the package maybe just pending to enter testing state.

![image](https://user-images.githubusercontent.com/8781107/185225332-7b833c00-f547-424b-ac24-1c3b3773137e.png)

So I had to open documentation (I know it exists, because I filled https://github.com/fedora-infra/bodhi/issues/2150 and had been pointed to it) https://fedora-infra.github.io/bodhi/6.0/user/update_states.html#pending

> Once an update is submitted to Bodhi it will enter the pending state. Bodhi will perform some sanity checks on the update request. Is the package built and available in koji? Is it tagged as an updates candidate for the release it is intended for? The update path for the package will also be checked at this point to make sure you don’t release a newer version of a package on an older release. The update must not break the upgrade path or it will be rejected.

This looks like the process is completely automatic. However, @bowlofeggs tells that switching package from "pending" to "testing" is a manual human process https://github.com/fedora-infra/bodhi/issues/2150#issuecomment-408884663

If the package was submitted by @rapgro and now is in "pending", who is requested to push the button to release it to "pending"? Would be nice to see the interface reflect that.

**Comment by mattiaverga** [comment]
> 
> If the package was submitted by @rapgro and now is in "pending", who is requested to push the button to release it to "pending"? Would be nice to see the interface reflect that.

No one. F36 is a release which is "composed" by Bodhi. That means that once (or twice, I don't remember exactly) a day a compose is performed and updates moved from pending to testing or from testing to stable.

So, you need to wait for the f36 compose, then the update will be moved to testing.

**Comment by abitrolly** [comment]
Found the docs https://fedora-infra.github.io/bodhi/6.0/administration.html#composer "generating the repositories that move packages", Not sure what it does exactly. I fetch the update from `update-testing`, which already exists. So what kind of repos it need?

Why wait 12 hours for it to kick in? Why `compose` can not be run as online service that kicks in immediately as a job for it is available?

**Comment by mattiaverga** [comment]
Creating a compose is a complex, time consuming, resource eager task and cannot be done on the fly each time a new build is submitted as an update.

Moreover, after a compose is done it usually takes 12/24 hours before mirrors synch themselves. If one cannot wait they can download the RPMs from Koji and manually update packages.

**Comment by abitrolly** [comment]
@mattiaverga is there a step be step description of what the compose is about? Diagram how it works and what takes so much time. Such critical part and no docs.

I did plumbing for different blockchain node synchronization and I smell a big potential for refactoring here. Without mining farms hopefully. )

**Comment by abitrolly** [comment]
> If one cannot wait they can download the RPMs from Koji and manually update packages.

But the point is to test update, not individual RPMs. It took me 17 hours and a lot of advice to do the testing properly https://ask.fedoraproject.org/t/how-to-select-another-mirror-in-dnf/25487 The test itself took 3 minutes.

**Comment by mattiaverga** [comment]
https://github.com/fedora-infra/bodhi/blob/8838976bf8da41ce602e2f651bc0007af397d374/bodhi-server/bodhi/server/tasks/composer.py#L103-L149

**Comment by abitrolly** [comment]
Docs say Composer "generates repositories", but docstring says it lock them. So how many repos are there? For example for update for F36. `updates-testing`, `updates` - is that all?

I would take a long time to read the code and ask questions.
