### ISSUE TITLE
Document DCO, Signed-off-by requirement

### ISSUE THREAD

**Issue by LenkaSeg** [fedora-infra/bodhi#4704]
Suggested by @gotmax23

Add DCO document to the repo and a note to file for contributors.

Example from rpmautospec:
https://pagure.io/fork/nphilipp/fedora-infra/rpmautospec/c/8355b525cc20a27dbe3e9af25e7c6f6ff881b55d?branch=main--random-fixes-and-additions

Related PR #4677

**Comment by ronitblenz** [comment]
May I work on this issue?
Please assign me so that I can look into it.

**Comment by mattiaverga** [comment]
For reference, this is already in the [developer documentation](https://github.com/fedora-infra/bodhi/blob/develop/docs/developer/index.rst#contribution-guidelines).

**Comment by ronitblenz** [comment]
I have made a PR, Kindly check
