### ISSUE TITLE
Properly handle EPEL buildroot overrides

### ISSUE THREAD

**Issue by gotmax23** [fedora-infra/bodhi#4737]
The epel8-next-build and epel9-next-build koji tags inherit packages from the epel8 and epel9 tags, respectively, but they don't inherit from epelX-override due to limitations in Koji (@nirik and I discussed this). However, when you create an override in Bodhi for a plain EPEL 8/9 package, Bodhi only tags the build into epelX-override. I propose either making this a special case and always tagging EPEL overrides into both epelX-override and epelX-next-override or allowing users to configure this.

This should *only* happen one way, though. Overrides for epelX packages should be tagged into both tags, but overrides for epelX-next packages should only be tagged into epelX-next-override.

**Comment by mattiaverga** [comment]
Would the above proposed solution be acceptable?

**Comment by nirik** [comment]
Yeah, I suppose so. :( The epel10 setup will be much nicer here. 

One nit, theres: "epel-9.override-extend=EPEL-9N,EPEL-8" in the comment, but that should be EPEL-9 there? or just EPEL9-N and nothing more? we don't want to tag epel9 things into epel8...

**Comment by mattiaverga** [comment]
Well, the comment is only meant to denote that it can inherit from multiple releases listed in CSVs (if have ever need to).
The [ansible PR](https://pagure.io/fedora-infra/ansible/pull-request/1686) I drafted reports
`epel-9.override-extend = EPEL-9N`
which means all EL9 builds submitted as BROs will also be tagged in EL9N override tag.

One nitpick I forgot to mention is that those BROs will only be listed in Bodhi under their main release (i.e. EL9 BRO which is also tagged as EL9N override will not be listed when searching for EL9N BROs).

**Comment by nirik** [comment]
Yeah, understand. Thanks.
