### ISSUE TITLE
user page url changed from bodhi1

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#476]
in bodhi1 we were having https://bodhi.fedoraproject.org/user/pnemade but now in bodhi2 we have https://bodhi.fedoraproject.org/users/pnemade

Is this intentional? shouldn't this break people's scripts if they are querying to https://bodhi.fedoraproject.org/user/pnemade in bodhi2?

**Comment by pnemade** [comment]
also, feel free to close this if this is intentional just wanted to know the thoughts behind this change.

**Comment by ralphbean** [comment]
No, it was accidental, but I think we're going to keep it.  The first part of the url path is now always consistently plural ``/updates/``, ``/users/``, ``/releases/``, ``/comments/``, etc..

We can add an apache rule to help redirect people from ``/user/NAME`` to ``/users/NAME``

**Comment by ralphbean** [comment]
Should be fixed with [this ansible commit](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=a38442910020a351848d367692ab21f594c81a11).
