### ISSUE TITLE
idea:  check for rpm signage before starting the mash

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#481]
I **think** right now that the masherthread chugs along and only fails in the middle or the end when it discovers that an rpm is not signed.

Could we check for that in the beginning to save time?  Maybe check in `sanity_check(..)` and kill the mash more quickly?

**Comment by puiterwijk** [comment]
This should now actually be fixed with the autosigning stuff and marking things as signed?

**Comment by bowlofeggs** [comment]
@puiterwijk I think it might not be. There was a mash a couple of weeks ago of EPEL 6 that failed since there isn't gating on EPEL 6, and I think it didn't fail early as @ralphbean was suggesting.

**Comment by bowlofeggs** [comment]
This was fixed by #2131.
