### ISSUE TITLE
'bodhi overrides edit --expire' finishes with "Running koji wait-repo ..."

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#4830]
Running `bodhi overrides edit --expire ...` finishes with the output "Running koji wait-repo ...".
But then finishes anyway. This looks like erroneous output to me - while mostly harmless it is a bit confusing.

I am using bodhi-client-6.0.1-4.fc37 - here is an example:

```shellsession
$ bodhi overrides edit --expire rpmbuild-order-0.4.10-1.fc35
============================================================
     rpmbuild-order-0.4.10-1.fc35
============================================================
  Submitter: petersen
  Expiration Date: 2022-11-20 08:00:59
  Notes: No explanation given...
  Expired: True


Running koji wait-repo f35-build --build=rpmbuild-order-0.4.10-1.fc35
$ 
```
Since I didn't specify `--wait`, just finishing is fine, but the "Running koji..." message should not appear in this case I think?

**Comment by mattiaverga** [comment]
Looks like `--wait` is the default:
https://github.com/fedora-infra/bodhi/blob/31c8358df9d893c7a0835a969094550438df3a5d/bodhi-client/bodhi/client/cli.py#L150-L161

**Comment by mattiaverga** [comment]
After re-reading I now understand the confusion... we just have to change the default to `--no-wait` when `--expire` is passed as argument.
