### ISSUE TITLE
RHEL 8 Postgis 3.3.2 requires gdal35-libs >= 3.5.2 

### ISSUE THREAD

**Issue by marcelomarques74** [fedora-infra/bodhi#4832]
root@lnx8pg12 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.6 (Ootpa)

[root@lnx8pg12 ~]# yum install postgis33_13
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                                                                                         17 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                                                                                      19 kB/s | 2.8 kB     00:00
EPEL8 x86_64                                                                                                                                                                                                  18 kB/s | 2.7 kB     00:00
Error:
 Problem: package postgis33_13-3.3.2-1.rhel8.x86_64 requires gdal35-libs >= 3.5.2, but none of the providers can be installed
  - package postgis33_13-3.3.2-1.rhel8.x86_64 requires libgdal.so.31()(64bit), but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libqhull_r.so.7()(64bit) needed by gdal35-libs-3.5.2-3.rhel8.x86_64
  - nothing provides libqhull_r.so.7()(64bit) needed by gdal35-libs-3.5.3-1.rhel8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

[root@lnx8pg12 ~]# yum install postgis33_12
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                                                                                         15 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                                                                                      18 kB/s | 2.8 kB     00:00
EPEL8 x86_64                                                                                                                                                                                                  22 kB/s | 2.7 kB     00:00
Error:
 Problem: package postgis33_12-3.3.2-1.rhel8.x86_64 requires gdal35-libs >= 3.5.2, but none of the providers can be installed
  - package postgis33_12-3.3.2-1.rhel8.x86_64 requires libgdal.so.31()(64bit), but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libqhull_r.so.7()(64bit) needed by gdal35-libs-3.5.2-3.rhel8.x86_64
  - nothing provides libqhull_r.so.7()(64bit) needed by gdal35-libs-3.5.3-1.rhel8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

[root@lnx8pg12 ~]# subscription-manager repos --list-enable
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-8-for-x86_64-appstream-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Repo URL:  https://red-inf-cap-p01.esri.com/pulp/repos/ESRI/LEP_Patch/cv_patch/content/dist/rhel8/$releasever/x86_64/appstream/os
Enabled:   1

Repo ID:   rhel-8-for-x86_64-baseos-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Repo URL:  https://red-inf-cap-p01.esri.com/pulp/repos/ESRI/LEP_Patch/cv_patch/content/dist/rhel8/$releasever/x86_64/baseos/os
Enabled:   1

Repo ID:   ESRI_EPEL_8_EPEL8_x86_64
Repo Name: EPEL8 x86_64
Repo URL:  https://red-inf-cap-p01.esri.com/pulp/repos/ESRI/LEP_Patch/cv_patch/custom/EPEL_8/EPEL8_x86_64
Enabled:   1

--------------------------------------------------------------------------------------------------------------------------------

CAUSE: RHEL 8 EPEL 8 is missing gdal35-libs >= 3.5.2

NOTE: RHEL 7 works fine to install Postgis 3.3.2 !!! EPEL 7 has all the packages !!!

NOTE: issue was also logged with Redhat Bugzilla and Postgis trac.osgeo

RHEL 8 Postgis 3.3.2 requires gdal35-libs >= 3.5.2

RedHat Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2143703

Fedora Bodhi https://github.com/fedora-infra/bodhi/issues/4832 

PostGIS https://trac.osgeo.org/postgis/ticket/5290#ticket

**Comment by mattiaverga** [comment]
This has nothing to do with Bodhi, you should report to RH Bugzilla.

**Comment by marcelomarques74** [comment]
**--WORKAROUND--**

**https://www.postgresql.org/download/linux/redhat/**

-- # Install the repository RPM:
**sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm**

-- # ls -la /etc/yum.repos.d

-- # yum install gdal35-libs*
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                                   14 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                                15 kB/s | 2.8 kB     00:00
EPEL8 x86_64                                                                                                                                            14 kB/s | 2.7 kB     00:00
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libqhull_r.so.7()(64bit) needed by gdal35-libs-3.5.3-1.rhel8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@lnx8pg12 ~]#

**--NOTE: Many packages, including libqhull, live in the "CodeReady Linux Builder" repo**

-- # subscription-manager repos --enable=codeready-builder-for-rhel-8-x86_64-rpms
-- # subscription-manager repos --list-enable

-- # yum install gdal35-libs*         **<== works fine this time!!!**

**--These work fine now!!!**
-- # yum install postgis33_12
-- # yum install postgis33_13
