### ISSUE TITLE
Clean up Update dates

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4837]
We have a lot of dates in the Update model, some of them seem not useful:
```
        date_submitted (DateTime): The date that the update was created.
        date_modified (DateTime): The date the update was last modified or ``None``.
        date_approved (DateTime): The date the update was approved or ``None``.
        date_pushed (DateTime): The date the update was pushed or ``None``.
        date_testing (DateTime): The date the update was placed into the testing repository
            or ``None``.
        date_stable (DateTime): The date the update was placed into the stable repository or
            ``None``.
```

`date_pushed` is actually almost equal to either `date_testing` or `date_stable` (or None). Only when the update is in testing and requested to stable it differs (`date_pushed`=`date_stable` =None/`date_testing`!=None).
But this is causing weird things with generated updateinfo metadata: an update entry in updateinfo.xml starts with an `issued date`=`date_submitted`, then it is changed to `issued date`=`date_pushed` after it is pushed to testing (and here we start having an `issued date` which is weirdly later than `modified date`), then `date_pushed` is set to None, so we have again `issued date`=`date_submitted` and finally `issued date`=`date_pushed` after it is pushed to stable (and definitely we have `issued date` later than `modified date`).
I think we can get rid of `date_pushed` and use something like `date_stable if not None else date_testing`.

Another column which was never used is `date_approved`. Here we can just remove the column, but if QA folks (@AdamWill ) think it could be useful, we must start setting it somewhere.

**Comment by AdamWill** [comment]
sorry, I thought I'd replied to this, but - yeah, I don't think we use any of those dates, so this should be fine.
