### ISSUE TITLE
No way to view buildroot overrides from web UI

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#484]
Buildroot overrides show up in the Bodhi 2 web UI search, but there is no place (I can see) where you can just go and view all buildroot overrides. This is sometimes something you want to do.

**Comment by ralphbean** [comment]
Oh, it's https://bodhi.fedoraproject.org/overrides/

We could maybe link to it from the ``/releases/SOME_RELEASE`` page by listing all the overrides there?

It's also linked to from user profiles (you can get there to see all the overrides submitted by *someone*).
