### ISSUE TITLE
Bodhi 7 missing in PyPI and stg.fp.o

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#4847]
I'd like to test my project against freshly-released Bodhi 7. Can you please submit the release even to PyPI and also deploy the server to stg.fp.o? Thanks!

**Comment by mattiaverga** [comment]
I've pushed 7.0.0 to Pypi-test, but for deployment bodhi-server to stg.fp.o I'm waiting for someone from fedora-infra (kevin has offered to deploy it this week when time permits).

**Comment by kparal** [comment]
Thanks, it's deployed now. It was enough to perform my tests. (Please don't forget to update production PyPI as well, thanks).
