### ISSUE TITLE
broken link "enhanced" in Fedora-Flavored Markdown

### ISSUE THREAD

**Issue by AloisMahdal** [fedora-infra/bodhi#4849]
[This page](https://fedora-infra.github.io/bodhi/6.0/user/fedora-flavored-markdown.html) is linked from Bodhi when adding comment.

The first link leads to *ffmarkdown.py* that does not exist already:

>     ========================
>     Fedora-Flavored Markdown
>     ========================
>
>     Description
>     ===========
>
>     Text fields in Bodhi2 support an `enhanced`_ version of `markdown`_. This is a cheat
>     sheet for your reference.
>
>     [.......]
>     [skipped]
>     [.......]
>
>     Lastly, you can embed inline **IMAGES** with syntax like this::
>
>       ![Alt text](/path/to/img.jpg)
>
>     .. _enhanced: https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/ffmarkdown.py
>     .. _markdown: http://daringfireball.net/projects/markdown/syntax

**Comment by AloisMahdal** [comment]
Let me guess the correct link:

    https://github.com/fedora-infra/bodhi/blob/develop/bodhi-server/bodhi/server/ffmarkdown.py

?

**Comment by AloisMahdal** [comment]
I wanted to create PR, but turns out the linking has been removed from the word "enhanced" as part of  3a11164, with no explanation.  (Note that the is still there at the bottom.)

**Comment by mattiaverga** [comment]
I just removed the broken link as I thought it doesn't bring much help to point users to raw code. The relevant explanation is all available inside the same page. I've forgotten to remove the link at the bottom, though.

**Comment by mattiaverga** [comment]
This should be fixed in Bodhi 7.0
