### ISSUE TITLE
Buildroot override view doesn't tell you who submitted it

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#485]
When I view an existing buildroot override submitted by someone else - e.g. https://bodhi.fedoraproject.org/overrides/rpm-4.13.0-0.rc1.1.fc23 - what I get is a view that kinda looks like it's intended for the person who submitted the override; it has 'Submit' and 'Expire' buttons and some instructions on checking if the override is active. But it doesn't tell me who submitted the override, which is what I actually wanted to know.

**Comment by ralphbean** [comment]
Should be easy to add there.
