### ISSUE TITLE
Support an old update URL format

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#488]
like ``/updates/{alias}/{title}``.  it's redundant, but some people are still trying to use it.

**Comment by pypingou** [comment]
This isn't such an easyfix as ``/updates/`` relies on cornice and not on the regular routing mechanism and we need to find a way to say: consider ``/updates/{alias}/{title}`` to be ``/updates/{alias}`` when ``{title}`` is not ``edit`` or ``request``, otherwise we conflict with other URLs

**Comment by pypingou** [comment]
Actually, it can only conflict with ``edit``, ``request`` is in another path

**Comment by pypingou** [comment]
so I tried two things:

a) Adding a new URL routing in the pyramid side that would just redirect the old URLs to the new ones:
````
@view_config(route_name='old_update', renderer='json',
             request_method='GET')
def old_update_view(request):
    """ Method providing a backward compatible url for old updates """
    return HTTPFound("/updates/{0}".format(request.matchdict['alias']))
````

Fails as it catches ``/update/{alias}/edit`` as well.

b) Add a new cornice service:
````
update_old = Service(name='update_edit', path='/updates/{id}/{title}',
                     validators=(validate_update_id,),
                     description='Update submission service',
                     #acl=bodhi.security.package_maintainers_only_acl,
                     acl=bodhi.security.packagers_allowed_acl,
                     cors_origins=bodhi.security.cors_origins_rw)
...
@update_old.get(accept=('application/json', 'text/json'), renderer='json',
                error_handler=bodhi.services.errors.json_handler)
def get_update_old(request):
    return HTTPFound("/updates/{0}".format(request.matchdict['alias']))
````

Fails as then: ``/update/{alias}/foobar`` is considered as ``/update/{alias}/edit``

**Comment by pypingou** [comment]
And this was the mistake:
> update_old = Service(name='update_edit',
The ``name`` there was incorrect, using the right one, it works.
