### ISSUE TITLE
Add a robots.txt

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#495]
We used to rely on http://admin.fedoraproject.org/robots.txt

Ideally we should do this redirect at the apache level.

**Comment by ralphbean** [comment]
Looks like this will be easy.  Just copy what we do for other domains here: https://lists.fedoraproject.org/archives/list/infrastructure%40lists.fedoraproject.org/thread/CXMD6HKSXHOFHEPJZIE2HWLH3IXGPXAU/

**Comment by ralphbean** [comment]
I thought [this ansible commit](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=dd76e91f2f441efbd953907889a4168c8f9159ac) would do it, but it looks like it [didn't work](https://bodhi.fedoraproject.org/robots.txt).

**Comment by ralphbean** [comment]
OK, and then I thought [this one](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=ed887a1cc9866a2cb018776c00d17dd7fc975823) would do it, but it also didn't work.
