### ISSUE TITLE
Can't push to stable

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#496]
e.g. https://bodhi.fedoraproject.org/updates/FEDORA-2015-14191

     11 days ago, 2015-08-26 17:29:39.256365 :  This update has been pushed to testing

But trying to push to stable

    This package have not met the minimum...

Also, I don't see anymore message about "this package have spent 7 days in testing ..;" and no notification.

**Comment by remicollet** [comment]
I was thinking this "new package" is blocked by "Requires bugs" (which doesn't make sense in this case), but after editing the errata, and disabling this checkbox, still the same issue.

**Comment by voxik** [comment]
I have similar issue [1]. Its for F23 and spent more than 3 days in testing. Interestingly, I was able to push much younger update [2], so this seems to be specific to some updates ...

[1] https://bodhi.fedoraproject.org/updates/FEDORA-2015-14748
[2] https://bodhi.fedoraproject.org/updates/FEDORA-2015-14929

**Comment by voxik** [comment]
This can be closed in favor of #505 I believe.

**Comment by lmacken** [comment]
This issue should hopefully be resolved.

**Comment by voxik** [comment]
Works for https://bodhi.fedoraproject.org/updates/FEDORA-2015-14748

 :+1:

**Comment by remicollet** [comment]
Yes, everything seems ok.
