### ISSUE TITLE
Incorrect order of Feedback columns for positive/negative karma

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#498]
Hi,

my bad I did not check which radio button adds positive/negative karma properly. However, if you look at any update with some karmas, there are two places:
1) Related Bugs
2) Feedback

1) shows karmas for bugs in positive | negative order of columns. 2) shows negative | neutral | positive order. Which is a little user-unfriendly. Would it be possible to switch ordering of 2) to positive | neutral | negative so it complies with ordering of 1)? If not, the issue can be closed.

[1] https://bodhi.fedoraproject.org/updates/golang-1.5-8.fc23

Jan

**Comment by ralphbean** [comment]
Thanks for the great ticket Jan!

I'll do the opposite, if you don't mind, and switch the order of 1) since I worry that some people are already used to the buttons for 2).
