### ISSUE TITLE
no bound on the size of update "notes" allows creating huge database entries

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4982]
After encountering some bodhi queries that were *really slow* and returned absolutely ***huge*** amounts of data (sometimes ~400 MB when querying for a single update), I think I found a bug in bodhi, which might also allow DoS attacks.

Two factors seem to be contributing to this problem:

- It looks like there is no enforced upper bound for the length of the "notes" field, neither for user-created updates nor for automatically created updates.
- The generation of update notes from rawhide updates  appears to be bug-prone, especially for certain packages with huge changelogs.

Narrowing it down, it appears that updates created by `packagerbot/os-master02.iad2.fedoraproject.org` and `packagerbot/os-control01.iad2.fedoraproject.org` users, in particular, updates that were generated for automatic builds of the `dummy-test-package-gloster` "canary" package (builds like `dummy-test-package-gloster-0-9708.fc37`).

Smaller updates with this problem cause dozens of MB of download from bodhi, like this one:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-74e6e3987a

The affected updates with the largest update "notes" have over 400 MB of text in them.
Opening such an update in the web interface times out or seems to crash the bodhi server.
To reproduce, this, visit <https://bodhi.fedoraproject.org/updates/{update-id}> with `{update-id} = FEDORA-2022-cf5f6b8ffe`

I think it would probably be a good idea to add an upper bound to the size of update notes, especially those generated from rawhide build changelogs. Doing some crude analysis for Fedora 37 updates, it looks like only about a dozen (14) actually human-created updates have notes that are bigger than 10 KB, most of which actually contain a copy of entire upstream changelog (for which the update notes isn't really the right place anyway).  Worst offender seem to be kernel updates for rebases to new major versions, where the RPM changelog contains a copy of the entire development history (which is madness in itself). All other packages with notes >= 10 KB were created by automation (568).

While the total size of "large" notes from human-created updates is just ~500 KiB, the total size of all bot-created update notes for updates with notes >= 10 KB is a whopping 10.6 GiB (!!! for Fedora 37 alone), so it might even be a good idea to truncate existing entries like these up in the bodhi database, in addition to adding guardrails to prevent this from happening in the future.

<details>
<summary> List of affected bot-created updates (Fedora 37 only, no guarantee for completeness) </summary>

FEDORA-2022-74e6e3987a
FEDORA-2022-9679b680cb
FEDORA-2022-22898ba6f1
FEDORA-2022-4a2924e6be
FEDORA-2022-dd91453e48
FEDORA-2022-0528cfb1f6
FEDORA-2022-a6c09ad42b
FEDORA-2022-b36d83b365
FEDORA-2022-73f6723a22
FEDORA-2022-fe90e14a6d
FEDORA-2022-6eb815ef9a
FEDORA-2022-eea62ab091
FEDORA-2022-5846b17a0b
FEDORA-2022-51d82192f0
FEDORA-2022-f0b7d00293
FEDORA-2022-024e962066
FEDORA-2022-6e05b60ac5
FEDORA-2022-facd5b1a6f
FEDORA-2022-0fbc6a1859
FEDORA-2022-783bcca1c8
FEDORA-2022-cf5f6b8ffe
FEDORA-2022-e257b91949
FEDORA-2022-f4a3420119
FEDORA-2022-7ed03b1e1d
FEDORA-2022-54705cf323
FEDORA-2022-67308ba402
FEDORA-2022-0703c702df
FEDORA-2022-646a6e6565
FEDORA-2022-bc3428ce39
FEDORA-2022-993acd01d8
FEDORA-2022-764b7a545f
FEDORA-2022-d8deb14890
FEDORA-2022-782e355000
FEDORA-2022-782e355000
FEDORA-2022-c6ef97e3ff
FEDORA-2022-23c7aaaf48
FEDORA-2022-c73f7001ef
FEDORA-2022-d3d42824a5
FEDORA-2022-caea8960cb
FEDORA-2022-86dd6be9a7
FEDORA-2022-9ce04c026f
FEDORA-2022-ed0ea5641b
FEDORA-2022-4aa92a7458
FEDORA-2022-c18f69f272
FEDORA-2022-68f6bf10da
FEDORA-2022-4836fdc251
FEDORA-2022-dc8f6909a8
FEDORA-2022-b2866add9b
FEDORA-2022-d5c7b7ce14
FEDORA-2022-d25b582aaa
FEDORA-2022-9ca955c418
FEDORA-2022-50f57c17fd
FEDORA-2022-0fe35daa23
FEDORA-2022-701ffa78f4
FEDORA-2022-b3577d16c5
FEDORA-2022-e64cbf68e3
FEDORA-2022-41cfa8ca83
FEDORA-2022-f10b620b98
FEDORA-2022-97e3c6f155
FEDORA-2022-f011454e29
FEDORA-2022-277bb54788
FEDORA-2022-6589f37f76
FEDORA-2022-e6bd967819
FEDORA-2022-dd87f0aa41
FEDORA-2022-4f50075ee3
FEDORA-2022-7abf08c215
FEDORA-2022-c4a2ddae21
FEDORA-2022-db8bbb3fb9
FEDORA-2022-b710d55b08
FEDORA-2022-7e23ab07f6
FEDORA-2022-d27e3b9946
FEDORA-2022-996141a3f8
FEDORA-2022-deadf37eb9
FEDORA-2022-4614d56eb2
FEDORA-2022-c612a8384d
FEDORA-2022-4bbc72b3cd
FEDORA-2022-45e029f013
FEDORA-2022-68cba191c1
FEDORA-2022-8dacd8e226
FEDORA-2022-303d6ab76e
FEDORA-2022-324f98b59c
FEDORA-2022-a4aa5e99ec
FEDORA-2022-4a94e4657c
FEDORA-2022-d57bcaf438
FEDORA-2022-5cf782813f
FEDORA-2022-b1cf7f3637
FEDORA-2022-56ee2c7d34
FEDORA-2022-8aa7437499
FEDORA-2022-18c32aa9b1
FEDORA-2022-5a27d5a21c
FEDORA-2022-c3bfca1d94
FEDORA-2022-ef840e2e27
FEDORA-2022-bbbadf3217
FEDORA-2022-ca3e33115d
FEDORA-2022-41506be091
FEDORA-2022-587f35dfae
FEDORA-2022-abaa679c4b
FEDORA-2022-c489378bed
FEDORA-2022-0080df0c7b
FEDORA-2022-519bfe5028
FEDORA-2022-b91e81a2b1
FEDORA-2022-6953b9fe7f
FEDORA-2022-aafe007571
FEDORA-2022-92cb20ffe6
FEDORA-2022-3bc253ac80
FEDORA-2022-010675279f
FEDORA-2022-bb32fa213c
FEDORA-2022-6313a12686
FEDORA-2022-445f2ddf19
FEDORA-2022-ef8d578b90
FEDORA-2022-e1c2fcc258
FEDORA-2022-1422671fca
FEDORA-2022-11018c9961
FEDORA-2022-3384d753aa
FEDORA-2022-43b56d6646
FEDORA-2022-49b24c5ed5
FEDORA-2022-a33a322880
FEDORA-2022-15935a28a8
FEDORA-2022-4ff4671f4d
FEDORA-2022-af6214639f
FEDORA-2022-e712679ddc
FEDORA-2022-a67fa1f0a7
FEDORA-2022-5903916f86
FEDORA-2022-7a9c309274
FEDORA-2022-410e722864
FEDORA-2022-1bcd99d22a
FEDORA-2022-916c5bfe4c
FEDORA-2022-6d64c0c343
FEDORA-2022-6242c142bd
FEDORA-2022-5ae4af0772
FEDORA-2022-089dc6991d
FEDORA-2022-b1b00251f0
FEDORA-2022-a7f0a0e427
FEDORA-2022-8c0dd21a95
FEDORA-2022-45492f5fee
FEDORA-2022-f9e8e8b250
FEDORA-2022-36d872b7ce
FEDORA-2022-9084bd55a0
FEDORA-2022-334ec24675
FEDORA-2022-149b1f044b
FEDORA-2022-0c6c7bdaa8
FEDORA-2022-975ec80e8f
FEDORA-2022-53250ba711
FEDORA-2022-3a71cdf9c1
FEDORA-2022-3fbd913430
FEDORA-2022-9913f95cf8
FEDORA-2022-7111a4a72c
FEDORA-2022-3ed1d0edc0
FEDORA-2022-46838697ab
FEDORA-2022-6af7e72d67
FEDORA-2022-67c6061d0f
FEDORA-2022-1e6dd5f8d8
FEDORA-2022-2b3af441f4
FEDORA-2022-4ae11ebed1
FEDORA-2022-b1cbdf8022
FEDORA-2022-f51c225490
FEDORA-2022-ed823af1c3
FEDORA-2022-e76b7d64a3
FEDORA-2022-bcc09da592
FEDORA-2022-b90f90b223
FEDORA-2022-b16fe127aa
FEDORA-2022-5cac27acd2
FEDORA-2022-701fafde95
FEDORA-2022-a05988292f
FEDORA-2022-0bd9804a12
FEDORA-2022-2bcc46af46
FEDORA-2022-ce9a1b2e59
FEDORA-2022-d98f30c497
FEDORA-2022-15a779c2f6
FEDORA-2022-d55689bdd4
FEDORA-2022-af28579599
FEDORA-2022-82630ab2f8
FEDORA-2022-6691726314
FEDORA-2022-f6f97efb29
FEDORA-2022-0e4905d36c
FEDORA-2022-196ffefe0d
FEDORA-2022-8337d0b00e
FEDORA-2022-9ce41d5f80
FEDORA-2022-79bedfa6ef
FEDORA-2022-072ffa501f
FEDORA-2022-fd29d38bd2
FEDORA-2022-5314a712b1
FEDORA-2022-ee494daa75
FEDORA-2022-64d2c0e142
FEDORA-2022-342f7cb752
FEDORA-2022-9711171f5d
FEDORA-2022-2aaa6cb8a0
FEDORA-2022-aef5e4d88c
FEDORA-2022-86fcb3752b
FEDORA-2022-0d6958b381
FEDORA-2022-6b31fa7ac8
FEDORA-2022-9117b6f9ce
FEDORA-2022-e51b605162
FEDORA-2022-eb57c6c844
FEDORA-2022-d676b975fe
FEDORA-2022-d84591ed1a
FEDORA-2022-f0d373533d
FEDORA-2022-b3059cf20f
FEDORA-2022-fe90b6a1dc
FEDORA-2022-4245003fb8
FEDORA-2022-bc7b641834
FEDORA-2022-16ddcfd367
FEDORA-2022-e322f8add3
FEDORA-2022-20ff043c0e
FEDORA-2022-124f0f5247
FEDORA-2022-ec8c255b53
FEDORA-2022-1bf7aff153
FEDORA-2022-72acee8eb2
FEDORA-2022-a4b99a6fe3
FEDORA-2022-14c8af199a
FEDORA-2022-7762216db7
FEDORA-2022-5f466413cf
FEDORA-2022-9cc20c2a8b
FEDORA-2022-8d30c2af78
FEDORA-2022-639aec5ef8
FEDORA-2022-023ab4db59
FEDORA-2022-61ed982714
FEDORA-2022-117be0a8ee
FEDORA-2022-8f12798ebf
FEDORA-2022-37aeb64af9
FEDORA-2022-384266e201
FEDORA-2022-b84b1d4c4e
FEDORA-2022-08621d40e8
FEDORA-2022-7def1853b3
FEDORA-2022-a9fd684b61
FEDORA-2022-6bf439decb
FEDORA-2022-9c9d5f67e9
FEDORA-2022-d65c7be86a
FEDORA-2022-2c5efba4c5
FEDORA-2022-e2530cd4d2
FEDORA-2022-52b8ebe0f3
FEDORA-2022-e9f53b5a23
FEDORA-2022-33d9633d95
FEDORA-2022-e03f5fe495
FEDORA-2022-6431566814
FEDORA-2022-fe05ecd90a
FEDORA-2022-7d862bcde3
FEDORA-2022-4013215972
FEDORA-2022-69889702f5
FEDORA-2022-14d4ac256f
FEDORA-2022-5df322852f
FEDORA-2022-09f4c2bbd3
FEDORA-2022-30417f5eae
FEDORA-2022-320da4727d
FEDORA-2022-61f42e2274
FEDORA-2022-223b0f7db3
FEDORA-2022-cd866e71aa
FEDORA-2022-44a76a2c05
FEDORA-2022-8c4728ba10
FEDORA-2022-ccb1e824eb
FEDORA-2022-07c27c94a9
FEDORA-2022-0287d8477a
FEDORA-2022-888aca8c94
FEDORA-2022-95927ee9c6
FEDORA-2022-1ff30ccbd4
FEDORA-2022-bdd12ed04e
FEDORA-2022-7d5a7aaa4c
FEDORA-2022-d966eba5e5
FEDORA-2022-859adfd44a
FEDORA-2022-7b8ce133a4
FEDORA-2022-4b1e0ab05a
FEDORA-2022-10a11a5653
FEDORA-2022-b13f46c5c9
FEDORA-2022-705e323605
FEDORA-2022-f161f99708
FEDORA-2022-1e10ba3beb
FEDORA-2022-6149f9e4a6
FEDORA-2022-cbf144fc44
FEDORA-2022-49c3fe029f
FEDORA-2022-3468157a57
FEDORA-2022-5f3528b731
FEDORA-2022-97fc3b27b4
FEDORA-2022-bb590505a9
FEDORA-2022-1e70a7f490
FEDORA-2022-7aa7103bc7
FEDORA-2022-161a3efcf4
FEDORA-2022-8030910133
FEDORA-2022-51bdc4f023
FEDORA-2022-c7015a3c16
FEDORA-2022-f579823011
FEDORA-2022-75a5d12fc8
FEDORA-2022-a3a8414768
FEDORA-2022-3b274a28a3
FEDORA-2022-9d0ad7773a
FEDORA-2022-c2e0afb00b
FEDORA-2022-d4c109754c
FEDORA-2022-c4635c7f28
FEDORA-2022-d719052558
FEDORA-2022-e0a5457b6a
FEDORA-2022-4d9b4cfb36
FEDORA-2022-d4776bc28e
FEDORA-2022-eb8f2979b5
FEDORA-2022-c714f1d166
FEDORA-2022-e719937285
FEDORA-2022-7e013e1a41
FEDORA-2022-92d1993630
FEDORA-2022-63c279b932
FEDORA-2022-6beddb9443
FEDORA-2022-bbe59113ee
FEDORA-2022-1459126427
FEDORA-2022-da98783050
FEDORA-2022-71bddbab01
FEDORA-2022-94ebe807de
FEDORA-2022-f2e819888f
FEDORA-2022-4feb2d2ef6
FEDORA-2022-44d53d6366
FEDORA-2022-296962679c
FEDORA-2022-213df11fc3
FEDORA-2022-630b2deb71
FEDORA-2022-93b910a7b6
FEDORA-2022-0e6ff10104
FEDORA-2022-edf99e99a4
FEDORA-2022-59e41a4d35
FEDORA-2022-dd2d37869d
FEDORA-2022-072af1350b
FEDORA-2022-cdac132ee9
FEDORA-2022-f73e3034bc
FEDORA-2022-e06d9e7471
FEDORA-2022-db101b84a1
FEDORA-2022-58fb4b9562
FEDORA-2022-be6ba1ef83
FEDORA-2022-1cb782759a
FEDORA-2022-835597fb48
FEDORA-2022-1daca1d065
FEDORA-2022-0df2bf68fe
FEDORA-2022-8a0ce26e3f
FEDORA-2022-b14cff1785
FEDORA-2022-a1e980ffca
FEDORA-2022-eb656cb74a
FEDORA-2022-2811371c0d
FEDORA-2022-401d2c2f91
FEDORA-2022-99d404138d
FEDORA-2022-c659c5ffb4
FEDORA-2022-a65d6a9e1b
FEDORA-2022-0f0e000f0d
FEDORA-2022-ceb7c5b9bd
FEDORA-2022-74f08330a0
FEDORA-2022-eff0ca3deb
FEDORA-2022-1aca70fa19
FEDORA-2022-1ee4ff02f6
FEDORA-2022-d3a570c955
FEDORA-2022-fa4be27d5b
FEDORA-2022-679f7e3111
FEDORA-2022-63cdd7487f
FEDORA-2022-b28875be3e
FEDORA-2022-80b60d4450
FEDORA-2022-adaaa979b7
FEDORA-2022-11c8a83796
FEDORA-2022-6ac4e88048
FEDORA-2022-817fdd7fac
FEDORA-2022-6678f206f6
FEDORA-2022-aa1263b1f5
FEDORA-2022-e2b7a2f744
FEDORA-2022-d14172cee6
FEDORA-2022-0fd1bb399c
FEDORA-2022-b7815f1cc7
FEDORA-2022-a9fe24df56
FEDORA-2022-48c89dafb3
FEDORA-2022-bad10b4ef1
FEDORA-2022-2205c7a9d1
FEDORA-2022-ca622c0fcd
FEDORA-2022-3b87b795e4
FEDORA-2022-3092d937f6
FEDORA-2022-7f604cc0fa
FEDORA-2022-6889f2a36d
FEDORA-2022-d9ea3bb3d5
FEDORA-2022-696e0d747f
FEDORA-2022-6e2027ad46
FEDORA-2022-95faf9ba86
FEDORA-2022-02ec72e7d2
FEDORA-2022-03281fc5aa
FEDORA-2022-4025e6bdae
FEDORA-2022-5871ac7e02
FEDORA-2022-2e49fc2330
FEDORA-2022-18a9fdf0ab
FEDORA-2022-ee9786ff8c
FEDORA-2022-3c4d0fc734
FEDORA-2022-73314f32e8
FEDORA-2022-8bd6cf2646
FEDORA-2022-a7e7b23a9f
FEDORA-2022-77efba887f
FEDORA-2022-b6175cd0db
FEDORA-2022-0248964d90
FEDORA-2022-8b19efc250
FEDORA-2022-81bea47597
FEDORA-2022-f0f7c0afb0
FEDORA-2022-3dbbeef28b
FEDORA-2022-07b6ec0582
FEDORA-2022-392b61a2b9
FEDORA-2022-455e00c465
FEDORA-2022-9ecaa858f5
FEDORA-2022-65cd409e42
FEDORA-2022-91084c798d
FEDORA-2022-a6f34d9a7e
FEDORA-2022-374ae5743f
FEDORA-2022-992c47bc91
FEDORA-2022-9ee08526e3
FEDORA-2022-0c36ed37f8
FEDORA-2022-3974dc3645
FEDORA-2022-335a640566
FEDORA-2022-c0e922d723
FEDORA-2022-6ce711274c
FEDORA-2022-3e52a3e7ee
FEDORA-2022-e3ad3ad52f
FEDORA-2022-d0243b55a5
FEDORA-2022-b998cf4be3
FEDORA-2022-9df909ee0a
FEDORA-2022-04b05978d5
FEDORA-2022-1c6bc32f3d
FEDORA-2022-512660e310
FEDORA-2022-f8731b5637
FEDORA-2022-f06189654f
FEDORA-2022-ea90f89760
FEDORA-2022-8894b6b0e2
FEDORA-2022-d08ae5de41
FEDORA-2022-b8caf68206
FEDORA-2022-e4f714d52e
FEDORA-2022-947ba325e7
FEDORA-2022-bb49178c5f
FEDORA-2022-c36f4d61b3
FEDORA-2022-7b797f2c35
FEDORA-2022-d4d48649ba
FEDORA-2022-565db60dfb
FEDORA-2022-7e4ea1a47e
FEDORA-2022-f59457bd1e
FEDORA-2022-894d84995e
FEDORA-2022-23bf6736ad
FEDORA-2022-173cc1b163
FEDORA-2022-7988160de0
FEDORA-2022-b6427f47ad
FEDORA-2022-7cc646ea47
FEDORA-2022-b0255bcae1
FEDORA-2022-0715ec4a42
FEDORA-2022-e7ba772531
FEDORA-2022-912a56247a
FEDORA-2022-97e7166c0f
FEDORA-2022-bb499d1b0d
FEDORA-2022-ea044ba9f9
FEDORA-2022-0325974b51
FEDORA-2022-4ec0822df4
FEDORA-2022-96cb238605
FEDORA-2022-08484c12ff
FEDORA-2022-aca14f566a
FEDORA-2022-8395937859
FEDORA-2022-ecf2e7a8b1
FEDORA-2022-29d30c2f7b
FEDORA-2022-e1a516d4f2
FEDORA-2022-e1bd17a5aa
FEDORA-2022-bf57882da2
FEDORA-2022-5b4b09cddf
FEDORA-2022-49f99453dd
FEDORA-2022-4f6973bbe7
FEDORA-2022-5aaa596cb4
FEDORA-2022-1f8c3db0ac
FEDORA-2022-8d2fc35845
FEDORA-2022-4ecb9e0d9a
FEDORA-2022-9a661f7ef3
FEDORA-2022-82d804691f
FEDORA-2022-e201c9563e
FEDORA-2022-1ae42a1b4d
FEDORA-2022-40820d027c
FEDORA-2022-e3a6462125
FEDORA-2022-50111cf1cb
FEDORA-2022-d6a04ebfe0
FEDORA-2022-739becbda6
FEDORA-2022-6556d96cb1
FEDORA-2022-e8c5c4fa18
FEDORA-2022-88a7750b80
FEDORA-2022-4230851edb
FEDORA-2022-6bbebfb559
FEDORA-2022-5a9a3fc77b
FEDORA-2022-5785314522
FEDORA-2022-187053b1ed
FEDORA-2022-9bc0bede73
FEDORA-2022-bb53eca4a7
FEDORA-2022-38895007a9
FEDORA-2022-062b63f2e9
FEDORA-2022-37068e24f0
FEDORA-2022-35cd1a22cf
FEDORA-2022-c244badab3
FEDORA-2022-b45f0d52d1
FEDORA-2022-7d0b76c0d7
FEDORA-2022-f038faa263
FEDORA-2022-cb6a1fb8f5
FEDORA-2022-a480674f0d
FEDORA-2022-e1cde400a2
FEDORA-2022-9bb8e68972
FEDORA-2022-0f0e99884b
FEDORA-2022-4a5e4be1a4
FEDORA-2022-1fed08f795
FEDORA-2022-ea6e5ac315
FEDORA-2022-8741c2db31
FEDORA-2022-84915afdb5
FEDORA-2022-ff0417a281
FEDORA-2022-33ac8bb651
FEDORA-2022-7246d1ed85
FEDORA-2022-fef5ba35a9
FEDORA-2022-a2d584b8c1
FEDORA-2022-8838e93ffd
FEDORA-2022-2e2adec828
FEDORA-2022-167fa55862
FEDORA-2022-ed6b76ffc0
FEDORA-2022-981ce33462
FEDORA-2022-5dfc1fd600
FEDORA-2022-d76ddf2da3
FEDORA-2022-fa2076ed84
FEDORA-2022-482ce2afca
FEDORA-2022-5f29070d4b
FEDORA-2022-94587d9c88
FEDORA-2022-c05cec216d
FEDORA-2022-e4421f1954
FEDORA-2022-2657ba9f1d
FEDORA-2022-80ee1d19aa
FEDORA-2022-4c378d5ea0
FEDORA-2022-7e0b35070d
FEDORA-2022-c813f5ccdf
FEDORA-2022-4804751298
FEDORA-2022-0d0c429a1e
FEDORA-2022-a01f55ab8a
FEDORA-2022-f378d543b2
FEDORA-2022-d303b32d25
FEDORA-2022-9c1cd871a8
FEDORA-2022-e8f45387e8
FEDORA-2022-737d7c1359
FEDORA-2022-2f208fed08
FEDORA-2022-4f584180c4
FEDORA-2022-6487837a04
FEDORA-2022-12b86712e5
FEDORA-2022-9b9bc7f5e0
FEDORA-2022-fcf6d6b47a
FEDORA-2022-934cc5d062
FEDORA-2022-6368f1627c
FEDORA-2022-f763013556
FEDORA-2022-49821915ee
FEDORA-2022-8c654fd9fa
FEDORA-2022-306127890d
FEDORA-2022-d12e0e9233
FEDORA-2022-ae6ec5b7e4
FEDORA-2022-fd45a72de0
FEDORA-2022-ef0e754ad3
FEDORA-2022-93dc80dad4
FEDORA-2022-4af7d5443e
FEDORA-2022-2d678367ac
FEDORA-2022-05238c27da
FEDORA-2022-ebfa613865
FEDORA-2022-b12a165cd4
FEDORA-2022-986a793623
FEDORA-2022-5d66dd40d7
FEDORA-2022-2950d4787e
FEDORA-2022-92cf7a2b90
FEDORA-2022-c94ea70ea6
FEDORA-2022-5bf77de9a3
FEDORA-2022-48bed54e85
FEDORA-2022-c95e1a0ff0
FEDORA-2022-0e4cc4682c
FEDORA-2022-32231b5e48
FEDORA-2022-cef291d453
FEDORA-2022-10c53aee99
FEDORA-2022-2bbf2eec94
FEDORA-2022-791afa76b9
FEDORA-2022-603a19c819
FEDORA-2022-4515d55c35
FEDORA-2022-a57f5f6c08
FEDORA-2022-23220001e5
FEDORA-2022-b6e965f7e4
FEDORA-2022-4d6d274960
FEDORA-2022-0ff4ec299c
FEDORA-2022-c5568a75a3

</details>

<details>
<summary> List of large (> 10 KiB) human-created updates (Fedora 37 only, no guarantee for completeness) </summary>

    FEDORA-2022-f35fb40609 prosody-0.12.1-1.fc37                                robert          10.4 KiB
    FEDORA-2022-3f9a2795e7 fail2ban-1.0.1-2.fc37                                hobbes1069      12.6 KiB
    FEDORA-2022-4c634ee466 ckeditor-4.20.0-1.fc37                               siwinski        27.4 KiB
    FEDORA-2022-6be9fa2074 fail2ban-1.0.1-1.fc37                                hobbes1069      12.6 KiB
    FEDORA-2022-663c97ec34 ca-certificates-2022.2.54-2.fc37                     rrelyea         11.1 KiB
    FEDORA-2022-0bfee9488f neomutt-20220629-1.fc37                              flatcap         15.2 KiB
    FEDORA-2022-c61cc2a3cd annobin-10.76-3.fc37                                 nickc           26.2 KiB
    FEDORA-2022-a974db2b7e obserware-0.2.9-1.fc37                               t0xic0der       13.5 KiB
    FEDORA-2022-1c3cd6915b kexec-tools-2.0.24-3.fc37                            coiby           19.8 KiB
    FEDORA-2022-70c8a90d20 kernel-5.18.0-0.rc7.20220519gitf993aed406ea.56.fc37  jforbes         258.1 KiB
    FEDORA-2022-82b17ba316 snapd-2.55.2-1.fc37                                  bboozzoo        17.7 KiB
    FEDORA-2022-3a93fe1a2f kernel-5.18.0-0.rc0.20220324gited4643521e6a.6.fc37   jforbes         76.5 KiB
    FEDORA-2022-426b321db2 glibc-2.35.9000-4.fc37                               codonell        12.7 KiB
    FEDORA-2022-5b24c1b7da gdb-11.2-2.fc37                                      kevinb          11.8 KiB

</details>

**Comment by mattiaverga** [comment]
```
>>> from sqlalchemy.sql.expression import func
>>> ups = s.query(m.Update.alias).filter(func.length(m.Update.notes) > 10000).all()
>>> len(ups)
1104
>>> ups = s.query(m.Update.alias).filter(func.length(m.Update.notes) > 15000).all()
>>> len(ups)
929
```
This is run on 3-weeks-old database snapshot, however I think the numbers haven't changed too much. There are nearly 1.100 update with notes length above 10k characters. I suppose most of these are due to changelog notes copied over and over, so it should be simple to trim them down to size.

I plan to put a cap of 10k characters to the notes in the next version, then I'll trim the existent updates down to the size running a script on bodhi backend directly (I prefer not to run a db migration and have it automatically do the cut). The 10k limit is debatable, though.

**Comment by decathorpe** [comment]
Looks great! Thank you for working on this. ❤️
