### ISSUE TITLE
Test Cases tab in the web UI is blank

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#5000]
I caught this report on chat.fedoraproject.org, and can confirm it myself:

(wayne6001) on the page for commenting on the kernel in the test repo, the link for "Test Cases" no longer provides information.  It used to say how many submitters passed or failed the regression tests.
(wayne6001) https://bodhi.fedoraproject.org/updates/FEDORA-2023-0597579983

as Wayne says, if you click on the "Test Cases" tab, it no longer shows information on reported test case passes/fails; in fact it shows nothing at all, it's completely blank.

This is probably fallout from a change in 7.0, perhaps the update to fedora-bootstrap 2.x?

**Comment by mattiaverga** [comment]
Sigh, I completely forgot about the testcases tab when I updated the template... I'll fix it ASAP
