### ISSUE TITLE
Investigate memory leak

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#503]
:non-potable_water:

**Comment by lmacken** [comment]
I discovered a number of huge strings in memory...

https://paste.fedoraproject.org/264601/65058144/

**Comment by lmacken** [comment]
It looks like this is the results of `get_update`, since it's the only place that sets `can_edit`.

**Comment by lmacken** [comment]
Okay, I think my initial hunch was actually due to the pyramid_debugtoolbar. More investigation is needed.

This article might help people dive in and poke around: https://chase-seibert.github.io/blog/2013/08/03/diagnosing-memory-leaks-python.html

**Comment by ralphbean** [comment]
I think this may be solved now.  We have the procs/threads back up and it hasn't faltered yet.  Can we close it @lmacken?

**Comment by lmacken** [comment]
Yep, I think we're good to go. I just cranked the threads up to 15 with 4 processes, and it's been rock solid. I'll keep bumping up the processes over the next week or so to find the sweet spot.

**Comment by ralphbean** [comment]
> I'll keep bumping up the processes over the next week or so to find the sweet spot.

Remember when you do, you have to also run:

```bash
# This tells the world to start looking for those new ports
ansible-playbook $(pwd)/master.yml -t fedmsgdconfig,fedmsgmonitor
# This tells iptables on the bodhi web nodes to open up for those new connections
ansible-playbook $(pwd)/playbooks/groups/bodhi2.yml -t iptables,fedmsgdconfig,bodhi2
```
