### ISSUE TITLE
Unable to push f23 update to stable repository

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/bodhi#505]
I have this update https://bodhi.fedoraproject.org/updates/FEDORA-2015-14896 which is having zero karma and already in testing for 4 days. When I attempt to push that update to stable I will get popup about package update acceptance criteria.

**Comment by lmacken** [comment]
Hmm, this should have been fixed by an alembic migration script that I think @ralphbean ran on Saturday. https://github.com/fedora-infra/bodhi/blob/develop/alembic/versions/3dbed75df3fe_set_testing_stable_dates_for_all_old_.py

**Comment by lmacken** [comment]
Ok, I think this is related to PR #477 and the migration script looking for them without properly handling the old style comments.

I'll update the migration script and run it again now.

**Comment by lmacken** [comment]
I think this issue has been resolved.

**Comment by pnemade** [comment]
Still issue is there, can't push this another update to stable https://bodhi.fedoraproject.org/updates/FEDORA-2015-14825

**Comment by pnemade** [comment]
yes I confirm this issue is resolved.
