### ISSUE TITLE
frozen state doesn't allow pushing stable updates correctly

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#5080]
Pending releases (before we have enabled the 'updates' repo at the very end of the cycle before release) 'compose' in bodhi by just tagging the builds and doing it's normal process _except_ it does not call pungi and compose the repo. We just want it to tag builds in and the nightly compose will add them to the base repo. 

Currently in bodhi/server/tasks/composer.py we have: 

```
    def work(self):
        """Perform the various high-level tasks for the compose."""
        self.id = getattr(self.compose.release, '%s_tag' % self.compose.request.value)

        # Set our thread's "name" so it shows up nicely in the logs.
        # https://docs.python.org/2/library/threading.html#thread-objects
        self.name = self.id

        # For 'pending' branched releases, we only want to perform repo-related
        # tasks for testing updates. For stable updates, we should just add the
        # dist_tag and do everything else other than composing/updateinfo, since
        # the nightly build-branched cron job composes for us.
        self.skip_compose = False
        if self.compose.release.state is ReleaseState.pending \
                and self.compose.request is UpdateRequest.stable:
            self.skip_compose = True
```

But... now with the new 'frozen' state, our ReleaseState is now 'frozen' not pending... so bodhi fires off a pungi task trying to do a f38-updates compose. :( 

I guess we should check for both frozen and pending here. 
(Because before and after freeze we want automatic updates to go to the base repo, during freeze we also want that and the freeze should prevent anyone but releng of doing pushes with stable requests.

**Comment by mattiaverga** [comment]
But a f38 stable compose should not exist at all. The push script should just create a f38 testing compose, so there should be no need to skip a f38 stable compose in composer...

**Comment by nirik** [comment]
> But a f38 stable compose should not exist at all. The push script should just create a f38 testing compose, so there should be no need to skip a f38 stable compose in composer...

But they do! There's builds that fix blockers or FE's... and QA requests those specific builds go through the freeze. 
So, a release engineer does that with a 'bodhi push --builds ...' and bodhi tags them and updates their updates, then the nightly compose script adds them to that nights compose. :)

**Comment by mattiaverga** [comment]
@nirik I've deployed the current 7.1 branch to staging.
Let me know if you want to deploy the update in the windows between beta and final freeze (is it possible?) and I'll build the final 7.1 release in time.

**Comment by nirik** [comment]
Yeah, that sounds good. Do remind me after freeze and we can get it deployed. ;)
