### ISSUE TITLE
Clicking "& X more" link in update title while you have text in the comment box wipes the text

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#5089]
I was writing a long comment into an update - https://bodhi.fedoraproject.org/updates/FEDORA-2023-f6afa6f9e5 - and needed to know the names of the packages in the update. Stupidly, I clicked the "fwupd-1.8.12-1.fc38, libjcat-0.1.13-1.fc38, & 1 more" link at the top of the page. This didn't show me the "1 more" package name, but it *did* wipe the entire text of my comment, apparently irretrievably.

Is there anything we can do about this footgun?

**Comment by mattiaverga** [comment]
I suppose we can drop the link, I see no purpose to have the title link to the same page?
