### ISSUE TITLE
Override problems

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/bodhi#510]
I submitted overrides for `nodejs-should-format-0.3.0-2.fc23` and `nodejs-should-equal-0.5.0-2.fc23` last night, but this morning they still hadn't reached f23-build although they did have the f23-override tag.

Then I submitted them for testing, in the hope that would have some sort of effect, but that just seems to have made things worse as that caused the `f23-override` tag to be removed, so now I can't even cancel the override as it tells me they aren't tagged as overrides...

**Comment by tomhughes** [comment]
Any news on this? As things stand I have broken overrides for `nodejs-should-type-0.2.0-2.fc23`, `nodejs-should-format-0.3.0-2.fc23` and `nodejs-should-equal-0.5.0-2.fc23` than don't work but can't be extended or expired. Indeed they have all passed their expiration deadlines now but bodhi still thinks they are active even though the packages are't tagged.

My fallback plan was to wait for them to hit stable as they have now passed their testing period, but I see we're not in beta freeze so nothing is going to be pushed to stable for some time.

**Comment by lmacken** [comment]
I believe this issue has been resolved.
