### ISSUE TITLE
Reset karma on updates when an edit changes the list of builds.

### ISSUE THREAD

**Issue by lkundrak** [fedora-infra/bodhi#511]
https://bodhi.fedoraproject.org/updates/NetworkManager-pptp-1.1.0-3.20150428git695d4f2.el7/edit

This one had -1 karma threshold and got a -1 karma. It was fixed since, but as karma count was not reset it keeps unpushing itself.

**Comment by ralphbean** [comment]
Just to be clear:

- What did you do to fix the update?  Did you edit it to change the build?

**Comment by lkundrak** [comment]
>  What did you do to fix the update? Did you edit it to change the build?

Yes. Should be clear from the log I guess: "lkundrak edited this update. New build(s)"
