### ISSUE TITLE
Bodhi changing a version number in Bugzilla

### ISSUE THREAD

**Issue by jkonecny12** [fedora-infra/bodhi#513]
My [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1252902) in bugzilla have bad version number when bodhi closed it.

Seems to me like bodhi have problems when the patch goes to multiple projects with *Resolves* and *Related* tags.

**Comment by ralphbean** [comment]
Confirmed.  It looks like bodhi used the version from the wrong build in a multi-build update to close the bug for that package.
