### ISSUE TITLE
Disallow obsoleting an update without providing which update obsoletes it

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#515]
The following update has been obsoleted by something but there's no indication (at least that I can see) in the UX what it's actually been obsoleted by:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-14219

If I remember correctly bodhi1 use to provide a link to the newer update that you could follow to see what update it was replaced by.

**Comment by ralphbean** [comment]
:+1:, the link would be very nice to have.

**Comment by ralphbean** [comment]
Upon looking closer, it looks like this is somewhat on purpose.  The normal auto-obsoletion code that gets fired when you submit a new update does work and it at least mentions what the new update is.

There are other code paths where an *admin* can forcibly obsolete an update.. but they can do so without indicating what other update obsoleted it.  Perhaps this is what happened here?  Hard to tell.

**Comment by nullr0ute** [comment]
It would be useful to be able to tell from an aufit PoV

**Comment by ralphbean** [comment]
OK, I'm changing the title of the ticket here to reflect more precisely what we need to do.

**Comment by bowlofeggs** [comment]
I believe this has been solved sometime in the past. For example, I can see a comment on [this kernel update](https://bodhi.fedoraproject.org/updates/FEDORA-2018-a3c4dabf9c) that says "This update has been obsoleted by kernel-4.15.6-300.fc27.", with a link to the new update.
