### ISSUE TITLE
Make "Close bugs on stable?" more fine grained

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#5179]
Working on updates such as [[1], [2]], it would be useful if the "Close bugs on stable?" option was more granular. I'd like to close the [rebase ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2032639), while the [CVE tracker](https://bugzilla.redhat.com/show_bug.cgi?id=2179644) should stay open until the issue is addressed also in F36.

If Bodhi was even smarter, being able to somehow deduce this automatically, that would be even better.

[1]: https://bodhi.fedoraproject.org/updates/FEDORA-2023-d6157bb1e2
[2]: https://bodhi.fedoraproject.org/updates/FEDORA-2023-7002afbbb8

**Comment by mattiaverga** [comment]
Closing as duplicate of #3175
