### ISSUE TITLE
Confusion about obsoletion behavior

### ISSUE THREAD

**Issue by sagitter** [fedora-infra/bodhi#518]
Hi,

i don't know how to remove an update not necessary anymore: https://bodhi.fedoraproject.org/updates/FEDORA-2015-14575
I don't see any "delete" button or something like that, neither i found something useful by using the "Edit" button.

Thanks.

**Comment by ralphbean** [comment]
Ah, there is no more "delete" functionality in Bodhi2.

Should it have been obsoleted by a different update, or...?

**Comment by sagitter** [comment]
>Should it have been obsoleted by a different update, or...?

Yes, theorically, but in this case the update of the same package has been submitted by another packager with whom i'm collaborating.

**Comment by bowlofeggs** [comment]
Is there any action to take on this ticket, or should we close it?
