### ISSUE TITLE
some recently-editted updates not queue'd for -testing

### ISSUE THREAD

**Issue by rdieter** [fedora-infra/bodhi#521]
per summary, some recently edited updates never got re-queue'd for -testing, they've been sitting for ~12 days now.  They are:
f21 https://bodhi.fedoraproject.org/updates/FEDORA-2015-14270
f22 https://bodhi.fedoraproject.org/updates/FEDORA-2015-14272
f23 https://bodhi.fedoraproject.org/updates/FEDORA-2015-14271

the f23 one has other issues (and has a separate ticket filed already), I only included it here for completeness.

**Comment by lmacken** [comment]
I fixed this 7 days ago in64a28c83c1a2ded435b593cda46b08fdd574d4a1

**Comment by lmacken** [comment]
Closing, as they should all be hopefully going to the right place now.
