### ISSUE TITLE
Tuna CLI is broken after update to 0.19

### ISSUE THREAD

**Issue by Upcycle-Electronics** [fedora-infra/bodhi#5228]
Hey I don't ususally make these issues and am bad about responding to internet stuff. Sorry in advance for any poor info. I am on Silverblue F37 
The Tuna package was updated from 18-1 to 19. After the update the command line for tuna does not appear to work at all. My usual command I use to help speed up FreeCAD by reducing non voluntary context switching does not work  ```sudo tuna --cpus=2,3 --isolate --affect_children --run="sudo --user=$USER -i flatpak run --branch=beta org.freecadweb.FreeCAD"``` I have tried simplifying the commands to see if something I am doing is causing the failure but that does not seem to be the case. I can't seem to get anything to run using the tuna CLI. The tuna GUI starts up and runs without an issue on 0.19. I did not do any further testing of the GUI functions.

**Comment by mattiaverga** [comment]
Hello, this is not the right place where to report such such problem.
Please report it on https://bugzilla.redhat.com/
