### ISSUE TITLE
Bugs are removed upon "edit"

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#5233]
I just wanted to add additional tickets to this update:

https://bodhi.fedoraproject.org/updates/FEDORA-2023-6b924d3b75

There are 4 bugs assigned ATM:

![image](https://user-images.githubusercontent.com/14406/231987537-bafcda30-30f7-4400-8c6d-50da4ceb4a31.png)

But after pressing "Edit", the bugs are gone:

![image](https://user-images.githubusercontent.com/14406/231987676-38bca645-09c6-49fe-9a64-61b202234b50.png)

 That is unexpected and very inconvenient.

**Comment by juhp** [comment]
Could the deployment be tracked here or somewhere else?
I think it is a pretty serious bug.

**Comment by gotmax23** [comment]
https://pagure.io/fedora-infrastructure/issue/11274 tracks the
deployment of bodhi 7.2.0.

**Comment by mattiaverga** [comment]
@nirik has updated bodhi 7.2.0 in prod, so the bug should be fixed now. Let me know if you spot something else.
Sorry for the troubles.
