### ISSUE TITLE
"fedpkg update" strips double %% from commits and then fails as a result

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#527]
If I have a commit changelog in either the rpm change log and git change log (not sure where fedpkg update pulls it from) it's stripped from the bodhi.template and then bodhi crashes as a result.

I'm not sure if this should be reported in fedpkg, python-fedora or bodhi

the notes line from the template is "notes=Use %configure macro as it deals with config.sub/guess and various flags properly"

Crash is:

$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: Commands._hash_file is deprecated and will be removed eventually.
    Please use Commands.lookasidecache.hash_file instead.
  hash = self.cmd._hash_file('bodhi.template', 'sha1')
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 209, in main
    updates = bodhi.parse_file(input_file=opts.input_file)
  File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 293, in parse_file
    'notes': config.get(section, 'notes'),
  File "/usr/lib64/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib64/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib64/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%configure macro as it deals with config.sub/guess and various flags properly'
Could not generate update request: Command 'bodhi --new --release f23 --file bodhi.template nrpe-2.15-7.fc23 --username pbrobinson' returned non-zero exit status 1

If I update the template with %%configure and run the above bodhi command line it submits fine

**Comment by bowlofeggs** [comment]
This appears to be about bodhi-0.9 based on the traceback, and this repo is for Bodhi >= 2 (currently 3.7.0).
