### ISSUE TITLE
critpath update confusion

### ISSUE THREAD

**Issue by lkundrak** [fedora-infra/bodhi#530]
More bodhi trouble here https://bodhi.fedoraproject.org/updates/FEDORA-2015-15337
What actually happened?
1. it's a critpath update
2. mmahut accidentally gave it +1 -1 karma
3. it got marked "obsolete" (wtf?)
4. them mmahut added another +1 +1
5. the update was submitted to stable. despite it's not too clear whether it has met the critpath criteria; it has just +1 karma and got a negative -1

I'm utterly confused.

**Comment by lmacken** [comment]
Everything worked as expected.

You set the karma thresholds to +1/-1, so mmahut's initial -1 unpushed/obsoleted it. Then his +1 reversed his initial vote and triggered the stable threshold. Since F23 was in pre-beta, critpath updates only need a minimum of 1 karma to go to stable.

**Comment by lmacken** [comment]
We should update the karma threshold messages to make this more clear. And also instead of 'obsolete' it should just get marked as 'unpushed' or we could even add an 'unstable' state.
