### ISSUE TITLE
The "Fixed In Version" Bugzilla field should contain NVRs

### ISSUE THREAD

**Issue by contyk** [fedora-infra/bodhi#531]
Traditionally, the "Fixed In Version" field in Bugzilla contained NVRs (separated by spaces where applicable). The current instance uses only VRs.

This adds an unnecessary inconsistency and confusion in cases where a bug is fixed by multiple packages, each with a different version.

**Comment by voxik** [comment]
This is related to #428 and #528

**Comment by ralphbean** [comment]
For reference, can you link me to one or two bugs that used the fixed-in version this way?

**Comment by contyk** [comment]
Sure.
https://bugzilla.redhat.com/show_bug.cgi?id=1134882
https://bugzilla.redhat.com/show_bug.cgi?id=1256190
https://bugzilla.redhat.com/show_bug.cgi?id=1256193
