### ISSUE TITLE
Can't comment on locked update(?)

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#539]
I twice tried to post a comment on https://bodhi.fedoraproject.org/updates/FEDORA-2015-15401 while it was showing "Locked: This update is currently locked and cannot be modified." Both times the comment and karma values did not appear. I wasn't focused on the tab so I didn't see if there was an error message (seriously, those vanishing error messages are an awful idea for something as slow as Bodhi, no-one sits there on the tab for a minute while they wait!)

The update being locked should not prevent comment/karma submissions, I don't think, if that's what's going on.

**Comment by ralphbean** [comment]
- Yes.  The update being locked should not prevent comment/karma submission.  Agreed!  However, we'd have to be careful that a comment with karma that pushes something above or below the karma threshold(s) doesn't send us into a weird/inconsistent state.
- On the error messages vanishing... the error messages are actually supposed to stay-put.  The "info" and "success" notifications vanish, but error ones should stick around until you manually dismiss them.  Try hard-reloading a page to make sure your browser doesn't have any old assets cached (this was introduced a week ago or so...).

**Comment by ralphbean** [comment]
Also, it takes an *insanely* long time to comment on that update.  What's going on!?

**Comment by ralphbean** [comment]
Ha, so I was able to comment on it.. but I just so happened to try it as it was completing the push, so I can't say what was what.

**Comment by ralphbean** [comment]
#542 leads in the direction of closing this as not-a-bug (although there are other problems, as we've both touched on here).

**Comment by AdamWill** [comment]
well, I definitely tried to submit my comment twice, and it definitely didn't wind up appearing in the update.

**Comment by ralphbean** [comment]
Sorry adam :(  I don't have any other information to go on at the moment.  If it happens to you again, can you make a note of the time in UTC and re-open this bug so we can go hunting in the logs?

**Comment by dhgutteridge** [comment]
I just encountered this same problem commenting on [https://bodhi.fedoraproject.org/updates/FEDORA-2017-8a540cb555](https://bodhi.fedoraproject.org/updates/FEDORA-2017-8a540cb555). It was in the process of being pushed to testing (though in the current incarnation of Bodhi, there was no visible notification I could see that this was the case), and Bodhi simply didn't record the input. This was between 19:00 and 20:00 UTC. (I resubmitted after it was pushed, and Bodhi accepted that input.)

**Comment by bowlofeggs** [comment]
@dhgutteridge I looked at the logs and I found when you logged in, but I didn't see anything enlightening. I also witnessed someone commented on one of my locked updates today so I know that it at least sometimes works.

Is there a possibility that you hit the stale CSRF token error and maybe didn't notice the popup in the lower right of the window? That seems to happen often (I think there's a bug somewhere about making the CSRF token valid longer because it's way too short as-is).

**Comment by dhgutteridge** [comment]
@bowlofeggs: I did hit a stale CSRF token, and refreshed, and then supplied the input again. The second time, the button at the bottom greyed out and had the little spinning icon for some minutes, and then nothing happened. It's possible I missed a stale CSRF token popup again, but I don't think I've ever seen the token issue again after a refresh (and I must have hit the stale token issue literally at least a hundred times). Then, after it hit testing, I tried a third time, and it worked. This isn't the first time I've encountered this, though it doesn't happen that frequently. In fact, #717 happens for me more frequently.

**Comment by dhgutteridge** [comment]
(BTW, with the current version of Bodhi, error messages like the stale CSRF token popup don't disappear. They stay visible on the page until the user closes them or refreshes the page. I think the rule is that lower priority notifications flash by quickly, but errors linger.)
