### ISSUE TITLE
Bodhi tests reporting broken composer in Rawhide

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#5405]
After the switch to dnf5 in Rawhide, the tests related to the composer / sanity checking the created repository are broken. The errors returned by dnf5 trying to load the test repository are something like:
```
Failed to load updateinfo extension for repo "testrepo" from "/var/cache/libdnf5/testrepo-fdf00cb61b01f01d/repodata/2f5afb18bc473546bdcceb4d0a2a6ed0b50a072aa385f4628cf20bc8749e9264-updateinfo.xml.zck": repo_updateinfoxml: Document is empty
 at line 1:1
```
For a full log just look at any failing Rawhide unit test in any PR.

I'm not sure if these failures are due to something we mock or if we're really creating bad repository metadata (which were tolerated by dnf4, but no more with dnf5). Or if it's a dnf5 fault.
@nirik @abompard any chance you could have a look, when you have some time?

**Comment by nirik** [comment]
Yeah, I am not sure whats going on here... I do see it's looking for the .zck file? Thats a zchunk delta... do we actually make those for the tests?
