### ISSUE TITLE
Why is "Bodhi's <nvr> bodhi update is ready for testing"?

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#5415]
Why does it say "Bodhi's" rather than "robert's"? This was my build.

```
Date: Thu, 13 Jul 2023 02:15:01 +0000 (UTC)
From: Fedora Notifications <notifications@fedoraproject.org>
To: <me>
Subject: [bodhi] Bodhi's openbgpd-8.1-1.fc38 bodhi update is ready for testing

Bodhi's Bodhi update is ready for testing
Builds:
openbgpd-8.1-1.fc38
https://bodhi.fedoraproject.org/updates/FEDORA-2023-6066e3b755-6059fc568b21d894d31f6122d5705dadf395ea1a
```

Note that the "next" e-mail contains my username correctly, see fedora-infra/bodhi#5416 for an example (even the issue itself is about another topic).

**Comment by abompard** [comment]
Good question! I'll transfer this issue to the Bodhi repo, where the messages schemas live. Thanks!
