### ISSUE TITLE
Show when update will be available for install

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/bodhi#5428]
I am waiting for https://bodhi.fedoraproject.org/updates/FEDORA-2023-19d6196f4a to arrive and I have no idea when it will happen. The instruction supplied on the page doesn't work and it is not clear why.

```bash
$ sudo dnf upgrade --advisory=FEDORA-2023-19d6196f4a
Updating and loading repositories:
Repositories loaded.
Nothing to do.
```

**Comment by abitrolly** [comment]
@mattiaverga no, that doesn't fix the problem. A week passed and there is no update.

```
$ sudo dnf upgrade --refresh --advisory=FEDORA-2023-19d6196f4a
Updating and loading repositories:
 Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                    100% |  79.0 KiB/s |  16.3 KiB |  00m00s
 Fedora - Rawhide - Developmental packages for the next Fedora release                                                            100% |  18.3 KiB/s |  14.3 KiB |  00m01s
 RPM Fusion for Fedora Rawhide - Free                                                                                             100% |  43.8 KiB/s |   6.4 KiB |  00m00s
 Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                    100% | 264.5 KiB/s | 229.0 KiB |  00m01s
 Fedora - Rawhide - Developmental packages for the next Fedora release                                                            100% |   1.2 MiB/s |   1.8 MiB |  00m01s
Repositories loaded.
Nothing to do. 
```

**Comment by mattiaverga** [comment]
What's the output of `sudo dnf list tmt`?

**Comment by abitrolly** [comment]
```
$ sudo dnf list tmt
Updating and loading repositories:
Repositories loaded.
Installed packages
tmt.noarch 1.24.1-2.fc39 rawhide

Available packages
tmt.noarch 1.25.0-1.fc39 rawhide
```

**Comment by abitrolly** [comment]
My expectations from the development page is to explain what happens and why. If the update is being packed into "compose", is it being shipped to main mirror, is it being synced to my mirror?

**Comment by mattiaverga** [comment]
Bodhi cannot know when an update is synced to a specific mirror as it certainly cannot know what mirror a user uses. It only shows the install/upgrade command when an update is pushed to testing/stable, which means it is available in the main mirror.

In this specific case, I think we have a dnf5 bug. The install command used together with `--advisory` crashes. The update command doesn't crash, but maybe doesn't work as expected with dnf5.
I'm going to report to dnf5 team

**Comment by abitrolly** [comment]
> Bodhi cannot know when an update is synced to a specific mirror as it certainly cannot know what mirror a user uses. 

If it can not know, then it should guide user through the process. Because there is no way user can get this info on its own.

> The install command used together with --advisory crashes. 

But Bodhi recommends upgrade command.
