### ISSUE TITLE
@username doesn't work if username contains a hyphen 

### ISSUE THREAD

**Issue by robatino** [fedora-infra/bodhi#5453]
I attempted to reply in Bodhi to user "roman-averin" using the @ sign, but it only recognizes the part of the username before the hyphen. For example, see https://bodhi.fedoraproject.org/updates/FEDORA-2023-ee241dcf80 . I saw no way to make it work so just removed my attempt. If there is a way to do it, it needs to be documented. The link to Fedora-Flavored Markdown says nothing.

**Comment by mattiaverga** [comment]
Hopefully, it just needs to better define the regex at
[MENTION_RE = r'(?<!\S)(@\w+)'](https://github.com/fedora-infra/bodhi/blob/7a2e0685f6ae5ecb4db606f67c16616566853e94/bodhi-server/bodhi/server/__init__.py#L44)
