### ISSUE TITLE
RFE: move a build from unpushed update to another existing update

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/bodhi#5485]
It would be good to have a way to merge updates together when independent people have accidentally submitted them as separate updates when they do need to land together.

The most recent case of this was with [FEDORA-2023-1b4954b53b](https://bodhi.fedoraproject.org/updates/FEDORA-2023-1b4954b53b) and [FEDORA-2023-a8847a9386](https://bodhi.fedoraproject.org/updates/FEDORA-2023-a8847a9386), where the former needed to be merged into the latter because they needed to be shipped together.

Unfortunately, there was no way to do it other than for me to do a no-change rebuild, obsolete the old one manually, and add the new build to the correct update.

This was a waste of human and compute resources that could have simply been avoided by having the ability to merge updates.

(Thankfully, this was only wallpapers, but I shudder if we had this problem with chromium or some other time-consuming package.)

**Comment by kalev** [comment]
Alternatively, having a way to remove all builds attached to an update would also work - that way, we could re-attach the builds to another update. It used to be possible to do that by deleting Bodhi updates, but that functionality was removed a while back.

**Comment by mattiaverga** [comment]
Same as #842 

BTW you don't need to do a no-change rebuild, just unpush the former update, then the build become available to be attached to another update. See #3975

**Comment by Conan-Kudo** [comment]
I tried that, it did not work.

**Comment by kalev** [comment]
@mattiaverga Oh wow, I had no idea that it should work like that - let me give this a try and see if I can merge https://bodhi.fedoraproject.org/updates/FEDORA-2023-b2e6ab4817 into https://bodhi.fedoraproject.org/updates/FEDORA-2023-d422824191

@Conan-Kudo I think you obsoleted the update, but didn't unpush. That may be a crucial difference.

**Comment by Conan-Kudo** [comment]
I did the obsoleting later after I found unpushing didn't work.

**Comment by kalev** [comment]
OK, I tried with my two updates and it didn't work either.

What I did was first, `bodhi updates request FEDORA-2023-b2e6ab4817 unpush` from the command line, and then tried to add vala-0.56.13-1.fc39 from that update to https://bodhi.fedoraproject.org/updates/FEDORA-2023-d422824191 in the web UI.

The web UI errored out with:
```
Builds : Update for vala-0.56.13-1.fc39 already exists
```

I'll just leave them in this state for now if you want to experiment with them in some way.

**Comment by mattiaverga** [comment]
Yeah, the commit I linked refers to create a new update with a build from an unpushed update.
It doesn't permit to edit an existing update with a build from an unpushed update... I'll see if this can be allowed without breaking things.

**Comment by kalev** [comment]
Thanks!
