### ISSUE TITLE
Inconsistent states shown for overrides

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#550]
In the list of my overrides displayed by bodhi:
https://bodhi.fedoraproject.org/overrides/?user=ellert
the following is shown:

Override | Age | Submitter | Status
-------- | --- | --------- | ------
globus-gridftp-server-8.7-1.el5 | 12 days | ellert | Active
globus-gridftp-server-8.7-1.el6 | 12 days | ellert | Active
globus-gridftp-server-8.7-1.el7 | 12 days | ellert | Active
globus-gridftp-server-8.7-1.fc21 | 12 days | ellert | Expired
globus-gridftp-server-8.7-1.fc22 | 12 days | ellert | 	Active
globus-gridftp-server-8.7-1.fc23 | 12 days | ellert | 	Expired

This is inconsistent with the information according to koji:

```
$ koji list-tag-history --package globus-gridftp-server | grep 8.7 | grep override 
Fri Aug 28 16:51:45 2015: globus-gridftp-server-8.7-1.fc23 tagged into f23-override by bodhi
Fri Aug 28 16:52:56 2015: globus-gridftp-server-8.7-1.fc22 tagged into f22-override by bodhi
Fri Aug 28 16:53:43 2015: globus-gridftp-server-8.7-1.fc21 tagged into f21-override by bodhi
Fri Aug 28 16:55:01 2015: globus-gridftp-server-8.7-1.el7 tagged into epel7-override by bodhi [still active]
Fri Aug 28 16:55:47 2015: globus-gridftp-server-8.7-1.el6 tagged into dist-6E-epel-override by bodhi [still active]
Fri Aug 28 16:56:36 2015: globus-gridftp-server-8.7-1.el5 tagged into dist-5E-epel-override by bodhi [still active]
Fri Sep  4 21:45:13 2015: globus-gridftp-server-8.7-1.fc23 untagged from f23-override by bodhi
Wed Sep  9 18:54:36 2015: globus-gridftp-server-8.7-1.fc22 untagged from f22-override by bodhi
Wed Sep  9 21:21:34 2015: globus-gridftp-server-8.7-1.fc21 untagged from f21-override by bodhi
```

Bodhi and koji disagrees on the state of the Fedora 22 override. According the the koji history the untagging was done by bodhi so bodhi should no it was untagged. Yet it is displayed as still active.

**Comment by ellert** [comment]
Since I filed this issue, there are now in the koji list-tag-history three more lines for the untagging of the remaining overrides:
```
Mon Sep 14 20:15:04 2015: globus-gridftp-server-8.7-1.el7 untagged from epel7-override by bodhi
Tue Sep 15 02:22:34 2015: globus-gridftp-server-8.7-1.el5 untagged from dist-5E-epel-override by bodhi
Tue Sep 15 02:22:44 2015: globus-gridftp-server-8.7-1.el6 untagged from dist-6E-epel-override by bodhi
```
but in the bodhi web interface only the EPEL 6 override has changed status from Active to Expired.

One additional override was added by me in the meantime, which has since expired:
```
$ koji list-tag-history --package xrootd | grep 4.2.3 | grep override 
Wed Sep 23 07:00:53 2015: xrootd-4.2.3-1.el6 tagged into dist-6E-epel-override by bodhi
Thu Sep 24 07:02:36 2015: xrootd-4.2.3-1.el6 untagged from dist-6E-epel-override by bodhi
```
However on the bode web interface it is still listed as Active.

**Comment by lmacken** [comment]
I think this issue has been resolved. Please reopen if you still experience this problem.
