### ISSUE TITLE
Drop custom skopeo-light

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#5505]
The `skopeo-light` script was added as a "temporary" solution while required features were being merged in skopeo:
```
Copy containers between registries.

This is a very limited version of the skopeo tool, but with support
for manifests lists and OCI image indexes.
https://github.com/containers/image/pull/400 will make this
unnecessary.

The only subcommand that is supported is 'copy', and the only supported image references
are Docker registry references of the form 'docker://docker-reference'.
```

Recent changes to the Fedora Flatpak builds highlighted that this custom script is no more compatible, meanwhile all features have been made available in the main skopeo package.
I think we can drop the script from our code. @owtaylor any objection/thought?

**Comment by owtaylor** [comment]
Sounds good to me. I think I'd suggest removing the skopeo config options too. Note that -a/--all is needed in the invocation of real skopeo so that all architectures are copied.
