### ISSUE TITLE
Setup custom loggers per masher thread with the koji tag as a prefix

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#555]
Right now it's difficult to differentiate which thread in the masher logs corresponds with which koji tag. We should have them setup a `[tagname]` logging prefix so it's clear which thread each message is from.

**Comment by ralphbean** [comment]
Added this to ansible in this commit:  https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=3256dc011ea55cb4dbb6dd1dc761281b74d78f24
