### ISSUE TITLE
Conflicting masher checkpoints

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#559]
With the recent KDE megaupdate fail, I noticed that after one of the build tags was fixed by hand, resuming the update completely skipped the tagging, even though `tagged` was `False`. Also, `f22-updates` was in the `completed_repos` as well, so it didn't tag or mash anything.
```
u'tagged': False, u'determine_and_perform_tag_actions': True,
```

I think if `tagged` is False, we should always `determine_and_perform_tag_actions`, as well as re-mash the repo. However, this was an edge case to begin with, so there might be a better way to solve it.

**Comment by ralphbean** [comment]
Where does ``tagged`` get set to ``True``?  I see only one reference to it in ``bodhi/consumers/masher.py``.

**Comment by lmacken** [comment]
Ah, looks like it's a legacy argument.

So yeah, I guess in this case either the state should have been edited by hand or a fresh push started.

**Comment by lmacken** [comment]
I'll remove the only reference to `tagged` in the masher now too...

**Comment by lmacken** [comment]
Closing, as we hopefully won't hit this issue again, and if we do we'll need to manually tweak the state if necessary and/or start a fresh push.
