### ISSUE TITLE
When running 'fedpkg update' multiple times in a row, it always asks for a password

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#563]
Hi,

before update to bodhi-2.0, it was always enough to type password only once when running fedpkg update multiple times in a row. Now, it asks for it every time I run it. Is there a particular reason for that or is it a bug?

Thanks
Jan

**Comment by ralphbean** [comment]
Agreed, this bug is annoying!

**Comment by ralphbean** [comment]
This is fixed in git with fedora-infra/python-fedora#146, but we're going to wait to push it out for a week or so until the Beta release of Fedora 23 is out.

**Comment by ingvagabund** [comment]
Thanks, appreciated.

**Comment by ralphbean** [comment]
The [python-fedora-0.6.0 updates](bodhi.fedoraproject.org/updates/python-fedora) are available for testing now.

**Comment by ryanlerch** [comment]
From the comments above, this one appears to have been fixed. so I am going to close it.

Feel free to re-open if it is still an issue.
