### ISSUE TITLE
Should not offer to push to testing on stable update

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#564]
When I visit https://bodhi.fedoraproject.org/updates/FEDORA-2015-15193 I see a "Push to testing" button in the upper right next to edit.  This shouldn't be offered as the update is already pushed to stable.

**Comment by keszybz** [comment]
Another example: https://bodhi.fedoraproject.org/updates/rpm-mpi-hooks-3-2.fc23%2Cmathgl-2.3-10.fc23%2Celpa-2015.05.001-2.fc23%2Cfreefem%2B%2B-3.31-7.3.fc23%2Cnetcdf-4.3.3.1-5.fc23%2CMUMPS-5.0.1-2.fc23%2Cgpaw-0.11.0.13004-15.fc23%2Cga-5.3b-18.fc23%2Cvalgrind-3.10.1-19.fc23%2Cboost-1.58.0-6.fc23%2Cdl_poly-1.9.20140324-14.fc23%2Chpl-2.1-13.fc23%2Cnetgen-mesher-5.3.1-8.fc23%2Cespresso-3.3.0-7.fc23%2Cscotch-6.0.4-5.fc23%2Chdf5-1.8.15-6.patch1.fc23%2Cscalapack-2.0.2-10.fc23%2Cgromacs-5.0.6-6.fc23%2Cscorep-1.4.2-2.fc23%2Csundials-2.6.2-4.fc23%2CRay-2.3.1-11.fc23%2Corsa-0.7.0-33.fc23%2Celk-3.1.12-14.fc23%2Cmpich-3.1.4-5.fc23%2Copenmpi-1.8.8-3.fc23%2Cmpi4py-1.3.1-14.fc23%2Cpypar-2.1.5_108-11.fc23%2Cparaview-4.3.1-11.fc23
