### ISSUE TITLE
fedora-ci.koji-build.rpminspect.static-analysis fails because of mixed SPDX and legacy license identifiers

### ISSUE THREAD

**Issue by wojnilowicz** [fedora-infra/bodhi#5662]
My package at https://bodhi.fedoraproject.org/updates/FEDORA-2024-2dcce24315 failed the test at https://artifacts.dev.testing-farm.io/bca62268-a8ec-4577-a20e-7837b3483bb8/

There are following two comments for each subpackage:
1. Valid License Tag in rust-proc-macro2-diagnostics-0.10.1-1.fc39.src: MIT OR Apache-2.0
2. Mixed SPDX and legacy license identifiers found in rust-proc-macro2-diagnostics-devel-0.10.1-1.fc39.noarch.
Is the second one valid? Looking at current SPDX listing, I see that both MIT and Apache-2.0 are written just as in my package. BTW, it comes so as standard from the rust2rpm tool.

**Comment by mattiaverga** [comment]
For help debugging failed Fedora CI tests (fedora-ci.*), contact the [Fedora CI team](https://matrix.to/#/#fedora-ci:fedoraproject.org). There's nothing to do at bodhi side.
