### ISSUE TITLE
psycopg2.OperationalError unable to connect

### ISSUE THREAD

**Issue by MaxRio87** [fedora-infra/bodhi#5675]
Hi, 

I am experiencing some technical difficulties using bodhi-server package. I tried to configure the application but i apache raise the following error. 

- Iam able to connect to the local postgres database using psql
- Iam using a fresh install of Fedora release 40 (Forty)

Thank you

`[Tue Jun 11 16:46:32.991925 2024] [wsgi:error] [pid 1049:tid 1247] [remote 127.0.0.1:60164] sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "127.0.0.1", port 5432 failed: Permission denied
[Tue Jun 11 16:46:32.991929 2024] [wsgi:error] [pid 1049:tid 1247] [remote 127.0.0.1:60164] \tIs the server running on that host and accepting TCP/IP connections?
[Tue Jun 11 16:46:32.991932 2024] [wsgi:error] [pid 1049:tid 1247] [remote 127.0.0.1:60164] 
[Tue Jun 11 16:46:32.991935 2024] [wsgi:error] [pid 1049:tid 1247] [remote 127.0.0.1:60164] (Background on this error at: https://sqlalche.me/e/20/e3q8)
`

**Comment by mattiaverga** [comment]
Maybe [here](https://fedora-infra.github.io/bodhi/8.0/developer/virtualenv.html#setting-up) there's something that can help, especially:
- run`alembic upgrade head`
- in point 3, "Adjust PostgreSQL Connection Settings"

Also check [Fedora Postgresql guide](https://docs.fedoraproject.org/en-US/quick-docs/postgresql/). Some time ago I had problems setting up pg_hba.conf to make a program able to connect to a local postgresql database (while psql just worked), unfortunately I don't remember how (and if) I was able to fix it...

**Comment by MaxRio87** [comment]
Oh thx a lot ! it was a firewall issue i guess
