### ISSUE TITLE
Cannot create Rawhide side tag update when the package has no %dist tag

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#5725]
I built [fedora-obsolete-packages-41-5](https://koji.fedoraproject.org/koji/buildinfo?buildID=2522581) in a rawhide side tag.

I proceed to create a Bodhi update from that side tag.

Bodhi told me:

![Builds: Can't create update from tag for release 'EL-5' composed by Bodhi.](https://github.com/user-attachments/assets/a92d0aa9-2c5a-4942-82f5-4ed55dccbe6c)

This is incorrect. The build was tagged to f41-build-side-93643 which is a Fedora 41 side tag. Bodhi should not attempt to parse the `-5` release as EL5.

I fixed this by `koji tag f41-updates-candidate fedora-obsolete-packages-41-5` which successfully created a Fedora 41 update: https://bodhi.fedoraproject.org/updates/FEDORA-2024-26e04543f7

**Comment by mattiaverga** [comment]
https://github.com/fedora-infra/bodhi/blob/2510b53ed1d3760e99be49a8beea6ab7f6435978/bodhi-server/bodhi/server/validators.py#L206-L216

This validator has no sense to me.
First of all, in `n, v, r = request.buildinfo[build]['nvr'] ` the `r` refers to the release of the RPM, not the Release which the build refers to. So this, at least, has never worked as planned.

Then, why creating an update from tag should not be allowed for releases composed by Bodhi? Maybe this is a leftover of the time when sidetags were only allowed in Rawhide?
