### ISSUE TITLE
[RFE] searching of builds in a new window

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#573]
Hi,

would it be possible to create a page for searching for builds as it was before? Sometimes I would like to see 40 builds in a row. Or is there an API/bodhi command which I can use to list builds based on a keyword?

Jan

**Comment by ralphbean** [comment]
For now, you can visit this url to get JSON:

https://bodhi.fedoraproject.org/builds/?packages=scala

We could enhance it to get an HTML view as well.

**Comment by ingvagabund** [comment]
Thanks. The form of get arguments is self-explaining.

**Comment by ralphbean** [comment]
Note that, those are just the individual builds.  If you really want updates, you can use this url instead:

https://bodhi.fedoraproject.org/updates/?packages=scala

**Comment by ryanlerch** [comment]
This one seems resolved, so going to close it off. Feel free to re-open if there is something to do here. cheers!
