### ISSUE TITLE
Incorrect newline character in bugzilla comment when build moved to testing

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#578]
When a build is moved to testing, the following comment is send to bugzilla bug. However, there are interpreted \n in it:

``golang-github-stevvooe-resumable-0-0.1.git51ad441.fc22 has been pushed to the Fedora 22 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with \n su -c 'yum --enablerepo=updates-testing update golang-github-stevvooe-resumable'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-16007``

The first is at the end of the second sentence. The second is in the third sentence before command "su -c 'yum...". There could be some missing NL as well.

It should be:

golang-github-stevvooe-resumable-0-0.1.git51ad441.fc22 has been pushed to the Fedora 22 testing repository. If problems still persist, please make note of it in this bug report. If you want to test the update, you can install it with 

su -c 'yum --enablerepo=updates-testing update golang-github-stevvooe-resumable'.

You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-16007

**Comment by ralphbean** [comment]
Thanks @ingvagabund!  This should be fixed in #535, which hasn't yet been pushed to production (due to the beta freeze).
