### ISSUE TITLE
Feedback box in package update package does not get colored after browser refresh 

### ISSUE THREAD

**Issue by danielkza** [fedora-infra/bodhi#587]
Browser: Firefox 40.0.3 on Fedora 22

Selecting a feedback option (positive or negative) on a package update package, and refreshing the browser afterwards keeps the option selected, but the box does not get colored green or red as it does when you manually click it.

**Comment by ryanlerch** [comment]
As of the recentish UI refresh, we no longer use the color of the boxes to highlight karma values.
