### ISSUE TITLE
RFE: List packages in testing

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/bodhi#590]
It would be very helpful to me to be able to pull up a list of my packages that are currently in testing.

**Comment by ralphbean** [comment]
@opoplawski, a url like this should be able to get it for you now:

https://bodhi.fedoraproject.org/updates/?user=orion&status=testing

As far as UI is concerned, on the [user profile page](https://bodhi.fedoraproject.org/users/orion) we could add more links at the top of the updates table next to 'View all' like 'View testing' 'View stable', etc...
