### ISSUE TITLE
Remove `bodhi/client.py` in favour of the similar code in python-fedora

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#592]
We seem to have wound up with two pairs of Bodhi client libraries, one in bodhi itself, one in python-fedora:

https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client.py
https://github.com/fedora-infra/python-fedora/blob/develop/fedora/client/bodhi.py

Talking with @ralphbean it seems that as far as he knows this was never really meant to be the case. I'm thinking that when `bodhi/client.py` was added it was just a very basic Bodhi 2 client, at a time when python-fedora only had a Bodhi 1 client, and then somehow over time, Bodhi 2 functionality got added to the python-fedora `bodhi.py` and Bodhi 1 functionality got added to the bodhi `client.py` and we wound up with the current duplication.

So we think the code in bodhi should be removed (and anything using it should be changed to use the python-fedora one).

**Comment by AdamWill** [comment]
It looks like 1b237fd11655b7156698e56cec00edd8aefef1bd switched the new CLI - `bodhi/cli.py` - to using the python-fedora client instead of the bodhi one. I can't now find anything that uses the bodhi one.

**Comment by pypingou** [comment]
So the file can just be dropped? That's an easyfix :)

**Comment by ralphbean** [comment]
> So the file can just be dropped?

Yeah.  I wanted to see if @lmacken knew of some reason that it should be kept around.

**Comment by lmacken** [comment]
Yep, we don't need it anymore.
