### ISSUE TITLE
New CLI 'download' command actually does the same as 'comment'

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#593]
I suspect what happened here is Luke copy/pasted the `comment` code as a base for the `download` code, then forgot to actually make any changes :)

    @updates.command()
    @click.argument('update')
    @click.argument('text')
    @click.option('--karma', default=0, type=click.INT, help='The karma for this comment (+1/0/-1)')
    @click.option('--user', envvar='USERNAME')
    @click.option('--password', prompt=True, hide_input=True)
    @click.option('--staging', help='Use the staging bodhi instance',
                  is_flag=True, default=False)
    def comment(update, text, karma, user, password, **kwargs):
        client = Bodhi2Client(username=user, password=password, staging=kwargs['staging'])
        print('%r %r %r' % (update, text, karma))
        resp = client.comment(update, text, karma)
        print_resp(resp, client)

    @updates.command()
    @click.argument('update')
    @click.option('--user', envvar='USERNAME')
    @click.option('--password', prompt=True, hide_input=True)
    @click.option('--staging', help='Use the staging bodhi instance',
                  is_flag=True, default=False)
    def download(update, **kwargs):
        client = Bodhi2Client(username=user, password=password, staging=kwargs['staging'])
        print('%r %r %r' % (update, text, karma))
        resp = client.comment(update, text, karma)
        print_resp(resp, client)

obviously the download command should, er, download, not post a comment...

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/bodhi/pull/594 is my attempt to implement this.

**Comment by ralphbean** [comment]
Closed by #594.
