### ISSUE TITLE
auto-obsoleting doesn't work when both are pending

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#599]
I just submitted one update, it had a bug in it, and so I submitted another one right afterwards.  Normally, the second update would obsolete the first, but since the first had never made it to testing (I'm guessing), it didn't get auto-obsoleted.

Now they're both sitting there.  One will move forwards and the other will be stuck in testing forever:

https://bodhi.fedoraproject.org/updates/?packages=fedmsg

**Comment by lmacken** [comment]
Fixed by https://github.com/fedora-infra/bodhi/pull/738
