### ISSUE TITLE
Jammed/Locked Firefox updates (FEDORA-2015-16455, FEDORA-2015-16454)

### ISSUE THREAD

**Issue by stransky** [fedora-infra/bodhi#601]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16455
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16454

Those two updates are locked for a day. They're supposed to be pushed to testing but that still have not happen yet. Please remove those two updates so I can create a new ones.

**Comment by lmacken** [comment]
It looks like this has resolved itself.
