### ISSUE TITLE
Unable to expire or extend override

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#602]
https://bodhi.fedoraproject.org/overrides/hawkey-0.6.1-1.fc23

This was a problem with this override. I've since tagged it manually, but bodhi untagged it completely at some point from -updates-testing as well as -override. I'm guessing it didn't properly mark the BuildrootOverride entity as being expired. So when I try to expire it by hand, it errors out saying it isn't tagged with f23-override.

**Comment by bowlofeggs** [comment]
It has been a long time since this was reported, and I have not observed this problem during my tenure.
