### ISSUE TITLE
the packages cornice service returns way too much information

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#606]
The symptom we see is that the search box is too slow.

The culprit is this API endpoint, which gets queried under the hood:  https://bodhi.fedoraproject.org/packages/?like=firefox

It takes a long time to load.. this could be for many reasons.. but one of them is that there is just way way way too much information returned in the json payload.

**Comment by kalev** [comment]
I've noticed that search seems to be slow when I search for something that is part of megaupdates. https://bodhi.fedoraproject.org/updates/gnome-shell is particularly slow, for example.

**Comment by ralphbean** [comment]
This is fixed now!  :)
