### ISSUE TITLE
traceback in expiring override

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#608]
on a push: 
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: [2015-09-24 22:17:45][     bodhi   ERR
OR] Problem expiring override
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: Traceback (most recent call last):
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: File "/usr/lib/python2.7/site-packages
/bodhi/consumers/masher.py", line 571, in expire_buildroot_overrides
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: build.override.expire()
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: File "/usr/lib/python2.7/site-packages
/bodhi/models/models.py", line 2138, in expire
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: self.build.nvr, strict=True)
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: File "/usr/lib/python2.7/site-packages
/koji/__init__.py", line 1577, in __call__
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: return self.__func(self.__name,args,op
ts)
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: File "/usr/lib/python2.7/site-packages
/koji/__init__.py", line 1939, in _callMethod
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: raise err
Sep 24 22:17:45 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[6481]: TagError: build xrootd-4.2.3-1.el6 not
 in tag dist-6E-epel-override

Perhaps catch this error and ignore it? or warn that the override wasn't right?

**Comment by lmacken** [comment]
Fixed in 68e401734d1d5ad4db06910b0e1f7ac8e2cea75a
