### ISSUE TITLE
Bodhi and koji do not agree on which updates have been pushed

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#610]
Bodhi and koji do not agree on which updates have been pushed. Here are some examples:

According to koji libs3-2.0-0.2.20150902git247ba1b.fc22 is in f22-updates-testing:

```
$ koji list-tag-history --build libs3-2.0-0.2.20150902git247ba1b.fc22
Wed Sep 23 06:39:05 2015: libs3-2.0-0.2.20150902git247ba1b.fc22 tagged into f22-updates-candidate by ellert
Wed Sep 23 07:50:16 2015: libs3-2.0-0.2.20150902git247ba1b.fc22 tagged into f22-updates-testing-pending by bodhi
Thu Sep 24 10:39:20 2015: libs3-2.0-0.2.20150902git247ba1b.fc22 untagged from f22-updates-candidate by bodhi
Thu Sep 24 10:39:20 2015: libs3-2.0-0.2.20150902git247ba1b.fc22 tagged into f22-updates-testing by bodhi [still active]
Thu Sep 24 10:39:30 2015: libs3-2.0-0.2.20150902git247ba1b.fc22 untagged from f22-updates-testing-pending by bodhi
```

However, according to bodhi it is pending with a request to be pushed to testing:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16482

According to koji R-qtl-1.37.11-1.el5 is in dist-5E-epel (i.e. stable):

```
$ koji list-tag-history --build R-qtl-1.37.11-1.el5
Tue Sep  8 11:02:22 2015: R-qtl-1.37.11-1.el5 tagged into dist-5E-epel-testing-candidate by ellert
Thu Sep 10 01:51:46 2015: R-qtl-1.37.11-1.el5 untagged from dist-5E-epel-testing-candidate by bodhi
Thu Sep 10 01:51:46 2015: R-qtl-1.37.11-1.el5 tagged into dist-5E-epel-testing by bodhi
Thu Sep 24 11:55:58 2015: R-qtl-1.37.11-1.el5 untagged from dist-5E-epel-testing by bodhi
Thu Sep 24 11:55:58 2015: R-qtl-1.37.11-1.el5 tagged into dist-5E-epel by bodhi [still active]
```

However, according to bodhi it is in testing with a request to be pushed to stable:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7993

According to koji xrootd-4.2.3-1.el5 is in dist-5E-epel (i.e. stable):

```
$ koji list-tag-history --build xrootd-4.2.3-1.el5
Tue Sep  8 10:32:13 2015: xrootd-4.2.3-1.el5 tagged into dist-5E-epel-testing-candidate by ellert
Thu Sep 10 01:51:47 2015: xrootd-4.2.3-1.el5 untagged from dist-5E-epel-testing-candidate by bodhi
Thu Sep 10 01:51:47 2015: xrootd-4.2.3-1.el5 tagged into dist-5E-epel-testing by bodhi
Thu Sep 24 11:56:00 2015: xrootd-4.2.3-1.el5 untagged from dist-5E-epel-testing by bodhi
Thu Sep 24 11:56:00 2015: xrootd-4.2.3-1.el5 tagged into dist-5E-epel by bodhi [still active]
```

However, according to bodhi it is in testing with a request to be pushed to stable:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7987

See also: https://fedorahosted.org/rel-eng/ticket/6265

**Comment by ellert** [comment]
The first example above - [libs3 F22](https://bodhi.fedoraproject.org/updates/FEDORA-2015-16482) - has cleared itself up. However the time between the timestamps for the push to testing as given by koji and bodhi (Sep 24 08:39:20 2015 - 2015-09-25 22:30:17) is ~38 hours, which is excessive. It is normally a few minutes.

The other two - [R-qtl EPEL5](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7993) and [xrootd EPEL5](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7987) - are still broken. Bodhi did try to push them again and failed with the same error as before: "ejected from the push because Cannot find relevant tag". Bodhi now says these are in testing without a request to be pushed to stable, while koji says they are in stable.

**Comment by ellert** [comment]
I have just received bogus comments from bodhi on these two updates:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7987
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7993

Saying

"This update has reached 28 days in testing and can be pushed to stable now if the maintainer wishes."

As can be seen from koji tag history in the previous comment these were pushed to stable on Sep 24.

**Comment by ellert** [comment]
rel-eng has now fixed the inconsistencies in the states between koji and bodhi.

It is still not clear why the inconsistencies appeared though, so I leave this open.

**Comment by bowlofeggs** [comment]
It has been about 3 years, and during the two years I've worked on Bodhi I don't believe I have observed this problem. Thus, I will close. Feel free to re-open if you believe it is still an issue!
