### ISSUE TITLE
gracefully reject rawhide updates

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#611]
Right now if someone mistakenly tries to submit a rawhide tagged package to bodhi it errors out: 

[waterlan@localhost wcd]$ fedpkg update
/usr/lib/python2.7/site-packages/fedpkg/cli.py:169: DeprecationWarning: 
Commands._hash_file is deprecated and will be removed eventually.
     Please use Commands.lookasidecache.hash_file instead.
   hash = self.cmd._hash_file('bodhi.template', 'sha1')
Creating a new update for  wcd-5.3.0-1.fc24
Password for waterlan:
Creating a new update for  wcd-5.3.0-1.fc24
Traceback (most recent call last):
   File "/usr/bin/bodhi", line 532, in <module>
     main()
   File "/usr/bin/bodhi", line 225, in main
     data = bodhi.save(**update_args)
   File "/usr/lib/python2.7/site-packages/fedora/client/bodhi.py", line 
107, in wrapper
     raise BodhiClientException(problems)
fedora.client.bodhi.BodhiClientException: Invalid tag: wcd-5.3.0-1.fc24 
tagged with [u'f23-updates-candidate', u'epel7-testing-candidate', 
u'dist-6E-epel-testing-candidate', u'dist-5E-epel-testing-candidate', 
u'f22-updates-candidate', u'f21-updates-candidate']
Unable to determine release from build: wcd-5.3.0-1.fc24
Could not generate update request: Command 'bodhi --new --release master 
--file bodhi.template wcd-5.3.0-1.fc24 --username waterlan' returned 
non-zero exit status 1

I have tried the bodhi website, https://bodhi.fedoraproject.org/, but 
there I get a similar message "Unable to determine release from build: 
wcd-5.3.0-1.fc24".

It would be nice to have bodhi say nicely "This is a rawhide package, it should go out in the next daily compose, no need to use bodhi" or something.

**Comment by sagarun** [comment]
Happened to see the same error message. Then realized it was rawhide. A fix would be nice :+1:

**Comment by neteler** [comment]
I also just wasted time before discovering the reason (through this bug report):
Please improve the user notification (e.g. as suggested above). Thanks!

**Comment by sebwoj** [comment]
@bowlofeggs As far as I remember, Bodhi 4.0 will be handling rawhide release.

**Comment by bowlofeggs** [comment]
Yeah - we plan to support Rawhide updates with a future Bodhi release, though likely not 4.0.
