### ISSUE TITLE
Don't get email when karma is added to my updates?

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/bodhi#613]
After switching to bodhi2, it seems that I don't receive any mails when comments or positive / negative karma is added to updates I submitted. Is this because bodhi2 does not implement this yet or some setting is needed?

**Comment by pypingou** [comment]
I believe bodhi2 does not send email anymore but FMN ( https://apps.fedoraproject.org/notifications/ )should be taking care of notifying you.
Maybe check your filters/rules there?

**Comment by mtasaka** [comment]
I don't know what to check. I see "add bodhi events" but I don't want it.
I want to know what changed (what comments are added) to
* the updates I submitted
* the updates I commented or I added some karma
as bodhi 1. Are there any rules for this?

**Comment by mtasaka** [comment]
s/add bodhi events/all bodhi events/

**Comment by lmacken** [comment]
Bodhi still sends emails, and you should receive them when karma is added to your update. I'll have a look at the logs to see what is going on.

**Comment by mtasaka** [comment]
FYI some recent examples related to my updates are
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16591
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16571

**Comment by mtasaka** [comment]
It seems that I can receive emails from the updates I commented, e.g.
https://bodhi.fedoraproject.org/updates/FEDORA-2015-b6b8d93863

But still I don't receive emails from the updates I submitted.

**Comment by ryanlerch** [comment]
@mtasaka are you still experiencing this issue?

**Comment by mtasaka** [comment]
Now I am receiving emails correctly, thank you.
