### ISSUE TITLE
clicking on a package in the search results takes you to the wrong page

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#617]
It takes you to ``/users/PACKAGE``, which obviously doesn't work.

The reason is that we removed the 'builds' from the package JSON, which was the right thing to do -- but the search javascript looks to see if there are builds attached to the json to figure out if it was a package or not.  We need to change that logic at the bottom of search.js.

**Comment by tradej** [comment]
+1. Searching for a package is impossible because of this.

**Comment by Dremor** [comment]
+1, very annoying bug

**Comment by ralphbean** [comment]
Short term workaround until we can get a fix out:

Manually visit the URL:  https://bodhi.fedoraproject.org/updates/PACKAGENAME

**Comment by tradej** [comment]
> Manually visit the URL: https://bodhi.fedoraproject.org/updates/PACKAGENAME

Works, thanks.

**Comment by farhaanbukhsh** [comment]
I want to take a stab on this bug :)

**Comment by sanjayankur31** [comment]
Another workaround to search is to use this URL: https://bodhi.fedoraproject.org/updates/?packages=PACKAGENAME

**Comment by sergiomb2** [comment]
+1 
is just replace /users/ by /updates/ (in url) .

**Comment by ralphbean** [comment]
This was fixed in #635 by @farhaanbukhsh.
