### ISSUE TITLE
pending updates since 3 days

### ISSUE THREAD

**Issue by andrea-manzi** [fedora-infra/bodhi#618]
Hello,
i sent an update on multiple platforms 3 days ago for https://bodhi.fedoraproject.org/updates/?packages=dpm-xrootd, but still 2 platforms are pending ( el5 and f22) 

https://bodhi.fedoraproject.org/updates/FEDORA-2015-ce537ce7e8
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-ac113bd3f9

is there any issue?
thanks
cheers
Andrea

**Comment by lmacken** [comment]
Looks like they all made it to testing. I don't think there is any bodhi bug here, just a lag in the time it takes for humans to sign the packages & kick off the push.

**Comment by andrea-manzi** [comment]
thanks, i will be more patient next time:-)
