### ISSUE TITLE
Duplicate el5 update, ACL errors

### ISSUE THREAD

**Issue by scaronni** [fedora-infra/bodhi#619]
Hello,

I have duplicate updates for an el5 package. I think I retried the update after receiving an error. The first one is stuck in pending/testing and I can not do anything on it, the second one prints "ACL validation mechanism was unable to determine ACLs."

Please delete the first one and push the second one to stable:

First one: FEDORA-EPEL-2015-7884
Second one: FEDORA-EPEL-2015-7886

Thanks & regards,
--Simone

**Comment by bowlofeggs** [comment]
EL 5 went end of life a while ago, so I will close this.
