### ISSUE TITLE
Log a summary instead at the end of the mash

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#620]
Right now it just says "push complete" https://github.com/fedora-infra/bodhi/blob/develop/bodhi/consumers/masher.py#L207

but... it would be cool if it could print out some sort of summary of all the branches it tried, whether they succeeded or failed, and if any updates were ejected for any of those.  Something so that the operator can know if they need to do anything special or not.

**Comment by farhaanbukhsh** [comment]
@ralphbean I would like to look into this :) More hints will be required
