### ISSUE TITLE
required notifications should tell you what is required

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#623]
simo tells me that if you update submit the form under certain conditions, you get a notification back that just says "required".  it means that one of the form fields you submitted is required but empty.. but it doesn't tell you *which* field that is.

It should already be in the JSON data.. we just need to show it via messenger.js

**Comment by simo5** [comment]
As requested, screenshot attached

![bodhi-required-error](https://cloud.githubusercontent.com/assets/8332609/10231671/0d23a8b2-6852-11e5-8300-f3f16920a2c4.png)

**Comment by ralphbean** [comment]
As discussed in IRC, this is because the "updates notes" textarea is blank.

We still need to update the little error popup to indicate that though.
