### ISSUE TITLE
Unhandled exceptions don't tell us anything about themselves

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#624]
We often see in the logs something like:

```
Unhandled exception raised
None
```

which is worthless.  We need to figure out what's hiding the exceptions there and uncover them.

**Comment by ralphbean** [comment]
So, after #680, we will be getting the exception message, but not the traceback.

I'm leaving this open until either:

- we figure out how to get the traceback or..
- we decide that the message is enough and we can close this as is.

**Comment by bowlofeggs** [comment]
I haven't observed this problem before, so I am closing this for now.
