### ISSUE TITLE
Screwy validator messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#630]
I just tried to submit an update for a nvr that never got built.  It failed (correctly) but I got these error messages back:

- Invalid tag: fedmsg-0.16.1-4.fc21 tagged with ``[u'f23-updates-candidate', u'epel7-testing-candidate', u'dist-6E-epel-testing-candidate', u'dist-5E-epel-testing-candidate', u'f22-updates-candidate', u'f21-updates-candidate']``
- Cannot find release associated with build: fedmsg-0.16.1-4.fc21, tags: ``[]``

The first one seems backwards.  It seems to be saying that that nvr **is** tagged with those tags, but the case is actually the opposite.  The nvr **is not** tagged with any of those.  We just need to change the wording.

The second one is also screwy.  Bodhi cannot find a release associated with that build that has "no" tags?  We should just say that we couldn't find any tags associated with that nvr.  That's more clear.

These should be pretty simple to add into ``bodhi/validators.py``.

**Comment by farhaanbukhsh** [comment]
hey @ralphbean  I would like to fix it , how can i reproduce the bug.

**Comment by pypingou** [comment]
@farhaanbukhsh check the first line:
> I just tried to submit an update for a nvr that never got built.

**Comment by TridevGuha** [comment]
There is lots of nvr in  https://github.com/fedora-infra/bodhi/blob/develop/bodhi/validators.py  getting confused on which line to fix. Need some help

**Comment by ralphbean** [comment]
Try grepping for some parts of the error messages.  "Invalid tag" and "Cannot find release".

**Comment by TridevGuha** [comment]
Hey @ralphbean I updated the file bodhi/validators.py for Cannot find release associated with build: fedmsg-0.16.1-4.fc21, tags: [] 
but I am not sure about the Invalid tag. 
What does 'We just need to change the wording' means in the first comment?  Thanks :)

**Comment by rahulbajaj0509** [comment]
hey, @ralphbean i would like to fix this bug.

**Comment by mandaltapesh** [comment]
@rahulbajaj0509 @farhaanbukhsh are you guys going to fix this ? because i am interested in fixing this. just confirming in order to prevent duplicate effort :)
