### ISSUE TITLE
Client shows incorrect link after submitting an update

### ISSUE THREAD

**Issue by scop** [fedora-infra/bodhi#631]
$ rpm -q bodhi-client
bodhi-client-0.9.12.2-3.fc22.noarch

I just submitted this update using "fedpkg update":
https://bodhi.fedoraproject.org/updates/FEDORA-2015-410cd31fc5

The link bodhi-client displayed to me was:
https://bodhi.fedoraproject.org/F23/FEDORA-2015-410cd31fc5

The displayed one is a 404, difference in working/nonworking is "updates" vs "F23".

**Comment by ralphbean** [comment]
Yeah, we need to get a release of the new bodhi client out.

There's a new release of python-fedora that should go with it.

**Comment by ralphbean** [comment]
FYI, that release of python-fedora is out, but we still need to release the new bodhi2 client.

**Comment by ryanlerch** [comment]
Pretty sure this one is resolved now, so going to close it off.

Please re-open if this is still an issue.
