### ISSUE TITLE
Package search triggers user search

### ISSUE THREAD

**Issue by Germano0** [fedora-infra/bodhi#633]
If you use the search field to look for a package, when you select the packagename hint that appears, you will be prompted to an URL that tries to search an user with the same name.
Example:
you write
boinc-client
a boinc-client hint will appear, you click it and you will get a 404 error on URL
https://bodhi.fedoraproject.org/users/boinc-client

**Comment by remicollet** [comment]
Searching for package is hard, same issue.

**Comment by ralphbean** [comment]
Thanks both, but this is a duplicate of #617 with a fix being worked on in #635.
