### ISSUE TITLE
Unfortunate formatting of updates with long package names.

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/bodhi#641]
The following update formats rather oddly: https://bodhi.fedoraproject.org/updates/FEDORA-2015-6b26456127

The icons are shifted down to accommodate the long package names, and then somehow the package names and icons get out of sync; sometimes there are two sets of icons on one line, and sometimes two package names stuck together (as with kwrited and kwin).

Of course, this is somewhat font size dependent.

**Comment by mbooth101** [comment]
I see this too, see my screenshot on #656
