### ISSUE TITLE
no longer receiving 'reached FOO days in testing and can be pushed' comments

### ISSUE THREAD

**Issue by crobinso** [fedora-infra/bodhi#644]
As of this writing, this update has been in testing for over 15 days:

https://bodhi.fedoraproject.org/updates/FEDORA-2015-16368

But it never received the 'reached FOO days in testing and can be pushed' message so I forgot about it. However when I went to the web UI it was pushable.

Intentionally dropped with bodhi2? (doesn't look like it from my brief scan of the code)

**Comment by lmacken** [comment]
I pushed out a new bodhi release yesterday with this fix. https://github.com/fedora-infra/bodhi/pull/639

Let me double check that it's actually working...

**Comment by lmacken** [comment]
Yeah, the `bodhi-approve-testing` cron job runs every 6 hours. https://bodhi.fedoraproject.org/updates/FEDORA-2015-a967da8f7c
