### ISSUE TITLE
revoking the request on a pending update should set the status to revoked

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#645]
it currently removed the request, but it leaves the status as pending (which is super confusing).

**Comment by farhaanbukhsh** [comment]
I would like to work on it. :)

**Comment by farhaanbukhsh** [comment]
can you give me the steps to duplicate this bug please?

**Comment by lmacken** [comment]
So it's not really a bug, just non-obvious resulting behavior from a 'revoke'. So in `models.py` there are a bunch of `UpdateStatus` enumerated types, and I think we'll need a new `revoked` status, which will get set by `Update.set_request`. Then, writing a simple unit test for this should be pretty easy.

**Comment by lmacken** [comment]
This might actually require an alembic db migration script as well?

**Comment by ralphbean** [comment]
Could we re-use the "unpushed" status (like [this one](https://bodhi.fedoraproject.org/updates/FEDORA-2015-15628)) or would you rather go with a new `revoked` status?

If the update has never been pushed to testing, you could say (in a way) that it is "unpushed".  No?

**Comment by lmacken** [comment]
But if an update is `testing` with a `stable` request and you `revoke` it, it doesn't get `unpushed` and is still `testing... Not sure what the best solution is.

**Comment by ralphbean** [comment]
How about:

- If we're pending going to testing and we revoke, set the status to unpushed.
- If we're testing going to stable, and we revoke, keep the status at testing.

Does that cover all the cases?

**Comment by rahulbajaj0509** [comment]
hey, can i work on this bug ?

**Comment by ralphbean** [comment]
Please.  Whoever fixes it first gets :cake:!

**Comment by farhaanbukhsh** [comment]
@ralphbean i want to :) just tell me how to replicate the bug

**Comment by ralphbean** [comment]
The best way is probably to try and write a test case for it that *fails* in ``bodhi/tests/functional/test_updates.py``.

Try to get the test suite running first with ``nosetests``.

**Comment by farhaanbukhsh** [comment]
@rahulbajaj0509  seems to be a new contributor who wants to get started in case he isn't willing to take it up I will do it :) , thanks a ton @ralphbean

**Comment by ralphbean** [comment]
(You two can work on it together, too... ;p)  @rahulbajaj0509, we often talk development in the ``#fedora-apps`` channel on the freenode IRC network if you'd like to join us there.

**Comment by farhaanbukhsh** [comment]
@ralphbean That will be amazing :) i would love to :)

**Comment by raveit65** [comment]
> How about:
>
>    If we're pending going to testing and we revoke, set the status to unpushed.
>    If we're testing going to stable, and we revoke, keep the status at testing.

and the result is that an obsolete update can't removed from updates-testing, see 
https://github.com/fedora-infra/bodhi/issues/693

**Comment by TridevGuha** [comment]
is this issue #645 open to work with?
