### ISSUE TITLE
Edit page should have [Save] button not [Edit] at bottom

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#646]
When editing an update the "save" button at the bottom of the page saves [Edit] not [Save].
This confusing - please change button label to [Save] (or "Submit changes").

**Comment by farhaanbukhsh** [comment]
I am taking a stab at it !!

**Comment by ralphbean** [comment]
Fixed by #648.

**Comment by juhp** [comment]
Thanks!
