### ISSUE TITLE
when creating new update don't suggest NVRs already in Bodhi

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#647]
When one creates a update for a particular package in Bodhi,
the web ui suggests NVRs for all builds not yet pushed to stable.
It should only suggest NVRs that have not yet been submitted to Bodhi.

**Comment by ralphbean** [comment]
Thinking through this... we may not want to do this.  It warrants discussion.

My question:  Is it possible/desirable to submit a multi-build update that contains a NVR that is also in another multi-build update?

**Comment by juhp** [comment]
Any examples?  To the better of my knowledge this is not supported by Bodhi/Fedora workflow: ie one can never have the same NVR in more than one Update.

**Comment by mbooth101** [comment]
I kind of agree with @juhp , why bother showing them if bodhi will just tell you "Update for NVR already exists" when you select it?

(Why lead the user down a path they can't go down?)

**Comment by ralphbean** [comment]
@lmacken, any comment on this one?

**Comment by mattiaverga** [comment]
To my knowledge, this is fixed in the current new update form.
