### ISSUE TITLE
Put the update builds in the <title>

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#649]
Having the `Update.title` in the `<title>` would make things easier when you have a lot of bodhi tabs open.

**Comment by ralphbean** [comment]
Agreed!  :+1:

**Comment by farhaanbukhsh** [comment]
I would like to work on it.

**Comment by farhaanbukhsh** [comment]
I tried looking into it , so since every page is inherting master.html so I ma thinking that titie has to be here, i tried to put  `${update.tiltle}` in title tag to check but its throwing error am i on the right track? @ralphbean
