### ISSUE TITLE
Prune out feedback from bodhi on the user profile

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#652]
Here's an idea.

The bottom half of a user's profile looks like this:

![feedback-received](https://cloud.githubusercontent.com/assets/331338/10431216/f4ba6878-70d1-11e5-9443-f9dd619f0b65.png)

The info on the left includes comments left on my updates by both *real users* and by the system bodhi user.  Those comments from bodhi are useful when looking at the page for a particular update, but they can be kind of spammy on the user profile page.  Can we remove them, and list only comments from people *other* than the bodhi user?

**Comment by pypingou** [comment]
This ticket is still formulated as a question. The pull-request linked above is a proposed implementation of a solution to address this ticket, but if we decide to keep these comments, then we can close the PR w/o merging it.
