### ISSUE TITLE
Release the new bodhi2-client

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#654]
* [ ] Add support for editing updates
* [ ] Add `--testable` and `--candidates` support (already implemented in python-fedora)
* [x] Update man page
* [ ] Create a wiki page with instructions on how to use it
* [x] Patch `fedpkg update` to work with the new syntax. Last time I checked it was only a matter of changing `--new` to `new`.
* [x] Push it out to users, either by patching the current bodhi-client package, or we could do a new bodhi2-client that obsoletes it, but  it would require going through the new package process.

**Comment by bowlofeggs** [comment]
I'm currently working on the man page, but this task is closely related to #142 so I might as well take care of both together.

**Comment by bowlofeggs** [comment]
Bodhi 2.2.0-1 has been released on Rawhide https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PIUKJNNXYEKC6QD6SZOT6UIHVXBFHDID/

I will file tickets to track each of the three remaining todo checkboxes in the description, since they could each be done separately.

**Comment by bowlofeggs** [comment]
I've created these three tickets to track the remaining work from the body of this ticket:

#937
#938
#939
