### ISSUE TITLE
Layout issues on updates with long build names

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#656]
See the following screenshot of update https://bodhi.fedoraproject.org/updates/FEDORA-2015-23cdf0f240

This is on Fedora 23, with Firefox 41.0.1-2.fc23.x86_64

![Screenshot](https://fedorapeople.org/~mbooth/bodhi_update_mess.png)

**Comment by mbooth101** [comment]
Oh I guess this is a duplicate of #641

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/bodhi/pull/682
