### ISSUE TITLE
Cannot create update for perl-MooX-Log-Any fc23

### ISSUE THREAD

**Issue by moto-timo** [fedora-infra/bodhi#658]
Error messages:
`Unable to determine release from build: perl-MooX-Log-Any-0.004002-1.fc23`

`Invalid tag: perl-MooX-Log-Any-0.004002-1.fc23 tagged with [u'f23-updates-candidate', u'epel7-testing-candidate', u'dist-6E-epel-testing-candidate', u'dist-5E-epel-testing-candidate', u'f22-updates-candidate', u'f21-updates-candidate']`

Yet, there is a fc23 build:

```
$ koji latest-pkg f23 perl-MooX-Log-Any
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
perl-MooX-Log-Any-0.004002-1.fc23         f23                   ttorling
```

Reference BZ#[1242726](https://bugzilla.redhat.com/show_bug.cgi?id=1242726)

**Comment by bowlofeggs** [comment]
This was because the package was already tagged into ```f23```, and therefore did not need an update.
