### ISSUE TITLE
Allow disabling event popups in web UI

### ISSUE THREAD

**Issue by bgilbert** [fedora-infra/bodhi#660]
While I'm trying to perform a task via the web UI, Bodhi keeps showing pop-up notifications saying that someone has done something with some random update.  This is distracting and also completely pointless, since those events are not actionable or even relevant to me.  Can we have a way to turn this off?

![popups](https://cloud.githubusercontent.com/assets/361374/10567778/03b75e4a-75db-11e5-88a5-da9fbc90a3e5.png)

**Comment by ralphbean** [comment]
Can do!
