### ISSUE TITLE
Create New Update: repeated search for the same package leads to duplication clutter

### ISSUE THREAD

**Issue by jnpkrn** [fedora-infra/bodhi#664]
... both  Candidate Builds and Related Bugs frames are affected.

Possible solution: remove anything added through association with the currently used input, only then reflect the data from the new query.  Provided that each query is processed anew, these queries are time sensitive, so that the new and old data for the same input can differ.

**Comment by ralphbean** [comment]
> Possible solution: remove anything added through association with the currently used input, only then reflect the data from the new query. Provided that each query is processed anew, these queries are time sensitive, so that the new and old data for the same input can differ.

Interesting idea.

Do you think it would be sufficient to remove all unchecked checkboxes before adding more from the most recent query?  We don't have so rich a data model on the client side as would be required to do what you describe.

**Comment by jnpkrn** [comment]
Sure, anything that won't make users making multi-package updates angry should work :)

**Comment by jnpkrn** [comment]
I'm back after some time :)

Now, I've accidentally noticed that unchecked items are being
automatically removed, presumably per the previous discussion.

It would be nice, however, to have "reload" buttons next
to each of Builds and Bugs box captions that would display
original query results per currently selected packages.
At least for the first time, that would IMHO be more intuitive
way to recover after "oops, actually wanted to have this item
present and checked... where have you gone?".

**Comment by bowlofeggs** [comment]
I believe this was fixed by https://github.com/fedora-infra/bodhi/commit/c77d62f160b4aa6a66395c28c5817a2847f69c68 so this should be fixed by the upcoming 2.3.0 release. Thanks for the report!
