### ISSUE TITLE
Create "New Update" mentions "phpMyAdmin" but not "phpMyAdmin4"

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/bodhi#672]
When loading https://bodhi.fedoraproject.org/updates/new to create "New Update" the "dropdown" called "Packages" mentions "phpMyAdmin" but not "phpMyAdmin4" - while phpMyAdmin4 is an active package for EPEL 5. Entering the package name manually leads to a search error (not found).

**Comment by ralphbean** [comment]
This is due to the search index from [fedora-packages](https://apps.fedoraproject.org/packages) being out of date.  We're working actively on a rewrite which should be out in the next month or so.

**Comment by ryanlerch** [comment]
Pretty sure this one is fixed in fedora-packages, so closing this one off. Feel free to reopen if this is still an issue.
