### ISSUE TITLE
Unable to expire override for eclipse-launchbar package

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#678]
Please see this override:

https://bodhi.fedoraproject.org/overrides/eclipse-launchbar-1.0.0-0.3.git01bfa62.fc22

Hitting "expire" button results in error message: "Invalid build. It must be tagged....."

This build was used for bootstrapping, so a newer version of eclipse-launchbar is already tagged into F22 stable.

**Comment by bowlofeggs** [comment]
I'm not sure there is enough info here to identify the issue at this point, and I doubt we have logs from 2.5 years ago (and if they do exist, they would likely not be useful now since Bodhi has changed a great deal since then). I'm closing, but please do reopen if you have trouble again.
