### ISSUE TITLE
Search "some" package not possible.

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#692]
From the search input box, enter "php-pear"

There are >100 packages starting with php-pear, and the main "php-pear" is not is the 4 proposed entries.

I think the package matching exactly the input text should always be proposed first (for other, just have to enter more text)

**Comment by remicollet** [comment]
Not only a php issue ;)
Try to search "python" or "perl"..

**Comment by oishommau** [comment]
it's also not possible to find selinux-policy-targeted

this bug may be related to https://github.com/fedora-infra/bodhi/issues/870

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
