### ISSUE TITLE
can't unpushed a update from updates-testing f23

### ISSUE THREAD

**Issue by raveit65** [fedora-infra/bodhi#693]
see https://bodhi.fedoraproject.org/updates/FEDORA-2015-ad1384765d
This update is obsolete since several days by marco-1.10.3-1.fc23, but i can't unpushed or delete the update.
In bodhi-1 it was possible to delete a update.
Why is this function removed?

**Comment by lmacken** [comment]
Hmm, you should be able to unpush this update, so I think that's a bug. We removed the ability to delete updates after many releng members complained about it removing the audit-trail.

**Comment by raveit65** [comment]
Maybe this is a sideeffect that this update was hanging around  more than 3 -4 days in pending state.
I submited marco-1.10.3-1.fc23 when marco-1.10.2-2.fc23 was in pending state.
When marco-1.10.2-2.fc23 was pushed to updates-testing, marco-1.10.3-1.fc23 was also pushed.
Then marco-1.10.3-1.fc23 reached stable karma but i could not unpush the obsolete update anymore.
Sorry, i have to much packages and everything should work like a machine, i can't wait if a package won't push from pending to testing or stable, for what reason ever.
That updates are in pendinding state for more than 1 or 2 days should be improved.
I have updates that needs about 12-13 days before they landed in stable.
** offtopic end**
The question is how/who can unpushed this update?

**Comment by lmacken** [comment]
I just unpushed `marco-1.10.2-2.fc23`. For some reason the `pushed` flag on that update was `False`, which was preventing the `Unpush` button from showing up.

**Comment by bowlofeggs** [comment]
It doesn't sound like there is any further action to take on this issue. Please reopen if you disagree.

**Comment by raveit65** [comment]
> Please reopen if you disagree.

f23 is EOL since a log time. Why generating spam-mails? Silent closing bugs is sufficient......
