### ISSUE TITLE
Update has been pushed to stable but it is not available on mirrors

### ISSUE THREAD

**Issue by nforro** [fedora-infra/bodhi#694]
Update [vim-go-1.1-1.fc21](https://bodhi.fedoraproject.org/updates/FEDORA-2015-12305) is marked as stable but it is not available on any mirror. Update for [F22](https://bodhi.fedoraproject.org/updates/FEDORA-2015-12244) is fine.

**Comment by lmacken** [comment]
It looks fine from a bodhi/koji tag perspective...

```
~ ➤ koji latest-pkg f21-updates vim-go                                          
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
vim-go-1.1-1.fc21                         f21-updates           nforro
```

**Comment by nforro** [comment]
Yes, but rpm is not on dl.fedoraproject.org or any mirrors: http://dl.fedoraproject.org/pub/fedora/linux/updates/21/x86_64/v/vim-go-1.1-1.fc21.noarch.rpm
Only the update is mentioned in updateinfo.xml.

**Comment by bowlofeggs** [comment]
Since this was reported 2.5 years ago, I don't believe there is server side logging left to aid in debugging this. Furthermore, Bodhi has changed a great deal since then, so even if we had the logs it may not be useful. I'm going to close this, but feel free to reopen if you see this again.
