### ISSUE TITLE
unpushed updates are displayed as pending nowhere

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#695]
This update has been unpushed:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-4a5b0b71c7
but it is displayed as `pending` (pending where?).

![bodhi](https://cloud.githubusercontent.com/assets/755451/10934013/380fde42-82dd-11e5-9d31-ee1b02d528ea.png)

Koji tags say it's not pending:

```
$ koji list-tag-history --build plymouth-0.8.9-8.2013.08.14.fc21
Fri Oct 30 19:18:16 2015: plymouth-0.8.9-8.2013.08.14.fc21 tagged into f21-updates-candidate by rstrode [still active]
Mon Nov  2 15:36:51 2015: plymouth-0.8.9-8.2013.08.14.fc21 tagged into f21-updates-testing-pending by bodhi
Mon Nov  2 15:58:32 2015: plymouth-0.8.9-8.2013.08.14.fc21 untagged from f21-updates-testing-pending by bodhi
```

I believe the `Status` should say `unpushed` (or `canceled` or something like that) instead. Also, there should be a comment from `bodhi` user and say something similar. There is a comment that it has been submitted, so there should be another comment that it has been unsubmitted.

Thanks.

**Comment by bowlofeggs** [comment]
I think this works properly these days. Please feel free to reopen if you disagree.
