### ISSUE TITLE
Unable to find any packages that match the current query

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#696]
On the New update form, using the Packages input.

Ex: php-tecnickcom-tc-lib-color

Of course, this package exists, but is quite recent.
Probably related to package sync being broken for a while (also missing on https://apps.fedoraproject.org/packages/)

**Comment by bowlofeggs** [comment]
That form actually queries https://apps.fedoraproject.org/packages/, so if that app doesn't know about a package than neither will Bodhi. I suggest reporting the issue there if you see it again.
