### ISSUE TITLE
Missing bugzilla comments about created updates

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#698]
When creating a set of new updates by selecting builds from more than one release, bodhi files comments in the associated bugzilla bug that the updates have been created. But not for all of them. There is always one that does not get a comment in bugzilla. Some recent examples:

nordugrid-arc-nagios-plugins-1.8.4-3:
- F22 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-b7c733e12f) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274493#c5)
- F23 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-e03be1e8b0) no comment
- EPEL5 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7d2142aa41) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274493#c6)
- EPEL7 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7600fcdec0) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274493#c7)
- EPEL6 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-f8d24e72ba) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274493#c8)

nordugrid-arc-gangliarc-1.0.0-2:
- EPEL6 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-1d8f08342b) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274690#c3)
- EPEL7 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-0091579952) no comment
- F23 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-37a556f5a6) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274690#c4)
- F22 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-17b4a7f2e6) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274690#c5)
- EPEL5 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-b7f714a161) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1274690#c6)

myproxy-6.1.15-2:
- EPEL6 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-7a79236ad7) no comment
- EPEL7 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-fd2fb0355c) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1272520#c3)
- F21 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-91efe6bbae) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1272520#c4)
- F23 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-1d5c0ccdce) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1272520#c5)
- EPEL5 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-40ef4e3c14) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1272520#c6)
- F22 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-2d4b6bd9bb) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1272520#c7)

nordugrid-arc-5.0.3-1, nordugrid-arc-doc-2.0.4-1:
- EPEL5 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-caa747664e) no comment
- F23 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-8938bb4295) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1265662#c1)
- EPEL7 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-3302f719eb) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1265662#c2)
- EPEL6 [update](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-db093b0da7) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1265662#c3)
- F22 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-3794289bc0) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1265662#c4)
- F21 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2015-77fdc860f7) [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1265662#c5)

**Comment by bowlofeggs** [comment]
Does this still happen? I've not observed this problem before. I'm going to close it, but feel free to reopen if you think it is still an issue.
