### ISSUE TITLE
Editing an update causes untagging from overrides as a side effect.

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#699]
Consider the following update:

https://bodhi.fedoraproject.org/updates/FEDORA-2015-e8f5adfc26

At 2015-11-04 05:13:48 there is a comment
https://bodhi.fedoraproject.org/updates/FEDORA-2015-e8f5adfc26#comment-347533
saying that the one of the builds in the update was replaced:
dpm-dsi-1.9.5-10.fc23 → dpm-dsi-1.9.5-11.fc23

Looking at the tagging history of the other two builds in this update at this time, we see:

Wed Nov  4 05:13:42 2015: globus-common-16.0-1.fc23 untagged from f23-updates-testing by bodhi
Wed Nov  4 05:13:42 2015: globus-common-16.0-1.fc23 untagged from f23-override by bodhi
Wed Nov  4 05:13:48 2015: globus-common-16.0-1.fc23 tagged into f23-updates-candidate by bodhi
Wed Nov  4 05:13:51 2015: globus-common-16.0-1.fc23 tagged into f23-updates-testing-pending by bodhi

Wed Nov  4 05:13:44 2015: globus-gridftp-server-9.0-2.fc23 untagged from f23-updates-testing by bodhi
Wed Nov  4 05:13:44 2015: globus-gridftp-server-9.0-2.fc23 untagged from f23-override by bodhi
Wed Nov  4 05:13:50 2015: globus-gridftp-server-9.0-2.fc23 tagged into f23-updates-candidate by bodhi
Wed Nov  4 05:13:51 2015: globus-gridftp-server-9.0-2.fc23 tagged into f23-updates-testing-pending by bodhi

So the builds were unpushed from testing (untagged from f23-updates-testing and tagged into f23-updates-candidate) and then a repush was requested again (tagged into f23-updates-testing-pending). Which was what was supposed to happen.

But, in addition the builds were untagged from f23-override which was not supposed to happen.

This untagging from f23-override in koji as a side effect of editing the update, did not result in bodhi expiring the overrides in the list of overrides in the bodhi web interface. According to the bodhi web interface the overrides were still active.

Changing the expiration date of the override in the web interface did not reactivate the override in koji. In order to reactivate the override I had to first press the expire button for the override in the web interface (which didn't change any tags in koji) and then resubmit it.

**Comment by kalev** [comment]
I noticed the same issue, but in my case the builds got untagged from a koji side repo, f23-gnome when editing a large multi-package update.
