### ISSUE TITLE
Anonymous commenting fails silently

### ISSUE THREAD

**Issue by Lyude** [fedora-infra/bodhi#704]
When trying to comment on a bodhi page when not logged in, posting any comments silently fails. Clicking the "Add Comment" button makes it look like it's about to post something, but then stops a couple seconds later and stops functioning. The only indicator of failure is a message in Firefox's debug console that says:

`15:00:49.230 TypeError: data.responseJSON is undefined1 forms.js:70:5`

The version of Firefox I'm using is 42.0-2.fc23

**Comment by bowlofeggs** [comment]
I am unable to reproduce this problem. Since it's been 2.5 years, it seems likely someone fixed it along the way. Feel free to reopen if you experience it again!
