### ISSUE TITLE
Bodhi doesn't see new packages/updates

### ISSUE THREAD

**Issue by dfateyev** [fedora-infra/bodhi#707]
I prepared updates for newly added package 'perl-Crypt-Salsa20' two days ago. Since that still can't push its updates, a notification in search box says that package 'perl-Crypt-Salsa20' doesn't exist.

**Comment by ralphbean** [comment]
@dfateyev can you give us a little more info?  Which search box on which page?  A screenshot would help resolve my confusion about it.

**Comment by dfateyev** [comment]
Sure thing, here is it:

![update00](https://cloud.githubusercontent.com/assets/727201/11338174/b978f380-921c-11e5-98ac-e1ecbacd79a3.png)

The package itself: http://pkgs.fedoraproject.org/cgit/perl-Crypt-Salsa20.git

**Comment by ralphbean** [comment]
Thanks!  This is a failure over at this app https://apps.fedoraproject.org/packages/s/perl-Crypt-Salsa20

It was recently [reworked](http://threebean.org/blog/history-of-fedora-packages/) to be better up-to-date, but there are apparently bugs in there.  ;)

**Comment by dfateyev** [comment]
Yet another package affected: https://admin.fedoraproject.org/pkgdb/package/perl-Crypt-ScryptKDF/

**Comment by ralphbean** [comment]
Yup, there's a permissions issue.  Still being worked on.  Thanks for the update!

**Comment by lmacken** [comment]
@ralphbean has this been resolved?

**Comment by ralphbean** [comment]
I haven't gotten an error email from packages03.phx2 in the last two or three days.. and that was the problem.  I *think* I finally got it but I'll probably need to give the index another rebuild to call it really really done.

Wait to close this until https://apps.fedoraproject.org/packages/s/perl-Crypt-Salsa20 is in place.

**Comment by dfateyev** [comment]
Yet another package: https://admin.fedoraproject.org/pkgdb/package/rpms/perl-DBIx-QueryLog/

**Comment by dfateyev** [comment]
Looks like fixed now, thanks.
