### ISSUE TITLE
RFE: link to bugs mentioned in comments

### ISSUE THREAD

**Issue by tyll** [fedora-infra/bodhi#708]
In the comment

https://bodhi.fedoraproject.org/updates/FEDORA-2015-5c8ff15dc9

the submitter uses `bug 1276971`. It would be nice if bodhi would create  a link to bugzilla from this, to make it possible to direclty click on it.

**Comment by dhgutteridge** [comment]
That is already possible, if the user understands how to apply the Markdown to the comment. In your example, if they'd typed it as RH#1276971 or RHBZ#1276971 or Fedora#1276971, the link would've been derived automatically. It also supports references to third-party bug reporting tools using the same method (e.g. KDE is another prefix that can be used), so without adding that context, it'd run the risk of linking to the wrong bug. (That is, I'm not a developer of Bodhi, just a user, but if I were supporting this application, I wouldn't automatically assume a given bug number applies to Red Hat's Bugzilla specifically.)

**Comment by ryanlerch** [comment]
This is supported as @dhgutteridge explained above. It is also explained in the pop-up that is shown if you click on the "Fedora Flavored Markdown" link below the description field when creating and update or submitting a comment.
