### ISSUE TITLE
Karma for testcase is not properly calculated

### ISSUE THREAD

**Issue by tyll** [fedora-infra/bodhi#709]
The test case overview at

https://bodhi.fedoraproject.org/updates/FEDORA-2015-5c8ff15dc9

does not show the negative karma for the intel multihead test case. Also the negative karma for the testcase does not seem to count as negative overall karma. This might be related to this.

**Comment by bowlofeggs** [comment]
I believe this issue may have been fixed 1-2 years ago. Let me know if you think it's still broken.
