### ISSUE TITLE
Adding Candidate Builds not working

### ISSUE THREAD

**Issue by vpodzime** [fedora-infra/bodhi#712]
I want to add builds to https://bodhi.fedoraproject.org/updates/libblockdev-1.3-2.fc23/edit (actually, I want to replace the old build with a new one -- libblockdev-1.3-4). Clicking the + button does nothing.

**Comment by lmacken** [comment]
The `+` button adds whatever build is in the text field to the left of to the list of potential candidates.
I just typed `libblockdev-1.3-4.fc23` in the text field and hit the `+` button, and it worked as expected.

The `-4` has been added to the update. https://bodhi.fedoraproject.org/updates/FEDORA-2015-63a08d4771

**Comment by vpodzime** [comment]
I'm sorry, but I still have hard times recognizing that the space next to the ``+`` button is a text field. This is how it looks like on my Firefox running on Fedora 23:

![candidatebuilds_ff_f23](https://cloud.githubusercontent.com/assets/1044278/11417580/7f021dfa-9418-11e5-9536-c05e3cb6f8f8.png)

Maybe a frame around the text field would help a lot?
