### ISSUE TITLE
Selecting the correct icon to leave feedback is not easy

### ISSUE THREAD

**Issue by nmav** [fedora-infra/bodhi#715]
I tried to leave feedback (for example in: https://bodhi.fedoraproject.org/updates/FEDORA-2015-a721916bcc ), but it was not apparent to me which button I should click for positive and negative. The circles are quite small and the tick is not easily distinguishable from the x (for me eyes at least). Having red/green colors would help.

**Comment by ryanlerch** [comment]
This has now changed in the UI refresh. There is now coloured tags with +1 and -1 in where there used to be a grey tick and grey cross.
