### ISSUE TITLE
When a package is update but change the bug type from bugfix to security, bodhi does not obsolete the previous one

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/bodhi#724]
Hello
Something wrong it is happening look at https://bodhi.fedoraproject.org/updates/?packages=p7zip

p7zip-15.09-3.fc23 now says that is security when it isn't .
p7zip-15.09-4.fc23 doesn't obsolete p7zip-15.09-3.fc23 

Anyway let's wait for pushes , to see if situation gets better .

Thanks.

**Comment by sergiomb2** [comment]
bodhi publish both package clearly a bug , bodhi when I change the type of the package doesn't obsolete the package with same name 

p7zip-15.09-3.fc23 is bugfix type 
p7zip-15.09-4.fc23 is security type

**Comment by sergiomb2** [comment]
bodhi have to obsolete p7zip-15.09-3.fc23 is bugfix type  !

**Comment by lmacken** [comment]
The auto-obsoletion code doesn't care about the update `type`. I think this issue is due to the fact that `-3` was `locked` and actively being pushed to `testing` when `-4` was submitted, thus bodhi did not obsolete it.

**Comment by lmacken** [comment]
Actually, it doesn't obsolete updates that have an open `request`, which `-3` had. Now that we have proper locking, we can now obsolete updates with an open request that hasn't been pushed yet.

**Comment by sergiomb2** [comment]
Cool thanks.
