### ISSUE TITLE
Karma is calculated wrong after editing an update

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#727]
When I edit an update, its karma gets reset to 0. So far so good.

But if one of the people who had previously given karma comments on the update afterwards, their karma isn't taken into account any more. It should be.

**Comment by lmacken** [comment]
Hmm, I though I fixed this bug already. Do you have an example of this that I could look into?

**Comment by kalev** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-2e33c48936 , it's quite long and winding, but if you count the +1 karma votes after latest edit, it should add up to 3, but bodhi only shows 2. Looks like pwalter's karma wasn't counted.

**Comment by kalev** [comment]
I remember you guys had trouble deploying a big bodhi update about the same time as I was battling the GNOME 3.18.2 megaupdate that I linked above. I think this bodhi update may have had all the fixes accumulated during the F23 final freeze. If the fix was included there, then please disregard this ticket :)

**Comment by lmacken** [comment]
Yep, this was resolved with bodhi 2.1.3, which I released on 11/24. 

https://lists.fedoraproject.org/archives/list/infrastructure%40lists.fedoraproject.org/message/WJLJGYQYGA5FZJ353GFNNSWLIK5VGWUO/
https://github.com/fedora-infra/bodhi/pull/670
