### ISSUE TITLE
Show user's page after login

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#729]
I've noticed that I pretty much always tend to go to https://bodhi.fedoraproject.org/users/kalev after logging in. It would be great if this happened automatically after login instead of showing the front page as is now; would save a few clicks.

**Comment by rathann** [comment]
This was a default action in the old bodhi IIRC. I'd like to see this implemented as well.

**Comment by ryanlerch** [comment]
#3500 (now in the develop branch) implements a new dashboard view for logged in users, displaying your pending+testing updates, and active overrides. This is what appears now as the homepage.

**Comment by kalev** [comment]
Excellent, thanks!
