### ISSUE TITLE
Change to bugzilla updates text for quicker testing feedback

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#740]
Forwarded from https://fedorahosted.org/bodhi/ticket/791

Based on the fedora-devel discussion ("Bodhi front page after login"):

What about scrapping the existing bugzilla message, and instead posting the direct link to koji to download the package (as soon as the package is signed):

"""To test the update now run:

dnf upgrade ​https://koji.fp.o/update-yyyy/path-to.rpm ​https://koji.fp.o/update-yyyy/path-to-another.

rpm ​https://koji.fp.o/update-yyyy/path-to-yet-another.rpm

After that go to ​https://bodhi.fp.o/update-yyyy/ to leave karma. """

dnf will skip packages that are not already installed with 'upgrade'. Since this would be only run manually, and the dependent packages would be downloaded from mirrors, this shouldn't cause too much load on koji servers. The advantage would be that the message would be actionable and feedback from the bug reporters would be as fast as possible.

**Comment by ryanlerch** [comment]
@nirik any idea what the original message to change was/is?

**Comment by nirik** [comment]
See for example: https://bugzilla.redhat.com/show_bug.cgi?id=1463975#c2

```
python-fedimg-0.7.2-1.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-7128106ce2
```
So, Id say change the middle line to something like: 

Use 'dnf update https://kojipkgs.fedoraproject.org/packages/python-fedimg/0.7.2/1.fc24/data/signed/81b46521/noarch/python-fedimg-0.7.2-1.fc24.noarch.rpm' to install this package to test. See https://fedoraproject.org/wiki/QA:Updates_Testing for
further information on how to install test updates.
