### ISSUE TITLE
Bodhi sends emails without subject lines

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/bodhi#741]
Bodhi sometimes sends emails concerning feedback and state changes of an update without supplying a subject line. My suspicion is that this occurs because the list of packages is too long, though that's just a guess. An example would be: https://bodhi.fedoraproject.org/updates/FEDORA-2015-0dfca110b6.

**Comment by dhgutteridge** [comment]
It seems this has been fixed? (E.g. https://bodhi.fedoraproject.org/updates/FEDORA-2016-58fb569ef8 generated emails with subject lines truncated to 256 characters.)

**Comment by lmacken** [comment]
Hmm, the code in production hasn't changed in a while, so I'm not quite sure...

**Comment by dhgutteridge** [comment]
I was wrong, it hasn't been fixed. It works inconsistently; sometimes long lists of packages are truncated to 256 characters in the subject line, and other times an empty subject line is sent.

https://bodhi.fedoraproject.org/updates/FEDORA-2016-541d258919 sent "[Fedora Update] [comment] bluedevil-5.6.5-1.fc23 breeze-gtk-5.6.5-2.fc23 grub2-breeze-theme-5.6.5-1.fc23 kactivitymanagerd-5.6.5-1.fc23 kde-cli-tools-5.6.5-1.fc23 kde-gtk-config-5.6.5-1.fc23 kdecoration-5.6.5-1.fc23 kdeplasma-addons-5.6.5-1.fc23 kgamma..." as the subject line (as did the equivalent testing update for Fedora 24), while https://bodhi.fedoraproject.org/updates/FEDORA-2016-26531afadf sent an empty subject line. So there's something more nuanced happening.

**Comment by ryanlerch** [comment]
Pretty sure this one is fixed now. We have code on the bodhi side of things (#1561) that shortens email subjects, so this should not happen any more. Feel free to reopen if you are still experiencing this issue (especially the empty subject lines)
