### ISSUE TITLE
[RFE] Display time to stable

### ISSUE THREAD

**Issue by frozencemetery** [fedora-infra/bodhi#745]
It would be great if, in addition to displaying time at which an update was submitted to testing, the time remaining until the update can be pushed to stable were displayed.  Thanks!

**Comment by trishnaguha** [comment]
@lmacken @ralphbean I would like to work on it. :)

**Comment by trishnaguha** [comment]
@lmacken @ralphbean This can be closed by #779 ?
Thanks :)

**Comment by lmacken** [comment]
Yep, thanks @trishnaguha!
