### ISSUE TITLE
bodhi doesn't leave tags in a usable manner by itself on error/eviction 

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#746]
I'm not really 100% sure why but it seems to get into knots. I can't see why in the logs something has been untagged / ejected from the build but it ends up failing and the logs are really detailed enough to see why. I wonder if it's possibly around karma and promotion between testing and stable. It appears some landed in testing, but some didn't appear to even be signed so not sure they ever made it. 

https://bodhi.fedoraproject.org/updates/FEDORA-2015-7b01e524aa

koji list-history --build powerdevil-5.5.0-3.fc22
Mon Dec 14 19:29:50 2015 powerdevil-5.5.0-3.fc22 tagged into f22-kde by rdieter [still active]
Mon Dec 14 19:32:00 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-candidate by rdieter
Mon Dec 14 19:34:26 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-testing-pending by bodhi
Tue Dec 15 09:39:16 2015 powerdevil-5.5.0-3.fc22 untagged from f22-updates-candidate by bodhi
Tue Dec 15 09:39:16 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-testing by bodhi
Wed Dec 16 01:29:43 2015 powerdevil-5.5.0-3.fc22 untagged from f22-updates-testing-pending by bodhi
Fri Dec 18 15:51:29 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-pending by bodhi [still active]
Fri Dec 18 22:26:01 2015 powerdevil-5.5.0-3.fc22 untagged from f22-updates-testing by bodhi
Fri Dec 18 22:26:01 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-candidate by bodhi
Sat Dec 19 18:41:01 2015 powerdevil-5.5.0-3.fc22 untagged from f22-updates-candidate by bodhi
Sat Dec 19 18:41:01 2015 powerdevil-5.5.0-3.fc22 tagged into f22-updates-testing by bodhi [still active]

Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: [2015-12-20 01:56:09][    fedmsg   ERROR]f22-updates-testing Exception in MasherThread(f22-updates-testing)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: Traceback (most recent call last):
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/consumers/masher.py", line 321, in work
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: self.determine_and_perform_tag_actions()
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/consumers/masher.py", line 59, in wrapper
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: retval = method(self, *args, **kwargs)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/consumers/masher.py", line 534, in determine_and_perform_tag_actions
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: self._determine_tag_actions()
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/consumers/masher.py", line 562, in _determine_tag_actions
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: self.eject_from_mash(update, reason)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/consumers/masher.py", line 453, in eject_from_mash
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: koji=self.koji)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/bodhi/models/models.py", line 1153, in remove_tag
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: koji.untagBuild(tag, build.nvr, force=True)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1582, in __call__
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: return self.__func(self.__name,args,opts)
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1949, in _callMethod
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: raise err
Dec 20 01:56:09 bodhi-backend01.phx2.fedoraproject.org fedmsg-hub[13627]: TagError: build powerdevil-5.5.0-3.fc22 not in tag f22-updates-testing-pending

**Comment by nullr0ute** [comment]
For reference to get this push to complete I re-tagged all the NVRs listed in the resume into f22-updates-testing-pending, signed all NVRs in the tag and then resumed the push. bodhi went through and evicted a bunch of updates but has continued on

**Comment by dkryzhevich** [comment]
Here is something similar: https://bodhi.fedoraproject.org/updates/FEDORA-2015-6ec19b0161

**Comment by lmacken** [comment]
This issue was due to a bug that would tag the same build twice, which would cause lead to a failure on the second attempt, which would kill the push leaving updates tagged properly, but not in the correct bodhi state. I fixed this in https://github.com/fedora-infra/bodhi/commit/d6300ae907bbc02b2a2033a2ce72dac05b811d61

@dkryzhevich that update is actually different, since the maintainer manually untagged the build from updates-testing...
