### ISSUE TITLE
issue with tagging doesn't allow update to go to updates-testing even though it appears it has

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#747]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-4b73839bb1

http://koji.fedoraproject.org/koji/buildinfo?buildID=705327

$ koji list-history --build=libsoc-0.7.1-1.fc22
Mon Dec 14 08:17:02 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-candidate by pbrobinson
Mon Dec 14 08:23:54 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing-pending by bodhi
Tue Dec 15 09:40:49 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-candidate by bodhi
Tue Dec 15 09:40:49 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing by bodhi
Wed Dec 16 01:30:15 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-testing-pending by bodhi
Thu Dec 17 02:54:18 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing-pending by bodhi
Fri Dec 18 10:03:21 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-testing-pending by bodhi
Fri Dec 18 22:23:43 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-testing by bodhi
Fri Dec 18 22:23:43 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-candidate by bodhi
Sat Dec 19 18:43:03 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-candidate by bodhi
Sat Dec 19 18:43:03 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing by bodhi [still active]
Sun Dec 20 02:24:35 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing-pending by pbrobinson
Sun Dec 20 02:32:40 2015 libsoc-0.7.1-1.fc22 untagged from f22-updates-testing-pending by bodhi
Sun Dec 20 03:52:38 2015 libsoc-0.7.1-1.fc22 tagged into f22-updates-testing-pending by bodhi [still active]

**Comment by lmacken** [comment]
Fixed in https://github.com/fedora-infra/bodhi/commit/d6300ae907bbc02b2a2033a2ce72dac05b811d61
