### ISSUE TITLE
should allow double spacing for comments

### ISSUE THREAD

**Issue by peullid** [fedora-infra/bodhi#748]
If the user adds any double spacing (double line breaks, resulting in an empty line separating two sections of text), bodhi strips the double spacing from the displayed comment. The stripping makes the text less readable and more confusing in cases where the user clearly intended to separate two or more thoughts.

**Comment by ryanlerch** [comment]
When leaving comments, adding a double space like this into the markdown field (now) correctly renders as two seperate paragraphs in the output.

**Comment by peullid** [comment]
@ryanlerch 

it seems that either the problem was bigger or the solution has created a new problem ...

take the following input:
> line one
> line two
> 
> line three

bodhi changes the above to:
> `<p>line one line two</p>`
> `<p>line three</p>`

which renders roughly as:
> line one line two
> 
> line three

should this issue be re-opened, or should I create a new issue?

**Comment by bowlofeggs** [comment]
@peullid I reported https://github.com/fedora-infra/bodhi/issues/1747 for you. Thanks!
