### ISSUE TITLE
shouldn't require e-mail address (only suggest)

### ISSUE THREAD

**Issue by troiwhaox** [fedora-infra/bodhi#754]
bodhi shouldn't force anonymous users to enter an e-mail address. i just enter fake e-mails to get around this. forcing the user to enter an e-mail address encourages some to input invalid info, which doesn't help anyone. if an anonymous user doesn't input an e-mail address and clicks submit, it would be better if a message came up suggesting that they fill-in an e-mail, but allowing them override and post without one if they so choose.

**Comment by bowlofeggs** [comment]
I'm planning to drop anonymous comments in https://github.com/fedora-infra/bodhi/issues/2700.

**Comment by sebwoj** [comment]
@bowlofeggs Can we close it?

**Comment by bowlofeggs** [comment]
Anonymous comments are dropped in Bodhi 4.0.0.

**Comment by troiwhaox** [comment]
goodbye, bodhi :-/
