### ISSUE TITLE
add a link to https://apps.fedoraproject.org/packages/*

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/bodhi#755]
Hi there,

almost every time a see a package that I don't know about, I have to go to https://apps.fedoraproject.org/packages/ to understand if i'm able to test or not.

Can you please add one link in the main pages/list ? 

Example : 
global package page : https://bodhi.fedoraproject.org/updates/?packages=kanatest
detailed build page : https://bodhi.fedoraproject.org/updates/kanatest-0.4.8-16.fc23

**Comment by ralphbean** [comment]
Oh!  We should have that link already with the little 'fedmenu' button on the bottom right.. but for some reason its missing.  Maybe it got commented out?  We should bring that back.

**Comment by ralphbean** [comment]
Oh, I see.  It is there on the single update page, but not in the updates list.  We can likely add it there when ``packages=kanatest`` is in the url.

**Comment by Jibec** [comment]
Thank you for your work, it's better :)

But : fedmenu is quitte hidden in the far end of the screen, I would suggest to add a little icon next to "build" line on a single page.
