### ISSUE TITLE
 bodhi allows packages to be downgraded in stable releases 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/bodhi#760]
I think here is right place to report this [1]
Same thing just happened with bzip2 - the packager submitted an older version for stable and it downgraded a newer version. The version in stable is now -18.

https://bodhi.fedoraproject.org/updates/FEDORA-2015-4a9c774398 (bzip2-1.0.6-18.fc23)
https://bodhi.fedoraproject.org/updates/FEDORA-2015-be3a6f6ed8 (bzip2-1.0.6-19.fc23)

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1292914#c5

**Comment by lmacken** [comment]
This will be fixed by https://github.com/fedora-infra/bodhi/pull/768

With this patch, `-18` would have gotten obsoleted as soon as `-19` hit the stable repos.

**Comment by lmacken** [comment]
This also would get caught by https://github.com/fedora-infra/bodhi/pull/769
