### ISSUE TITLE
bodhi obsoletes existing "pending stable" updates when submitting a newer package for testing

### ISSUE THREAD

**Issue by rathann** [fedora-infra/bodhi#763]
Specifically, I had two packages in updates testing which I submitted for stable:
mozilla-noscript-2.9-1.fc23
mozilla-noscript-2.9-1.fc22

When I submitted a new set of packages for testing:
mozilla-noscript-2.9.0.2-1.fc23
mozilla-noscript-2.9.0.2-1.fc22
the previous ones got obsoleted and the new updates inherited their changelogs and bugs.

**Comment by richardfearn** [comment]
Thanks @lmacken for fixing that so quickly! And thanks @rathann for filing the bug!
