### ISSUE TITLE
Port the job to clean up old repos

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#765]
Bodhi1 had a job in `jobs.py` that would clean up old stale mashes. We should port this logic over and have it keep the last 10 mashes around.

**Comment by bowlofeggs** [comment]
This appears to be the old job in question:

https://github.com/fedora-infra/bodhi/blob/1.0/bodhi/jobs.py#L38-L71

**Comment by ankit01ojha** [comment]
I want to take it can you please assist me.

**Comment by bowlofeggs** [comment]
@ankit01ojha We'll need to port the code in my most recent comment to work with Bodhi 2. Probably you can add a new module in `bodhi.server.scripts` that does the work (see other scripts there for example), configure `setup.py` to turn the script into an executable in `/usr/bin`, and then we can just call it with cron (and that part would be done in Ansible later, so you wouldn't need to worry about it here). I hope that helps!

**Comment by ankit01ojha** [comment]
Can you please elaborate it.

**Comment by bowlofeggs** [comment]
I don't think I know more than I've said about this issue, as I am not familiar with Bodhi 1. But perhaps we shouldn't have put the easy fix label on this one if it's not clear what needs to be done. I'll just remove that label. I apologize if this was confusing!

**Comment by bowlofeggs** [comment]
The mashes are in `/mnt/koji/mash/updates` which may (should?) be referenced by a setting. Inside there, there are folders named like `f25-updates-161103.1814`.
