### ISSUE TITLE
It should be possible to manually push an update with karma 1

### ISSUE THREAD

**Issue by kkofler** [fedora-infra/bodhi#772]
Since the minimum value for auto-karma is 1, it would be only logical to be also allowed to manually push updates which have a karma of +1.

In Bodhi 1, this was at least possible with the following workaround:
* edit the update
* enable auto-karma
* set the stable threshold to 1
* confirm the edit
* now hit the "push to stable" button

and then it worked (whereas just hitting "push to stable" without the workaround would complain that the update does not satisfy the criteria).

Now in Bodhi 2, even this workaround does not work anymore. I see no way to trigger the push. (There is no "Push to stable" button shown, neither without nor with the workaround.) It is entirely illogical that we allow updates to go stable with a karma of +1 if it was set to do so automatically with no verification, but not if the packager verified that the feedback is OK. That punishes the packager for wanting to ensure the quality of his/her package, and ultimately hurts the user (because either they will have to wait longer for a verified update, or the packagers will just enable autokarma and then bad updates can end up pushed because no human looked at the feedback, especially at the threshold +1).

Please allow manual pushes at karma +1 for consistency with the minimum auto-karma threshold.

**Comment by kkofler** [comment]
Case in point: https://bodhi.fedoraproject.org/updates/FEDORA-2016-afa165bd29

**Comment by kkofler** [comment]
To elaborate on why I think this should be allowed:

Case A:
* The update is submitted.
* Auto-karma is enabled at the threshold +1.
* A tester gives 1 karma.
* The update is automatically pushed to stable.

Case B:
* The update is submitted.
* Auto-karma is not enabled.
* A tester gives 1 karma.
* The update has exactly the same amount of testing as in case A. Yet, Bodhi will not allow me to push this update to stable. Why?

Case C (the Bodhi 1 workaround, that also no longer works):
* The update is submitted.
* Auto-karma is not enabled.
* A tester gives 1 karma.
* The update is edited, auto-karma is now enabled at the threshold +1.
* The update is now in exactly the same state as in case A. Yet, Bodhi neither automatically pushes the update to stable, nor allows me to push it manually. Why?

**Comment by bowlofeggs** [comment]
I believe that @trishnaguha fixed this in #821.

**Comment by kkofler** [comment]
Bodhi 2.2.2 is now deployed and this still doesn't work. Please reopen this issue!

The stablekarma is (still) not saved if the autokarma checkbox is not checked. And for some reason, you decided to not allow the manual pushes if autokarma is enabled (which doesn't make sense – if the autokarma didn't trigger for some reason, e.g., because it was only enabled after the karma was already reached, you want to allow manual pushes, so the `and not update.autokarma` condition needs to go away, in the line I've just posted a review comment for).

I don't understand why this was not simply implemented the much simpler way I suggested, which is totally equivalent policy-wise (because the karma threshold is settable): instead of checking that the update's karma is ≥ the stablekarma (which is maintainer-settable and ≥ the minimum allowed stable karma), just directly check that the update's karma is ≥ the minimum allowed stable karma for that update type (usually 1, 2 for critpath) and eliminate the useless setting. That would have avoided the issue we're now having.

**Comment by kkofler** [comment]
In case you didn't understand my suggestion:
Why check that a ≥ some user settable x ≥ b when you can just check that a ≥ b?
(∃ x: a ≥ x ≥ b) ⇔ (a ≥ b)

**Comment by kkofler** [comment]
The update that I'm trying to push:
https://bodhi.fedoraproject.org/updates/ksensors-0.7.3-34.fc24
No matter what I do, I can't push it to stable, despite it having karma +1. If I keep autokarma disabled and set stablekarma to 1, it ignores the setting. If I enable autokarma, it doesn't show "Push to stable" due to the `not update.autokarma` conditional.

**Comment by trishnaguha** [comment]
If you look at the issue #796 the plan was to show `Push to stable` when `autokarma` is disabled. Enabling `autokarma` is for `Autopush` which means it wouldn't show `Push to stable` when `autokarma` is enabled.

**Comment by kkofler** [comment]
In case this wasn't clear, the main issue is this one:

> The stablekarma is (still) not saved if the autokarma checkbox is not checked.

Therefore, it is impossible to meet the conditions of the code you added.

Another, probably related, bug that I am seeing now is that my new updates get filed with autokarma enabled even though I explicitly unchecked it! I have to go and edit them to turn autokarma off.

**Comment by trishnaguha** [comment]
@kkofler Can you reopen the issue if you think it still exists?

**Comment by kkofler** [comment]
No, GitHub doesn't let me do it, only a project admin can reopen issues in GitHub.

**Comment by trishnaguha** [comment]
@bowlofeggs ping.

**Comment by kkofler** [comment]
Ping? Any progress on this? Shall I file a new bug so that it doesn't get forgotten?

**Comment by kkofler** [comment]
Actually, I went ahead and filed issue #1033.
