### ISSUE TITLE
Editing an update VR is kinda awkward

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#774]
The Bodhi 2 editing UI makes just changing the version-release of a build for an update kinda awkward, unless I'm missing something. Say I want to replace `foo-1.0-1.fc23` with `foo-1.0-2.fc23`; there doesn't seem to be any way to just edit the NVR and replace `1` with `2`, I have to awkwardly copy the NVR of the existing build (by dragging in from the right to avoid triggering the hyperlink), paste it into the text entry box, drop the extra space that's created by the awkward copy/paste, change the 1 to a 2, click the +, then uncheck the entry for the old NVR. Whew. That's...not so convenient.

**Comment by ryanlerch** [comment]
The new update form is now in develop, and makes it a lot easier to add/remove/update builds.

#3453
