### ISSUE TITLE
Cannot request stable - 'failing to determine ACLs'

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#775]
For this update:  https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-50448945cd

Something is screwy when I try to request stable.  Not sure what.  Perhaps we should sync prod data to stg and then try adding some debugging around it over there.

**Comment by lmacken** [comment]
Hm, yeah when I try to push it to stable I get:

```
ACL validation mechanism was unable to determine ACLs.
```

**Comment by lmacken** [comment]
I synced the prod db to stg, and then manually queued this one up for stable. We'll have to do further testing to figure out the root of the problem.

**Comment by lmacken** [comment]
Logs from `bodhi02.stg`
```
[bodhi][MainThread] validate_acls was passed data with nothing to validate.
[bodhi][MainThread] validating request
```

**Comment by lmacken** [comment]
This is because you somehow managed to create 2 updates for the same build 5 seconds apart from each other.

https://bodhi.stg.fedoraproject.org/updates/FEDORA-EPEL-2016-50448945cd
https://bodhi.stg.fedoraproject.org/updates/FEDORA-EPEL-2016-184f2c8947

**Comment by ralphbean** [comment]
Amazing.  :P
