### ISSUE TITLE
Update IDs in comments should be automatically linkified

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#776]
For example, when mentioning another update in a comment:

https://bodhi.fedoraproject.org/updates/eclipse-remote-2.0.1-1.fc23#comment-386091

It should be automatically turned into a link, in much the same way bugzilla does with bug numbers.

**Comment by pypingou** [comment]
If that can help, pagure has a few customization in its markdow processor: https://pagure.io/pagure/blob/master/f/pagure/pfmarkdown.py
