### ISSUE TITLE
Bodhi triggered e-mails from bugzilla sometimes have the wrong date.

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#778]
E.g. the email sent for this comment:

https://bugzilla.redhat.com/show_bug.cgi?id=1305887#c2

which on the bugzilla page is timestamped "2016-02-17 17:30:45 EST", has a e-mail header saying:

Date: Tue, 9 Feb 2016 14:00:30 +0000 (2016-02-09 15:00:30)

The Received headers locks more reasonable:
```
Received: from bugweb-03.app.bz.hst.phx2.redhat.com (bugweb-03.app.bz.hst.phx2.redhat.com [10.5.117.33])  by mx1-phx2.redhat.com (8.14.4/8.14.4) with ESMTP id u1HFN0Sp042290     (version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384 bits=256 verify=NO)       for <mattias.ellert@fysast.uu.se>; Wed, 17 Feb 2016 10:23:01 -0500
Received: from bugweb-03.app.bz.hst.phx2.redhat.com (localhost [127.0.0.1])       by bugweb-03.app.bz.hst.phx2.redhat.com (8.14.4/8.14.4) with ESMTP id u1HFN0JY031493    for <mattias.ellert@fysast.uu.se>; Wed, 17 Feb 2016 10:23:00 -0500
Received: (from apache@localhost) by bugweb-03.app.bz.hst.phx2.redhat.com (8.14.4/8.14.4/Submit) id u1HFN0tc031480;       Wed, 17 Feb 2016 10:23:00 -0500
```
The bad date header corresponds to the original creation time of the bugzilla ticket.

**Comment by ralphbean** [comment]
This is a bug for bugzilla.redhat.com itself, no?

**Comment by ellert** [comment]
I was not sure if I should report this to Bodhi or Bugzilla, so I chose one. But thinking about it you are probably right this is more of a Bugzilla issue. I have reported it there too now:

https://bugzilla.redhat.com/show_bug.cgi?id=1310038

**Comment by ralphbean** [comment]
Thank you, as always, @ellert.  :)
