### ISSUE TITLE
Duplicate test cases when viewing an update

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/bodhi#780]
See this one for example: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-79ebb637bd

It says "Test Cases (4)", but then it lists 6.

And as it turns out, there really are only 4, but two of them are just duplicated, which also happens in the form to submit karma, people are asked to say twice whether "Test Case clone distgit repository" passed. :confused:

**Comment by bochecha** [comment]
And for some more weirdness: https://bodhi.fedoraproject.org/updates/FEDORA-2016-4c1187ae1d

As you can see, in his comment plautrba gives a +1 to each test case.

But then the points are collated so they are given to the original of each test case, not to the clones. :smile: 

And so even though only 2 people gave some points to the test cases, some of them get up to +3.

**Comment by maitreyaverma** [comment]
@bochecha can I do it as my first bug

**Comment by trishnaguha** [comment]
@maitreyaverma yeah ofcourse!

**Comment by maitreyaverma** [comment]
I am very enthusiastic to do it. Can you tell me how can I start?

**Comment by bochecha** [comment]
@maitreyaverma You don't need to ask anybody's permission to work on something. Certainly not mine, as I'm just the bug reporter here, I haven't worked on Bodhi for a long time.

In any case, the way to get started on this one is the same as the way to get started on any other projects:
1. set up a development environment (see the `README.rst` file)
2. try to reproduce the bug (this is very important, because if you can't reproduce it you'll never know if you have fixed it)
3. find the problem in the source code and fix it
4. add some automatic tests so that the bug never comes back

**Comment by bowlofeggs** [comment]
This was fixed in https://github.com/fedora-infra/bodhi/pull/1584
