### ISSUE TITLE
Documentation is missing entirely

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/bodhi#781]
The documentation in docs/ is two years old and empty, and the documentation on https://infrastructure.fedoraproject.org/infra/docs/bodhi.rst is still from Bodhi1.

So either there is no documentation, or I am unable to find the documentation.
Either one needs to be fixed ASAP for a service this critical to Fedora's release pipeline.

At least some overview of how all the pieces work together and operational SOPs need to be documented.

**Comment by puiterwijk** [comment]
This has been discussed in #326 and #259 as well, but should really be fixed soon.
I don't care what framework you use for it, as long as there's at least basic SOPs and architectual overview in the Infra repo.

**Comment by lmacken** [comment]
I updated the SOP last week :)

**Comment by puiterwijk** [comment]
Note that there's still not something like an architecture overview describing which box does what.
Given the high complexity, that would be very useful to have or be linked to.
