### ISSUE TITLE
manually push holland to stable

### ISSUE THREAD

**Issue by carlwgeorge** [fedora-infra/bodhi#785]
I'm filing an issue here based on the advice I received in `#fedora-devel`.

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-0b5dd66ba7

When I created this update, I accidentally left auto-karma enabled.  I ended up reaching the karma threshold last Friday.  I didn't want to push out the update over the weekend, just in case.  I clicked unpush, which deleted the stable request, but it also reset the time in testing.  The update has been in testing for over two weeks total and has +3 karma.  I would like to push it to stable now, but I don't have a push button.

Can anyone help me manually push this update to stable?

**Comment by rapgro** [comment]
I have one active update ¹ in bodhi but without any buttons. What can I do with that? Maybe bodhi needs an intelligent garbage collector.

¹ https://bodhi.fedoraproject.org/updates/FEDORA-2016-52e09c8358

**Comment by lmacken** [comment]
I queued up the `holland-1.0.12-3.el6` update for stable and obsoleted the single `lxqt-common` one.

**Comment by rapgro** [comment]
Thanks!

**Comment by carlwgeorge** [comment]
Thank you much.
