### ISSUE TITLE
bugzilla serialization issues

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#795]
When someone submits an update for several branches with the same bug(s) attached, bodhi spins off threads to update the bugs and tries to update the same bug at the same time. 

From bz maintainers: "We have recently discovered that fedora bot is causing serialization errors by updating a bug in parallel. e.g. if a package is updated for F22 and F23, it adds both comments at the same time in different threads. I hope you can direct this concern to the bot maintainers so this problem can be resolved."

I also have error output from this error, but it seems the cause is pretty clear.

**Comment by ralphbean** [comment]
This will hopefully be fixed by https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=23a18cc784263644a5247abbad00b5f3656537c2

**Comment by lmacken** [comment]
Yep, I think that'll do the trick. Thanks @ralphbean!

**Comment by lmacken** [comment]
The last BZ serialization error occured on `2016-03-04 15:09:47`, the day @ralphbean deployed the fix. Looks like we're good to go. Thanks!
