### ISSUE TITLE
Some buildroot overrides were unexpected untagged

### ISSUE THREAD

**Issue by mbooth101** [fedora-infra/bodhi#798]
My buildroot overrides for "eclipse-emf" and "eclipse-ecf" were untagged in koji after the updates were pushed to testing.

However, the overrides in bodhi were still "active" (they had not yet reached the expiry date)

I had to manually expire and re-submit these overrides to get them re-tagged in koji

Please don't untag buildroot overrides until the corresponding update has made it to stable or the expiry date has been reached.

**Comment by mbooth101** [comment]
How do increase the visibility of this issue? It happens all the time. When you add new builds to an update, the override tags disappear from koji.

The override is still active in bodhi, so I have to expire and then un-expire each one. It's a massive ball-ache for a dozen or more packages because you can only edit one override at a time.

**Comment by juhp** [comment]
Yeah +1, annoying and confusing.

**Comment by juhp** [comment]
@puiterwijk it is pretty easy to reproduce: any build that gets tagged into updates-testing by Bodhi gets untagged from overrides in Koji.

A few recent examples for me: ghc-boxes-0.1.4-4.fc25, ghc-rpm-macros-1.6.9-3.fc25, and ghc-rpm-macros-1.6.9-2.fc25.
