### ISSUE TITLE
use different color for '0' in test cases section

### ISSUE THREAD

**Issue by matthiasclasen** [fedora-infra/bodhi#799]
A page like https://bodhi.fedoraproject.org/updates/FEDORA-2016-606ca05253 more or less screams 'all green'. But if you get close enough, most of the test results are '0'. It would be less misleading to use blue or white as background for values that don't indicate a succeeded test.

**Comment by userimack** [comment]
I am working on it.

**Comment by akshayharidas** [comment]
Hi ,I am new to Fedroa. Can someone assign me to this bug?

**Comment by lmacken** [comment]
@akshayharidas Absolutely, feel free to dive in! Please let me know if you need any help getting started.

**Comment by akshayharidas** [comment]
Hi
So happy see your message .I am stated working on the bug, I cloned in my
pc and am stucked in the running time . It shows 'waiterss' distribution
was not found an pkg_resources. I  searched for the solution . Presently am
not done with that error . Hope  you can help me . Thank you :)
On 10-May-2016 1:07 AM, "Luke Macken" notifications@github.com wrote:

@akshayharidas https://github.com/akshayharidas Absolutely, feel free to
dive in! Please let me know if you need any help getting started.

**Comment by akshayharidas** [comment]
I am getting "raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'waitress' distribution was not found and is required by the application"  these kinds of  errors 
I don't know what to do! 
![screenshot from 2016-06-05 13-26-51](https://cloud.githubusercontent.com/assets/16167718/15885303/f4b0e050-2d73-11e6-90f4-474208c31bbc.png)

**Comment by trishnaguha** [comment]
@akshayharidas `setup.py` already has `waitress`. Check here https://github.com/fedora-infra/bodhi/blob/develop/setup.py#L24
Have you followed the instructions given on `readme` properly? 
You need to run `python setup.py develop` in virtualenv as given in readme.

https://github.com/fedora-infra/bodhi#setting-up after bootstrapping the virtualenv https://github.com/fedora-infra/bodhi#bootstrap-the-virtualenv

**Comment by akshayharidas** [comment]
@trishnaguha 
>Have you followed the instructions given on readme properly? 

yes, I followed the instructions in https://github.com/fedora-infra/bodhi .

>You need to run python setup.py develop in virtualenv as given in readme.

https://github.com/fedora-infra/bodhi#setting-up after bootstrapping the virtualenv https://github.com/fedora-infra/bodhi#bootstrap-the-virtualenv

after running i got outputs like this.
![screenshot from 2016-06-09 11-28-46](https://cloud.githubusercontent.com/assets/16167718/15921498/850f6024-2e3f-11e6-9173-178899040c13.png)

**Comment by akshayharidas** [comment]
@lmacken @trishnaguha 
when entered the commad -  xzcat bodhi2.dump.xz | sudo -u postgres psql bodhi2
 i got error role "bodhi2" does not exist!
i didn't get any solution
![screenshot from 2016-06-11 17-57-55](https://cloud.githubusercontent.com/assets/16167718/15985046/66bad822-2ffe-11e6-962a-def4197c7232.png)

**Comment by pnemade** [comment]
Are you on Fedora 24?  I observed the same. But when last time I deployed bodhi on Fedora 23 it was successful.

**Comment by trishnaguha** [comment]
@akshayharidas Have you executed the command `sudo -u postgres createdb bodhi2`?
Also note you should have PostgreSQL server running https://github.com/fedora-infra/bodhi#setup-the-postgresql-server.

**Comment by akshayharidas** [comment]
@trishnaguha  yes
![screenshot from 2016-06-11 18-23-16](https://cloud.githubusercontent.com/assets/16167718/15985140/99be1d26-3001-11e6-95c0-55264d25b5da.png)

**Comment by trishnaguha** [comment]
@akshayharidas Make sure you edit pg_hba.conf as **privileged user** as shown here https://github.com/fedora-infra/bodhi#3-adjust-postgresql-connection-settings and start postgresql server after that with `sudo systemctl start postgresql.service`.

**Comment by bowlofeggs** [comment]
@akshayharidas Another way to get quickly up and running with Bodhi development is to use the Vagrantfile. I've got an open pull request that makes it fully functional here, so I recommend using the one from my commit:

https://pagure.io/fedora-apps-vagrantfiles/pull-request/1

You can see instructions at https://pagure.io/fedora-apps-vagrantfiles/blob/master/f/bodhi/README.md

I hope that's helpful!

**Comment by mbtamuli** [comment]
@akshayharidas Are you still working on this?
I am interested in fixing this, asking just to confirm in order to prevent redundant effort.

**Comment by mbtamuli** [comment]
@lmacken Can I send a pull request to this issue?

**Comment by trishnaguha** [comment]
@mbtamuli If you are done with the patch feel free to send in a PR :).

**Comment by abhishekcs10** [comment]
How can i get started with this issue? Please help :)

**Comment by trishnaguha** [comment]
@abhishekcs10 You can start by setting up the development environment of bodhi on your machine. You should have an instance of bodhi running on your local machine.
https://github.com/fedora-infra/bodhi#bodhi-v20-development-environment

Either Start from here https://github.com/fedora-infra/bodhi#virtualenv

or you can use vagrantfile for setting up the development environment as @bowlofeggs said earlier.
https://pagure.io/fedora-apps-vagrantfiles/blob/master/f/bodhi/README.md

After you are done with that you can dive in to the issue directly.

**Comment by abhishekcs10** [comment]
In fedora 24 the solution to database problem is
sudo -u postgres -i    //login to postgres
psql -s bodhi2    //use database bodhi2
create user bodhi2 password 'somepassword';     //this creates user and role with name bodhi2 
GRANT ALL PRIVILEGES ON DATABASE bodhi2 TO postgres;

Then run xzcat bodhi2.dump.xz | sudo -u postgres psql bodhi2 command

**Comment by abhishekcs10** [comment]
While using vagrant up command i got following error

Bringing machine 'default' up with 'libvirt' provider...
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/fedora/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

**Comment by abhishekcs10** [comment]
i have setup bodhi development environment using virtualenv.
However everytime i entered a command many errors popped up due to some missing packages as i am using a minimal install copy of fedora.
So how can i be sure that bodhi is working well?? 
and what to do further?

**Comment by trishnaguha** [comment]
@abhishekcs10 Have you tried to run the server using `pserve development.ini --reload`?
You would be able to view the app on `http://localhost:6543`
Also run `python setup.py test` to make sure everything is working fine. You are supposed to have all tests passed successfully!

**Comment by trishnaguha** [comment]
@abhishekcs10 Regarding vagrantfile, sounds like you are on Ubuntu?
Try restarting libvirt service.
`service libvirtd restart`

**Comment by abhishekcs10** [comment]
@trishnaguha i am using fedora 24 cloud server .
Do I need to have apache server.?

**Comment by trishnaguha** [comment]
@abhishekcs10 You don't have to install it separately. 
Since you have mentioned that you have setup the development environment of bodhi I can assume that you already have the application running on your machine.
If you have followed all the instructions properly starting from https://github.com/fedora-infra/bodhi#virtualenv to the end of `README` you are supposed to have everything ready for running the application on your localhost.
You just need to execute `pserve development.ini --reload`(mentioned on README), you will be able to view the app via localhost:6543

**Comment by abhishekcs10** [comment]
the server startes but i am getting programming error in a database query when i open localhost:6543 on web browser..
I can give access to server if you can provide your public ip.-->
error->
(psycopg2.ProgrammingError) column updates.autokarma does not exist LINE 2: ...AS updates_title, updates.karma AS updates_karma, updates.au... ^ [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT updates.id AS updates_id, updates.title AS updates_title, updates.karma AS updates_karma, updates.autokarma AS updates_autokarma, updates.stable_karma AS updates_stable_karma, updates.unstable_karma AS updates_unstable_karma, updates.requirements AS updates_requirements, updates.require_bugs AS updates_require_bugs, updates.require_testcases AS updates_require_testcases, updates.notes AS updates_notes, updates.type AS updates_type, updates.status AS updates_status, updates.request AS updates_request, updates.severity AS updates_severity, updates.suggest AS updates_suggest, updates.locked AS updates_locked, updates.pushed AS updates_pushed, updates.critpath AS updates_critpath, updates.close_bugs AS updates_close_bugs, updates.date_submitted AS updates_date_submitted, updates.date_modified AS updates_date_modified, updates.date_approved AS updates_date_approved, updates.date_pushed AS updates_date_pushed, updates.date_testing AS updates_date_testing, updates.date_stable AS updates_date_stable, updates.date_locked AS updates_date_locked, updates.alias AS updates_alias, updates.old_updateid AS updates_old_updateid, updates.release_id AS updates_release_id, updates.user_id AS updates_user_id \nFROM updates \nWHERE %(param_1)s = updates.release_id AND updates.status = %(status_1)s) AS anon_1'] [parameters: {'param_1': 10, 'status_1': 'pending'}]

**Comment by trishnaguha** [comment]
@abhishekcs10 Oh execute `alembic upgrade head` :) and then run the server again.

**Comment by mbtamuli** [comment]
To see changes made to the code, we need to run `pserve development.ini --reload`, right?
I mean every time we make some change, we need to run this again to view the changes, right?

**Comment by trishnaguha** [comment]
@mbtamuli `pserve development.ini --reload` will launch bodhi application on localhost. This is how we run pyramid app.
If your changes are related to UI, you will be able to view that, otherwise you will need to write unittest to make sure your patch is working correct.

You can always come on #fedora-apps(IRC) if you have doubts :).

**Comment by abhishekcs10** [comment]
@trishnaguha  :(

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 3aae6532b560 -> a1d8dae7cc, Add autokarma column
ERROR [alembic.util.messaging] Online migration expected to match one row when updating '3aae6532b560' to 'a1d8dae7cc' in 'alembic_version'; 2 found
  FAILED: Online migration expected to match one row when updating '3aae6532b560'
  to 'a1d8dae7cc' in 'alembic_version'; 2 found

**Comment by abhishekcs10** [comment]
solved above issue :)
delete enteries from alembic_version table in the bodhi2 database and then run command 
alembic upgrade head (this command on first go failed because of m2crypto package missing but a row in alembic_version table was inserted so when i executed the command second time there were two copies... may be this caused error, not sure )

**Comment by trishnaguha** [comment]
@bowlofeggs We can close this? :)

**Comment by bowlofeggs** [comment]
@trishnaguha it does sound like we can - thanks!
