### ISSUE TITLE
Cannot submit kicad-4.0.2-1.fc23 to stable since it is older than kicad-2015.08.03-3.rev6041.fc23

### ISSUE THREAD

**Issue by lkundrak** [fedora-infra/bodhi#801]
I get this error when I try to push the update:

  Cannot submit kicad-4.0.2-1.fc23 to stable since it is older than kicad-2015.08.03-3.rev6041.fc23

It is not true. And it shouldn't matter; I have no idea why the kicad-2015.08.03-3.rev6041.fc23 version is relevant.

**Comment by puiterwijk** [comment]
The problem here is that bodhi seems to be using lexicographical version ordering.
This means that 2015 < 4, just because 2 < 4.
This means that the version number comparison that Bodhi is doing will need to change to an interpretation schema rather than plain lexicographical ordering.

**Comment by puiterwijk** [comment]
Sorry, I misread the ordering.
In this case, you will need to use an epoch, since 4 < 2015 with semantic versioning, which means that also dnf and yum will consider 2015 older.

**Comment by puiterwijk** [comment]
Okay, there is an epoch but bodhi ignores it for version ordering, which is the underlying bug here.

**Comment by puiterwijk** [comment]
This seems to be fixed by a59b7f1a0c9b2a671bb41f9748dfffb1bae76a02.

**Comment by lmacken** [comment]
https://github.com/fedora-infra/bodhi/issues/801 is currently breaking database migrations in staging, which is preventing me from getting this code out right now. I'm working on a fix, but in the mean time I queued this update up for stable by hand.
