### ISSUE TITLE
Multiple builds update does not obsolete active updates for a single package (with same version)

### ISSUE THREAD

**Issue by rapgro** [fedora-infra/bodhi#803]
We've seen this already in #785.
I (accidently) managed to reproduce with https://bodhi.fedoraproject.org/updates/FEDORA-2016-796de36de3 as now in a dead state without any action buttons, corresponding multiple builds update is https://bodhi.fedoraproject.org/updates/FEDORA-2016-b38ae34a10

**Comment by lmacken** [comment]
Ah, so it looks like the issue editing and update and adding the same build from a different update. I'll try and write a test case to reproduce this.

**Comment by lmacken** [comment]
I was able to write a test to reproduce this issue. Working on a fix.
