### ISSUE TITLE
Unable to push to stable builds with epoch set

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#804]
In updates [1] there is runc-0.0.8-0.1.git1a124e9.fc23.
In stable there is runc-0.2-0.2.git90e6d37.fc23.

When requesting for a push to stable for [1] I get:
```
Cannot submit runc-0.0.8-0.1.git1a124e9.fc23 to stable since it is older than runc-0.2-0.2.git90e6d37.fc23
```

runc-0.0.8-0.1.git1a124e9.fc23 has epoch set to 1, runc-0.2-0.2.git90e6d37.fc23 has no epoch.

Seems the check does not check for epoch. 

[1] https://bodhi.fedoraproject.org/updates/FEDORA-2016-c579df4ace

**Comment by lmacken** [comment]
I fixed this in https://github.com/fedora-infra/bodhi/pull/792 but have been hitting some issues deploying it to staging... working on it this week, but in the mean time I'll queue your update up for stable manually.

**Comment by ingvagabund** [comment]
Thanks
