### ISSUE TITLE
Put bodhi docs on rtfd.org

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#805]
We have a docs directory here https://github.com/fedora-infra/bodhi/tree/develop/docs

We should build them!  :hammer:

Once they're built, we should link to them in this document before closing this ticket, please:  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/apps-fp-o/files/apps.yaml

**Comment by lmacken** [comment]
I think migrating to pagure.io is probably in our future... and doesn't that support it's own doc rendering?

**Comment by bowlofeggs** [comment]
@jeremycline put Bodhi's docs here:

http://bodhi.readthedocs.io/en/latest/

I do believe we will switch to pagure at some point, but I tried to do this about a month ago and the importer wasn't able to process Bodhi's repo:

https://pagure.io/pagure-importer/issue/110

I added the current RTD URL here:

https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/roles/apps-fp-o/files/apps.yaml?id=02e54075a19f57f40914d17bc49447d676a5be3d

**Comment by ralphbean** [comment]
:rainbow:

**Comment by jeremycline** [comment]
Note that Pagure has a webhook for RTD and Pagure itself can't currently auto-build the docs like RTD does.
