### ISSUE TITLE
bug is placed in MODIFIED even though 'close bugs on stable' is unchecked

### ISSUE THREAD

**Issue by bcl** [fedora-infra/bodhi#807]
I created this update:
https://bodhi.fedoraproject.org/updates/lorax-24.15-2.fc24

And unchecked 'close bugs on stable' and it changed bug 1315541 to MODIFIED when it added the comment about the update. I expected the comment, but not the change in state.

**Comment by bowlofeggs** [comment]
I think this is a duplicate with #1349. Since that one has a little more discussion, I'll close this one even though it was reported first.
