### ISSUE TITLE
bodhi --mine gives KeyError

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/bodhi#811]
Running "bodhi --mine --username=puiterwijk" results in a KeyError: 'title'.

Also, not all update information is displayed:
....
 python-openid-cla-1.2-1.fc22                 enhancement  stable    2016-03-02 
 python-fedora-0.7.1-4.fc22
 python-openid-cla-1.2-1.el6                  enhancement  stable    2016-03-10 
 python-openid-cla-1.2-1.el7                  enhancement  stable    2016-03-10 
 python-fedora-0.7.1-4.fc23                   enhancement  stable    2016-02-22 
 python-openid-cla-1.2-1.fc23
 devtodo2-2.1-14.20120711git8dee6.fc23        bugfix       stable    2016-02-21 
.....

**Comment by ryanlerch** [comment]
The Bodhi CLI has changed since this issue was filed, but the --mine is not implemented in the new CLI for updates. There is an open issue for --mine on overrides too ( #1382  )

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744
