### ISSUE TITLE
Can not push to stable (again)

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#817]
With reference to #787, I have the same problem again not being able to push an update to EPEL 5.

I added a comment to the old issue, but I guess noone reads comments to closed issues.

Can you please push https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-c13a4dbfd9 to stable since bodhi refuses me to do it because it doesn't understand Epochs in EPEL 5.

**Comment by lmacken** [comment]
Yeah, the fix for this hasn't been pushed out to production yet. In the mean time, I manually submitted your update to stable.
