### ISSUE TITLE
Remove "-" sign from 'Days to Stable' in Web UI

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/bodhi#819]
I just found that bodhi is displaying `Days to Stable` with `-` sign before the number of days. 
Although the logic works perfect but it looks bit awkward to have `-` before the number of days. :)
We can remove the `-` sign in web UI. 
For example https://bodhi.fedoraproject.org/updates/FEDORA-2016-5621af18d4
This was the commit for the method https://github.com/fedora-infra/bodhi/commit/f297ddba86509fbb3e26040ecaa7ccc2de39b0e2

**Comment by trishnaguha** [comment]
Let me know if we really want this. I think that I have the patch ready. If nobody takes this I won't mind pushing a PR for the same. :)

**Comment by lmacken** [comment]
Yeah, feel free to send in a PR to remove this. Thanks :)
