### ISSUE TITLE
Unchecking bugs in Related Bugs makes them vanish

### ISSUE THREAD

**Issue by bcl** [fedora-infra/bodhi#826]
instead of just unchecking the bug it disappears from the list.

**Comment by mattiaverga** [comment]
While working on #2821 I came across with this old bug report.

Removing the checkbox seems to be the intended behavior and is made by a specific function introduced to solve #260.
Should we change this?

**Comment by bcl** [comment]
I think so. The Related Bugs list itself shouldn't change when you uncheck the bug. What if you accidentally unchecked it? Now you have to start over by refreshing the page.

**Comment by mattiaverga** [comment]
Well, no, if you accidentally uncheck a bug you can get it again by entering the package name in the `packages` textfield; or you can re-add it manually by entering the bug number in the `Related Bugs` textfield.

I think another solution would be to add a specific icon to remove the bug (or the candidate build) from the list, but I think the actual solution was preferred to not make the UI more confusing.
I would like to hear @bowlofeggs opinion before proposing a change like this.

**Comment by bowlofeggs** [comment]
Yeah I think I like the original suggestion in #260 to use a remove button instead of checkboxes, like @kalev suggestion. I'm not sure why it was implemented this way, but I agree that it is confusing.

**Comment by mattiaverga** [comment]
This is fixed with the new update form, closing.
