### ISSUE TITLE
Can not create new override with build NVR for which there was override in the past

### ISSUE THREAD

**Issue by thozza** [fedora-infra/bodhi#827]
Today I tried to create a new buildroot override with a build of log4cplus in F24 because of forgotten dependency I needed to rebuild. Previously another maintainer created buildroot override with the same build for F24 as I was trying to create, but the override was already expired.

When creating new override, the creation failed with error "Builds : Buildroot override for log4cplus-1.2.0-2.fc24 already exists". However there is no way in web UI to find old overrides created by other users. I had to open old override from F23 and change the dist tag in URL to get to it. After that I was able to resubmit the old override.

I see two issues here:
1. I'm not able to find overrides created by other users in the web UI
2. I should be able to create new override with the same build if the old already expired without the need to look for the old one and resubmit it. Especially in a case when the old override was not created by me, as I'm not able to easily find it. 

Maybe bodhi is identifying the overrides by build NVR, but given the situation this does not seem as a good solution, because it forbids one to resubmit expired override with the same build NVR.

**Comment by mattiaverga** [comment]
Both the issues are fixed in Bodhi 5.4.0:
- overrides can be searched through the new override list page
- submitting an override for a build with an active or expired override will inherit the notes of the old override and set a new expire date
