### ISSUE TITLE
Updates stuck in "This update is currently locked and cannot be modified" state

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#828]
Four of my pending updates:
- https://bodhi.fedoraproject.org/updates/FEDORA-2016-d97cf2c03f
- https://bodhi.fedoraproject.org/updates/FEDORA-2016-60adf1a1bc
- https://bodhi.fedoraproject.org/updates/FEDORA-2016-cb8ef7364a
- https://bodhi.fedoraproject.org/updates/FEDORA-2016-ddcb606466

have been stuck in the "This update is currently locked and cannot be modified" state now for several days. During this time there have been several successful mashes for f22-updates-testing and f23-updates-testing, which are the repos these updates are submitted to. Other updates I have submitted to these repos after the stuck updates were submitted have already been pushed successfully.

What is going on with these updates?

**Comment by ellert** [comment]
It has now been two more days, and these updates are still stuck. There has been even more mashes run during this time, and none of them pushed the stuck pending updates.

**Comment by ellert** [comment]
Issue #830 is another example of an update suffering the same fate. Looking at the list of updates in bodhi there are 21 updates submitted to f22-updates-testing and 36 updates submitted to f23-updates-testing that are stuck in this way. All submitted (or in two cases modified) five days ago.

**Comment by lmacken** [comment]
This was caused by a sporadic database outage that happened at the beginning of the push. I unlocked this update by hand, so it should get pulled into the next one. Sorry for the inconvenience.
