### ISSUE TITLE
bodhi doesn't appear to reset karma on a build when it's unpushed, edited and a new version pushed.

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#845]
In this grub2 update the initial NVR was grub2-2.02-0.33.fc24 it received a bunch of karma.

Then the build was unpushed by the maintainer and grub2-2.02-0.34.fc24 was submitted. In the next updates push that happened it took all the karma from the original build and ones the updates-testing push was done it automatically then submitted it for stable.

I would expect that for a build that is unpushed and then edited that the karma would be reset.

https://bodhi.fedoraproject.org/updates/FEDORA-2016-c4d43baacc

**Comment by trishnaguha** [comment]
I would like to work on it.

**Comment by trishnaguha** [comment]
It seems we already have test for this https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/functional/test_updates.py#L2396 and it doesn't seem to fail.
I am not sure what might be the issue here. @lmacken thoughts on this?

**Comment by trishnaguha** [comment]
I tried adding few lines in the testcase `test_edit_testing_update_reset_karma` for `unpushing` the update before `editing` the build and it passed successfully. 
Here are the few added lines. https://paste.fedoraproject.org/382092/

**Comment by lmacken** [comment]
This specific update got into a weird state where it contained multiple grub2 builds. I had to go into the database and remove one of them by hand. We should try and reproduce this issue in a test case.

**Comment by trishnaguha** [comment]
@lmacken We can relate this issue with https://github.com/fedora-infra/bodhi/issues/846
To check for multiple builds for same package the script is here https://github.com/fedora-infra/bodhi/blob/develop/bodhi/validators.py#L370. We also have test for the same https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/functional/test_updates.py#L154.

I tried submitting multiple builds https://paste.fedoraproject.org/382402/ and got this traceback https://paste.fedoraproject.org/382401/ which is expected to happen. Bodhi is not allowing to send two builds for same update simultaneously.

I think this is a matter of obsoleting the older build. Let me know if I am wrong.

**Comment by bowlofeggs** [comment]
I believe that the karma counting is correct now. It was re-factored a couple years ago to store the data in a normalized fashion, rather than denormalized (which is how some of the data used to get into weird states). Let me know if you think this is still an issue.
