### ISSUE TITLE
"Push to stable" on an obsolete update submits to testing; should not be submitted at all

### ISSUE THREAD

**Issue by morxa** [fedora-infra/bodhi#848]
On an obsolete update, there is still a "Push to stable" option. If I do a push to stable, the update is submitted to testing instead. This leads to two different updates (the new update and the obsolete update) for the same package pending for testing.
#### How to reproduce:
1. Submit an update (say update 1) to testing; wait until it has been pushed to testing (otherwise this results in the behavior described in #818).
2. Submit a second update (say update 2); update 2 will obsolete update 1.
3. Go back to update 1. It will have the option to push to stable; press the button to push to stable.
#### Expected behavior:

Some error message, e.g. "This update is obsolete and cannot be submitted to stable".
#### Actual behavior:

Update 1 will be submitted to testing instead. Both updates are now pending for testing.

This happened to me with btrfs-sxbackup for F23:
Update 1 for 0.6.6-2: [FEDORA-2016-aca792d485](https://bodhi.fedoraproject.org/updates/FEDORA-2016-aca792d485)
Update 2 for 0.6.7-1: [FEDORA-2016-6c687157ee](https://bodhi.fedoraproject.org/updates/FEDORA-2016-6c687157ee)

**Comment by trishnaguha** [comment]
There can be two possible solutions.
- Stop showing **Push to Stable** for `Obsolete` updates.
-  Show **Push to Stable**, but requesting for it would revoke the request automatically and display some message like `"This update is obsolete and cannot be submitted to stable"`. 

@lmacken Which one should we go for?
