### ISSUE TITLE
fedora-bootstrap improvements.

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#852]
An issue to track the progress of @ryanlerch's fedora-bootstrap improvements for bodhi.

**Comment by lmacken** [comment]
![i](https://cloud.githubusercontent.com/assets/9980/16274630/a28754c6-3863-11e6-8a48-1453b3320bc6.png)

https://github.com/ryanlerch/bodhi

**Comment by trishnaguha** [comment]
This is going to look really nice :+1: . Excited to see the updated ui :).

**Comment by lmacken** [comment]
Hey @ryanlerch, is this almost ready to merge?
