### ISSUE TITLE
never ending progress animation near bug number

### ISSUE THREAD

**Issue by pavlix** [fedora-infra/bodhi#853]
The new bodhi shows an animation that hints that it hasn't finished its job. The animation is located near the bug number. There is no hint what the job is though and the animation doesn't go away.

I'm seeing it on the following update:

https://bodhi.fedoraproject.org/updates/aiccu-2007.01.15-26.fc23

**Comment by yarda** [comment]
When this happen correct data can be shown if the page is refreshed manually after cca. few minutes.

**Comment by yarda** [comment]
I am experiencing this problem in Firefox (currently version 47), and I don't know whether the animation is "never ending" or whether it ends after while (I always refreshed the page manually after few minutes).

**Comment by k3rn3l3rr0r** [comment]
I can confirm this behaviour. In my case with an URL pointing to a RHBZ bug report which was classified as private in bugzilla. Sorry, I can't find the package/update concerned, but this should be easy to reproduce.

**Comment by bowlofeggs** [comment]
I believe this is fixed now for non-private bugs. It seems that there was a deployment issue that prevented bodhi's frontend and backend from communicating. @puiterwijk has resolved this for us!

The blinking dots may still happen for a minute or two after the update is submitted - they mean that the backend hasn't finished talking to bugzilla to retrieve the details yet. Once the details are retrieved, refreshing the update page should show the details as long as the BZ isn't private.
