### ISSUE TITLE
Provide URL link to feedback guidelines

### ISSUE THREAD

**Issue by stickster** [fedora-infra/bodhi#865]
Re: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/4526JDWE77ZXVPIT67ABOKVIP677AQYY/

In the section for delivering karma/feedback, it seems like it would be useful to provide a link to guidelines for providing same -- i.e. setting expectations for feedback.

**Comment by userimack** [comment]
hii, I would like to work on this fix.

**Comment by trishnaguha** [comment]
@lmacken We can close this :) ?

**Comment by bowlofeggs** [comment]
Thanks @trishnaguha, looks like we're good to close!
