### ISSUE TITLE
Stable request policy bug (or GUI bug -- I'm not sure which)

### ISSUE THREAD

**Issue by amluto** [fedora-infra/bodhi#869]
This may represent more than one bug.

The Bodhi web UI would not let me push my update to stable despite having plenty of karma (https://bodhi.fedoraproject.org/updates/fish-2.3.0-2.fc24).  The options were "Edit" and "Unpush".

I was able to request stable from the command line, though:

```
$ bodhi -u amluto -R stable fish-2.3.0-2.fc24
No handlers could be found for logger "fedora.client.bodhi"
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 273, in main
    log.info(data['tg_flash'])
KeyError: 'tg_flash'

```

The output notwithstanding, that worked.

**Comment by lmacken** [comment]
The command-line bug will be fixed in the next release. As for the first issue, I /think/ that might be fixed as well.

**Comment by ryanlerch** [comment]
Pretty sure this one is fixed now in the new webUI. Feel free to open if it is still an issue.
