### ISSUE TITLE
[RFE] Add direct hyperlink from NVR text to koji build

### ISSUE THREAD

**Issue by deekej** [fedora-infra/bodhi#873]
Hello guys!

Right now, there's no way to directly _click-through_ from bodhi update page to koji build page...

Example of page: https://bodhi.fedoraproject.org/updates/FEDORA-2016-fd7708db05

The _Builds_ line shows 'esmtp-1.0-15.fc23', but I can't click on it to get into koji:
https://koji.fedoraproject.org/koji/buildinfo?buildID=780917

This means, that if user (like me) does not have _testing_ repo enabled, is notified about the new build via automatic comment in BZ, and just wants to try only the new build if it actually fixes the issue for him, the user then have to manually search for the package in koji (and select the correct build by NVR).

I think making the NVR a direct link (in bodhi update page) to exact build in koji would help improve user's experience, and might help getting more the +/-1 karma into the bodhi update page.

I'm not sure I made myself clear, I hope you get my point. If not, feel free to ask me. :)

**Comment by deekej** [comment]
Ah, I've just seen there's a small _icon_ at the end of the _Build_ line, leading directly to koji... It just shows for me that this is not so much intuitive as I would expect...

Could be possible to make the NVR text as a link to koji build?

**Comment by ryanlerch** [comment]
In the Builds tab of an update, the NVR is now a link to the koji build.
