### ISSUE TITLE
[webgui] "New update" form usability

### ISSUE THREAD

**Issue by jnpkrn** [fedora-infra/bodhi#876]
It seems that currently the form is convenient just for the "clicky" people, but those preferring keyboard should be served as well.
Now I am talking about following use case when filling out the mentioned form:
- fill the package name under Packages label and do not select the autocompletion item
- press `TAB` so as to move to the next item

Observed: no completion of possible builds is triggered

Expected: it is triggered just as when the package is selected from autocompletion with a mouse

**Comment by k3rn3l3rr0r** [comment]
@jnpkrn I don't think, that the "New update" form,  as it is now, serves only the "clicky" people. You just have to press `arrow down` / `arrow up` on your keyboard to select the desired package from the autocomplete list and confirm your selection with `TAB`, which works well for me in Chrome and Firefox...

But to further enhance the accessibility of the form I would suggest to autofocus the "Packages" filed on the page load...
