### ISSUE TITLE
Vagrant dev instance talking to prod

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/bodhi#886]
I was testing out the functionality of bodhi in local vagrant instance and logged in through fas.

For some reason it was affecting prod since the author of a package was messaging me why I was messing with the karma so much. ( I was trying to fault bodhi for the race condition https://github.com/fedora-infra/bodhi/issues/834 ) Is there a way we can force isolation of development env from prod?

**Comment by trishnaguha** [comment]
I think the only way to work with karma(Checking karma functionality) in dev is to write unit test to reproduce the same. That is what I have done while working with karma. https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/functional/test_updates.py is the place to workaround with karma.

**Comment by skrzepto** [comment]
The problem with unittests is that its sequential. Unless there's a way we can send multiple karma updates at once (threads??) to fault bodhi.

**Comment by ryanlerch** [comment]
Pretty sure the Vagrant instance is now fixed so this no longer happens.

Feel free to re-open if you are still experiencing this.
