### ISSUE TITLE
Bodhi sometimes does not generate repodata/repomd.xml

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#887]
@ausil sent me a script that he frequently uses after the masher runs to check on some common problems. One of the problems is that the repomd.xml file isn't always present afterwards. The following script is used by release engineering to work around this problem:

```
## Missing repodata/repomd.xml
## "IOError: Cannot open"
for I in /mnt/fedora_koji/koji/mash/updates/dist-5E-epel{,-testing}.repocache/repodata/ \
         /mnt/fedora_koji/koji/mash/updates/dist-6E-epel{,-testing}.repocache/repodata/ \
         /mnt/fedora_koji/koji/mash/updates/epel7{,-testing}.repocache/repodata/        \
         /mnt/fedora_koji/koji/mash/updates/f23-updates{,-testing}.repocache/repodata/  \
         /mnt/fedora_koji/koji/mash/updates/f24-updates{,-testing}.repocache/repodata/  \
         /mnt/fedora_koji/koji/mash/updates/f25-updates{,-testing}.repocache/repodata/  ;
do
        if test -d "$I"
        then  
              if test -f "${I}/repomd.xml"
              then  
                    continue
              else  
                    printf '* No repomd.xml found; Removing %s\n' "$I"
                    sudo rmdir "$I"
              fi
        else
              #printf '> Skipping (not found) %s\n' "$I"
              continue
        fi
done
```

This problem is mentioned at the bottom of https://infrastructure.fedoraproject.org/infra/docs/bodhi.rst

The cause is not known. For now, it would be helpful to add some logging so we can identify what is happening.

**Comment by ausil** [comment]
I want to be clear. I've never used the script. Others wrote it and use it.

Dennis

On August 17, 2016 3:58:15 PM CDT, Randy Barlow notifications@github.com wrote:

> @ausil sent me a script that he frequently uses after the masher runs
> to check on some common problems. One of the problems is that the
> repomd.xml file isn't always present afterwards. The following script
> is used by release engineering to work around this problem:
> 
> ```
> ## Missing repodata/repomd.xml
> ## "IOError: Cannot open"
> for I in
> /mnt/fedora_koji/koji/mash/updates/dist-5E-epel{,-testing}.repocache/repodata/
> \
> /mnt/fedora_koji/koji/mash/updates/dist-6E-epel{,-testing}.repocache/repodata/
> \
> /mnt/fedora_koji/koji/mash/updates/epel7{,-testing}.repocache/repodata/
>       \
> /mnt/fedora_koji/koji/mash/updates/f23-updates{,-testing}.repocache/repodata/
> \
> /mnt/fedora_koji/koji/mash/updates/f24-updates{,-testing}.repocache/repodata/
> \
> /mnt/fedora_koji/koji/mash/updates/f25-updates{,-testing}.repocache/repodata/
> ;
> do
>        if test -d "$I"
>        then  
>              if test -f "${I}/repomd.xml"
>              then  
>                    continue
>              else  
>                    printf '* No repomd.xml found; Removing %s\n' "$I"
>                    sudo rmdir "$I"
>              fi
>        else
>              #printf '> Skipping (not found) %s\n' "$I"
>              continue
>        fi
> done
> ```
> 
> This problem is mentioned at the bottom of
> https://infrastructure.fedoraproject.org/infra/docs/bodhi.rst
> 
> The cause is not known. For now, it would be helpful to add some
> logging so we can identify what is happening.
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-infra/bodhi/issues/887

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bowlofeggs** [comment]
I've filed https://github.com/fedora-infra/bodhi/issues/908 as a workaround to this issue. This issue will remain open as a way to track the problem of the missing file, but I think fixing #908 will be easier and will relieve some of the pain felt by releng.

We should still try to identify why these files are going missing and see if we can stop that from happening. #908 beign fixed makes fixing this much less urgent, as this is now reduced to a performance issue instead of a correctness issue.
