### ISSUE TITLE
Incomplete list of Taskotron checks is pulled

### ISSUE THREAD

**Issue by mkrizek** [fedora-infra/bodhi#891]
With #890, bodhi pulls Taskotron results per koji_build. It seems though that not always a complete list of results is pulled. See https://bodhi.fedoraproject.org/updates/FEDORA-2016-d1861f2d10 and https://bodhi.fedoraproject.org/updates/FEDORA-2016-a4de0434e9. They differ in a number of rpmgrill subchecks, at least in my browser. The complete list is here: https://taskotron.fedoraproject.org/resultsdb/results?job_id=312600.

**Comment by ryanlerch** [comment]
There has been a number of changes to how these results are pulled from taskotron in the past few releases. Is this one still an issue?

**Comment by kparal** [comment]
This should be resolved now. Bodhi does no longer pull the list of all available testcases, instead it checks for existence of just those specified.
