### ISSUE TITLE
setup.py install includes the unit tests

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#899]
Currently running setup.py install will install the unit tests. We should adjust setup.py to exclude the unit tests, or we could move the unit tests to be outside of the code directory so setup.py doesn't find them during install. Either way is fine.

**Comment by amitsin6h** [comment]
Want to work on this

**Comment by bowlofeggs** [comment]
I needed to mess with the setup.py files to split up the client and server, so I went ahead and fixed this in https://github.com/fedora-infra/bodhi/pull/915

I'll update that commit message to reference this issue. Thanks for taking a shot at it @jarifibrahim, and thanks to @amitsin6h for the offer to help out too!
