### ISSUE TITLE
Work around missing repodata.xml

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#908]
Sometimes the previous run of the Bodhi masher leaves some directories with missing repodata.xml files (See #887). That issue is about stopping that from happening in the future, but it is a bit mysterious and may take some time to identify its cause.

In the meantime, we can make Bodhi more robust. In subsequent runs of the masher, there is a test for the existence of the folder that should contain a repodata.xml file and if that folder is present Bodhi assumes that the file is present as well. This assumption is false, and it causes Bodhi to blow up later.

We should adjust that test to test for the existence of the file instead of the folder. This will make Bodhi more robust for releng, and should be a pretty easy change as well.

**Comment by amitsin6h** [comment]
can i work on this

**Comment by bowlofeggs** [comment]
@amitsin6h sure, that would be great!

**Comment by amitsin6h** [comment]
so how can i start. excited \o/

**Comment by bowlofeggs** [comment]
Hey @amitsin6h! The easiest way to get start with Bodhi development is to use our Vagrant setup:

https://github.com/fedora-infra/bodhi/blob/develop/README.rst#vagrant

I'm not actually too familiar with the specific code that this ticket is about, so I'm not sure I can give you very specific pointers for it. I marked it easy fix because once you find that if statement (wherever it is), it's likely just a matter of adjusting the check to test for the existence of the file rather than the directory that contains it.

**Comment by himanshuraja** [comment]
hello,can I also work on it?

**Comment by bowlofeggs** [comment]
Hello @himanshuraja! This is probably going to be a pretty small change, but if you want to coordinate with @amitsin6h go for it!

**Comment by himanshuraja** [comment]
Yes but I am new to this , can you please help me out in starting ? Thank you .

**Comment by trishnaguha** [comment]
@amitsin6h @himanshuraja You probably need to check https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/metadata.py
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/consumers/masher.py#L770-L816

Might want to look at the testcases also?
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/test_masher.py
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/test_metadata.py

**Comment by himanshuraja** [comment]
thanks a lot @trishnaguha .

**Comment by himanshuraja** [comment]
https://download.fedoraproject.org/pub/fedora/linux/updates/%s/%s/repodata/repomd.xml
is giving error cause .

**Comment by sayanchowdhury** [comment]
@himanshuraja It would be better to come over on IRC for any issues you are facing.

**Comment by himanshuraja** [comment]
Hi,
I am new to contributing,can you please share the channel where I can log
on.
Thanks.
Regards,
Himanshu Sharma
dgplug,Acadgild

**Comment by sayanchowdhury** [comment]
The channel is `#fedora-apps` on Freenode.

**Comment by himanshuraja** [comment]
I really appreciate it,thank you.

**Comment by amitsin6h** [comment]
am having problem in setting up bodhi development am setting up using virtualenv

**Comment by k3rn3l3rr0r** [comment]
@amitsin6h Can you describe the problem further? Maybe include the error message or a link to a log?

**Comment by amitsin6h** [comment]
@k3rn3l3rr0r @trishnaguha @bowlofeggs @sayanchowdhury     http://paste.fedoraproject.org/427071/36593701/

**Comment by k3rn3l3rr0r** [comment]
@amitsin6h @bowlofeggs I can't test it right now on virtualenv host, but it seems like a deps/path problem coming from link_system_libs() in the bootstrap.py ... This conversation should be moved in new, separate issue.

**Comment by bowlofeggs** [comment]
@amitsin6h it looks to me like maybe you don't have a virtuenv enabled.

**Comment by amitsin6h** [comment]
@bowlofeggs how should i enable it

**Comment by bowlofeggs** [comment]
@amitsin6h I'm not sure, but it does sound like there might be a problem in the virtualenv setup. I agree with @k3rn3l3rr0r, and recommend filing a separate issue as we don't want to fill this ticket up with non-related conversation.

**Comment by amitsin6h** [comment]
@bowlofeggs is this the thing which i need to fix 
http://paste.fedoraproject.org/427822/82777114/

**Comment by trishnaguha** [comment]
@k3rn3l3rr0r Make sure to open PR since you have already committed in your fork :).

**Comment by k3rn3l3rr0r** [comment]
@trishnaguha Thanks. But I commented on that diff and pinged @bowlofeggs to take a look, as I wasn't very sure, this could be merged... But yeah, I will open a PR.

**Comment by bowlofeggs** [comment]
@amitsin6h It looks like you have a missing dependency. I think @k3rn3l3rr0r might have made the change we need in that linked PR. @k3rn3l3rr0r, I'll take a look soon and thanks very much!
