### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by himanshuraja** [fedora-infra/bodhi#917]
https://download.fedoraproject.org/pub/fedora/linux/updates/%s/%s/repodata/repomd.xml
is giving error

**Comment by sayanchowdhury** [comment]
Surely, %s is culprit here but can you share more details on the same? How to reproduce, etc?

**Comment by himanshuraja** [comment]
Hi,
![bad](https://cloud.githubusercontent.com/assets/9448918/18410370/a7d8b6d6-777e-11e6-9e68-4463f62bb151.png)

**Comment by sayanchowdhury** [comment]
The URL is malformed and ought to throw error. Can you share from where you are trying to access the same URL. If you trying to setup the project to contribute it would better to ping us over IRC with the setup issues

**Comment by himanshuraja** [comment]
Yeah thank you for your kind reply.

**Comment by bowlofeggs** [comment]
I'm going to close this, as it does not seem to be a bodhi issue.

**Comment by himanshuraja** [comment]
Hi,
Actually this link I have gathered from the following.
