### ISSUE TITLE
Document where all repocaching takes place

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#926]
We currently have a need to regenerate all the repodata fresh (on order to pick up any weak deps in packages). In order to do that we need to figure out all the places that repodata could be cached so we can remove those caches and get bodhi to do a fresh new repodata. 

I already noted/tried removing /mnt/koji/mash/updates/*repocache but that didn't do it. 
It might be mash that has additional cache, or it might be that bodhi is pulling cache from the existing repos. 
If we could document this we could then know where to remove the caching.

**Comment by pnemade** [comment]
Not sure where this documentation will happen but I think good to add some section on this "Regenerating repodata freshly" in fedora-infra bodhi SOP also.

**Comment by bowlofeggs** [comment]
@nirik Is this still a problem since Bodhi uses pungi now?

**Comment by nirik** [comment]
Not a problem for me anymore. I suppose any docs could say "see pungi for information on caching"?

**Comment by bowlofeggs** [comment]
I don't think Pungi really documents this either, since https://docs.pagure.org/pungi/search.html?q=cache&check_keywords=yes&area=default only matches dogpile cache. I think I will close this as a result, since there aren't really Pungi docs to link to either.
