### ISSUE TITLE
Support waiving some blocking Taskotron task results

### ISSUE THREAD

**Issue by dodjiseketeli** [fedora-infra/bodhi#932]
There are some Taskotron task results that can block Bodhi updates.

In some case, it is important for package maintainers to be able to override the fact that a particular task result blocks the package update.

In this overriding process, the maintainer would have to document the reason why she thinks that the result of the offending test should not block the package update.

All the waivers of all the tests that were initially supposed to block a given update should be available and easily readable from the page of the update.

For more context about this issue, please read the discussion at https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MCYGMG24GAHGUD2AUACL45MFGXSSR4OR/

**Comment by dodjiseketeli** [comment]
Please note that this issue is probably a blocker for issue https://github.com/fedora-infra/bodhi/issues/933.

**Comment by bowlofeggs** [comment]
Bodhi has integration with WaiverDB to do this now.
