### ISSUE TITLE
Make Taskotron's task-abicheck results potentially blocking for package updates

### ISSUE THREAD

**Issue by dodjiseketeli** [fedora-infra/bodhi#933]
The task-abicheck task[1](https://fedoraproject.org/wiki/Taskotron/Tasks/abicheck) spots potentially incompatible ABI changes in C and C++ packages updates that are in the "critical path"[2](https://fedoraproject.org/wiki/Update_Critpath_SOP) set.

Bodhi should take the results of that task-abicheck task into account before allowing a package to be automatically updated.

Whenever the result of that task-abicheck is either NEED_INSPECTION or FAILED then the package update should be blocked.  That means no _automatic_ update should happen for that particular package version.

If the maintainer reviews and _waives_ the problematic task-abicheck, then the update can be un-blocked.

Please note that this issue probably depends on issue https://github.com/fedora-infra/bodhi/issues/932.

To context of this Request For Enhancement can be better understood by reading the email sub-thread under https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/ZDRC4AHWJYEPCRLLMIA5UHHIWQ7DB6ZF/

**Comment by keszybz** [comment]
It'd be nice to be able to preemptively mark some builds as abi breaks to tell task-abicheck to ignore them. I have no idea what the best way to mark this would be (maybe some kind of fake Provides). This way we don't get false-positive errors from task-abicheck.

**Comment by dodjiseketeli** [comment]
Zbigniew Jędrzejewski-Szmek notifications@github.com a écrit:

> It'd be nice to be able to preemptively mark some builds as abi breaks
> to tell task-abicheck to ignore them.

There is a way to tell the ABI verifier in task-abicheck to avoid
reporting some classes of ABI changes, because for instance, the package
maintainers knows that that particular class of ABI changes is OK for
her package.  To do so, the package maintainer needs to add a file which
name ends with the suffix ".abignore" into the package.  That file
contains "suppression specifications" that instruct the ABI verifier to
suppress some ABI changes from the report.  The concepts and syntax of
suppression specifications are explained at
https://sourceware.org/libabigail/manual/libabigail-concepts.html#suppression-specifications

> I have no idea what the best way to mark this would be (maybe some
> kind of fake Provides). This way we don't get false-positive errors
> from task-abicheck.

Suppression specifications are meant for this.

One annoying thing to keep in mind is that adding a suppression
specification requires the user to update the package; that is, she
needs to submit a new version of the package just to effectively "waive"
a test.  Note that there might be more than one Taskotron test to waive
too.  There are going to be more kinds of tests than just test-abicheck.

This is un-necessarily cumbersome for users (package maintainers),
compared to just clicking on the result of the test in Bodhi and say
"okay, the result this Taskotron task is not problematic in my case
because X, Y Z. I am thus waiving this blocking test result".

This is why I filed a companion Request For Enhancement to this one,
which is https://github.com/fedora-infra/bodhi/issues/932.  That's the
RFE to support waiving the result of a test that blocks an update in Bodhi.

## 

```
    Dodji
```

**Comment by keszybz** [comment]
I had in mind a more transient condition: where there's a single
abi break, for example an .so major-version bump.

Some packages put the following in %files:

```
%_libdir/lib%{name}.so.N
%_libdir/lib%{name}.so.N.*
```

where `N` is some number, so that when the so-version changes, and
`N` has to be explicitly updated. In that case one could also
"tell" abi-check that the abi break it will detect is expected.

On Thu, Sep 15, 2016 at 02:12:40PM -0700, dodjiseketeli wrote:

> This is un-necessarily cumbersome for users (package maintainers),
> compared to just clicking on the result of the test in Bodhi and say
> "okay, the result this Taskotron task is not problematic in my case
> because X, Y Z. I am thus waiving this blocking test result".

You're right, that's a fairly simple and sufficient solution.
After all majority of packages should not break ABI more than
once in a blue moon.

**Comment by bowlofeggs** [comment]
Bodhi now supports blocking package updates based on tests. As for a request to do it for a specific test, I recommend filing a ticket with FESCo to request it, since that is a matter of policy (and this ticket tracker is for the upstream Bodhi project).
