### ISSUE TITLE
Add example documentation for using the CLI

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#939]
We should add a workflows section to the man page that has some practical examples on how to use the CLI.

**Comment by cosmologist10** [comment]
Hey @bowlofeggs, I want to work on this issue. Can you please elaborate this task.

**Comment by bowlofeggs** [comment]
Hello @cosmologist10! The bodhi man page's source code is located in the sphinx project:

https://github.com/fedora-infra/bodhi/blob/2.2.4/docs/man_bodhi.rst

Quality man pages often have an Examples section that show the user a few common tasks they might want to do. For this ticket, we'll want to add an Examples section (probably just before the Bugs section at the end) with some examples of common bodhi CLI operations (perhaps things like creating updates, editing updates, downloading the files for an update, creating buildroot overrides, or anything else that sounds useful).

**Comment by cosmologist10** [comment]
Thanks @bowlofeggs, I am working on this issue.

**Comment by bowlofeggs** [comment]
We have some example documentation now.
