### ISSUE TITLE
Add test coverage for bodhi.server.services.updates.get_update_for_editing()

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#948]
We had an issue in production with an error in `bodhi.server.services.updates.get_update_for_editing()` that made it clear that we lack test coverage on the function. Please add tests for this function.

https://github.com/fedora-infra/bodhi/pull/945/ addressed the error in production.

**Comment by sebwoj** [comment]
@bowlofeggs can we close issue?

**Comment by bowlofeggs** [comment]
Ha, yep. I really need to go through Bodhi's giant pile of issues and clear out old stuff like this ☹
