### ISSUE TITLE
Bodhi 2.2.0 does not display the lock banner on locked updates during pushes anymore

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#952]
These two updates should both display that they are locked right now because there is an active push for them in progress, but neither of them displays the locked banner:

https://bodhi.fedoraproject.org/updates/FEDORA-2016-a6867138e2
https://bodhi.fedoraproject.org/updates/FEDORA-2016-821d2ec8cd

**Comment by bowlofeggs** [comment]
@puiterwijk suggested that the problem is that the `update.locked = True` isn't followed by `session.add(update)` at https://github.com/fedora-infra/bodhi/blob/2.2.0/bodhi/server/consumers/masher.py#L220

**Comment by trishnaguha** [comment]
This also means we don't have test for this :(.

**Comment by puiterwijk** [comment]
Turns out that we WERE locking them, but the interface didn't get the massive banner because of date_locked not being set.
See #959 and its commit messages for the explanation.

**Comment by bowlofeggs** [comment]
Thanks @puiterwijk! I'll update the text here to reflect that.
