### ISSUE TITLE
Page title for multiple updates can be quite large

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#957]
On updates that have many packages, like this GNOME one for example -- https://bodhi.fedoraproject.org/updates/FEDORA-2016-78efe5595f -- the &lt;title&gt; of the page contains all the package names.

While this might work for updates with just one package, for updates with many, it is unweildy and not useful at all. On a tab in your browser, you only see the name of the first package in the set, which may not be useful to describe the nature of the update.

**Comment by genodeftest** [comment]
On another page, FEDORA-2016-77ffa78abb, it seems to make [firefox run amok](https://bugzilla.redhat.com/show_bug.cgi?id=1378601) and [Epiphany is having a hard time too](https://bugs.webkit.org/show_bug.cgi?id=162465). Both issues are probably related to the title being so long.
