### ISSUE TITLE
Bodhi should e-mail crash tracebacks to admins

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#969]
Debugging would be aided by adding some code to Bodhi that sends tracebacks to admins. Here are a few requirements:
1. We need count/rate limiting, so nobody gets 1,000 e-mails in their inbox.
2. The list of e-mail addresses should be a setting.
3. We should set this up for both the web interface and the masher.

**Comment by puiterwijk** [comment]
1. The default configuration value should be an empty list.
2. Bodhi should ALSO log everything to the standard logs (apache for front, journal for mash).

**Comment by bowlofeggs** [comment]
I'm marking this as critical priority because the crash e-mails we currently get come from fedmsg-hub, and with Bodhi 4 we will no longer have fedmsg-hub. Thus, we will have a feature regression if we don't implement this in time for Bodhi 4.

**Comment by bowlofeggs** [comment]
According to the note at https://docs.python.org/3.7/library/logging.config.html#configuration-file-format we cannot use filters with the logging config file format in Python and have to use the DictConfig format if we want that functionality. This is a bit unfortunate, as it's one more backwards incompatible change if we decide to go that route. I had planned on using a filter to rate limit the e-mails so we don't get too many.

Perhaps another option is to provide a RateLimitedSMTPHandler object that users can use that subclasses SMTPHandler, but it does feel like the filter is the more natural fit here.

**Comment by bowlofeggs** [comment]
I have submitted a package review for a pyramid plugin that allows us to use a DictConfig file:

https://bugzilla.redhat.com/show_bug.cgi?id=1702451

This would actually not be a formal dependency of Bodhi's since it's something you set up in the Bodhi config file, but I will probably document it as a suggested way to achieve rate limited e-mail log handling.

**Comment by bowlofeggs** [comment]
This change is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
