### ISSUE TITLE
Bodhi and Koji out of sync

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#978]
The update https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-bcda96018d is out of sync with the tags in koji. According to bodhi the update is "Pending", i.e. not yet pushed to testing, but according to koji, bodhi has already pushed the update to testing:

```
$ koji list-history --build globus-gssapi-gsi-12.9-1.el5
Sat Sep 24 15:55:54 2016 globus-gssapi-gsi-12.9-1.el5 tagged into dist-5E-epel-testing-candidate by ellert
Sat Sep 24 16:40:51 2016 globus-gssapi-gsi-12.9-1.el5 tagged into dist-5E-epel-override by bodhi [still active]
Sun Sep 25 05:53:40 2016 globus-gssapi-gsi-12.9-1.el5 untagged from dist-5E-epel-testing-candidate by bodhi
Sun Sep 25 05:53:40 2016 globus-gssapi-gsi-12.9-1.el5 tagged into dist-5E-epel-testing by bodhi [still active]
```

**Comment by puiterwijk** [comment]
Sorry about that, that was caused by a bug in bodhi that has now been fixed.
I will make sure that releng fixes the tags on your build so that it will go out with the next epel5 push.

**Comment by puiterwijk** [comment]
This tag has now been fixed. Sorry for the issues.
