### ISSUE TITLE
Bodhi does not modify BZ ticket after updates submission

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#979]
I just submitted update into Bodhi [1]. However, this action does not switch the BZ ticket into MODIFIED state as it used to do. It seems that Bodhi knows there is some issue, since next to the BZ ticket number, there is stripe of blinking dots.

However, it seems that Bodhi updates the ticket as soon as the package is pushed into testing repository, e.g. this [2] is update from yesterday (although now I see that there is also stripe of blinking dots, so something is wrong with it as well ...).

[1] https://bodhi.fedoraproject.org/updates/FEDORA-2016-d783e0ef27
[2] https://bodhi.fedoraproject.org/updates/FEDORA-2016-2bef97338c

**Comment by voxik** [comment]
BTW I received the FMN notification just fine ....

**Comment by bowlofeggs** [comment]
I see what you mean. It does seem to be moving it to ON_QA still, so at least that part still works. Hopefully it will also close the bug correctly. Thanks for the report. I wonder if the "blinking dots" are a hint about what's going wrong…

**Comment by bowlofeggs** [comment]
I also experienced this today with an update I submitted for python-zope-sqlalchemy. It happened on all the distro versions, for example https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-a60a15d9ac

**Comment by pnemade** [comment]
same experienced by me just now. Update submitted but no notification to added bugzilla.

**Comment by bowlofeggs** [comment]
@puiterwijk believes this is due to the bodhi frontend and backend having a disruption in message passing over fedmsg, causing the backend not to process new updates as they are submitted.

**Comment by AdamWill** [comment]
@bowlofeggs thinks this may also be why Bodhi appears to not be up-to-date on finding test cases for packages from the wiki: it seems to be using a mapping from at least before 2015-08-22, as anaconda updates are listing https://fedoraproject.org/wiki/User:Pschindl/Draft/Testcase_Custom_partitioning , which was removed from `Category:Package_anaconda_test_cases` on that date.

**Comment by bowlofeggs** [comment]
I believe this is fixed now. It seems that there was a deployment issue that prevented bodhi's frontend and backend from communicating. @puiterwijk has resolved this for us!
