### ISSUE TITLE
bodhi's server package doesn't build with setuptools 28.0

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#994]
setuptools 28.0 made a change that causes an exclusion on a package to also exclude all subpackages:

https://github.com/pypa/setuptools/pull/733

Unfortunately, bodhi's setup.py was relying on the previous behavior to exclude the bodhi package (i.e., the bodhi/**init**.py, which belongs to the common package) and now the setup.py is not installing the server's code anymore.

We will need to find a way to work around this change that works in both the new and old setuptool versions.

**Comment by bowlofeggs** [comment]
It seems that the 28.0 release of setuptools also changes the behaviour of the `include` argument such that it will not include subpackages if their superpackages are not also part of the include list. Though I could just not use `find_packages()` for Bodhi, I'd prefer to keep using if I can so that any future new packages automatically get included. Thus, I think I will just use something like:

```
server_packages = find_packages(include=['bodhi', 'bodhi.server', 'bodhi.server.*'])
server_packages.remove('bodhi')
```

**Comment by bowlofeggs** [comment]
Well I went with the approach I mentioned in my most recent comment, and it turns out that the version of setuptools in EPEL 7 doesn't have the `include` argument for `find_packages`:

```
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    server_packages = find_packages(include=['bodhi', 'bodhi.server', 'bodhi.server.*'])
TypeError: find_packages() got an unexpected keyword argument 'include'
```

Thus, we need a solution that does not use include.

**Comment by tehsmyers** [comment]
I suggest nested list comprehensions with `filter` and globbing.

:D
