### ISSUE TITLE
Display whether autopush is enabled or disabled on the Update page

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#999]
With the 2.2.0 release, all updates have karma thresholds displayed, whether or not autopush is enabled. Users are used to looking for the karma levels to decipher whether an update is set to autopush or not, and so users seem to be confused about whether updates autopush.

I propose that we display on the update page whether autopush is or is not enabled so that it is clear what should be expected of Bodhi when karma is given.

**Comment by trishnaguha** [comment]
This would be a nice feature to have.
